import { AssociateAdminAccountCommandInput, AssociateAdminAccountCommandOutput } from "../commands/AssociateAdminAccountCommand";
import { DeleteNotificationChannelCommandInput, DeleteNotificationChannelCommandOutput } from "../commands/DeleteNotificationChannelCommand";
import { DeletePolicyCommandInput, DeletePolicyCommandOutput } from "../commands/DeletePolicyCommand";
import { DisassociateAdminAccountCommandInput, DisassociateAdminAccountCommandOutput } from "../commands/DisassociateAdminAccountCommand";
import { GetAdminAccountCommandInput, GetAdminAccountCommandOutput } from "../commands/GetAdminAccountCommand";
import { GetComplianceDetailCommandInput, GetComplianceDetailCommandOutput } from "../commands/GetComplianceDetailCommand";
import { GetNotificationChannelCommandInput, GetNotificationChannelCommandOutput } from "../commands/GetNotificationChannelCommand";
import { GetPolicyCommandInput, GetPolicyCommandOutput } from "../commands/GetPolicyCommand";
import { GetProtectionStatusCommandInput, GetProtectionStatusCommandOutput } from "../commands/GetProtectionStatusCommand";
import { ListComplianceStatusCommandInput, ListComplianceStatusCommandOutput } from "../commands/ListComplianceStatusCommand";
import { ListMemberAccountsCommandInput, ListMemberAccountsCommandOutput } from "../commands/ListMemberAccountsCommand";
import { ListPoliciesCommandInput, ListPoliciesCommandOutput } from "../commands/ListPoliciesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { PutNotificationChannelCommandInput, PutNotificationChannelCommandOutput } from "../commands/PutNotificationChannelCommand";
import { PutPolicyCommandInput, PutPolicyCommandOutput } from "../commands/PutPolicyCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateAdminAccountCommand(input: AssociateAdminAccountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteNotificationChannelCommand(input: DeleteNotificationChannelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePolicyCommand(input: DeletePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateAdminAccountCommand(input: DisassociateAdminAccountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAdminAccountCommand(input: GetAdminAccountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetComplianceDetailCommand(input: GetComplianceDetailCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetNotificationChannelCommand(input: GetNotificationChannelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPolicyCommand(input: GetPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetProtectionStatusCommand(input: GetProtectionStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListComplianceStatusCommand(input: ListComplianceStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListMemberAccountsCommand(input: ListMemberAccountsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPoliciesCommand(input: ListPoliciesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutNotificationChannelCommand(input: PutNotificationChannelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutPolicyCommand(input: PutPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateAdminAccountCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateAdminAccountCommandOutput>;
export declare function deserializeAws_json1_1DeleteNotificationChannelCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteNotificationChannelCommandOutput>;
export declare function deserializeAws_json1_1DeletePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePolicyCommandOutput>;
export declare function deserializeAws_json1_1DisassociateAdminAccountCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateAdminAccountCommandOutput>;
export declare function deserializeAws_json1_1GetAdminAccountCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAdminAccountCommandOutput>;
export declare function deserializeAws_json1_1GetComplianceDetailCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetComplianceDetailCommandOutput>;
export declare function deserializeAws_json1_1GetNotificationChannelCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetNotificationChannelCommandOutput>;
export declare function deserializeAws_json1_1GetPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPolicyCommandOutput>;
export declare function deserializeAws_json1_1GetProtectionStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetProtectionStatusCommandOutput>;
export declare function deserializeAws_json1_1ListComplianceStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListComplianceStatusCommandOutput>;
export declare function deserializeAws_json1_1ListMemberAccountsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListMemberAccountsCommandOutput>;
export declare function deserializeAws_json1_1ListPoliciesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPoliciesCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1PutNotificationChannelCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutNotificationChannelCommandOutput>;
export declare function deserializeAws_json1_1PutPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutPolicyCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
