import { AllocateStaticIpCommandInput, AllocateStaticIpCommandOutput } from "../commands/AllocateStaticIpCommand";
import { AttachDiskCommandInput, AttachDiskCommandOutput } from "../commands/AttachDiskCommand";
import { AttachInstancesToLoadBalancerCommandInput, AttachInstancesToLoadBalancerCommandOutput } from "../commands/AttachInstancesToLoadBalancerCommand";
import { AttachLoadBalancerTlsCertificateCommandInput, AttachLoadBalancerTlsCertificateCommandOutput } from "../commands/AttachLoadBalancerTlsCertificateCommand";
import { AttachStaticIpCommandInput, AttachStaticIpCommandOutput } from "../commands/AttachStaticIpCommand";
import { CloseInstancePublicPortsCommandInput, CloseInstancePublicPortsCommandOutput } from "../commands/CloseInstancePublicPortsCommand";
import { CopySnapshotCommandInput, CopySnapshotCommandOutput } from "../commands/CopySnapshotCommand";
import { CreateCloudFormationStackCommandInput, CreateCloudFormationStackCommandOutput } from "../commands/CreateCloudFormationStackCommand";
import { CreateDiskCommandInput, CreateDiskCommandOutput } from "../commands/CreateDiskCommand";
import { CreateDiskFromSnapshotCommandInput, CreateDiskFromSnapshotCommandOutput } from "../commands/CreateDiskFromSnapshotCommand";
import { CreateDiskSnapshotCommandInput, CreateDiskSnapshotCommandOutput } from "../commands/CreateDiskSnapshotCommand";
import { CreateDomainCommandInput, CreateDomainCommandOutput } from "../commands/CreateDomainCommand";
import { CreateDomainEntryCommandInput, CreateDomainEntryCommandOutput } from "../commands/CreateDomainEntryCommand";
import { CreateInstanceSnapshotCommandInput, CreateInstanceSnapshotCommandOutput } from "../commands/CreateInstanceSnapshotCommand";
import { CreateInstancesCommandInput, CreateInstancesCommandOutput } from "../commands/CreateInstancesCommand";
import { CreateInstancesFromSnapshotCommandInput, CreateInstancesFromSnapshotCommandOutput } from "../commands/CreateInstancesFromSnapshotCommand";
import { CreateKeyPairCommandInput, CreateKeyPairCommandOutput } from "../commands/CreateKeyPairCommand";
import { CreateLoadBalancerCommandInput, CreateLoadBalancerCommandOutput } from "../commands/CreateLoadBalancerCommand";
import { CreateLoadBalancerTlsCertificateCommandInput, CreateLoadBalancerTlsCertificateCommandOutput } from "../commands/CreateLoadBalancerTlsCertificateCommand";
import { CreateRelationalDatabaseCommandInput, CreateRelationalDatabaseCommandOutput } from "../commands/CreateRelationalDatabaseCommand";
import { CreateRelationalDatabaseFromSnapshotCommandInput, CreateRelationalDatabaseFromSnapshotCommandOutput } from "../commands/CreateRelationalDatabaseFromSnapshotCommand";
import { CreateRelationalDatabaseSnapshotCommandInput, CreateRelationalDatabaseSnapshotCommandOutput } from "../commands/CreateRelationalDatabaseSnapshotCommand";
import { DeleteAutoSnapshotCommandInput, DeleteAutoSnapshotCommandOutput } from "../commands/DeleteAutoSnapshotCommand";
import { DeleteDiskCommandInput, DeleteDiskCommandOutput } from "../commands/DeleteDiskCommand";
import { DeleteDiskSnapshotCommandInput, DeleteDiskSnapshotCommandOutput } from "../commands/DeleteDiskSnapshotCommand";
import { DeleteDomainCommandInput, DeleteDomainCommandOutput } from "../commands/DeleteDomainCommand";
import { DeleteDomainEntryCommandInput, DeleteDomainEntryCommandOutput } from "../commands/DeleteDomainEntryCommand";
import { DeleteInstanceCommandInput, DeleteInstanceCommandOutput } from "../commands/DeleteInstanceCommand";
import { DeleteInstanceSnapshotCommandInput, DeleteInstanceSnapshotCommandOutput } from "../commands/DeleteInstanceSnapshotCommand";
import { DeleteKeyPairCommandInput, DeleteKeyPairCommandOutput } from "../commands/DeleteKeyPairCommand";
import { DeleteKnownHostKeysCommandInput, DeleteKnownHostKeysCommandOutput } from "../commands/DeleteKnownHostKeysCommand";
import { DeleteLoadBalancerCommandInput, DeleteLoadBalancerCommandOutput } from "../commands/DeleteLoadBalancerCommand";
import { DeleteLoadBalancerTlsCertificateCommandInput, DeleteLoadBalancerTlsCertificateCommandOutput } from "../commands/DeleteLoadBalancerTlsCertificateCommand";
import { DeleteRelationalDatabaseCommandInput, DeleteRelationalDatabaseCommandOutput } from "../commands/DeleteRelationalDatabaseCommand";
import { DeleteRelationalDatabaseSnapshotCommandInput, DeleteRelationalDatabaseSnapshotCommandOutput } from "../commands/DeleteRelationalDatabaseSnapshotCommand";
import { DetachDiskCommandInput, DetachDiskCommandOutput } from "../commands/DetachDiskCommand";
import { DetachInstancesFromLoadBalancerCommandInput, DetachInstancesFromLoadBalancerCommandOutput } from "../commands/DetachInstancesFromLoadBalancerCommand";
import { DetachStaticIpCommandInput, DetachStaticIpCommandOutput } from "../commands/DetachStaticIpCommand";
import { DisableAddOnCommandInput, DisableAddOnCommandOutput } from "../commands/DisableAddOnCommand";
import { DownloadDefaultKeyPairCommandInput, DownloadDefaultKeyPairCommandOutput } from "../commands/DownloadDefaultKeyPairCommand";
import { EnableAddOnCommandInput, EnableAddOnCommandOutput } from "../commands/EnableAddOnCommand";
import { ExportSnapshotCommandInput, ExportSnapshotCommandOutput } from "../commands/ExportSnapshotCommand";
import { GetActiveNamesCommandInput, GetActiveNamesCommandOutput } from "../commands/GetActiveNamesCommand";
import { GetAutoSnapshotsCommandInput, GetAutoSnapshotsCommandOutput } from "../commands/GetAutoSnapshotsCommand";
import { GetBlueprintsCommandInput, GetBlueprintsCommandOutput } from "../commands/GetBlueprintsCommand";
import { GetBundlesCommandInput, GetBundlesCommandOutput } from "../commands/GetBundlesCommand";
import { GetCloudFormationStackRecordsCommandInput, GetCloudFormationStackRecordsCommandOutput } from "../commands/GetCloudFormationStackRecordsCommand";
import { GetDiskCommandInput, GetDiskCommandOutput } from "../commands/GetDiskCommand";
import { GetDiskSnapshotCommandInput, GetDiskSnapshotCommandOutput } from "../commands/GetDiskSnapshotCommand";
import { GetDiskSnapshotsCommandInput, GetDiskSnapshotsCommandOutput } from "../commands/GetDiskSnapshotsCommand";
import { GetDisksCommandInput, GetDisksCommandOutput } from "../commands/GetDisksCommand";
import { GetDomainCommandInput, GetDomainCommandOutput } from "../commands/GetDomainCommand";
import { GetDomainsCommandInput, GetDomainsCommandOutput } from "../commands/GetDomainsCommand";
import { GetExportSnapshotRecordsCommandInput, GetExportSnapshotRecordsCommandOutput } from "../commands/GetExportSnapshotRecordsCommand";
import { GetInstanceAccessDetailsCommandInput, GetInstanceAccessDetailsCommandOutput } from "../commands/GetInstanceAccessDetailsCommand";
import { GetInstanceCommandInput, GetInstanceCommandOutput } from "../commands/GetInstanceCommand";
import { GetInstanceMetricDataCommandInput, GetInstanceMetricDataCommandOutput } from "../commands/GetInstanceMetricDataCommand";
import { GetInstancePortStatesCommandInput, GetInstancePortStatesCommandOutput } from "../commands/GetInstancePortStatesCommand";
import { GetInstanceSnapshotCommandInput, GetInstanceSnapshotCommandOutput } from "../commands/GetInstanceSnapshotCommand";
import { GetInstanceSnapshotsCommandInput, GetInstanceSnapshotsCommandOutput } from "../commands/GetInstanceSnapshotsCommand";
import { GetInstanceStateCommandInput, GetInstanceStateCommandOutput } from "../commands/GetInstanceStateCommand";
import { GetInstancesCommandInput, GetInstancesCommandOutput } from "../commands/GetInstancesCommand";
import { GetKeyPairCommandInput, GetKeyPairCommandOutput } from "../commands/GetKeyPairCommand";
import { GetKeyPairsCommandInput, GetKeyPairsCommandOutput } from "../commands/GetKeyPairsCommand";
import { GetLoadBalancerCommandInput, GetLoadBalancerCommandOutput } from "../commands/GetLoadBalancerCommand";
import { GetLoadBalancerMetricDataCommandInput, GetLoadBalancerMetricDataCommandOutput } from "../commands/GetLoadBalancerMetricDataCommand";
import { GetLoadBalancerTlsCertificatesCommandInput, GetLoadBalancerTlsCertificatesCommandOutput } from "../commands/GetLoadBalancerTlsCertificatesCommand";
import { GetLoadBalancersCommandInput, GetLoadBalancersCommandOutput } from "../commands/GetLoadBalancersCommand";
import { GetOperationCommandInput, GetOperationCommandOutput } from "../commands/GetOperationCommand";
import { GetOperationsCommandInput, GetOperationsCommandOutput } from "../commands/GetOperationsCommand";
import { GetOperationsForResourceCommandInput, GetOperationsForResourceCommandOutput } from "../commands/GetOperationsForResourceCommand";
import { GetRegionsCommandInput, GetRegionsCommandOutput } from "../commands/GetRegionsCommand";
import { GetRelationalDatabaseBlueprintsCommandInput, GetRelationalDatabaseBlueprintsCommandOutput } from "../commands/GetRelationalDatabaseBlueprintsCommand";
import { GetRelationalDatabaseBundlesCommandInput, GetRelationalDatabaseBundlesCommandOutput } from "../commands/GetRelationalDatabaseBundlesCommand";
import { GetRelationalDatabaseCommandInput, GetRelationalDatabaseCommandOutput } from "../commands/GetRelationalDatabaseCommand";
import { GetRelationalDatabaseEventsCommandInput, GetRelationalDatabaseEventsCommandOutput } from "../commands/GetRelationalDatabaseEventsCommand";
import { GetRelationalDatabaseLogEventsCommandInput, GetRelationalDatabaseLogEventsCommandOutput } from "../commands/GetRelationalDatabaseLogEventsCommand";
import { GetRelationalDatabaseLogStreamsCommandInput, GetRelationalDatabaseLogStreamsCommandOutput } from "../commands/GetRelationalDatabaseLogStreamsCommand";
import { GetRelationalDatabaseMasterUserPasswordCommandInput, GetRelationalDatabaseMasterUserPasswordCommandOutput } from "../commands/GetRelationalDatabaseMasterUserPasswordCommand";
import { GetRelationalDatabaseMetricDataCommandInput, GetRelationalDatabaseMetricDataCommandOutput } from "../commands/GetRelationalDatabaseMetricDataCommand";
import { GetRelationalDatabaseParametersCommandInput, GetRelationalDatabaseParametersCommandOutput } from "../commands/GetRelationalDatabaseParametersCommand";
import { GetRelationalDatabaseSnapshotCommandInput, GetRelationalDatabaseSnapshotCommandOutput } from "../commands/GetRelationalDatabaseSnapshotCommand";
import { GetRelationalDatabaseSnapshotsCommandInput, GetRelationalDatabaseSnapshotsCommandOutput } from "../commands/GetRelationalDatabaseSnapshotsCommand";
import { GetRelationalDatabasesCommandInput, GetRelationalDatabasesCommandOutput } from "../commands/GetRelationalDatabasesCommand";
import { GetStaticIpCommandInput, GetStaticIpCommandOutput } from "../commands/GetStaticIpCommand";
import { GetStaticIpsCommandInput, GetStaticIpsCommandOutput } from "../commands/GetStaticIpsCommand";
import { ImportKeyPairCommandInput, ImportKeyPairCommandOutput } from "../commands/ImportKeyPairCommand";
import { IsVpcPeeredCommandInput, IsVpcPeeredCommandOutput } from "../commands/IsVpcPeeredCommand";
import { OpenInstancePublicPortsCommandInput, OpenInstancePublicPortsCommandOutput } from "../commands/OpenInstancePublicPortsCommand";
import { PeerVpcCommandInput, PeerVpcCommandOutput } from "../commands/PeerVpcCommand";
import { PutInstancePublicPortsCommandInput, PutInstancePublicPortsCommandOutput } from "../commands/PutInstancePublicPortsCommand";
import { RebootInstanceCommandInput, RebootInstanceCommandOutput } from "../commands/RebootInstanceCommand";
import { RebootRelationalDatabaseCommandInput, RebootRelationalDatabaseCommandOutput } from "../commands/RebootRelationalDatabaseCommand";
import { ReleaseStaticIpCommandInput, ReleaseStaticIpCommandOutput } from "../commands/ReleaseStaticIpCommand";
import { StartInstanceCommandInput, StartInstanceCommandOutput } from "../commands/StartInstanceCommand";
import { StartRelationalDatabaseCommandInput, StartRelationalDatabaseCommandOutput } from "../commands/StartRelationalDatabaseCommand";
import { StopInstanceCommandInput, StopInstanceCommandOutput } from "../commands/StopInstanceCommand";
import { StopRelationalDatabaseCommandInput, StopRelationalDatabaseCommandOutput } from "../commands/StopRelationalDatabaseCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UnpeerVpcCommandInput, UnpeerVpcCommandOutput } from "../commands/UnpeerVpcCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateDomainEntryCommandInput, UpdateDomainEntryCommandOutput } from "../commands/UpdateDomainEntryCommand";
import { UpdateLoadBalancerAttributeCommandInput, UpdateLoadBalancerAttributeCommandOutput } from "../commands/UpdateLoadBalancerAttributeCommand";
import { UpdateRelationalDatabaseCommandInput, UpdateRelationalDatabaseCommandOutput } from "../commands/UpdateRelationalDatabaseCommand";
import { UpdateRelationalDatabaseParametersCommandInput, UpdateRelationalDatabaseParametersCommandOutput } from "../commands/UpdateRelationalDatabaseParametersCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AllocateStaticIpCommand(input: AllocateStaticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachDiskCommand(input: AttachDiskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachInstancesToLoadBalancerCommand(input: AttachInstancesToLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachLoadBalancerTlsCertificateCommand(input: AttachLoadBalancerTlsCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachStaticIpCommand(input: AttachStaticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CloseInstancePublicPortsCommand(input: CloseInstancePublicPortsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CopySnapshotCommand(input: CopySnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateCloudFormationStackCommand(input: CreateCloudFormationStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDiskCommand(input: CreateDiskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDiskFromSnapshotCommand(input: CreateDiskFromSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDiskSnapshotCommand(input: CreateDiskSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDomainCommand(input: CreateDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDomainEntryCommand(input: CreateDomainEntryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInstanceSnapshotCommand(input: CreateInstanceSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInstancesCommand(input: CreateInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInstancesFromSnapshotCommand(input: CreateInstancesFromSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateKeyPairCommand(input: CreateKeyPairCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateLoadBalancerCommand(input: CreateLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateLoadBalancerTlsCertificateCommand(input: CreateLoadBalancerTlsCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRelationalDatabaseCommand(input: CreateRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRelationalDatabaseFromSnapshotCommand(input: CreateRelationalDatabaseFromSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRelationalDatabaseSnapshotCommand(input: CreateRelationalDatabaseSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAutoSnapshotCommand(input: DeleteAutoSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDiskCommand(input: DeleteDiskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDiskSnapshotCommand(input: DeleteDiskSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDomainCommand(input: DeleteDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDomainEntryCommand(input: DeleteDomainEntryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInstanceCommand(input: DeleteInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInstanceSnapshotCommand(input: DeleteInstanceSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteKeyPairCommand(input: DeleteKeyPairCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteKnownHostKeysCommand(input: DeleteKnownHostKeysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLoadBalancerCommand(input: DeleteLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLoadBalancerTlsCertificateCommand(input: DeleteLoadBalancerTlsCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRelationalDatabaseCommand(input: DeleteRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRelationalDatabaseSnapshotCommand(input: DeleteRelationalDatabaseSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DetachDiskCommand(input: DetachDiskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DetachInstancesFromLoadBalancerCommand(input: DetachInstancesFromLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DetachStaticIpCommand(input: DetachStaticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisableAddOnCommand(input: DisableAddOnCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DownloadDefaultKeyPairCommand(input: DownloadDefaultKeyPairCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1EnableAddOnCommand(input: EnableAddOnCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ExportSnapshotCommand(input: ExportSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetActiveNamesCommand(input: GetActiveNamesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAutoSnapshotsCommand(input: GetAutoSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetBlueprintsCommand(input: GetBlueprintsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetBundlesCommand(input: GetBundlesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCloudFormationStackRecordsCommand(input: GetCloudFormationStackRecordsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDiskCommand(input: GetDiskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDiskSnapshotCommand(input: GetDiskSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDiskSnapshotsCommand(input: GetDiskSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDisksCommand(input: GetDisksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDomainCommand(input: GetDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDomainsCommand(input: GetDomainsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetExportSnapshotRecordsCommand(input: GetExportSnapshotRecordsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceCommand(input: GetInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceAccessDetailsCommand(input: GetInstanceAccessDetailsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceMetricDataCommand(input: GetInstanceMetricDataCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstancePortStatesCommand(input: GetInstancePortStatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceSnapshotCommand(input: GetInstanceSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceSnapshotsCommand(input: GetInstanceSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceStateCommand(input: GetInstanceStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstancesCommand(input: GetInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetKeyPairCommand(input: GetKeyPairCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetKeyPairsCommand(input: GetKeyPairsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoadBalancerCommand(input: GetLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoadBalancerMetricDataCommand(input: GetLoadBalancerMetricDataCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoadBalancerTlsCertificatesCommand(input: GetLoadBalancerTlsCertificatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoadBalancersCommand(input: GetLoadBalancersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOperationCommand(input: GetOperationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOperationsCommand(input: GetOperationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOperationsForResourceCommand(input: GetOperationsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRegionsCommand(input: GetRegionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseCommand(input: GetRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseBlueprintsCommand(input: GetRelationalDatabaseBlueprintsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseBundlesCommand(input: GetRelationalDatabaseBundlesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseEventsCommand(input: GetRelationalDatabaseEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseLogEventsCommand(input: GetRelationalDatabaseLogEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseLogStreamsCommand(input: GetRelationalDatabaseLogStreamsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseMasterUserPasswordCommand(input: GetRelationalDatabaseMasterUserPasswordCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseMetricDataCommand(input: GetRelationalDatabaseMetricDataCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseParametersCommand(input: GetRelationalDatabaseParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseSnapshotCommand(input: GetRelationalDatabaseSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabaseSnapshotsCommand(input: GetRelationalDatabaseSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRelationalDatabasesCommand(input: GetRelationalDatabasesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetStaticIpCommand(input: GetStaticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetStaticIpsCommand(input: GetStaticIpsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ImportKeyPairCommand(input: ImportKeyPairCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1IsVpcPeeredCommand(input: IsVpcPeeredCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1OpenInstancePublicPortsCommand(input: OpenInstancePublicPortsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PeerVpcCommand(input: PeerVpcCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutInstancePublicPortsCommand(input: PutInstancePublicPortsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebootInstanceCommand(input: RebootInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebootRelationalDatabaseCommand(input: RebootRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ReleaseStaticIpCommand(input: ReleaseStaticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartInstanceCommand(input: StartInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartRelationalDatabaseCommand(input: StartRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopInstanceCommand(input: StopInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopRelationalDatabaseCommand(input: StopRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UnpeerVpcCommand(input: UnpeerVpcCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDomainEntryCommand(input: UpdateDomainEntryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateLoadBalancerAttributeCommand(input: UpdateLoadBalancerAttributeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRelationalDatabaseCommand(input: UpdateRelationalDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRelationalDatabaseParametersCommand(input: UpdateRelationalDatabaseParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AllocateStaticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocateStaticIpCommandOutput>;
export declare function deserializeAws_json1_1AttachDiskCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachDiskCommandOutput>;
export declare function deserializeAws_json1_1AttachInstancesToLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachInstancesToLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1AttachLoadBalancerTlsCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachLoadBalancerTlsCertificateCommandOutput>;
export declare function deserializeAws_json1_1AttachStaticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachStaticIpCommandOutput>;
export declare function deserializeAws_json1_1CloseInstancePublicPortsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CloseInstancePublicPortsCommandOutput>;
export declare function deserializeAws_json1_1CopySnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CopySnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateCloudFormationStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCloudFormationStackCommandOutput>;
export declare function deserializeAws_json1_1CreateDiskCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDiskCommandOutput>;
export declare function deserializeAws_json1_1CreateDiskFromSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDiskFromSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateDiskSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDiskSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDomainCommandOutput>;
export declare function deserializeAws_json1_1CreateDomainEntryCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDomainEntryCommandOutput>;
export declare function deserializeAws_json1_1CreateInstanceSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInstanceSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInstancesCommandOutput>;
export declare function deserializeAws_json1_1CreateInstancesFromSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInstancesFromSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateKeyPairCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateKeyPairCommandOutput>;
export declare function deserializeAws_json1_1CreateLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1CreateLoadBalancerTlsCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateLoadBalancerTlsCertificateCommandOutput>;
export declare function deserializeAws_json1_1CreateRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1CreateRelationalDatabaseFromSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRelationalDatabaseFromSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateRelationalDatabaseSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRelationalDatabaseSnapshotCommandOutput>;
export declare function deserializeAws_json1_1DeleteAutoSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAutoSnapshotCommandOutput>;
export declare function deserializeAws_json1_1DeleteDiskCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDiskCommandOutput>;
export declare function deserializeAws_json1_1DeleteDiskSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDiskSnapshotCommandOutput>;
export declare function deserializeAws_json1_1DeleteDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDomainCommandOutput>;
export declare function deserializeAws_json1_1DeleteDomainEntryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDomainEntryCommandOutput>;
export declare function deserializeAws_json1_1DeleteInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInstanceCommandOutput>;
export declare function deserializeAws_json1_1DeleteInstanceSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInstanceSnapshotCommandOutput>;
export declare function deserializeAws_json1_1DeleteKeyPairCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteKeyPairCommandOutput>;
export declare function deserializeAws_json1_1DeleteKnownHostKeysCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteKnownHostKeysCommandOutput>;
export declare function deserializeAws_json1_1DeleteLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1DeleteLoadBalancerTlsCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLoadBalancerTlsCertificateCommandOutput>;
export declare function deserializeAws_json1_1DeleteRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1DeleteRelationalDatabaseSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRelationalDatabaseSnapshotCommandOutput>;
export declare function deserializeAws_json1_1DetachDiskCommand(output: __HttpResponse, context: __SerdeContext): Promise<DetachDiskCommandOutput>;
export declare function deserializeAws_json1_1DetachInstancesFromLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DetachInstancesFromLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1DetachStaticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<DetachStaticIpCommandOutput>;
export declare function deserializeAws_json1_1DisableAddOnCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableAddOnCommandOutput>;
export declare function deserializeAws_json1_1DownloadDefaultKeyPairCommand(output: __HttpResponse, context: __SerdeContext): Promise<DownloadDefaultKeyPairCommandOutput>;
export declare function deserializeAws_json1_1EnableAddOnCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableAddOnCommandOutput>;
export declare function deserializeAws_json1_1ExportSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<ExportSnapshotCommandOutput>;
export declare function deserializeAws_json1_1GetActiveNamesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetActiveNamesCommandOutput>;
export declare function deserializeAws_json1_1GetAutoSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAutoSnapshotsCommandOutput>;
export declare function deserializeAws_json1_1GetBlueprintsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetBlueprintsCommandOutput>;
export declare function deserializeAws_json1_1GetBundlesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetBundlesCommandOutput>;
export declare function deserializeAws_json1_1GetCloudFormationStackRecordsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCloudFormationStackRecordsCommandOutput>;
export declare function deserializeAws_json1_1GetDiskCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDiskCommandOutput>;
export declare function deserializeAws_json1_1GetDiskSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDiskSnapshotCommandOutput>;
export declare function deserializeAws_json1_1GetDiskSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDiskSnapshotsCommandOutput>;
export declare function deserializeAws_json1_1GetDisksCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDisksCommandOutput>;
export declare function deserializeAws_json1_1GetDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDomainCommandOutput>;
export declare function deserializeAws_json1_1GetDomainsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDomainsCommandOutput>;
export declare function deserializeAws_json1_1GetExportSnapshotRecordsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetExportSnapshotRecordsCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceAccessDetailsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceAccessDetailsCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceMetricDataCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceMetricDataCommandOutput>;
export declare function deserializeAws_json1_1GetInstancePortStatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstancePortStatesCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceSnapshotCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceSnapshotsCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceStateCommandOutput>;
export declare function deserializeAws_json1_1GetInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstancesCommandOutput>;
export declare function deserializeAws_json1_1GetKeyPairCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetKeyPairCommandOutput>;
export declare function deserializeAws_json1_1GetKeyPairsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetKeyPairsCommandOutput>;
export declare function deserializeAws_json1_1GetLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1GetLoadBalancerMetricDataCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoadBalancerMetricDataCommandOutput>;
export declare function deserializeAws_json1_1GetLoadBalancerTlsCertificatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoadBalancerTlsCertificatesCommandOutput>;
export declare function deserializeAws_json1_1GetLoadBalancersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoadBalancersCommandOutput>;
export declare function deserializeAws_json1_1GetOperationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOperationCommandOutput>;
export declare function deserializeAws_json1_1GetOperationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOperationsCommandOutput>;
export declare function deserializeAws_json1_1GetOperationsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOperationsForResourceCommandOutput>;
export declare function deserializeAws_json1_1GetRegionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRegionsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseBlueprintsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseBlueprintsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseBundlesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseBundlesCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseEventsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseLogEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseLogEventsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseLogStreamsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseLogStreamsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseMasterUserPasswordCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseMasterUserPasswordCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseMetricDataCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseMetricDataCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseParametersCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseSnapshotCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabaseSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabaseSnapshotsCommandOutput>;
export declare function deserializeAws_json1_1GetRelationalDatabasesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRelationalDatabasesCommandOutput>;
export declare function deserializeAws_json1_1GetStaticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetStaticIpCommandOutput>;
export declare function deserializeAws_json1_1GetStaticIpsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetStaticIpsCommandOutput>;
export declare function deserializeAws_json1_1ImportKeyPairCommand(output: __HttpResponse, context: __SerdeContext): Promise<ImportKeyPairCommandOutput>;
export declare function deserializeAws_json1_1IsVpcPeeredCommand(output: __HttpResponse, context: __SerdeContext): Promise<IsVpcPeeredCommandOutput>;
export declare function deserializeAws_json1_1OpenInstancePublicPortsCommand(output: __HttpResponse, context: __SerdeContext): Promise<OpenInstancePublicPortsCommandOutput>;
export declare function deserializeAws_json1_1PeerVpcCommand(output: __HttpResponse, context: __SerdeContext): Promise<PeerVpcCommandOutput>;
export declare function deserializeAws_json1_1PutInstancePublicPortsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutInstancePublicPortsCommandOutput>;
export declare function deserializeAws_json1_1RebootInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootInstanceCommandOutput>;
export declare function deserializeAws_json1_1RebootRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1ReleaseStaticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<ReleaseStaticIpCommandOutput>;
export declare function deserializeAws_json1_1StartInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartInstanceCommandOutput>;
export declare function deserializeAws_json1_1StartRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1StopInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopInstanceCommandOutput>;
export declare function deserializeAws_json1_1StopRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UnpeerVpcCommand(output: __HttpResponse, context: __SerdeContext): Promise<UnpeerVpcCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateDomainEntryCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDomainEntryCommandOutput>;
export declare function deserializeAws_json1_1UpdateLoadBalancerAttributeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateLoadBalancerAttributeCommandOutput>;
export declare function deserializeAws_json1_1UpdateRelationalDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRelationalDatabaseCommandOutput>;
export declare function deserializeAws_json1_1UpdateRelationalDatabaseParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRelationalDatabaseParametersCommandOutput>;
