import { ReservedDBInstancesOfferingNotFoundFault } from "./ReservedDBInstancesOfferingNotFoundFault";
export type DescribeReservedDBInstancesOfferingsExceptionsUnion = ReservedDBInstancesOfferingNotFoundFault;
