import { AddTagsToResourceCommandInput, AddTagsToResourceCommandOutput } from "../commands/AddTagsToResourceCommand";
import { CancelCommandCommandInput, CancelCommandCommandOutput } from "../commands/CancelCommandCommand";
import { CancelMaintenanceWindowExecutionCommandInput, CancelMaintenanceWindowExecutionCommandOutput } from "../commands/CancelMaintenanceWindowExecutionCommand";
import { CreateActivationCommandInput, CreateActivationCommandOutput } from "../commands/CreateActivationCommand";
import { CreateAssociationBatchCommandInput, CreateAssociationBatchCommandOutput } from "../commands/CreateAssociationBatchCommand";
import { CreateAssociationCommandInput, CreateAssociationCommandOutput } from "../commands/CreateAssociationCommand";
import { CreateDocumentCommandInput, CreateDocumentCommandOutput } from "../commands/CreateDocumentCommand";
import { CreateMaintenanceWindowCommandInput, CreateMaintenanceWindowCommandOutput } from "../commands/CreateMaintenanceWindowCommand";
import { CreateOpsItemCommandInput, CreateOpsItemCommandOutput } from "../commands/CreateOpsItemCommand";
import { CreatePatchBaselineCommandInput, CreatePatchBaselineCommandOutput } from "../commands/CreatePatchBaselineCommand";
import { CreateResourceDataSyncCommandInput, CreateResourceDataSyncCommandOutput } from "../commands/CreateResourceDataSyncCommand";
import { DeleteActivationCommandInput, DeleteActivationCommandOutput } from "../commands/DeleteActivationCommand";
import { DeleteAssociationCommandInput, DeleteAssociationCommandOutput } from "../commands/DeleteAssociationCommand";
import { DeleteDocumentCommandInput, DeleteDocumentCommandOutput } from "../commands/DeleteDocumentCommand";
import { DeleteInventoryCommandInput, DeleteInventoryCommandOutput } from "../commands/DeleteInventoryCommand";
import { DeleteMaintenanceWindowCommandInput, DeleteMaintenanceWindowCommandOutput } from "../commands/DeleteMaintenanceWindowCommand";
import { DeleteParameterCommandInput, DeleteParameterCommandOutput } from "../commands/DeleteParameterCommand";
import { DeleteParametersCommandInput, DeleteParametersCommandOutput } from "../commands/DeleteParametersCommand";
import { DeletePatchBaselineCommandInput, DeletePatchBaselineCommandOutput } from "../commands/DeletePatchBaselineCommand";
import { DeleteResourceDataSyncCommandInput, DeleteResourceDataSyncCommandOutput } from "../commands/DeleteResourceDataSyncCommand";
import { DeregisterManagedInstanceCommandInput, DeregisterManagedInstanceCommandOutput } from "../commands/DeregisterManagedInstanceCommand";
import { DeregisterPatchBaselineForPatchGroupCommandInput, DeregisterPatchBaselineForPatchGroupCommandOutput } from "../commands/DeregisterPatchBaselineForPatchGroupCommand";
import { DeregisterTargetFromMaintenanceWindowCommandInput, DeregisterTargetFromMaintenanceWindowCommandOutput } from "../commands/DeregisterTargetFromMaintenanceWindowCommand";
import { DeregisterTaskFromMaintenanceWindowCommandInput, DeregisterTaskFromMaintenanceWindowCommandOutput } from "../commands/DeregisterTaskFromMaintenanceWindowCommand";
import { DescribeActivationsCommandInput, DescribeActivationsCommandOutput } from "../commands/DescribeActivationsCommand";
import { DescribeAssociationCommandInput, DescribeAssociationCommandOutput } from "../commands/DescribeAssociationCommand";
import { DescribeAssociationExecutionTargetsCommandInput, DescribeAssociationExecutionTargetsCommandOutput } from "../commands/DescribeAssociationExecutionTargetsCommand";
import { DescribeAssociationExecutionsCommandInput, DescribeAssociationExecutionsCommandOutput } from "../commands/DescribeAssociationExecutionsCommand";
import { DescribeAutomationExecutionsCommandInput, DescribeAutomationExecutionsCommandOutput } from "../commands/DescribeAutomationExecutionsCommand";
import { DescribeAutomationStepExecutionsCommandInput, DescribeAutomationStepExecutionsCommandOutput } from "../commands/DescribeAutomationStepExecutionsCommand";
import { DescribeAvailablePatchesCommandInput, DescribeAvailablePatchesCommandOutput } from "../commands/DescribeAvailablePatchesCommand";
import { DescribeDocumentCommandInput, DescribeDocumentCommandOutput } from "../commands/DescribeDocumentCommand";
import { DescribeDocumentPermissionCommandInput, DescribeDocumentPermissionCommandOutput } from "../commands/DescribeDocumentPermissionCommand";
import { DescribeEffectiveInstanceAssociationsCommandInput, DescribeEffectiveInstanceAssociationsCommandOutput } from "../commands/DescribeEffectiveInstanceAssociationsCommand";
import { DescribeEffectivePatchesForPatchBaselineCommandInput, DescribeEffectivePatchesForPatchBaselineCommandOutput } from "../commands/DescribeEffectivePatchesForPatchBaselineCommand";
import { DescribeInstanceAssociationsStatusCommandInput, DescribeInstanceAssociationsStatusCommandOutput } from "../commands/DescribeInstanceAssociationsStatusCommand";
import { DescribeInstanceInformationCommandInput, DescribeInstanceInformationCommandOutput } from "../commands/DescribeInstanceInformationCommand";
import { DescribeInstancePatchStatesCommandInput, DescribeInstancePatchStatesCommandOutput } from "../commands/DescribeInstancePatchStatesCommand";
import { DescribeInstancePatchStatesForPatchGroupCommandInput, DescribeInstancePatchStatesForPatchGroupCommandOutput } from "../commands/DescribeInstancePatchStatesForPatchGroupCommand";
import { DescribeInstancePatchesCommandInput, DescribeInstancePatchesCommandOutput } from "../commands/DescribeInstancePatchesCommand";
import { DescribeInventoryDeletionsCommandInput, DescribeInventoryDeletionsCommandOutput } from "../commands/DescribeInventoryDeletionsCommand";
import { DescribeMaintenanceWindowExecutionTaskInvocationsCommandInput, DescribeMaintenanceWindowExecutionTaskInvocationsCommandOutput } from "../commands/DescribeMaintenanceWindowExecutionTaskInvocationsCommand";
import { DescribeMaintenanceWindowExecutionTasksCommandInput, DescribeMaintenanceWindowExecutionTasksCommandOutput } from "../commands/DescribeMaintenanceWindowExecutionTasksCommand";
import { DescribeMaintenanceWindowExecutionsCommandInput, DescribeMaintenanceWindowExecutionsCommandOutput } from "../commands/DescribeMaintenanceWindowExecutionsCommand";
import { DescribeMaintenanceWindowScheduleCommandInput, DescribeMaintenanceWindowScheduleCommandOutput } from "../commands/DescribeMaintenanceWindowScheduleCommand";
import { DescribeMaintenanceWindowTargetsCommandInput, DescribeMaintenanceWindowTargetsCommandOutput } from "../commands/DescribeMaintenanceWindowTargetsCommand";
import { DescribeMaintenanceWindowTasksCommandInput, DescribeMaintenanceWindowTasksCommandOutput } from "../commands/DescribeMaintenanceWindowTasksCommand";
import { DescribeMaintenanceWindowsCommandInput, DescribeMaintenanceWindowsCommandOutput } from "../commands/DescribeMaintenanceWindowsCommand";
import { DescribeMaintenanceWindowsForTargetCommandInput, DescribeMaintenanceWindowsForTargetCommandOutput } from "../commands/DescribeMaintenanceWindowsForTargetCommand";
import { DescribeOpsItemsCommandInput, DescribeOpsItemsCommandOutput } from "../commands/DescribeOpsItemsCommand";
import { DescribeParametersCommandInput, DescribeParametersCommandOutput } from "../commands/DescribeParametersCommand";
import { DescribePatchBaselinesCommandInput, DescribePatchBaselinesCommandOutput } from "../commands/DescribePatchBaselinesCommand";
import { DescribePatchGroupStateCommandInput, DescribePatchGroupStateCommandOutput } from "../commands/DescribePatchGroupStateCommand";
import { DescribePatchGroupsCommandInput, DescribePatchGroupsCommandOutput } from "../commands/DescribePatchGroupsCommand";
import { DescribePatchPropertiesCommandInput, DescribePatchPropertiesCommandOutput } from "../commands/DescribePatchPropertiesCommand";
import { DescribeSessionsCommandInput, DescribeSessionsCommandOutput } from "../commands/DescribeSessionsCommand";
import { GetAutomationExecutionCommandInput, GetAutomationExecutionCommandOutput } from "../commands/GetAutomationExecutionCommand";
import { GetCalendarStateCommandInput, GetCalendarStateCommandOutput } from "../commands/GetCalendarStateCommand";
import { GetCommandInvocationCommandInput, GetCommandInvocationCommandOutput } from "../commands/GetCommandInvocationCommand";
import { GetConnectionStatusCommandInput, GetConnectionStatusCommandOutput } from "../commands/GetConnectionStatusCommand";
import { GetDefaultPatchBaselineCommandInput, GetDefaultPatchBaselineCommandOutput } from "../commands/GetDefaultPatchBaselineCommand";
import { GetDeployablePatchSnapshotForInstanceCommandInput, GetDeployablePatchSnapshotForInstanceCommandOutput } from "../commands/GetDeployablePatchSnapshotForInstanceCommand";
import { GetDocumentCommandInput, GetDocumentCommandOutput } from "../commands/GetDocumentCommand";
import { GetInventoryCommandInput, GetInventoryCommandOutput } from "../commands/GetInventoryCommand";
import { GetInventorySchemaCommandInput, GetInventorySchemaCommandOutput } from "../commands/GetInventorySchemaCommand";
import { GetMaintenanceWindowCommandInput, GetMaintenanceWindowCommandOutput } from "../commands/GetMaintenanceWindowCommand";
import { GetMaintenanceWindowExecutionCommandInput, GetMaintenanceWindowExecutionCommandOutput } from "../commands/GetMaintenanceWindowExecutionCommand";
import { GetMaintenanceWindowExecutionTaskCommandInput, GetMaintenanceWindowExecutionTaskCommandOutput } from "../commands/GetMaintenanceWindowExecutionTaskCommand";
import { GetMaintenanceWindowExecutionTaskInvocationCommandInput, GetMaintenanceWindowExecutionTaskInvocationCommandOutput } from "../commands/GetMaintenanceWindowExecutionTaskInvocationCommand";
import { GetMaintenanceWindowTaskCommandInput, GetMaintenanceWindowTaskCommandOutput } from "../commands/GetMaintenanceWindowTaskCommand";
import { GetOpsItemCommandInput, GetOpsItemCommandOutput } from "../commands/GetOpsItemCommand";
import { GetOpsSummaryCommandInput, GetOpsSummaryCommandOutput } from "../commands/GetOpsSummaryCommand";
import { GetParameterCommandInput, GetParameterCommandOutput } from "../commands/GetParameterCommand";
import { GetParameterHistoryCommandInput, GetParameterHistoryCommandOutput } from "../commands/GetParameterHistoryCommand";
import { GetParametersByPathCommandInput, GetParametersByPathCommandOutput } from "../commands/GetParametersByPathCommand";
import { GetParametersCommandInput, GetParametersCommandOutput } from "../commands/GetParametersCommand";
import { GetPatchBaselineCommandInput, GetPatchBaselineCommandOutput } from "../commands/GetPatchBaselineCommand";
import { GetPatchBaselineForPatchGroupCommandInput, GetPatchBaselineForPatchGroupCommandOutput } from "../commands/GetPatchBaselineForPatchGroupCommand";
import { GetServiceSettingCommandInput, GetServiceSettingCommandOutput } from "../commands/GetServiceSettingCommand";
import { LabelParameterVersionCommandInput, LabelParameterVersionCommandOutput } from "../commands/LabelParameterVersionCommand";
import { ListAssociationVersionsCommandInput, ListAssociationVersionsCommandOutput } from "../commands/ListAssociationVersionsCommand";
import { ListAssociationsCommandInput, ListAssociationsCommandOutput } from "../commands/ListAssociationsCommand";
import { ListCommandInvocationsCommandInput, ListCommandInvocationsCommandOutput } from "../commands/ListCommandInvocationsCommand";
import { ListCommandsCommandInput, ListCommandsCommandOutput } from "../commands/ListCommandsCommand";
import { ListComplianceItemsCommandInput, ListComplianceItemsCommandOutput } from "../commands/ListComplianceItemsCommand";
import { ListComplianceSummariesCommandInput, ListComplianceSummariesCommandOutput } from "../commands/ListComplianceSummariesCommand";
import { ListDocumentVersionsCommandInput, ListDocumentVersionsCommandOutput } from "../commands/ListDocumentVersionsCommand";
import { ListDocumentsCommandInput, ListDocumentsCommandOutput } from "../commands/ListDocumentsCommand";
import { ListInventoryEntriesCommandInput, ListInventoryEntriesCommandOutput } from "../commands/ListInventoryEntriesCommand";
import { ListResourceComplianceSummariesCommandInput, ListResourceComplianceSummariesCommandOutput } from "../commands/ListResourceComplianceSummariesCommand";
import { ListResourceDataSyncCommandInput, ListResourceDataSyncCommandOutput } from "../commands/ListResourceDataSyncCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ModifyDocumentPermissionCommandInput, ModifyDocumentPermissionCommandOutput } from "../commands/ModifyDocumentPermissionCommand";
import { PutComplianceItemsCommandInput, PutComplianceItemsCommandOutput } from "../commands/PutComplianceItemsCommand";
import { PutInventoryCommandInput, PutInventoryCommandOutput } from "../commands/PutInventoryCommand";
import { PutParameterCommandInput, PutParameterCommandOutput } from "../commands/PutParameterCommand";
import { RegisterDefaultPatchBaselineCommandInput, RegisterDefaultPatchBaselineCommandOutput } from "../commands/RegisterDefaultPatchBaselineCommand";
import { RegisterPatchBaselineForPatchGroupCommandInput, RegisterPatchBaselineForPatchGroupCommandOutput } from "../commands/RegisterPatchBaselineForPatchGroupCommand";
import { RegisterTargetWithMaintenanceWindowCommandInput, RegisterTargetWithMaintenanceWindowCommandOutput } from "../commands/RegisterTargetWithMaintenanceWindowCommand";
import { RegisterTaskWithMaintenanceWindowCommandInput, RegisterTaskWithMaintenanceWindowCommandOutput } from "../commands/RegisterTaskWithMaintenanceWindowCommand";
import { RemoveTagsFromResourceCommandInput, RemoveTagsFromResourceCommandOutput } from "../commands/RemoveTagsFromResourceCommand";
import { ResetServiceSettingCommandInput, ResetServiceSettingCommandOutput } from "../commands/ResetServiceSettingCommand";
import { ResumeSessionCommandInput, ResumeSessionCommandOutput } from "../commands/ResumeSessionCommand";
import { SendAutomationSignalCommandInput, SendAutomationSignalCommandOutput } from "../commands/SendAutomationSignalCommand";
import { SendCommandCommandInput, SendCommandCommandOutput } from "../commands/SendCommandCommand";
import { StartAssociationsOnceCommandInput, StartAssociationsOnceCommandOutput } from "../commands/StartAssociationsOnceCommand";
import { StartAutomationExecutionCommandInput, StartAutomationExecutionCommandOutput } from "../commands/StartAutomationExecutionCommand";
import { StartSessionCommandInput, StartSessionCommandOutput } from "../commands/StartSessionCommand";
import { StopAutomationExecutionCommandInput, StopAutomationExecutionCommandOutput } from "../commands/StopAutomationExecutionCommand";
import { TerminateSessionCommandInput, TerminateSessionCommandOutput } from "../commands/TerminateSessionCommand";
import { UpdateAssociationCommandInput, UpdateAssociationCommandOutput } from "../commands/UpdateAssociationCommand";
import { UpdateAssociationStatusCommandInput, UpdateAssociationStatusCommandOutput } from "../commands/UpdateAssociationStatusCommand";
import { UpdateDocumentCommandInput, UpdateDocumentCommandOutput } from "../commands/UpdateDocumentCommand";
import { UpdateDocumentDefaultVersionCommandInput, UpdateDocumentDefaultVersionCommandOutput } from "../commands/UpdateDocumentDefaultVersionCommand";
import { UpdateMaintenanceWindowCommandInput, UpdateMaintenanceWindowCommandOutput } from "../commands/UpdateMaintenanceWindowCommand";
import { UpdateMaintenanceWindowTargetCommandInput, UpdateMaintenanceWindowTargetCommandOutput } from "../commands/UpdateMaintenanceWindowTargetCommand";
import { UpdateMaintenanceWindowTaskCommandInput, UpdateMaintenanceWindowTaskCommandOutput } from "../commands/UpdateMaintenanceWindowTaskCommand";
import { UpdateManagedInstanceRoleCommandInput, UpdateManagedInstanceRoleCommandOutput } from "../commands/UpdateManagedInstanceRoleCommand";
import { UpdateOpsItemCommandInput, UpdateOpsItemCommandOutput } from "../commands/UpdateOpsItemCommand";
import { UpdatePatchBaselineCommandInput, UpdatePatchBaselineCommandOutput } from "../commands/UpdatePatchBaselineCommand";
import { UpdateResourceDataSyncCommandInput, UpdateResourceDataSyncCommandOutput } from "../commands/UpdateResourceDataSyncCommand";
import { UpdateServiceSettingCommandInput, UpdateServiceSettingCommandOutput } from "../commands/UpdateServiceSettingCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddTagsToResourceCommand(input: AddTagsToResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelCommandCommand(input: CancelCommandCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelMaintenanceWindowExecutionCommand(input: CancelMaintenanceWindowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateActivationCommand(input: CreateActivationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAssociationCommand(input: CreateAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAssociationBatchCommand(input: CreateAssociationBatchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDocumentCommand(input: CreateDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateMaintenanceWindowCommand(input: CreateMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateOpsItemCommand(input: CreateOpsItemCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePatchBaselineCommand(input: CreatePatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateResourceDataSyncCommand(input: CreateResourceDataSyncCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteActivationCommand(input: DeleteActivationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAssociationCommand(input: DeleteAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDocumentCommand(input: DeleteDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInventoryCommand(input: DeleteInventoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMaintenanceWindowCommand(input: DeleteMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteParameterCommand(input: DeleteParameterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteParametersCommand(input: DeleteParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePatchBaselineCommand(input: DeletePatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteResourceDataSyncCommand(input: DeleteResourceDataSyncCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterManagedInstanceCommand(input: DeregisterManagedInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterPatchBaselineForPatchGroupCommand(input: DeregisterPatchBaselineForPatchGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterTargetFromMaintenanceWindowCommand(input: DeregisterTargetFromMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterTaskFromMaintenanceWindowCommand(input: DeregisterTaskFromMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeActivationsCommand(input: DescribeActivationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAssociationCommand(input: DescribeAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAssociationExecutionTargetsCommand(input: DescribeAssociationExecutionTargetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAssociationExecutionsCommand(input: DescribeAssociationExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAutomationExecutionsCommand(input: DescribeAutomationExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAutomationStepExecutionsCommand(input: DescribeAutomationStepExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAvailablePatchesCommand(input: DescribeAvailablePatchesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDocumentCommand(input: DescribeDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDocumentPermissionCommand(input: DescribeDocumentPermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEffectiveInstanceAssociationsCommand(input: DescribeEffectiveInstanceAssociationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEffectivePatchesForPatchBaselineCommand(input: DescribeEffectivePatchesForPatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstanceAssociationsStatusCommand(input: DescribeInstanceAssociationsStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstanceInformationCommand(input: DescribeInstanceInformationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstancePatchStatesCommand(input: DescribeInstancePatchStatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstancePatchStatesForPatchGroupCommand(input: DescribeInstancePatchStatesForPatchGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstancePatchesCommand(input: DescribeInstancePatchesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInventoryDeletionsCommand(input: DescribeInventoryDeletionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowExecutionTaskInvocationsCommand(input: DescribeMaintenanceWindowExecutionTaskInvocationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowExecutionTasksCommand(input: DescribeMaintenanceWindowExecutionTasksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowExecutionsCommand(input: DescribeMaintenanceWindowExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowScheduleCommand(input: DescribeMaintenanceWindowScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowTargetsCommand(input: DescribeMaintenanceWindowTargetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowTasksCommand(input: DescribeMaintenanceWindowTasksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowsCommand(input: DescribeMaintenanceWindowsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceWindowsForTargetCommand(input: DescribeMaintenanceWindowsForTargetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeOpsItemsCommand(input: DescribeOpsItemsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeParametersCommand(input: DescribeParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePatchBaselinesCommand(input: DescribePatchBaselinesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePatchGroupStateCommand(input: DescribePatchGroupStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePatchGroupsCommand(input: DescribePatchGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePatchPropertiesCommand(input: DescribePatchPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSessionsCommand(input: DescribeSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAutomationExecutionCommand(input: GetAutomationExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCalendarStateCommand(input: GetCalendarStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCommandInvocationCommand(input: GetCommandInvocationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetConnectionStatusCommand(input: GetConnectionStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDefaultPatchBaselineCommand(input: GetDefaultPatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDeployablePatchSnapshotForInstanceCommand(input: GetDeployablePatchSnapshotForInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDocumentCommand(input: GetDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInventoryCommand(input: GetInventoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInventorySchemaCommand(input: GetInventorySchemaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMaintenanceWindowCommand(input: GetMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMaintenanceWindowExecutionCommand(input: GetMaintenanceWindowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMaintenanceWindowExecutionTaskCommand(input: GetMaintenanceWindowExecutionTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMaintenanceWindowExecutionTaskInvocationCommand(input: GetMaintenanceWindowExecutionTaskInvocationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMaintenanceWindowTaskCommand(input: GetMaintenanceWindowTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOpsItemCommand(input: GetOpsItemCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOpsSummaryCommand(input: GetOpsSummaryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetParameterCommand(input: GetParameterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetParameterHistoryCommand(input: GetParameterHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetParametersCommand(input: GetParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetParametersByPathCommand(input: GetParametersByPathCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPatchBaselineCommand(input: GetPatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPatchBaselineForPatchGroupCommand(input: GetPatchBaselineForPatchGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetServiceSettingCommand(input: GetServiceSettingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1LabelParameterVersionCommand(input: LabelParameterVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAssociationVersionsCommand(input: ListAssociationVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAssociationsCommand(input: ListAssociationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListCommandInvocationsCommand(input: ListCommandInvocationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListCommandsCommand(input: ListCommandsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListComplianceItemsCommand(input: ListComplianceItemsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListComplianceSummariesCommand(input: ListComplianceSummariesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDocumentVersionsCommand(input: ListDocumentVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDocumentsCommand(input: ListDocumentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListInventoryEntriesCommand(input: ListInventoryEntriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourceComplianceSummariesCommand(input: ListResourceComplianceSummariesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourceDataSyncCommand(input: ListResourceDataSyncCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyDocumentPermissionCommand(input: ModifyDocumentPermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutComplianceItemsCommand(input: PutComplianceItemsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutInventoryCommand(input: PutInventoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutParameterCommand(input: PutParameterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterDefaultPatchBaselineCommand(input: RegisterDefaultPatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterPatchBaselineForPatchGroupCommand(input: RegisterPatchBaselineForPatchGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterTargetWithMaintenanceWindowCommand(input: RegisterTargetWithMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterTaskWithMaintenanceWindowCommand(input: RegisterTaskWithMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTagsFromResourceCommand(input: RemoveTagsFromResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResetServiceSettingCommand(input: ResetServiceSettingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResumeSessionCommand(input: ResumeSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SendAutomationSignalCommand(input: SendAutomationSignalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SendCommandCommand(input: SendCommandCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartAssociationsOnceCommand(input: StartAssociationsOnceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartAutomationExecutionCommand(input: StartAutomationExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartSessionCommand(input: StartSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopAutomationExecutionCommand(input: StopAutomationExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TerminateSessionCommand(input: TerminateSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAssociationCommand(input: UpdateAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAssociationStatusCommand(input: UpdateAssociationStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDocumentCommand(input: UpdateDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDocumentDefaultVersionCommand(input: UpdateDocumentDefaultVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMaintenanceWindowCommand(input: UpdateMaintenanceWindowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMaintenanceWindowTargetCommand(input: UpdateMaintenanceWindowTargetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMaintenanceWindowTaskCommand(input: UpdateMaintenanceWindowTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateManagedInstanceRoleCommand(input: UpdateManagedInstanceRoleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateOpsItemCommand(input: UpdateOpsItemCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePatchBaselineCommand(input: UpdatePatchBaselineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateResourceDataSyncCommand(input: UpdateResourceDataSyncCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateServiceSettingCommand(input: UpdateServiceSettingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddTagsToResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsToResourceCommandOutput>;
export declare function deserializeAws_json1_1CancelCommandCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelCommandCommandOutput>;
export declare function deserializeAws_json1_1CancelMaintenanceWindowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelMaintenanceWindowExecutionCommandOutput>;
export declare function deserializeAws_json1_1CreateActivationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateActivationCommandOutput>;
export declare function deserializeAws_json1_1CreateAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAssociationCommandOutput>;
export declare function deserializeAws_json1_1CreateAssociationBatchCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAssociationBatchCommandOutput>;
export declare function deserializeAws_json1_1CreateDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDocumentCommandOutput>;
export declare function deserializeAws_json1_1CreateMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1CreateOpsItemCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateOpsItemCommandOutput>;
export declare function deserializeAws_json1_1CreatePatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1CreateResourceDataSyncCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateResourceDataSyncCommandOutput>;
export declare function deserializeAws_json1_1DeleteActivationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteActivationCommandOutput>;
export declare function deserializeAws_json1_1DeleteAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAssociationCommandOutput>;
export declare function deserializeAws_json1_1DeleteDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDocumentCommandOutput>;
export declare function deserializeAws_json1_1DeleteInventoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInventoryCommandOutput>;
export declare function deserializeAws_json1_1DeleteMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1DeleteParameterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteParameterCommandOutput>;
export declare function deserializeAws_json1_1DeleteParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteParametersCommandOutput>;
export declare function deserializeAws_json1_1DeletePatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1DeleteResourceDataSyncCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteResourceDataSyncCommandOutput>;
export declare function deserializeAws_json1_1DeregisterManagedInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterManagedInstanceCommandOutput>;
export declare function deserializeAws_json1_1DeregisterPatchBaselineForPatchGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterPatchBaselineForPatchGroupCommandOutput>;
export declare function deserializeAws_json1_1DeregisterTargetFromMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterTargetFromMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1DeregisterTaskFromMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterTaskFromMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1DescribeActivationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeActivationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAssociationCommandOutput>;
export declare function deserializeAws_json1_1DescribeAssociationExecutionTargetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAssociationExecutionTargetsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAssociationExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAssociationExecutionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAutomationExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAutomationExecutionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAutomationStepExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAutomationStepExecutionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAvailablePatchesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAvailablePatchesCommandOutput>;
export declare function deserializeAws_json1_1DescribeDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDocumentCommandOutput>;
export declare function deserializeAws_json1_1DescribeDocumentPermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDocumentPermissionCommandOutput>;
export declare function deserializeAws_json1_1DescribeEffectiveInstanceAssociationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEffectiveInstanceAssociationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeEffectivePatchesForPatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEffectivePatchesForPatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstanceAssociationsStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstanceAssociationsStatusCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstanceInformationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstanceInformationCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstancePatchStatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancePatchStatesCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstancePatchStatesForPatchGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancePatchStatesForPatchGroupCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstancePatchesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancePatchesCommandOutput>;
export declare function deserializeAws_json1_1DescribeInventoryDeletionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInventoryDeletionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowExecutionTaskInvocationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowExecutionTaskInvocationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowExecutionTasksCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowExecutionTasksCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowExecutionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowScheduleCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowTargetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowTargetsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowTasksCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowTasksCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceWindowsForTargetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceWindowsForTargetCommandOutput>;
export declare function deserializeAws_json1_1DescribeOpsItemsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeOpsItemsCommandOutput>;
export declare function deserializeAws_json1_1DescribeParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeParametersCommandOutput>;
export declare function deserializeAws_json1_1DescribePatchBaselinesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePatchBaselinesCommandOutput>;
export declare function deserializeAws_json1_1DescribePatchGroupStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePatchGroupStateCommandOutput>;
export declare function deserializeAws_json1_1DescribePatchGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePatchGroupsCommandOutput>;
export declare function deserializeAws_json1_1DescribePatchPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePatchPropertiesCommandOutput>;
export declare function deserializeAws_json1_1DescribeSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSessionsCommandOutput>;
export declare function deserializeAws_json1_1GetAutomationExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAutomationExecutionCommandOutput>;
export declare function deserializeAws_json1_1GetCalendarStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCalendarStateCommandOutput>;
export declare function deserializeAws_json1_1GetCommandInvocationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCommandInvocationCommandOutput>;
export declare function deserializeAws_json1_1GetConnectionStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetConnectionStatusCommandOutput>;
export declare function deserializeAws_json1_1GetDefaultPatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDefaultPatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1GetDeployablePatchSnapshotForInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDeployablePatchSnapshotForInstanceCommandOutput>;
export declare function deserializeAws_json1_1GetDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDocumentCommandOutput>;
export declare function deserializeAws_json1_1GetInventoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInventoryCommandOutput>;
export declare function deserializeAws_json1_1GetInventorySchemaCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInventorySchemaCommandOutput>;
export declare function deserializeAws_json1_1GetMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1GetMaintenanceWindowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMaintenanceWindowExecutionCommandOutput>;
export declare function deserializeAws_json1_1GetMaintenanceWindowExecutionTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMaintenanceWindowExecutionTaskCommandOutput>;
export declare function deserializeAws_json1_1GetMaintenanceWindowExecutionTaskInvocationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMaintenanceWindowExecutionTaskInvocationCommandOutput>;
export declare function deserializeAws_json1_1GetMaintenanceWindowTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMaintenanceWindowTaskCommandOutput>;
export declare function deserializeAws_json1_1GetOpsItemCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOpsItemCommandOutput>;
export declare function deserializeAws_json1_1GetOpsSummaryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOpsSummaryCommandOutput>;
export declare function deserializeAws_json1_1GetParameterCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetParameterCommandOutput>;
export declare function deserializeAws_json1_1GetParameterHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetParameterHistoryCommandOutput>;
export declare function deserializeAws_json1_1GetParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetParametersCommandOutput>;
export declare function deserializeAws_json1_1GetParametersByPathCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetParametersByPathCommandOutput>;
export declare function deserializeAws_json1_1GetPatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1GetPatchBaselineForPatchGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPatchBaselineForPatchGroupCommandOutput>;
export declare function deserializeAws_json1_1GetServiceSettingCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetServiceSettingCommandOutput>;
export declare function deserializeAws_json1_1LabelParameterVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<LabelParameterVersionCommandOutput>;
export declare function deserializeAws_json1_1ListAssociationVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAssociationVersionsCommandOutput>;
export declare function deserializeAws_json1_1ListAssociationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAssociationsCommandOutput>;
export declare function deserializeAws_json1_1ListCommandInvocationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCommandInvocationsCommandOutput>;
export declare function deserializeAws_json1_1ListCommandsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCommandsCommandOutput>;
export declare function deserializeAws_json1_1ListComplianceItemsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListComplianceItemsCommandOutput>;
export declare function deserializeAws_json1_1ListComplianceSummariesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListComplianceSummariesCommandOutput>;
export declare function deserializeAws_json1_1ListDocumentVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDocumentVersionsCommandOutput>;
export declare function deserializeAws_json1_1ListDocumentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDocumentsCommandOutput>;
export declare function deserializeAws_json1_1ListInventoryEntriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListInventoryEntriesCommandOutput>;
export declare function deserializeAws_json1_1ListResourceComplianceSummariesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourceComplianceSummariesCommandOutput>;
export declare function deserializeAws_json1_1ListResourceDataSyncCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourceDataSyncCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ModifyDocumentPermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyDocumentPermissionCommandOutput>;
export declare function deserializeAws_json1_1PutComplianceItemsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutComplianceItemsCommandOutput>;
export declare function deserializeAws_json1_1PutInventoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutInventoryCommandOutput>;
export declare function deserializeAws_json1_1PutParameterCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutParameterCommandOutput>;
export declare function deserializeAws_json1_1RegisterDefaultPatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterDefaultPatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1RegisterPatchBaselineForPatchGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterPatchBaselineForPatchGroupCommandOutput>;
export declare function deserializeAws_json1_1RegisterTargetWithMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterTargetWithMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1RegisterTaskWithMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterTaskWithMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1RemoveTagsFromResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsFromResourceCommandOutput>;
export declare function deserializeAws_json1_1ResetServiceSettingCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetServiceSettingCommandOutput>;
export declare function deserializeAws_json1_1ResumeSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResumeSessionCommandOutput>;
export declare function deserializeAws_json1_1SendAutomationSignalCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendAutomationSignalCommandOutput>;
export declare function deserializeAws_json1_1SendCommandCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendCommandCommandOutput>;
export declare function deserializeAws_json1_1StartAssociationsOnceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartAssociationsOnceCommandOutput>;
export declare function deserializeAws_json1_1StartAutomationExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartAutomationExecutionCommandOutput>;
export declare function deserializeAws_json1_1StartSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartSessionCommandOutput>;
export declare function deserializeAws_json1_1StopAutomationExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopAutomationExecutionCommandOutput>;
export declare function deserializeAws_json1_1TerminateSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<TerminateSessionCommandOutput>;
export declare function deserializeAws_json1_1UpdateAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAssociationCommandOutput>;
export declare function deserializeAws_json1_1UpdateAssociationStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAssociationStatusCommandOutput>;
export declare function deserializeAws_json1_1UpdateDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDocumentCommandOutput>;
export declare function deserializeAws_json1_1UpdateDocumentDefaultVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDocumentDefaultVersionCommandOutput>;
export declare function deserializeAws_json1_1UpdateMaintenanceWindowCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMaintenanceWindowCommandOutput>;
export declare function deserializeAws_json1_1UpdateMaintenanceWindowTargetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMaintenanceWindowTargetCommandOutput>;
export declare function deserializeAws_json1_1UpdateMaintenanceWindowTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMaintenanceWindowTaskCommandOutput>;
export declare function deserializeAws_json1_1UpdateManagedInstanceRoleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateManagedInstanceRoleCommandOutput>;
export declare function deserializeAws_json1_1UpdateOpsItemCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateOpsItemCommandOutput>;
export declare function deserializeAws_json1_1UpdatePatchBaselineCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePatchBaselineCommandOutput>;
export declare function deserializeAws_json1_1UpdateResourceDataSyncCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateResourceDataSyncCommandOutput>;
export declare function deserializeAws_json1_1UpdateServiceSettingCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateServiceSettingCommandOutput>;
