import { CreateMeshCommandInput, CreateMeshCommandOutput } from "../commands/CreateMeshCommand";
import { CreateRouteCommandInput, CreateRouteCommandOutput } from "../commands/CreateRouteCommand";
import { CreateVirtualNodeCommandInput, CreateVirtualNodeCommandOutput } from "../commands/CreateVirtualNodeCommand";
import { CreateVirtualRouterCommandInput, CreateVirtualRouterCommandOutput } from "../commands/CreateVirtualRouterCommand";
import { CreateVirtualServiceCommandInput, CreateVirtualServiceCommandOutput } from "../commands/CreateVirtualServiceCommand";
import { DeleteMeshCommandInput, DeleteMeshCommandOutput } from "../commands/DeleteMeshCommand";
import { DeleteRouteCommandInput, DeleteRouteCommandOutput } from "../commands/DeleteRouteCommand";
import { DeleteVirtualNodeCommandInput, DeleteVirtualNodeCommandOutput } from "../commands/DeleteVirtualNodeCommand";
import { DeleteVirtualRouterCommandInput, DeleteVirtualRouterCommandOutput } from "../commands/DeleteVirtualRouterCommand";
import { DeleteVirtualServiceCommandInput, DeleteVirtualServiceCommandOutput } from "../commands/DeleteVirtualServiceCommand";
import { DescribeMeshCommandInput, DescribeMeshCommandOutput } from "../commands/DescribeMeshCommand";
import { DescribeRouteCommandInput, DescribeRouteCommandOutput } from "../commands/DescribeRouteCommand";
import { DescribeVirtualNodeCommandInput, DescribeVirtualNodeCommandOutput } from "../commands/DescribeVirtualNodeCommand";
import { DescribeVirtualRouterCommandInput, DescribeVirtualRouterCommandOutput } from "../commands/DescribeVirtualRouterCommand";
import { DescribeVirtualServiceCommandInput, DescribeVirtualServiceCommandOutput } from "../commands/DescribeVirtualServiceCommand";
import { ListMeshesCommandInput, ListMeshesCommandOutput } from "../commands/ListMeshesCommand";
import { ListRoutesCommandInput, ListRoutesCommandOutput } from "../commands/ListRoutesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListVirtualNodesCommandInput, ListVirtualNodesCommandOutput } from "../commands/ListVirtualNodesCommand";
import { ListVirtualRoutersCommandInput, ListVirtualRoutersCommandOutput } from "../commands/ListVirtualRoutersCommand";
import { ListVirtualServicesCommandInput, ListVirtualServicesCommandOutput } from "../commands/ListVirtualServicesCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateMeshCommandInput, UpdateMeshCommandOutput } from "../commands/UpdateMeshCommand";
import { UpdateRouteCommandInput, UpdateRouteCommandOutput } from "../commands/UpdateRouteCommand";
import { UpdateVirtualNodeCommandInput, UpdateVirtualNodeCommandOutput } from "../commands/UpdateVirtualNodeCommand";
import { UpdateVirtualRouterCommandInput, UpdateVirtualRouterCommandOutput } from "../commands/UpdateVirtualRouterCommand";
import { UpdateVirtualServiceCommandInput, UpdateVirtualServiceCommandOutput } from "../commands/UpdateVirtualServiceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restJson1_1CreateMeshCommand(input: CreateMeshCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateRouteCommand(input: CreateRouteCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateVirtualNodeCommand(input: CreateVirtualNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateVirtualRouterCommand(input: CreateVirtualRouterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateVirtualServiceCommand(input: CreateVirtualServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteMeshCommand(input: DeleteMeshCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteRouteCommand(input: DeleteRouteCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteVirtualNodeCommand(input: DeleteVirtualNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteVirtualRouterCommand(input: DeleteVirtualRouterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteVirtualServiceCommand(input: DeleteVirtualServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeMeshCommand(input: DescribeMeshCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeRouteCommand(input: DescribeRouteCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeVirtualNodeCommand(input: DescribeVirtualNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeVirtualRouterCommand(input: DescribeVirtualRouterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeVirtualServiceCommand(input: DescribeVirtualServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListMeshesCommand(input: ListMeshesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListRoutesCommand(input: ListRoutesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListVirtualNodesCommand(input: ListVirtualNodesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListVirtualRoutersCommand(input: ListVirtualRoutersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListVirtualServicesCommand(input: ListVirtualServicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateMeshCommand(input: UpdateMeshCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateRouteCommand(input: UpdateRouteCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateVirtualNodeCommand(input: UpdateVirtualNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateVirtualRouterCommand(input: UpdateVirtualRouterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateVirtualServiceCommand(input: UpdateVirtualServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restJson1_1CreateMeshCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMeshCommandOutput>;
export declare function deserializeAws_restJson1_1CreateRouteCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRouteCommandOutput>;
export declare function deserializeAws_restJson1_1CreateVirtualNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVirtualNodeCommandOutput>;
export declare function deserializeAws_restJson1_1CreateVirtualRouterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVirtualRouterCommandOutput>;
export declare function deserializeAws_restJson1_1CreateVirtualServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVirtualServiceCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteMeshCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMeshCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteRouteCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRouteCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteVirtualNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVirtualNodeCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteVirtualRouterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVirtualRouterCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteVirtualServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVirtualServiceCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeMeshCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMeshCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeRouteCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeRouteCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeVirtualNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVirtualNodeCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeVirtualRouterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVirtualRouterCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeVirtualServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVirtualServiceCommandOutput>;
export declare function deserializeAws_restJson1_1ListMeshesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListMeshesCommandOutput>;
export declare function deserializeAws_restJson1_1ListRoutesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRoutesCommandOutput>;
export declare function deserializeAws_restJson1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_restJson1_1ListVirtualNodesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVirtualNodesCommandOutput>;
export declare function deserializeAws_restJson1_1ListVirtualRoutersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVirtualRoutersCommandOutput>;
export declare function deserializeAws_restJson1_1ListVirtualServicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVirtualServicesCommandOutput>;
export declare function deserializeAws_restJson1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateMeshCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMeshCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateRouteCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRouteCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateVirtualNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVirtualNodeCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateVirtualRouterCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVirtualRouterCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateVirtualServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVirtualServiceCommandOutput>;
