import { CreateDevicePoolCommandInput, CreateDevicePoolCommandOutput } from "../commands/CreateDevicePoolCommand";
import { CreateInstanceProfileCommandInput, CreateInstanceProfileCommandOutput } from "../commands/CreateInstanceProfileCommand";
import { CreateNetworkProfileCommandInput, CreateNetworkProfileCommandOutput } from "../commands/CreateNetworkProfileCommand";
import { CreateProjectCommandInput, CreateProjectCommandOutput } from "../commands/CreateProjectCommand";
import { CreateRemoteAccessSessionCommandInput, CreateRemoteAccessSessionCommandOutput } from "../commands/CreateRemoteAccessSessionCommand";
import { CreateTestGridProjectCommandInput, CreateTestGridProjectCommandOutput } from "../commands/CreateTestGridProjectCommand";
import { CreateTestGridUrlCommandInput, CreateTestGridUrlCommandOutput } from "../commands/CreateTestGridUrlCommand";
import { CreateUploadCommandInput, CreateUploadCommandOutput } from "../commands/CreateUploadCommand";
import { CreateVPCEConfigurationCommandInput, CreateVPCEConfigurationCommandOutput } from "../commands/CreateVPCEConfigurationCommand";
import { DeleteDevicePoolCommandInput, DeleteDevicePoolCommandOutput } from "../commands/DeleteDevicePoolCommand";
import { DeleteInstanceProfileCommandInput, DeleteInstanceProfileCommandOutput } from "../commands/DeleteInstanceProfileCommand";
import { DeleteNetworkProfileCommandInput, DeleteNetworkProfileCommandOutput } from "../commands/DeleteNetworkProfileCommand";
import { DeleteProjectCommandInput, DeleteProjectCommandOutput } from "../commands/DeleteProjectCommand";
import { DeleteRemoteAccessSessionCommandInput, DeleteRemoteAccessSessionCommandOutput } from "../commands/DeleteRemoteAccessSessionCommand";
import { DeleteRunCommandInput, DeleteRunCommandOutput } from "../commands/DeleteRunCommand";
import { DeleteTestGridProjectCommandInput, DeleteTestGridProjectCommandOutput } from "../commands/DeleteTestGridProjectCommand";
import { DeleteUploadCommandInput, DeleteUploadCommandOutput } from "../commands/DeleteUploadCommand";
import { DeleteVPCEConfigurationCommandInput, DeleteVPCEConfigurationCommandOutput } from "../commands/DeleteVPCEConfigurationCommand";
import { GetAccountSettingsCommandInput, GetAccountSettingsCommandOutput } from "../commands/GetAccountSettingsCommand";
import { GetDeviceCommandInput, GetDeviceCommandOutput } from "../commands/GetDeviceCommand";
import { GetDeviceInstanceCommandInput, GetDeviceInstanceCommandOutput } from "../commands/GetDeviceInstanceCommand";
import { GetDevicePoolCommandInput, GetDevicePoolCommandOutput } from "../commands/GetDevicePoolCommand";
import { GetDevicePoolCompatibilityCommandInput, GetDevicePoolCompatibilityCommandOutput } from "../commands/GetDevicePoolCompatibilityCommand";
import { GetInstanceProfileCommandInput, GetInstanceProfileCommandOutput } from "../commands/GetInstanceProfileCommand";
import { GetJobCommandInput, GetJobCommandOutput } from "../commands/GetJobCommand";
import { GetNetworkProfileCommandInput, GetNetworkProfileCommandOutput } from "../commands/GetNetworkProfileCommand";
import { GetOfferingStatusCommandInput, GetOfferingStatusCommandOutput } from "../commands/GetOfferingStatusCommand";
import { GetProjectCommandInput, GetProjectCommandOutput } from "../commands/GetProjectCommand";
import { GetRemoteAccessSessionCommandInput, GetRemoteAccessSessionCommandOutput } from "../commands/GetRemoteAccessSessionCommand";
import { GetRunCommandInput, GetRunCommandOutput } from "../commands/GetRunCommand";
import { GetSuiteCommandInput, GetSuiteCommandOutput } from "../commands/GetSuiteCommand";
import { GetTestCommandInput, GetTestCommandOutput } from "../commands/GetTestCommand";
import { GetTestGridProjectCommandInput, GetTestGridProjectCommandOutput } from "../commands/GetTestGridProjectCommand";
import { GetTestGridSessionCommandInput, GetTestGridSessionCommandOutput } from "../commands/GetTestGridSessionCommand";
import { GetUploadCommandInput, GetUploadCommandOutput } from "../commands/GetUploadCommand";
import { GetVPCEConfigurationCommandInput, GetVPCEConfigurationCommandOutput } from "../commands/GetVPCEConfigurationCommand";
import { InstallToRemoteAccessSessionCommandInput, InstallToRemoteAccessSessionCommandOutput } from "../commands/InstallToRemoteAccessSessionCommand";
import { ListArtifactsCommandInput, ListArtifactsCommandOutput } from "../commands/ListArtifactsCommand";
import { ListDeviceInstancesCommandInput, ListDeviceInstancesCommandOutput } from "../commands/ListDeviceInstancesCommand";
import { ListDevicePoolsCommandInput, ListDevicePoolsCommandOutput } from "../commands/ListDevicePoolsCommand";
import { ListDevicesCommandInput, ListDevicesCommandOutput } from "../commands/ListDevicesCommand";
import { ListInstanceProfilesCommandInput, ListInstanceProfilesCommandOutput } from "../commands/ListInstanceProfilesCommand";
import { ListJobsCommandInput, ListJobsCommandOutput } from "../commands/ListJobsCommand";
import { ListNetworkProfilesCommandInput, ListNetworkProfilesCommandOutput } from "../commands/ListNetworkProfilesCommand";
import { ListOfferingPromotionsCommandInput, ListOfferingPromotionsCommandOutput } from "../commands/ListOfferingPromotionsCommand";
import { ListOfferingTransactionsCommandInput, ListOfferingTransactionsCommandOutput } from "../commands/ListOfferingTransactionsCommand";
import { ListOfferingsCommandInput, ListOfferingsCommandOutput } from "../commands/ListOfferingsCommand";
import { ListProjectsCommandInput, ListProjectsCommandOutput } from "../commands/ListProjectsCommand";
import { ListRemoteAccessSessionsCommandInput, ListRemoteAccessSessionsCommandOutput } from "../commands/ListRemoteAccessSessionsCommand";
import { ListRunsCommandInput, ListRunsCommandOutput } from "../commands/ListRunsCommand";
import { ListSamplesCommandInput, ListSamplesCommandOutput } from "../commands/ListSamplesCommand";
import { ListSuitesCommandInput, ListSuitesCommandOutput } from "../commands/ListSuitesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListTestGridProjectsCommandInput, ListTestGridProjectsCommandOutput } from "../commands/ListTestGridProjectsCommand";
import { ListTestGridSessionActionsCommandInput, ListTestGridSessionActionsCommandOutput } from "../commands/ListTestGridSessionActionsCommand";
import { ListTestGridSessionArtifactsCommandInput, ListTestGridSessionArtifactsCommandOutput } from "../commands/ListTestGridSessionArtifactsCommand";
import { ListTestGridSessionsCommandInput, ListTestGridSessionsCommandOutput } from "../commands/ListTestGridSessionsCommand";
import { ListTestsCommandInput, ListTestsCommandOutput } from "../commands/ListTestsCommand";
import { ListUniqueProblemsCommandInput, ListUniqueProblemsCommandOutput } from "../commands/ListUniqueProblemsCommand";
import { ListUploadsCommandInput, ListUploadsCommandOutput } from "../commands/ListUploadsCommand";
import { ListVPCEConfigurationsCommandInput, ListVPCEConfigurationsCommandOutput } from "../commands/ListVPCEConfigurationsCommand";
import { PurchaseOfferingCommandInput, PurchaseOfferingCommandOutput } from "../commands/PurchaseOfferingCommand";
import { RenewOfferingCommandInput, RenewOfferingCommandOutput } from "../commands/RenewOfferingCommand";
import { ScheduleRunCommandInput, ScheduleRunCommandOutput } from "../commands/ScheduleRunCommand";
import { StopJobCommandInput, StopJobCommandOutput } from "../commands/StopJobCommand";
import { StopRemoteAccessSessionCommandInput, StopRemoteAccessSessionCommandOutput } from "../commands/StopRemoteAccessSessionCommand";
import { StopRunCommandInput, StopRunCommandOutput } from "../commands/StopRunCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateDeviceInstanceCommandInput, UpdateDeviceInstanceCommandOutput } from "../commands/UpdateDeviceInstanceCommand";
import { UpdateDevicePoolCommandInput, UpdateDevicePoolCommandOutput } from "../commands/UpdateDevicePoolCommand";
import { UpdateInstanceProfileCommandInput, UpdateInstanceProfileCommandOutput } from "../commands/UpdateInstanceProfileCommand";
import { UpdateNetworkProfileCommandInput, UpdateNetworkProfileCommandOutput } from "../commands/UpdateNetworkProfileCommand";
import { UpdateProjectCommandInput, UpdateProjectCommandOutput } from "../commands/UpdateProjectCommand";
import { UpdateTestGridProjectCommandInput, UpdateTestGridProjectCommandOutput } from "../commands/UpdateTestGridProjectCommand";
import { UpdateUploadCommandInput, UpdateUploadCommandOutput } from "../commands/UpdateUploadCommand";
import { UpdateVPCEConfigurationCommandInput, UpdateVPCEConfigurationCommandOutput } from "../commands/UpdateVPCEConfigurationCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateDevicePoolCommand(input: CreateDevicePoolCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInstanceProfileCommand(input: CreateInstanceProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateNetworkProfileCommand(input: CreateNetworkProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateProjectCommand(input: CreateProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRemoteAccessSessionCommand(input: CreateRemoteAccessSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTestGridProjectCommand(input: CreateTestGridProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTestGridUrlCommand(input: CreateTestGridUrlCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateUploadCommand(input: CreateUploadCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateVPCEConfigurationCommand(input: CreateVPCEConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDevicePoolCommand(input: DeleteDevicePoolCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInstanceProfileCommand(input: DeleteInstanceProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteNetworkProfileCommand(input: DeleteNetworkProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteProjectCommand(input: DeleteProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRemoteAccessSessionCommand(input: DeleteRemoteAccessSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRunCommand(input: DeleteRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTestGridProjectCommand(input: DeleteTestGridProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteUploadCommand(input: DeleteUploadCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVPCEConfigurationCommand(input: DeleteVPCEConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAccountSettingsCommand(input: GetAccountSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDeviceCommand(input: GetDeviceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDeviceInstanceCommand(input: GetDeviceInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDevicePoolCommand(input: GetDevicePoolCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDevicePoolCompatibilityCommand(input: GetDevicePoolCompatibilityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceProfileCommand(input: GetInstanceProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobCommand(input: GetJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetNetworkProfileCommand(input: GetNetworkProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOfferingStatusCommand(input: GetOfferingStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetProjectCommand(input: GetProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRemoteAccessSessionCommand(input: GetRemoteAccessSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRunCommand(input: GetRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSuiteCommand(input: GetSuiteCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTestCommand(input: GetTestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTestGridProjectCommand(input: GetTestGridProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTestGridSessionCommand(input: GetTestGridSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetUploadCommand(input: GetUploadCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetVPCEConfigurationCommand(input: GetVPCEConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1InstallToRemoteAccessSessionCommand(input: InstallToRemoteAccessSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListArtifactsCommand(input: ListArtifactsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDeviceInstancesCommand(input: ListDeviceInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDevicePoolsCommand(input: ListDevicePoolsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDevicesCommand(input: ListDevicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListInstanceProfilesCommand(input: ListInstanceProfilesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListJobsCommand(input: ListJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListNetworkProfilesCommand(input: ListNetworkProfilesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListOfferingPromotionsCommand(input: ListOfferingPromotionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListOfferingTransactionsCommand(input: ListOfferingTransactionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListOfferingsCommand(input: ListOfferingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListProjectsCommand(input: ListProjectsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRemoteAccessSessionsCommand(input: ListRemoteAccessSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRunsCommand(input: ListRunsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListSamplesCommand(input: ListSamplesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListSuitesCommand(input: ListSuitesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTestGridProjectsCommand(input: ListTestGridProjectsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTestGridSessionActionsCommand(input: ListTestGridSessionActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTestGridSessionArtifactsCommand(input: ListTestGridSessionArtifactsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTestGridSessionsCommand(input: ListTestGridSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTestsCommand(input: ListTestsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListUniqueProblemsCommand(input: ListUniqueProblemsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListUploadsCommand(input: ListUploadsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVPCEConfigurationsCommand(input: ListVPCEConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PurchaseOfferingCommand(input: PurchaseOfferingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RenewOfferingCommand(input: RenewOfferingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ScheduleRunCommand(input: ScheduleRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopJobCommand(input: StopJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopRemoteAccessSessionCommand(input: StopRemoteAccessSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopRunCommand(input: StopRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDeviceInstanceCommand(input: UpdateDeviceInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDevicePoolCommand(input: UpdateDevicePoolCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateInstanceProfileCommand(input: UpdateInstanceProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateNetworkProfileCommand(input: UpdateNetworkProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateProjectCommand(input: UpdateProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateTestGridProjectCommand(input: UpdateTestGridProjectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateUploadCommand(input: UpdateUploadCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVPCEConfigurationCommand(input: UpdateVPCEConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateDevicePoolCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDevicePoolCommandOutput>;
export declare function deserializeAws_json1_1CreateInstanceProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInstanceProfileCommandOutput>;
export declare function deserializeAws_json1_1CreateNetworkProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateNetworkProfileCommandOutput>;
export declare function deserializeAws_json1_1CreateProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateProjectCommandOutput>;
export declare function deserializeAws_json1_1CreateRemoteAccessSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRemoteAccessSessionCommandOutput>;
export declare function deserializeAws_json1_1CreateTestGridProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTestGridProjectCommandOutput>;
export declare function deserializeAws_json1_1CreateTestGridUrlCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTestGridUrlCommandOutput>;
export declare function deserializeAws_json1_1CreateUploadCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateUploadCommandOutput>;
export declare function deserializeAws_json1_1CreateVPCEConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVPCEConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeleteDevicePoolCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDevicePoolCommandOutput>;
export declare function deserializeAws_json1_1DeleteInstanceProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInstanceProfileCommandOutput>;
export declare function deserializeAws_json1_1DeleteNetworkProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteNetworkProfileCommandOutput>;
export declare function deserializeAws_json1_1DeleteProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteProjectCommandOutput>;
export declare function deserializeAws_json1_1DeleteRemoteAccessSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRemoteAccessSessionCommandOutput>;
export declare function deserializeAws_json1_1DeleteRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRunCommandOutput>;
export declare function deserializeAws_json1_1DeleteTestGridProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTestGridProjectCommandOutput>;
export declare function deserializeAws_json1_1DeleteUploadCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteUploadCommandOutput>;
export declare function deserializeAws_json1_1DeleteVPCEConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVPCEConfigurationCommandOutput>;
export declare function deserializeAws_json1_1GetAccountSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAccountSettingsCommandOutput>;
export declare function deserializeAws_json1_1GetDeviceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDeviceCommandOutput>;
export declare function deserializeAws_json1_1GetDeviceInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDeviceInstanceCommandOutput>;
export declare function deserializeAws_json1_1GetDevicePoolCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDevicePoolCommandOutput>;
export declare function deserializeAws_json1_1GetDevicePoolCompatibilityCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDevicePoolCompatibilityCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceProfileCommandOutput>;
export declare function deserializeAws_json1_1GetJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobCommandOutput>;
export declare function deserializeAws_json1_1GetNetworkProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetNetworkProfileCommandOutput>;
export declare function deserializeAws_json1_1GetOfferingStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOfferingStatusCommandOutput>;
export declare function deserializeAws_json1_1GetProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetProjectCommandOutput>;
export declare function deserializeAws_json1_1GetRemoteAccessSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRemoteAccessSessionCommandOutput>;
export declare function deserializeAws_json1_1GetRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRunCommandOutput>;
export declare function deserializeAws_json1_1GetSuiteCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSuiteCommandOutput>;
export declare function deserializeAws_json1_1GetTestCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTestCommandOutput>;
export declare function deserializeAws_json1_1GetTestGridProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTestGridProjectCommandOutput>;
export declare function deserializeAws_json1_1GetTestGridSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTestGridSessionCommandOutput>;
export declare function deserializeAws_json1_1GetUploadCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetUploadCommandOutput>;
export declare function deserializeAws_json1_1GetVPCEConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetVPCEConfigurationCommandOutput>;
export declare function deserializeAws_json1_1InstallToRemoteAccessSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<InstallToRemoteAccessSessionCommandOutput>;
export declare function deserializeAws_json1_1ListArtifactsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListArtifactsCommandOutput>;
export declare function deserializeAws_json1_1ListDeviceInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDeviceInstancesCommandOutput>;
export declare function deserializeAws_json1_1ListDevicePoolsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDevicePoolsCommandOutput>;
export declare function deserializeAws_json1_1ListDevicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDevicesCommandOutput>;
export declare function deserializeAws_json1_1ListInstanceProfilesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListInstanceProfilesCommandOutput>;
export declare function deserializeAws_json1_1ListJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListJobsCommandOutput>;
export declare function deserializeAws_json1_1ListNetworkProfilesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListNetworkProfilesCommandOutput>;
export declare function deserializeAws_json1_1ListOfferingPromotionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOfferingPromotionsCommandOutput>;
export declare function deserializeAws_json1_1ListOfferingTransactionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOfferingTransactionsCommandOutput>;
export declare function deserializeAws_json1_1ListOfferingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOfferingsCommandOutput>;
export declare function deserializeAws_json1_1ListProjectsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListProjectsCommandOutput>;
export declare function deserializeAws_json1_1ListRemoteAccessSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRemoteAccessSessionsCommandOutput>;
export declare function deserializeAws_json1_1ListRunsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRunsCommandOutput>;
export declare function deserializeAws_json1_1ListSamplesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSamplesCommandOutput>;
export declare function deserializeAws_json1_1ListSuitesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSuitesCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListTestGridProjectsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTestGridProjectsCommandOutput>;
export declare function deserializeAws_json1_1ListTestGridSessionActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTestGridSessionActionsCommandOutput>;
export declare function deserializeAws_json1_1ListTestGridSessionArtifactsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTestGridSessionArtifactsCommandOutput>;
export declare function deserializeAws_json1_1ListTestGridSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTestGridSessionsCommandOutput>;
export declare function deserializeAws_json1_1ListTestsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTestsCommandOutput>;
export declare function deserializeAws_json1_1ListUniqueProblemsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListUniqueProblemsCommandOutput>;
export declare function deserializeAws_json1_1ListUploadsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListUploadsCommandOutput>;
export declare function deserializeAws_json1_1ListVPCEConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVPCEConfigurationsCommandOutput>;
export declare function deserializeAws_json1_1PurchaseOfferingCommand(output: __HttpResponse, context: __SerdeContext): Promise<PurchaseOfferingCommandOutput>;
export declare function deserializeAws_json1_1RenewOfferingCommand(output: __HttpResponse, context: __SerdeContext): Promise<RenewOfferingCommandOutput>;
export declare function deserializeAws_json1_1ScheduleRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<ScheduleRunCommandOutput>;
export declare function deserializeAws_json1_1StopJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopJobCommandOutput>;
export declare function deserializeAws_json1_1StopRemoteAccessSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopRemoteAccessSessionCommandOutput>;
export declare function deserializeAws_json1_1StopRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopRunCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateDeviceInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDeviceInstanceCommandOutput>;
export declare function deserializeAws_json1_1UpdateDevicePoolCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDevicePoolCommandOutput>;
export declare function deserializeAws_json1_1UpdateInstanceProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateInstanceProfileCommandOutput>;
export declare function deserializeAws_json1_1UpdateNetworkProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateNetworkProfileCommandOutput>;
export declare function deserializeAws_json1_1UpdateProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateProjectCommandOutput>;
export declare function deserializeAws_json1_1UpdateTestGridProjectCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateTestGridProjectCommandOutput>;
export declare function deserializeAws_json1_1UpdateUploadCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateUploadCommandOutput>;
export declare function deserializeAws_json1_1UpdateVPCEConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVPCEConfigurationCommandOutput>;
