import { AssociateDRTLogBucketCommandInput, AssociateDRTLogBucketCommandOutput } from "../commands/AssociateDRTLogBucketCommand";
import { AssociateDRTRoleCommandInput, AssociateDRTRoleCommandOutput } from "../commands/AssociateDRTRoleCommand";
import { CreateProtectionCommandInput, CreateProtectionCommandOutput } from "../commands/CreateProtectionCommand";
import { CreateSubscriptionCommandInput, CreateSubscriptionCommandOutput } from "../commands/CreateSubscriptionCommand";
import { DeleteProtectionCommandInput, DeleteProtectionCommandOutput } from "../commands/DeleteProtectionCommand";
import { DeleteSubscriptionCommandInput, DeleteSubscriptionCommandOutput } from "../commands/DeleteSubscriptionCommand";
import { DescribeAttackCommandInput, DescribeAttackCommandOutput } from "../commands/DescribeAttackCommand";
import { DescribeDRTAccessCommandInput, DescribeDRTAccessCommandOutput } from "../commands/DescribeDRTAccessCommand";
import { DescribeEmergencyContactSettingsCommandInput, DescribeEmergencyContactSettingsCommandOutput } from "../commands/DescribeEmergencyContactSettingsCommand";
import { DescribeProtectionCommandInput, DescribeProtectionCommandOutput } from "../commands/DescribeProtectionCommand";
import { DescribeSubscriptionCommandInput, DescribeSubscriptionCommandOutput } from "../commands/DescribeSubscriptionCommand";
import { DisassociateDRTLogBucketCommandInput, DisassociateDRTLogBucketCommandOutput } from "../commands/DisassociateDRTLogBucketCommand";
import { DisassociateDRTRoleCommandInput, DisassociateDRTRoleCommandOutput } from "../commands/DisassociateDRTRoleCommand";
import { GetSubscriptionStateCommandInput, GetSubscriptionStateCommandOutput } from "../commands/GetSubscriptionStateCommand";
import { ListAttacksCommandInput, ListAttacksCommandOutput } from "../commands/ListAttacksCommand";
import { ListProtectionsCommandInput, ListProtectionsCommandOutput } from "../commands/ListProtectionsCommand";
import { UpdateEmergencyContactSettingsCommandInput, UpdateEmergencyContactSettingsCommandOutput } from "../commands/UpdateEmergencyContactSettingsCommand";
import { UpdateSubscriptionCommandInput, UpdateSubscriptionCommandOutput } from "../commands/UpdateSubscriptionCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateDRTLogBucketCommand(input: AssociateDRTLogBucketCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateDRTRoleCommand(input: AssociateDRTRoleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateProtectionCommand(input: CreateProtectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSubscriptionCommand(input: CreateSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteProtectionCommand(input: DeleteProtectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSubscriptionCommand(input: DeleteSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAttackCommand(input: DescribeAttackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDRTAccessCommand(input: DescribeDRTAccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEmergencyContactSettingsCommand(input: DescribeEmergencyContactSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeProtectionCommand(input: DescribeProtectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSubscriptionCommand(input: DescribeSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateDRTLogBucketCommand(input: DisassociateDRTLogBucketCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateDRTRoleCommand(input: DisassociateDRTRoleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSubscriptionStateCommand(input: GetSubscriptionStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAttacksCommand(input: ListAttacksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListProtectionsCommand(input: ListProtectionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateEmergencyContactSettingsCommand(input: UpdateEmergencyContactSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSubscriptionCommand(input: UpdateSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateDRTLogBucketCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateDRTLogBucketCommandOutput>;
export declare function deserializeAws_json1_1AssociateDRTRoleCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateDRTRoleCommandOutput>;
export declare function deserializeAws_json1_1CreateProtectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateProtectionCommandOutput>;
export declare function deserializeAws_json1_1CreateSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSubscriptionCommandOutput>;
export declare function deserializeAws_json1_1DeleteProtectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteProtectionCommandOutput>;
export declare function deserializeAws_json1_1DeleteSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSubscriptionCommandOutput>;
export declare function deserializeAws_json1_1DescribeAttackCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAttackCommandOutput>;
export declare function deserializeAws_json1_1DescribeDRTAccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDRTAccessCommandOutput>;
export declare function deserializeAws_json1_1DescribeEmergencyContactSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEmergencyContactSettingsCommandOutput>;
export declare function deserializeAws_json1_1DescribeProtectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeProtectionCommandOutput>;
export declare function deserializeAws_json1_1DescribeSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSubscriptionCommandOutput>;
export declare function deserializeAws_json1_1DisassociateDRTLogBucketCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateDRTLogBucketCommandOutput>;
export declare function deserializeAws_json1_1DisassociateDRTRoleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateDRTRoleCommandOutput>;
export declare function deserializeAws_json1_1GetSubscriptionStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSubscriptionStateCommandOutput>;
export declare function deserializeAws_json1_1ListAttacksCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAttacksCommandOutput>;
export declare function deserializeAws_json1_1ListProtectionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListProtectionsCommandOutput>;
export declare function deserializeAws_json1_1UpdateEmergencyContactSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateEmergencyContactSettingsCommandOutput>;
export declare function deserializeAws_json1_1UpdateSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSubscriptionCommandOutput>;
