import { DescribeReportCreationCommandInput, DescribeReportCreationCommandOutput } from "../commands/DescribeReportCreationCommand";
import { GetComplianceSummaryCommandInput, GetComplianceSummaryCommandOutput } from "../commands/GetComplianceSummaryCommand";
import { GetResourcesCommandInput, GetResourcesCommandOutput } from "../commands/GetResourcesCommand";
import { GetTagKeysCommandInput, GetTagKeysCommandOutput } from "../commands/GetTagKeysCommand";
import { GetTagValuesCommandInput, GetTagValuesCommandOutput } from "../commands/GetTagValuesCommand";
import { StartReportCreationCommandInput, StartReportCreationCommandOutput } from "../commands/StartReportCreationCommand";
import { TagResourcesCommandInput, TagResourcesCommandOutput } from "../commands/TagResourcesCommand";
import { UntagResourcesCommandInput, UntagResourcesCommandOutput } from "../commands/UntagResourcesCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1DescribeReportCreationCommand(input: DescribeReportCreationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetComplianceSummaryCommand(input: GetComplianceSummaryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResourcesCommand(input: GetResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTagKeysCommand(input: GetTagKeysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTagValuesCommand(input: GetTagValuesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartReportCreationCommand(input: StartReportCreationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourcesCommand(input: TagResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourcesCommand(input: UntagResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1DescribeReportCreationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReportCreationCommandOutput>;
export declare function deserializeAws_json1_1GetComplianceSummaryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetComplianceSummaryCommandOutput>;
export declare function deserializeAws_json1_1GetResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResourcesCommandOutput>;
export declare function deserializeAws_json1_1GetTagKeysCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTagKeysCommandOutput>;
export declare function deserializeAws_json1_1GetTagValuesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTagValuesCommandOutput>;
export declare function deserializeAws_json1_1StartReportCreationCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartReportCreationCommandOutput>;
export declare function deserializeAws_json1_1TagResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourcesCommandOutput>;
export declare function deserializeAws_json1_1UntagResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourcesCommandOutput>;
