nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.2.0.cjs

# TODO: add dev dependency to the aws-crt library
packageExtensions:
  "aws-crt@*":
    dependencies:
      "@types/node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
