version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building...
      - yarn
      - echo Executing unit tests
      - yarn test
  post_build:
    commands:
      - ./node_modules/.bin/codecov -f coverage/*.json
