version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g yarn
  build:
    commands:
      - echo Building...
      - yarn --frozen-lockfile
      - echo Executing unit tests
      - yarn test:all
      - echo Executing functional test
      - yarn test:functional
  post_build:
    commands:
      - ./node_modules/.bin/codecov -f coverage/*.json -t 26989a8c-a2e9-4e6f-844a-35a741240b60
