version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g yarn
  build:
    commands:
      - echo Building...
      - yarn
      - echo Executing unit tests
      - yarn build:smithy-client #TODO: change to `yarn test:all` after clients are ready
      - echo Executing functional test
      - yarn test:functional
  post_build:
    commands:
      - ./node_modules/.bin/codecov -f coverage/*.json
