import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    exclude: ["**/*.{integ,e2e,browser}.spec.ts"],
    include: [
      "clients/client-*/**/*.spec.ts",
      "lib/lib-dynamodb/**/*.spec.ts",
      "lib/lib-storage/**/*.spec.ts",
      // "packages/body-checksum-browser/**/*.spec.ts",
      "packages/body-checksum-node/**/*.spec.ts",
      "packages/chunked-stream-reader-node/**/*.spec.ts",
      "packages/cloudfront-signer/**/*.spec.ts",
      "packages/core/**/*.spec.ts",
      "packages/credential-provider-cognito-identity/**/*.spec.ts",
      "packages/credential-provider-env/**/*.spec.ts",
      "packages/credential-provider-http/**/*.spec.ts",
      "packages/credential-provider-ini/**/*.spec.ts",
      "packages/credential-provider-node/**/*.spec.ts",
      "packages/credential-provider-process/**/*.spec.ts",
      "packages/credential-provider-sso/**/*.spec.ts",
      "packages/credential-provider-web-identity/**/*.spec.ts",
      "packages/credential-providers/**/*.spec.ts",
      "packages/ec2-metadata-service/**/*.spec.ts",
      "packages/endpoint-cache/**/*.spec.ts",
      "packages/eventstream-handler-node/**/*.spec.ts",
      "packages/middleware-api-key/**/*.spec.ts",
      "packages/middleware-bucket-endpoint/**/*.spec.ts",
      "packages/middleware-endpoint-discovery/**/*.spec.ts",
      "packages/middleware-eventstream/**/*.spec.ts",
      "packages/middleware-expect-continue/**/*.spec.ts",
      "packages/middleware-flexible-checksums/**/*.spec.ts",
      "packages/middleware-host-header/**/*.spec.ts",
      "packages/middleware-location-constraint/**/*.spec.ts",
      "packages/middleware-logger/**/*.spec.ts",
      "packages/middleware-recursion-detection/**/*.spec.ts",
      "packages/middleware-sdk-api-gateway/**/*.spec.ts",
      "packages/middleware-sdk-ec2/**/*.spec.ts",
      "packages/middleware-sdk-glacier/**/*.spec.ts",
      "packages/middleware-sdk-machinelearning/**/*.spec.ts",
      "packages/middleware-sdk-rds/**/*.spec.ts",
      "packages/middleware-sdk-route53/**/*.spec.ts",
      "packages/middleware-sdk-s3/**/*.spec.ts",
      "packages/middleware-sdk-s3-control/**/*.spec.ts",
      "packages/middleware-sdk-sqs/**/*.spec.ts",
      "packages/middleware-sdk-sts/**/*.spec.ts",
      "packages/middleware-sdk-transcribe-streaming/**/*.spec.ts",
      "packages/middleware-signing/**/*.spec.ts",
      "packages/middleware-ssec/**/*.spec.ts",
      "packages/middleware-token/**/*.spec.ts",
      "packages/middleware-user-agent/**/*.spec.ts",
      // "packages/middleware-websocket/**/*.spec.ts",
    ],
    environment: "node",
  },
});
