import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    exclude: ["**/*.{e2e,browser}.spec.ts"],
    include: [
      "lib/lib-dynamodb/**/*.integ.spec.ts",
      "lib/lib-storage/**/*.integ.spec.ts",
      // "packages/body-checksum-browser/**/*.integ.spec.ts",
      "packages/body-checksum-node/**/*.integ.spec.ts",
      "packages/chunked-stream-reader-node/**/*.integ.spec.ts",
      "packages/cloudfront-signer/**/*.integ.spec.ts",
      "packages/core/**/*.integ.spec.ts",
      "packages/credential-provider-cognito-identity/**/*.integ.spec.ts",
      "packages/credential-provider-env/**/*.integ.spec.ts",
      "packages/credential-provider-http/**/*.integ.spec.ts",
      "packages/credential-provider-ini/**/*.integ.spec.ts",
      // "packages/credential-provider-node/**/*.integ.spec.ts",
      "packages/credential-provider-process/**/*.integ.spec.ts",
      "packages/credential-provider-sso/**/*.integ.spec.ts",
      "packages/credential-provider-web-identity/**/*.integ.spec.ts",
      "packages/credential-providers/**/*.integ.spec.ts",
      "packages/ec2-metadata-service/**/*.integ.spec.ts",
      "packages/endpoint-cache/**/*.integ.spec.ts",
      "packages/eventstream-handler-node/**/*.integ.spec.ts",
      "packages/middleware-api-key/**/*.integ.spec.ts",
      "packages/middleware-bucket-endpoint/**/*.integ.spec.ts",
      "packages/middleware-endpoint-discovery/**/*.integ.spec.ts",
      "packages/middleware-eventstream/**/*.integ.spec.ts",
      "packages/middleware-expect-continue/**/*.integ.spec.ts",
      "packages/middleware-flexible-checksums/**/*.integ.spec.ts",
      "packages/middleware-host-header/**/*.integ.spec.ts",
      "packages/middleware-location-constraint/**/*.integ.spec.ts",
      "packages/middleware-logger/**/*.integ.spec.ts",
      "packages/middleware-recursion-detection/**/*.integ.spec.ts",
      "packages/middleware-sdk-api-gateway/**/*.integ.spec.ts",
      "packages/middleware-sdk-ec2/**/*.integ.spec.ts",
      "packages/middleware-sdk-glacier/**/*.integ.spec.ts",
      "packages/middleware-sdk-machinelearning/**/*.integ.spec.ts",
      "packages/middleware-sdk-rds/**/*.integ.spec.ts",
      "packages/middleware-sdk-route53/**/*.integ.spec.ts",
      "packages/middleware-sdk-s3/**/*.integ.spec.ts",
      "packages/middleware-sdk-s3-control/**/*.integ.spec.ts",
      "packages/middleware-sdk-sqs/**/*.integ.spec.ts",
      "packages/middleware-sdk-sts/**/*.integ.spec.ts",
      "packages/middleware-sdk-transcribe-streaming/**/*.integ.spec.ts",
      "packages/middleware-signing/**/*.integ.spec.ts",
      "packages/middleware-ssec/**/*.integ.spec.ts",
      "packages/middleware-token/**/*.integ.spec.ts",
      "packages/middleware-user-agent/**/*.integ.spec.ts",
      "packages/middleware-websocket/**/*.integ.spec.ts",
    ],
    environment: "node",
  },
});
