// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AccessDeniedException$,
  BadRequestException$,
  ConflictException$,
  CreateNamespace$,
  CreateNamespaceCommand,
  CreateTable$,
  CreateTableBucket$,
  CreateTableBucketCommand,
  CreateTableCommand,
  DeleteNamespace$,
  DeleteNamespaceCommand,
  DeleteTable$,
  DeleteTableBucket$,
  DeleteTableBucketCommand,
  DeleteTableBucketEncryption$,
  DeleteTableBucketEncryptionCommand,
  DeleteTableBucketMetricsConfiguration$,
  DeleteTableBucketMetricsConfigurationCommand,
  DeleteTableBucketPolicy$,
  DeleteTableBucketPolicyCommand,
  DeleteTableBucketReplication$,
  DeleteTableBucketReplicationCommand,
  DeleteTableCommand,
  DeleteTablePolicy$,
  DeleteTablePolicyCommand,
  DeleteTableReplication$,
  DeleteTableReplicationCommand,
  ForbiddenException$,
  GetNamespace$,
  GetNamespaceCommand,
  GetTable$,
  GetTableBucket$,
  GetTableBucketCommand,
  GetTableBucketEncryption$,
  GetTableBucketEncryptionCommand,
  GetTableBucketMaintenanceConfiguration$,
  GetTableBucketMaintenanceConfigurationCommand,
  GetTableBucketMetricsConfiguration$,
  GetTableBucketMetricsConfigurationCommand,
  GetTableBucketPolicy$,
  GetTableBucketPolicyCommand,
  GetTableBucketReplication$,
  GetTableBucketReplicationCommand,
  GetTableBucketStorageClass$,
  GetTableBucketStorageClassCommand,
  GetTableCommand,
  GetTableEncryption$,
  GetTableEncryptionCommand,
  GetTableMaintenanceConfiguration$,
  GetTableMaintenanceConfigurationCommand,
  GetTableMaintenanceJobStatus$,
  GetTableMaintenanceJobStatusCommand,
  GetTableMetadataLocation$,
  GetTableMetadataLocationCommand,
  GetTablePolicy$,
  GetTablePolicyCommand,
  GetTableRecordExpirationConfiguration$,
  GetTableRecordExpirationConfigurationCommand,
  GetTableRecordExpirationJobStatus$,
  GetTableRecordExpirationJobStatusCommand,
  GetTableReplication$,
  GetTableReplicationCommand,
  GetTableReplicationStatus$,
  GetTableReplicationStatusCommand,
  GetTableStorageClass$,
  GetTableStorageClassCommand,
  InternalServerErrorException$,
  ListNamespaces$,
  ListNamespacesCommand,
  ListTableBuckets$,
  ListTableBucketsCommand,
  ListTables$,
  ListTablesCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  MethodNotAllowedException$,
  NotFoundException$,
  PutTableBucketEncryption$,
  PutTableBucketEncryptionCommand,
  PutTableBucketMaintenanceConfiguration$,
  PutTableBucketMaintenanceConfigurationCommand,
  PutTableBucketMetricsConfiguration$,
  PutTableBucketMetricsConfigurationCommand,
  PutTableBucketPolicy$,
  PutTableBucketPolicyCommand,
  PutTableBucketReplication$,
  PutTableBucketReplicationCommand,
  PutTableBucketStorageClass$,
  PutTableBucketStorageClassCommand,
  PutTableMaintenanceConfiguration$,
  PutTableMaintenanceConfigurationCommand,
  PutTablePolicy$,
  PutTablePolicyCommand,
  PutTableRecordExpirationConfiguration$,
  PutTableRecordExpirationConfigurationCommand,
  PutTableReplication$,
  PutTableReplicationCommand,
  RenameTable$,
  RenameTableCommand,
  S3TablesClient,
  TagResource$,
  TagResourceCommand,
  TooManyRequestsException$,
  UntagResource$,
  UntagResourceCommand,
  UpdateTableMetadataLocation$,
  UpdateTableMetadataLocationCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = S3TablesClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("S3TablesClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [CreateNamespace$, CreateNamespaceCommand],
      [CreateTable$, CreateTableCommand],
      [CreateTableBucket$, CreateTableBucketCommand],
      [DeleteNamespace$, DeleteNamespaceCommand],
      [DeleteTable$, DeleteTableCommand],
      [DeleteTableBucket$, DeleteTableBucketCommand],
      [DeleteTableBucketEncryption$, DeleteTableBucketEncryptionCommand],
      [DeleteTableBucketMetricsConfiguration$, DeleteTableBucketMetricsConfigurationCommand],
      [DeleteTableBucketPolicy$, DeleteTableBucketPolicyCommand],
      [DeleteTableBucketReplication$, DeleteTableBucketReplicationCommand],
      [DeleteTablePolicy$, DeleteTablePolicyCommand],
      [DeleteTableReplication$, DeleteTableReplicationCommand],
      [GetNamespace$, GetNamespaceCommand],
      [GetTable$, GetTableCommand],
      [GetTableBucket$, GetTableBucketCommand],
      [GetTableBucketEncryption$, GetTableBucketEncryptionCommand],
      [GetTableBucketMaintenanceConfiguration$, GetTableBucketMaintenanceConfigurationCommand],
      [GetTableBucketMetricsConfiguration$, GetTableBucketMetricsConfigurationCommand],
      [GetTableBucketPolicy$, GetTableBucketPolicyCommand],
      [GetTableBucketReplication$, GetTableBucketReplicationCommand],
      [GetTableBucketStorageClass$, GetTableBucketStorageClassCommand],
      [GetTableEncryption$, GetTableEncryptionCommand],
      [GetTableMaintenanceConfiguration$, GetTableMaintenanceConfigurationCommand],
      [GetTableMaintenanceJobStatus$, GetTableMaintenanceJobStatusCommand],
      [GetTableMetadataLocation$, GetTableMetadataLocationCommand],
      [GetTablePolicy$, GetTablePolicyCommand],
      [GetTableRecordExpirationConfiguration$, GetTableRecordExpirationConfigurationCommand],
      [GetTableRecordExpirationJobStatus$, GetTableRecordExpirationJobStatusCommand],
      [GetTableReplication$, GetTableReplicationCommand],
      [GetTableReplicationStatus$, GetTableReplicationStatusCommand],
      [GetTableStorageClass$, GetTableStorageClassCommand],
      [ListNamespaces$, ListNamespacesCommand],
      [ListTableBuckets$, ListTableBucketsCommand],
      [ListTables$, ListTablesCommand],
      [ListTagsForResource$, ListTagsForResourceCommand],
      [PutTableBucketEncryption$, PutTableBucketEncryptionCommand],
      [PutTableBucketMaintenanceConfiguration$, PutTableBucketMaintenanceConfigurationCommand],
      [PutTableBucketMetricsConfiguration$, PutTableBucketMetricsConfigurationCommand],
      [PutTableBucketPolicy$, PutTableBucketPolicyCommand],
      [PutTableBucketReplication$, PutTableBucketReplicationCommand],
      [PutTableBucketStorageClass$, PutTableBucketStorageClassCommand],
      [PutTableMaintenanceConfiguration$, PutTableMaintenanceConfigurationCommand],
      [PutTablePolicy$, PutTablePolicyCommand],
      [PutTableRecordExpirationConfiguration$, PutTableRecordExpirationConfigurationCommand],
      [PutTableReplication$, PutTableReplicationCommand],
      [RenameTable$, RenameTableCommand],
      [TagResource$, TagResourceCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateTableMetadataLocation$, UpdateTableMetadataLocationCommand],
    ]),
    errors: [
      AccessDeniedException$,
      BadRequestException$,
      ConflictException$,
      ForbiddenException$,
      InternalServerErrorException$,
      MethodNotAllowedException$,
      NotFoundException$,
      TooManyRequestsException$,
    ],
  });
  runner.run();
}, 30_000);
