import { CreateVocabularyCommandInput, CreateVocabularyCommandOutput } from "../commands/CreateVocabularyCommand";
import { CreateVocabularyFilterCommandInput, CreateVocabularyFilterCommandOutput } from "../commands/CreateVocabularyFilterCommand";
import { DeleteTranscriptionJobCommandInput, DeleteTranscriptionJobCommandOutput } from "../commands/DeleteTranscriptionJobCommand";
import { DeleteVocabularyCommandInput, DeleteVocabularyCommandOutput } from "../commands/DeleteVocabularyCommand";
import { DeleteVocabularyFilterCommandInput, DeleteVocabularyFilterCommandOutput } from "../commands/DeleteVocabularyFilterCommand";
import { GetTranscriptionJobCommandInput, GetTranscriptionJobCommandOutput } from "../commands/GetTranscriptionJobCommand";
import { GetVocabularyCommandInput, GetVocabularyCommandOutput } from "../commands/GetVocabularyCommand";
import { GetVocabularyFilterCommandInput, GetVocabularyFilterCommandOutput } from "../commands/GetVocabularyFilterCommand";
import { ListTranscriptionJobsCommandInput, ListTranscriptionJobsCommandOutput } from "../commands/ListTranscriptionJobsCommand";
import { ListVocabulariesCommandInput, ListVocabulariesCommandOutput } from "../commands/ListVocabulariesCommand";
import { ListVocabularyFiltersCommandInput, ListVocabularyFiltersCommandOutput } from "../commands/ListVocabularyFiltersCommand";
import { StartTranscriptionJobCommandInput, StartTranscriptionJobCommandOutput } from "../commands/StartTranscriptionJobCommand";
import { UpdateVocabularyCommandInput, UpdateVocabularyCommandOutput } from "../commands/UpdateVocabularyCommand";
import { UpdateVocabularyFilterCommandInput, UpdateVocabularyFilterCommandOutput } from "../commands/UpdateVocabularyFilterCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateVocabularyCommand(input: CreateVocabularyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateVocabularyFilterCommand(input: CreateVocabularyFilterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTranscriptionJobCommand(input: DeleteTranscriptionJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVocabularyCommand(input: DeleteVocabularyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVocabularyFilterCommand(input: DeleteVocabularyFilterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTranscriptionJobCommand(input: GetTranscriptionJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetVocabularyCommand(input: GetVocabularyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetVocabularyFilterCommand(input: GetVocabularyFilterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTranscriptionJobsCommand(input: ListTranscriptionJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVocabulariesCommand(input: ListVocabulariesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVocabularyFiltersCommand(input: ListVocabularyFiltersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartTranscriptionJobCommand(input: StartTranscriptionJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVocabularyCommand(input: UpdateVocabularyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVocabularyFilterCommand(input: UpdateVocabularyFilterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateVocabularyCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVocabularyCommandOutput>;
export declare function deserializeAws_json1_1CreateVocabularyFilterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVocabularyFilterCommandOutput>;
export declare function deserializeAws_json1_1DeleteTranscriptionJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTranscriptionJobCommandOutput>;
export declare function deserializeAws_json1_1DeleteVocabularyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVocabularyCommandOutput>;
export declare function deserializeAws_json1_1DeleteVocabularyFilterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVocabularyFilterCommandOutput>;
export declare function deserializeAws_json1_1GetTranscriptionJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTranscriptionJobCommandOutput>;
export declare function deserializeAws_json1_1GetVocabularyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetVocabularyCommandOutput>;
export declare function deserializeAws_json1_1GetVocabularyFilterCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetVocabularyFilterCommandOutput>;
export declare function deserializeAws_json1_1ListTranscriptionJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTranscriptionJobsCommandOutput>;
export declare function deserializeAws_json1_1ListVocabulariesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVocabulariesCommandOutput>;
export declare function deserializeAws_json1_1ListVocabularyFiltersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVocabularyFiltersCommandOutput>;
export declare function deserializeAws_json1_1StartTranscriptionJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartTranscriptionJobCommandOutput>;
export declare function deserializeAws_json1_1UpdateVocabularyCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVocabularyCommandOutput>;
export declare function deserializeAws_json1_1UpdateVocabularyFilterCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVocabularyFilterCommandOutput>;
