import { ActivateEventSourceCommandInput, ActivateEventSourceCommandOutput } from "../commands/ActivateEventSourceCommand";
import { CreateEventBusCommandInput, CreateEventBusCommandOutput } from "../commands/CreateEventBusCommand";
import { CreatePartnerEventSourceCommandInput, CreatePartnerEventSourceCommandOutput } from "../commands/CreatePartnerEventSourceCommand";
import { DeactivateEventSourceCommandInput, DeactivateEventSourceCommandOutput } from "../commands/DeactivateEventSourceCommand";
import { DeleteEventBusCommandInput, DeleteEventBusCommandOutput } from "../commands/DeleteEventBusCommand";
import { DeletePartnerEventSourceCommandInput, DeletePartnerEventSourceCommandOutput } from "../commands/DeletePartnerEventSourceCommand";
import { DeleteRuleCommandInput, DeleteRuleCommandOutput } from "../commands/DeleteRuleCommand";
import { DescribeEventBusCommandInput, DescribeEventBusCommandOutput } from "../commands/DescribeEventBusCommand";
import { DescribeEventSourceCommandInput, DescribeEventSourceCommandOutput } from "../commands/DescribeEventSourceCommand";
import { DescribePartnerEventSourceCommandInput, DescribePartnerEventSourceCommandOutput } from "../commands/DescribePartnerEventSourceCommand";
import { DescribeRuleCommandInput, DescribeRuleCommandOutput } from "../commands/DescribeRuleCommand";
import { DisableRuleCommandInput, DisableRuleCommandOutput } from "../commands/DisableRuleCommand";
import { EnableRuleCommandInput, EnableRuleCommandOutput } from "../commands/EnableRuleCommand";
import { ListEventBusesCommandInput, ListEventBusesCommandOutput } from "../commands/ListEventBusesCommand";
import { ListEventSourcesCommandInput, ListEventSourcesCommandOutput } from "../commands/ListEventSourcesCommand";
import { ListPartnerEventSourceAccountsCommandInput, ListPartnerEventSourceAccountsCommandOutput } from "../commands/ListPartnerEventSourceAccountsCommand";
import { ListPartnerEventSourcesCommandInput, ListPartnerEventSourcesCommandOutput } from "../commands/ListPartnerEventSourcesCommand";
import { ListRuleNamesByTargetCommandInput, ListRuleNamesByTargetCommandOutput } from "../commands/ListRuleNamesByTargetCommand";
import { ListRulesCommandInput, ListRulesCommandOutput } from "../commands/ListRulesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListTargetsByRuleCommandInput, ListTargetsByRuleCommandOutput } from "../commands/ListTargetsByRuleCommand";
import { PutEventsCommandInput, PutEventsCommandOutput } from "../commands/PutEventsCommand";
import { PutPartnerEventsCommandInput, PutPartnerEventsCommandOutput } from "../commands/PutPartnerEventsCommand";
import { PutPermissionCommandInput, PutPermissionCommandOutput } from "../commands/PutPermissionCommand";
import { PutRuleCommandInput, PutRuleCommandOutput } from "../commands/PutRuleCommand";
import { PutTargetsCommandInput, PutTargetsCommandOutput } from "../commands/PutTargetsCommand";
import { RemovePermissionCommandInput, RemovePermissionCommandOutput } from "../commands/RemovePermissionCommand";
import { RemoveTargetsCommandInput, RemoveTargetsCommandOutput } from "../commands/RemoveTargetsCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { TestEventPatternCommandInput, TestEventPatternCommandOutput } from "../commands/TestEventPatternCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1ActivateEventSourceCommand(input: ActivateEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateEventBusCommand(input: CreateEventBusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePartnerEventSourceCommand(input: CreatePartnerEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeactivateEventSourceCommand(input: DeactivateEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteEventBusCommand(input: DeleteEventBusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePartnerEventSourceCommand(input: DeletePartnerEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRuleCommand(input: DeleteRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEventBusCommand(input: DescribeEventBusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEventSourceCommand(input: DescribeEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePartnerEventSourceCommand(input: DescribePartnerEventSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeRuleCommand(input: DescribeRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisableRuleCommand(input: DisableRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1EnableRuleCommand(input: EnableRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListEventBusesCommand(input: ListEventBusesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListEventSourcesCommand(input: ListEventSourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPartnerEventSourceAccountsCommand(input: ListPartnerEventSourceAccountsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPartnerEventSourcesCommand(input: ListPartnerEventSourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRuleNamesByTargetCommand(input: ListRuleNamesByTargetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRulesCommand(input: ListRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTargetsByRuleCommand(input: ListTargetsByRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutEventsCommand(input: PutEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutPartnerEventsCommand(input: PutPartnerEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutPermissionCommand(input: PutPermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutRuleCommand(input: PutRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutTargetsCommand(input: PutTargetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemovePermissionCommand(input: RemovePermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTargetsCommand(input: RemoveTargetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TestEventPatternCommand(input: TestEventPatternCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1ActivateEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ActivateEventSourceCommandOutput>;
export declare function deserializeAws_json1_1CreateEventBusCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateEventBusCommandOutput>;
export declare function deserializeAws_json1_1CreatePartnerEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePartnerEventSourceCommandOutput>;
export declare function deserializeAws_json1_1DeactivateEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeactivateEventSourceCommandOutput>;
export declare function deserializeAws_json1_1DeleteEventBusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEventBusCommandOutput>;
export declare function deserializeAws_json1_1DeletePartnerEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePartnerEventSourceCommandOutput>;
export declare function deserializeAws_json1_1DeleteRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRuleCommandOutput>;
export declare function deserializeAws_json1_1DescribeEventBusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventBusCommandOutput>;
export declare function deserializeAws_json1_1DescribeEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventSourceCommandOutput>;
export declare function deserializeAws_json1_1DescribePartnerEventSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePartnerEventSourceCommandOutput>;
export declare function deserializeAws_json1_1DescribeRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeRuleCommandOutput>;
export declare function deserializeAws_json1_1DisableRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableRuleCommandOutput>;
export declare function deserializeAws_json1_1EnableRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableRuleCommandOutput>;
export declare function deserializeAws_json1_1ListEventBusesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListEventBusesCommandOutput>;
export declare function deserializeAws_json1_1ListEventSourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListEventSourcesCommandOutput>;
export declare function deserializeAws_json1_1ListPartnerEventSourceAccountsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPartnerEventSourceAccountsCommandOutput>;
export declare function deserializeAws_json1_1ListPartnerEventSourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPartnerEventSourcesCommandOutput>;
export declare function deserializeAws_json1_1ListRuleNamesByTargetCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRuleNamesByTargetCommandOutput>;
export declare function deserializeAws_json1_1ListRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRulesCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListTargetsByRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTargetsByRuleCommandOutput>;
export declare function deserializeAws_json1_1PutEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutEventsCommandOutput>;
export declare function deserializeAws_json1_1PutPartnerEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutPartnerEventsCommandOutput>;
export declare function deserializeAws_json1_1PutPermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutPermissionCommandOutput>;
export declare function deserializeAws_json1_1PutRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutRuleCommandOutput>;
export declare function deserializeAws_json1_1PutTargetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutTargetsCommandOutput>;
export declare function deserializeAws_json1_1RemovePermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemovePermissionCommandOutput>;
export declare function deserializeAws_json1_1RemoveTargetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTargetsCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1TestEventPatternCommand(output: __HttpResponse, context: __SerdeContext): Promise<TestEventPatternCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
