import { BatchDeleteDocumentCommandInput, BatchDeleteDocumentCommandOutput } from "../commands/BatchDeleteDocumentCommand";
import { BatchPutDocumentCommandInput, BatchPutDocumentCommandOutput } from "../commands/BatchPutDocumentCommand";
import { CreateDataSourceCommandInput, CreateDataSourceCommandOutput } from "../commands/CreateDataSourceCommand";
import { CreateFaqCommandInput, CreateFaqCommandOutput } from "../commands/CreateFaqCommand";
import { CreateIndexCommandInput, CreateIndexCommandOutput } from "../commands/CreateIndexCommand";
import { DeleteFaqCommandInput, DeleteFaqCommandOutput } from "../commands/DeleteFaqCommand";
import { DeleteIndexCommandInput, DeleteIndexCommandOutput } from "../commands/DeleteIndexCommand";
import { DescribeDataSourceCommandInput, DescribeDataSourceCommandOutput } from "../commands/DescribeDataSourceCommand";
import { DescribeFaqCommandInput, DescribeFaqCommandOutput } from "../commands/DescribeFaqCommand";
import { DescribeIndexCommandInput, DescribeIndexCommandOutput } from "../commands/DescribeIndexCommand";
import { ListDataSourceSyncJobsCommandInput, ListDataSourceSyncJobsCommandOutput } from "../commands/ListDataSourceSyncJobsCommand";
import { ListDataSourcesCommandInput, ListDataSourcesCommandOutput } from "../commands/ListDataSourcesCommand";
import { ListFaqsCommandInput, ListFaqsCommandOutput } from "../commands/ListFaqsCommand";
import { ListIndicesCommandInput, ListIndicesCommandOutput } from "../commands/ListIndicesCommand";
import { QueryCommandInput, QueryCommandOutput } from "../commands/QueryCommand";
import { StartDataSourceSyncJobCommandInput, StartDataSourceSyncJobCommandOutput } from "../commands/StartDataSourceSyncJobCommand";
import { StopDataSourceSyncJobCommandInput, StopDataSourceSyncJobCommandOutput } from "../commands/StopDataSourceSyncJobCommand";
import { SubmitFeedbackCommandInput, SubmitFeedbackCommandOutput } from "../commands/SubmitFeedbackCommand";
import { UpdateDataSourceCommandInput, UpdateDataSourceCommandOutput } from "../commands/UpdateDataSourceCommand";
import { UpdateIndexCommandInput, UpdateIndexCommandOutput } from "../commands/UpdateIndexCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1BatchDeleteDocumentCommand(input: BatchDeleteDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchPutDocumentCommand(input: BatchPutDocumentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDataSourceCommand(input: CreateDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateFaqCommand(input: CreateFaqCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateIndexCommand(input: CreateIndexCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteFaqCommand(input: DeleteFaqCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteIndexCommand(input: DeleteIndexCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDataSourceCommand(input: DescribeDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFaqCommand(input: DescribeFaqCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeIndexCommand(input: DescribeIndexCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDataSourceSyncJobsCommand(input: ListDataSourceSyncJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDataSourcesCommand(input: ListDataSourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListFaqsCommand(input: ListFaqsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListIndicesCommand(input: ListIndicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1QueryCommand(input: QueryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartDataSourceSyncJobCommand(input: StartDataSourceSyncJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopDataSourceSyncJobCommand(input: StopDataSourceSyncJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SubmitFeedbackCommand(input: SubmitFeedbackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDataSourceCommand(input: UpdateDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateIndexCommand(input: UpdateIndexCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1BatchDeleteDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeleteDocumentCommandOutput>;
export declare function deserializeAws_json1_1BatchPutDocumentCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchPutDocumentCommandOutput>;
export declare function deserializeAws_json1_1CreateDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDataSourceCommandOutput>;
export declare function deserializeAws_json1_1CreateFaqCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateFaqCommandOutput>;
export declare function deserializeAws_json1_1CreateIndexCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateIndexCommandOutput>;
export declare function deserializeAws_json1_1DeleteFaqCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFaqCommandOutput>;
export declare function deserializeAws_json1_1DeleteIndexCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteIndexCommandOutput>;
export declare function deserializeAws_json1_1DescribeDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDataSourceCommandOutput>;
export declare function deserializeAws_json1_1DescribeFaqCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFaqCommandOutput>;
export declare function deserializeAws_json1_1DescribeIndexCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeIndexCommandOutput>;
export declare function deserializeAws_json1_1ListDataSourceSyncJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDataSourceSyncJobsCommandOutput>;
export declare function deserializeAws_json1_1ListDataSourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDataSourcesCommandOutput>;
export declare function deserializeAws_json1_1ListFaqsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFaqsCommandOutput>;
export declare function deserializeAws_json1_1ListIndicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListIndicesCommandOutput>;
export declare function deserializeAws_json1_1QueryCommand(output: __HttpResponse, context: __SerdeContext): Promise<QueryCommandOutput>;
export declare function deserializeAws_json1_1StartDataSourceSyncJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartDataSourceSyncJobCommandOutput>;
export declare function deserializeAws_json1_1StopDataSourceSyncJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopDataSourceSyncJobCommandOutput>;
export declare function deserializeAws_json1_1SubmitFeedbackCommand(output: __HttpResponse, context: __SerdeContext): Promise<SubmitFeedbackCommandOutput>;
export declare function deserializeAws_json1_1UpdateDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDataSourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateIndexCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateIndexCommandOutput>;
