// smithy-typescript generated code
export type {
  CloudSearchDomainClient,
  CloudSearchDomain,
  SearchCommand,
  SearchCommandInput,
  SearchCommandOutput,
  SuggestCommand,
  SuggestCommandInput,
  SuggestCommandOutput,
  UploadDocumentsCommand,
  UploadDocumentsCommandInput,
  UploadDocumentsCommandOutput,
  ContentType,
  QueryParser,
  Bucket,
  BucketInfo,
  DocumentServiceWarning,
  FieldStats,
  Hit,
  Hits,
  SearchRequest,
  SearchResponse,
  SearchStatus,
  SuggestionMatch,
  SuggestModel,
  SuggestRequest,
  SuggestResponse,
  SuggestStatus,
  UploadDocumentsRequest,
  UploadDocumentsResponse,
  CloudSearchDomainServiceException,
} from "../dist-types/index.d";
