import { AddTagsCommandInput, AddTagsCommandOutput } from "../commands/AddTagsCommand";
import { CreateBatchPredictionCommandInput, CreateBatchPredictionCommandOutput } from "../commands/CreateBatchPredictionCommand";
import { CreateDataSourceFromRDSCommandInput, CreateDataSourceFromRDSCommandOutput } from "../commands/CreateDataSourceFromRDSCommand";
import { CreateDataSourceFromRedshiftCommandInput, CreateDataSourceFromRedshiftCommandOutput } from "../commands/CreateDataSourceFromRedshiftCommand";
import { CreateDataSourceFromS3CommandInput, CreateDataSourceFromS3CommandOutput } from "../commands/CreateDataSourceFromS3Command";
import { CreateEvaluationCommandInput, CreateEvaluationCommandOutput } from "../commands/CreateEvaluationCommand";
import { CreateMLModelCommandInput, CreateMLModelCommandOutput } from "../commands/CreateMLModelCommand";
import { CreateRealtimeEndpointCommandInput, CreateRealtimeEndpointCommandOutput } from "../commands/CreateRealtimeEndpointCommand";
import { DeleteBatchPredictionCommandInput, DeleteBatchPredictionCommandOutput } from "../commands/DeleteBatchPredictionCommand";
import { DeleteDataSourceCommandInput, DeleteDataSourceCommandOutput } from "../commands/DeleteDataSourceCommand";
import { DeleteEvaluationCommandInput, DeleteEvaluationCommandOutput } from "../commands/DeleteEvaluationCommand";
import { DeleteMLModelCommandInput, DeleteMLModelCommandOutput } from "../commands/DeleteMLModelCommand";
import { DeleteRealtimeEndpointCommandInput, DeleteRealtimeEndpointCommandOutput } from "../commands/DeleteRealtimeEndpointCommand";
import { DeleteTagsCommandInput, DeleteTagsCommandOutput } from "../commands/DeleteTagsCommand";
import { DescribeBatchPredictionsCommandInput, DescribeBatchPredictionsCommandOutput } from "../commands/DescribeBatchPredictionsCommand";
import { DescribeDataSourcesCommandInput, DescribeDataSourcesCommandOutput } from "../commands/DescribeDataSourcesCommand";
import { DescribeEvaluationsCommandInput, DescribeEvaluationsCommandOutput } from "../commands/DescribeEvaluationsCommand";
import { DescribeMLModelsCommandInput, DescribeMLModelsCommandOutput } from "../commands/DescribeMLModelsCommand";
import { DescribeTagsCommandInput, DescribeTagsCommandOutput } from "../commands/DescribeTagsCommand";
import { GetBatchPredictionCommandInput, GetBatchPredictionCommandOutput } from "../commands/GetBatchPredictionCommand";
import { GetDataSourceCommandInput, GetDataSourceCommandOutput } from "../commands/GetDataSourceCommand";
import { GetEvaluationCommandInput, GetEvaluationCommandOutput } from "../commands/GetEvaluationCommand";
import { GetMLModelCommandInput, GetMLModelCommandOutput } from "../commands/GetMLModelCommand";
import { PredictCommandInput, PredictCommandOutput } from "../commands/PredictCommand";
import { UpdateBatchPredictionCommandInput, UpdateBatchPredictionCommandOutput } from "../commands/UpdateBatchPredictionCommand";
import { UpdateDataSourceCommandInput, UpdateDataSourceCommandOutput } from "../commands/UpdateDataSourceCommand";
import { UpdateEvaluationCommandInput, UpdateEvaluationCommandOutput } from "../commands/UpdateEvaluationCommand";
import { UpdateMLModelCommandInput, UpdateMLModelCommandOutput } from "../commands/UpdateMLModelCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddTagsCommand(input: AddTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateBatchPredictionCommand(input: CreateBatchPredictionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDataSourceFromRDSCommand(input: CreateDataSourceFromRDSCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDataSourceFromRedshiftCommand(input: CreateDataSourceFromRedshiftCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDataSourceFromS3Command(input: CreateDataSourceFromS3CommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateEvaluationCommand(input: CreateEvaluationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateMLModelCommand(input: CreateMLModelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRealtimeEndpointCommand(input: CreateRealtimeEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBatchPredictionCommand(input: DeleteBatchPredictionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDataSourceCommand(input: DeleteDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteEvaluationCommand(input: DeleteEvaluationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMLModelCommand(input: DeleteMLModelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRealtimeEndpointCommand(input: DeleteRealtimeEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTagsCommand(input: DeleteTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBatchPredictionsCommand(input: DescribeBatchPredictionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDataSourcesCommand(input: DescribeDataSourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEvaluationsCommand(input: DescribeEvaluationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMLModelsCommand(input: DescribeMLModelsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTagsCommand(input: DescribeTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetBatchPredictionCommand(input: GetBatchPredictionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDataSourceCommand(input: GetDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetEvaluationCommand(input: GetEvaluationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMLModelCommand(input: GetMLModelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PredictCommand(input: PredictCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateBatchPredictionCommand(input: UpdateBatchPredictionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDataSourceCommand(input: UpdateDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateEvaluationCommand(input: UpdateEvaluationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMLModelCommand(input: UpdateMLModelCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsCommandOutput>;
export declare function deserializeAws_json1_1CreateBatchPredictionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBatchPredictionCommandOutput>;
export declare function deserializeAws_json1_1CreateDataSourceFromRDSCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDataSourceFromRDSCommandOutput>;
export declare function deserializeAws_json1_1CreateDataSourceFromRedshiftCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDataSourceFromRedshiftCommandOutput>;
export declare function deserializeAws_json1_1CreateDataSourceFromS3Command(output: __HttpResponse, context: __SerdeContext): Promise<CreateDataSourceFromS3CommandOutput>;
export declare function deserializeAws_json1_1CreateEvaluationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateEvaluationCommandOutput>;
export declare function deserializeAws_json1_1CreateMLModelCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMLModelCommandOutput>;
export declare function deserializeAws_json1_1CreateRealtimeEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRealtimeEndpointCommandOutput>;
export declare function deserializeAws_json1_1DeleteBatchPredictionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBatchPredictionCommandOutput>;
export declare function deserializeAws_json1_1DeleteDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDataSourceCommandOutput>;
export declare function deserializeAws_json1_1DeleteEvaluationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEvaluationCommandOutput>;
export declare function deserializeAws_json1_1DeleteMLModelCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMLModelCommandOutput>;
export declare function deserializeAws_json1_1DeleteRealtimeEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRealtimeEndpointCommandOutput>;
export declare function deserializeAws_json1_1DeleteTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTagsCommandOutput>;
export declare function deserializeAws_json1_1DescribeBatchPredictionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBatchPredictionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeDataSourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDataSourcesCommandOutput>;
export declare function deserializeAws_json1_1DescribeEvaluationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEvaluationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMLModelsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMLModelsCommandOutput>;
export declare function deserializeAws_json1_1DescribeTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTagsCommandOutput>;
export declare function deserializeAws_json1_1GetBatchPredictionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetBatchPredictionCommandOutput>;
export declare function deserializeAws_json1_1GetDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDataSourceCommandOutput>;
export declare function deserializeAws_json1_1GetEvaluationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetEvaluationCommandOutput>;
export declare function deserializeAws_json1_1GetMLModelCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMLModelCommandOutput>;
export declare function deserializeAws_json1_1PredictCommand(output: __HttpResponse, context: __SerdeContext): Promise<PredictCommandOutput>;
export declare function deserializeAws_json1_1UpdateBatchPredictionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateBatchPredictionCommandOutput>;
export declare function deserializeAws_json1_1UpdateDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDataSourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateEvaluationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateEvaluationCommandOutput>;
export declare function deserializeAws_json1_1UpdateMLModelCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMLModelCommandOutput>;
