import { ActivatePipelineCommandInput, ActivatePipelineCommandOutput } from "../commands/ActivatePipelineCommand";
import { AddTagsCommandInput, AddTagsCommandOutput } from "../commands/AddTagsCommand";
import { CreatePipelineCommandInput, CreatePipelineCommandOutput } from "../commands/CreatePipelineCommand";
import { DeactivatePipelineCommandInput, DeactivatePipelineCommandOutput } from "../commands/DeactivatePipelineCommand";
import { DeletePipelineCommandInput, DeletePipelineCommandOutput } from "../commands/DeletePipelineCommand";
import { DescribeObjectsCommandInput, DescribeObjectsCommandOutput } from "../commands/DescribeObjectsCommand";
import { DescribePipelinesCommandInput, DescribePipelinesCommandOutput } from "../commands/DescribePipelinesCommand";
import { EvaluateExpressionCommandInput, EvaluateExpressionCommandOutput } from "../commands/EvaluateExpressionCommand";
import { GetPipelineDefinitionCommandInput, GetPipelineDefinitionCommandOutput } from "../commands/GetPipelineDefinitionCommand";
import { ListPipelinesCommandInput, ListPipelinesCommandOutput } from "../commands/ListPipelinesCommand";
import { PollForTaskCommandInput, PollForTaskCommandOutput } from "../commands/PollForTaskCommand";
import { PutPipelineDefinitionCommandInput, PutPipelineDefinitionCommandOutput } from "../commands/PutPipelineDefinitionCommand";
import { QueryObjectsCommandInput, QueryObjectsCommandOutput } from "../commands/QueryObjectsCommand";
import { RemoveTagsCommandInput, RemoveTagsCommandOutput } from "../commands/RemoveTagsCommand";
import { ReportTaskProgressCommandInput, ReportTaskProgressCommandOutput } from "../commands/ReportTaskProgressCommand";
import { ReportTaskRunnerHeartbeatCommandInput, ReportTaskRunnerHeartbeatCommandOutput } from "../commands/ReportTaskRunnerHeartbeatCommand";
import { SetStatusCommandInput, SetStatusCommandOutput } from "../commands/SetStatusCommand";
import { SetTaskStatusCommandInput, SetTaskStatusCommandOutput } from "../commands/SetTaskStatusCommand";
import { ValidatePipelineDefinitionCommandInput, ValidatePipelineDefinitionCommandOutput } from "../commands/ValidatePipelineDefinitionCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1ActivatePipelineCommand(input: ActivatePipelineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddTagsCommand(input: AddTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePipelineCommand(input: CreatePipelineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeactivatePipelineCommand(input: DeactivatePipelineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePipelineCommand(input: DeletePipelineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeObjectsCommand(input: DescribeObjectsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePipelinesCommand(input: DescribePipelinesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1EvaluateExpressionCommand(input: EvaluateExpressionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPipelineDefinitionCommand(input: GetPipelineDefinitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPipelinesCommand(input: ListPipelinesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PollForTaskCommand(input: PollForTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutPipelineDefinitionCommand(input: PutPipelineDefinitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1QueryObjectsCommand(input: QueryObjectsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTagsCommand(input: RemoveTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ReportTaskProgressCommand(input: ReportTaskProgressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ReportTaskRunnerHeartbeatCommand(input: ReportTaskRunnerHeartbeatCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetStatusCommand(input: SetStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetTaskStatusCommand(input: SetTaskStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ValidatePipelineDefinitionCommand(input: ValidatePipelineDefinitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1ActivatePipelineCommand(output: __HttpResponse, context: __SerdeContext): Promise<ActivatePipelineCommandOutput>;
export declare function deserializeAws_json1_1AddTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsCommandOutput>;
export declare function deserializeAws_json1_1CreatePipelineCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePipelineCommandOutput>;
export declare function deserializeAws_json1_1DeactivatePipelineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeactivatePipelineCommandOutput>;
export declare function deserializeAws_json1_1DeletePipelineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePipelineCommandOutput>;
export declare function deserializeAws_json1_1DescribeObjectsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeObjectsCommandOutput>;
export declare function deserializeAws_json1_1DescribePipelinesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePipelinesCommandOutput>;
export declare function deserializeAws_json1_1EvaluateExpressionCommand(output: __HttpResponse, context: __SerdeContext): Promise<EvaluateExpressionCommandOutput>;
export declare function deserializeAws_json1_1GetPipelineDefinitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPipelineDefinitionCommandOutput>;
export declare function deserializeAws_json1_1ListPipelinesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPipelinesCommandOutput>;
export declare function deserializeAws_json1_1PollForTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<PollForTaskCommandOutput>;
export declare function deserializeAws_json1_1PutPipelineDefinitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutPipelineDefinitionCommandOutput>;
export declare function deserializeAws_json1_1QueryObjectsCommand(output: __HttpResponse, context: __SerdeContext): Promise<QueryObjectsCommandOutput>;
export declare function deserializeAws_json1_1RemoveTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsCommandOutput>;
export declare function deserializeAws_json1_1ReportTaskProgressCommand(output: __HttpResponse, context: __SerdeContext): Promise<ReportTaskProgressCommandOutput>;
export declare function deserializeAws_json1_1ReportTaskRunnerHeartbeatCommand(output: __HttpResponse, context: __SerdeContext): Promise<ReportTaskRunnerHeartbeatCommandOutput>;
export declare function deserializeAws_json1_1SetStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetStatusCommandOutput>;
export declare function deserializeAws_json1_1SetTaskStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetTaskStatusCommandOutput>;
export declare function deserializeAws_json1_1ValidatePipelineDefinitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ValidatePipelineDefinitionCommandOutput>;
