import { AssociateDelegateToResourceCommandInput, AssociateDelegateToResourceCommandOutput } from "../commands/AssociateDelegateToResourceCommand";
import { AssociateMemberToGroupCommandInput, AssociateMemberToGroupCommandOutput } from "../commands/AssociateMemberToGroupCommand";
import { CreateAliasCommandInput, CreateAliasCommandOutput } from "../commands/CreateAliasCommand";
import { CreateGroupCommandInput, CreateGroupCommandOutput } from "../commands/CreateGroupCommand";
import { CreateResourceCommandInput, CreateResourceCommandOutput } from "../commands/CreateResourceCommand";
import { CreateUserCommandInput, CreateUserCommandOutput } from "../commands/CreateUserCommand";
import { DeleteAliasCommandInput, DeleteAliasCommandOutput } from "../commands/DeleteAliasCommand";
import { DeleteGroupCommandInput, DeleteGroupCommandOutput } from "../commands/DeleteGroupCommand";
import { DeleteMailboxPermissionsCommandInput, DeleteMailboxPermissionsCommandOutput } from "../commands/DeleteMailboxPermissionsCommand";
import { DeleteResourceCommandInput, DeleteResourceCommandOutput } from "../commands/DeleteResourceCommand";
import { DeleteUserCommandInput, DeleteUserCommandOutput } from "../commands/DeleteUserCommand";
import { DeregisterFromWorkMailCommandInput, DeregisterFromWorkMailCommandOutput } from "../commands/DeregisterFromWorkMailCommand";
import { DescribeGroupCommandInput, DescribeGroupCommandOutput } from "../commands/DescribeGroupCommand";
import { DescribeOrganizationCommandInput, DescribeOrganizationCommandOutput } from "../commands/DescribeOrganizationCommand";
import { DescribeResourceCommandInput, DescribeResourceCommandOutput } from "../commands/DescribeResourceCommand";
import { DescribeUserCommandInput, DescribeUserCommandOutput } from "../commands/DescribeUserCommand";
import { DisassociateDelegateFromResourceCommandInput, DisassociateDelegateFromResourceCommandOutput } from "../commands/DisassociateDelegateFromResourceCommand";
import { DisassociateMemberFromGroupCommandInput, DisassociateMemberFromGroupCommandOutput } from "../commands/DisassociateMemberFromGroupCommand";
import { GetMailboxDetailsCommandInput, GetMailboxDetailsCommandOutput } from "../commands/GetMailboxDetailsCommand";
import { ListAliasesCommandInput, ListAliasesCommandOutput } from "../commands/ListAliasesCommand";
import { ListGroupMembersCommandInput, ListGroupMembersCommandOutput } from "../commands/ListGroupMembersCommand";
import { ListGroupsCommandInput, ListGroupsCommandOutput } from "../commands/ListGroupsCommand";
import { ListMailboxPermissionsCommandInput, ListMailboxPermissionsCommandOutput } from "../commands/ListMailboxPermissionsCommand";
import { ListOrganizationsCommandInput, ListOrganizationsCommandOutput } from "../commands/ListOrganizationsCommand";
import { ListResourceDelegatesCommandInput, ListResourceDelegatesCommandOutput } from "../commands/ListResourceDelegatesCommand";
import { ListResourcesCommandInput, ListResourcesCommandOutput } from "../commands/ListResourcesCommand";
import { ListUsersCommandInput, ListUsersCommandOutput } from "../commands/ListUsersCommand";
import { PutMailboxPermissionsCommandInput, PutMailboxPermissionsCommandOutput } from "../commands/PutMailboxPermissionsCommand";
import { RegisterToWorkMailCommandInput, RegisterToWorkMailCommandOutput } from "../commands/RegisterToWorkMailCommand";
import { ResetPasswordCommandInput, ResetPasswordCommandOutput } from "../commands/ResetPasswordCommand";
import { UpdateMailboxQuotaCommandInput, UpdateMailboxQuotaCommandOutput } from "../commands/UpdateMailboxQuotaCommand";
import { UpdatePrimaryEmailAddressCommandInput, UpdatePrimaryEmailAddressCommandOutput } from "../commands/UpdatePrimaryEmailAddressCommand";
import { UpdateResourceCommandInput, UpdateResourceCommandOutput } from "../commands/UpdateResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateDelegateToResourceCommand(input: AssociateDelegateToResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateMemberToGroupCommand(input: AssociateMemberToGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAliasCommand(input: CreateAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateGroupCommand(input: CreateGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateResourceCommand(input: CreateResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateUserCommand(input: CreateUserCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAliasCommand(input: DeleteAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteGroupCommand(input: DeleteGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMailboxPermissionsCommand(input: DeleteMailboxPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteResourceCommand(input: DeleteResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteUserCommand(input: DeleteUserCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterFromWorkMailCommand(input: DeregisterFromWorkMailCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGroupCommand(input: DescribeGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeOrganizationCommand(input: DescribeOrganizationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeResourceCommand(input: DescribeResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeUserCommand(input: DescribeUserCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateDelegateFromResourceCommand(input: DisassociateDelegateFromResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateMemberFromGroupCommand(input: DisassociateMemberFromGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMailboxDetailsCommand(input: GetMailboxDetailsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAliasesCommand(input: ListAliasesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListGroupMembersCommand(input: ListGroupMembersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListGroupsCommand(input: ListGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListMailboxPermissionsCommand(input: ListMailboxPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListOrganizationsCommand(input: ListOrganizationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourceDelegatesCommand(input: ListResourceDelegatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourcesCommand(input: ListResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListUsersCommand(input: ListUsersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutMailboxPermissionsCommand(input: PutMailboxPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterToWorkMailCommand(input: RegisterToWorkMailCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResetPasswordCommand(input: ResetPasswordCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMailboxQuotaCommand(input: UpdateMailboxQuotaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePrimaryEmailAddressCommand(input: UpdatePrimaryEmailAddressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateResourceCommand(input: UpdateResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateDelegateToResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateDelegateToResourceCommandOutput>;
export declare function deserializeAws_json1_1AssociateMemberToGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateMemberToGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAliasCommandOutput>;
export declare function deserializeAws_json1_1CreateGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateResourceCommandOutput>;
export declare function deserializeAws_json1_1CreateUserCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateUserCommandOutput>;
export declare function deserializeAws_json1_1DeleteAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAliasCommandOutput>;
export declare function deserializeAws_json1_1DeleteGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteMailboxPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMailboxPermissionsCommandOutput>;
export declare function deserializeAws_json1_1DeleteResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteResourceCommandOutput>;
export declare function deserializeAws_json1_1DeleteUserCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteUserCommandOutput>;
export declare function deserializeAws_json1_1DeregisterFromWorkMailCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterFromWorkMailCommandOutput>;
export declare function deserializeAws_json1_1DescribeGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGroupCommandOutput>;
export declare function deserializeAws_json1_1DescribeOrganizationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeOrganizationCommandOutput>;
export declare function deserializeAws_json1_1DescribeResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeResourceCommandOutput>;
export declare function deserializeAws_json1_1DescribeUserCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeUserCommandOutput>;
export declare function deserializeAws_json1_1DisassociateDelegateFromResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateDelegateFromResourceCommandOutput>;
export declare function deserializeAws_json1_1DisassociateMemberFromGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateMemberFromGroupCommandOutput>;
export declare function deserializeAws_json1_1GetMailboxDetailsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMailboxDetailsCommandOutput>;
export declare function deserializeAws_json1_1ListAliasesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAliasesCommandOutput>;
export declare function deserializeAws_json1_1ListGroupMembersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListGroupMembersCommandOutput>;
export declare function deserializeAws_json1_1ListGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListMailboxPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListMailboxPermissionsCommandOutput>;
export declare function deserializeAws_json1_1ListOrganizationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOrganizationsCommandOutput>;
export declare function deserializeAws_json1_1ListResourceDelegatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourceDelegatesCommandOutput>;
export declare function deserializeAws_json1_1ListResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourcesCommandOutput>;
export declare function deserializeAws_json1_1ListUsersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListUsersCommandOutput>;
export declare function deserializeAws_json1_1PutMailboxPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutMailboxPermissionsCommandOutput>;
export declare function deserializeAws_json1_1RegisterToWorkMailCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterToWorkMailCommandOutput>;
export declare function deserializeAws_json1_1ResetPasswordCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetPasswordCommandOutput>;
export declare function deserializeAws_json1_1UpdateMailboxQuotaCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMailboxQuotaCommandOutput>;
export declare function deserializeAws_json1_1UpdatePrimaryEmailAddressCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePrimaryEmailAddressCommandOutput>;
export declare function deserializeAws_json1_1UpdateResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateResourceCommandOutput>;
