export * from "./client";
export * from "./command";
export * from "./emitWarningIfUnsupportedVersion";
export * from "./extended-encode-uri-component";
export * from "./get-array-if-single-item";
export * from "./get-value-from-text-node";
export * from "./lazy-json";
export * from "./parse-utils";
export * from "./ser-utils";
export * from "./date-utils";
export * from "./split-every";
export * from "./constants";
export type { DocumentType, SdkError, SmithyException } from "@aws-sdk/types";
