import { AssociateResolverEndpointIpAddressCommandInput, AssociateResolverEndpointIpAddressCommandOutput } from "../commands/AssociateResolverEndpointIpAddressCommand";
import { AssociateResolverRuleCommandInput, AssociateResolverRuleCommandOutput } from "../commands/AssociateResolverRuleCommand";
import { CreateResolverEndpointCommandInput, CreateResolverEndpointCommandOutput } from "../commands/CreateResolverEndpointCommand";
import { CreateResolverRuleCommandInput, CreateResolverRuleCommandOutput } from "../commands/CreateResolverRuleCommand";
import { DeleteResolverEndpointCommandInput, DeleteResolverEndpointCommandOutput } from "../commands/DeleteResolverEndpointCommand";
import { DeleteResolverRuleCommandInput, DeleteResolverRuleCommandOutput } from "../commands/DeleteResolverRuleCommand";
import { DisassociateResolverEndpointIpAddressCommandInput, DisassociateResolverEndpointIpAddressCommandOutput } from "../commands/DisassociateResolverEndpointIpAddressCommand";
import { DisassociateResolverRuleCommandInput, DisassociateResolverRuleCommandOutput } from "../commands/DisassociateResolverRuleCommand";
import { GetResolverEndpointCommandInput, GetResolverEndpointCommandOutput } from "../commands/GetResolverEndpointCommand";
import { GetResolverRuleAssociationCommandInput, GetResolverRuleAssociationCommandOutput } from "../commands/GetResolverRuleAssociationCommand";
import { GetResolverRuleCommandInput, GetResolverRuleCommandOutput } from "../commands/GetResolverRuleCommand";
import { GetResolverRulePolicyCommandInput, GetResolverRulePolicyCommandOutput } from "../commands/GetResolverRulePolicyCommand";
import { ListResolverEndpointIpAddressesCommandInput, ListResolverEndpointIpAddressesCommandOutput } from "../commands/ListResolverEndpointIpAddressesCommand";
import { ListResolverEndpointsCommandInput, ListResolverEndpointsCommandOutput } from "../commands/ListResolverEndpointsCommand";
import { ListResolverRuleAssociationsCommandInput, ListResolverRuleAssociationsCommandOutput } from "../commands/ListResolverRuleAssociationsCommand";
import { ListResolverRulesCommandInput, ListResolverRulesCommandOutput } from "../commands/ListResolverRulesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { PutResolverRulePolicyCommandInput, PutResolverRulePolicyCommandOutput } from "../commands/PutResolverRulePolicyCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateResolverEndpointCommandInput, UpdateResolverEndpointCommandOutput } from "../commands/UpdateResolverEndpointCommand";
import { UpdateResolverRuleCommandInput, UpdateResolverRuleCommandOutput } from "../commands/UpdateResolverRuleCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateResolverEndpointIpAddressCommand(input: AssociateResolverEndpointIpAddressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateResolverRuleCommand(input: AssociateResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateResolverEndpointCommand(input: CreateResolverEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateResolverRuleCommand(input: CreateResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteResolverEndpointCommand(input: DeleteResolverEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteResolverRuleCommand(input: DeleteResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateResolverEndpointIpAddressCommand(input: DisassociateResolverEndpointIpAddressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateResolverRuleCommand(input: DisassociateResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResolverEndpointCommand(input: GetResolverEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResolverRuleCommand(input: GetResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResolverRuleAssociationCommand(input: GetResolverRuleAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResolverRulePolicyCommand(input: GetResolverRulePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResolverEndpointIpAddressesCommand(input: ListResolverEndpointIpAddressesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResolverEndpointsCommand(input: ListResolverEndpointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResolverRuleAssociationsCommand(input: ListResolverRuleAssociationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResolverRulesCommand(input: ListResolverRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutResolverRulePolicyCommand(input: PutResolverRulePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateResolverEndpointCommand(input: UpdateResolverEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateResolverRuleCommand(input: UpdateResolverRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateResolverEndpointIpAddressCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateResolverEndpointIpAddressCommandOutput>;
export declare function deserializeAws_json1_1AssociateResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateResolverRuleCommandOutput>;
export declare function deserializeAws_json1_1CreateResolverEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateResolverEndpointCommandOutput>;
export declare function deserializeAws_json1_1CreateResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateResolverRuleCommandOutput>;
export declare function deserializeAws_json1_1DeleteResolverEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteResolverEndpointCommandOutput>;
export declare function deserializeAws_json1_1DeleteResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteResolverRuleCommandOutput>;
export declare function deserializeAws_json1_1DisassociateResolverEndpointIpAddressCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateResolverEndpointIpAddressCommandOutput>;
export declare function deserializeAws_json1_1DisassociateResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateResolverRuleCommandOutput>;
export declare function deserializeAws_json1_1GetResolverEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResolverEndpointCommandOutput>;
export declare function deserializeAws_json1_1GetResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResolverRuleCommandOutput>;
export declare function deserializeAws_json1_1GetResolverRuleAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResolverRuleAssociationCommandOutput>;
export declare function deserializeAws_json1_1GetResolverRulePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResolverRulePolicyCommandOutput>;
export declare function deserializeAws_json1_1ListResolverEndpointIpAddressesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResolverEndpointIpAddressesCommandOutput>;
export declare function deserializeAws_json1_1ListResolverEndpointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResolverEndpointsCommandOutput>;
export declare function deserializeAws_json1_1ListResolverRuleAssociationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResolverRuleAssociationsCommandOutput>;
export declare function deserializeAws_json1_1ListResolverRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResolverRulesCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1PutResolverRulePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutResolverRulePolicyCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateResolverEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateResolverEndpointCommandOutput>;
export declare function deserializeAws_json1_1UpdateResolverRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateResolverRuleCommandOutput>;
