import { BuildSuggestersCommandInput, BuildSuggestersCommandOutput } from "../commands/BuildSuggestersCommand";
import { CreateDomainCommandInput, CreateDomainCommandOutput } from "../commands/CreateDomainCommand";
import { DefineAnalysisSchemeCommandInput, DefineAnalysisSchemeCommandOutput } from "../commands/DefineAnalysisSchemeCommand";
import { DefineExpressionCommandInput, DefineExpressionCommandOutput } from "../commands/DefineExpressionCommand";
import { DefineIndexFieldCommandInput, DefineIndexFieldCommandOutput } from "../commands/DefineIndexFieldCommand";
import { DefineSuggesterCommandInput, DefineSuggesterCommandOutput } from "../commands/DefineSuggesterCommand";
import { DeleteAnalysisSchemeCommandInput, DeleteAnalysisSchemeCommandOutput } from "../commands/DeleteAnalysisSchemeCommand";
import { DeleteDomainCommandInput, DeleteDomainCommandOutput } from "../commands/DeleteDomainCommand";
import { DeleteExpressionCommandInput, DeleteExpressionCommandOutput } from "../commands/DeleteExpressionCommand";
import { DeleteIndexFieldCommandInput, DeleteIndexFieldCommandOutput } from "../commands/DeleteIndexFieldCommand";
import { DeleteSuggesterCommandInput, DeleteSuggesterCommandOutput } from "../commands/DeleteSuggesterCommand";
import { DescribeAnalysisSchemesCommandInput, DescribeAnalysisSchemesCommandOutput } from "../commands/DescribeAnalysisSchemesCommand";
import { DescribeAvailabilityOptionsCommandInput, DescribeAvailabilityOptionsCommandOutput } from "../commands/DescribeAvailabilityOptionsCommand";
import { DescribeDomainEndpointOptionsCommandInput, DescribeDomainEndpointOptionsCommandOutput } from "../commands/DescribeDomainEndpointOptionsCommand";
import { DescribeDomainsCommandInput, DescribeDomainsCommandOutput } from "../commands/DescribeDomainsCommand";
import { DescribeExpressionsCommandInput, DescribeExpressionsCommandOutput } from "../commands/DescribeExpressionsCommand";
import { DescribeIndexFieldsCommandInput, DescribeIndexFieldsCommandOutput } from "../commands/DescribeIndexFieldsCommand";
import { DescribeScalingParametersCommandInput, DescribeScalingParametersCommandOutput } from "../commands/DescribeScalingParametersCommand";
import { DescribeServiceAccessPoliciesCommandInput, DescribeServiceAccessPoliciesCommandOutput } from "../commands/DescribeServiceAccessPoliciesCommand";
import { DescribeSuggestersCommandInput, DescribeSuggestersCommandOutput } from "../commands/DescribeSuggestersCommand";
import { IndexDocumentsCommandInput, IndexDocumentsCommandOutput } from "../commands/IndexDocumentsCommand";
import { ListDomainNamesCommandInput, ListDomainNamesCommandOutput } from "../commands/ListDomainNamesCommand";
import { UpdateAvailabilityOptionsCommandInput, UpdateAvailabilityOptionsCommandOutput } from "../commands/UpdateAvailabilityOptionsCommand";
import { UpdateDomainEndpointOptionsCommandInput, UpdateDomainEndpointOptionsCommandOutput } from "../commands/UpdateDomainEndpointOptionsCommand";
import { UpdateScalingParametersCommandInput, UpdateScalingParametersCommandOutput } from "../commands/UpdateScalingParametersCommand";
import { UpdateServiceAccessPoliciesCommandInput, UpdateServiceAccessPoliciesCommandOutput } from "../commands/UpdateServiceAccessPoliciesCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryBuildSuggestersCommand(input: BuildSuggestersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateDomainCommand(input: CreateDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDefineAnalysisSchemeCommand(input: DefineAnalysisSchemeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDefineExpressionCommand(input: DefineExpressionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDefineIndexFieldCommand(input: DefineIndexFieldCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDefineSuggesterCommand(input: DefineSuggesterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteAnalysisSchemeCommand(input: DeleteAnalysisSchemeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteDomainCommand(input: DeleteDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteExpressionCommand(input: DeleteExpressionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteIndexFieldCommand(input: DeleteIndexFieldCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteSuggesterCommand(input: DeleteSuggesterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAnalysisSchemesCommand(input: DescribeAnalysisSchemesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAvailabilityOptionsCommand(input: DescribeAvailabilityOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeDomainEndpointOptionsCommand(input: DescribeDomainEndpointOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeDomainsCommand(input: DescribeDomainsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeExpressionsCommand(input: DescribeExpressionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeIndexFieldsCommand(input: DescribeIndexFieldsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeScalingParametersCommand(input: DescribeScalingParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeServiceAccessPoliciesCommand(input: DescribeServiceAccessPoliciesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeSuggestersCommand(input: DescribeSuggestersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryIndexDocumentsCommand(input: IndexDocumentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListDomainNamesCommand(input: ListDomainNamesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateAvailabilityOptionsCommand(input: UpdateAvailabilityOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateDomainEndpointOptionsCommand(input: UpdateDomainEndpointOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateScalingParametersCommand(input: UpdateScalingParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateServiceAccessPoliciesCommand(input: UpdateServiceAccessPoliciesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryBuildSuggestersCommand(output: __HttpResponse, context: __SerdeContext): Promise<BuildSuggestersCommandOutput>;
export declare function deserializeAws_queryCreateDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDomainCommandOutput>;
export declare function deserializeAws_queryDefineAnalysisSchemeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DefineAnalysisSchemeCommandOutput>;
export declare function deserializeAws_queryDefineExpressionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DefineExpressionCommandOutput>;
export declare function deserializeAws_queryDefineIndexFieldCommand(output: __HttpResponse, context: __SerdeContext): Promise<DefineIndexFieldCommandOutput>;
export declare function deserializeAws_queryDefineSuggesterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DefineSuggesterCommandOutput>;
export declare function deserializeAws_queryDeleteAnalysisSchemeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAnalysisSchemeCommandOutput>;
export declare function deserializeAws_queryDeleteDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDomainCommandOutput>;
export declare function deserializeAws_queryDeleteExpressionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteExpressionCommandOutput>;
export declare function deserializeAws_queryDeleteIndexFieldCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteIndexFieldCommandOutput>;
export declare function deserializeAws_queryDeleteSuggesterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSuggesterCommandOutput>;
export declare function deserializeAws_queryDescribeAnalysisSchemesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAnalysisSchemesCommandOutput>;
export declare function deserializeAws_queryDescribeAvailabilityOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAvailabilityOptionsCommandOutput>;
export declare function deserializeAws_queryDescribeDomainEndpointOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDomainEndpointOptionsCommandOutput>;
export declare function deserializeAws_queryDescribeDomainsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDomainsCommandOutput>;
export declare function deserializeAws_queryDescribeExpressionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeExpressionsCommandOutput>;
export declare function deserializeAws_queryDescribeIndexFieldsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeIndexFieldsCommandOutput>;
export declare function deserializeAws_queryDescribeScalingParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeScalingParametersCommandOutput>;
export declare function deserializeAws_queryDescribeServiceAccessPoliciesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeServiceAccessPoliciesCommandOutput>;
export declare function deserializeAws_queryDescribeSuggestersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSuggestersCommandOutput>;
export declare function deserializeAws_queryIndexDocumentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<IndexDocumentsCommandOutput>;
export declare function deserializeAws_queryListDomainNamesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDomainNamesCommandOutput>;
export declare function deserializeAws_queryUpdateAvailabilityOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAvailabilityOptionsCommandOutput>;
export declare function deserializeAws_queryUpdateDomainEndpointOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDomainEndpointOptionsCommandOutput>;
export declare function deserializeAws_queryUpdateScalingParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateScalingParametersCommandOutput>;
export declare function deserializeAws_queryUpdateServiceAccessPoliciesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateServiceAccessPoliciesCommandOutput>;
