export const _A = "Agents";
export const _AA = "AgentArn";
export const _AAg = "AgentArns";
export const _ABSC = "AzureBlobSasConfiguration";
export const _ABST = "AzureBlobSasToken";
export const _ADFD = "AtDestinationForDelete";
export const _AK = "ActivationKey";
export const _AKc = "AccessKey";
export const _AL = "AgentList";
export const _ALE = "AgentListEntry";
export const _AN = "AgentName";
export const _APA = "AccessPointArn";
export const _AS = "AtSource";
export const _AT = "AuthenticationType";
export const _ATc = "AccessTier";
export const _Ac = "Action";
export const _At = "Atime";
export const _BARA = "BucketAccessRoleArn";
export const _BC = "BytesCompressed";
export const _BN = "BucketName";
export const _BPS = "BytesPerSecond";
export const _BS = "BlockSize";
export const _BT = "BlobType";
export const _BTy = "BytesTransferred";
export const _BW = "BytesWritten";
export const _CA = "CreateAgent";
export const _CAR = "CreateAgentRequest";
export const _CARr = "CreateAgentResponse";
export const _CLAB = "CreateLocationAzureBlob";
export const _CLABR = "CreateLocationAzureBlobRequest";
export const _CLABRr = "CreateLocationAzureBlobResponse";
export const _CLE = "CreateLocationEfs";
export const _CLER = "CreateLocationEfsRequest";
export const _CLERr = "CreateLocationEfsResponse";
export const _CLFL = "CreateLocationFsxLustre";
export const _CLFLR = "CreateLocationFsxLustreRequest";
export const _CLFLRr = "CreateLocationFsxLustreResponse";
export const _CLFO = "CreateLocationFsxOntap";
export const _CLFOR = "CreateLocationFsxOntapRequest";
export const _CLFORr = "CreateLocationFsxOntapResponse";
export const _CLFOZ = "CreateLocationFsxOpenZfs";
export const _CLFOZR = "CreateLocationFsxOpenZfsRequest";
export const _CLFOZRr = "CreateLocationFsxOpenZfsResponse";
export const _CLFW = "CreateLocationFsxWindows";
export const _CLFWR = "CreateLocationFsxWindowsRequest";
export const _CLFWRr = "CreateLocationFsxWindowsResponse";
export const _CLH = "CreateLocationHdfs";
export const _CLHR = "CreateLocationHdfsRequest";
export const _CLHRr = "CreateLocationHdfsResponse";
export const _CLN = "CreateLocationNfs";
export const _CLNR = "CreateLocationNfsRequest";
export const _CLNRr = "CreateLocationNfsResponse";
export const _CLOS = "CreateLocationObjectStorage";
export const _CLOSR = "CreateLocationObjectStorageRequest";
export const _CLOSRr = "CreateLocationObjectStorageResponse";
export const _CLS = "CreateLocationS3";
export const _CLSR = "CreateLocationS3Request";
export const _CLSRr = "CreateLocationS3Response";
export const _CLSRre = "CreateLocationSmbRequest";
export const _CLSRrea = "CreateLocationSmbResponse";
export const _CLSr = "CreateLocationSmb";
export const _CSC = "CmkSecretConfig";
export const _CSCu = "CustomSecretConfig";
export const _CT = "CreationTime";
export const _CTE = "CancelTaskExecution";
export const _CTEA = "CurrentTaskExecutionArn";
export const _CTER = "CancelTaskExecutionRequest";
export const _CTERa = "CancelTaskExecutionResponse";
export const _CTR = "CreateTaskRequest";
export const _CTRr = "CreateTaskResponse";
export const _CTr = "CreateTask";
export const _CU = "ContainerUrl";
export const _CWLGA = "CloudWatchLogGroupArn";
export const _D = "Domain";
export const _DA = "DeleteAgent";
export const _DAR = "DeleteAgentRequest";
export const _DARe = "DeleteAgentResponse";
export const _DARes = "DescribeAgentRequest";
export const _DAResc = "DescribeAgentResponse";
export const _DAe = "DescribeAgent";
export const _DB = "DisabledBy";
export const _DIA = "DnsIpAddresses";
export const _DL = "DeleteLocation";
export const _DLA = "DestinationLocationArn";
export const _DLAB = "DescribeLocationAzureBlob";
export const _DLABR = "DescribeLocationAzureBlobRequest";
export const _DLABRe = "DescribeLocationAzureBlobResponse";
export const _DLE = "DescribeLocationEfs";
export const _DLER = "DescribeLocationEfsRequest";
export const _DLERe = "DescribeLocationEfsResponse";
export const _DLFL = "DescribeLocationFsxLustre";
export const _DLFLR = "DescribeLocationFsxLustreRequest";
export const _DLFLRe = "DescribeLocationFsxLustreResponse";
export const _DLFO = "DescribeLocationFsxOntap";
export const _DLFOR = "DescribeLocationFsxOntapRequest";
export const _DLFORe = "DescribeLocationFsxOntapResponse";
export const _DLFOZ = "DescribeLocationFsxOpenZfs";
export const _DLFOZR = "DescribeLocationFsxOpenZfsRequest";
export const _DLFOZRe = "DescribeLocationFsxOpenZfsResponse";
export const _DLFW = "DescribeLocationFsxWindows";
export const _DLFWR = "DescribeLocationFsxWindowsRequest";
export const _DLFWRe = "DescribeLocationFsxWindowsResponse";
export const _DLH = "DescribeLocationHdfs";
export const _DLHR = "DescribeLocationHdfsRequest";
export const _DLHRe = "DescribeLocationHdfsResponse";
export const _DLN = "DescribeLocationNfs";
export const _DLNR = "DescribeLocationNfsRequest";
export const _DLNRe = "DescribeLocationNfsResponse";
export const _DLOS = "DescribeLocationObjectStorage";
export const _DLOSR = "DescribeLocationObjectStorageRequest";
export const _DLOSRe = "DescribeLocationObjectStorageResponse";
export const _DLR = "DeleteLocationRequest";
export const _DLRe = "DeleteLocationResponse";
export const _DLS = "DescribeLocationS3";
export const _DLSR = "DescribeLocationS3Request";
export const _DLSRe = "DescribeLocationS3Response";
export const _DLSRes = "DescribeLocationSmbRequest";
export const _DLSResc = "DescribeLocationSmbResponse";
export const _DLSe = "DescribeLocationSmb";
export const _DNIA = "DestinationNetworkInterfaceArns";
export const _DR = "DisabledReason";
export const _DT = "DeleteTask";
export const _DTE = "DescribeTaskExecution";
export const _DTER = "DescribeTaskExecutionRequest";
export const _DTERe = "DescribeTaskExecutionResponse";
export const _DTP = "DataTransferProtection";
export const _DTR = "DeleteTaskRequest";
export const _DTRe = "DeleteTaskResponse";
export const _DTRes = "DescribeTaskRequest";
export const _DTResc = "DescribeTaskResponse";
export const _DTe = "DescribeTask";
export const _De = "Deleted";
export const _Del = "Delete";
export const _Des = "Destination";
export const _E = "Excludes";
export const _EBTT = "EstimatedBytesToTransfer";
export const _EC = "Ec2Config";
export const _ECr = "ErrorCode";
export const _ED = "ErrorDetail";
export const _EFA = "EfsFilesystemArn";
export const _EFTD = "EstimatedFilesToDelete";
export const _EFTT = "EstimatedFilesToTransfer";
export const _ET = "EndpointType";
export const _ETn = "EndTime";
export const _F = "Filters";
export const _FD = "FilesDeleted";
export const _FF = "FilesFailed";
export const _FFA = "FsxFilesystemArn";
export const _FL = "FilesListed";
export const _FLi = "FilterList";
export const _FP = "FilesPrepared";
export const _FPN = "FsxProtocolNfs";
export const _FPS = "FsxProtocolSmb";
export const _FPs = "FsxProtocol";
export const _FR = "FilterRule";
export const _FS = "FilesSkipped";
export const _FSARA = "FileSystemAccessRoleArn";
export const _FT = "FilesTransferred";
export const _FTi = "FilterType";
export const _FUP = "FsxUpdateProtocol";
export const _FUPS = "FsxUpdateProtocolSmb";
export const _FV = "FilesVerified";
export const _Fo = "Format";
export const _G = "Gid";
export const _H = "Hostname";
export const _HNN = "HdfsNameNode";
export const _HNNL = "HdfsNameNodeList";
export const _I = "Includes";
export const _IE = "InternalException";
export const _IRE = "InvalidRequestException";
export const _ITE = "InTransitEncryption";
export const _ITL = "InputTagList";
export const _K = "Key";
export const _KK = "KerberosKeytab";
export const _KKA = "KmsKeyArn";
export const _KKC = "KerberosKrb5Conf";
export const _KKPU = "KmsKeyProviderUri";
export const _KP = "KerberosPrincipal";
export const _Ke = "Keys";
export const _L = "Locations";
export const _LA = "LocationArn";
export const _LAR = "ListAgentsRequest";
export const _LARi = "ListAgentsResponse";
export const _LAi = "ListAgents";
export const _LCT = "LastConnectionTime";
export const _LF = "LocationFilter";
export const _LFo = "LocationFilters";
export const _LL = "LogLevel";
export const _LLE = "LocationListEntry";
export const _LLR = "ListLocationsRequest";
export const _LLRi = "ListLocationsResponse";
export const _LLi = "ListLocations";
export const _LLo = "LocationList";
export const _LT = "LaunchTime";
export const _LTE = "ListTaskExecutions";
export const _LTER = "ListTaskExecutionsRequest";
export const _LTERi = "ListTaskExecutionsResponse";
export const _LTFR = "ListTagsForResource";
export const _LTFRR = "ListTagsForResourceRequest";
export const _LTFRRi = "ListTagsForResourceResponse";
export const _LTR = "ListTasksRequest";
export const _LTRi = "ListTasksResponse";
export const _LTi = "ListTasks";
export const _LU = "LocationUri";
export const _M = "Mtime";
export const _MC = "ManifestConfig";
export const _MO = "MountOptions";
export const _MOP = "ManifestObjectPath";
export const _MOVI = "ManifestObjectVersionId";
export const _MR = "MaxResults";
export const _MSC = "ManagedSecretConfig";
export const _N = "Name";
export const _NFS = "NFS";
export const _NMO = "NfsMountOptions";
export const _NN = "NameNodes";
export const _NT = "NextToken";
export const _O = "Options";
export const _OM = "OverwriteMode";
export const _OO = "OverrideOptions";
export const _OPC = "OnPremConfig";
export const _OSSK = "ObjectStorageSecretKey";
export const _OT = "ObjectTags";
export const _OTL = "OutputTagList";
export const _OTu = "OutputType";
export const _OVI = "ObjectVersionIds";
export const _Op = "Operator";
export const _Ov = "Overrides";
export const _P = "Platform";
export const _PD = "PreserveDevices";
export const _PDF = "PreserveDeletedFiles";
export const _PDr = "PrepareDuration";
export const _PLC = "PrivateLinkConfig";
export const _PLE = "PrivateLinkEndpoint";
export const _PP = "PosixPermissions";
export const _PS = "PrepareStatus";
export const _Pa = "Password";
export const _Po = "Port";
export const _Pr = "Protocol";
export const _Pre = "Prepare";
export const _QC = "QopConfiguration";
export const _R = "Result";
export const _RA = "ResourceArn";
export const _RD = "ReportDestination";
export const _RDS = "ReportDestinationS3";
export const _RF = "ReplicationFactor";
export const _RL = "ReportLevel";
export const _RO = "ReportOverride";
export const _ROe = "ReportOverrides";
export const _RP = "RpcProtection";
export const _RR = "ReportResult";
export const _S = "Status";
export const _SA = "SecretArn";
export const _SARA = "SecretAccessRoleArn";
export const _SAu = "SubnetArns";
export const _SAub = "SubnetArn";
export const _SBA = "S3BucketArn";
export const _SC = "SasConfiguration";
export const _SCe = "ServerCertificate";
export const _SCo = "S3Config";
export const _SD = "ScheduleDetails";
export const _SDCF = "SecurityDescriptorCopyFlags";
export const _SE = "ScheduleExpression";
export const _SGA = "SecurityGroupArns";
export const _SH = "ServerHostname";
export const _SK = "SecretKey";
export const _SLA = "SourceLocationArn";
export const _SMB = "SMB";
export const _SMC = "S3ManifestConfig";
export const _SMCo = "SourceManifestConfig";
export const _SMO = "SmbMountOptions";
export const _SNIA = "SourceNetworkInterfaceArns";
export const _SP = "SmbPassword";
export const _SPe = "ServerPort";
export const _SPer = "ServerProtocol";
export const _SSC = "S3StorageClass";
export const _ST = "StartTime";
export const _STE = "StartTaskExecution";
export const _STER = "StartTaskExecutionRequest";
export const _STERt = "StartTaskExecutionResponse";
export const _SU = "SimpleUser";
export const _SUT = "StatusUpdateTime";
export const _SVMA = "StorageVirtualMachineArn";
export const _S_ = "S3";
export const _Sc = "Schedule";
export const _Sk = "Skipped";
export const _So = "Source";
export const _Su = "Subdirectory";
export const _T = "Token";
export const _TA = "TaskArn";
export const _TD = "TotalDuration";
export const _TDr = "TransferDuration";
export const _TE = "TaskExecutions";
export const _TEA = "TaskExecutionArn";
export const _TEFFD = "TaskExecutionFilesFailedDetail";
export const _TEFLD = "TaskExecutionFilesListedDetail";
export const _TEL = "TaskExecutionList";
export const _TELE = "TaskExecutionListEntry";
export const _TERD = "TaskExecutionResultDetail";
export const _TF = "TaskFilter";
export const _TFa = "TaskFilters";
export const _TL = "TaskList";
export const _TLE = "TagListEntry";
export const _TLEa = "TaskListEntry";
export const _TM = "TaskMode";
export const _TMr = "TransferMode";
export const _TQ = "TaskQueueing";
export const _TR = "TagResource";
export const _TRC = "TaskReportConfig";
export const _TRR = "TagResourceRequest";
export const _TRRa = "TagResourceResponse";
export const _TS = "TransferStatus";
export const _TSD = "TaskScheduleDetails";
export const _TSa = "TaskSchedule";
export const _Ta = "Tags";
export const _Tas = "Tasks";
export const _Tr = "Transferred";
export const _Tra = "Transfer";
export const _U = "User";
export const _UA = "UpdateAgent";
export const _UAR = "UpdateAgentRequest";
export const _UARp = "UpdateAgentResponse";
export const _ULAB = "UpdateLocationAzureBlob";
export const _ULABR = "UpdateLocationAzureBlobRequest";
export const _ULABRp = "UpdateLocationAzureBlobResponse";
export const _ULE = "UpdateLocationEfs";
export const _ULER = "UpdateLocationEfsRequest";
export const _ULERp = "UpdateLocationEfsResponse";
export const _ULFL = "UpdateLocationFsxLustre";
export const _ULFLR = "UpdateLocationFsxLustreRequest";
export const _ULFLRp = "UpdateLocationFsxLustreResponse";
export const _ULFO = "UpdateLocationFsxOntap";
export const _ULFOR = "UpdateLocationFsxOntapRequest";
export const _ULFORp = "UpdateLocationFsxOntapResponse";
export const _ULFOZ = "UpdateLocationFsxOpenZfs";
export const _ULFOZR = "UpdateLocationFsxOpenZfsRequest";
export const _ULFOZRp = "UpdateLocationFsxOpenZfsResponse";
export const _ULFW = "UpdateLocationFsxWindows";
export const _ULFWR = "UpdateLocationFsxWindowsRequest";
export const _ULFWRp = "UpdateLocationFsxWindowsResponse";
export const _ULH = "UpdateLocationHdfs";
export const _ULHR = "UpdateLocationHdfsRequest";
export const _ULHRp = "UpdateLocationHdfsResponse";
export const _ULN = "UpdateLocationNfs";
export const _ULNR = "UpdateLocationNfsRequest";
export const _ULNRp = "UpdateLocationNfsResponse";
export const _ULOS = "UpdateLocationObjectStorage";
export const _ULOSR = "UpdateLocationObjectStorageRequest";
export const _ULOSRp = "UpdateLocationObjectStorageResponse";
export const _ULS = "UpdateLocationS3";
export const _ULSR = "UpdateLocationS3Request";
export const _ULSRp = "UpdateLocationS3Response";
export const _ULSRpd = "UpdateLocationSmbRequest";
export const _ULSRpda = "UpdateLocationSmbResponse";
export const _ULSp = "UpdateLocationSmb";
export const _UR = "UntagResource";
export const _URR = "UntagResourceRequest";
export const _URRn = "UntagResourceResponse";
export const _UT = "UpdateTask";
export const _UTE = "UpdateTaskExecution";
export const _UTER = "UpdateTaskExecutionRequest";
export const _UTERp = "UpdateTaskExecutionResponse";
export const _UTR = "UpdateTaskRequest";
export const _UTRp = "UpdateTaskResponse";
export const _Ui = "Uid";
export const _V = "Value";
export const _VD = "VerifyDuration";
export const _VEI = "VpcEndpointId";
export const _VM = "VerifyMode";
export const _VS = "VerifyStatus";
export const _Va = "Values";
export const _Ve = "Version";
export const _Ver = "Verified";
export const _Veri = "Verify";
export const _c = "client";
export const _dEC = "datasyncErrorCode";
export const _e = "error";
export const _eC = "errorCode";
export const _m = "message";
export const _s = "server";
export const n0 = "com.amazonaws.datasync";

// smithy-typescript generated code
import { error, list, struct } from "@smithy/core/schema";

import { DataSyncServiceException as __DataSyncServiceException } from "../models/DataSyncServiceException";
import {
  InternalException as __InternalException,
  InvalidRequestException as __InvalidRequestException,
} from "../models/index";

/* eslint no-var: 0 */

export var InternalException = error(
  n0,
  _IE,
  {
    [_e]: _s,
  },
  [_m, _eC],
  [0, 0],

  __InternalException
);
export var InvalidRequestException = error(
  n0,
  _IRE,
  {
    [_e]: _c,
  },
  [_m, _eC, _dEC],
  [0, 0, 0],

  __InvalidRequestException
);
export var TagListEntry = struct(n0, _TLE, 0, [_K, _V], [0, 0]);
export var Unit = "unit" as const;

export var DataSyncServiceException = error(
  "smithy.ts.sdk.synthetic.com.amazonaws.datasync",
  "DataSyncServiceException",
  0,
  [],
  [],
  __DataSyncServiceException
);
export var AgentArnList = 64 | 0;

export var InputTagList = list(n0, _ITL, 0, () => TagListEntry);
