// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AddLayerVersionPermission$,
  AddLayerVersionPermissionCommand,
  AddPermission$,
  AddPermissionCommand,
  AliasLimitExceededException$,
  CallbackTimeoutException$,
  CapacityProviderLimitExceededException$,
  CheckpointDurableExecution$,
  CheckpointDurableExecutionCommand,
  CodeArtifactUserDeletedException$,
  CodeArtifactUserFailedException$,
  CodeArtifactUserPendingException$,
  CodeSigningConfigNotFoundException$,
  CodeStorageExceededException$,
  CodeVerificationFailedException$,
  CreateAlias$,
  CreateAliasCommand,
  CreateCapacityProvider$,
  CreateCapacityProviderCommand,
  CreateCodeSigningConfig$,
  CreateCodeSigningConfigCommand,
  CreateEventSourceMapping$,
  CreateEventSourceMappingCommand,
  CreateFunction$,
  CreateFunctionCommand,
  CreateFunctionUrlConfig$,
  CreateFunctionUrlConfigCommand,
  DeleteAlias$,
  DeleteAliasCommand,
  DeleteCapacityProvider$,
  DeleteCapacityProviderCommand,
  DeleteCodeSigningConfig$,
  DeleteCodeSigningConfigCommand,
  DeleteEventSourceMapping$,
  DeleteEventSourceMappingCommand,
  DeleteFunction$,
  DeleteFunctionCodeSigningConfig$,
  DeleteFunctionCodeSigningConfigCommand,
  DeleteFunctionCommand,
  DeleteFunctionConcurrency$,
  DeleteFunctionConcurrencyCommand,
  DeleteFunctionEventInvokeConfig$,
  DeleteFunctionEventInvokeConfigCommand,
  DeleteFunctionUrlConfig$,
  DeleteFunctionUrlConfigCommand,
  DeleteLayerVersion$,
  DeleteLayerVersionCommand,
  DeleteProvisionedConcurrencyConfig$,
  DeleteProvisionedConcurrencyConfigCommand,
  DurableExecutionAlreadyStartedException$,
  EC2AccessDeniedException$,
  EC2ThrottledException$,
  EC2UnexpectedException$,
  EFSIOException$,
  EFSMountConnectivityException$,
  EFSMountFailureException$,
  EFSMountTimeoutException$,
  ENILimitReachedException$,
  ENINotReadyException$,
  FunctionVersionsPerCapacityProviderLimitExceededException$,
  GetAccountSettings$,
  GetAccountSettingsCommand,
  GetAlias$,
  GetAliasCommand,
  GetCapacityProvider$,
  GetCapacityProviderCommand,
  GetCodeSigningConfig$,
  GetCodeSigningConfigCommand,
  GetDurableExecution$,
  GetDurableExecutionCommand,
  GetDurableExecutionHistory$,
  GetDurableExecutionHistoryCommand,
  GetDurableExecutionState$,
  GetDurableExecutionStateCommand,
  GetEventSourceMapping$,
  GetEventSourceMappingCommand,
  GetFunction$,
  GetFunctionCodeSigningConfig$,
  GetFunctionCodeSigningConfigCommand,
  GetFunctionCommand,
  GetFunctionConcurrency$,
  GetFunctionConcurrencyCommand,
  GetFunctionConfiguration$,
  GetFunctionConfigurationCommand,
  GetFunctionEventInvokeConfig$,
  GetFunctionEventInvokeConfigCommand,
  GetFunctionRecursionConfig$,
  GetFunctionRecursionConfigCommand,
  GetFunctionScalingConfig$,
  GetFunctionScalingConfigCommand,
  GetFunctionUrlConfig$,
  GetFunctionUrlConfigCommand,
  GetLayerVersion$,
  GetLayerVersionByArn$,
  GetLayerVersionByArnCommand,
  GetLayerVersionCommand,
  GetLayerVersionPolicy$,
  GetLayerVersionPolicyCommand,
  GetPolicy$,
  GetPolicyCommand,
  GetProvisionedConcurrencyConfig$,
  GetProvisionedConcurrencyConfigCommand,
  GetRuntimeManagementConfig$,
  GetRuntimeManagementConfigCommand,
  InvalidCodeSignatureException$,
  InvalidParameterValueException$,
  InvalidRequestContentException$,
  InvalidRuntimeException$,
  InvalidSecurityGroupIDException$,
  InvalidSubnetIDException$,
  InvalidZipFileException$,
  Invoke$,
  InvokeAsync$,
  InvokeAsyncCommand,
  InvokeCommand,
  InvokeWithResponseStream$,
  InvokeWithResponseStreamCommand,
  KMSAccessDeniedException$,
  KMSDisabledException$,
  KMSInvalidStateException$,
  KMSNotFoundException$,
  LambdaClient,
  ListAliases$,
  ListAliasesCommand,
  ListCapacityProviders$,
  ListCapacityProvidersCommand,
  ListCodeSigningConfigs$,
  ListCodeSigningConfigsCommand,
  ListDurableExecutionsByFunction$,
  ListDurableExecutionsByFunctionCommand,
  ListEventSourceMappings$,
  ListEventSourceMappingsCommand,
  ListFunctionEventInvokeConfigs$,
  ListFunctionEventInvokeConfigsCommand,
  ListFunctions$,
  ListFunctionsByCodeSigningConfig$,
  ListFunctionsByCodeSigningConfigCommand,
  ListFunctionsCommand,
  ListFunctionUrlConfigs$,
  ListFunctionUrlConfigsCommand,
  ListFunctionVersionsByCapacityProvider$,
  ListFunctionVersionsByCapacityProviderCommand,
  ListLayers$,
  ListLayersCommand,
  ListLayerVersions$,
  ListLayerVersionsCommand,
  ListProvisionedConcurrencyConfigs$,
  ListProvisionedConcurrencyConfigsCommand,
  ListTags$,
  ListTagsCommand,
  ListVersionsByFunction$,
  ListVersionsByFunctionCommand,
  ModeNotSupportedException$,
  NoPublishedVersionException$,
  PolicyLengthExceededException$,
  PreconditionFailedException$,
  ProvisionedConcurrencyConfigNotFoundException$,
  PublicPolicyException$,
  PublishLayerVersion$,
  PublishLayerVersionCommand,
  PublishVersion$,
  PublishVersionCommand,
  PutFunctionCodeSigningConfig$,
  PutFunctionCodeSigningConfigCommand,
  PutFunctionConcurrency$,
  PutFunctionConcurrencyCommand,
  PutFunctionEventInvokeConfig$,
  PutFunctionEventInvokeConfigCommand,
  PutFunctionRecursionConfig$,
  PutFunctionRecursionConfigCommand,
  PutFunctionScalingConfig$,
  PutFunctionScalingConfigCommand,
  PutProvisionedConcurrencyConfig$,
  PutProvisionedConcurrencyConfigCommand,
  PutRuntimeManagementConfig$,
  PutRuntimeManagementConfigCommand,
  RecursiveInvocationException$,
  RemoveLayerVersionPermission$,
  RemoveLayerVersionPermissionCommand,
  RemovePermission$,
  RemovePermissionCommand,
  RequestTooLargeException$,
  ResourceConflictException$,
  ResourceInUseException$,
  ResourceNotFoundException$,
  ResourceNotReadyException$,
  S3FilesMountConnectivityException$,
  S3FilesMountFailureException$,
  S3FilesMountTimeoutException$,
  SendDurableExecutionCallbackFailure$,
  SendDurableExecutionCallbackFailureCommand,
  SendDurableExecutionCallbackHeartbeat$,
  SendDurableExecutionCallbackHeartbeatCommand,
  SendDurableExecutionCallbackSuccess$,
  SendDurableExecutionCallbackSuccessCommand,
  SerializedRequestEntityTooLargeException$,
  ServiceException$,
  ServiceQuotaExceededException$,
  SnapStartException$,
  SnapStartNotReadyException$,
  SnapStartRegenerationFailureException$,
  SnapStartTimeoutException$,
  StopDurableExecution$,
  StopDurableExecutionCommand,
  SubnetIPAddressLimitReachedException$,
  TagResource$,
  TagResourceCommand,
  TooManyRequestsException$,
  UnsupportedMediaTypeException$,
  UntagResource$,
  UntagResourceCommand,
  UpdateAlias$,
  UpdateAliasCommand,
  UpdateCapacityProvider$,
  UpdateCapacityProviderCommand,
  UpdateCodeSigningConfig$,
  UpdateCodeSigningConfigCommand,
  UpdateEventSourceMapping$,
  UpdateEventSourceMappingCommand,
  UpdateFunctionCode$,
  UpdateFunctionCodeCommand,
  UpdateFunctionConfiguration$,
  UpdateFunctionConfigurationCommand,
  UpdateFunctionEventInvokeConfig$,
  UpdateFunctionEventInvokeConfigCommand,
  UpdateFunctionUrlConfig$,
  UpdateFunctionUrlConfigCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = LambdaClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("LambdaClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AddLayerVersionPermission$, AddLayerVersionPermissionCommand],
      [AddPermission$, AddPermissionCommand],
      [CheckpointDurableExecution$, CheckpointDurableExecutionCommand],
      [CreateAlias$, CreateAliasCommand],
      [CreateCapacityProvider$, CreateCapacityProviderCommand],
      [CreateCodeSigningConfig$, CreateCodeSigningConfigCommand],
      [CreateEventSourceMapping$, CreateEventSourceMappingCommand],
      [CreateFunction$, CreateFunctionCommand],
      [CreateFunctionUrlConfig$, CreateFunctionUrlConfigCommand],
      [DeleteAlias$, DeleteAliasCommand],
      [DeleteCapacityProvider$, DeleteCapacityProviderCommand],
      [DeleteCodeSigningConfig$, DeleteCodeSigningConfigCommand],
      [DeleteEventSourceMapping$, DeleteEventSourceMappingCommand],
      [DeleteFunction$, DeleteFunctionCommand],
      [DeleteFunctionCodeSigningConfig$, DeleteFunctionCodeSigningConfigCommand],
      [DeleteFunctionConcurrency$, DeleteFunctionConcurrencyCommand],
      [DeleteFunctionEventInvokeConfig$, DeleteFunctionEventInvokeConfigCommand],
      [DeleteFunctionUrlConfig$, DeleteFunctionUrlConfigCommand],
      [DeleteLayerVersion$, DeleteLayerVersionCommand],
      [DeleteProvisionedConcurrencyConfig$, DeleteProvisionedConcurrencyConfigCommand],
      [GetAccountSettings$, GetAccountSettingsCommand],
      [GetAlias$, GetAliasCommand],
      [GetCapacityProvider$, GetCapacityProviderCommand],
      [GetCodeSigningConfig$, GetCodeSigningConfigCommand],
      [GetDurableExecution$, GetDurableExecutionCommand],
      [GetDurableExecutionHistory$, GetDurableExecutionHistoryCommand],
      [GetDurableExecutionState$, GetDurableExecutionStateCommand],
      [GetEventSourceMapping$, GetEventSourceMappingCommand],
      [GetFunction$, GetFunctionCommand],
      [GetFunctionCodeSigningConfig$, GetFunctionCodeSigningConfigCommand],
      [GetFunctionConcurrency$, GetFunctionConcurrencyCommand],
      [GetFunctionConfiguration$, GetFunctionConfigurationCommand],
      [GetFunctionEventInvokeConfig$, GetFunctionEventInvokeConfigCommand],
      [GetFunctionRecursionConfig$, GetFunctionRecursionConfigCommand],
      [GetFunctionScalingConfig$, GetFunctionScalingConfigCommand],
      [GetFunctionUrlConfig$, GetFunctionUrlConfigCommand],
      [GetLayerVersion$, GetLayerVersionCommand],
      [GetLayerVersionByArn$, GetLayerVersionByArnCommand],
      [GetLayerVersionPolicy$, GetLayerVersionPolicyCommand],
      [GetPolicy$, GetPolicyCommand],
      [GetProvisionedConcurrencyConfig$, GetProvisionedConcurrencyConfigCommand],
      [GetRuntimeManagementConfig$, GetRuntimeManagementConfigCommand],
      [Invoke$, InvokeCommand],
      [InvokeAsync$, InvokeAsyncCommand],
      [InvokeWithResponseStream$, InvokeWithResponseStreamCommand],
      [ListAliases$, ListAliasesCommand],
      [ListCapacityProviders$, ListCapacityProvidersCommand],
      [ListCodeSigningConfigs$, ListCodeSigningConfigsCommand],
      [ListDurableExecutionsByFunction$, ListDurableExecutionsByFunctionCommand],
      [ListEventSourceMappings$, ListEventSourceMappingsCommand],
      [ListFunctionEventInvokeConfigs$, ListFunctionEventInvokeConfigsCommand],
      [ListFunctions$, ListFunctionsCommand],
      [ListFunctionsByCodeSigningConfig$, ListFunctionsByCodeSigningConfigCommand],
      [ListFunctionUrlConfigs$, ListFunctionUrlConfigsCommand],
      [ListFunctionVersionsByCapacityProvider$, ListFunctionVersionsByCapacityProviderCommand],
      [ListLayers$, ListLayersCommand],
      [ListLayerVersions$, ListLayerVersionsCommand],
      [ListProvisionedConcurrencyConfigs$, ListProvisionedConcurrencyConfigsCommand],
      [ListTags$, ListTagsCommand],
      [ListVersionsByFunction$, ListVersionsByFunctionCommand],
      [PublishLayerVersion$, PublishLayerVersionCommand],
      [PublishVersion$, PublishVersionCommand],
      [PutFunctionCodeSigningConfig$, PutFunctionCodeSigningConfigCommand],
      [PutFunctionConcurrency$, PutFunctionConcurrencyCommand],
      [PutFunctionEventInvokeConfig$, PutFunctionEventInvokeConfigCommand],
      [PutFunctionRecursionConfig$, PutFunctionRecursionConfigCommand],
      [PutFunctionScalingConfig$, PutFunctionScalingConfigCommand],
      [PutProvisionedConcurrencyConfig$, PutProvisionedConcurrencyConfigCommand],
      [PutRuntimeManagementConfig$, PutRuntimeManagementConfigCommand],
      [RemoveLayerVersionPermission$, RemoveLayerVersionPermissionCommand],
      [RemovePermission$, RemovePermissionCommand],
      [SendDurableExecutionCallbackFailure$, SendDurableExecutionCallbackFailureCommand],
      [SendDurableExecutionCallbackHeartbeat$, SendDurableExecutionCallbackHeartbeatCommand],
      [SendDurableExecutionCallbackSuccess$, SendDurableExecutionCallbackSuccessCommand],
      [StopDurableExecution$, StopDurableExecutionCommand],
      [TagResource$, TagResourceCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateAlias$, UpdateAliasCommand],
      [UpdateCapacityProvider$, UpdateCapacityProviderCommand],
      [UpdateCodeSigningConfig$, UpdateCodeSigningConfigCommand],
      [UpdateEventSourceMapping$, UpdateEventSourceMappingCommand],
      [UpdateFunctionCode$, UpdateFunctionCodeCommand],
      [UpdateFunctionConfiguration$, UpdateFunctionConfigurationCommand],
      [UpdateFunctionEventInvokeConfig$, UpdateFunctionEventInvokeConfigCommand],
      [UpdateFunctionUrlConfig$, UpdateFunctionUrlConfigCommand],
    ]),
    errors: [
      AliasLimitExceededException$,
      CallbackTimeoutException$,
      CapacityProviderLimitExceededException$,
      CodeArtifactUserDeletedException$,
      CodeArtifactUserFailedException$,
      CodeArtifactUserPendingException$,
      CodeSigningConfigNotFoundException$,
      CodeStorageExceededException$,
      CodeVerificationFailedException$,
      DurableExecutionAlreadyStartedException$,
      EC2AccessDeniedException$,
      EC2ThrottledException$,
      EC2UnexpectedException$,
      EFSIOException$,
      EFSMountConnectivityException$,
      EFSMountFailureException$,
      EFSMountTimeoutException$,
      ENILimitReachedException$,
      ENINotReadyException$,
      FunctionVersionsPerCapacityProviderLimitExceededException$,
      InvalidCodeSignatureException$,
      InvalidParameterValueException$,
      InvalidRequestContentException$,
      InvalidRuntimeException$,
      InvalidSecurityGroupIDException$,
      InvalidSubnetIDException$,
      InvalidZipFileException$,
      KMSAccessDeniedException$,
      KMSDisabledException$,
      KMSInvalidStateException$,
      KMSNotFoundException$,
      ModeNotSupportedException$,
      NoPublishedVersionException$,
      PolicyLengthExceededException$,
      PreconditionFailedException$,
      ProvisionedConcurrencyConfigNotFoundException$,
      PublicPolicyException$,
      RecursiveInvocationException$,
      RequestTooLargeException$,
      ResourceConflictException$,
      ResourceInUseException$,
      ResourceNotFoundException$,
      ResourceNotReadyException$,
      S3FilesMountConnectivityException$,
      S3FilesMountFailureException$,
      S3FilesMountTimeoutException$,
      SerializedRequestEntityTooLargeException$,
      ServiceException$,
      ServiceQuotaExceededException$,
      SnapStartException$,
      SnapStartNotReadyException$,
      SnapStartRegenerationFailureException$,
      SnapStartTimeoutException$,
      SubnetIPAddressLimitReachedException$,
      TooManyRequestsException$,
      UnsupportedMediaTypeException$,
    ],
  });
  runner.run();
}, 30_000);
