import { AcceptQualificationRequestCommandInput, AcceptQualificationRequestCommandOutput } from "../commands/AcceptQualificationRequestCommand";
import { ApproveAssignmentCommandInput, ApproveAssignmentCommandOutput } from "../commands/ApproveAssignmentCommand";
import { AssociateQualificationWithWorkerCommandInput, AssociateQualificationWithWorkerCommandOutput } from "../commands/AssociateQualificationWithWorkerCommand";
import { CreateAdditionalAssignmentsForHITCommandInput, CreateAdditionalAssignmentsForHITCommandOutput } from "../commands/CreateAdditionalAssignmentsForHITCommand";
import { CreateHITCommandInput, CreateHITCommandOutput } from "../commands/CreateHITCommand";
import { CreateHITTypeCommandInput, CreateHITTypeCommandOutput } from "../commands/CreateHITTypeCommand";
import { CreateHITWithHITTypeCommandInput, CreateHITWithHITTypeCommandOutput } from "../commands/CreateHITWithHITTypeCommand";
import { CreateQualificationTypeCommandInput, CreateQualificationTypeCommandOutput } from "../commands/CreateQualificationTypeCommand";
import { CreateWorkerBlockCommandInput, CreateWorkerBlockCommandOutput } from "../commands/CreateWorkerBlockCommand";
import { DeleteHITCommandInput, DeleteHITCommandOutput } from "../commands/DeleteHITCommand";
import { DeleteQualificationTypeCommandInput, DeleteQualificationTypeCommandOutput } from "../commands/DeleteQualificationTypeCommand";
import { DeleteWorkerBlockCommandInput, DeleteWorkerBlockCommandOutput } from "../commands/DeleteWorkerBlockCommand";
import { DisassociateQualificationFromWorkerCommandInput, DisassociateQualificationFromWorkerCommandOutput } from "../commands/DisassociateQualificationFromWorkerCommand";
import { GetAccountBalanceCommandInput, GetAccountBalanceCommandOutput } from "../commands/GetAccountBalanceCommand";
import { GetAssignmentCommandInput, GetAssignmentCommandOutput } from "../commands/GetAssignmentCommand";
import { GetFileUploadURLCommandInput, GetFileUploadURLCommandOutput } from "../commands/GetFileUploadURLCommand";
import { GetHITCommandInput, GetHITCommandOutput } from "../commands/GetHITCommand";
import { GetQualificationScoreCommandInput, GetQualificationScoreCommandOutput } from "../commands/GetQualificationScoreCommand";
import { GetQualificationTypeCommandInput, GetQualificationTypeCommandOutput } from "../commands/GetQualificationTypeCommand";
import { ListAssignmentsForHITCommandInput, ListAssignmentsForHITCommandOutput } from "../commands/ListAssignmentsForHITCommand";
import { ListBonusPaymentsCommandInput, ListBonusPaymentsCommandOutput } from "../commands/ListBonusPaymentsCommand";
import { ListHITsCommandInput, ListHITsCommandOutput } from "../commands/ListHITsCommand";
import { ListHITsForQualificationTypeCommandInput, ListHITsForQualificationTypeCommandOutput } from "../commands/ListHITsForQualificationTypeCommand";
import { ListQualificationRequestsCommandInput, ListQualificationRequestsCommandOutput } from "../commands/ListQualificationRequestsCommand";
import { ListQualificationTypesCommandInput, ListQualificationTypesCommandOutput } from "../commands/ListQualificationTypesCommand";
import { ListReviewPolicyResultsForHITCommandInput, ListReviewPolicyResultsForHITCommandOutput } from "../commands/ListReviewPolicyResultsForHITCommand";
import { ListReviewableHITsCommandInput, ListReviewableHITsCommandOutput } from "../commands/ListReviewableHITsCommand";
import { ListWorkerBlocksCommandInput, ListWorkerBlocksCommandOutput } from "../commands/ListWorkerBlocksCommand";
import { ListWorkersWithQualificationTypeCommandInput, ListWorkersWithQualificationTypeCommandOutput } from "../commands/ListWorkersWithQualificationTypeCommand";
import { NotifyWorkersCommandInput, NotifyWorkersCommandOutput } from "../commands/NotifyWorkersCommand";
import { RejectAssignmentCommandInput, RejectAssignmentCommandOutput } from "../commands/RejectAssignmentCommand";
import { RejectQualificationRequestCommandInput, RejectQualificationRequestCommandOutput } from "../commands/RejectQualificationRequestCommand";
import { SendBonusCommandInput, SendBonusCommandOutput } from "../commands/SendBonusCommand";
import { SendTestEventNotificationCommandInput, SendTestEventNotificationCommandOutput } from "../commands/SendTestEventNotificationCommand";
import { UpdateExpirationForHITCommandInput, UpdateExpirationForHITCommandOutput } from "../commands/UpdateExpirationForHITCommand";
import { UpdateHITReviewStatusCommandInput, UpdateHITReviewStatusCommandOutput } from "../commands/UpdateHITReviewStatusCommand";
import { UpdateHITTypeOfHITCommandInput, UpdateHITTypeOfHITCommandOutput } from "../commands/UpdateHITTypeOfHITCommand";
import { UpdateNotificationSettingsCommandInput, UpdateNotificationSettingsCommandOutput } from "../commands/UpdateNotificationSettingsCommand";
import { UpdateQualificationTypeCommandInput, UpdateQualificationTypeCommandOutput } from "../commands/UpdateQualificationTypeCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AcceptQualificationRequestCommand(input: AcceptQualificationRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ApproveAssignmentCommand(input: ApproveAssignmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateQualificationWithWorkerCommand(input: AssociateQualificationWithWorkerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAdditionalAssignmentsForHITCommand(input: CreateAdditionalAssignmentsForHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateHITCommand(input: CreateHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateHITTypeCommand(input: CreateHITTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateHITWithHITTypeCommand(input: CreateHITWithHITTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateQualificationTypeCommand(input: CreateQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateWorkerBlockCommand(input: CreateWorkerBlockCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteHITCommand(input: DeleteHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteQualificationTypeCommand(input: DeleteQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteWorkerBlockCommand(input: DeleteWorkerBlockCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateQualificationFromWorkerCommand(input: DisassociateQualificationFromWorkerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAccountBalanceCommand(input: GetAccountBalanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetAssignmentCommand(input: GetAssignmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetFileUploadURLCommand(input: GetFileUploadURLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetHITCommand(input: GetHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetQualificationScoreCommand(input: GetQualificationScoreCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetQualificationTypeCommand(input: GetQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAssignmentsForHITCommand(input: ListAssignmentsForHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListBonusPaymentsCommand(input: ListBonusPaymentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListHITsCommand(input: ListHITsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListHITsForQualificationTypeCommand(input: ListHITsForQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListQualificationRequestsCommand(input: ListQualificationRequestsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListQualificationTypesCommand(input: ListQualificationTypesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListReviewPolicyResultsForHITCommand(input: ListReviewPolicyResultsForHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListReviewableHITsCommand(input: ListReviewableHITsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListWorkerBlocksCommand(input: ListWorkerBlocksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListWorkersWithQualificationTypeCommand(input: ListWorkersWithQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1NotifyWorkersCommand(input: NotifyWorkersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RejectAssignmentCommand(input: RejectAssignmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RejectQualificationRequestCommand(input: RejectQualificationRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SendBonusCommand(input: SendBonusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SendTestEventNotificationCommand(input: SendTestEventNotificationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateExpirationForHITCommand(input: UpdateExpirationForHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateHITReviewStatusCommand(input: UpdateHITReviewStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateHITTypeOfHITCommand(input: UpdateHITTypeOfHITCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateNotificationSettingsCommand(input: UpdateNotificationSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateQualificationTypeCommand(input: UpdateQualificationTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AcceptQualificationRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<AcceptQualificationRequestCommandOutput>;
export declare function deserializeAws_json1_1ApproveAssignmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<ApproveAssignmentCommandOutput>;
export declare function deserializeAws_json1_1AssociateQualificationWithWorkerCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateQualificationWithWorkerCommandOutput>;
export declare function deserializeAws_json1_1CreateAdditionalAssignmentsForHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAdditionalAssignmentsForHITCommandOutput>;
export declare function deserializeAws_json1_1CreateHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHITCommandOutput>;
export declare function deserializeAws_json1_1CreateHITTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHITTypeCommandOutput>;
export declare function deserializeAws_json1_1CreateHITWithHITTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHITWithHITTypeCommandOutput>;
export declare function deserializeAws_json1_1CreateQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateQualificationTypeCommandOutput>;
export declare function deserializeAws_json1_1CreateWorkerBlockCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateWorkerBlockCommandOutput>;
export declare function deserializeAws_json1_1DeleteHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteHITCommandOutput>;
export declare function deserializeAws_json1_1DeleteQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteQualificationTypeCommandOutput>;
export declare function deserializeAws_json1_1DeleteWorkerBlockCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteWorkerBlockCommandOutput>;
export declare function deserializeAws_json1_1DisassociateQualificationFromWorkerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateQualificationFromWorkerCommandOutput>;
export declare function deserializeAws_json1_1GetAccountBalanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAccountBalanceCommandOutput>;
export declare function deserializeAws_json1_1GetAssignmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetAssignmentCommandOutput>;
export declare function deserializeAws_json1_1GetFileUploadURLCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFileUploadURLCommandOutput>;
export declare function deserializeAws_json1_1GetHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetHITCommandOutput>;
export declare function deserializeAws_json1_1GetQualificationScoreCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetQualificationScoreCommandOutput>;
export declare function deserializeAws_json1_1GetQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetQualificationTypeCommandOutput>;
export declare function deserializeAws_json1_1ListAssignmentsForHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAssignmentsForHITCommandOutput>;
export declare function deserializeAws_json1_1ListBonusPaymentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListBonusPaymentsCommandOutput>;
export declare function deserializeAws_json1_1ListHITsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListHITsCommandOutput>;
export declare function deserializeAws_json1_1ListHITsForQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListHITsForQualificationTypeCommandOutput>;
export declare function deserializeAws_json1_1ListQualificationRequestsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListQualificationRequestsCommandOutput>;
export declare function deserializeAws_json1_1ListQualificationTypesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListQualificationTypesCommandOutput>;
export declare function deserializeAws_json1_1ListReviewPolicyResultsForHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListReviewPolicyResultsForHITCommandOutput>;
export declare function deserializeAws_json1_1ListReviewableHITsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListReviewableHITsCommandOutput>;
export declare function deserializeAws_json1_1ListWorkerBlocksCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWorkerBlocksCommandOutput>;
export declare function deserializeAws_json1_1ListWorkersWithQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWorkersWithQualificationTypeCommandOutput>;
export declare function deserializeAws_json1_1NotifyWorkersCommand(output: __HttpResponse, context: __SerdeContext): Promise<NotifyWorkersCommandOutput>;
export declare function deserializeAws_json1_1RejectAssignmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<RejectAssignmentCommandOutput>;
export declare function deserializeAws_json1_1RejectQualificationRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<RejectQualificationRequestCommandOutput>;
export declare function deserializeAws_json1_1SendBonusCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendBonusCommandOutput>;
export declare function deserializeAws_json1_1SendTestEventNotificationCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendTestEventNotificationCommandOutput>;
export declare function deserializeAws_json1_1UpdateExpirationForHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateExpirationForHITCommandOutput>;
export declare function deserializeAws_json1_1UpdateHITReviewStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateHITReviewStatusCommandOutput>;
export declare function deserializeAws_json1_1UpdateHITTypeOfHITCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateHITTypeOfHITCommandOutput>;
export declare function deserializeAws_json1_1UpdateNotificationSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateNotificationSettingsCommandOutput>;
export declare function deserializeAws_json1_1UpdateQualificationTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateQualificationTypeCommandOutput>;
