// smithy-typescript generated code
import { BinaryDecisionDiagram } from "@smithy/core/endpoints";

const X="ref";
const a=-1,
b=false,
c=true,
d="isSet",
e="PartitionResult",
f="stringEquals",
g="substring",
h="coalesce",
i="",
j="-",
k="aws.parseArn",
l=(n: number)=>"arn_ssa_"+n+i,
m="isValidHostLabel",
n="getAttr",
o="accountId",
p="region",
q="service",
s="kinesis",
t="resourceId[0]",
u=(n: number)=>"arnType_ssa_"+n+i,
v="stream",
w="partition",
x="booleanEquals",
y=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
z=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",
A=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",
B=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dnsSuffix}",
C=(n: number)=>"Partition: {arn_ssa_"+n+"#partition} from ARN doesn't match with partition name: {PartitionResult#name}.",
D=(n: number)=>"Invalid ARN: Kinesis ARNs don't support `{arnType_ssa_"+n+"}` arn types.",
E=(n: number)=>"Invalid ARN: The ARN was not for the Kinesis service, found: {arn_ssa_"+n+"#service}.",
F={"fn":n,"argv":[{[X]:e},"name"]},
G={[X]:"StreamId"},
H={[X]:"Endpoint"},
I={[X]:"arn_ssa_3"},
J={[X]:"arn_ssa_1"},
K={[X]:"arnType_ssa_2"},
L={[X]:"AccountIdEndpointMode"},
M={[X]:"arn_ssa_2"},
N={[X]:"arnType_ssa_3"},
O={[X]:"AccountId"},
P={[X]:"arnType_ssa_1"},
Q={[X]:e},
R={},
S={"metricValues":["O"]},
T=[{[X]:"Region"}],
U=[{[X]:"StreamARN"}],
V=[{[X]:"ConsumerARN"}],
W=[{[X]:"ResourceARN"}];
const _data={
  conditions: [
    [d,T],
    ["aws.partition",T,e],
    [f,[F,"aws-iso-b"]],
    [f,[F,"aws-iso"]],
    [d,[G]],
    [g,[G,21,24,b],"StreamIdSuffixValue"],
    [g,[G,0,20,b],"StreamIdPrefixValue"],
    [f,[{fn:h,argv:[{fn:g,argv:[G,20,21,b]},i]},j]],
    [f,[{fn:h,argv:[{fn:g,argv:[G,3,4,c]},i]},j]],
    [d,[H]],
    [g,[H,15,20,b],"HttpsCustomEndpointSuffixValue"],
    [f,[{fn:h,argv:[{fn:g,argv:[H,15,16,b]},i]},j]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,20,21,b]},i]},"."]],
    [g,[H,7,12,b],"PlainCustomEndpointSuffixValue"],
    [d,U],
    [k,U,l(3)],
    [m,[{fn:n,argv:[I,o]},b]],
    [m,[{fn:n,argv:[I,p]},b]],
    [f,[{fn:n,argv:[I,q]},s]],
    [d,V],
    [n,[I,t],u(1)],
    [k,V,l(1)],
    [m,[{fn:n,argv:[J,o]},b]],
    [m,[{fn:n,argv:[J,p]},b]],
    [f,[{fn:n,argv:[J,q]},s]],
    [n,[J,t],u(2)],
    [f,[K,i]],
    [f,[K,v]],
    [f,[F,{fn:n,argv:[J,w]}]],
    [d,W],
    [k,W,l(2)],
    [d,[L]],
    [m,[{fn:n,argv:[M,o]},b]],
    [m,[{fn:n,argv:[M,p]},b]],
    [f,[{fn:n,argv:[M,q]},s]],
    [n,[M,t],u(3)],
    [f,[N,i]],
    [f,[N,v]],
    [f,[F,{fn:n,argv:[M,w]}]],
    [d,[O]],
    [f,[L,"disabled"]],
    [f,[L,"required"]],
    [m,[O,b]],
    [f,[P,i]],
    [f,[P,v]],
    [f,[F,{fn:n,argv:[I,w]}]],
    [d,[{[X]:"OperationType"}]],
    [x,[{[X]:"UseFIPS"},c]],
    [x,[{fn:n,argv:[Q,"supportsFIPS"]},c]],
    [x,[{[X]:"UseDualStack"},c]],
    [x,[{fn:n,argv:[Q,"supportsDualStack"]},c]],
    [f,[F,"aws-us-gov"]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,12,13,b]},i]},"."]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,7,8,b]},i]},j]]
  ],
  results: [
    [a],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    [a,"DualStack is enabled, but this partition does not support DualStack."],
    [a,"FIPS is enabled, but this partition does not support FIPS."],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dnsSuffix}",R],
    [a,"FIPS is enabled but this partition does not support FIPS"],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    [a,"DualStack is enabled but this partition does not support DualStack"],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}.{Region}.{PartitionResult#dnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}.{Region}.{PartitionResult#dnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis.{Region}.{PartitionResult#dnsSuffix}",R],
    [a,"Operation Type is not set. Please contact service team for resolution."],
    [y(3),R],
    [z(3),R],
    [A(3),R],
    [B(3),R],
    [a,C(3)],
    [a,D(1)],
    [a,"Invalid ARN: No ARN type specified"],
    [a,E(3)],
    [a,"Invalid ARN: Invalid region."],
    [a,"Invalid ARN: Invalid account id."],
    [a,"Invalid ARN: Failed to parse ARN."],
    [y(1),R],
    [z(1),R],
    [A(1),R],
    [B(1),R],
    [a,C(1)],
    [a,D(2)],
    [a,E(1)],
    [y(2),R],
    [z(2),R],
    [A(2),R],
    [B(2),R],
    [a,C(2)],
    [a,D(3)],
    [a,E(2)],
    ["https://{AccountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",S],
    ["https://{AccountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",S],
    ["https://{AccountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",S],
    ["https://{AccountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dnsSuffix}",S],
    [a,"Invalid account id."],
    [a,"AccountIdEndpointMode is required but no AccountID was provided or able to be loaded"],
    [a,"Invalid Configuration: AccountIdEndpointMode is required but account endpoints are not supported in this partition"],
    [a,"Invalid Configuration: FIPS and custom endpoint are not supported"],
    [a,"Invalid Configuration: Dualstack and custom endpoint are not supported"],
    [H,R],
    ["https://kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    [a,"FIPS and DualStack are enabled, but this partition does not support one or both"],
    ["https://kinesis.{Region}.amazonaws.com",R],
    ["https://kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",R],
    ["https://kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",R],
    ["https://kinesis.{Region}.{PartitionResult#dnsSuffix}",R],
    [a,"Invalid Configuration: Missing Region"]
  ]
};

const root = 2;
const r = 100_000_000;
const nodes = new Int32Array([
  -1, 1, -1,
  0, 3, 4,
  1, 5, 4,
  9, 119, r + 59,
  2, 108, 6,
  3, 108, 7,
  4, 8, 12,
  5, 9, 12,
  6, 10, 12,
  7, 11, 12,
  8, 73, 12,
  9, 119, 13,
  14, 58, 14,
  19, 43, 15,
  29, 28, 16,
  31, 17, 111,
  39, 18, 27,
  40, 27, 19,
  42, 20, r + 47,
  46, 21, r + 17,
  47, 24, 22,
  49, 23, r + 46,
  50, r + 45, r + 7,
  48, 25, 105,
  49, 26, r + 44,
  50, r + 43, r + 2,
  41, r + 48, 111,
  30, 29, r + 28,
  32, 30, r + 27,
  33, 31, r + 26,
  34, 32, r + 42,
  35, 33, r + 24,
  36, r + 24, 34,
  37, 35, r + 41,
  38, 36, r + 40,
  46, 37, r + 17,
  47, 40, 38,
  49, 39, r + 39,
  50, r + 38, r + 7,
  48, 41, 105,
  49, 42, r + 37,
  50, r + 36, r + 2,
  21, 44, r + 28,
  22, 45, r + 27,
  23, 46, r + 26,
  24, 47, r + 35,
  25, 48, r + 24,
  26, r + 24, 49,
  27, 50, r + 34,
  28, 51, r + 33,
  46, 52, r + 17,
  47, 55, 53,
  49, 54, r + 32,
  50, r + 31, r + 7,
  48, 56, 105,
  49, 57, r + 30,
  50, r + 29, r + 2,
  15, 59, r + 28,
  16, 60, r + 27,
  17, 61, r + 26,
  18, 62, r + 25,
  20, 63, r + 24,
  43, r + 24, 64,
  44, 65, r + 23,
  45, 66, r + 22,
  46, 67, r + 17,
  47, 70, 68,
  49, 69, r + 21,
  50, r + 20, r + 7,
  48, 71, 105,
  49, 72, r + 19,
  50, r + 18, r + 2,
  9, 74, 78,
  10, 75, 77,
  11, 76, 77,
  12, 100, 77,
  13, 85, 78,
  46, 79, r + 17,
  47, 82, 80,
  49, 81, r + 16,
  50, r + 15, r + 7,
  48, 83, 105,
  49, 84, r + 14,
  50, r + 13, r + 2,
  46, 86, r + 17,
  47, 93, 87,
  49, 90, 88,
  52, 89, r + 16,
  53, r + 12, r + 16,
  50, 91, r + 7,
  52, 92, r + 15,
  53, r + 11, r + 15,
  48, 94, 105,
  49, 97, 95,
  52, 96, r + 14,
  53, r + 10, r + 14,
  50, 98, r + 2,
  52, 99, r + 13,
  53, r + 9, r + 13,
  46, 101, r + 17,
  47, 104, 102,
  49, 103, r + 8,
  50, r + 6, r + 7,
  48, 106, 105,
  49, r + 3, r + 5,
  49, 107, r + 4,
  50, r + 1, r + 2,
  9, 119, 109,
  31, 110, 111,
  41, r + 49, 111,
  47, 114, 112,
  49, 113, r + 58,
  50, r + 57, r + 7,
  48, 116, 115,
  49, r + 54, r + 5,
  49, 118, 117,
  51, r + 55, r + 56,
  50, r + 53, r + 54,
  47, r + 50, 120,
  49, r + 51, r + 52,
]);
export const bdd = BinaryDecisionDiagram.from(
  nodes, root, _data.conditions, _data.results
);
