// smithy-typescript generated code
import { BinaryDecisionDiagram } from "@smithy/util-endpoints";

const U="ref";
const a=-1,
b=false,
c=true,
d="isSet",
e="PartitionResult",
f="stringEquals",
g="substring",
h="coalesce",
i="",
j="-",
k="aws.parseArn",
l=(n: number)=>"arn_ssa_"+n+i,
m="isValidHostLabel",
n="getAttr",
o="accountId",
p="region",
q="service",
s="kinesis",
t="resourceId[0]",
u=(n: number)=>"arnType_ssa_"+n+i,
v="stream",
w="partition",
x="booleanEquals",
y=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
z=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",
A=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",
B=(n: number)=>"https://{arn_ssa_"+n+"#accountId}.{OperationType}-kinesis.{Region}.{PartitionResult#dnsSuffix}",
C=(n: number)=>"Partition: {arn_ssa_"+n+"#partition} from ARN doesn't match with partition name: {PartitionResult#name}.",
D=(n: number)=>"Invalid ARN: Kinesis ARNs don't support `{arnType_ssa_"+n+"}` arn types.",
E=(n: number)=>"Invalid ARN: The ARN was not for the Kinesis service, found: {arn_ssa_"+n+"#service}.",
F={"fn":n,"argv":[{[U]:e},"name"]},
G={[U]:"StreamId"},
H={[U]:"Endpoint"},
I={[U]:"arn_ssa_3"},
J={[U]:"arnType_ssa_1"},
K={[U]:"arn_ssa_2"},
L={[U]:"arnType_ssa_3"},
M={[U]:"arn_ssa_1"},
N={[U]:"arnType_ssa_2"},
O={[U]:e},
P={},
Q=[{[U]:"Region"}],
R=[{[U]:"StreamARN"}],
S=[{[U]:"ConsumerARN"}],
T=[{[U]:"ResourceARN"}];
const _data={
  conditions: [
    [d,Q],
    ["aws.partition",Q,e],
    [f,[F,"aws-iso-b"]],
    [f,[F,"aws-iso"]],
    [d,[G]],
    [g,[G,21,24,b],"StreamIdSuffixValue"],
    [g,[G,0,20,b],"StreamIdPrefixValue"],
    [f,[{fn:h,argv:[{fn:g,argv:[G,20,21,b]},i]},j]],
    [f,[{fn:h,argv:[{fn:g,argv:[G,3,4,c]},i]},j]],
    [d,[H]],
    [d,R],
    [k,R,l(3)],
    [m,[{fn:n,argv:[I,o]},b]],
    [m,[{fn:n,argv:[I,p]},b]],
    [g,[H,15,20,b],"HttpsCustomEndpointSuffixValue"],
    [f,[{fn:h,argv:[{fn:g,argv:[H,20,21,b]},i]},"."]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,15,16,b]},i]},j]],
    [g,[H,7,12,b],"PlainCustomEndpointSuffixValue"],
    [f,[{fn:n,argv:[I,q]},s]],
    [n,[I,t],u(1)],
    [f,[J,i]],
    [f,[J,v]],
    [d,S],
    [d,T],
    [k,T,l(2)],
    [m,[{fn:n,argv:[K,o]},b]],
    [m,[{fn:n,argv:[K,p]},b]],
    [f,[{fn:n,argv:[K,q]},s]],
    [n,[K,t],u(3)],
    [f,[L,i]],
    [f,[L,v]],
    [f,[F,{fn:n,argv:[K,w]}]],
    [k,S,l(1)],
    [m,[{fn:n,argv:[M,o]},b]],
    [m,[{fn:n,argv:[M,p]},b]],
    [f,[{fn:n,argv:[M,q]},s]],
    [n,[M,t],u(2)],
    [f,[N,i]],
    [f,[N,v]],
    [f,[F,{fn:n,argv:[M,w]}]],
    [f,[F,{fn:n,argv:[I,w]}]],
    [d,[{[U]:"OperationType"}]],
    [x,[{[U]:"UseFIPS"},c]],
    [x,[{fn:n,argv:[O,"supportsFIPS"]},c]],
    [x,[{[U]:"UseDualStack"},c]],
    [x,[{fn:n,argv:[O,"supportsDualStack"]},c]],
    [f,[F,"aws-us-gov"]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,7,8,b]},i]},j]],
    [f,[{fn:h,argv:[{fn:g,argv:[H,12,13,b]},i]},"."]]
  ],
  results: [
    [a],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    [a,"DualStack is enabled, but this partition does not support DualStack."],
    [a,"FIPS is enabled, but this partition does not support FIPS."],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dnsSuffix}",P],
    [a,"FIPS is enabled but this partition does not support FIPS"],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    [a,"DualStack is enabled but this partition does not support DualStack"],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{HttpsCustomEndpointSuffixValue}.{Region}.{PartitionResult#dnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}-fips.{Region}.{PartitionResult#dnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis{PlainCustomEndpointSuffixValue}.{Region}.{PartitionResult#dnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    ["https://{StreamIdPrefixValue}.{StreamIdSuffixValue}.{OperationType}-kinesis.{Region}.{PartitionResult#dnsSuffix}",P],
    [a,"Operation Type is not set. Please contact service team for resolution."],
    [y(3),P],
    [z(3),P],
    [A(3),P],
    [B(3),P],
    [a,C(3)],
    [a,D(1)],
    [a,"Invalid ARN: No ARN type specified"],
    [a,E(3)],
    [a,"Invalid ARN: Invalid region."],
    [a,"Invalid ARN: Invalid account id."],
    [a,"Invalid ARN: Failed to parse ARN."],
    [y(1),P],
    [z(1),P],
    [A(1),P],
    [B(1),P],
    [a,C(1)],
    [a,D(2)],
    [a,E(1)],
    [y(2),P],
    [z(2),P],
    [A(2),P],
    [B(2),P],
    [a,C(2)],
    [a,D(3)],
    [a,E(2)],
    [a,"Invalid Configuration: FIPS and custom endpoint are not supported"],
    [a,"Invalid Configuration: Dualstack and custom endpoint are not supported"],
    [H,P],
    ["https://kinesis-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    [a,"FIPS and DualStack are enabled, but this partition does not support one or both"],
    ["https://kinesis.{Region}.amazonaws.com",P],
    ["https://kinesis-fips.{Region}.{PartitionResult#dnsSuffix}",P],
    ["https://kinesis.{Region}.{PartitionResult#dualStackDnsSuffix}",P],
    ["https://kinesis.{Region}.{PartitionResult#dnsSuffix}",P],
    [a,"Invalid Configuration: Missing Region"]
  ]
};

const root = 2;
const r = 100_000_000;
const nodes = new Int32Array([
  -1, 1, -1,
  0, 3, 4,
  1, 5, 4,
  9, 105, r + 52,
  2, 96, 6,
  3, 96, 7,
  4, 8, 12,
  5, 9, 12,
  6, 10, 12,
  7, 11, 12,
  8, 61, 12,
  9, 105, 13,
  10, 46, 14,
  22, 31, 15,
  23, 16, 97,
  24, 17, r + 28,
  25, 18, r + 27,
  26, 19, r + 26,
  27, 20, r + 42,
  28, 21, r + 24,
  29, r + 24, 22,
  30, 23, r + 41,
  31, 24, r + 40,
  41, 25, r + 17,
  42, 28, 26,
  44, 27, r + 39,
  45, r + 38, r + 7,
  43, 29, 93,
  44, 30, r + 37,
  45, r + 36, r + 2,
  32, 32, r + 28,
  33, 33, r + 27,
  34, 34, r + 26,
  35, 35, r + 35,
  36, 36, r + 24,
  37, r + 24, 37,
  38, 38, r + 34,
  39, 39, r + 33,
  41, 40, r + 17,
  42, 43, 41,
  44, 42, r + 32,
  45, r + 31, r + 7,
  43, 44, 93,
  44, 45, r + 30,
  45, r + 29, r + 2,
  11, 47, r + 28,
  12, 48, r + 27,
  13, 49, r + 26,
  18, 50, r + 25,
  19, 51, r + 24,
  20, r + 24, 52,
  21, 53, r + 23,
  40, 54, r + 22,
  41, 55, r + 17,
  42, 58, 56,
  44, 57, r + 21,
  45, r + 20, r + 7,
  43, 59, 93,
  44, 60, r + 19,
  45, r + 18, r + 2,
  9, 62, 66,
  14, 63, 65,
  15, 64, 65,
  16, 88, 65,
  17, 73, 66,
  41, 67, r + 17,
  42, 70, 68,
  44, 69, r + 16,
  45, r + 15, r + 7,
  43, 71, 93,
  44, 72, r + 14,
  45, r + 13, r + 2,
  41, 74, r + 17,
  42, 81, 75,
  44, 78, 76,
  47, 77, r + 16,
  48, r + 12, r + 16,
  45, 79, r + 7,
  47, 80, r + 15,
  48, r + 11, r + 15,
  43, 82, 93,
  44, 85, 83,
  47, 84, r + 14,
  48, r + 10, r + 14,
  45, 86, r + 2,
  47, 87, r + 13,
  48, r + 9, r + 13,
  41, 89, r + 17,
  42, 92, 90,
  44, 91, r + 8,
  45, r + 6, r + 7,
  43, 94, 93,
  44, r + 3, r + 5,
  44, 95, r + 4,
  45, r + 1, r + 2,
  9, 105, 97,
  42, 100, 98,
  44, 99, r + 51,
  45, r + 50, r + 7,
  43, 102, 101,
  44, r + 47, r + 5,
  44, 104, 103,
  46, r + 48, r + 49,
  45, r + 46, r + 47,
  42, r + 43, 106,
  44, r + 44, r + 45,
]);
export const bdd = BinaryDecisionDiagram.from(
  nodes, root, _data.conditions, _data.results
);
