// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  ActivateKeySigningKey$,
  ActivateKeySigningKeyCommand,
  AssociateVPCWithHostedZone$,
  AssociateVPCWithHostedZoneCommand,
  ChangeCidrCollection$,
  ChangeCidrCollectionCommand,
  ChangeResourceRecordSets$,
  ChangeResourceRecordSetsCommand,
  ChangeTagsForResource$,
  ChangeTagsForResourceCommand,
  CidrBlockInUseException$,
  CidrCollectionAlreadyExistsException$,
  CidrCollectionInUseException$,
  CidrCollectionVersionMismatchException$,
  ConcurrentModification$,
  ConflictingDomainExists$,
  ConflictingTypes$,
  CreateCidrCollection$,
  CreateCidrCollectionCommand,
  CreateHealthCheck$,
  CreateHealthCheckCommand,
  CreateHostedZone$,
  CreateHostedZoneCommand,
  CreateKeySigningKey$,
  CreateKeySigningKeyCommand,
  CreateQueryLoggingConfig$,
  CreateQueryLoggingConfigCommand,
  CreateReusableDelegationSet$,
  CreateReusableDelegationSetCommand,
  CreateTrafficPolicy$,
  CreateTrafficPolicyCommand,
  CreateTrafficPolicyInstance$,
  CreateTrafficPolicyInstanceCommand,
  CreateTrafficPolicyVersion$,
  CreateTrafficPolicyVersionCommand,
  CreateVPCAssociationAuthorization$,
  CreateVPCAssociationAuthorizationCommand,
  DeactivateKeySigningKey$,
  DeactivateKeySigningKeyCommand,
  DelegationSetAlreadyCreated$,
  DelegationSetAlreadyReusable$,
  DelegationSetInUse$,
  DelegationSetNotAvailable$,
  DelegationSetNotReusable$,
  DeleteCidrCollection$,
  DeleteCidrCollectionCommand,
  DeleteHealthCheck$,
  DeleteHealthCheckCommand,
  DeleteHostedZone$,
  DeleteHostedZoneCommand,
  DeleteKeySigningKey$,
  DeleteKeySigningKeyCommand,
  DeleteQueryLoggingConfig$,
  DeleteQueryLoggingConfigCommand,
  DeleteReusableDelegationSet$,
  DeleteReusableDelegationSetCommand,
  DeleteTrafficPolicy$,
  DeleteTrafficPolicyCommand,
  DeleteTrafficPolicyInstance$,
  DeleteTrafficPolicyInstanceCommand,
  DeleteVPCAssociationAuthorization$,
  DeleteVPCAssociationAuthorizationCommand,
  DisableHostedZoneDNSSEC$,
  DisableHostedZoneDNSSECCommand,
  DisassociateVPCFromHostedZone$,
  DisassociateVPCFromHostedZoneCommand,
  DNSSECNotFound$,
  EnableHostedZoneDNSSEC$,
  EnableHostedZoneDNSSECCommand,
  GetAccountLimit$,
  GetAccountLimitCommand,
  GetChange$,
  GetChangeCommand,
  GetCheckerIpRanges$,
  GetCheckerIpRangesCommand,
  GetDNSSEC$,
  GetDNSSECCommand,
  GetGeoLocation$,
  GetGeoLocationCommand,
  GetHealthCheck$,
  GetHealthCheckCommand,
  GetHealthCheckCount$,
  GetHealthCheckCountCommand,
  GetHealthCheckLastFailureReason$,
  GetHealthCheckLastFailureReasonCommand,
  GetHealthCheckStatus$,
  GetHealthCheckStatusCommand,
  GetHostedZone$,
  GetHostedZoneCommand,
  GetHostedZoneCount$,
  GetHostedZoneCountCommand,
  GetHostedZoneLimit$,
  GetHostedZoneLimitCommand,
  GetQueryLoggingConfig$,
  GetQueryLoggingConfigCommand,
  GetReusableDelegationSet$,
  GetReusableDelegationSetCommand,
  GetReusableDelegationSetLimit$,
  GetReusableDelegationSetLimitCommand,
  GetTrafficPolicy$,
  GetTrafficPolicyCommand,
  GetTrafficPolicyInstance$,
  GetTrafficPolicyInstanceCommand,
  GetTrafficPolicyInstanceCount$,
  GetTrafficPolicyInstanceCountCommand,
  HealthCheckAlreadyExists$,
  HealthCheckInUse$,
  HealthCheckVersionMismatch$,
  HostedZoneAlreadyExists$,
  HostedZoneNotEmpty$,
  HostedZoneNotFound$,
  HostedZoneNotPrivate$,
  HostedZonePartiallyDelegated$,
  IncompatibleVersion$,
  InsufficientCloudWatchLogsResourcePolicy$,
  InvalidArgument$,
  InvalidChangeBatch$,
  InvalidDomainName$,
  InvalidInput$,
  InvalidKeySigningKeyName$,
  InvalidKeySigningKeyStatus$,
  InvalidKMSArn$,
  InvalidPaginationToken$,
  InvalidSigningStatus$,
  InvalidTrafficPolicyDocument$,
  InvalidVPCId$,
  KeySigningKeyAlreadyExists$,
  KeySigningKeyInParentDSRecord$,
  KeySigningKeyInUse$,
  KeySigningKeyWithActiveStatusNotFound$,
  LastVPCAssociation$,
  LimitsExceeded$,
  ListCidrBlocks$,
  ListCidrBlocksCommand,
  ListCidrCollections$,
  ListCidrCollectionsCommand,
  ListCidrLocations$,
  ListCidrLocationsCommand,
  ListGeoLocations$,
  ListGeoLocationsCommand,
  ListHealthChecks$,
  ListHealthChecksCommand,
  ListHostedZones$,
  ListHostedZonesByName$,
  ListHostedZonesByNameCommand,
  ListHostedZonesByVPC$,
  ListHostedZonesByVPCCommand,
  ListHostedZonesCommand,
  ListQueryLoggingConfigs$,
  ListQueryLoggingConfigsCommand,
  ListResourceRecordSets$,
  ListResourceRecordSetsCommand,
  ListReusableDelegationSets$,
  ListReusableDelegationSetsCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  ListTagsForResources$,
  ListTagsForResourcesCommand,
  ListTrafficPolicies$,
  ListTrafficPoliciesCommand,
  ListTrafficPolicyInstances$,
  ListTrafficPolicyInstancesByHostedZone$,
  ListTrafficPolicyInstancesByHostedZoneCommand,
  ListTrafficPolicyInstancesByPolicy$,
  ListTrafficPolicyInstancesByPolicyCommand,
  ListTrafficPolicyInstancesCommand,
  ListTrafficPolicyVersions$,
  ListTrafficPolicyVersionsCommand,
  ListVPCAssociationAuthorizations$,
  ListVPCAssociationAuthorizationsCommand,
  NoSuchChange$,
  NoSuchCidrCollectionException$,
  NoSuchCidrLocationException$,
  NoSuchCloudWatchLogsLogGroup$,
  NoSuchDelegationSet$,
  NoSuchGeoLocation$,
  NoSuchHealthCheck$,
  NoSuchHostedZone$,
  NoSuchKeySigningKey$,
  NoSuchQueryLoggingConfig$,
  NoSuchTrafficPolicy$,
  NoSuchTrafficPolicyInstance$,
  NotAuthorizedException$,
  PriorRequestNotComplete$,
  PublicZoneVPCAssociation$,
  QueryLoggingConfigAlreadyExists$,
  Route53Client,
  TestDNSAnswer$,
  TestDNSAnswerCommand,
  ThrottlingException$,
  TooManyHealthChecks$,
  TooManyHostedZones$,
  TooManyKeySigningKeys$,
  TooManyTrafficPolicies$,
  TooManyTrafficPolicyInstances$,
  TooManyTrafficPolicyVersionsForCurrentPolicy$,
  TooManyVPCAssociationAuthorizations$,
  TrafficPolicyAlreadyExists$,
  TrafficPolicyInstanceAlreadyExists$,
  TrafficPolicyInUse$,
  UpdateHealthCheck$,
  UpdateHealthCheckCommand,
  UpdateHostedZoneComment$,
  UpdateHostedZoneCommentCommand,
  UpdateHostedZoneFeatures$,
  UpdateHostedZoneFeaturesCommand,
  UpdateTrafficPolicyComment$,
  UpdateTrafficPolicyCommentCommand,
  UpdateTrafficPolicyInstance$,
  UpdateTrafficPolicyInstanceCommand,
  VPCAssociationAuthorizationNotFound$,
  VPCAssociationNotFound$,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = Route53Client;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("Route53Client" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [ActivateKeySigningKey$, ActivateKeySigningKeyCommand],
      [AssociateVPCWithHostedZone$, AssociateVPCWithHostedZoneCommand],
      [ChangeCidrCollection$, ChangeCidrCollectionCommand],
      [ChangeResourceRecordSets$, ChangeResourceRecordSetsCommand],
      [ChangeTagsForResource$, ChangeTagsForResourceCommand],
      [CreateCidrCollection$, CreateCidrCollectionCommand],
      [CreateHealthCheck$, CreateHealthCheckCommand],
      [CreateHostedZone$, CreateHostedZoneCommand],
      [CreateKeySigningKey$, CreateKeySigningKeyCommand],
      [CreateQueryLoggingConfig$, CreateQueryLoggingConfigCommand],
      [CreateReusableDelegationSet$, CreateReusableDelegationSetCommand],
      [CreateTrafficPolicy$, CreateTrafficPolicyCommand],
      [CreateTrafficPolicyInstance$, CreateTrafficPolicyInstanceCommand],
      [CreateTrafficPolicyVersion$, CreateTrafficPolicyVersionCommand],
      [CreateVPCAssociationAuthorization$, CreateVPCAssociationAuthorizationCommand],
      [DeactivateKeySigningKey$, DeactivateKeySigningKeyCommand],
      [DeleteCidrCollection$, DeleteCidrCollectionCommand],
      [DeleteHealthCheck$, DeleteHealthCheckCommand],
      [DeleteHostedZone$, DeleteHostedZoneCommand],
      [DeleteKeySigningKey$, DeleteKeySigningKeyCommand],
      [DeleteQueryLoggingConfig$, DeleteQueryLoggingConfigCommand],
      [DeleteReusableDelegationSet$, DeleteReusableDelegationSetCommand],
      [DeleteTrafficPolicy$, DeleteTrafficPolicyCommand],
      [DeleteTrafficPolicyInstance$, DeleteTrafficPolicyInstanceCommand],
      [DeleteVPCAssociationAuthorization$, DeleteVPCAssociationAuthorizationCommand],
      [DisableHostedZoneDNSSEC$, DisableHostedZoneDNSSECCommand],
      [DisassociateVPCFromHostedZone$, DisassociateVPCFromHostedZoneCommand],
      [EnableHostedZoneDNSSEC$, EnableHostedZoneDNSSECCommand],
      [GetAccountLimit$, GetAccountLimitCommand],
      [GetChange$, GetChangeCommand],
      [GetCheckerIpRanges$, GetCheckerIpRangesCommand],
      [GetDNSSEC$, GetDNSSECCommand],
      [GetGeoLocation$, GetGeoLocationCommand],
      [GetHealthCheck$, GetHealthCheckCommand],
      [GetHealthCheckCount$, GetHealthCheckCountCommand],
      [GetHealthCheckLastFailureReason$, GetHealthCheckLastFailureReasonCommand],
      [GetHealthCheckStatus$, GetHealthCheckStatusCommand],
      [GetHostedZone$, GetHostedZoneCommand],
      [GetHostedZoneCount$, GetHostedZoneCountCommand],
      [GetHostedZoneLimit$, GetHostedZoneLimitCommand],
      [GetQueryLoggingConfig$, GetQueryLoggingConfigCommand],
      [GetReusableDelegationSet$, GetReusableDelegationSetCommand],
      [GetReusableDelegationSetLimit$, GetReusableDelegationSetLimitCommand],
      [GetTrafficPolicy$, GetTrafficPolicyCommand],
      [GetTrafficPolicyInstance$, GetTrafficPolicyInstanceCommand],
      [GetTrafficPolicyInstanceCount$, GetTrafficPolicyInstanceCountCommand],
      [ListCidrBlocks$, ListCidrBlocksCommand],
      [ListCidrCollections$, ListCidrCollectionsCommand],
      [ListCidrLocations$, ListCidrLocationsCommand],
      [ListGeoLocations$, ListGeoLocationsCommand],
      [ListHealthChecks$, ListHealthChecksCommand],
      [ListHostedZones$, ListHostedZonesCommand],
      [ListHostedZonesByName$, ListHostedZonesByNameCommand],
      [ListHostedZonesByVPC$, ListHostedZonesByVPCCommand],
      [ListQueryLoggingConfigs$, ListQueryLoggingConfigsCommand],
      [ListResourceRecordSets$, ListResourceRecordSetsCommand],
      [ListReusableDelegationSets$, ListReusableDelegationSetsCommand],
      [ListTagsForResource$, ListTagsForResourceCommand],
      [ListTagsForResources$, ListTagsForResourcesCommand],
      [ListTrafficPolicies$, ListTrafficPoliciesCommand],
      [ListTrafficPolicyInstances$, ListTrafficPolicyInstancesCommand],
      [ListTrafficPolicyInstancesByHostedZone$, ListTrafficPolicyInstancesByHostedZoneCommand],
      [ListTrafficPolicyInstancesByPolicy$, ListTrafficPolicyInstancesByPolicyCommand],
      [ListTrafficPolicyVersions$, ListTrafficPolicyVersionsCommand],
      [ListVPCAssociationAuthorizations$, ListVPCAssociationAuthorizationsCommand],
      [TestDNSAnswer$, TestDNSAnswerCommand],
      [UpdateHealthCheck$, UpdateHealthCheckCommand],
      [UpdateHostedZoneComment$, UpdateHostedZoneCommentCommand],
      [UpdateHostedZoneFeatures$, UpdateHostedZoneFeaturesCommand],
      [UpdateTrafficPolicyComment$, UpdateTrafficPolicyCommentCommand],
      [UpdateTrafficPolicyInstance$, UpdateTrafficPolicyInstanceCommand],
    ]),
    errors: [
      CidrBlockInUseException$,
      CidrCollectionAlreadyExistsException$,
      CidrCollectionInUseException$,
      CidrCollectionVersionMismatchException$,
      ConcurrentModification$,
      ConflictingDomainExists$,
      ConflictingTypes$,
      DelegationSetAlreadyCreated$,
      DelegationSetAlreadyReusable$,
      DelegationSetInUse$,
      DelegationSetNotAvailable$,
      DelegationSetNotReusable$,
      DNSSECNotFound$,
      HealthCheckAlreadyExists$,
      HealthCheckInUse$,
      HealthCheckVersionMismatch$,
      HostedZoneAlreadyExists$,
      HostedZoneNotEmpty$,
      HostedZoneNotFound$,
      HostedZoneNotPrivate$,
      HostedZonePartiallyDelegated$,
      IncompatibleVersion$,
      InsufficientCloudWatchLogsResourcePolicy$,
      InvalidArgument$,
      InvalidChangeBatch$,
      InvalidDomainName$,
      InvalidInput$,
      InvalidKeySigningKeyName$,
      InvalidKeySigningKeyStatus$,
      InvalidKMSArn$,
      InvalidPaginationToken$,
      InvalidSigningStatus$,
      InvalidTrafficPolicyDocument$,
      InvalidVPCId$,
      KeySigningKeyAlreadyExists$,
      KeySigningKeyInParentDSRecord$,
      KeySigningKeyInUse$,
      KeySigningKeyWithActiveStatusNotFound$,
      LastVPCAssociation$,
      LimitsExceeded$,
      NoSuchChange$,
      NoSuchCidrCollectionException$,
      NoSuchCidrLocationException$,
      NoSuchCloudWatchLogsLogGroup$,
      NoSuchDelegationSet$,
      NoSuchGeoLocation$,
      NoSuchHealthCheck$,
      NoSuchHostedZone$,
      NoSuchKeySigningKey$,
      NoSuchQueryLoggingConfig$,
      NoSuchTrafficPolicy$,
      NoSuchTrafficPolicyInstance$,
      NotAuthorizedException$,
      PriorRequestNotComplete$,
      PublicZoneVPCAssociation$,
      QueryLoggingConfigAlreadyExists$,
      ThrottlingException$,
      TooManyHealthChecks$,
      TooManyHostedZones$,
      TooManyKeySigningKeys$,
      TooManyTrafficPolicies$,
      TooManyTrafficPolicyInstances$,
      TooManyTrafficPolicyVersionsForCurrentPolicy$,
      TooManyVPCAssociationAuthorizations$,
      TrafficPolicyAlreadyExists$,
      TrafficPolicyInstanceAlreadyExists$,
      TrafficPolicyInUse$,
      VPCAssociationAuthorizationNotFound$,
      VPCAssociationNotFound$,
    ],
  });
  runner.run();
}, 30_000);
