import { CancelClusterCommandInput, CancelClusterCommandOutput } from "../commands/CancelClusterCommand";
import { CancelJobCommandInput, CancelJobCommandOutput } from "../commands/CancelJobCommand";
import { CreateAddressCommandInput, CreateAddressCommandOutput } from "../commands/CreateAddressCommand";
import { CreateClusterCommandInput, CreateClusterCommandOutput } from "../commands/CreateClusterCommand";
import { CreateJobCommandInput, CreateJobCommandOutput } from "../commands/CreateJobCommand";
import { DescribeAddressCommandInput, DescribeAddressCommandOutput } from "../commands/DescribeAddressCommand";
import { DescribeAddressesCommandInput, DescribeAddressesCommandOutput } from "../commands/DescribeAddressesCommand";
import { DescribeClusterCommandInput, DescribeClusterCommandOutput } from "../commands/DescribeClusterCommand";
import { DescribeJobCommandInput, DescribeJobCommandOutput } from "../commands/DescribeJobCommand";
import { GetJobManifestCommandInput, GetJobManifestCommandOutput } from "../commands/GetJobManifestCommand";
import { GetJobUnlockCodeCommandInput, GetJobUnlockCodeCommandOutput } from "../commands/GetJobUnlockCodeCommand";
import { GetSnowballUsageCommandInput, GetSnowballUsageCommandOutput } from "../commands/GetSnowballUsageCommand";
import { GetSoftwareUpdatesCommandInput, GetSoftwareUpdatesCommandOutput } from "../commands/GetSoftwareUpdatesCommand";
import { ListClusterJobsCommandInput, ListClusterJobsCommandOutput } from "../commands/ListClusterJobsCommand";
import { ListClustersCommandInput, ListClustersCommandOutput } from "../commands/ListClustersCommand";
import { ListCompatibleImagesCommandInput, ListCompatibleImagesCommandOutput } from "../commands/ListCompatibleImagesCommand";
import { ListJobsCommandInput, ListJobsCommandOutput } from "../commands/ListJobsCommand";
import { UpdateClusterCommandInput, UpdateClusterCommandOutput } from "../commands/UpdateClusterCommand";
import { UpdateJobCommandInput, UpdateJobCommandOutput } from "../commands/UpdateJobCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CancelClusterCommand(input: CancelClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelJobCommand(input: CancelJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAddressCommand(input: CreateAddressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateClusterCommand(input: CreateClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateJobCommand(input: CreateJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAddressCommand(input: DescribeAddressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAddressesCommand(input: DescribeAddressesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeClusterCommand(input: DescribeClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeJobCommand(input: DescribeJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobManifestCommand(input: GetJobManifestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobUnlockCodeCommand(input: GetJobUnlockCodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSnowballUsageCommand(input: GetSnowballUsageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSoftwareUpdatesCommand(input: GetSoftwareUpdatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListClusterJobsCommand(input: ListClusterJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListClustersCommand(input: ListClustersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListCompatibleImagesCommand(input: ListCompatibleImagesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListJobsCommand(input: ListJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateClusterCommand(input: UpdateClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateJobCommand(input: UpdateJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CancelClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelClusterCommandOutput>;
export declare function deserializeAws_json1_1CancelJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelJobCommandOutput>;
export declare function deserializeAws_json1_1CreateAddressCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAddressCommandOutput>;
export declare function deserializeAws_json1_1CreateClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterCommandOutput>;
export declare function deserializeAws_json1_1CreateJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateJobCommandOutput>;
export declare function deserializeAws_json1_1DescribeAddressCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAddressCommandOutput>;
export declare function deserializeAws_json1_1DescribeAddressesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAddressesCommandOutput>;
export declare function deserializeAws_json1_1DescribeClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterCommandOutput>;
export declare function deserializeAws_json1_1DescribeJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeJobCommandOutput>;
export declare function deserializeAws_json1_1GetJobManifestCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobManifestCommandOutput>;
export declare function deserializeAws_json1_1GetJobUnlockCodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobUnlockCodeCommandOutput>;
export declare function deserializeAws_json1_1GetSnowballUsageCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSnowballUsageCommandOutput>;
export declare function deserializeAws_json1_1GetSoftwareUpdatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSoftwareUpdatesCommandOutput>;
export declare function deserializeAws_json1_1ListClusterJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListClusterJobsCommandOutput>;
export declare function deserializeAws_json1_1ListClustersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListClustersCommandOutput>;
export declare function deserializeAws_json1_1ListCompatibleImagesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCompatibleImagesCommandOutput>;
export declare function deserializeAws_json1_1ListJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListJobsCommandOutput>;
export declare function deserializeAws_json1_1UpdateClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateClusterCommandOutput>;
export declare function deserializeAws_json1_1UpdateJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateJobCommandOutput>;
