import { CreateCloudFrontOriginAccessIdentityCommandInput, CreateCloudFrontOriginAccessIdentityCommandOutput } from "../commands/CreateCloudFrontOriginAccessIdentityCommand";
import { CreateDistributionCommandInput, CreateDistributionCommandOutput } from "../commands/CreateDistributionCommand";
import { CreateDistributionWithTagsCommandInput, CreateDistributionWithTagsCommandOutput } from "../commands/CreateDistributionWithTagsCommand";
import { CreateFieldLevelEncryptionConfigCommandInput, CreateFieldLevelEncryptionConfigCommandOutput } from "../commands/CreateFieldLevelEncryptionConfigCommand";
import { CreateFieldLevelEncryptionProfileCommandInput, CreateFieldLevelEncryptionProfileCommandOutput } from "../commands/CreateFieldLevelEncryptionProfileCommand";
import { CreateInvalidationCommandInput, CreateInvalidationCommandOutput } from "../commands/CreateInvalidationCommand";
import { CreatePublicKeyCommandInput, CreatePublicKeyCommandOutput } from "../commands/CreatePublicKeyCommand";
import { CreateStreamingDistributionCommandInput, CreateStreamingDistributionCommandOutput } from "../commands/CreateStreamingDistributionCommand";
import { CreateStreamingDistributionWithTagsCommandInput, CreateStreamingDistributionWithTagsCommandOutput } from "../commands/CreateStreamingDistributionWithTagsCommand";
import { DeleteCloudFrontOriginAccessIdentityCommandInput, DeleteCloudFrontOriginAccessIdentityCommandOutput } from "../commands/DeleteCloudFrontOriginAccessIdentityCommand";
import { DeleteDistributionCommandInput, DeleteDistributionCommandOutput } from "../commands/DeleteDistributionCommand";
import { DeleteFieldLevelEncryptionConfigCommandInput, DeleteFieldLevelEncryptionConfigCommandOutput } from "../commands/DeleteFieldLevelEncryptionConfigCommand";
import { DeleteFieldLevelEncryptionProfileCommandInput, DeleteFieldLevelEncryptionProfileCommandOutput } from "../commands/DeleteFieldLevelEncryptionProfileCommand";
import { DeletePublicKeyCommandInput, DeletePublicKeyCommandOutput } from "../commands/DeletePublicKeyCommand";
import { DeleteStreamingDistributionCommandInput, DeleteStreamingDistributionCommandOutput } from "../commands/DeleteStreamingDistributionCommand";
import { GetCloudFrontOriginAccessIdentityCommandInput, GetCloudFrontOriginAccessIdentityCommandOutput } from "../commands/GetCloudFrontOriginAccessIdentityCommand";
import { GetCloudFrontOriginAccessIdentityConfigCommandInput, GetCloudFrontOriginAccessIdentityConfigCommandOutput } from "../commands/GetCloudFrontOriginAccessIdentityConfigCommand";
import { GetDistributionCommandInput, GetDistributionCommandOutput } from "../commands/GetDistributionCommand";
import { GetDistributionConfigCommandInput, GetDistributionConfigCommandOutput } from "../commands/GetDistributionConfigCommand";
import { GetFieldLevelEncryptionCommandInput, GetFieldLevelEncryptionCommandOutput } from "../commands/GetFieldLevelEncryptionCommand";
import { GetFieldLevelEncryptionConfigCommandInput, GetFieldLevelEncryptionConfigCommandOutput } from "../commands/GetFieldLevelEncryptionConfigCommand";
import { GetFieldLevelEncryptionProfileCommandInput, GetFieldLevelEncryptionProfileCommandOutput } from "../commands/GetFieldLevelEncryptionProfileCommand";
import { GetFieldLevelEncryptionProfileConfigCommandInput, GetFieldLevelEncryptionProfileConfigCommandOutput } from "../commands/GetFieldLevelEncryptionProfileConfigCommand";
import { GetInvalidationCommandInput, GetInvalidationCommandOutput } from "../commands/GetInvalidationCommand";
import { GetPublicKeyCommandInput, GetPublicKeyCommandOutput } from "../commands/GetPublicKeyCommand";
import { GetPublicKeyConfigCommandInput, GetPublicKeyConfigCommandOutput } from "../commands/GetPublicKeyConfigCommand";
import { GetStreamingDistributionCommandInput, GetStreamingDistributionCommandOutput } from "../commands/GetStreamingDistributionCommand";
import { GetStreamingDistributionConfigCommandInput, GetStreamingDistributionConfigCommandOutput } from "../commands/GetStreamingDistributionConfigCommand";
import { ListCloudFrontOriginAccessIdentitiesCommandInput, ListCloudFrontOriginAccessIdentitiesCommandOutput } from "../commands/ListCloudFrontOriginAccessIdentitiesCommand";
import { ListDistributionsByWebACLIdCommandInput, ListDistributionsByWebACLIdCommandOutput } from "../commands/ListDistributionsByWebACLIdCommand";
import { ListDistributionsCommandInput, ListDistributionsCommandOutput } from "../commands/ListDistributionsCommand";
import { ListFieldLevelEncryptionConfigsCommandInput, ListFieldLevelEncryptionConfigsCommandOutput } from "../commands/ListFieldLevelEncryptionConfigsCommand";
import { ListFieldLevelEncryptionProfilesCommandInput, ListFieldLevelEncryptionProfilesCommandOutput } from "../commands/ListFieldLevelEncryptionProfilesCommand";
import { ListInvalidationsCommandInput, ListInvalidationsCommandOutput } from "../commands/ListInvalidationsCommand";
import { ListPublicKeysCommandInput, ListPublicKeysCommandOutput } from "../commands/ListPublicKeysCommand";
import { ListStreamingDistributionsCommandInput, ListStreamingDistributionsCommandOutput } from "../commands/ListStreamingDistributionsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateCloudFrontOriginAccessIdentityCommandInput, UpdateCloudFrontOriginAccessIdentityCommandOutput } from "../commands/UpdateCloudFrontOriginAccessIdentityCommand";
import { UpdateDistributionCommandInput, UpdateDistributionCommandOutput } from "../commands/UpdateDistributionCommand";
import { UpdateFieldLevelEncryptionConfigCommandInput, UpdateFieldLevelEncryptionConfigCommandOutput } from "../commands/UpdateFieldLevelEncryptionConfigCommand";
import { UpdateFieldLevelEncryptionProfileCommandInput, UpdateFieldLevelEncryptionProfileCommandOutput } from "../commands/UpdateFieldLevelEncryptionProfileCommand";
import { UpdatePublicKeyCommandInput, UpdatePublicKeyCommandOutput } from "../commands/UpdatePublicKeyCommand";
import { UpdateStreamingDistributionCommandInput, UpdateStreamingDistributionCommandOutput } from "../commands/UpdateStreamingDistributionCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restXmlCreateCloudFrontOriginAccessIdentityCommand(input: CreateCloudFrontOriginAccessIdentityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateDistributionCommand(input: CreateDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateDistributionWithTagsCommand(input: CreateDistributionWithTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateFieldLevelEncryptionConfigCommand(input: CreateFieldLevelEncryptionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateFieldLevelEncryptionProfileCommand(input: CreateFieldLevelEncryptionProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateInvalidationCommand(input: CreateInvalidationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreatePublicKeyCommand(input: CreatePublicKeyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateStreamingDistributionCommand(input: CreateStreamingDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlCreateStreamingDistributionWithTagsCommand(input: CreateStreamingDistributionWithTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeleteCloudFrontOriginAccessIdentityCommand(input: DeleteCloudFrontOriginAccessIdentityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeleteDistributionCommand(input: DeleteDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeleteFieldLevelEncryptionConfigCommand(input: DeleteFieldLevelEncryptionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeleteFieldLevelEncryptionProfileCommand(input: DeleteFieldLevelEncryptionProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeletePublicKeyCommand(input: DeletePublicKeyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlDeleteStreamingDistributionCommand(input: DeleteStreamingDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetCloudFrontOriginAccessIdentityCommand(input: GetCloudFrontOriginAccessIdentityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetCloudFrontOriginAccessIdentityConfigCommand(input: GetCloudFrontOriginAccessIdentityConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetDistributionCommand(input: GetDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetDistributionConfigCommand(input: GetDistributionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetFieldLevelEncryptionCommand(input: GetFieldLevelEncryptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetFieldLevelEncryptionConfigCommand(input: GetFieldLevelEncryptionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetFieldLevelEncryptionProfileCommand(input: GetFieldLevelEncryptionProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetFieldLevelEncryptionProfileConfigCommand(input: GetFieldLevelEncryptionProfileConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetInvalidationCommand(input: GetInvalidationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetPublicKeyCommand(input: GetPublicKeyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetPublicKeyConfigCommand(input: GetPublicKeyConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetStreamingDistributionCommand(input: GetStreamingDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlGetStreamingDistributionConfigCommand(input: GetStreamingDistributionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListCloudFrontOriginAccessIdentitiesCommand(input: ListCloudFrontOriginAccessIdentitiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListDistributionsCommand(input: ListDistributionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListDistributionsByWebACLIdCommand(input: ListDistributionsByWebACLIdCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListFieldLevelEncryptionConfigsCommand(input: ListFieldLevelEncryptionConfigsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListFieldLevelEncryptionProfilesCommand(input: ListFieldLevelEncryptionProfilesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListInvalidationsCommand(input: ListInvalidationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListPublicKeysCommand(input: ListPublicKeysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListStreamingDistributionsCommand(input: ListStreamingDistributionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlTagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdateCloudFrontOriginAccessIdentityCommand(input: UpdateCloudFrontOriginAccessIdentityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdateDistributionCommand(input: UpdateDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdateFieldLevelEncryptionConfigCommand(input: UpdateFieldLevelEncryptionConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdateFieldLevelEncryptionProfileCommand(input: UpdateFieldLevelEncryptionProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdatePublicKeyCommand(input: UpdatePublicKeyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restXmlUpdateStreamingDistributionCommand(input: UpdateStreamingDistributionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restXmlCreateCloudFrontOriginAccessIdentityCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCloudFrontOriginAccessIdentityCommandOutput>;
export declare function deserializeAws_restXmlCreateDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDistributionCommandOutput>;
export declare function deserializeAws_restXmlCreateDistributionWithTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDistributionWithTagsCommandOutput>;
export declare function deserializeAws_restXmlCreateFieldLevelEncryptionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateFieldLevelEncryptionConfigCommandOutput>;
export declare function deserializeAws_restXmlCreateFieldLevelEncryptionProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateFieldLevelEncryptionProfileCommandOutput>;
export declare function deserializeAws_restXmlCreateInvalidationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInvalidationCommandOutput>;
export declare function deserializeAws_restXmlCreatePublicKeyCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePublicKeyCommandOutput>;
export declare function deserializeAws_restXmlCreateStreamingDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStreamingDistributionCommandOutput>;
export declare function deserializeAws_restXmlCreateStreamingDistributionWithTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStreamingDistributionWithTagsCommandOutput>;
export declare function deserializeAws_restXmlDeleteCloudFrontOriginAccessIdentityCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCloudFrontOriginAccessIdentityCommandOutput>;
export declare function deserializeAws_restXmlDeleteDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDistributionCommandOutput>;
export declare function deserializeAws_restXmlDeleteFieldLevelEncryptionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFieldLevelEncryptionConfigCommandOutput>;
export declare function deserializeAws_restXmlDeleteFieldLevelEncryptionProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFieldLevelEncryptionProfileCommandOutput>;
export declare function deserializeAws_restXmlDeletePublicKeyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePublicKeyCommandOutput>;
export declare function deserializeAws_restXmlDeleteStreamingDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteStreamingDistributionCommandOutput>;
export declare function deserializeAws_restXmlGetCloudFrontOriginAccessIdentityCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCloudFrontOriginAccessIdentityCommandOutput>;
export declare function deserializeAws_restXmlGetCloudFrontOriginAccessIdentityConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCloudFrontOriginAccessIdentityConfigCommandOutput>;
export declare function deserializeAws_restXmlGetDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDistributionCommandOutput>;
export declare function deserializeAws_restXmlGetDistributionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDistributionConfigCommandOutput>;
export declare function deserializeAws_restXmlGetFieldLevelEncryptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFieldLevelEncryptionCommandOutput>;
export declare function deserializeAws_restXmlGetFieldLevelEncryptionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFieldLevelEncryptionConfigCommandOutput>;
export declare function deserializeAws_restXmlGetFieldLevelEncryptionProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFieldLevelEncryptionProfileCommandOutput>;
export declare function deserializeAws_restXmlGetFieldLevelEncryptionProfileConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFieldLevelEncryptionProfileConfigCommandOutput>;
export declare function deserializeAws_restXmlGetInvalidationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInvalidationCommandOutput>;
export declare function deserializeAws_restXmlGetPublicKeyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPublicKeyCommandOutput>;
export declare function deserializeAws_restXmlGetPublicKeyConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPublicKeyConfigCommandOutput>;
export declare function deserializeAws_restXmlGetStreamingDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetStreamingDistributionCommandOutput>;
export declare function deserializeAws_restXmlGetStreamingDistributionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetStreamingDistributionConfigCommandOutput>;
export declare function deserializeAws_restXmlListCloudFrontOriginAccessIdentitiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCloudFrontOriginAccessIdentitiesCommandOutput>;
export declare function deserializeAws_restXmlListDistributionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDistributionsCommandOutput>;
export declare function deserializeAws_restXmlListDistributionsByWebACLIdCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDistributionsByWebACLIdCommandOutput>;
export declare function deserializeAws_restXmlListFieldLevelEncryptionConfigsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFieldLevelEncryptionConfigsCommandOutput>;
export declare function deserializeAws_restXmlListFieldLevelEncryptionProfilesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFieldLevelEncryptionProfilesCommandOutput>;
export declare function deserializeAws_restXmlListInvalidationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListInvalidationsCommandOutput>;
export declare function deserializeAws_restXmlListPublicKeysCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPublicKeysCommandOutput>;
export declare function deserializeAws_restXmlListStreamingDistributionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListStreamingDistributionsCommandOutput>;
export declare function deserializeAws_restXmlListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_restXmlTagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_restXmlUntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_restXmlUpdateCloudFrontOriginAccessIdentityCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateCloudFrontOriginAccessIdentityCommandOutput>;
export declare function deserializeAws_restXmlUpdateDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDistributionCommandOutput>;
export declare function deserializeAws_restXmlUpdateFieldLevelEncryptionConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFieldLevelEncryptionConfigCommandOutput>;
export declare function deserializeAws_restXmlUpdateFieldLevelEncryptionProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFieldLevelEncryptionProfileCommandOutput>;
export declare function deserializeAws_restXmlUpdatePublicKeyCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePublicKeyCommandOutput>;
export declare function deserializeAws_restXmlUpdateStreamingDistributionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateStreamingDistributionCommandOutput>;
