import { AddApplicationCloudWatchLoggingOptionCommandInput, AddApplicationCloudWatchLoggingOptionCommandOutput } from "../commands/AddApplicationCloudWatchLoggingOptionCommand";
import { AddApplicationInputCommandInput, AddApplicationInputCommandOutput } from "../commands/AddApplicationInputCommand";
import { AddApplicationInputProcessingConfigurationCommandInput, AddApplicationInputProcessingConfigurationCommandOutput } from "../commands/AddApplicationInputProcessingConfigurationCommand";
import { AddApplicationOutputCommandInput, AddApplicationOutputCommandOutput } from "../commands/AddApplicationOutputCommand";
import { AddApplicationReferenceDataSourceCommandInput, AddApplicationReferenceDataSourceCommandOutput } from "../commands/AddApplicationReferenceDataSourceCommand";
import { CreateApplicationCommandInput, CreateApplicationCommandOutput } from "../commands/CreateApplicationCommand";
import { DeleteApplicationCloudWatchLoggingOptionCommandInput, DeleteApplicationCloudWatchLoggingOptionCommandOutput } from "../commands/DeleteApplicationCloudWatchLoggingOptionCommand";
import { DeleteApplicationCommandInput, DeleteApplicationCommandOutput } from "../commands/DeleteApplicationCommand";
import { DeleteApplicationInputProcessingConfigurationCommandInput, DeleteApplicationInputProcessingConfigurationCommandOutput } from "../commands/DeleteApplicationInputProcessingConfigurationCommand";
import { DeleteApplicationOutputCommandInput, DeleteApplicationOutputCommandOutput } from "../commands/DeleteApplicationOutputCommand";
import { DeleteApplicationReferenceDataSourceCommandInput, DeleteApplicationReferenceDataSourceCommandOutput } from "../commands/DeleteApplicationReferenceDataSourceCommand";
import { DescribeApplicationCommandInput, DescribeApplicationCommandOutput } from "../commands/DescribeApplicationCommand";
import { DiscoverInputSchemaCommandInput, DiscoverInputSchemaCommandOutput } from "../commands/DiscoverInputSchemaCommand";
import { ListApplicationsCommandInput, ListApplicationsCommandOutput } from "../commands/ListApplicationsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { StartApplicationCommandInput, StartApplicationCommandOutput } from "../commands/StartApplicationCommand";
import { StopApplicationCommandInput, StopApplicationCommandOutput } from "../commands/StopApplicationCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateApplicationCommandInput, UpdateApplicationCommandOutput } from "../commands/UpdateApplicationCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddApplicationCloudWatchLoggingOptionCommand(input: AddApplicationCloudWatchLoggingOptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddApplicationInputCommand(input: AddApplicationInputCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddApplicationInputProcessingConfigurationCommand(input: AddApplicationInputProcessingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddApplicationOutputCommand(input: AddApplicationOutputCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddApplicationReferenceDataSourceCommand(input: AddApplicationReferenceDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateApplicationCommand(input: CreateApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApplicationCommand(input: DeleteApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApplicationCloudWatchLoggingOptionCommand(input: DeleteApplicationCloudWatchLoggingOptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApplicationInputProcessingConfigurationCommand(input: DeleteApplicationInputProcessingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApplicationOutputCommand(input: DeleteApplicationOutputCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApplicationReferenceDataSourceCommand(input: DeleteApplicationReferenceDataSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeApplicationCommand(input: DescribeApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DiscoverInputSchemaCommand(input: DiscoverInputSchemaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListApplicationsCommand(input: ListApplicationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartApplicationCommand(input: StartApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopApplicationCommand(input: StopApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateApplicationCommand(input: UpdateApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddApplicationCloudWatchLoggingOptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddApplicationCloudWatchLoggingOptionCommandOutput>;
export declare function deserializeAws_json1_1AddApplicationInputCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddApplicationInputCommandOutput>;
export declare function deserializeAws_json1_1AddApplicationInputProcessingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddApplicationInputProcessingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1AddApplicationOutputCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddApplicationOutputCommandOutput>;
export declare function deserializeAws_json1_1AddApplicationReferenceDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddApplicationReferenceDataSourceCommandOutput>;
export declare function deserializeAws_json1_1CreateApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateApplicationCommandOutput>;
export declare function deserializeAws_json1_1DeleteApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationCommandOutput>;
export declare function deserializeAws_json1_1DeleteApplicationCloudWatchLoggingOptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationCloudWatchLoggingOptionCommandOutput>;
export declare function deserializeAws_json1_1DeleteApplicationInputProcessingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationInputProcessingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeleteApplicationOutputCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationOutputCommandOutput>;
export declare function deserializeAws_json1_1DeleteApplicationReferenceDataSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationReferenceDataSourceCommandOutput>;
export declare function deserializeAws_json1_1DescribeApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeApplicationCommandOutput>;
export declare function deserializeAws_json1_1DiscoverInputSchemaCommand(output: __HttpResponse, context: __SerdeContext): Promise<DiscoverInputSchemaCommandOutput>;
export declare function deserializeAws_json1_1ListApplicationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListApplicationsCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1StartApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartApplicationCommandOutput>;
export declare function deserializeAws_json1_1StopApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopApplicationCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApplicationCommandOutput>;
