import { AcceptMatchCommandInput, AcceptMatchCommandOutput } from "../commands/AcceptMatchCommand";
import { CreateAliasCommandInput, CreateAliasCommandOutput } from "../commands/CreateAliasCommand";
import { CreateBuildCommandInput, CreateBuildCommandOutput } from "../commands/CreateBuildCommand";
import { CreateFleetCommandInput, CreateFleetCommandOutput } from "../commands/CreateFleetCommand";
import { CreateGameSessionCommandInput, CreateGameSessionCommandOutput } from "../commands/CreateGameSessionCommand";
import { CreateGameSessionQueueCommandInput, CreateGameSessionQueueCommandOutput } from "../commands/CreateGameSessionQueueCommand";
import { CreateMatchmakingConfigurationCommandInput, CreateMatchmakingConfigurationCommandOutput } from "../commands/CreateMatchmakingConfigurationCommand";
import { CreateMatchmakingRuleSetCommandInput, CreateMatchmakingRuleSetCommandOutput } from "../commands/CreateMatchmakingRuleSetCommand";
import { CreatePlayerSessionCommandInput, CreatePlayerSessionCommandOutput } from "../commands/CreatePlayerSessionCommand";
import { CreatePlayerSessionsCommandInput, CreatePlayerSessionsCommandOutput } from "../commands/CreatePlayerSessionsCommand";
import { CreateScriptCommandInput, CreateScriptCommandOutput } from "../commands/CreateScriptCommand";
import { CreateVpcPeeringAuthorizationCommandInput, CreateVpcPeeringAuthorizationCommandOutput } from "../commands/CreateVpcPeeringAuthorizationCommand";
import { CreateVpcPeeringConnectionCommandInput, CreateVpcPeeringConnectionCommandOutput } from "../commands/CreateVpcPeeringConnectionCommand";
import { DeleteAliasCommandInput, DeleteAliasCommandOutput } from "../commands/DeleteAliasCommand";
import { DeleteBuildCommandInput, DeleteBuildCommandOutput } from "../commands/DeleteBuildCommand";
import { DeleteFleetCommandInput, DeleteFleetCommandOutput } from "../commands/DeleteFleetCommand";
import { DeleteGameSessionQueueCommandInput, DeleteGameSessionQueueCommandOutput } from "../commands/DeleteGameSessionQueueCommand";
import { DeleteMatchmakingConfigurationCommandInput, DeleteMatchmakingConfigurationCommandOutput } from "../commands/DeleteMatchmakingConfigurationCommand";
import { DeleteMatchmakingRuleSetCommandInput, DeleteMatchmakingRuleSetCommandOutput } from "../commands/DeleteMatchmakingRuleSetCommand";
import { DeleteScalingPolicyCommandInput, DeleteScalingPolicyCommandOutput } from "../commands/DeleteScalingPolicyCommand";
import { DeleteScriptCommandInput, DeleteScriptCommandOutput } from "../commands/DeleteScriptCommand";
import { DeleteVpcPeeringAuthorizationCommandInput, DeleteVpcPeeringAuthorizationCommandOutput } from "../commands/DeleteVpcPeeringAuthorizationCommand";
import { DeleteVpcPeeringConnectionCommandInput, DeleteVpcPeeringConnectionCommandOutput } from "../commands/DeleteVpcPeeringConnectionCommand";
import { DescribeAliasCommandInput, DescribeAliasCommandOutput } from "../commands/DescribeAliasCommand";
import { DescribeBuildCommandInput, DescribeBuildCommandOutput } from "../commands/DescribeBuildCommand";
import { DescribeEC2InstanceLimitsCommandInput, DescribeEC2InstanceLimitsCommandOutput } from "../commands/DescribeEC2InstanceLimitsCommand";
import { DescribeFleetAttributesCommandInput, DescribeFleetAttributesCommandOutput } from "../commands/DescribeFleetAttributesCommand";
import { DescribeFleetCapacityCommandInput, DescribeFleetCapacityCommandOutput } from "../commands/DescribeFleetCapacityCommand";
import { DescribeFleetEventsCommandInput, DescribeFleetEventsCommandOutput } from "../commands/DescribeFleetEventsCommand";
import { DescribeFleetPortSettingsCommandInput, DescribeFleetPortSettingsCommandOutput } from "../commands/DescribeFleetPortSettingsCommand";
import { DescribeFleetUtilizationCommandInput, DescribeFleetUtilizationCommandOutput } from "../commands/DescribeFleetUtilizationCommand";
import { DescribeGameSessionDetailsCommandInput, DescribeGameSessionDetailsCommandOutput } from "../commands/DescribeGameSessionDetailsCommand";
import { DescribeGameSessionPlacementCommandInput, DescribeGameSessionPlacementCommandOutput } from "../commands/DescribeGameSessionPlacementCommand";
import { DescribeGameSessionQueuesCommandInput, DescribeGameSessionQueuesCommandOutput } from "../commands/DescribeGameSessionQueuesCommand";
import { DescribeGameSessionsCommandInput, DescribeGameSessionsCommandOutput } from "../commands/DescribeGameSessionsCommand";
import { DescribeInstancesCommandInput, DescribeInstancesCommandOutput } from "../commands/DescribeInstancesCommand";
import { DescribeMatchmakingCommandInput, DescribeMatchmakingCommandOutput } from "../commands/DescribeMatchmakingCommand";
import { DescribeMatchmakingConfigurationsCommandInput, DescribeMatchmakingConfigurationsCommandOutput } from "../commands/DescribeMatchmakingConfigurationsCommand";
import { DescribeMatchmakingRuleSetsCommandInput, DescribeMatchmakingRuleSetsCommandOutput } from "../commands/DescribeMatchmakingRuleSetsCommand";
import { DescribePlayerSessionsCommandInput, DescribePlayerSessionsCommandOutput } from "../commands/DescribePlayerSessionsCommand";
import { DescribeRuntimeConfigurationCommandInput, DescribeRuntimeConfigurationCommandOutput } from "../commands/DescribeRuntimeConfigurationCommand";
import { DescribeScalingPoliciesCommandInput, DescribeScalingPoliciesCommandOutput } from "../commands/DescribeScalingPoliciesCommand";
import { DescribeScriptCommandInput, DescribeScriptCommandOutput } from "../commands/DescribeScriptCommand";
import { DescribeVpcPeeringAuthorizationsCommandInput, DescribeVpcPeeringAuthorizationsCommandOutput } from "../commands/DescribeVpcPeeringAuthorizationsCommand";
import { DescribeVpcPeeringConnectionsCommandInput, DescribeVpcPeeringConnectionsCommandOutput } from "../commands/DescribeVpcPeeringConnectionsCommand";
import { GetGameSessionLogUrlCommandInput, GetGameSessionLogUrlCommandOutput } from "../commands/GetGameSessionLogUrlCommand";
import { GetInstanceAccessCommandInput, GetInstanceAccessCommandOutput } from "../commands/GetInstanceAccessCommand";
import { ListAliasesCommandInput, ListAliasesCommandOutput } from "../commands/ListAliasesCommand";
import { ListBuildsCommandInput, ListBuildsCommandOutput } from "../commands/ListBuildsCommand";
import { ListFleetsCommandInput, ListFleetsCommandOutput } from "../commands/ListFleetsCommand";
import { ListScriptsCommandInput, ListScriptsCommandOutput } from "../commands/ListScriptsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { PutScalingPolicyCommandInput, PutScalingPolicyCommandOutput } from "../commands/PutScalingPolicyCommand";
import { RequestUploadCredentialsCommandInput, RequestUploadCredentialsCommandOutput } from "../commands/RequestUploadCredentialsCommand";
import { ResolveAliasCommandInput, ResolveAliasCommandOutput } from "../commands/ResolveAliasCommand";
import { SearchGameSessionsCommandInput, SearchGameSessionsCommandOutput } from "../commands/SearchGameSessionsCommand";
import { StartFleetActionsCommandInput, StartFleetActionsCommandOutput } from "../commands/StartFleetActionsCommand";
import { StartGameSessionPlacementCommandInput, StartGameSessionPlacementCommandOutput } from "../commands/StartGameSessionPlacementCommand";
import { StartMatchBackfillCommandInput, StartMatchBackfillCommandOutput } from "../commands/StartMatchBackfillCommand";
import { StartMatchmakingCommandInput, StartMatchmakingCommandOutput } from "../commands/StartMatchmakingCommand";
import { StopFleetActionsCommandInput, StopFleetActionsCommandOutput } from "../commands/StopFleetActionsCommand";
import { StopGameSessionPlacementCommandInput, StopGameSessionPlacementCommandOutput } from "../commands/StopGameSessionPlacementCommand";
import { StopMatchmakingCommandInput, StopMatchmakingCommandOutput } from "../commands/StopMatchmakingCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateAliasCommandInput, UpdateAliasCommandOutput } from "../commands/UpdateAliasCommand";
import { UpdateBuildCommandInput, UpdateBuildCommandOutput } from "../commands/UpdateBuildCommand";
import { UpdateFleetAttributesCommandInput, UpdateFleetAttributesCommandOutput } from "../commands/UpdateFleetAttributesCommand";
import { UpdateFleetCapacityCommandInput, UpdateFleetCapacityCommandOutput } from "../commands/UpdateFleetCapacityCommand";
import { UpdateFleetPortSettingsCommandInput, UpdateFleetPortSettingsCommandOutput } from "../commands/UpdateFleetPortSettingsCommand";
import { UpdateGameSessionCommandInput, UpdateGameSessionCommandOutput } from "../commands/UpdateGameSessionCommand";
import { UpdateGameSessionQueueCommandInput, UpdateGameSessionQueueCommandOutput } from "../commands/UpdateGameSessionQueueCommand";
import { UpdateMatchmakingConfigurationCommandInput, UpdateMatchmakingConfigurationCommandOutput } from "../commands/UpdateMatchmakingConfigurationCommand";
import { UpdateRuntimeConfigurationCommandInput, UpdateRuntimeConfigurationCommandOutput } from "../commands/UpdateRuntimeConfigurationCommand";
import { UpdateScriptCommandInput, UpdateScriptCommandOutput } from "../commands/UpdateScriptCommand";
import { ValidateMatchmakingRuleSetCommandInput, ValidateMatchmakingRuleSetCommandOutput } from "../commands/ValidateMatchmakingRuleSetCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AcceptMatchCommand(input: AcceptMatchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAliasCommand(input: CreateAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateBuildCommand(input: CreateBuildCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateFleetCommand(input: CreateFleetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateGameSessionCommand(input: CreateGameSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateGameSessionQueueCommand(input: CreateGameSessionQueueCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateMatchmakingConfigurationCommand(input: CreateMatchmakingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateMatchmakingRuleSetCommand(input: CreateMatchmakingRuleSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePlayerSessionCommand(input: CreatePlayerSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePlayerSessionsCommand(input: CreatePlayerSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateScriptCommand(input: CreateScriptCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateVpcPeeringAuthorizationCommand(input: CreateVpcPeeringAuthorizationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateVpcPeeringConnectionCommand(input: CreateVpcPeeringConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAliasCommand(input: DeleteAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBuildCommand(input: DeleteBuildCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteFleetCommand(input: DeleteFleetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteGameSessionQueueCommand(input: DeleteGameSessionQueueCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMatchmakingConfigurationCommand(input: DeleteMatchmakingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMatchmakingRuleSetCommand(input: DeleteMatchmakingRuleSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteScalingPolicyCommand(input: DeleteScalingPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteScriptCommand(input: DeleteScriptCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVpcPeeringAuthorizationCommand(input: DeleteVpcPeeringAuthorizationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVpcPeeringConnectionCommand(input: DeleteVpcPeeringConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAliasCommand(input: DescribeAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBuildCommand(input: DescribeBuildCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEC2InstanceLimitsCommand(input: DescribeEC2InstanceLimitsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFleetAttributesCommand(input: DescribeFleetAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFleetCapacityCommand(input: DescribeFleetCapacityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFleetEventsCommand(input: DescribeFleetEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFleetPortSettingsCommand(input: DescribeFleetPortSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeFleetUtilizationCommand(input: DescribeFleetUtilizationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGameSessionDetailsCommand(input: DescribeGameSessionDetailsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGameSessionPlacementCommand(input: DescribeGameSessionPlacementCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGameSessionQueuesCommand(input: DescribeGameSessionQueuesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGameSessionsCommand(input: DescribeGameSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstancesCommand(input: DescribeInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMatchmakingCommand(input: DescribeMatchmakingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMatchmakingConfigurationsCommand(input: DescribeMatchmakingConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMatchmakingRuleSetsCommand(input: DescribeMatchmakingRuleSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePlayerSessionsCommand(input: DescribePlayerSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeRuntimeConfigurationCommand(input: DescribeRuntimeConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeScalingPoliciesCommand(input: DescribeScalingPoliciesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeScriptCommand(input: DescribeScriptCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVpcPeeringAuthorizationsCommand(input: DescribeVpcPeeringAuthorizationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVpcPeeringConnectionsCommand(input: DescribeVpcPeeringConnectionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetGameSessionLogUrlCommand(input: GetGameSessionLogUrlCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceAccessCommand(input: GetInstanceAccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAliasesCommand(input: ListAliasesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListBuildsCommand(input: ListBuildsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListFleetsCommand(input: ListFleetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListScriptsCommand(input: ListScriptsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutScalingPolicyCommand(input: PutScalingPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RequestUploadCredentialsCommand(input: RequestUploadCredentialsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResolveAliasCommand(input: ResolveAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SearchGameSessionsCommand(input: SearchGameSessionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartFleetActionsCommand(input: StartFleetActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartGameSessionPlacementCommand(input: StartGameSessionPlacementCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartMatchBackfillCommand(input: StartMatchBackfillCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartMatchmakingCommand(input: StartMatchmakingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopFleetActionsCommand(input: StopFleetActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopGameSessionPlacementCommand(input: StopGameSessionPlacementCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopMatchmakingCommand(input: StopMatchmakingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAliasCommand(input: UpdateAliasCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateBuildCommand(input: UpdateBuildCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateFleetAttributesCommand(input: UpdateFleetAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateFleetCapacityCommand(input: UpdateFleetCapacityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateFleetPortSettingsCommand(input: UpdateFleetPortSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateGameSessionCommand(input: UpdateGameSessionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateGameSessionQueueCommand(input: UpdateGameSessionQueueCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMatchmakingConfigurationCommand(input: UpdateMatchmakingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRuntimeConfigurationCommand(input: UpdateRuntimeConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateScriptCommand(input: UpdateScriptCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ValidateMatchmakingRuleSetCommand(input: ValidateMatchmakingRuleSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AcceptMatchCommand(output: __HttpResponse, context: __SerdeContext): Promise<AcceptMatchCommandOutput>;
export declare function deserializeAws_json1_1CreateAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAliasCommandOutput>;
export declare function deserializeAws_json1_1CreateBuildCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBuildCommandOutput>;
export declare function deserializeAws_json1_1CreateFleetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateFleetCommandOutput>;
export declare function deserializeAws_json1_1CreateGameSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateGameSessionCommandOutput>;
export declare function deserializeAws_json1_1CreateGameSessionQueueCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateGameSessionQueueCommandOutput>;
export declare function deserializeAws_json1_1CreateMatchmakingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMatchmakingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1CreateMatchmakingRuleSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMatchmakingRuleSetCommandOutput>;
export declare function deserializeAws_json1_1CreatePlayerSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePlayerSessionCommandOutput>;
export declare function deserializeAws_json1_1CreatePlayerSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePlayerSessionsCommandOutput>;
export declare function deserializeAws_json1_1CreateScriptCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateScriptCommandOutput>;
export declare function deserializeAws_json1_1CreateVpcPeeringAuthorizationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVpcPeeringAuthorizationCommandOutput>;
export declare function deserializeAws_json1_1CreateVpcPeeringConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateVpcPeeringConnectionCommandOutput>;
export declare function deserializeAws_json1_1DeleteAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAliasCommandOutput>;
export declare function deserializeAws_json1_1DeleteBuildCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBuildCommandOutput>;
export declare function deserializeAws_json1_1DeleteFleetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFleetCommandOutput>;
export declare function deserializeAws_json1_1DeleteGameSessionQueueCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteGameSessionQueueCommandOutput>;
export declare function deserializeAws_json1_1DeleteMatchmakingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMatchmakingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeleteMatchmakingRuleSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMatchmakingRuleSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteScalingPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteScalingPolicyCommandOutput>;
export declare function deserializeAws_json1_1DeleteScriptCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteScriptCommandOutput>;
export declare function deserializeAws_json1_1DeleteVpcPeeringAuthorizationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVpcPeeringAuthorizationCommandOutput>;
export declare function deserializeAws_json1_1DeleteVpcPeeringConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVpcPeeringConnectionCommandOutput>;
export declare function deserializeAws_json1_1DescribeAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAliasCommandOutput>;
export declare function deserializeAws_json1_1DescribeBuildCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBuildCommandOutput>;
export declare function deserializeAws_json1_1DescribeEC2InstanceLimitsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEC2InstanceLimitsCommandOutput>;
export declare function deserializeAws_json1_1DescribeFleetAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFleetAttributesCommandOutput>;
export declare function deserializeAws_json1_1DescribeFleetCapacityCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFleetCapacityCommandOutput>;
export declare function deserializeAws_json1_1DescribeFleetEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFleetEventsCommandOutput>;
export declare function deserializeAws_json1_1DescribeFleetPortSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFleetPortSettingsCommandOutput>;
export declare function deserializeAws_json1_1DescribeFleetUtilizationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFleetUtilizationCommandOutput>;
export declare function deserializeAws_json1_1DescribeGameSessionDetailsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGameSessionDetailsCommandOutput>;
export declare function deserializeAws_json1_1DescribeGameSessionPlacementCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGameSessionPlacementCommandOutput>;
export declare function deserializeAws_json1_1DescribeGameSessionQueuesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGameSessionQueuesCommandOutput>;
export declare function deserializeAws_json1_1DescribeGameSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGameSessionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancesCommandOutput>;
export declare function deserializeAws_json1_1DescribeMatchmakingCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMatchmakingCommandOutput>;
export declare function deserializeAws_json1_1DescribeMatchmakingConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMatchmakingConfigurationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeMatchmakingRuleSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMatchmakingRuleSetsCommandOutput>;
export declare function deserializeAws_json1_1DescribePlayerSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePlayerSessionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeRuntimeConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeRuntimeConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DescribeScalingPoliciesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeScalingPoliciesCommandOutput>;
export declare function deserializeAws_json1_1DescribeScriptCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeScriptCommandOutput>;
export declare function deserializeAws_json1_1DescribeVpcPeeringAuthorizationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVpcPeeringAuthorizationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeVpcPeeringConnectionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVpcPeeringConnectionsCommandOutput>;
export declare function deserializeAws_json1_1GetGameSessionLogUrlCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetGameSessionLogUrlCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceAccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceAccessCommandOutput>;
export declare function deserializeAws_json1_1ListAliasesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAliasesCommandOutput>;
export declare function deserializeAws_json1_1ListBuildsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListBuildsCommandOutput>;
export declare function deserializeAws_json1_1ListFleetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFleetsCommandOutput>;
export declare function deserializeAws_json1_1ListScriptsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListScriptsCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1PutScalingPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutScalingPolicyCommandOutput>;
export declare function deserializeAws_json1_1RequestUploadCredentialsCommand(output: __HttpResponse, context: __SerdeContext): Promise<RequestUploadCredentialsCommandOutput>;
export declare function deserializeAws_json1_1ResolveAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResolveAliasCommandOutput>;
export declare function deserializeAws_json1_1SearchGameSessionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<SearchGameSessionsCommandOutput>;
export declare function deserializeAws_json1_1StartFleetActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartFleetActionsCommandOutput>;
export declare function deserializeAws_json1_1StartGameSessionPlacementCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartGameSessionPlacementCommandOutput>;
export declare function deserializeAws_json1_1StartMatchBackfillCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMatchBackfillCommandOutput>;
export declare function deserializeAws_json1_1StartMatchmakingCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMatchmakingCommandOutput>;
export declare function deserializeAws_json1_1StopFleetActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopFleetActionsCommandOutput>;
export declare function deserializeAws_json1_1StopGameSessionPlacementCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopGameSessionPlacementCommandOutput>;
export declare function deserializeAws_json1_1StopMatchmakingCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopMatchmakingCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateAliasCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAliasCommandOutput>;
export declare function deserializeAws_json1_1UpdateBuildCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateBuildCommandOutput>;
export declare function deserializeAws_json1_1UpdateFleetAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFleetAttributesCommandOutput>;
export declare function deserializeAws_json1_1UpdateFleetCapacityCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFleetCapacityCommandOutput>;
export declare function deserializeAws_json1_1UpdateFleetPortSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFleetPortSettingsCommandOutput>;
export declare function deserializeAws_json1_1UpdateGameSessionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateGameSessionCommandOutput>;
export declare function deserializeAws_json1_1UpdateGameSessionQueueCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateGameSessionQueueCommandOutput>;
export declare function deserializeAws_json1_1UpdateMatchmakingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMatchmakingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1UpdateRuntimeConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRuntimeConfigurationCommandOutput>;
export declare function deserializeAws_json1_1UpdateScriptCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateScriptCommandOutput>;
export declare function deserializeAws_json1_1ValidateMatchmakingRuleSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<ValidateMatchmakingRuleSetCommandOutput>;
