import { AssignInstanceCommandInput, AssignInstanceCommandOutput } from "../commands/AssignInstanceCommand";
import { AssignVolumeCommandInput, AssignVolumeCommandOutput } from "../commands/AssignVolumeCommand";
import { AssociateElasticIpCommandInput, AssociateElasticIpCommandOutput } from "../commands/AssociateElasticIpCommand";
import { AttachElasticLoadBalancerCommandInput, AttachElasticLoadBalancerCommandOutput } from "../commands/AttachElasticLoadBalancerCommand";
import { CloneStackCommandInput, CloneStackCommandOutput } from "../commands/CloneStackCommand";
import { CreateAppCommandInput, CreateAppCommandOutput } from "../commands/CreateAppCommand";
import { CreateDeploymentCommandInput, CreateDeploymentCommandOutput } from "../commands/CreateDeploymentCommand";
import { CreateInstanceCommandInput, CreateInstanceCommandOutput } from "../commands/CreateInstanceCommand";
import { CreateLayerCommandInput, CreateLayerCommandOutput } from "../commands/CreateLayerCommand";
import { CreateStackCommandInput, CreateStackCommandOutput } from "../commands/CreateStackCommand";
import { CreateUserProfileCommandInput, CreateUserProfileCommandOutput } from "../commands/CreateUserProfileCommand";
import { DeleteAppCommandInput, DeleteAppCommandOutput } from "../commands/DeleteAppCommand";
import { DeleteInstanceCommandInput, DeleteInstanceCommandOutput } from "../commands/DeleteInstanceCommand";
import { DeleteLayerCommandInput, DeleteLayerCommandOutput } from "../commands/DeleteLayerCommand";
import { DeleteStackCommandInput, DeleteStackCommandOutput } from "../commands/DeleteStackCommand";
import { DeleteUserProfileCommandInput, DeleteUserProfileCommandOutput } from "../commands/DeleteUserProfileCommand";
import { DeregisterEcsClusterCommandInput, DeregisterEcsClusterCommandOutput } from "../commands/DeregisterEcsClusterCommand";
import { DeregisterElasticIpCommandInput, DeregisterElasticIpCommandOutput } from "../commands/DeregisterElasticIpCommand";
import { DeregisterInstanceCommandInput, DeregisterInstanceCommandOutput } from "../commands/DeregisterInstanceCommand";
import { DeregisterRdsDbInstanceCommandInput, DeregisterRdsDbInstanceCommandOutput } from "../commands/DeregisterRdsDbInstanceCommand";
import { DeregisterVolumeCommandInput, DeregisterVolumeCommandOutput } from "../commands/DeregisterVolumeCommand";
import { DescribeAgentVersionsCommandInput, DescribeAgentVersionsCommandOutput } from "../commands/DescribeAgentVersionsCommand";
import { DescribeAppsCommandInput, DescribeAppsCommandOutput } from "../commands/DescribeAppsCommand";
import { DescribeCommandsCommandInput, DescribeCommandsCommandOutput } from "../commands/DescribeCommandsCommand";
import { DescribeDeploymentsCommandInput, DescribeDeploymentsCommandOutput } from "../commands/DescribeDeploymentsCommand";
import { DescribeEcsClustersCommandInput, DescribeEcsClustersCommandOutput } from "../commands/DescribeEcsClustersCommand";
import { DescribeElasticIpsCommandInput, DescribeElasticIpsCommandOutput } from "../commands/DescribeElasticIpsCommand";
import { DescribeElasticLoadBalancersCommandInput, DescribeElasticLoadBalancersCommandOutput } from "../commands/DescribeElasticLoadBalancersCommand";
import { DescribeInstancesCommandInput, DescribeInstancesCommandOutput } from "../commands/DescribeInstancesCommand";
import { DescribeLayersCommandInput, DescribeLayersCommandOutput } from "../commands/DescribeLayersCommand";
import { DescribeLoadBasedAutoScalingCommandInput, DescribeLoadBasedAutoScalingCommandOutput } from "../commands/DescribeLoadBasedAutoScalingCommand";
import { DescribeMyUserProfileCommandInput, DescribeMyUserProfileCommandOutput } from "../commands/DescribeMyUserProfileCommand";
import { DescribeOperatingSystemsCommandInput, DescribeOperatingSystemsCommandOutput } from "../commands/DescribeOperatingSystemsCommand";
import { DescribePermissionsCommandInput, DescribePermissionsCommandOutput } from "../commands/DescribePermissionsCommand";
import { DescribeRaidArraysCommandInput, DescribeRaidArraysCommandOutput } from "../commands/DescribeRaidArraysCommand";
import { DescribeRdsDbInstancesCommandInput, DescribeRdsDbInstancesCommandOutput } from "../commands/DescribeRdsDbInstancesCommand";
import { DescribeServiceErrorsCommandInput, DescribeServiceErrorsCommandOutput } from "../commands/DescribeServiceErrorsCommand";
import { DescribeStackProvisioningParametersCommandInput, DescribeStackProvisioningParametersCommandOutput } from "../commands/DescribeStackProvisioningParametersCommand";
import { DescribeStackSummaryCommandInput, DescribeStackSummaryCommandOutput } from "../commands/DescribeStackSummaryCommand";
import { DescribeStacksCommandInput, DescribeStacksCommandOutput } from "../commands/DescribeStacksCommand";
import { DescribeTimeBasedAutoScalingCommandInput, DescribeTimeBasedAutoScalingCommandOutput } from "../commands/DescribeTimeBasedAutoScalingCommand";
import { DescribeUserProfilesCommandInput, DescribeUserProfilesCommandOutput } from "../commands/DescribeUserProfilesCommand";
import { DescribeVolumesCommandInput, DescribeVolumesCommandOutput } from "../commands/DescribeVolumesCommand";
import { DetachElasticLoadBalancerCommandInput, DetachElasticLoadBalancerCommandOutput } from "../commands/DetachElasticLoadBalancerCommand";
import { DisassociateElasticIpCommandInput, DisassociateElasticIpCommandOutput } from "../commands/DisassociateElasticIpCommand";
import { GetHostnameSuggestionCommandInput, GetHostnameSuggestionCommandOutput } from "../commands/GetHostnameSuggestionCommand";
import { GrantAccessCommandInput, GrantAccessCommandOutput } from "../commands/GrantAccessCommand";
import { ListTagsCommandInput, ListTagsCommandOutput } from "../commands/ListTagsCommand";
import { RebootInstanceCommandInput, RebootInstanceCommandOutput } from "../commands/RebootInstanceCommand";
import { RegisterEcsClusterCommandInput, RegisterEcsClusterCommandOutput } from "../commands/RegisterEcsClusterCommand";
import { RegisterElasticIpCommandInput, RegisterElasticIpCommandOutput } from "../commands/RegisterElasticIpCommand";
import { RegisterInstanceCommandInput, RegisterInstanceCommandOutput } from "../commands/RegisterInstanceCommand";
import { RegisterRdsDbInstanceCommandInput, RegisterRdsDbInstanceCommandOutput } from "../commands/RegisterRdsDbInstanceCommand";
import { RegisterVolumeCommandInput, RegisterVolumeCommandOutput } from "../commands/RegisterVolumeCommand";
import { SetLoadBasedAutoScalingCommandInput, SetLoadBasedAutoScalingCommandOutput } from "../commands/SetLoadBasedAutoScalingCommand";
import { SetPermissionCommandInput, SetPermissionCommandOutput } from "../commands/SetPermissionCommand";
import { SetTimeBasedAutoScalingCommandInput, SetTimeBasedAutoScalingCommandOutput } from "../commands/SetTimeBasedAutoScalingCommand";
import { StartInstanceCommandInput, StartInstanceCommandOutput } from "../commands/StartInstanceCommand";
import { StartStackCommandInput, StartStackCommandOutput } from "../commands/StartStackCommand";
import { StopInstanceCommandInput, StopInstanceCommandOutput } from "../commands/StopInstanceCommand";
import { StopStackCommandInput, StopStackCommandOutput } from "../commands/StopStackCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UnassignInstanceCommandInput, UnassignInstanceCommandOutput } from "../commands/UnassignInstanceCommand";
import { UnassignVolumeCommandInput, UnassignVolumeCommandOutput } from "../commands/UnassignVolumeCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateAppCommandInput, UpdateAppCommandOutput } from "../commands/UpdateAppCommand";
import { UpdateElasticIpCommandInput, UpdateElasticIpCommandOutput } from "../commands/UpdateElasticIpCommand";
import { UpdateInstanceCommandInput, UpdateInstanceCommandOutput } from "../commands/UpdateInstanceCommand";
import { UpdateLayerCommandInput, UpdateLayerCommandOutput } from "../commands/UpdateLayerCommand";
import { UpdateMyUserProfileCommandInput, UpdateMyUserProfileCommandOutput } from "../commands/UpdateMyUserProfileCommand";
import { UpdateRdsDbInstanceCommandInput, UpdateRdsDbInstanceCommandOutput } from "../commands/UpdateRdsDbInstanceCommand";
import { UpdateStackCommandInput, UpdateStackCommandOutput } from "../commands/UpdateStackCommand";
import { UpdateUserProfileCommandInput, UpdateUserProfileCommandOutput } from "../commands/UpdateUserProfileCommand";
import { UpdateVolumeCommandInput, UpdateVolumeCommandOutput } from "../commands/UpdateVolumeCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssignInstanceCommand(input: AssignInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssignVolumeCommand(input: AssignVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateElasticIpCommand(input: AssociateElasticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachElasticLoadBalancerCommand(input: AttachElasticLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CloneStackCommand(input: CloneStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateAppCommand(input: CreateAppCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDeploymentCommand(input: CreateDeploymentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInstanceCommand(input: CreateInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateLayerCommand(input: CreateLayerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateStackCommand(input: CreateStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateUserProfileCommand(input: CreateUserProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAppCommand(input: DeleteAppCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInstanceCommand(input: DeleteInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLayerCommand(input: DeleteLayerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteStackCommand(input: DeleteStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteUserProfileCommand(input: DeleteUserProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterEcsClusterCommand(input: DeregisterEcsClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterElasticIpCommand(input: DeregisterElasticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterInstanceCommand(input: DeregisterInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterRdsDbInstanceCommand(input: DeregisterRdsDbInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterVolumeCommand(input: DeregisterVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAgentVersionsCommand(input: DescribeAgentVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAppsCommand(input: DescribeAppsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCommandsCommand(input: DescribeCommandsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDeploymentsCommand(input: DescribeDeploymentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEcsClustersCommand(input: DescribeEcsClustersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeElasticIpsCommand(input: DescribeElasticIpsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeElasticLoadBalancersCommand(input: DescribeElasticLoadBalancersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInstancesCommand(input: DescribeInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLayersCommand(input: DescribeLayersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLoadBasedAutoScalingCommand(input: DescribeLoadBasedAutoScalingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMyUserProfileCommand(input: DescribeMyUserProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeOperatingSystemsCommand(input: DescribeOperatingSystemsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePermissionsCommand(input: DescribePermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeRaidArraysCommand(input: DescribeRaidArraysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeRdsDbInstancesCommand(input: DescribeRdsDbInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeServiceErrorsCommand(input: DescribeServiceErrorsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeStackProvisioningParametersCommand(input: DescribeStackProvisioningParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeStackSummaryCommand(input: DescribeStackSummaryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeStacksCommand(input: DescribeStacksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTimeBasedAutoScalingCommand(input: DescribeTimeBasedAutoScalingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeUserProfilesCommand(input: DescribeUserProfilesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVolumesCommand(input: DescribeVolumesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DetachElasticLoadBalancerCommand(input: DetachElasticLoadBalancerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateElasticIpCommand(input: DisassociateElasticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetHostnameSuggestionCommand(input: GetHostnameSuggestionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GrantAccessCommand(input: GrantAccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsCommand(input: ListTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebootInstanceCommand(input: RebootInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterEcsClusterCommand(input: RegisterEcsClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterElasticIpCommand(input: RegisterElasticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterInstanceCommand(input: RegisterInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterRdsDbInstanceCommand(input: RegisterRdsDbInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterVolumeCommand(input: RegisterVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetLoadBasedAutoScalingCommand(input: SetLoadBasedAutoScalingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetPermissionCommand(input: SetPermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetTimeBasedAutoScalingCommand(input: SetTimeBasedAutoScalingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartInstanceCommand(input: StartInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartStackCommand(input: StartStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopInstanceCommand(input: StopInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopStackCommand(input: StopStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UnassignInstanceCommand(input: UnassignInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UnassignVolumeCommand(input: UnassignVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAppCommand(input: UpdateAppCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateElasticIpCommand(input: UpdateElasticIpCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateInstanceCommand(input: UpdateInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateLayerCommand(input: UpdateLayerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMyUserProfileCommand(input: UpdateMyUserProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRdsDbInstanceCommand(input: UpdateRdsDbInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateStackCommand(input: UpdateStackCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateUserProfileCommand(input: UpdateUserProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVolumeCommand(input: UpdateVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssignInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssignInstanceCommandOutput>;
export declare function deserializeAws_json1_1AssignVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssignVolumeCommandOutput>;
export declare function deserializeAws_json1_1AssociateElasticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateElasticIpCommandOutput>;
export declare function deserializeAws_json1_1AttachElasticLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachElasticLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1CloneStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<CloneStackCommandOutput>;
export declare function deserializeAws_json1_1CreateAppCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAppCommandOutput>;
export declare function deserializeAws_json1_1CreateDeploymentCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDeploymentCommandOutput>;
export declare function deserializeAws_json1_1CreateInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInstanceCommandOutput>;
export declare function deserializeAws_json1_1CreateLayerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateLayerCommandOutput>;
export declare function deserializeAws_json1_1CreateStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStackCommandOutput>;
export declare function deserializeAws_json1_1CreateUserProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateUserProfileCommandOutput>;
export declare function deserializeAws_json1_1DeleteAppCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAppCommandOutput>;
export declare function deserializeAws_json1_1DeleteInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInstanceCommandOutput>;
export declare function deserializeAws_json1_1DeleteLayerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLayerCommandOutput>;
export declare function deserializeAws_json1_1DeleteStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteStackCommandOutput>;
export declare function deserializeAws_json1_1DeleteUserProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteUserProfileCommandOutput>;
export declare function deserializeAws_json1_1DeregisterEcsClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterEcsClusterCommandOutput>;
export declare function deserializeAws_json1_1DeregisterElasticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterElasticIpCommandOutput>;
export declare function deserializeAws_json1_1DeregisterInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterInstanceCommandOutput>;
export declare function deserializeAws_json1_1DeregisterRdsDbInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterRdsDbInstanceCommandOutput>;
export declare function deserializeAws_json1_1DeregisterVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterVolumeCommandOutput>;
export declare function deserializeAws_json1_1DescribeAgentVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAgentVersionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeAppsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAppsCommandOutput>;
export declare function deserializeAws_json1_1DescribeCommandsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCommandsCommandOutput>;
export declare function deserializeAws_json1_1DescribeDeploymentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDeploymentsCommandOutput>;
export declare function deserializeAws_json1_1DescribeEcsClustersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEcsClustersCommandOutput>;
export declare function deserializeAws_json1_1DescribeElasticIpsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeElasticIpsCommandOutput>;
export declare function deserializeAws_json1_1DescribeElasticLoadBalancersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeElasticLoadBalancersCommandOutput>;
export declare function deserializeAws_json1_1DescribeInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancesCommandOutput>;
export declare function deserializeAws_json1_1DescribeLayersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLayersCommandOutput>;
export declare function deserializeAws_json1_1DescribeLoadBasedAutoScalingCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLoadBasedAutoScalingCommandOutput>;
export declare function deserializeAws_json1_1DescribeMyUserProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMyUserProfileCommandOutput>;
export declare function deserializeAws_json1_1DescribeOperatingSystemsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeOperatingSystemsCommandOutput>;
export declare function deserializeAws_json1_1DescribePermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePermissionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeRaidArraysCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeRaidArraysCommandOutput>;
export declare function deserializeAws_json1_1DescribeRdsDbInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeRdsDbInstancesCommandOutput>;
export declare function deserializeAws_json1_1DescribeServiceErrorsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeServiceErrorsCommandOutput>;
export declare function deserializeAws_json1_1DescribeStackProvisioningParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStackProvisioningParametersCommandOutput>;
export declare function deserializeAws_json1_1DescribeStackSummaryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStackSummaryCommandOutput>;
export declare function deserializeAws_json1_1DescribeStacksCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStacksCommandOutput>;
export declare function deserializeAws_json1_1DescribeTimeBasedAutoScalingCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTimeBasedAutoScalingCommandOutput>;
export declare function deserializeAws_json1_1DescribeUserProfilesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeUserProfilesCommandOutput>;
export declare function deserializeAws_json1_1DescribeVolumesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVolumesCommandOutput>;
export declare function deserializeAws_json1_1DetachElasticLoadBalancerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DetachElasticLoadBalancerCommandOutput>;
export declare function deserializeAws_json1_1DisassociateElasticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateElasticIpCommandOutput>;
export declare function deserializeAws_json1_1GetHostnameSuggestionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetHostnameSuggestionCommandOutput>;
export declare function deserializeAws_json1_1GrantAccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<GrantAccessCommandOutput>;
export declare function deserializeAws_json1_1ListTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsCommandOutput>;
export declare function deserializeAws_json1_1RebootInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootInstanceCommandOutput>;
export declare function deserializeAws_json1_1RegisterEcsClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterEcsClusterCommandOutput>;
export declare function deserializeAws_json1_1RegisterElasticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterElasticIpCommandOutput>;
export declare function deserializeAws_json1_1RegisterInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterInstanceCommandOutput>;
export declare function deserializeAws_json1_1RegisterRdsDbInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterRdsDbInstanceCommandOutput>;
export declare function deserializeAws_json1_1RegisterVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterVolumeCommandOutput>;
export declare function deserializeAws_json1_1SetLoadBasedAutoScalingCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetLoadBasedAutoScalingCommandOutput>;
export declare function deserializeAws_json1_1SetPermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetPermissionCommandOutput>;
export declare function deserializeAws_json1_1SetTimeBasedAutoScalingCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetTimeBasedAutoScalingCommandOutput>;
export declare function deserializeAws_json1_1StartInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartInstanceCommandOutput>;
export declare function deserializeAws_json1_1StartStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartStackCommandOutput>;
export declare function deserializeAws_json1_1StopInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopInstanceCommandOutput>;
export declare function deserializeAws_json1_1StopStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopStackCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UnassignInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UnassignInstanceCommandOutput>;
export declare function deserializeAws_json1_1UnassignVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UnassignVolumeCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateAppCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAppCommandOutput>;
export declare function deserializeAws_json1_1UpdateElasticIpCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateElasticIpCommandOutput>;
export declare function deserializeAws_json1_1UpdateInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateInstanceCommandOutput>;
export declare function deserializeAws_json1_1UpdateLayerCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateLayerCommandOutput>;
export declare function deserializeAws_json1_1UpdateMyUserProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMyUserProfileCommandOutput>;
export declare function deserializeAws_json1_1UpdateRdsDbInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRdsDbInstanceCommandOutput>;
export declare function deserializeAws_json1_1UpdateStackCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateStackCommandOutput>;
export declare function deserializeAws_json1_1UpdateUserProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateUserProfileCommandOutput>;
export declare function deserializeAws_json1_1UpdateVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVolumeCommandOutput>;
