import { AddTagsToResourceCommandInput, AddTagsToResourceCommandOutput } from "../commands/AddTagsToResourceCommand";
import { CreateHapgCommandInput, CreateHapgCommandOutput } from "../commands/CreateHapgCommand";
import { CreateHsmCommandInput, CreateHsmCommandOutput } from "../commands/CreateHsmCommand";
import { CreateLunaClientCommandInput, CreateLunaClientCommandOutput } from "../commands/CreateLunaClientCommand";
import { DeleteHapgCommandInput, DeleteHapgCommandOutput } from "../commands/DeleteHapgCommand";
import { DeleteHsmCommandInput, DeleteHsmCommandOutput } from "../commands/DeleteHsmCommand";
import { DeleteLunaClientCommandInput, DeleteLunaClientCommandOutput } from "../commands/DeleteLunaClientCommand";
import { DescribeHapgCommandInput, DescribeHapgCommandOutput } from "../commands/DescribeHapgCommand";
import { DescribeHsmCommandInput, DescribeHsmCommandOutput } from "../commands/DescribeHsmCommand";
import { DescribeLunaClientCommandInput, DescribeLunaClientCommandOutput } from "../commands/DescribeLunaClientCommand";
import { GetConfigCommandInput, GetConfigCommandOutput } from "../commands/GetConfigCommand";
import { ListAvailableZonesCommandInput, ListAvailableZonesCommandOutput } from "../commands/ListAvailableZonesCommand";
import { ListHapgsCommandInput, ListHapgsCommandOutput } from "../commands/ListHapgsCommand";
import { ListHsmsCommandInput, ListHsmsCommandOutput } from "../commands/ListHsmsCommand";
import { ListLunaClientsCommandInput, ListLunaClientsCommandOutput } from "../commands/ListLunaClientsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ModifyHapgCommandInput, ModifyHapgCommandOutput } from "../commands/ModifyHapgCommand";
import { ModifyHsmCommandInput, ModifyHsmCommandOutput } from "../commands/ModifyHsmCommand";
import { ModifyLunaClientCommandInput, ModifyLunaClientCommandOutput } from "../commands/ModifyLunaClientCommand";
import { RemoveTagsFromResourceCommandInput, RemoveTagsFromResourceCommandOutput } from "../commands/RemoveTagsFromResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddTagsToResourceCommand(input: AddTagsToResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateHapgCommand(input: CreateHapgCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateHsmCommand(input: CreateHsmCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateLunaClientCommand(input: CreateLunaClientCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteHapgCommand(input: DeleteHapgCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteHsmCommand(input: DeleteHsmCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLunaClientCommand(input: DeleteLunaClientCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeHapgCommand(input: DescribeHapgCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeHsmCommand(input: DescribeHsmCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLunaClientCommand(input: DescribeLunaClientCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetConfigCommand(input: GetConfigCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAvailableZonesCommand(input: ListAvailableZonesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListHapgsCommand(input: ListHapgsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListHsmsCommand(input: ListHsmsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListLunaClientsCommand(input: ListLunaClientsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyHapgCommand(input: ModifyHapgCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyHsmCommand(input: ModifyHsmCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyLunaClientCommand(input: ModifyLunaClientCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTagsFromResourceCommand(input: RemoveTagsFromResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddTagsToResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsToResourceCommandOutput>;
export declare function deserializeAws_json1_1CreateHapgCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHapgCommandOutput>;
export declare function deserializeAws_json1_1CreateHsmCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHsmCommandOutput>;
export declare function deserializeAws_json1_1CreateLunaClientCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateLunaClientCommandOutput>;
export declare function deserializeAws_json1_1DeleteHapgCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteHapgCommandOutput>;
export declare function deserializeAws_json1_1DeleteHsmCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteHsmCommandOutput>;
export declare function deserializeAws_json1_1DeleteLunaClientCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLunaClientCommandOutput>;
export declare function deserializeAws_json1_1DescribeHapgCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeHapgCommandOutput>;
export declare function deserializeAws_json1_1DescribeHsmCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeHsmCommandOutput>;
export declare function deserializeAws_json1_1DescribeLunaClientCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLunaClientCommandOutput>;
export declare function deserializeAws_json1_1GetConfigCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetConfigCommandOutput>;
export declare function deserializeAws_json1_1ListAvailableZonesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAvailableZonesCommandOutput>;
export declare function deserializeAws_json1_1ListHapgsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListHapgsCommandOutput>;
export declare function deserializeAws_json1_1ListHsmsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListHsmsCommandOutput>;
export declare function deserializeAws_json1_1ListLunaClientsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListLunaClientsCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ModifyHapgCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyHapgCommandOutput>;
export declare function deserializeAws_json1_1ModifyHsmCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyHsmCommandOutput>;
export declare function deserializeAws_json1_1ModifyLunaClientCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyLunaClientCommandOutput>;
export declare function deserializeAws_json1_1RemoveTagsFromResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsFromResourceCommandOutput>;
