import { CreateActivityCommandInput, CreateActivityCommandOutput } from "../commands/CreateActivityCommand";
import { CreateStateMachineCommandInput, CreateStateMachineCommandOutput } from "../commands/CreateStateMachineCommand";
import { DeleteActivityCommandInput, DeleteActivityCommandOutput } from "../commands/DeleteActivityCommand";
import { DeleteStateMachineCommandInput, DeleteStateMachineCommandOutput } from "../commands/DeleteStateMachineCommand";
import { DescribeActivityCommandInput, DescribeActivityCommandOutput } from "../commands/DescribeActivityCommand";
import { DescribeExecutionCommandInput, DescribeExecutionCommandOutput } from "../commands/DescribeExecutionCommand";
import { DescribeStateMachineCommandInput, DescribeStateMachineCommandOutput } from "../commands/DescribeStateMachineCommand";
import { DescribeStateMachineForExecutionCommandInput, DescribeStateMachineForExecutionCommandOutput } from "../commands/DescribeStateMachineForExecutionCommand";
import { GetActivityTaskCommandInput, GetActivityTaskCommandOutput } from "../commands/GetActivityTaskCommand";
import { GetExecutionHistoryCommandInput, GetExecutionHistoryCommandOutput } from "../commands/GetExecutionHistoryCommand";
import { ListActivitiesCommandInput, ListActivitiesCommandOutput } from "../commands/ListActivitiesCommand";
import { ListExecutionsCommandInput, ListExecutionsCommandOutput } from "../commands/ListExecutionsCommand";
import { ListStateMachinesCommandInput, ListStateMachinesCommandOutput } from "../commands/ListStateMachinesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { SendTaskFailureCommandInput, SendTaskFailureCommandOutput } from "../commands/SendTaskFailureCommand";
import { SendTaskHeartbeatCommandInput, SendTaskHeartbeatCommandOutput } from "../commands/SendTaskHeartbeatCommand";
import { SendTaskSuccessCommandInput, SendTaskSuccessCommandOutput } from "../commands/SendTaskSuccessCommand";
import { StartExecutionCommandInput, StartExecutionCommandOutput } from "../commands/StartExecutionCommand";
import { StopExecutionCommandInput, StopExecutionCommandOutput } from "../commands/StopExecutionCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateStateMachineCommandInput, UpdateStateMachineCommandOutput } from "../commands/UpdateStateMachineCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_0CreateActivityCommand(input: CreateActivityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0CreateStateMachineCommand(input: CreateStateMachineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DeleteActivityCommand(input: DeleteActivityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DeleteStateMachineCommand(input: DeleteStateMachineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeActivityCommand(input: DescribeActivityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeExecutionCommand(input: DescribeExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeStateMachineCommand(input: DescribeStateMachineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeStateMachineForExecutionCommand(input: DescribeStateMachineForExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0GetActivityTaskCommand(input: GetActivityTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0GetExecutionHistoryCommand(input: GetExecutionHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListActivitiesCommand(input: ListActivitiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListExecutionsCommand(input: ListExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListStateMachinesCommand(input: ListStateMachinesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0SendTaskFailureCommand(input: SendTaskFailureCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0SendTaskHeartbeatCommand(input: SendTaskHeartbeatCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0SendTaskSuccessCommand(input: SendTaskSuccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0StartExecutionCommand(input: StartExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0StopExecutionCommand(input: StopExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UpdateStateMachineCommand(input: UpdateStateMachineCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_0CreateActivityCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateActivityCommandOutput>;
export declare function deserializeAws_json1_0CreateStateMachineCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStateMachineCommandOutput>;
export declare function deserializeAws_json1_0DeleteActivityCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteActivityCommandOutput>;
export declare function deserializeAws_json1_0DeleteStateMachineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteStateMachineCommandOutput>;
export declare function deserializeAws_json1_0DescribeActivityCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeActivityCommandOutput>;
export declare function deserializeAws_json1_0DescribeExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeExecutionCommandOutput>;
export declare function deserializeAws_json1_0DescribeStateMachineCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStateMachineCommandOutput>;
export declare function deserializeAws_json1_0DescribeStateMachineForExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStateMachineForExecutionCommandOutput>;
export declare function deserializeAws_json1_0GetActivityTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetActivityTaskCommandOutput>;
export declare function deserializeAws_json1_0GetExecutionHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetExecutionHistoryCommandOutput>;
export declare function deserializeAws_json1_0ListActivitiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListActivitiesCommandOutput>;
export declare function deserializeAws_json1_0ListExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListExecutionsCommandOutput>;
export declare function deserializeAws_json1_0ListStateMachinesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListStateMachinesCommandOutput>;
export declare function deserializeAws_json1_0ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_0SendTaskFailureCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendTaskFailureCommandOutput>;
export declare function deserializeAws_json1_0SendTaskHeartbeatCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendTaskHeartbeatCommandOutput>;
export declare function deserializeAws_json1_0SendTaskSuccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<SendTaskSuccessCommandOutput>;
export declare function deserializeAws_json1_0StartExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartExecutionCommandOutput>;
export declare function deserializeAws_json1_0StopExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopExecutionCommandOutput>;
export declare function deserializeAws_json1_0TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_0UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_0UpdateStateMachineCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateStateMachineCommandOutput>;
