import { AcceptReservedNodeExchangeCommandInput, AcceptReservedNodeExchangeCommandOutput } from "../commands/AcceptReservedNodeExchangeCommand";
import { AuthorizeClusterSecurityGroupIngressCommandInput, AuthorizeClusterSecurityGroupIngressCommandOutput } from "../commands/AuthorizeClusterSecurityGroupIngressCommand";
import { AuthorizeSnapshotAccessCommandInput, AuthorizeSnapshotAccessCommandOutput } from "../commands/AuthorizeSnapshotAccessCommand";
import { BatchDeleteClusterSnapshotsCommandInput, BatchDeleteClusterSnapshotsCommandOutput } from "../commands/BatchDeleteClusterSnapshotsCommand";
import { BatchModifyClusterSnapshotsCommandInput, BatchModifyClusterSnapshotsCommandOutput } from "../commands/BatchModifyClusterSnapshotsCommand";
import { CancelResizeCommandInput, CancelResizeCommandOutput } from "../commands/CancelResizeCommand";
import { CopyClusterSnapshotCommandInput, CopyClusterSnapshotCommandOutput } from "../commands/CopyClusterSnapshotCommand";
import { CreateClusterCommandInput, CreateClusterCommandOutput } from "../commands/CreateClusterCommand";
import { CreateClusterParameterGroupCommandInput, CreateClusterParameterGroupCommandOutput } from "../commands/CreateClusterParameterGroupCommand";
import { CreateClusterSecurityGroupCommandInput, CreateClusterSecurityGroupCommandOutput } from "../commands/CreateClusterSecurityGroupCommand";
import { CreateClusterSnapshotCommandInput, CreateClusterSnapshotCommandOutput } from "../commands/CreateClusterSnapshotCommand";
import { CreateClusterSubnetGroupCommandInput, CreateClusterSubnetGroupCommandOutput } from "../commands/CreateClusterSubnetGroupCommand";
import { CreateEventSubscriptionCommandInput, CreateEventSubscriptionCommandOutput } from "../commands/CreateEventSubscriptionCommand";
import { CreateHsmClientCertificateCommandInput, CreateHsmClientCertificateCommandOutput } from "../commands/CreateHsmClientCertificateCommand";
import { CreateHsmConfigurationCommandInput, CreateHsmConfigurationCommandOutput } from "../commands/CreateHsmConfigurationCommand";
import { CreateScheduledActionCommandInput, CreateScheduledActionCommandOutput } from "../commands/CreateScheduledActionCommand";
import { CreateSnapshotCopyGrantCommandInput, CreateSnapshotCopyGrantCommandOutput } from "../commands/CreateSnapshotCopyGrantCommand";
import { CreateSnapshotScheduleCommandInput, CreateSnapshotScheduleCommandOutput } from "../commands/CreateSnapshotScheduleCommand";
import { CreateTagsCommandInput, CreateTagsCommandOutput } from "../commands/CreateTagsCommand";
import { DeleteClusterCommandInput, DeleteClusterCommandOutput } from "../commands/DeleteClusterCommand";
import { DeleteClusterParameterGroupCommandInput, DeleteClusterParameterGroupCommandOutput } from "../commands/DeleteClusterParameterGroupCommand";
import { DeleteClusterSecurityGroupCommandInput, DeleteClusterSecurityGroupCommandOutput } from "../commands/DeleteClusterSecurityGroupCommand";
import { DeleteClusterSnapshotCommandInput, DeleteClusterSnapshotCommandOutput } from "../commands/DeleteClusterSnapshotCommand";
import { DeleteClusterSubnetGroupCommandInput, DeleteClusterSubnetGroupCommandOutput } from "../commands/DeleteClusterSubnetGroupCommand";
import { DeleteEventSubscriptionCommandInput, DeleteEventSubscriptionCommandOutput } from "../commands/DeleteEventSubscriptionCommand";
import { DeleteHsmClientCertificateCommandInput, DeleteHsmClientCertificateCommandOutput } from "../commands/DeleteHsmClientCertificateCommand";
import { DeleteHsmConfigurationCommandInput, DeleteHsmConfigurationCommandOutput } from "../commands/DeleteHsmConfigurationCommand";
import { DeleteScheduledActionCommandInput, DeleteScheduledActionCommandOutput } from "../commands/DeleteScheduledActionCommand";
import { DeleteSnapshotCopyGrantCommandInput, DeleteSnapshotCopyGrantCommandOutput } from "../commands/DeleteSnapshotCopyGrantCommand";
import { DeleteSnapshotScheduleCommandInput, DeleteSnapshotScheduleCommandOutput } from "../commands/DeleteSnapshotScheduleCommand";
import { DeleteTagsCommandInput, DeleteTagsCommandOutput } from "../commands/DeleteTagsCommand";
import { DescribeAccountAttributesCommandInput, DescribeAccountAttributesCommandOutput } from "../commands/DescribeAccountAttributesCommand";
import { DescribeClusterDbRevisionsCommandInput, DescribeClusterDbRevisionsCommandOutput } from "../commands/DescribeClusterDbRevisionsCommand";
import { DescribeClusterParameterGroupsCommandInput, DescribeClusterParameterGroupsCommandOutput } from "../commands/DescribeClusterParameterGroupsCommand";
import { DescribeClusterParametersCommandInput, DescribeClusterParametersCommandOutput } from "../commands/DescribeClusterParametersCommand";
import { DescribeClusterSecurityGroupsCommandInput, DescribeClusterSecurityGroupsCommandOutput } from "../commands/DescribeClusterSecurityGroupsCommand";
import { DescribeClusterSnapshotsCommandInput, DescribeClusterSnapshotsCommandOutput } from "../commands/DescribeClusterSnapshotsCommand";
import { DescribeClusterSubnetGroupsCommandInput, DescribeClusterSubnetGroupsCommandOutput } from "../commands/DescribeClusterSubnetGroupsCommand";
import { DescribeClusterTracksCommandInput, DescribeClusterTracksCommandOutput } from "../commands/DescribeClusterTracksCommand";
import { DescribeClusterVersionsCommandInput, DescribeClusterVersionsCommandOutput } from "../commands/DescribeClusterVersionsCommand";
import { DescribeClustersCommandInput, DescribeClustersCommandOutput } from "../commands/DescribeClustersCommand";
import { DescribeDefaultClusterParametersCommandInput, DescribeDefaultClusterParametersCommandOutput } from "../commands/DescribeDefaultClusterParametersCommand";
import { DescribeEventCategoriesCommandInput, DescribeEventCategoriesCommandOutput } from "../commands/DescribeEventCategoriesCommand";
import { DescribeEventSubscriptionsCommandInput, DescribeEventSubscriptionsCommandOutput } from "../commands/DescribeEventSubscriptionsCommand";
import { DescribeEventsCommandInput, DescribeEventsCommandOutput } from "../commands/DescribeEventsCommand";
import { DescribeHsmClientCertificatesCommandInput, DescribeHsmClientCertificatesCommandOutput } from "../commands/DescribeHsmClientCertificatesCommand";
import { DescribeHsmConfigurationsCommandInput, DescribeHsmConfigurationsCommandOutput } from "../commands/DescribeHsmConfigurationsCommand";
import { DescribeLoggingStatusCommandInput, DescribeLoggingStatusCommandOutput } from "../commands/DescribeLoggingStatusCommand";
import { DescribeNodeConfigurationOptionsCommandInput, DescribeNodeConfigurationOptionsCommandOutput } from "../commands/DescribeNodeConfigurationOptionsCommand";
import { DescribeOrderableClusterOptionsCommandInput, DescribeOrderableClusterOptionsCommandOutput } from "../commands/DescribeOrderableClusterOptionsCommand";
import { DescribeReservedNodeOfferingsCommandInput, DescribeReservedNodeOfferingsCommandOutput } from "../commands/DescribeReservedNodeOfferingsCommand";
import { DescribeReservedNodesCommandInput, DescribeReservedNodesCommandOutput } from "../commands/DescribeReservedNodesCommand";
import { DescribeResizeCommandInput, DescribeResizeCommandOutput } from "../commands/DescribeResizeCommand";
import { DescribeScheduledActionsCommandInput, DescribeScheduledActionsCommandOutput } from "../commands/DescribeScheduledActionsCommand";
import { DescribeSnapshotCopyGrantsCommandInput, DescribeSnapshotCopyGrantsCommandOutput } from "../commands/DescribeSnapshotCopyGrantsCommand";
import { DescribeSnapshotSchedulesCommandInput, DescribeSnapshotSchedulesCommandOutput } from "../commands/DescribeSnapshotSchedulesCommand";
import { DescribeStorageCommandInput, DescribeStorageCommandOutput } from "../commands/DescribeStorageCommand";
import { DescribeTableRestoreStatusCommandInput, DescribeTableRestoreStatusCommandOutput } from "../commands/DescribeTableRestoreStatusCommand";
import { DescribeTagsCommandInput, DescribeTagsCommandOutput } from "../commands/DescribeTagsCommand";
import { DisableLoggingCommandInput, DisableLoggingCommandOutput } from "../commands/DisableLoggingCommand";
import { DisableSnapshotCopyCommandInput, DisableSnapshotCopyCommandOutput } from "../commands/DisableSnapshotCopyCommand";
import { EnableLoggingCommandInput, EnableLoggingCommandOutput } from "../commands/EnableLoggingCommand";
import { EnableSnapshotCopyCommandInput, EnableSnapshotCopyCommandOutput } from "../commands/EnableSnapshotCopyCommand";
import { GetClusterCredentialsCommandInput, GetClusterCredentialsCommandOutput } from "../commands/GetClusterCredentialsCommand";
import { GetReservedNodeExchangeOfferingsCommandInput, GetReservedNodeExchangeOfferingsCommandOutput } from "../commands/GetReservedNodeExchangeOfferingsCommand";
import { ModifyClusterCommandInput, ModifyClusterCommandOutput } from "../commands/ModifyClusterCommand";
import { ModifyClusterDbRevisionCommandInput, ModifyClusterDbRevisionCommandOutput } from "../commands/ModifyClusterDbRevisionCommand";
import { ModifyClusterIamRolesCommandInput, ModifyClusterIamRolesCommandOutput } from "../commands/ModifyClusterIamRolesCommand";
import { ModifyClusterMaintenanceCommandInput, ModifyClusterMaintenanceCommandOutput } from "../commands/ModifyClusterMaintenanceCommand";
import { ModifyClusterParameterGroupCommandInput, ModifyClusterParameterGroupCommandOutput } from "../commands/ModifyClusterParameterGroupCommand";
import { ModifyClusterSnapshotCommandInput, ModifyClusterSnapshotCommandOutput } from "../commands/ModifyClusterSnapshotCommand";
import { ModifyClusterSnapshotScheduleCommandInput, ModifyClusterSnapshotScheduleCommandOutput } from "../commands/ModifyClusterSnapshotScheduleCommand";
import { ModifyClusterSubnetGroupCommandInput, ModifyClusterSubnetGroupCommandOutput } from "../commands/ModifyClusterSubnetGroupCommand";
import { ModifyEventSubscriptionCommandInput, ModifyEventSubscriptionCommandOutput } from "../commands/ModifyEventSubscriptionCommand";
import { ModifyScheduledActionCommandInput, ModifyScheduledActionCommandOutput } from "../commands/ModifyScheduledActionCommand";
import { ModifySnapshotCopyRetentionPeriodCommandInput, ModifySnapshotCopyRetentionPeriodCommandOutput } from "../commands/ModifySnapshotCopyRetentionPeriodCommand";
import { ModifySnapshotScheduleCommandInput, ModifySnapshotScheduleCommandOutput } from "../commands/ModifySnapshotScheduleCommand";
import { PurchaseReservedNodeOfferingCommandInput, PurchaseReservedNodeOfferingCommandOutput } from "../commands/PurchaseReservedNodeOfferingCommand";
import { RebootClusterCommandInput, RebootClusterCommandOutput } from "../commands/RebootClusterCommand";
import { ResetClusterParameterGroupCommandInput, ResetClusterParameterGroupCommandOutput } from "../commands/ResetClusterParameterGroupCommand";
import { ResizeClusterCommandInput, ResizeClusterCommandOutput } from "../commands/ResizeClusterCommand";
import { RestoreFromClusterSnapshotCommandInput, RestoreFromClusterSnapshotCommandOutput } from "../commands/RestoreFromClusterSnapshotCommand";
import { RestoreTableFromClusterSnapshotCommandInput, RestoreTableFromClusterSnapshotCommandOutput } from "../commands/RestoreTableFromClusterSnapshotCommand";
import { RevokeClusterSecurityGroupIngressCommandInput, RevokeClusterSecurityGroupIngressCommandOutput } from "../commands/RevokeClusterSecurityGroupIngressCommand";
import { RevokeSnapshotAccessCommandInput, RevokeSnapshotAccessCommandOutput } from "../commands/RevokeSnapshotAccessCommand";
import { RotateEncryptionKeyCommandInput, RotateEncryptionKeyCommandOutput } from "../commands/RotateEncryptionKeyCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryAcceptReservedNodeExchangeCommand(input: AcceptReservedNodeExchangeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryAuthorizeClusterSecurityGroupIngressCommand(input: AuthorizeClusterSecurityGroupIngressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryAuthorizeSnapshotAccessCommand(input: AuthorizeSnapshotAccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryBatchDeleteClusterSnapshotsCommand(input: BatchDeleteClusterSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryBatchModifyClusterSnapshotsCommand(input: BatchModifyClusterSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCancelResizeCommand(input: CancelResizeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCopyClusterSnapshotCommand(input: CopyClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateClusterCommand(input: CreateClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateClusterParameterGroupCommand(input: CreateClusterParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateClusterSecurityGroupCommand(input: CreateClusterSecurityGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateClusterSnapshotCommand(input: CreateClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateClusterSubnetGroupCommand(input: CreateClusterSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateEventSubscriptionCommand(input: CreateEventSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateHsmClientCertificateCommand(input: CreateHsmClientCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateHsmConfigurationCommand(input: CreateHsmConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateScheduledActionCommand(input: CreateScheduledActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateSnapshotCopyGrantCommand(input: CreateSnapshotCopyGrantCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateSnapshotScheduleCommand(input: CreateSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateTagsCommand(input: CreateTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteClusterCommand(input: DeleteClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteClusterParameterGroupCommand(input: DeleteClusterParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteClusterSecurityGroupCommand(input: DeleteClusterSecurityGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteClusterSnapshotCommand(input: DeleteClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteClusterSubnetGroupCommand(input: DeleteClusterSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteEventSubscriptionCommand(input: DeleteEventSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteHsmClientCertificateCommand(input: DeleteHsmClientCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteHsmConfigurationCommand(input: DeleteHsmConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteScheduledActionCommand(input: DeleteScheduledActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteSnapshotCopyGrantCommand(input: DeleteSnapshotCopyGrantCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteSnapshotScheduleCommand(input: DeleteSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteTagsCommand(input: DeleteTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAccountAttributesCommand(input: DescribeAccountAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterDbRevisionsCommand(input: DescribeClusterDbRevisionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterParameterGroupsCommand(input: DescribeClusterParameterGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterParametersCommand(input: DescribeClusterParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterSecurityGroupsCommand(input: DescribeClusterSecurityGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterSnapshotsCommand(input: DescribeClusterSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterSubnetGroupsCommand(input: DescribeClusterSubnetGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterTracksCommand(input: DescribeClusterTracksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClusterVersionsCommand(input: DescribeClusterVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeClustersCommand(input: DescribeClustersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeDefaultClusterParametersCommand(input: DescribeDefaultClusterParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEventCategoriesCommand(input: DescribeEventCategoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEventSubscriptionsCommand(input: DescribeEventSubscriptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEventsCommand(input: DescribeEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeHsmClientCertificatesCommand(input: DescribeHsmClientCertificatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeHsmConfigurationsCommand(input: DescribeHsmConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeLoggingStatusCommand(input: DescribeLoggingStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeNodeConfigurationOptionsCommand(input: DescribeNodeConfigurationOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeOrderableClusterOptionsCommand(input: DescribeOrderableClusterOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeReservedNodeOfferingsCommand(input: DescribeReservedNodeOfferingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeReservedNodesCommand(input: DescribeReservedNodesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeResizeCommand(input: DescribeResizeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeScheduledActionsCommand(input: DescribeScheduledActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeSnapshotCopyGrantsCommand(input: DescribeSnapshotCopyGrantsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeSnapshotSchedulesCommand(input: DescribeSnapshotSchedulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeStorageCommand(input: DescribeStorageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeTableRestoreStatusCommand(input: DescribeTableRestoreStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeTagsCommand(input: DescribeTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDisableLoggingCommand(input: DisableLoggingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDisableSnapshotCopyCommand(input: DisableSnapshotCopyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryEnableLoggingCommand(input: EnableLoggingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryEnableSnapshotCopyCommand(input: EnableSnapshotCopyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetClusterCredentialsCommand(input: GetClusterCredentialsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetReservedNodeExchangeOfferingsCommand(input: GetReservedNodeExchangeOfferingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterCommand(input: ModifyClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterDbRevisionCommand(input: ModifyClusterDbRevisionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterIamRolesCommand(input: ModifyClusterIamRolesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterMaintenanceCommand(input: ModifyClusterMaintenanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterParameterGroupCommand(input: ModifyClusterParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterSnapshotCommand(input: ModifyClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterSnapshotScheduleCommand(input: ModifyClusterSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyClusterSubnetGroupCommand(input: ModifyClusterSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyEventSubscriptionCommand(input: ModifyEventSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyScheduledActionCommand(input: ModifyScheduledActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifySnapshotCopyRetentionPeriodCommand(input: ModifySnapshotCopyRetentionPeriodCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifySnapshotScheduleCommand(input: ModifySnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPurchaseReservedNodeOfferingCommand(input: PurchaseReservedNodeOfferingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRebootClusterCommand(input: RebootClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryResetClusterParameterGroupCommand(input: ResetClusterParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryResizeClusterCommand(input: ResizeClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRestoreFromClusterSnapshotCommand(input: RestoreFromClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRestoreTableFromClusterSnapshotCommand(input: RestoreTableFromClusterSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRevokeClusterSecurityGroupIngressCommand(input: RevokeClusterSecurityGroupIngressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRevokeSnapshotAccessCommand(input: RevokeSnapshotAccessCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRotateEncryptionKeyCommand(input: RotateEncryptionKeyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryAcceptReservedNodeExchangeCommand(output: __HttpResponse, context: __SerdeContext): Promise<AcceptReservedNodeExchangeCommandOutput>;
export declare function deserializeAws_queryAuthorizeClusterSecurityGroupIngressCommand(output: __HttpResponse, context: __SerdeContext): Promise<AuthorizeClusterSecurityGroupIngressCommandOutput>;
export declare function deserializeAws_queryAuthorizeSnapshotAccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<AuthorizeSnapshotAccessCommandOutput>;
export declare function deserializeAws_queryBatchDeleteClusterSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeleteClusterSnapshotsCommandOutput>;
export declare function deserializeAws_queryBatchModifyClusterSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchModifyClusterSnapshotsCommandOutput>;
export declare function deserializeAws_queryCancelResizeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelResizeCommandOutput>;
export declare function deserializeAws_queryCopyClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CopyClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryCreateClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterCommandOutput>;
export declare function deserializeAws_queryCreateClusterParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterParameterGroupCommandOutput>;
export declare function deserializeAws_queryCreateClusterSecurityGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterSecurityGroupCommandOutput>;
export declare function deserializeAws_queryCreateClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryCreateClusterSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterSubnetGroupCommandOutput>;
export declare function deserializeAws_queryCreateEventSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateEventSubscriptionCommandOutput>;
export declare function deserializeAws_queryCreateHsmClientCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHsmClientCertificateCommandOutput>;
export declare function deserializeAws_queryCreateHsmConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHsmConfigurationCommandOutput>;
export declare function deserializeAws_queryCreateScheduledActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateScheduledActionCommandOutput>;
export declare function deserializeAws_queryCreateSnapshotCopyGrantCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSnapshotCopyGrantCommandOutput>;
export declare function deserializeAws_queryCreateSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSnapshotScheduleCommandOutput>;
export declare function deserializeAws_queryCreateTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTagsCommandOutput>;
export declare function deserializeAws_queryDeleteClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterCommandOutput>;
export declare function deserializeAws_queryDeleteClusterParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterParameterGroupCommandOutput>;
export declare function deserializeAws_queryDeleteClusterSecurityGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterSecurityGroupCommandOutput>;
export declare function deserializeAws_queryDeleteClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryDeleteClusterSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterSubnetGroupCommandOutput>;
export declare function deserializeAws_queryDeleteEventSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEventSubscriptionCommandOutput>;
export declare function deserializeAws_queryDeleteHsmClientCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteHsmClientCertificateCommandOutput>;
export declare function deserializeAws_queryDeleteHsmConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteHsmConfigurationCommandOutput>;
export declare function deserializeAws_queryDeleteScheduledActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteScheduledActionCommandOutput>;
export declare function deserializeAws_queryDeleteSnapshotCopyGrantCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSnapshotCopyGrantCommandOutput>;
export declare function deserializeAws_queryDeleteSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSnapshotScheduleCommandOutput>;
export declare function deserializeAws_queryDeleteTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTagsCommandOutput>;
export declare function deserializeAws_queryDescribeAccountAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAccountAttributesCommandOutput>;
export declare function deserializeAws_queryDescribeClusterDbRevisionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterDbRevisionsCommandOutput>;
export declare function deserializeAws_queryDescribeClusterParameterGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterParameterGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeClusterParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterParametersCommandOutput>;
export declare function deserializeAws_queryDescribeClusterSecurityGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterSecurityGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeClusterSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterSnapshotsCommandOutput>;
export declare function deserializeAws_queryDescribeClusterSubnetGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterSubnetGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeClusterTracksCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterTracksCommandOutput>;
export declare function deserializeAws_queryDescribeClusterVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClusterVersionsCommandOutput>;
export declare function deserializeAws_queryDescribeClustersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClustersCommandOutput>;
export declare function deserializeAws_queryDescribeDefaultClusterParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDefaultClusterParametersCommandOutput>;
export declare function deserializeAws_queryDescribeEventCategoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventCategoriesCommandOutput>;
export declare function deserializeAws_queryDescribeEventSubscriptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventSubscriptionsCommandOutput>;
export declare function deserializeAws_queryDescribeEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventsCommandOutput>;
export declare function deserializeAws_queryDescribeHsmClientCertificatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeHsmClientCertificatesCommandOutput>;
export declare function deserializeAws_queryDescribeHsmConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeHsmConfigurationsCommandOutput>;
export declare function deserializeAws_queryDescribeLoggingStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLoggingStatusCommandOutput>;
export declare function deserializeAws_queryDescribeNodeConfigurationOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeNodeConfigurationOptionsCommandOutput>;
export declare function deserializeAws_queryDescribeOrderableClusterOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeOrderableClusterOptionsCommandOutput>;
export declare function deserializeAws_queryDescribeReservedNodeOfferingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReservedNodeOfferingsCommandOutput>;
export declare function deserializeAws_queryDescribeReservedNodesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReservedNodesCommandOutput>;
export declare function deserializeAws_queryDescribeResizeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeResizeCommandOutput>;
export declare function deserializeAws_queryDescribeScheduledActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeScheduledActionsCommandOutput>;
export declare function deserializeAws_queryDescribeSnapshotCopyGrantsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSnapshotCopyGrantsCommandOutput>;
export declare function deserializeAws_queryDescribeSnapshotSchedulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSnapshotSchedulesCommandOutput>;
export declare function deserializeAws_queryDescribeStorageCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStorageCommandOutput>;
export declare function deserializeAws_queryDescribeTableRestoreStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTableRestoreStatusCommandOutput>;
export declare function deserializeAws_queryDescribeTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTagsCommandOutput>;
export declare function deserializeAws_queryDisableLoggingCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableLoggingCommandOutput>;
export declare function deserializeAws_queryDisableSnapshotCopyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableSnapshotCopyCommandOutput>;
export declare function deserializeAws_queryEnableLoggingCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableLoggingCommandOutput>;
export declare function deserializeAws_queryEnableSnapshotCopyCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableSnapshotCopyCommandOutput>;
export declare function deserializeAws_queryGetClusterCredentialsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetClusterCredentialsCommandOutput>;
export declare function deserializeAws_queryGetReservedNodeExchangeOfferingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetReservedNodeExchangeOfferingsCommandOutput>;
export declare function deserializeAws_queryModifyClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterCommandOutput>;
export declare function deserializeAws_queryModifyClusterDbRevisionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterDbRevisionCommandOutput>;
export declare function deserializeAws_queryModifyClusterIamRolesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterIamRolesCommandOutput>;
export declare function deserializeAws_queryModifyClusterMaintenanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterMaintenanceCommandOutput>;
export declare function deserializeAws_queryModifyClusterParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterParameterGroupCommandOutput>;
export declare function deserializeAws_queryModifyClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryModifyClusterSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterSnapshotScheduleCommandOutput>;
export declare function deserializeAws_queryModifyClusterSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClusterSubnetGroupCommandOutput>;
export declare function deserializeAws_queryModifyEventSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyEventSubscriptionCommandOutput>;
export declare function deserializeAws_queryModifyScheduledActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyScheduledActionCommandOutput>;
export declare function deserializeAws_queryModifySnapshotCopyRetentionPeriodCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifySnapshotCopyRetentionPeriodCommandOutput>;
export declare function deserializeAws_queryModifySnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifySnapshotScheduleCommandOutput>;
export declare function deserializeAws_queryPurchaseReservedNodeOfferingCommand(output: __HttpResponse, context: __SerdeContext): Promise<PurchaseReservedNodeOfferingCommandOutput>;
export declare function deserializeAws_queryRebootClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootClusterCommandOutput>;
export declare function deserializeAws_queryResetClusterParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetClusterParameterGroupCommandOutput>;
export declare function deserializeAws_queryResizeClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResizeClusterCommandOutput>;
export declare function deserializeAws_queryRestoreFromClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<RestoreFromClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryRestoreTableFromClusterSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<RestoreTableFromClusterSnapshotCommandOutput>;
export declare function deserializeAws_queryRevokeClusterSecurityGroupIngressCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokeClusterSecurityGroupIngressCommandOutput>;
export declare function deserializeAws_queryRevokeSnapshotAccessCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokeSnapshotAccessCommandOutput>;
export declare function deserializeAws_queryRotateEncryptionKeyCommand(output: __HttpResponse, context: __SerdeContext): Promise<RotateEncryptionKeyCommandOutput>;
