import { AcceptInvitationCommandInput, AcceptInvitationCommandOutput } from "../commands/AcceptInvitationCommand";
import { CreateGraphCommandInput, CreateGraphCommandOutput } from "../commands/CreateGraphCommand";
import { CreateMembersCommandInput, CreateMembersCommandOutput } from "../commands/CreateMembersCommand";
import { DeleteGraphCommandInput, DeleteGraphCommandOutput } from "../commands/DeleteGraphCommand";
import { DeleteMembersCommandInput, DeleteMembersCommandOutput } from "../commands/DeleteMembersCommand";
import { DisassociateMembershipCommandInput, DisassociateMembershipCommandOutput } from "../commands/DisassociateMembershipCommand";
import { GetMembersCommandInput, GetMembersCommandOutput } from "../commands/GetMembersCommand";
import { ListGraphsCommandInput, ListGraphsCommandOutput } from "../commands/ListGraphsCommand";
import { ListInvitationsCommandInput, ListInvitationsCommandOutput } from "../commands/ListInvitationsCommand";
import { ListMembersCommandInput, ListMembersCommandOutput } from "../commands/ListMembersCommand";
import { RejectInvitationCommandInput, RejectInvitationCommandOutput } from "../commands/RejectInvitationCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restJson1_1AcceptInvitationCommand(input: AcceptInvitationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateGraphCommand(input: CreateGraphCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateMembersCommand(input: CreateMembersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteGraphCommand(input: DeleteGraphCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteMembersCommand(input: DeleteMembersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DisassociateMembershipCommand(input: DisassociateMembershipCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1GetMembersCommand(input: GetMembersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListGraphsCommand(input: ListGraphsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListInvitationsCommand(input: ListInvitationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListMembersCommand(input: ListMembersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1RejectInvitationCommand(input: RejectInvitationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restJson1_1AcceptInvitationCommand(output: __HttpResponse, context: __SerdeContext): Promise<AcceptInvitationCommandOutput>;
export declare function deserializeAws_restJson1_1CreateGraphCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateGraphCommandOutput>;
export declare function deserializeAws_restJson1_1CreateMembersCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMembersCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteGraphCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteGraphCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteMembersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMembersCommandOutput>;
export declare function deserializeAws_restJson1_1DisassociateMembershipCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateMembershipCommandOutput>;
export declare function deserializeAws_restJson1_1GetMembersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMembersCommandOutput>;
export declare function deserializeAws_restJson1_1ListGraphsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListGraphsCommandOutput>;
export declare function deserializeAws_restJson1_1ListInvitationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListInvitationsCommandOutput>;
export declare function deserializeAws_restJson1_1ListMembersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListMembersCommandOutput>;
export declare function deserializeAws_restJson1_1RejectInvitationCommand(output: __HttpResponse, context: __SerdeContext): Promise<RejectInvitationCommandOutput>;
