import { AbortEnvironmentUpdateCommandInput, AbortEnvironmentUpdateCommandOutput } from "../commands/AbortEnvironmentUpdateCommand";
import { ApplyEnvironmentManagedActionCommandInput, ApplyEnvironmentManagedActionCommandOutput } from "../commands/ApplyEnvironmentManagedActionCommand";
import { CheckDNSAvailabilityCommandInput, CheckDNSAvailabilityCommandOutput } from "../commands/CheckDNSAvailabilityCommand";
import { ComposeEnvironmentsCommandInput, ComposeEnvironmentsCommandOutput } from "../commands/ComposeEnvironmentsCommand";
import { CreateApplicationCommandInput, CreateApplicationCommandOutput } from "../commands/CreateApplicationCommand";
import { CreateApplicationVersionCommandInput, CreateApplicationVersionCommandOutput } from "../commands/CreateApplicationVersionCommand";
import { CreateConfigurationTemplateCommandInput, CreateConfigurationTemplateCommandOutput } from "../commands/CreateConfigurationTemplateCommand";
import { CreateEnvironmentCommandInput, CreateEnvironmentCommandOutput } from "../commands/CreateEnvironmentCommand";
import { CreatePlatformVersionCommandInput, CreatePlatformVersionCommandOutput } from "../commands/CreatePlatformVersionCommand";
import { CreateStorageLocationCommandInput, CreateStorageLocationCommandOutput } from "../commands/CreateStorageLocationCommand";
import { DeleteApplicationCommandInput, DeleteApplicationCommandOutput } from "../commands/DeleteApplicationCommand";
import { DeleteApplicationVersionCommandInput, DeleteApplicationVersionCommandOutput } from "../commands/DeleteApplicationVersionCommand";
import { DeleteConfigurationTemplateCommandInput, DeleteConfigurationTemplateCommandOutput } from "../commands/DeleteConfigurationTemplateCommand";
import { DeleteEnvironmentConfigurationCommandInput, DeleteEnvironmentConfigurationCommandOutput } from "../commands/DeleteEnvironmentConfigurationCommand";
import { DeletePlatformVersionCommandInput, DeletePlatformVersionCommandOutput } from "../commands/DeletePlatformVersionCommand";
import { DescribeAccountAttributesCommandInput, DescribeAccountAttributesCommandOutput } from "../commands/DescribeAccountAttributesCommand";
import { DescribeApplicationVersionsCommandInput, DescribeApplicationVersionsCommandOutput } from "../commands/DescribeApplicationVersionsCommand";
import { DescribeApplicationsCommandInput, DescribeApplicationsCommandOutput } from "../commands/DescribeApplicationsCommand";
import { DescribeConfigurationOptionsCommandInput, DescribeConfigurationOptionsCommandOutput } from "../commands/DescribeConfigurationOptionsCommand";
import { DescribeConfigurationSettingsCommandInput, DescribeConfigurationSettingsCommandOutput } from "../commands/DescribeConfigurationSettingsCommand";
import { DescribeEnvironmentHealthCommandInput, DescribeEnvironmentHealthCommandOutput } from "../commands/DescribeEnvironmentHealthCommand";
import { DescribeEnvironmentManagedActionHistoryCommandInput, DescribeEnvironmentManagedActionHistoryCommandOutput } from "../commands/DescribeEnvironmentManagedActionHistoryCommand";
import { DescribeEnvironmentManagedActionsCommandInput, DescribeEnvironmentManagedActionsCommandOutput } from "../commands/DescribeEnvironmentManagedActionsCommand";
import { DescribeEnvironmentResourcesCommandInput, DescribeEnvironmentResourcesCommandOutput } from "../commands/DescribeEnvironmentResourcesCommand";
import { DescribeEnvironmentsCommandInput, DescribeEnvironmentsCommandOutput } from "../commands/DescribeEnvironmentsCommand";
import { DescribeEventsCommandInput, DescribeEventsCommandOutput } from "../commands/DescribeEventsCommand";
import { DescribeInstancesHealthCommandInput, DescribeInstancesHealthCommandOutput } from "../commands/DescribeInstancesHealthCommand";
import { DescribePlatformVersionCommandInput, DescribePlatformVersionCommandOutput } from "../commands/DescribePlatformVersionCommand";
import { ListAvailableSolutionStacksCommandInput, ListAvailableSolutionStacksCommandOutput } from "../commands/ListAvailableSolutionStacksCommand";
import { ListPlatformVersionsCommandInput, ListPlatformVersionsCommandOutput } from "../commands/ListPlatformVersionsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { RebuildEnvironmentCommandInput, RebuildEnvironmentCommandOutput } from "../commands/RebuildEnvironmentCommand";
import { RequestEnvironmentInfoCommandInput, RequestEnvironmentInfoCommandOutput } from "../commands/RequestEnvironmentInfoCommand";
import { RestartAppServerCommandInput, RestartAppServerCommandOutput } from "../commands/RestartAppServerCommand";
import { RetrieveEnvironmentInfoCommandInput, RetrieveEnvironmentInfoCommandOutput } from "../commands/RetrieveEnvironmentInfoCommand";
import { SwapEnvironmentCNAMEsCommandInput, SwapEnvironmentCNAMEsCommandOutput } from "../commands/SwapEnvironmentCNAMEsCommand";
import { TerminateEnvironmentCommandInput, TerminateEnvironmentCommandOutput } from "../commands/TerminateEnvironmentCommand";
import { UpdateApplicationCommandInput, UpdateApplicationCommandOutput } from "../commands/UpdateApplicationCommand";
import { UpdateApplicationResourceLifecycleCommandInput, UpdateApplicationResourceLifecycleCommandOutput } from "../commands/UpdateApplicationResourceLifecycleCommand";
import { UpdateApplicationVersionCommandInput, UpdateApplicationVersionCommandOutput } from "../commands/UpdateApplicationVersionCommand";
import { UpdateConfigurationTemplateCommandInput, UpdateConfigurationTemplateCommandOutput } from "../commands/UpdateConfigurationTemplateCommand";
import { UpdateEnvironmentCommandInput, UpdateEnvironmentCommandOutput } from "../commands/UpdateEnvironmentCommand";
import { UpdateTagsForResourceCommandInput, UpdateTagsForResourceCommandOutput } from "../commands/UpdateTagsForResourceCommand";
import { ValidateConfigurationSettingsCommandInput, ValidateConfigurationSettingsCommandOutput } from "../commands/ValidateConfigurationSettingsCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryAbortEnvironmentUpdateCommand(input: AbortEnvironmentUpdateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryApplyEnvironmentManagedActionCommand(input: ApplyEnvironmentManagedActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCheckDNSAvailabilityCommand(input: CheckDNSAvailabilityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryComposeEnvironmentsCommand(input: ComposeEnvironmentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateApplicationCommand(input: CreateApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateApplicationVersionCommand(input: CreateApplicationVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateConfigurationTemplateCommand(input: CreateConfigurationTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateEnvironmentCommand(input: CreateEnvironmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreatePlatformVersionCommand(input: CreatePlatformVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateStorageLocationCommand(input: CreateStorageLocationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteApplicationCommand(input: DeleteApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteApplicationVersionCommand(input: DeleteApplicationVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteConfigurationTemplateCommand(input: DeleteConfigurationTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteEnvironmentConfigurationCommand(input: DeleteEnvironmentConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeletePlatformVersionCommand(input: DeletePlatformVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAccountAttributesCommand(input: DescribeAccountAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeApplicationVersionsCommand(input: DescribeApplicationVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeApplicationsCommand(input: DescribeApplicationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeConfigurationOptionsCommand(input: DescribeConfigurationOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeConfigurationSettingsCommand(input: DescribeConfigurationSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEnvironmentHealthCommand(input: DescribeEnvironmentHealthCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEnvironmentManagedActionHistoryCommand(input: DescribeEnvironmentManagedActionHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEnvironmentManagedActionsCommand(input: DescribeEnvironmentManagedActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEnvironmentResourcesCommand(input: DescribeEnvironmentResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEnvironmentsCommand(input: DescribeEnvironmentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEventsCommand(input: DescribeEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeInstancesHealthCommand(input: DescribeInstancesHealthCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribePlatformVersionCommand(input: DescribePlatformVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListAvailableSolutionStacksCommand(input: ListAvailableSolutionStacksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListPlatformVersionsCommand(input: ListPlatformVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRebuildEnvironmentCommand(input: RebuildEnvironmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRequestEnvironmentInfoCommand(input: RequestEnvironmentInfoCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRestartAppServerCommand(input: RestartAppServerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRetrieveEnvironmentInfoCommand(input: RetrieveEnvironmentInfoCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySwapEnvironmentCNAMEsCommand(input: SwapEnvironmentCNAMEsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryTerminateEnvironmentCommand(input: TerminateEnvironmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateApplicationCommand(input: UpdateApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateApplicationResourceLifecycleCommand(input: UpdateApplicationResourceLifecycleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateApplicationVersionCommand(input: UpdateApplicationVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateConfigurationTemplateCommand(input: UpdateConfigurationTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateEnvironmentCommand(input: UpdateEnvironmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUpdateTagsForResourceCommand(input: UpdateTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryValidateConfigurationSettingsCommand(input: ValidateConfigurationSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryAbortEnvironmentUpdateCommand(output: __HttpResponse, context: __SerdeContext): Promise<AbortEnvironmentUpdateCommandOutput>;
export declare function deserializeAws_queryApplyEnvironmentManagedActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ApplyEnvironmentManagedActionCommandOutput>;
export declare function deserializeAws_queryCheckDNSAvailabilityCommand(output: __HttpResponse, context: __SerdeContext): Promise<CheckDNSAvailabilityCommandOutput>;
export declare function deserializeAws_queryComposeEnvironmentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ComposeEnvironmentsCommandOutput>;
export declare function deserializeAws_queryCreateApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateApplicationCommandOutput>;
export declare function deserializeAws_queryCreateApplicationVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateApplicationVersionCommandOutput>;
export declare function deserializeAws_queryCreateConfigurationTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateConfigurationTemplateCommandOutput>;
export declare function deserializeAws_queryCreateEnvironmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateEnvironmentCommandOutput>;
export declare function deserializeAws_queryCreatePlatformVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePlatformVersionCommandOutput>;
export declare function deserializeAws_queryCreateStorageLocationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStorageLocationCommandOutput>;
export declare function deserializeAws_queryDeleteApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationCommandOutput>;
export declare function deserializeAws_queryDeleteApplicationVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApplicationVersionCommandOutput>;
export declare function deserializeAws_queryDeleteConfigurationTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteConfigurationTemplateCommandOutput>;
export declare function deserializeAws_queryDeleteEnvironmentConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEnvironmentConfigurationCommandOutput>;
export declare function deserializeAws_queryDeletePlatformVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePlatformVersionCommandOutput>;
export declare function deserializeAws_queryDescribeAccountAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAccountAttributesCommandOutput>;
export declare function deserializeAws_queryDescribeApplicationVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeApplicationVersionsCommandOutput>;
export declare function deserializeAws_queryDescribeApplicationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeApplicationsCommandOutput>;
export declare function deserializeAws_queryDescribeConfigurationOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeConfigurationOptionsCommandOutput>;
export declare function deserializeAws_queryDescribeConfigurationSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeConfigurationSettingsCommandOutput>;
export declare function deserializeAws_queryDescribeEnvironmentHealthCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEnvironmentHealthCommandOutput>;
export declare function deserializeAws_queryDescribeEnvironmentManagedActionHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEnvironmentManagedActionHistoryCommandOutput>;
export declare function deserializeAws_queryDescribeEnvironmentManagedActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEnvironmentManagedActionsCommandOutput>;
export declare function deserializeAws_queryDescribeEnvironmentResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEnvironmentResourcesCommandOutput>;
export declare function deserializeAws_queryDescribeEnvironmentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEnvironmentsCommandOutput>;
export declare function deserializeAws_queryDescribeEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventsCommandOutput>;
export declare function deserializeAws_queryDescribeInstancesHealthCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInstancesHealthCommandOutput>;
export declare function deserializeAws_queryDescribePlatformVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePlatformVersionCommandOutput>;
export declare function deserializeAws_queryListAvailableSolutionStacksCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAvailableSolutionStacksCommandOutput>;
export declare function deserializeAws_queryListPlatformVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPlatformVersionsCommandOutput>;
export declare function deserializeAws_queryListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_queryRebuildEnvironmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebuildEnvironmentCommandOutput>;
export declare function deserializeAws_queryRequestEnvironmentInfoCommand(output: __HttpResponse, context: __SerdeContext): Promise<RequestEnvironmentInfoCommandOutput>;
export declare function deserializeAws_queryRestartAppServerCommand(output: __HttpResponse, context: __SerdeContext): Promise<RestartAppServerCommandOutput>;
export declare function deserializeAws_queryRetrieveEnvironmentInfoCommand(output: __HttpResponse, context: __SerdeContext): Promise<RetrieveEnvironmentInfoCommandOutput>;
export declare function deserializeAws_querySwapEnvironmentCNAMEsCommand(output: __HttpResponse, context: __SerdeContext): Promise<SwapEnvironmentCNAMEsCommandOutput>;
export declare function deserializeAws_queryTerminateEnvironmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<TerminateEnvironmentCommandOutput>;
export declare function deserializeAws_queryUpdateApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApplicationCommandOutput>;
export declare function deserializeAws_queryUpdateApplicationResourceLifecycleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApplicationResourceLifecycleCommandOutput>;
export declare function deserializeAws_queryUpdateApplicationVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApplicationVersionCommandOutput>;
export declare function deserializeAws_queryUpdateConfigurationTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateConfigurationTemplateCommandOutput>;
export declare function deserializeAws_queryUpdateEnvironmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateEnvironmentCommandOutput>;
export declare function deserializeAws_queryUpdateTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateTagsForResourceCommandOutput>;
export declare function deserializeAws_queryValidateConfigurationSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ValidateConfigurationSettingsCommandOutput>;
