import { DBInstanceAutomatedBackupNotFoundFault } from "./DBInstanceAutomatedBackupNotFoundFault";
export type DescribeDBInstanceAutomatedBackupsExceptionsUnion = DBInstanceAutomatedBackupNotFoundFault;
