// smithy-typescript generated code
export type {
  UxcClient,
  Uxc,
  GetAccountCustomizationsCommand,
  GetAccountCustomizationsCommandInput,
  GetAccountCustomizationsCommandOutput,
  ListServicesCommand,
  ListServicesCommandInput,
  ListServicesCommandOutput,
  UpdateAccountCustomizationsCommand,
  UpdateAccountCustomizationsCommandInput,
  UpdateAccountCustomizationsCommandOutput,
  AccountColor,
  GetAccountCustomizationsInput,
  GetAccountCustomizationsOutput,
  ListServicesInput,
  ListServicesOutput,
  UpdateAccountCustomizationsInput,
  UpdateAccountCustomizationsOutput,
  ValidationExceptionField,
  AccessDeniedException,
  InternalServerException,
  ThrottlingException,
  ValidationException,
  UxcServiceException,
  paginateListServices,
} from "../dist-types/index.d";
