import { CustomVerificationEmailTemplateDoesNotExistException } from "./CustomVerificationEmailTemplateDoesNotExistException";
export type GetCustomVerificationEmailTemplateExceptionsUnion = CustomVerificationEmailTemplateDoesNotExistException;
