import { ConfigurationSetDoesNotExistException } from "./ConfigurationSetDoesNotExistException";
export type UpdateConfigurationSetReputationMetricsEnabledExceptionsUnion = ConfigurationSetDoesNotExistException;
