import { ConfigurationSetDoesNotExistException } from "./ConfigurationSetDoesNotExistException";
export type UpdateConfigurationSetSendingEnabledExceptionsUnion = ConfigurationSetDoesNotExistException;
