import { AssociateIpGroupsCommandInput, AssociateIpGroupsCommandOutput } from "../commands/AssociateIpGroupsCommand";
import { AuthorizeIpRulesCommandInput, AuthorizeIpRulesCommandOutput } from "../commands/AuthorizeIpRulesCommand";
import { CopyWorkspaceImageCommandInput, CopyWorkspaceImageCommandOutput } from "../commands/CopyWorkspaceImageCommand";
import { CreateIpGroupCommandInput, CreateIpGroupCommandOutput } from "../commands/CreateIpGroupCommand";
import { CreateTagsCommandInput, CreateTagsCommandOutput } from "../commands/CreateTagsCommand";
import { CreateWorkspacesCommandInput, CreateWorkspacesCommandOutput } from "../commands/CreateWorkspacesCommand";
import { DeleteIpGroupCommandInput, DeleteIpGroupCommandOutput } from "../commands/DeleteIpGroupCommand";
import { DeleteTagsCommandInput, DeleteTagsCommandOutput } from "../commands/DeleteTagsCommand";
import { DeleteWorkspaceImageCommandInput, DeleteWorkspaceImageCommandOutput } from "../commands/DeleteWorkspaceImageCommand";
import { DeregisterWorkspaceDirectoryCommandInput, DeregisterWorkspaceDirectoryCommandOutput } from "../commands/DeregisterWorkspaceDirectoryCommand";
import { DescribeAccountCommandInput, DescribeAccountCommandOutput } from "../commands/DescribeAccountCommand";
import { DescribeAccountModificationsCommandInput, DescribeAccountModificationsCommandOutput } from "../commands/DescribeAccountModificationsCommand";
import { DescribeClientPropertiesCommandInput, DescribeClientPropertiesCommandOutput } from "../commands/DescribeClientPropertiesCommand";
import { DescribeIpGroupsCommandInput, DescribeIpGroupsCommandOutput } from "../commands/DescribeIpGroupsCommand";
import { DescribeTagsCommandInput, DescribeTagsCommandOutput } from "../commands/DescribeTagsCommand";
import { DescribeWorkspaceBundlesCommandInput, DescribeWorkspaceBundlesCommandOutput } from "../commands/DescribeWorkspaceBundlesCommand";
import { DescribeWorkspaceDirectoriesCommandInput, DescribeWorkspaceDirectoriesCommandOutput } from "../commands/DescribeWorkspaceDirectoriesCommand";
import { DescribeWorkspaceImagesCommandInput, DescribeWorkspaceImagesCommandOutput } from "../commands/DescribeWorkspaceImagesCommand";
import { DescribeWorkspaceSnapshotsCommandInput, DescribeWorkspaceSnapshotsCommandOutput } from "../commands/DescribeWorkspaceSnapshotsCommand";
import { DescribeWorkspacesCommandInput, DescribeWorkspacesCommandOutput } from "../commands/DescribeWorkspacesCommand";
import { DescribeWorkspacesConnectionStatusCommandInput, DescribeWorkspacesConnectionStatusCommandOutput } from "../commands/DescribeWorkspacesConnectionStatusCommand";
import { DisassociateIpGroupsCommandInput, DisassociateIpGroupsCommandOutput } from "../commands/DisassociateIpGroupsCommand";
import { ImportWorkspaceImageCommandInput, ImportWorkspaceImageCommandOutput } from "../commands/ImportWorkspaceImageCommand";
import { ListAvailableManagementCidrRangesCommandInput, ListAvailableManagementCidrRangesCommandOutput } from "../commands/ListAvailableManagementCidrRangesCommand";
import { MigrateWorkspaceCommandInput, MigrateWorkspaceCommandOutput } from "../commands/MigrateWorkspaceCommand";
import { ModifyAccountCommandInput, ModifyAccountCommandOutput } from "../commands/ModifyAccountCommand";
import { ModifyClientPropertiesCommandInput, ModifyClientPropertiesCommandOutput } from "../commands/ModifyClientPropertiesCommand";
import { ModifySelfservicePermissionsCommandInput, ModifySelfservicePermissionsCommandOutput } from "../commands/ModifySelfservicePermissionsCommand";
import { ModifyWorkspaceAccessPropertiesCommandInput, ModifyWorkspaceAccessPropertiesCommandOutput } from "../commands/ModifyWorkspaceAccessPropertiesCommand";
import { ModifyWorkspaceCreationPropertiesCommandInput, ModifyWorkspaceCreationPropertiesCommandOutput } from "../commands/ModifyWorkspaceCreationPropertiesCommand";
import { ModifyWorkspacePropertiesCommandInput, ModifyWorkspacePropertiesCommandOutput } from "../commands/ModifyWorkspacePropertiesCommand";
import { ModifyWorkspaceStateCommandInput, ModifyWorkspaceStateCommandOutput } from "../commands/ModifyWorkspaceStateCommand";
import { RebootWorkspacesCommandInput, RebootWorkspacesCommandOutput } from "../commands/RebootWorkspacesCommand";
import { RebuildWorkspacesCommandInput, RebuildWorkspacesCommandOutput } from "../commands/RebuildWorkspacesCommand";
import { RegisterWorkspaceDirectoryCommandInput, RegisterWorkspaceDirectoryCommandOutput } from "../commands/RegisterWorkspaceDirectoryCommand";
import { RestoreWorkspaceCommandInput, RestoreWorkspaceCommandOutput } from "../commands/RestoreWorkspaceCommand";
import { RevokeIpRulesCommandInput, RevokeIpRulesCommandOutput } from "../commands/RevokeIpRulesCommand";
import { StartWorkspacesCommandInput, StartWorkspacesCommandOutput } from "../commands/StartWorkspacesCommand";
import { StopWorkspacesCommandInput, StopWorkspacesCommandOutput } from "../commands/StopWorkspacesCommand";
import { TerminateWorkspacesCommandInput, TerminateWorkspacesCommandOutput } from "../commands/TerminateWorkspacesCommand";
import { UpdateRulesOfIpGroupCommandInput, UpdateRulesOfIpGroupCommandOutput } from "../commands/UpdateRulesOfIpGroupCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateIpGroupsCommand(input: AssociateIpGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AuthorizeIpRulesCommand(input: AuthorizeIpRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CopyWorkspaceImageCommand(input: CopyWorkspaceImageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateIpGroupCommand(input: CreateIpGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTagsCommand(input: CreateTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateWorkspacesCommand(input: CreateWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteIpGroupCommand(input: DeleteIpGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTagsCommand(input: DeleteTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteWorkspaceImageCommand(input: DeleteWorkspaceImageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterWorkspaceDirectoryCommand(input: DeregisterWorkspaceDirectoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAccountCommand(input: DescribeAccountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAccountModificationsCommand(input: DescribeAccountModificationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeClientPropertiesCommand(input: DescribeClientPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeIpGroupsCommand(input: DescribeIpGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTagsCommand(input: DescribeTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspaceBundlesCommand(input: DescribeWorkspaceBundlesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspaceDirectoriesCommand(input: DescribeWorkspaceDirectoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspaceImagesCommand(input: DescribeWorkspaceImagesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspaceSnapshotsCommand(input: DescribeWorkspaceSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspacesCommand(input: DescribeWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkspacesConnectionStatusCommand(input: DescribeWorkspacesConnectionStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateIpGroupsCommand(input: DisassociateIpGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ImportWorkspaceImageCommand(input: ImportWorkspaceImageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAvailableManagementCidrRangesCommand(input: ListAvailableManagementCidrRangesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MigrateWorkspaceCommand(input: MigrateWorkspaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyAccountCommand(input: ModifyAccountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyClientPropertiesCommand(input: ModifyClientPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifySelfservicePermissionsCommand(input: ModifySelfservicePermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyWorkspaceAccessPropertiesCommand(input: ModifyWorkspaceAccessPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyWorkspaceCreationPropertiesCommand(input: ModifyWorkspaceCreationPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyWorkspacePropertiesCommand(input: ModifyWorkspacePropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ModifyWorkspaceStateCommand(input: ModifyWorkspaceStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebootWorkspacesCommand(input: RebootWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebuildWorkspacesCommand(input: RebuildWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterWorkspaceDirectoryCommand(input: RegisterWorkspaceDirectoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RestoreWorkspaceCommand(input: RestoreWorkspaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RevokeIpRulesCommand(input: RevokeIpRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartWorkspacesCommand(input: StartWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopWorkspacesCommand(input: StopWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TerminateWorkspacesCommand(input: TerminateWorkspacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRulesOfIpGroupCommand(input: UpdateRulesOfIpGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateIpGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateIpGroupsCommandOutput>;
export declare function deserializeAws_json1_1AuthorizeIpRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<AuthorizeIpRulesCommandOutput>;
export declare function deserializeAws_json1_1CopyWorkspaceImageCommand(output: __HttpResponse, context: __SerdeContext): Promise<CopyWorkspaceImageCommandOutput>;
export declare function deserializeAws_json1_1CreateIpGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateIpGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTagsCommandOutput>;
export declare function deserializeAws_json1_1CreateWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1DeleteIpGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteIpGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTagsCommandOutput>;
export declare function deserializeAws_json1_1DeleteWorkspaceImageCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteWorkspaceImageCommandOutput>;
export declare function deserializeAws_json1_1DeregisterWorkspaceDirectoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterWorkspaceDirectoryCommandOutput>;
export declare function deserializeAws_json1_1DescribeAccountCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAccountCommandOutput>;
export declare function deserializeAws_json1_1DescribeAccountModificationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAccountModificationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeClientPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClientPropertiesCommandOutput>;
export declare function deserializeAws_json1_1DescribeIpGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeIpGroupsCommandOutput>;
export declare function deserializeAws_json1_1DescribeTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTagsCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspaceBundlesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspaceBundlesCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspaceDirectoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspaceDirectoriesCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspaceImagesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspaceImagesCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspaceSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspaceSnapshotsCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkspacesConnectionStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkspacesConnectionStatusCommandOutput>;
export declare function deserializeAws_json1_1DisassociateIpGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateIpGroupsCommandOutput>;
export declare function deserializeAws_json1_1ImportWorkspaceImageCommand(output: __HttpResponse, context: __SerdeContext): Promise<ImportWorkspaceImageCommandOutput>;
export declare function deserializeAws_json1_1ListAvailableManagementCidrRangesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAvailableManagementCidrRangesCommandOutput>;
export declare function deserializeAws_json1_1MigrateWorkspaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<MigrateWorkspaceCommandOutput>;
export declare function deserializeAws_json1_1ModifyAccountCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyAccountCommandOutput>;
export declare function deserializeAws_json1_1ModifyClientPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyClientPropertiesCommandOutput>;
export declare function deserializeAws_json1_1ModifySelfservicePermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifySelfservicePermissionsCommandOutput>;
export declare function deserializeAws_json1_1ModifyWorkspaceAccessPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyWorkspaceAccessPropertiesCommandOutput>;
export declare function deserializeAws_json1_1ModifyWorkspaceCreationPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyWorkspaceCreationPropertiesCommandOutput>;
export declare function deserializeAws_json1_1ModifyWorkspacePropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyWorkspacePropertiesCommandOutput>;
export declare function deserializeAws_json1_1ModifyWorkspaceStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyWorkspaceStateCommandOutput>;
export declare function deserializeAws_json1_1RebootWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1RebuildWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebuildWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1RegisterWorkspaceDirectoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterWorkspaceDirectoryCommandOutput>;
export declare function deserializeAws_json1_1RestoreWorkspaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RestoreWorkspaceCommandOutput>;
export declare function deserializeAws_json1_1RevokeIpRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokeIpRulesCommandOutput>;
export declare function deserializeAws_json1_1StartWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1StopWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1TerminateWorkspacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<TerminateWorkspacesCommandOutput>;
export declare function deserializeAws_json1_1UpdateRulesOfIpGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRulesOfIpGroupCommandOutput>;
