// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AcceptDelegationRequest$,
  AcceptDelegationRequestCommand,
  AddClientIDToOpenIDConnectProvider$,
  AddClientIDToOpenIDConnectProviderCommand,
  AddRoleToInstanceProfile$,
  AddRoleToInstanceProfileCommand,
  AddUserToGroup$,
  AddUserToGroupCommand,
  AssociateDelegationRequest$,
  AssociateDelegationRequestCommand,
  AttachGroupPolicy$,
  AttachGroupPolicyCommand,
  AttachRolePolicy$,
  AttachRolePolicyCommand,
  AttachUserPolicy$,
  AttachUserPolicyCommand,
  ChangePassword$,
  ChangePasswordCommand,
  CreateAccessKey$,
  CreateAccessKeyCommand,
  CreateAccountAlias$,
  CreateAccountAliasCommand,
  CreateDelegationRequest$,
  CreateDelegationRequestCommand,
  CreateGroup$,
  CreateGroupCommand,
  CreateInstanceProfile$,
  CreateInstanceProfileCommand,
  CreateLoginProfile$,
  CreateLoginProfileCommand,
  CreateOpenIDConnectProvider$,
  CreateOpenIDConnectProviderCommand,
  CreatePolicy$,
  CreatePolicyCommand,
  CreatePolicyVersion$,
  CreatePolicyVersionCommand,
  CreateRole$,
  CreateRoleCommand,
  CreateSAMLProvider$,
  CreateSAMLProviderCommand,
  CreateServiceLinkedRole$,
  CreateServiceLinkedRoleCommand,
  CreateServiceSpecificCredential$,
  CreateServiceSpecificCredentialCommand,
  CreateUser$,
  CreateUserCommand,
  CreateVirtualMFADevice$,
  CreateVirtualMFADeviceCommand,
  DeactivateMFADevice$,
  DeactivateMFADeviceCommand,
  DeleteAccessKey$,
  DeleteAccessKeyCommand,
  DeleteAccountAlias$,
  DeleteAccountAliasCommand,
  DeleteAccountPasswordPolicy$,
  DeleteAccountPasswordPolicyCommand,
  DeleteGroup$,
  DeleteGroupCommand,
  DeleteGroupPolicy$,
  DeleteGroupPolicyCommand,
  DeleteInstanceProfile$,
  DeleteInstanceProfileCommand,
  DeleteLoginProfile$,
  DeleteLoginProfileCommand,
  DeleteOpenIDConnectProvider$,
  DeleteOpenIDConnectProviderCommand,
  DeletePolicy$,
  DeletePolicyCommand,
  DeletePolicyVersion$,
  DeletePolicyVersionCommand,
  DeleteRole$,
  DeleteRoleCommand,
  DeleteRolePermissionsBoundary$,
  DeleteRolePermissionsBoundaryCommand,
  DeleteRolePolicy$,
  DeleteRolePolicyCommand,
  DeleteSAMLProvider$,
  DeleteSAMLProviderCommand,
  DeleteServerCertificate$,
  DeleteServerCertificateCommand,
  DeleteServiceLinkedRole$,
  DeleteServiceLinkedRoleCommand,
  DeleteServiceSpecificCredential$,
  DeleteServiceSpecificCredentialCommand,
  DeleteSigningCertificate$,
  DeleteSigningCertificateCommand,
  DeleteSSHPublicKey$,
  DeleteSSHPublicKeyCommand,
  DeleteUser$,
  DeleteUserCommand,
  DeleteUserPermissionsBoundary$,
  DeleteUserPermissionsBoundaryCommand,
  DeleteUserPolicy$,
  DeleteUserPolicyCommand,
  DeleteVirtualMFADevice$,
  DeleteVirtualMFADeviceCommand,
  DetachGroupPolicy$,
  DetachGroupPolicyCommand,
  DetachRolePolicy$,
  DetachRolePolicyCommand,
  DetachUserPolicy$,
  DetachUserPolicyCommand,
  DisableOrganizationsRootCredentialsManagement$,
  DisableOrganizationsRootCredentialsManagementCommand,
  DisableOrganizationsRootSessions$,
  DisableOrganizationsRootSessionsCommand,
  DisableOutboundWebIdentityFederation$,
  DisableOutboundWebIdentityFederationCommand,
  EnableMFADevice$,
  EnableMFADeviceCommand,
  EnableOrganizationsRootCredentialsManagement$,
  EnableOrganizationsRootCredentialsManagementCommand,
  EnableOrganizationsRootSessions$,
  EnableOrganizationsRootSessionsCommand,
  EnableOutboundWebIdentityFederation$,
  EnableOutboundWebIdentityFederationCommand,
  GenerateCredentialReport$,
  GenerateCredentialReportCommand,
  GenerateOrganizationsAccessReport$,
  GenerateOrganizationsAccessReportCommand,
  GenerateServiceLastAccessedDetails$,
  GenerateServiceLastAccessedDetailsCommand,
  GetAccessKeyLastUsed$,
  GetAccessKeyLastUsedCommand,
  GetAccountAuthorizationDetails$,
  GetAccountAuthorizationDetailsCommand,
  GetAccountPasswordPolicy$,
  GetAccountPasswordPolicyCommand,
  GetAccountSummary$,
  GetAccountSummaryCommand,
  GetContextKeysForCustomPolicy$,
  GetContextKeysForCustomPolicyCommand,
  GetContextKeysForPrincipalPolicy$,
  GetContextKeysForPrincipalPolicyCommand,
  GetCredentialReport$,
  GetCredentialReportCommand,
  GetDelegationRequest$,
  GetDelegationRequestCommand,
  GetGroup$,
  GetGroupCommand,
  GetGroupPolicy$,
  GetGroupPolicyCommand,
  GetHumanReadableSummary$,
  GetHumanReadableSummaryCommand,
  GetInstanceProfile$,
  GetInstanceProfileCommand,
  GetLoginProfile$,
  GetLoginProfileCommand,
  GetMFADevice$,
  GetMFADeviceCommand,
  GetOpenIDConnectProvider$,
  GetOpenIDConnectProviderCommand,
  GetOrganizationsAccessReport$,
  GetOrganizationsAccessReportCommand,
  GetOutboundWebIdentityFederationInfo$,
  GetOutboundWebIdentityFederationInfoCommand,
  GetPolicy$,
  GetPolicyCommand,
  GetPolicyVersion$,
  GetPolicyVersionCommand,
  GetRole$,
  GetRoleCommand,
  GetRolePolicy$,
  GetRolePolicyCommand,
  GetSAMLProvider$,
  GetSAMLProviderCommand,
  GetServerCertificate$,
  GetServerCertificateCommand,
  GetServiceLastAccessedDetails$,
  GetServiceLastAccessedDetailsCommand,
  GetServiceLastAccessedDetailsWithEntities$,
  GetServiceLastAccessedDetailsWithEntitiesCommand,
  GetServiceLinkedRoleDeletionStatus$,
  GetServiceLinkedRoleDeletionStatusCommand,
  GetSSHPublicKey$,
  GetSSHPublicKeyCommand,
  GetUser$,
  GetUserCommand,
  GetUserPolicy$,
  GetUserPolicyCommand,
  IAMClient,
  ListAccessKeys$,
  ListAccessKeysCommand,
  ListAccountAliases$,
  ListAccountAliasesCommand,
  ListAttachedGroupPolicies$,
  ListAttachedGroupPoliciesCommand,
  ListAttachedRolePolicies$,
  ListAttachedRolePoliciesCommand,
  ListAttachedUserPolicies$,
  ListAttachedUserPoliciesCommand,
  ListDelegationRequests$,
  ListDelegationRequestsCommand,
  ListEntitiesForPolicy$,
  ListEntitiesForPolicyCommand,
  ListGroupPolicies$,
  ListGroupPoliciesCommand,
  ListGroups$,
  ListGroupsCommand,
  ListGroupsForUser$,
  ListGroupsForUserCommand,
  ListInstanceProfiles$,
  ListInstanceProfilesCommand,
  ListInstanceProfilesForRole$,
  ListInstanceProfilesForRoleCommand,
  ListInstanceProfileTags$,
  ListInstanceProfileTagsCommand,
  ListMFADevices$,
  ListMFADevicesCommand,
  ListMFADeviceTags$,
  ListMFADeviceTagsCommand,
  ListOpenIDConnectProviders$,
  ListOpenIDConnectProvidersCommand,
  ListOpenIDConnectProviderTags$,
  ListOpenIDConnectProviderTagsCommand,
  ListOrganizationsFeatures$,
  ListOrganizationsFeaturesCommand,
  ListPolicies$,
  ListPoliciesCommand,
  ListPoliciesGrantingServiceAccess$,
  ListPoliciesGrantingServiceAccessCommand,
  ListPolicyTags$,
  ListPolicyTagsCommand,
  ListPolicyVersions$,
  ListPolicyVersionsCommand,
  ListRolePolicies$,
  ListRolePoliciesCommand,
  ListRoles$,
  ListRolesCommand,
  ListRoleTags$,
  ListRoleTagsCommand,
  ListSAMLProviders$,
  ListSAMLProvidersCommand,
  ListSAMLProviderTags$,
  ListSAMLProviderTagsCommand,
  ListServerCertificates$,
  ListServerCertificatesCommand,
  ListServerCertificateTags$,
  ListServerCertificateTagsCommand,
  ListServiceSpecificCredentials$,
  ListServiceSpecificCredentialsCommand,
  ListSigningCertificates$,
  ListSigningCertificatesCommand,
  ListSSHPublicKeys$,
  ListSSHPublicKeysCommand,
  ListUserPolicies$,
  ListUserPoliciesCommand,
  ListUsers$,
  ListUsersCommand,
  ListUserTags$,
  ListUserTagsCommand,
  ListVirtualMFADevices$,
  ListVirtualMFADevicesCommand,
  PutGroupPolicy$,
  PutGroupPolicyCommand,
  PutRolePermissionsBoundary$,
  PutRolePermissionsBoundaryCommand,
  PutRolePolicy$,
  PutRolePolicyCommand,
  PutUserPermissionsBoundary$,
  PutUserPermissionsBoundaryCommand,
  PutUserPolicy$,
  PutUserPolicyCommand,
  RejectDelegationRequest$,
  RejectDelegationRequestCommand,
  RemoveClientIDFromOpenIDConnectProvider$,
  RemoveClientIDFromOpenIDConnectProviderCommand,
  RemoveRoleFromInstanceProfile$,
  RemoveRoleFromInstanceProfileCommand,
  RemoveUserFromGroup$,
  RemoveUserFromGroupCommand,
  ResetServiceSpecificCredential$,
  ResetServiceSpecificCredentialCommand,
  ResyncMFADevice$,
  ResyncMFADeviceCommand,
  SendDelegationToken$,
  SendDelegationTokenCommand,
  SetDefaultPolicyVersion$,
  SetDefaultPolicyVersionCommand,
  SetSecurityTokenServicePreferences$,
  SetSecurityTokenServicePreferencesCommand,
  SimulateCustomPolicy$,
  SimulateCustomPolicyCommand,
  SimulatePrincipalPolicy$,
  SimulatePrincipalPolicyCommand,
  TagInstanceProfile$,
  TagInstanceProfileCommand,
  TagMFADevice$,
  TagMFADeviceCommand,
  TagOpenIDConnectProvider$,
  TagOpenIDConnectProviderCommand,
  TagPolicy$,
  TagPolicyCommand,
  TagRole$,
  TagRoleCommand,
  TagSAMLProvider$,
  TagSAMLProviderCommand,
  TagServerCertificate$,
  TagServerCertificateCommand,
  TagUser$,
  TagUserCommand,
  UntagInstanceProfile$,
  UntagInstanceProfileCommand,
  UntagMFADevice$,
  UntagMFADeviceCommand,
  UntagOpenIDConnectProvider$,
  UntagOpenIDConnectProviderCommand,
  UntagPolicy$,
  UntagPolicyCommand,
  UntagRole$,
  UntagRoleCommand,
  UntagSAMLProvider$,
  UntagSAMLProviderCommand,
  UntagServerCertificate$,
  UntagServerCertificateCommand,
  UntagUser$,
  UntagUserCommand,
  UpdateAccessKey$,
  UpdateAccessKeyCommand,
  UpdateAccountPasswordPolicy$,
  UpdateAccountPasswordPolicyCommand,
  UpdateAssumeRolePolicy$,
  UpdateAssumeRolePolicyCommand,
  UpdateDelegationRequest$,
  UpdateDelegationRequestCommand,
  UpdateGroup$,
  UpdateGroupCommand,
  UpdateLoginProfile$,
  UpdateLoginProfileCommand,
  UpdateOpenIDConnectProviderThumbprint$,
  UpdateOpenIDConnectProviderThumbprintCommand,
  UpdateRole$,
  UpdateRoleCommand,
  UpdateRoleDescription$,
  UpdateRoleDescriptionCommand,
  UpdateSAMLProvider$,
  UpdateSAMLProviderCommand,
  UpdateServerCertificate$,
  UpdateServerCertificateCommand,
  UpdateServiceSpecificCredential$,
  UpdateServiceSpecificCredentialCommand,
  UpdateSigningCertificate$,
  UpdateSigningCertificateCommand,
  UpdateSSHPublicKey$,
  UpdateSSHPublicKeyCommand,
  UpdateUser$,
  UpdateUserCommand,
  UploadServerCertificate$,
  UploadServerCertificateCommand,
  UploadSigningCertificate$,
  UploadSigningCertificateCommand,
  UploadSSHPublicKey$,
  UploadSSHPublicKeyCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = IAMClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("IAMClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas:
      new Map<any, any>([
        [AcceptDelegationRequest$, AcceptDelegationRequestCommand],
        [AddClientIDToOpenIDConnectProvider$, AddClientIDToOpenIDConnectProviderCommand],
        [AddRoleToInstanceProfile$, AddRoleToInstanceProfileCommand],
        [AddUserToGroup$, AddUserToGroupCommand],
        [AssociateDelegationRequest$, AssociateDelegationRequestCommand],
        [AttachGroupPolicy$, AttachGroupPolicyCommand],
        [AttachRolePolicy$, AttachRolePolicyCommand],
        [AttachUserPolicy$, AttachUserPolicyCommand],
        [ChangePassword$, ChangePasswordCommand],
        [CreateAccessKey$, CreateAccessKeyCommand],
        [CreateAccountAlias$, CreateAccountAliasCommand],
        [CreateDelegationRequest$, CreateDelegationRequestCommand],
        [CreateGroup$, CreateGroupCommand],
        [CreateInstanceProfile$, CreateInstanceProfileCommand],
        [CreateLoginProfile$, CreateLoginProfileCommand],
        [CreateOpenIDConnectProvider$, CreateOpenIDConnectProviderCommand],
        [CreatePolicy$, CreatePolicyCommand],
        [CreatePolicyVersion$, CreatePolicyVersionCommand],
        [CreateRole$, CreateRoleCommand],
        [CreateSAMLProvider$, CreateSAMLProviderCommand],
        [CreateServiceLinkedRole$, CreateServiceLinkedRoleCommand],
        [CreateServiceSpecificCredential$, CreateServiceSpecificCredentialCommand],
        [CreateUser$, CreateUserCommand],
        [CreateVirtualMFADevice$, CreateVirtualMFADeviceCommand],
        [DeactivateMFADevice$, DeactivateMFADeviceCommand],
        [DeleteAccessKey$, DeleteAccessKeyCommand],
        [DeleteAccountAlias$, DeleteAccountAliasCommand],
        [DeleteAccountPasswordPolicy$, DeleteAccountPasswordPolicyCommand],
        [DeleteGroup$, DeleteGroupCommand],
        [DeleteGroupPolicy$, DeleteGroupPolicyCommand],
        [DeleteInstanceProfile$, DeleteInstanceProfileCommand],
        [DeleteLoginProfile$, DeleteLoginProfileCommand],
        [DeleteOpenIDConnectProvider$, DeleteOpenIDConnectProviderCommand],
        [DeletePolicy$, DeletePolicyCommand],
        [DeletePolicyVersion$, DeletePolicyVersionCommand],
        [DeleteRole$, DeleteRoleCommand],
        [DeleteRolePermissionsBoundary$, DeleteRolePermissionsBoundaryCommand],
        [DeleteRolePolicy$, DeleteRolePolicyCommand],
        [DeleteSAMLProvider$, DeleteSAMLProviderCommand],
        [DeleteServerCertificate$, DeleteServerCertificateCommand],
        [DeleteServiceLinkedRole$, DeleteServiceLinkedRoleCommand],
        [DeleteServiceSpecificCredential$, DeleteServiceSpecificCredentialCommand],
        [DeleteSigningCertificate$, DeleteSigningCertificateCommand],
        [DeleteSSHPublicKey$, DeleteSSHPublicKeyCommand],
        [DeleteUser$, DeleteUserCommand],
        [DeleteUserPermissionsBoundary$, DeleteUserPermissionsBoundaryCommand],
        [DeleteUserPolicy$, DeleteUserPolicyCommand],
        [DeleteVirtualMFADevice$, DeleteVirtualMFADeviceCommand],
        [DetachGroupPolicy$, DetachGroupPolicyCommand],
        [DetachRolePolicy$, DetachRolePolicyCommand],
        [DetachUserPolicy$, DetachUserPolicyCommand],
        [DisableOrganizationsRootCredentialsManagement$, DisableOrganizationsRootCredentialsManagementCommand],
        [DisableOrganizationsRootSessions$, DisableOrganizationsRootSessionsCommand],
        [DisableOutboundWebIdentityFederation$, DisableOutboundWebIdentityFederationCommand],
        [EnableMFADevice$, EnableMFADeviceCommand],
        [EnableOrganizationsRootCredentialsManagement$, EnableOrganizationsRootCredentialsManagementCommand],
        [EnableOrganizationsRootSessions$, EnableOrganizationsRootSessionsCommand],
        [EnableOutboundWebIdentityFederation$, EnableOutboundWebIdentityFederationCommand],
        [GenerateCredentialReport$, GenerateCredentialReportCommand],
        [GenerateOrganizationsAccessReport$, GenerateOrganizationsAccessReportCommand],
        [GenerateServiceLastAccessedDetails$, GenerateServiceLastAccessedDetailsCommand],
        [GetAccessKeyLastUsed$, GetAccessKeyLastUsedCommand],
        [GetAccountAuthorizationDetails$, GetAccountAuthorizationDetailsCommand],
        [GetAccountPasswordPolicy$, GetAccountPasswordPolicyCommand],
        [GetAccountSummary$, GetAccountSummaryCommand],
        [GetContextKeysForCustomPolicy$, GetContextKeysForCustomPolicyCommand],
        [GetContextKeysForPrincipalPolicy$, GetContextKeysForPrincipalPolicyCommand],
        [GetCredentialReport$, GetCredentialReportCommand],
        [GetDelegationRequest$, GetDelegationRequestCommand],
        [GetGroup$, GetGroupCommand],
        [GetGroupPolicy$, GetGroupPolicyCommand],
        [GetHumanReadableSummary$, GetHumanReadableSummaryCommand],
        [GetInstanceProfile$, GetInstanceProfileCommand],
        [GetLoginProfile$, GetLoginProfileCommand],
        [GetMFADevice$, GetMFADeviceCommand],
        [GetOpenIDConnectProvider$, GetOpenIDConnectProviderCommand],
        [GetOrganizationsAccessReport$, GetOrganizationsAccessReportCommand],
        [GetOutboundWebIdentityFederationInfo$, GetOutboundWebIdentityFederationInfoCommand],
        [GetPolicy$, GetPolicyCommand],
        [GetPolicyVersion$, GetPolicyVersionCommand],
        [GetRole$, GetRoleCommand],
        [GetRolePolicy$, GetRolePolicyCommand],
        [GetSAMLProvider$, GetSAMLProviderCommand],
        [GetServerCertificate$, GetServerCertificateCommand],
        [GetServiceLastAccessedDetails$, GetServiceLastAccessedDetailsCommand],
        [GetServiceLastAccessedDetailsWithEntities$, GetServiceLastAccessedDetailsWithEntitiesCommand],
        [GetServiceLinkedRoleDeletionStatus$, GetServiceLinkedRoleDeletionStatusCommand],
        [GetSSHPublicKey$, GetSSHPublicKeyCommand],
        [GetUser$, GetUserCommand],
        [GetUserPolicy$, GetUserPolicyCommand],
        [ListAccessKeys$, ListAccessKeysCommand],
        [ListAccountAliases$, ListAccountAliasesCommand],
        [ListAttachedGroupPolicies$, ListAttachedGroupPoliciesCommand],
        [ListAttachedRolePolicies$, ListAttachedRolePoliciesCommand],
        [ListAttachedUserPolicies$, ListAttachedUserPoliciesCommand],
        [ListDelegationRequests$, ListDelegationRequestsCommand],
        [ListEntitiesForPolicy$, ListEntitiesForPolicyCommand],
        [ListGroupPolicies$, ListGroupPoliciesCommand],
        [ListGroups$, ListGroupsCommand],
        [ListGroupsForUser$, ListGroupsForUserCommand],
        [ListInstanceProfiles$, ListInstanceProfilesCommand],
        [ListInstanceProfilesForRole$, ListInstanceProfilesForRoleCommand],
        [ListInstanceProfileTags$, ListInstanceProfileTagsCommand],
        [ListMFADevices$, ListMFADevicesCommand],
        [ListMFADeviceTags$, ListMFADeviceTagsCommand],
        [ListOpenIDConnectProviders$, ListOpenIDConnectProvidersCommand],
        [ListOpenIDConnectProviderTags$, ListOpenIDConnectProviderTagsCommand],
        [ListOrganizationsFeatures$, ListOrganizationsFeaturesCommand],
        [ListPolicies$, ListPoliciesCommand],
        [ListPoliciesGrantingServiceAccess$, ListPoliciesGrantingServiceAccessCommand],
        [ListPolicyTags$, ListPolicyTagsCommand],
        [ListPolicyVersions$, ListPolicyVersionsCommand],
        [ListRolePolicies$, ListRolePoliciesCommand],
        [ListRoles$, ListRolesCommand],
        [ListRoleTags$, ListRoleTagsCommand],
        [ListSAMLProviders$, ListSAMLProvidersCommand],
        [ListSAMLProviderTags$, ListSAMLProviderTagsCommand],
        [ListServerCertificates$, ListServerCertificatesCommand],
        [ListServerCertificateTags$, ListServerCertificateTagsCommand],
        [ListServiceSpecificCredentials$, ListServiceSpecificCredentialsCommand],
        [ListSigningCertificates$, ListSigningCertificatesCommand],
        [ListSSHPublicKeys$, ListSSHPublicKeysCommand],
        [ListUserPolicies$, ListUserPoliciesCommand],
        [ListUsers$, ListUsersCommand],
        [ListUserTags$, ListUserTagsCommand],
        [ListVirtualMFADevices$, ListVirtualMFADevicesCommand],
        [PutGroupPolicy$, PutGroupPolicyCommand],
        [PutRolePermissionsBoundary$, PutRolePermissionsBoundaryCommand],
        [PutRolePolicy$, PutRolePolicyCommand],
        [PutUserPermissionsBoundary$, PutUserPermissionsBoundaryCommand],
        [PutUserPolicy$, PutUserPolicyCommand],
        [RejectDelegationRequest$, RejectDelegationRequestCommand],
        [RemoveClientIDFromOpenIDConnectProvider$, RemoveClientIDFromOpenIDConnectProviderCommand],
        [RemoveRoleFromInstanceProfile$, RemoveRoleFromInstanceProfileCommand],
        [RemoveUserFromGroup$, RemoveUserFromGroupCommand],
        [ResetServiceSpecificCredential$, ResetServiceSpecificCredentialCommand],
        [ResyncMFADevice$, ResyncMFADeviceCommand],
        [SendDelegationToken$, SendDelegationTokenCommand],
        [SetDefaultPolicyVersion$, SetDefaultPolicyVersionCommand],
        [SetSecurityTokenServicePreferences$, SetSecurityTokenServicePreferencesCommand],
        [SimulateCustomPolicy$, SimulateCustomPolicyCommand],
        [SimulatePrincipalPolicy$, SimulatePrincipalPolicyCommand],
        [TagInstanceProfile$, TagInstanceProfileCommand],
        [TagMFADevice$, TagMFADeviceCommand],
        [TagOpenIDConnectProvider$, TagOpenIDConnectProviderCommand],
        [TagPolicy$, TagPolicyCommand],
        [TagRole$, TagRoleCommand],
        [TagSAMLProvider$, TagSAMLProviderCommand],
        [TagServerCertificate$, TagServerCertificateCommand],
        [TagUser$, TagUserCommand],
        [UntagInstanceProfile$, UntagInstanceProfileCommand],
        [UntagMFADevice$, UntagMFADeviceCommand],
        [UntagOpenIDConnectProvider$, UntagOpenIDConnectProviderCommand],
        [UntagPolicy$, UntagPolicyCommand],
        [UntagRole$, UntagRoleCommand],
        [UntagSAMLProvider$, UntagSAMLProviderCommand],
        [UntagServerCertificate$, UntagServerCertificateCommand],
        [UntagUser$, UntagUserCommand],
        [UpdateAccessKey$, UpdateAccessKeyCommand],
        [UpdateAccountPasswordPolicy$, UpdateAccountPasswordPolicyCommand],
        [UpdateAssumeRolePolicy$, UpdateAssumeRolePolicyCommand],
        [UpdateDelegationRequest$, UpdateDelegationRequestCommand],
        [UpdateGroup$, UpdateGroupCommand],
        [UpdateLoginProfile$, UpdateLoginProfileCommand],
        [UpdateOpenIDConnectProviderThumbprint$, UpdateOpenIDConnectProviderThumbprintCommand],
        [UpdateRole$, UpdateRoleCommand],
        [UpdateRoleDescription$, UpdateRoleDescriptionCommand],
        [UpdateSAMLProvider$, UpdateSAMLProviderCommand],
        [UpdateServerCertificate$, UpdateServerCertificateCommand],
        [UpdateServiceSpecificCredential$, UpdateServiceSpecificCredentialCommand],
        [UpdateSigningCertificate$, UpdateSigningCertificateCommand],
        [UpdateSSHPublicKey$, UpdateSSHPublicKeyCommand],
        [UpdateUser$, UpdateUserCommand],
        [UploadServerCertificate$, UploadServerCertificateCommand],
        [UploadSigningCertificate$, UploadSigningCertificateCommand],
        [UploadSSHPublicKey$, UploadSSHPublicKeyCommand],
      ]),

  });

  runner.run();
}, 30_000);
