import { ReportGenerationLimitExceededException } from "./ReportGenerationLimitExceededException";
export type GenerateOrganizationsAccessReportExceptionsUnion = ReportGenerationLimitExceededException;
