import { AssociateNodeCommandInput, AssociateNodeCommandOutput } from "../commands/AssociateNodeCommand";
import { CreateBackupCommandInput, CreateBackupCommandOutput } from "../commands/CreateBackupCommand";
import { CreateServerCommandInput, CreateServerCommandOutput } from "../commands/CreateServerCommand";
import { DeleteBackupCommandInput, DeleteBackupCommandOutput } from "../commands/DeleteBackupCommand";
import { DeleteServerCommandInput, DeleteServerCommandOutput } from "../commands/DeleteServerCommand";
import { DescribeAccountAttributesCommandInput, DescribeAccountAttributesCommandOutput } from "../commands/DescribeAccountAttributesCommand";
import { DescribeBackupsCommandInput, DescribeBackupsCommandOutput } from "../commands/DescribeBackupsCommand";
import { DescribeEventsCommandInput, DescribeEventsCommandOutput } from "../commands/DescribeEventsCommand";
import { DescribeNodeAssociationStatusCommandInput, DescribeNodeAssociationStatusCommandOutput } from "../commands/DescribeNodeAssociationStatusCommand";
import { DescribeServersCommandInput, DescribeServersCommandOutput } from "../commands/DescribeServersCommand";
import { DisassociateNodeCommandInput, DisassociateNodeCommandOutput } from "../commands/DisassociateNodeCommand";
import { ExportServerEngineAttributeCommandInput, ExportServerEngineAttributeCommandOutput } from "../commands/ExportServerEngineAttributeCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { RestoreServerCommandInput, RestoreServerCommandOutput } from "../commands/RestoreServerCommand";
import { StartMaintenanceCommandInput, StartMaintenanceCommandOutput } from "../commands/StartMaintenanceCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateServerCommandInput, UpdateServerCommandOutput } from "../commands/UpdateServerCommand";
import { UpdateServerEngineAttributesCommandInput, UpdateServerEngineAttributesCommandOutput } from "../commands/UpdateServerEngineAttributesCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateNodeCommand(input: AssociateNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateBackupCommand(input: CreateBackupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateServerCommand(input: CreateServerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBackupCommand(input: DeleteBackupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteServerCommand(input: DeleteServerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAccountAttributesCommand(input: DescribeAccountAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBackupsCommand(input: DescribeBackupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEventsCommand(input: DescribeEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeNodeAssociationStatusCommand(input: DescribeNodeAssociationStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeServersCommand(input: DescribeServersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateNodeCommand(input: DisassociateNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ExportServerEngineAttributeCommand(input: ExportServerEngineAttributeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RestoreServerCommand(input: RestoreServerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartMaintenanceCommand(input: StartMaintenanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateServerCommand(input: UpdateServerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateServerEngineAttributesCommand(input: UpdateServerEngineAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateNodeCommandOutput>;
export declare function deserializeAws_json1_1CreateBackupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBackupCommandOutput>;
export declare function deserializeAws_json1_1CreateServerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateServerCommandOutput>;
export declare function deserializeAws_json1_1DeleteBackupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBackupCommandOutput>;
export declare function deserializeAws_json1_1DeleteServerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteServerCommandOutput>;
export declare function deserializeAws_json1_1DescribeAccountAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAccountAttributesCommandOutput>;
export declare function deserializeAws_json1_1DescribeBackupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBackupsCommandOutput>;
export declare function deserializeAws_json1_1DescribeEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventsCommandOutput>;
export declare function deserializeAws_json1_1DescribeNodeAssociationStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeNodeAssociationStatusCommandOutput>;
export declare function deserializeAws_json1_1DescribeServersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeServersCommandOutput>;
export declare function deserializeAws_json1_1DisassociateNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateNodeCommandOutput>;
export declare function deserializeAws_json1_1ExportServerEngineAttributeCommand(output: __HttpResponse, context: __SerdeContext): Promise<ExportServerEngineAttributeCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1RestoreServerCommand(output: __HttpResponse, context: __SerdeContext): Promise<RestoreServerCommandOutput>;
export declare function deserializeAws_json1_1StartMaintenanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMaintenanceCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateServerCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateServerCommandOutput>;
export declare function deserializeAws_json1_1UpdateServerEngineAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateServerEngineAttributesCommandOutput>;
