import { AddAttachmentsToSetCommandInput, AddAttachmentsToSetCommandOutput } from "../commands/AddAttachmentsToSetCommand";
import { AddCommunicationToCaseCommandInput, AddCommunicationToCaseCommandOutput } from "../commands/AddCommunicationToCaseCommand";
import { CreateCaseCommandInput, CreateCaseCommandOutput } from "../commands/CreateCaseCommand";
import { DescribeAttachmentCommandInput, DescribeAttachmentCommandOutput } from "../commands/DescribeAttachmentCommand";
import { DescribeCasesCommandInput, DescribeCasesCommandOutput } from "../commands/DescribeCasesCommand";
import { DescribeCommunicationsCommandInput, DescribeCommunicationsCommandOutput } from "../commands/DescribeCommunicationsCommand";
import { DescribeServicesCommandInput, DescribeServicesCommandOutput } from "../commands/DescribeServicesCommand";
import { DescribeSeverityLevelsCommandInput, DescribeSeverityLevelsCommandOutput } from "../commands/DescribeSeverityLevelsCommand";
import { DescribeTrustedAdvisorCheckRefreshStatusesCommandInput, DescribeTrustedAdvisorCheckRefreshStatusesCommandOutput } from "../commands/DescribeTrustedAdvisorCheckRefreshStatusesCommand";
import { DescribeTrustedAdvisorCheckResultCommandInput, DescribeTrustedAdvisorCheckResultCommandOutput } from "../commands/DescribeTrustedAdvisorCheckResultCommand";
import { DescribeTrustedAdvisorCheckSummariesCommandInput, DescribeTrustedAdvisorCheckSummariesCommandOutput } from "../commands/DescribeTrustedAdvisorCheckSummariesCommand";
import { DescribeTrustedAdvisorChecksCommandInput, DescribeTrustedAdvisorChecksCommandOutput } from "../commands/DescribeTrustedAdvisorChecksCommand";
import { RefreshTrustedAdvisorCheckCommandInput, RefreshTrustedAdvisorCheckCommandOutput } from "../commands/RefreshTrustedAdvisorCheckCommand";
import { ResolveCaseCommandInput, ResolveCaseCommandOutput } from "../commands/ResolveCaseCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddAttachmentsToSetCommand(input: AddAttachmentsToSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddCommunicationToCaseCommand(input: AddCommunicationToCaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateCaseCommand(input: CreateCaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAttachmentCommand(input: DescribeAttachmentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCasesCommand(input: DescribeCasesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCommunicationsCommand(input: DescribeCommunicationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeServicesCommand(input: DescribeServicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSeverityLevelsCommand(input: DescribeSeverityLevelsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResolveCaseCommand(input: ResolveCaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTrustedAdvisorCheckRefreshStatusesCommand(input: DescribeTrustedAdvisorCheckRefreshStatusesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTrustedAdvisorCheckResultCommand(input: DescribeTrustedAdvisorCheckResultCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTrustedAdvisorCheckSummariesCommand(input: DescribeTrustedAdvisorCheckSummariesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTrustedAdvisorChecksCommand(input: DescribeTrustedAdvisorChecksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RefreshTrustedAdvisorCheckCommand(input: RefreshTrustedAdvisorCheckCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddAttachmentsToSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddAttachmentsToSetCommandOutput>;
export declare function deserializeAws_json1_1AddCommunicationToCaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddCommunicationToCaseCommandOutput>;
export declare function deserializeAws_json1_1CreateCaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCaseCommandOutput>;
export declare function deserializeAws_json1_1DescribeAttachmentCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAttachmentCommandOutput>;
export declare function deserializeAws_json1_1DescribeCasesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCasesCommandOutput>;
export declare function deserializeAws_json1_1DescribeCommunicationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCommunicationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeServicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeServicesCommandOutput>;
export declare function deserializeAws_json1_1DescribeSeverityLevelsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSeverityLevelsCommandOutput>;
export declare function deserializeAws_json1_1ResolveCaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResolveCaseCommandOutput>;
export declare function deserializeAws_json1_1DescribeTrustedAdvisorCheckRefreshStatusesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTrustedAdvisorCheckRefreshStatusesCommandOutput>;
export declare function deserializeAws_json1_1DescribeTrustedAdvisorCheckResultCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTrustedAdvisorCheckResultCommandOutput>;
export declare function deserializeAws_json1_1DescribeTrustedAdvisorCheckSummariesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTrustedAdvisorCheckSummariesCommandOutput>;
export declare function deserializeAws_json1_1DescribeTrustedAdvisorChecksCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTrustedAdvisorChecksCommandOutput>;
export declare function deserializeAws_json1_1RefreshTrustedAdvisorCheckCommand(output: __HttpResponse, context: __SerdeContext): Promise<RefreshTrustedAdvisorCheckCommandOutput>;
