import { CreateContainerCommandInput, CreateContainerCommandOutput } from "../commands/CreateContainerCommand";
import { DeleteContainerCommandInput, DeleteContainerCommandOutput } from "../commands/DeleteContainerCommand";
import { DeleteContainerPolicyCommandInput, DeleteContainerPolicyCommandOutput } from "../commands/DeleteContainerPolicyCommand";
import { DeleteCorsPolicyCommandInput, DeleteCorsPolicyCommandOutput } from "../commands/DeleteCorsPolicyCommand";
import { DeleteLifecyclePolicyCommandInput, DeleteLifecyclePolicyCommandOutput } from "../commands/DeleteLifecyclePolicyCommand";
import { DescribeContainerCommandInput, DescribeContainerCommandOutput } from "../commands/DescribeContainerCommand";
import { GetContainerPolicyCommandInput, GetContainerPolicyCommandOutput } from "../commands/GetContainerPolicyCommand";
import { GetCorsPolicyCommandInput, GetCorsPolicyCommandOutput } from "../commands/GetCorsPolicyCommand";
import { GetLifecyclePolicyCommandInput, GetLifecyclePolicyCommandOutput } from "../commands/GetLifecyclePolicyCommand";
import { ListContainersCommandInput, ListContainersCommandOutput } from "../commands/ListContainersCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { PutContainerPolicyCommandInput, PutContainerPolicyCommandOutput } from "../commands/PutContainerPolicyCommand";
import { PutCorsPolicyCommandInput, PutCorsPolicyCommandOutput } from "../commands/PutCorsPolicyCommand";
import { PutLifecyclePolicyCommandInput, PutLifecyclePolicyCommandOutput } from "../commands/PutLifecyclePolicyCommand";
import { StartAccessLoggingCommandInput, StartAccessLoggingCommandOutput } from "../commands/StartAccessLoggingCommand";
import { StopAccessLoggingCommandInput, StopAccessLoggingCommandOutput } from "../commands/StopAccessLoggingCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateContainerCommand(input: CreateContainerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteContainerCommand(input: DeleteContainerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteContainerPolicyCommand(input: DeleteContainerPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteCorsPolicyCommand(input: DeleteCorsPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLifecyclePolicyCommand(input: DeleteLifecyclePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeContainerCommand(input: DescribeContainerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetContainerPolicyCommand(input: GetContainerPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCorsPolicyCommand(input: GetCorsPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLifecyclePolicyCommand(input: GetLifecyclePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListContainersCommand(input: ListContainersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutContainerPolicyCommand(input: PutContainerPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutCorsPolicyCommand(input: PutCorsPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutLifecyclePolicyCommand(input: PutLifecyclePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartAccessLoggingCommand(input: StartAccessLoggingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopAccessLoggingCommand(input: StopAccessLoggingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateContainerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateContainerCommandOutput>;
export declare function deserializeAws_json1_1DeleteContainerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteContainerCommandOutput>;
export declare function deserializeAws_json1_1DeleteContainerPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteContainerPolicyCommandOutput>;
export declare function deserializeAws_json1_1DeleteCorsPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCorsPolicyCommandOutput>;
export declare function deserializeAws_json1_1DeleteLifecyclePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLifecyclePolicyCommandOutput>;
export declare function deserializeAws_json1_1DescribeContainerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeContainerCommandOutput>;
export declare function deserializeAws_json1_1GetContainerPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetContainerPolicyCommandOutput>;
export declare function deserializeAws_json1_1GetCorsPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCorsPolicyCommandOutput>;
export declare function deserializeAws_json1_1GetLifecyclePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLifecyclePolicyCommandOutput>;
export declare function deserializeAws_json1_1ListContainersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListContainersCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1PutContainerPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutContainerPolicyCommandOutput>;
export declare function deserializeAws_json1_1PutCorsPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutCorsPolicyCommandOutput>;
export declare function deserializeAws_json1_1PutLifecyclePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutLifecyclePolicyCommandOutput>;
export declare function deserializeAws_json1_1StartAccessLoggingCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartAccessLoggingCommandOutput>;
export declare function deserializeAws_json1_1StopAccessLoggingCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopAccessLoggingCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
