import { DeleteAlarmsCommandInput, DeleteAlarmsCommandOutput } from "../commands/DeleteAlarmsCommand";
import { DeleteAnomalyDetectorCommandInput, DeleteAnomalyDetectorCommandOutput } from "../commands/DeleteAnomalyDetectorCommand";
import { DeleteDashboardsCommandInput, DeleteDashboardsCommandOutput } from "../commands/DeleteDashboardsCommand";
import { DeleteInsightRulesCommandInput, DeleteInsightRulesCommandOutput } from "../commands/DeleteInsightRulesCommand";
import { DescribeAlarmHistoryCommandInput, DescribeAlarmHistoryCommandOutput } from "../commands/DescribeAlarmHistoryCommand";
import { DescribeAlarmsCommandInput, DescribeAlarmsCommandOutput } from "../commands/DescribeAlarmsCommand";
import { DescribeAlarmsForMetricCommandInput, DescribeAlarmsForMetricCommandOutput } from "../commands/DescribeAlarmsForMetricCommand";
import { DescribeAnomalyDetectorsCommandInput, DescribeAnomalyDetectorsCommandOutput } from "../commands/DescribeAnomalyDetectorsCommand";
import { DescribeInsightRulesCommandInput, DescribeInsightRulesCommandOutput } from "../commands/DescribeInsightRulesCommand";
import { DisableAlarmActionsCommandInput, DisableAlarmActionsCommandOutput } from "../commands/DisableAlarmActionsCommand";
import { DisableInsightRulesCommandInput, DisableInsightRulesCommandOutput } from "../commands/DisableInsightRulesCommand";
import { EnableAlarmActionsCommandInput, EnableAlarmActionsCommandOutput } from "../commands/EnableAlarmActionsCommand";
import { EnableInsightRulesCommandInput, EnableInsightRulesCommandOutput } from "../commands/EnableInsightRulesCommand";
import { GetDashboardCommandInput, GetDashboardCommandOutput } from "../commands/GetDashboardCommand";
import { GetInsightRuleReportCommandInput, GetInsightRuleReportCommandOutput } from "../commands/GetInsightRuleReportCommand";
import { GetMetricDataCommandInput, GetMetricDataCommandOutput } from "../commands/GetMetricDataCommand";
import { GetMetricStatisticsCommandInput, GetMetricStatisticsCommandOutput } from "../commands/GetMetricStatisticsCommand";
import { GetMetricWidgetImageCommandInput, GetMetricWidgetImageCommandOutput } from "../commands/GetMetricWidgetImageCommand";
import { ListDashboardsCommandInput, ListDashboardsCommandOutput } from "../commands/ListDashboardsCommand";
import { ListMetricsCommandInput, ListMetricsCommandOutput } from "../commands/ListMetricsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { PutAnomalyDetectorCommandInput, PutAnomalyDetectorCommandOutput } from "../commands/PutAnomalyDetectorCommand";
import { PutDashboardCommandInput, PutDashboardCommandOutput } from "../commands/PutDashboardCommand";
import { PutInsightRuleCommandInput, PutInsightRuleCommandOutput } from "../commands/PutInsightRuleCommand";
import { PutMetricAlarmCommandInput, PutMetricAlarmCommandOutput } from "../commands/PutMetricAlarmCommand";
import { PutMetricDataCommandInput, PutMetricDataCommandOutput } from "../commands/PutMetricDataCommand";
import { SetAlarmStateCommandInput, SetAlarmStateCommandOutput } from "../commands/SetAlarmStateCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryDeleteAlarmsCommand(input: DeleteAlarmsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteAnomalyDetectorCommand(input: DeleteAnomalyDetectorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteDashboardsCommand(input: DeleteDashboardsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteInsightRulesCommand(input: DeleteInsightRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAlarmHistoryCommand(input: DescribeAlarmHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAlarmsCommand(input: DescribeAlarmsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAlarmsForMetricCommand(input: DescribeAlarmsForMetricCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeAnomalyDetectorsCommand(input: DescribeAnomalyDetectorsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeInsightRulesCommand(input: DescribeInsightRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDisableAlarmActionsCommand(input: DisableAlarmActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDisableInsightRulesCommand(input: DisableInsightRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryEnableAlarmActionsCommand(input: EnableAlarmActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryEnableInsightRulesCommand(input: EnableInsightRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetDashboardCommand(input: GetDashboardCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetInsightRuleReportCommand(input: GetInsightRuleReportCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetMetricDataCommand(input: GetMetricDataCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetMetricStatisticsCommand(input: GetMetricStatisticsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetMetricWidgetImageCommand(input: GetMetricWidgetImageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListDashboardsCommand(input: ListDashboardsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListMetricsCommand(input: ListMetricsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPutAnomalyDetectorCommand(input: PutAnomalyDetectorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPutDashboardCommand(input: PutDashboardCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPutInsightRuleCommand(input: PutInsightRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPutMetricAlarmCommand(input: PutMetricAlarmCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPutMetricDataCommand(input: PutMetricDataCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetAlarmStateCommand(input: SetAlarmStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryTagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryDeleteAlarmsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAlarmsCommandOutput>;
export declare function deserializeAws_queryDeleteAnomalyDetectorCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAnomalyDetectorCommandOutput>;
export declare function deserializeAws_queryDeleteDashboardsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDashboardsCommandOutput>;
export declare function deserializeAws_queryDeleteInsightRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInsightRulesCommandOutput>;
export declare function deserializeAws_queryDescribeAlarmHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAlarmHistoryCommandOutput>;
export declare function deserializeAws_queryDescribeAlarmsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAlarmsCommandOutput>;
export declare function deserializeAws_queryDescribeAlarmsForMetricCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAlarmsForMetricCommandOutput>;
export declare function deserializeAws_queryDescribeAnomalyDetectorsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAnomalyDetectorsCommandOutput>;
export declare function deserializeAws_queryDescribeInsightRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInsightRulesCommandOutput>;
export declare function deserializeAws_queryDisableAlarmActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableAlarmActionsCommandOutput>;
export declare function deserializeAws_queryDisableInsightRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableInsightRulesCommandOutput>;
export declare function deserializeAws_queryEnableAlarmActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableAlarmActionsCommandOutput>;
export declare function deserializeAws_queryEnableInsightRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<EnableInsightRulesCommandOutput>;
export declare function deserializeAws_queryGetDashboardCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDashboardCommandOutput>;
export declare function deserializeAws_queryGetInsightRuleReportCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInsightRuleReportCommandOutput>;
export declare function deserializeAws_queryGetMetricDataCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMetricDataCommandOutput>;
export declare function deserializeAws_queryGetMetricStatisticsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMetricStatisticsCommandOutput>;
export declare function deserializeAws_queryGetMetricWidgetImageCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMetricWidgetImageCommandOutput>;
export declare function deserializeAws_queryListDashboardsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDashboardsCommandOutput>;
export declare function deserializeAws_queryListMetricsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListMetricsCommandOutput>;
export declare function deserializeAws_queryListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_queryPutAnomalyDetectorCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutAnomalyDetectorCommandOutput>;
export declare function deserializeAws_queryPutDashboardCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutDashboardCommandOutput>;
export declare function deserializeAws_queryPutInsightRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutInsightRuleCommandOutput>;
export declare function deserializeAws_queryPutMetricAlarmCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutMetricAlarmCommandOutput>;
export declare function deserializeAws_queryPutMetricDataCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutMetricDataCommandOutput>;
export declare function deserializeAws_querySetAlarmStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetAlarmStateCommandOutput>;
export declare function deserializeAws_queryTagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_queryUntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
