// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AllQueryStringTypes$,
  AllQueryStringTypesCommand,
  ConstantAndVariableQueryString$,
  ConstantAndVariableQueryStringCommand,
  ConstantQueryString$,
  ConstantQueryStringCommand,
  ContentTypeParameters$,
  ContentTypeParametersCommand,
  DatetimeOffsets$,
  DatetimeOffsetsCommand,
  DocumentType$,
  DocumentTypeAsMapValue$,
  DocumentTypeAsMapValueCommand,
  DocumentTypeAsPayload$,
  DocumentTypeAsPayloadCommand,
  DocumentTypeCommand,
  DuplexStream$,
  DuplexStreamCommand,
  DuplexStreamWithDistinctStreams$,
  DuplexStreamWithDistinctStreamsCommand,
  DuplexStreamWithInitialMessages$,
  DuplexStreamWithInitialMessagesCommand,
  EmptyInputAndEmptyOutput$,
  EmptyInputAndEmptyOutputCommand,
  EndpointOperation$,
  EndpointOperationCommand,
  EndpointWithHostLabelOperation$,
  EndpointWithHostLabelOperationCommand,
  FractionalSeconds$,
  FractionalSecondsCommand,
  GreetingWithErrors$,
  GreetingWithErrorsCommand,
  HostWithPathOperation$,
  HostWithPathOperationCommand,
  HttpChecksumRequired$,
  HttpChecksumRequiredCommand,
  HttpEmptyPrefixHeaders$,
  HttpEmptyPrefixHeadersCommand,
  HttpEnumPayload$,
  HttpEnumPayloadCommand,
  HttpPayloadTraits$,
  HttpPayloadTraitsCommand,
  HttpPayloadTraitsWithMediaType$,
  HttpPayloadTraitsWithMediaTypeCommand,
  HttpPayloadWithStructure$,
  HttpPayloadWithStructureCommand,
  HttpPayloadWithUnion$,
  HttpPayloadWithUnionCommand,
  HttpPrefixHeaders$,
  HttpPrefixHeadersCommand,
  HttpPrefixHeadersInResponse$,
  HttpPrefixHeadersInResponseCommand,
  HttpQueryParamsOnlyOperation$,
  HttpQueryParamsOnlyOperationCommand,
  HttpRequestWithFloatLabels$,
  HttpRequestWithFloatLabelsCommand,
  HttpRequestWithGreedyLabelInPath$,
  HttpRequestWithGreedyLabelInPathCommand,
  HttpRequestWithLabels$,
  HttpRequestWithLabelsAndTimestampFormat$,
  HttpRequestWithLabelsAndTimestampFormatCommand,
  HttpRequestWithLabelsCommand,
  HttpRequestWithRegexLiteral$,
  HttpRequestWithRegexLiteralCommand,
  HttpResponseCode$,
  HttpResponseCodeCommand,
  HttpStringPayload$,
  HttpStringPayloadCommand,
  IgnoreQueryParamsInResponse$,
  IgnoreQueryParamsInResponseCommand,
  InputAndOutputWithHeaders$,
  InputAndOutputWithHeadersCommand,
  InputStream$,
  InputStreamCommand,
  InputStreamWithInitialRequest$,
  InputStreamWithInitialRequestCommand,
  JsonBlobs$,
  JsonBlobsCommand,
  JsonEnums$,
  JsonEnumsCommand,
  JsonIntEnums$,
  JsonIntEnumsCommand,
  JsonLists$,
  JsonListsCommand,
  JsonMaps$,
  JsonMapsCommand,
  JsonTimestamps$,
  JsonTimestampsCommand,
  JsonUnions$,
  JsonUnionsCommand,
  MalformedAcceptWithBody$,
  MalformedAcceptWithBodyCommand,
  MalformedAcceptWithGenericString$,
  MalformedAcceptWithGenericStringCommand,
  MalformedAcceptWithPayload$,
  MalformedAcceptWithPayloadCommand,
  MalformedBlob$,
  MalformedBlobCommand,
  MalformedBoolean$,
  MalformedBooleanCommand,
  MalformedByte$,
  MalformedByteCommand,
  MalformedContentTypeWithBody$,
  MalformedContentTypeWithBodyCommand,
  MalformedContentTypeWithGenericString$,
  MalformedContentTypeWithGenericStringCommand,
  MalformedContentTypeWithoutBody$,
  MalformedContentTypeWithoutBodyCommand,
  MalformedContentTypeWithoutBodyEmptyInput$,
  MalformedContentTypeWithoutBodyEmptyInputCommand,
  MalformedContentTypeWithPayload$,
  MalformedContentTypeWithPayloadCommand,
  MalformedDouble$,
  MalformedDoubleCommand,
  MalformedFloat$,
  MalformedFloatCommand,
  MalformedInteger$,
  MalformedIntegerCommand,
  MalformedList$,
  MalformedListCommand,
  MalformedLong$,
  MalformedLongCommand,
  MalformedMap$,
  MalformedMapCommand,
  MalformedRequestBody$,
  MalformedRequestBodyCommand,
  MalformedShort$,
  MalformedShortCommand,
  MalformedString$,
  MalformedStringCommand,
  MalformedTimestampBodyDateTime$,
  MalformedTimestampBodyDateTimeCommand,
  MalformedTimestampBodyDefault$,
  MalformedTimestampBodyDefaultCommand,
  MalformedTimestampBodyHttpDate$,
  MalformedTimestampBodyHttpDateCommand,
  MalformedTimestampHeaderDateTime$,
  MalformedTimestampHeaderDateTimeCommand,
  MalformedTimestampHeaderDefault$,
  MalformedTimestampHeaderDefaultCommand,
  MalformedTimestampHeaderEpoch$,
  MalformedTimestampHeaderEpochCommand,
  MalformedTimestampPathDefault$,
  MalformedTimestampPathDefaultCommand,
  MalformedTimestampPathEpoch$,
  MalformedTimestampPathEpochCommand,
  MalformedTimestampPathHttpDate$,
  MalformedTimestampPathHttpDateCommand,
  MalformedTimestampQueryDefault$,
  MalformedTimestampQueryDefaultCommand,
  MalformedTimestampQueryEpoch$,
  MalformedTimestampQueryEpochCommand,
  MalformedTimestampQueryHttpDate$,
  MalformedTimestampQueryHttpDateCommand,
  MalformedUnion$,
  MalformedUnionCommand,
  MediaTypeHeader$,
  MediaTypeHeaderCommand,
  NoInputAndNoOutput$,
  NoInputAndNoOutputCommand,
  NoInputAndOutput$,
  NoInputAndOutputCommand,
  NullAndEmptyHeadersClient$,
  NullAndEmptyHeadersClientCommand,
  NullAndEmptyHeadersServer$,
  NullAndEmptyHeadersServerCommand,
  OmitsNullSerializesEmptyString$,
  OmitsNullSerializesEmptyStringCommand,
  OmitsSerializingEmptyLists$,
  OmitsSerializingEmptyListsCommand,
  OperationWithDefaults$,
  OperationWithDefaultsCommand,
  OperationWithNestedStructure$,
  OperationWithNestedStructureCommand,
  OutputStream$,
  OutputStreamCommand,
  OutputStreamWithInitialResponse$,
  OutputStreamWithInitialResponseCommand,
  PostPlayerAction$,
  PostPlayerActionCommand,
  PostUnionWithJsonName$,
  PostUnionWithJsonNameCommand,
  PutWithContentEncoding$,
  PutWithContentEncodingCommand,
  QueryIdempotencyTokenAutoFill$,
  QueryIdempotencyTokenAutoFillCommand,
  QueryParamsAsStringListMap$,
  QueryParamsAsStringListMapCommand,
  QueryPrecedence$,
  QueryPrecedenceCommand,
  RecursiveShapes$,
  RecursiveShapesCommand,
  ResponseCodeHttpFallback$,
  ResponseCodeHttpFallbackCommand,
  ResponseCodeRequired$,
  ResponseCodeRequiredCommand,
  RestJsonProtocolClient,
  SimpleScalarProperties$,
  SimpleScalarPropertiesCommand,
  SparseJsonLists$,
  SparseJsonListsCommand,
  SparseJsonMaps$,
  SparseJsonMapsCommand,
  StreamingTraits$,
  StreamingTraitsCommand,
  StreamingTraitsRequireLength$,
  StreamingTraitsRequireLengthCommand,
  StreamingTraitsWithMediaType$,
  StreamingTraitsWithMediaTypeCommand,
  TestBodyStructure$,
  TestBodyStructureCommand,
  TestGetNoInputNoPayload$,
  TestGetNoInputNoPayloadCommand,
  TestGetNoPayload$,
  TestGetNoPayloadCommand,
  TestPayloadBlob$,
  TestPayloadBlobCommand,
  TestPayloadStructure$,
  TestPayloadStructureCommand,
  TestPostNoInputNoPayload$,
  TestPostNoInputNoPayloadCommand,
  TestPostNoPayload$,
  TestPostNoPayloadCommand,
  TimestampFormatHeaders$,
  TimestampFormatHeadersCommand,
  UnitInputAndOutput$,
  UnitInputAndOutputCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = RestJsonProtocolClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("RestJsonProtocolClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas:
      new Map<any, any>([
        [AllQueryStringTypes$, AllQueryStringTypesCommand],
        [ConstantAndVariableQueryString$, ConstantAndVariableQueryStringCommand],
        [ConstantQueryString$, ConstantQueryStringCommand],
        [ContentTypeParameters$, ContentTypeParametersCommand],
        [DatetimeOffsets$, DatetimeOffsetsCommand],
        [DocumentType$, DocumentTypeCommand],
        [DocumentTypeAsMapValue$, DocumentTypeAsMapValueCommand],
        [DocumentTypeAsPayload$, DocumentTypeAsPayloadCommand],
        [DuplexStream$, DuplexStreamCommand],
        [DuplexStreamWithDistinctStreams$, DuplexStreamWithDistinctStreamsCommand],
        [DuplexStreamWithInitialMessages$, DuplexStreamWithInitialMessagesCommand],
        [EmptyInputAndEmptyOutput$, EmptyInputAndEmptyOutputCommand],
        [EndpointOperation$, EndpointOperationCommand],
        [EndpointWithHostLabelOperation$, EndpointWithHostLabelOperationCommand],
        [FractionalSeconds$, FractionalSecondsCommand],
        [GreetingWithErrors$, GreetingWithErrorsCommand],
        [HostWithPathOperation$, HostWithPathOperationCommand],
        [HttpChecksumRequired$, HttpChecksumRequiredCommand],
        [HttpEmptyPrefixHeaders$, HttpEmptyPrefixHeadersCommand],
        [HttpEnumPayload$, HttpEnumPayloadCommand],
        [HttpPayloadTraits$, HttpPayloadTraitsCommand],
        [HttpPayloadTraitsWithMediaType$, HttpPayloadTraitsWithMediaTypeCommand],
        [HttpPayloadWithStructure$, HttpPayloadWithStructureCommand],
        [HttpPayloadWithUnion$, HttpPayloadWithUnionCommand],
        [HttpPrefixHeaders$, HttpPrefixHeadersCommand],
        [HttpPrefixHeadersInResponse$, HttpPrefixHeadersInResponseCommand],
        [HttpQueryParamsOnlyOperation$, HttpQueryParamsOnlyOperationCommand],
        [HttpRequestWithFloatLabels$, HttpRequestWithFloatLabelsCommand],
        [HttpRequestWithGreedyLabelInPath$, HttpRequestWithGreedyLabelInPathCommand],
        [HttpRequestWithLabels$, HttpRequestWithLabelsCommand],
        [HttpRequestWithLabelsAndTimestampFormat$, HttpRequestWithLabelsAndTimestampFormatCommand],
        [HttpRequestWithRegexLiteral$, HttpRequestWithRegexLiteralCommand],
        [HttpResponseCode$, HttpResponseCodeCommand],
        [HttpStringPayload$, HttpStringPayloadCommand],
        [IgnoreQueryParamsInResponse$, IgnoreQueryParamsInResponseCommand],
        [InputAndOutputWithHeaders$, InputAndOutputWithHeadersCommand],
        [InputStream$, InputStreamCommand],
        [InputStreamWithInitialRequest$, InputStreamWithInitialRequestCommand],
        [JsonBlobs$, JsonBlobsCommand],
        [JsonEnums$, JsonEnumsCommand],
        [JsonIntEnums$, JsonIntEnumsCommand],
        [JsonLists$, JsonListsCommand],
        [JsonMaps$, JsonMapsCommand],
        [JsonTimestamps$, JsonTimestampsCommand],
        [JsonUnions$, JsonUnionsCommand],
        [MalformedAcceptWithBody$, MalformedAcceptWithBodyCommand],
        [MalformedAcceptWithGenericString$, MalformedAcceptWithGenericStringCommand],
        [MalformedAcceptWithPayload$, MalformedAcceptWithPayloadCommand],
        [MalformedBlob$, MalformedBlobCommand],
        [MalformedBoolean$, MalformedBooleanCommand],
        [MalformedByte$, MalformedByteCommand],
        [MalformedContentTypeWithBody$, MalformedContentTypeWithBodyCommand],
        [MalformedContentTypeWithGenericString$, MalformedContentTypeWithGenericStringCommand],
        [MalformedContentTypeWithoutBody$, MalformedContentTypeWithoutBodyCommand],
        [MalformedContentTypeWithoutBodyEmptyInput$, MalformedContentTypeWithoutBodyEmptyInputCommand],
        [MalformedContentTypeWithPayload$, MalformedContentTypeWithPayloadCommand],
        [MalformedDouble$, MalformedDoubleCommand],
        [MalformedFloat$, MalformedFloatCommand],
        [MalformedInteger$, MalformedIntegerCommand],
        [MalformedList$, MalformedListCommand],
        [MalformedLong$, MalformedLongCommand],
        [MalformedMap$, MalformedMapCommand],
        [MalformedRequestBody$, MalformedRequestBodyCommand],
        [MalformedShort$, MalformedShortCommand],
        [MalformedString$, MalformedStringCommand],
        [MalformedTimestampBodyDateTime$, MalformedTimestampBodyDateTimeCommand],
        [MalformedTimestampBodyDefault$, MalformedTimestampBodyDefaultCommand],
        [MalformedTimestampBodyHttpDate$, MalformedTimestampBodyHttpDateCommand],
        [MalformedTimestampHeaderDateTime$, MalformedTimestampHeaderDateTimeCommand],
        [MalformedTimestampHeaderDefault$, MalformedTimestampHeaderDefaultCommand],
        [MalformedTimestampHeaderEpoch$, MalformedTimestampHeaderEpochCommand],
        [MalformedTimestampPathDefault$, MalformedTimestampPathDefaultCommand],
        [MalformedTimestampPathEpoch$, MalformedTimestampPathEpochCommand],
        [MalformedTimestampPathHttpDate$, MalformedTimestampPathHttpDateCommand],
        [MalformedTimestampQueryDefault$, MalformedTimestampQueryDefaultCommand],
        [MalformedTimestampQueryEpoch$, MalformedTimestampQueryEpochCommand],
        [MalformedTimestampQueryHttpDate$, MalformedTimestampQueryHttpDateCommand],
        [MalformedUnion$, MalformedUnionCommand],
        [MediaTypeHeader$, MediaTypeHeaderCommand],
        [NoInputAndNoOutput$, NoInputAndNoOutputCommand],
        [NoInputAndOutput$, NoInputAndOutputCommand],
        [NullAndEmptyHeadersClient$, NullAndEmptyHeadersClientCommand],
        [NullAndEmptyHeadersServer$, NullAndEmptyHeadersServerCommand],
        [OmitsNullSerializesEmptyString$, OmitsNullSerializesEmptyStringCommand],
        [OmitsSerializingEmptyLists$, OmitsSerializingEmptyListsCommand],
        [OperationWithDefaults$, OperationWithDefaultsCommand],
        [OperationWithNestedStructure$, OperationWithNestedStructureCommand],
        [OutputStream$, OutputStreamCommand],
        [OutputStreamWithInitialResponse$, OutputStreamWithInitialResponseCommand],
        [PostPlayerAction$, PostPlayerActionCommand],
        [PostUnionWithJsonName$, PostUnionWithJsonNameCommand],
        [PutWithContentEncoding$, PutWithContentEncodingCommand],
        [QueryIdempotencyTokenAutoFill$, QueryIdempotencyTokenAutoFillCommand],
        [QueryParamsAsStringListMap$, QueryParamsAsStringListMapCommand],
        [QueryPrecedence$, QueryPrecedenceCommand],
        [RecursiveShapes$, RecursiveShapesCommand],
        [ResponseCodeHttpFallback$, ResponseCodeHttpFallbackCommand],
        [ResponseCodeRequired$, ResponseCodeRequiredCommand],
        [SimpleScalarProperties$, SimpleScalarPropertiesCommand],
        [SparseJsonLists$, SparseJsonListsCommand],
        [SparseJsonMaps$, SparseJsonMapsCommand],
        [StreamingTraits$, StreamingTraitsCommand],
        [StreamingTraitsRequireLength$, StreamingTraitsRequireLengthCommand],
        [StreamingTraitsWithMediaType$, StreamingTraitsWithMediaTypeCommand],
        [TestBodyStructure$, TestBodyStructureCommand],
        [TestGetNoInputNoPayload$, TestGetNoInputNoPayloadCommand],
        [TestGetNoPayload$, TestGetNoPayloadCommand],
        [TestPayloadBlob$, TestPayloadBlobCommand],
        [TestPayloadStructure$, TestPayloadStructureCommand],
        [TestPostNoInputNoPayload$, TestPostNoInputNoPayloadCommand],
        [TestPostNoPayload$, TestPostNoPayloadCommand],
        [TimestampFormatHeaders$, TimestampFormatHeadersCommand],
        [UnitInputAndOutput$, UnitInputAndOutputCommand],
      ]),

  });

  runner.run();
}, 30_000);
