import { CreateHttpNamespaceCommandInput, CreateHttpNamespaceCommandOutput } from "../commands/CreateHttpNamespaceCommand";
import { CreatePrivateDnsNamespaceCommandInput, CreatePrivateDnsNamespaceCommandOutput } from "../commands/CreatePrivateDnsNamespaceCommand";
import { CreatePublicDnsNamespaceCommandInput, CreatePublicDnsNamespaceCommandOutput } from "../commands/CreatePublicDnsNamespaceCommand";
import { CreateServiceCommandInput, CreateServiceCommandOutput } from "../commands/CreateServiceCommand";
import { DeleteNamespaceCommandInput, DeleteNamespaceCommandOutput } from "../commands/DeleteNamespaceCommand";
import { DeleteServiceCommandInput, DeleteServiceCommandOutput } from "../commands/DeleteServiceCommand";
import { DeregisterInstanceCommandInput, DeregisterInstanceCommandOutput } from "../commands/DeregisterInstanceCommand";
import { DiscoverInstancesCommandInput, DiscoverInstancesCommandOutput } from "../commands/DiscoverInstancesCommand";
import { GetInstanceCommandInput, GetInstanceCommandOutput } from "../commands/GetInstanceCommand";
import { GetInstancesHealthStatusCommandInput, GetInstancesHealthStatusCommandOutput } from "../commands/GetInstancesHealthStatusCommand";
import { GetNamespaceCommandInput, GetNamespaceCommandOutput } from "../commands/GetNamespaceCommand";
import { GetOperationCommandInput, GetOperationCommandOutput } from "../commands/GetOperationCommand";
import { GetServiceCommandInput, GetServiceCommandOutput } from "../commands/GetServiceCommand";
import { ListInstancesCommandInput, ListInstancesCommandOutput } from "../commands/ListInstancesCommand";
import { ListNamespacesCommandInput, ListNamespacesCommandOutput } from "../commands/ListNamespacesCommand";
import { ListOperationsCommandInput, ListOperationsCommandOutput } from "../commands/ListOperationsCommand";
import { ListServicesCommandInput, ListServicesCommandOutput } from "../commands/ListServicesCommand";
import { RegisterInstanceCommandInput, RegisterInstanceCommandOutput } from "../commands/RegisterInstanceCommand";
import { UpdateInstanceCustomHealthStatusCommandInput, UpdateInstanceCustomHealthStatusCommandOutput } from "../commands/UpdateInstanceCustomHealthStatusCommand";
import { UpdateServiceCommandInput, UpdateServiceCommandOutput } from "../commands/UpdateServiceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateHttpNamespaceCommand(input: CreateHttpNamespaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePrivateDnsNamespaceCommand(input: CreatePrivateDnsNamespaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePublicDnsNamespaceCommand(input: CreatePublicDnsNamespaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateServiceCommand(input: CreateServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteNamespaceCommand(input: DeleteNamespaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteServiceCommand(input: DeleteServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterInstanceCommand(input: DeregisterInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DiscoverInstancesCommand(input: DiscoverInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstanceCommand(input: GetInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetInstancesHealthStatusCommand(input: GetInstancesHealthStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetNamespaceCommand(input: GetNamespaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetOperationCommand(input: GetOperationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetServiceCommand(input: GetServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListInstancesCommand(input: ListInstancesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListNamespacesCommand(input: ListNamespacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListOperationsCommand(input: ListOperationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListServicesCommand(input: ListServicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterInstanceCommand(input: RegisterInstanceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateInstanceCustomHealthStatusCommand(input: UpdateInstanceCustomHealthStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateServiceCommand(input: UpdateServiceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateHttpNamespaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateHttpNamespaceCommandOutput>;
export declare function deserializeAws_json1_1CreatePrivateDnsNamespaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePrivateDnsNamespaceCommandOutput>;
export declare function deserializeAws_json1_1CreatePublicDnsNamespaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePublicDnsNamespaceCommandOutput>;
export declare function deserializeAws_json1_1CreateServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateServiceCommandOutput>;
export declare function deserializeAws_json1_1DeleteNamespaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteNamespaceCommandOutput>;
export declare function deserializeAws_json1_1DeleteServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteServiceCommandOutput>;
export declare function deserializeAws_json1_1DeregisterInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterInstanceCommandOutput>;
export declare function deserializeAws_json1_1DiscoverInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DiscoverInstancesCommandOutput>;
export declare function deserializeAws_json1_1GetInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstanceCommandOutput>;
export declare function deserializeAws_json1_1GetInstancesHealthStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetInstancesHealthStatusCommandOutput>;
export declare function deserializeAws_json1_1GetNamespaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetNamespaceCommandOutput>;
export declare function deserializeAws_json1_1GetOperationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetOperationCommandOutput>;
export declare function deserializeAws_json1_1GetServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetServiceCommandOutput>;
export declare function deserializeAws_json1_1ListInstancesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListInstancesCommandOutput>;
export declare function deserializeAws_json1_1ListNamespacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListNamespacesCommandOutput>;
export declare function deserializeAws_json1_1ListOperationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOperationsCommandOutput>;
export declare function deserializeAws_json1_1ListServicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListServicesCommandOutput>;
export declare function deserializeAws_json1_1RegisterInstanceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterInstanceCommandOutput>;
export declare function deserializeAws_json1_1UpdateInstanceCustomHealthStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateInstanceCustomHealthStatusCommandOutput>;
export declare function deserializeAws_json1_1UpdateServiceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateServiceCommandOutput>;
