// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AccountSendingPausedException$,
  AlreadyExistsException$,
  CannotDeleteException$,
  CloneReceiptRuleSet$,
  CloneReceiptRuleSetCommand,
  ConfigurationSetAlreadyExistsException$,
  ConfigurationSetDoesNotExistException$,
  ConfigurationSetSendingPausedException$,
  CreateConfigurationSet$,
  CreateConfigurationSetCommand,
  CreateConfigurationSetEventDestination$,
  CreateConfigurationSetEventDestinationCommand,
  CreateConfigurationSetTrackingOptions$,
  CreateConfigurationSetTrackingOptionsCommand,
  CreateCustomVerificationEmailTemplate$,
  CreateCustomVerificationEmailTemplateCommand,
  CreateReceiptFilter$,
  CreateReceiptFilterCommand,
  CreateReceiptRule$,
  CreateReceiptRuleCommand,
  CreateReceiptRuleSet$,
  CreateReceiptRuleSetCommand,
  CreateTemplate$,
  CreateTemplateCommand,
  CustomVerificationEmailInvalidContentException$,
  CustomVerificationEmailTemplateAlreadyExistsException$,
  CustomVerificationEmailTemplateDoesNotExistException$,
  DeleteConfigurationSet$,
  DeleteConfigurationSetCommand,
  DeleteConfigurationSetEventDestination$,
  DeleteConfigurationSetEventDestinationCommand,
  DeleteConfigurationSetTrackingOptions$,
  DeleteConfigurationSetTrackingOptionsCommand,
  DeleteCustomVerificationEmailTemplate$,
  DeleteCustomVerificationEmailTemplateCommand,
  DeleteIdentity$,
  DeleteIdentityCommand,
  DeleteIdentityPolicy$,
  DeleteIdentityPolicyCommand,
  DeleteReceiptFilter$,
  DeleteReceiptFilterCommand,
  DeleteReceiptRule$,
  DeleteReceiptRuleCommand,
  DeleteReceiptRuleSet$,
  DeleteReceiptRuleSetCommand,
  DeleteTemplate$,
  DeleteTemplateCommand,
  DeleteVerifiedEmailAddress$,
  DeleteVerifiedEmailAddressCommand,
  DescribeActiveReceiptRuleSet$,
  DescribeActiveReceiptRuleSetCommand,
  DescribeConfigurationSet$,
  DescribeConfigurationSetCommand,
  DescribeReceiptRule$,
  DescribeReceiptRuleCommand,
  DescribeReceiptRuleSet$,
  DescribeReceiptRuleSetCommand,
  EventDestinationAlreadyExistsException$,
  EventDestinationDoesNotExistException$,
  FromEmailAddressNotVerifiedException$,
  GetAccountSendingEnabled$,
  GetAccountSendingEnabledCommand,
  GetCustomVerificationEmailTemplate$,
  GetCustomVerificationEmailTemplateCommand,
  GetIdentityDkimAttributes$,
  GetIdentityDkimAttributesCommand,
  GetIdentityMailFromDomainAttributes$,
  GetIdentityMailFromDomainAttributesCommand,
  GetIdentityNotificationAttributes$,
  GetIdentityNotificationAttributesCommand,
  GetIdentityPolicies$,
  GetIdentityPoliciesCommand,
  GetIdentityVerificationAttributes$,
  GetIdentityVerificationAttributesCommand,
  GetSendQuota$,
  GetSendQuotaCommand,
  GetSendStatistics$,
  GetSendStatisticsCommand,
  GetTemplate$,
  GetTemplateCommand,
  InvalidCloudWatchDestinationException$,
  InvalidConfigurationSetException$,
  InvalidDeliveryOptionsException$,
  InvalidFirehoseDestinationException$,
  InvalidLambdaFunctionException$,
  InvalidPolicyException$,
  InvalidRenderingParameterException$,
  InvalidS3ConfigurationException$,
  InvalidSNSDestinationException$,
  InvalidSnsTopicException$,
  InvalidTemplateException$,
  InvalidTrackingOptionsException$,
  LimitExceededException$,
  ListConfigurationSets$,
  ListConfigurationSetsCommand,
  ListCustomVerificationEmailTemplates$,
  ListCustomVerificationEmailTemplatesCommand,
  ListIdentities$,
  ListIdentitiesCommand,
  ListIdentityPolicies$,
  ListIdentityPoliciesCommand,
  ListReceiptFilters$,
  ListReceiptFiltersCommand,
  ListReceiptRuleSets$,
  ListReceiptRuleSetsCommand,
  ListTemplates$,
  ListTemplatesCommand,
  ListVerifiedEmailAddresses$,
  ListVerifiedEmailAddressesCommand,
  MailFromDomainNotVerifiedException$,
  MessageRejected$,
  MissingRenderingAttributeException$,
  ProductionAccessNotGrantedException$,
  PutConfigurationSetDeliveryOptions$,
  PutConfigurationSetDeliveryOptionsCommand,
  PutIdentityPolicy$,
  PutIdentityPolicyCommand,
  ReorderReceiptRuleSet$,
  ReorderReceiptRuleSetCommand,
  RuleDoesNotExistException$,
  RuleSetDoesNotExistException$,
  SendBounce$,
  SendBounceCommand,
  SendBulkTemplatedEmail$,
  SendBulkTemplatedEmailCommand,
  SendCustomVerificationEmail$,
  SendCustomVerificationEmailCommand,
  SendEmail$,
  SendEmailCommand,
  SendRawEmail$,
  SendRawEmailCommand,
  SendTemplatedEmail$,
  SendTemplatedEmailCommand,
  SESClient,
  SetActiveReceiptRuleSet$,
  SetActiveReceiptRuleSetCommand,
  SetIdentityDkimEnabled$,
  SetIdentityDkimEnabledCommand,
  SetIdentityFeedbackForwardingEnabled$,
  SetIdentityFeedbackForwardingEnabledCommand,
  SetIdentityHeadersInNotificationsEnabled$,
  SetIdentityHeadersInNotificationsEnabledCommand,
  SetIdentityMailFromDomain$,
  SetIdentityMailFromDomainCommand,
  SetIdentityNotificationTopic$,
  SetIdentityNotificationTopicCommand,
  SetReceiptRulePosition$,
  SetReceiptRulePositionCommand,
  TemplateDoesNotExistException$,
  TestRenderTemplate$,
  TestRenderTemplateCommand,
  TrackingOptionsAlreadyExistsException$,
  TrackingOptionsDoesNotExistException$,
  UpdateAccountSendingEnabled$,
  UpdateAccountSendingEnabledCommand,
  UpdateConfigurationSetEventDestination$,
  UpdateConfigurationSetEventDestinationCommand,
  UpdateConfigurationSetReputationMetricsEnabled$,
  UpdateConfigurationSetReputationMetricsEnabledCommand,
  UpdateConfigurationSetSendingEnabled$,
  UpdateConfigurationSetSendingEnabledCommand,
  UpdateConfigurationSetTrackingOptions$,
  UpdateConfigurationSetTrackingOptionsCommand,
  UpdateCustomVerificationEmailTemplate$,
  UpdateCustomVerificationEmailTemplateCommand,
  UpdateReceiptRule$,
  UpdateReceiptRuleCommand,
  UpdateTemplate$,
  UpdateTemplateCommand,
  VerifyDomainDkim$,
  VerifyDomainDkimCommand,
  VerifyDomainIdentity$,
  VerifyDomainIdentityCommand,
  VerifyEmailAddress$,
  VerifyEmailAddressCommand,
  VerifyEmailIdentity$,
  VerifyEmailIdentityCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = SESClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("SESClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [CloneReceiptRuleSet$, CloneReceiptRuleSetCommand],
      [CreateConfigurationSet$, CreateConfigurationSetCommand],
      [CreateConfigurationSetEventDestination$, CreateConfigurationSetEventDestinationCommand],
      [CreateConfigurationSetTrackingOptions$, CreateConfigurationSetTrackingOptionsCommand],
      [CreateCustomVerificationEmailTemplate$, CreateCustomVerificationEmailTemplateCommand],
      [CreateReceiptFilter$, CreateReceiptFilterCommand],
      [CreateReceiptRule$, CreateReceiptRuleCommand],
      [CreateReceiptRuleSet$, CreateReceiptRuleSetCommand],
      [CreateTemplate$, CreateTemplateCommand],
      [DeleteConfigurationSet$, DeleteConfigurationSetCommand],
      [DeleteConfigurationSetEventDestination$, DeleteConfigurationSetEventDestinationCommand],
      [DeleteConfigurationSetTrackingOptions$, DeleteConfigurationSetTrackingOptionsCommand],
      [DeleteCustomVerificationEmailTemplate$, DeleteCustomVerificationEmailTemplateCommand],
      [DeleteIdentity$, DeleteIdentityCommand],
      [DeleteIdentityPolicy$, DeleteIdentityPolicyCommand],
      [DeleteReceiptFilter$, DeleteReceiptFilterCommand],
      [DeleteReceiptRule$, DeleteReceiptRuleCommand],
      [DeleteReceiptRuleSet$, DeleteReceiptRuleSetCommand],
      [DeleteTemplate$, DeleteTemplateCommand],
      [DeleteVerifiedEmailAddress$, DeleteVerifiedEmailAddressCommand],
      [DescribeActiveReceiptRuleSet$, DescribeActiveReceiptRuleSetCommand],
      [DescribeConfigurationSet$, DescribeConfigurationSetCommand],
      [DescribeReceiptRule$, DescribeReceiptRuleCommand],
      [DescribeReceiptRuleSet$, DescribeReceiptRuleSetCommand],
      [GetAccountSendingEnabled$, GetAccountSendingEnabledCommand],
      [GetCustomVerificationEmailTemplate$, GetCustomVerificationEmailTemplateCommand],
      [GetIdentityDkimAttributes$, GetIdentityDkimAttributesCommand],
      [GetIdentityMailFromDomainAttributes$, GetIdentityMailFromDomainAttributesCommand],
      [GetIdentityNotificationAttributes$, GetIdentityNotificationAttributesCommand],
      [GetIdentityPolicies$, GetIdentityPoliciesCommand],
      [GetIdentityVerificationAttributes$, GetIdentityVerificationAttributesCommand],
      [GetSendQuota$, GetSendQuotaCommand],
      [GetSendStatistics$, GetSendStatisticsCommand],
      [GetTemplate$, GetTemplateCommand],
      [ListConfigurationSets$, ListConfigurationSetsCommand],
      [ListCustomVerificationEmailTemplates$, ListCustomVerificationEmailTemplatesCommand],
      [ListIdentities$, ListIdentitiesCommand],
      [ListIdentityPolicies$, ListIdentityPoliciesCommand],
      [ListReceiptFilters$, ListReceiptFiltersCommand],
      [ListReceiptRuleSets$, ListReceiptRuleSetsCommand],
      [ListTemplates$, ListTemplatesCommand],
      [ListVerifiedEmailAddresses$, ListVerifiedEmailAddressesCommand],
      [PutConfigurationSetDeliveryOptions$, PutConfigurationSetDeliveryOptionsCommand],
      [PutIdentityPolicy$, PutIdentityPolicyCommand],
      [ReorderReceiptRuleSet$, ReorderReceiptRuleSetCommand],
      [SendBounce$, SendBounceCommand],
      [SendBulkTemplatedEmail$, SendBulkTemplatedEmailCommand],
      [SendCustomVerificationEmail$, SendCustomVerificationEmailCommand],
      [SendEmail$, SendEmailCommand],
      [SendRawEmail$, SendRawEmailCommand],
      [SendTemplatedEmail$, SendTemplatedEmailCommand],
      [SetActiveReceiptRuleSet$, SetActiveReceiptRuleSetCommand],
      [SetIdentityDkimEnabled$, SetIdentityDkimEnabledCommand],
      [SetIdentityFeedbackForwardingEnabled$, SetIdentityFeedbackForwardingEnabledCommand],
      [SetIdentityHeadersInNotificationsEnabled$, SetIdentityHeadersInNotificationsEnabledCommand],
      [SetIdentityMailFromDomain$, SetIdentityMailFromDomainCommand],
      [SetIdentityNotificationTopic$, SetIdentityNotificationTopicCommand],
      [SetReceiptRulePosition$, SetReceiptRulePositionCommand],
      [TestRenderTemplate$, TestRenderTemplateCommand],
      [UpdateAccountSendingEnabled$, UpdateAccountSendingEnabledCommand],
      [UpdateConfigurationSetEventDestination$, UpdateConfigurationSetEventDestinationCommand],
      [UpdateConfigurationSetReputationMetricsEnabled$, UpdateConfigurationSetReputationMetricsEnabledCommand],
      [UpdateConfigurationSetSendingEnabled$, UpdateConfigurationSetSendingEnabledCommand],
      [UpdateConfigurationSetTrackingOptions$, UpdateConfigurationSetTrackingOptionsCommand],
      [UpdateCustomVerificationEmailTemplate$, UpdateCustomVerificationEmailTemplateCommand],
      [UpdateReceiptRule$, UpdateReceiptRuleCommand],
      [UpdateTemplate$, UpdateTemplateCommand],
      [VerifyDomainDkim$, VerifyDomainDkimCommand],
      [VerifyDomainIdentity$, VerifyDomainIdentityCommand],
      [VerifyEmailAddress$, VerifyEmailAddressCommand],
      [VerifyEmailIdentity$, VerifyEmailIdentityCommand],
    ]),
    errors: [
      AccountSendingPausedException$,
      AlreadyExistsException$,
      CannotDeleteException$,
      ConfigurationSetAlreadyExistsException$,
      ConfigurationSetDoesNotExistException$,
      ConfigurationSetSendingPausedException$,
      CustomVerificationEmailInvalidContentException$,
      CustomVerificationEmailTemplateAlreadyExistsException$,
      CustomVerificationEmailTemplateDoesNotExistException$,
      EventDestinationAlreadyExistsException$,
      EventDestinationDoesNotExistException$,
      FromEmailAddressNotVerifiedException$,
      InvalidCloudWatchDestinationException$,
      InvalidConfigurationSetException$,
      InvalidDeliveryOptionsException$,
      InvalidFirehoseDestinationException$,
      InvalidLambdaFunctionException$,
      InvalidPolicyException$,
      InvalidRenderingParameterException$,
      InvalidS3ConfigurationException$,
      InvalidSNSDestinationException$,
      InvalidSnsTopicException$,
      InvalidTemplateException$,
      InvalidTrackingOptionsException$,
      LimitExceededException$,
      MailFromDomainNotVerifiedException$,
      MessageRejected$,
      MissingRenderingAttributeException$,
      ProductionAccessNotGrantedException$,
      RuleDoesNotExistException$,
      RuleSetDoesNotExistException$,
      TemplateDoesNotExistException$,
      TrackingOptionsAlreadyExistsException$,
      TrackingOptionsDoesNotExistException$,
    ],
  });
  runner.run();
}, 30_000);
