// smithy-typescript generated code
import { BinaryDecisionDiagram } from "@smithy/core/endpoints";

const v="ref",
w="authSchemes",
x="name",
y="signingRegion";
const a=-1,
b=true,
c="isSet",
d="PartitionResult",
e="stringEquals",
f="booleanEquals",
g="getAttr",
h={[v]:"Endpoint"},
i={"fn":g,"argv":[{[v]:d},"name"]},
j={[v]:d},
k={[w]:[{[x]:"sigv4",[y]:"us-east-1"}]},
l={[w]:[{[x]:"sigv4",[y]:"cn-north-1"}]},
m={[w]:[{[x]:"sigv4",[y]:"us-gov-west-1"}]},
n={[w]:[{[x]:"sigv4",[y]:"us-iso-east-1"}]},
o={[w]:[{[x]:"sigv4",[y]:"us-isob-east-1"}]},
p={[w]:[{[x]:"sigv4",[y]:"eu-isoe-west-1"}]},
q={[w]:[{[x]:"sigv4",[y]:"us-isof-south-1"}]},
s={[w]:[{[x]:"sigv4",[y]:"eusc-de-east-1"}]},
t={[w]:[{[x]:"sigv4",[y]:"{PartitionResult#implicitGlobalRegion}"}]},
u=[{[v]:"Region"}];
const _data={
  conditions: [
    [c,[h]],
    [c,u],
    ["aws.partition",u,d],
    [e,[i,"aws"]],
    [e,[i,"aws-cn"]],
    [e,[i,"aws-us-gov"]],
    [e,[i,"aws-iso"]],
    [f,[{[v]:"UseFIPS"},b]],
    [f,[{[v]:"UseDualStack"},b]],
    [e,[i,"aws-iso-b"]],
    [e,[i,"aws-iso-e"]],
    [e,[i,"aws-iso-f"]],
    [e,[i,"aws-eusc"]],
    [f,[{fn:g,argv:[j,"supportsDualStack"]},b]],
    [f,[{fn:g,argv:[j,"supportsFIPS"]},b]]
  ],
  results: [
    [a],
    [a,"Invalid Configuration: FIPS and custom endpoint are not supported"],
    [a,"Invalid Configuration: Dualstack and custom endpoint are not supported"],
    [h,{}],
    ["https://iam.amazonaws.com",k],
    ["https://iam-fips.amazonaws.com",k],
    ["https://iam.global.api.aws",k],
    ["https://iam-fips.global.api.aws",k],
    ["https://iam.global.api.amazonwebservices.com.cn",l],
    ["https://iam-fips.api.amazonwebservices.com.cn",l],
    ["https://iam.cn-north-1.amazonaws.com.cn",l],
    ["https://iam-fips.amazonaws.com.cn",l],
    ["https://iam.us-gov.api.aws",m],
    ["https://iam.us-gov.amazonaws.com",m],
    ["https://iam.us-iso-east-1.c2s.ic.gov",n],
    ["https://iam-fips.us-iso-east-1.c2s.ic.gov",n],
    ["https://iam.api.aws.ic.gov",n],
    ["https://iam-fips.api.aws.ic.gov",n],
    ["https://iam.us-isob-east-1.sc2s.sgov.gov",o],
    ["https://iam-fips.us-isob-east-1.sc2s.sgov.gov",o],
    ["https://iam.api.aws.scloud",o],
    ["https://iam-fips.api.aws.scloud",o],
    ["https://iam.eu-isoe-west-1.cloud.adc-e.uk",p],
    ["https://iam-fips.cloud.adc-e.uk",p],
    ["https://iam.api.cloud-aws.adc-e.uk",p],
    ["https://iam-fips.api.cloud-aws.adc-e.uk",p],
    ["https://iam.us-isof-south-1.csp.hci.ic.gov",q],
    ["https://iam-fips.csp.hci.ic.gov",q],
    ["https://iam.api.aws.hci.ic.gov",q],
    ["https://iam-fips.api.aws.hci.ic.gov",q],
    ["https://iam.eusc-de-east-1.amazonaws.eu",s],
    ["https://iam-fips.amazonaws.eu",s],
    ["https://iam.global.api.amazonwebservices.eu",s],
    ["https://iam-fips.api.amazonwebservices.eu",s],
    ["https://iam-fips.{PartitionResult#implicitGlobalRegion}.{PartitionResult#dualStackDnsSuffix}",t],
    [a,"FIPS and DualStack are enabled, but this partition does not support one or both"],
    ["https://iam-fips.{PartitionResult#implicitGlobalRegion}.{PartitionResult#dnsSuffix}",t],
    [a,"FIPS is enabled but this partition does not support FIPS"],
    ["https://iam.{PartitionResult#implicitGlobalRegion}.{PartitionResult#dualStackDnsSuffix}",t],
    [a,"DualStack is enabled but this partition does not support DualStack"],
    ["https://iam.{PartitionResult#implicitGlobalRegion}.{PartitionResult#dnsSuffix}",t],
    [a,"Invalid Configuration: Missing Region"]
  ]
};

const root = 2;
const r = 100_000_000;
const nodes = new Int32Array([
  -1, 1, -1,
  0, 42, 3,
  1, 4, r + 41,
  2, 5, r + 41,
  3, 39, 6,
  4, 36, 7,
  5, 35, 8,
  6, 32, 9,
  7, 20, 10,
  8, 15, 11,
  9, r + 18, 12,
  10, r + 22, 13,
  11, r + 26, 14,
  12, r + 30, r + 40,
  9, r + 20, 16,
  10, r + 24, 17,
  11, r + 28, 18,
  12, r + 32, 19,
  13, r + 38, r + 39,
  8, 26, 21,
  9, r + 19, 22,
  10, r + 23, 23,
  11, r + 27, 24,
  12, r + 31, 25,
  14, r + 36, r + 37,
  9, r + 21, 27,
  10, r + 25, 28,
  11, r + 29, 29,
  12, r + 33, 30,
  13, 31, r + 35,
  14, r + 34, r + 35,
  7, 34, 33,
  8, r + 16, r + 14,
  8, r + 17, r + 15,
  8, r + 12, r + 13,
  7, 38, 37,
  8, r + 8, r + 10,
  8, r + 9, r + 11,
  7, 41, 40,
  8, r + 6, r + 4,
  8, r + 7, r + 5,
  7, r + 1, 43,
  8, r + 2, r + 3,
]);
export const bdd = BinaryDecisionDiagram.from(
  nodes, root, _data.conditions, _data.results
);
