import { ClaimDevicesByClaimCodeCommandInput, ClaimDevicesByClaimCodeCommandOutput } from "../commands/ClaimDevicesByClaimCodeCommand";
import { DescribeDeviceCommandInput, DescribeDeviceCommandOutput } from "../commands/DescribeDeviceCommand";
import { FinalizeDeviceClaimCommandInput, FinalizeDeviceClaimCommandOutput } from "../commands/FinalizeDeviceClaimCommand";
import { GetDeviceMethodsCommandInput, GetDeviceMethodsCommandOutput } from "../commands/GetDeviceMethodsCommand";
import { InitiateDeviceClaimCommandInput, InitiateDeviceClaimCommandOutput } from "../commands/InitiateDeviceClaimCommand";
import { InvokeDeviceMethodCommandInput, InvokeDeviceMethodCommandOutput } from "../commands/InvokeDeviceMethodCommand";
import { ListDeviceEventsCommandInput, ListDeviceEventsCommandOutput } from "../commands/ListDeviceEventsCommand";
import { ListDevicesCommandInput, ListDevicesCommandOutput } from "../commands/ListDevicesCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UnclaimDeviceCommandInput, UnclaimDeviceCommandOutput } from "../commands/UnclaimDeviceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateDeviceStateCommandInput, UpdateDeviceStateCommandOutput } from "../commands/UpdateDeviceStateCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restJson1_1ClaimDevicesByClaimCodeCommand(input: ClaimDevicesByClaimCodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeDeviceCommand(input: DescribeDeviceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1FinalizeDeviceClaimCommand(input: FinalizeDeviceClaimCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1GetDeviceMethodsCommand(input: GetDeviceMethodsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1InitiateDeviceClaimCommand(input: InitiateDeviceClaimCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1InvokeDeviceMethodCommand(input: InvokeDeviceMethodCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListDeviceEventsCommand(input: ListDeviceEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListDevicesCommand(input: ListDevicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UnclaimDeviceCommand(input: UnclaimDeviceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateDeviceStateCommand(input: UpdateDeviceStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restJson1_1ClaimDevicesByClaimCodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<ClaimDevicesByClaimCodeCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeDeviceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDeviceCommandOutput>;
export declare function deserializeAws_restJson1_1FinalizeDeviceClaimCommand(output: __HttpResponse, context: __SerdeContext): Promise<FinalizeDeviceClaimCommandOutput>;
export declare function deserializeAws_restJson1_1GetDeviceMethodsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDeviceMethodsCommandOutput>;
export declare function deserializeAws_restJson1_1InitiateDeviceClaimCommand(output: __HttpResponse, context: __SerdeContext): Promise<InitiateDeviceClaimCommandOutput>;
export declare function deserializeAws_restJson1_1InvokeDeviceMethodCommand(output: __HttpResponse, context: __SerdeContext): Promise<InvokeDeviceMethodCommandOutput>;
export declare function deserializeAws_restJson1_1ListDeviceEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDeviceEventsCommandOutput>;
export declare function deserializeAws_restJson1_1ListDevicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDevicesCommandOutput>;
export declare function deserializeAws_restJson1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_restJson1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UnclaimDeviceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UnclaimDeviceCommandOutput>;
export declare function deserializeAws_restJson1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateDeviceStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDeviceStateCommandOutput>;
