import { BatchGrantPermissionsCommandInput, BatchGrantPermissionsCommandOutput } from "../commands/BatchGrantPermissionsCommand";
import { BatchRevokePermissionsCommandInput, BatchRevokePermissionsCommandOutput } from "../commands/BatchRevokePermissionsCommand";
import { DeregisterResourceCommandInput, DeregisterResourceCommandOutput } from "../commands/DeregisterResourceCommand";
import { DescribeResourceCommandInput, DescribeResourceCommandOutput } from "../commands/DescribeResourceCommand";
import { GetDataLakeSettingsCommandInput, GetDataLakeSettingsCommandOutput } from "../commands/GetDataLakeSettingsCommand";
import { GetEffectivePermissionsForPathCommandInput, GetEffectivePermissionsForPathCommandOutput } from "../commands/GetEffectivePermissionsForPathCommand";
import { GrantPermissionsCommandInput, GrantPermissionsCommandOutput } from "../commands/GrantPermissionsCommand";
import { ListPermissionsCommandInput, ListPermissionsCommandOutput } from "../commands/ListPermissionsCommand";
import { ListResourcesCommandInput, ListResourcesCommandOutput } from "../commands/ListResourcesCommand";
import { PutDataLakeSettingsCommandInput, PutDataLakeSettingsCommandOutput } from "../commands/PutDataLakeSettingsCommand";
import { RegisterResourceCommandInput, RegisterResourceCommandOutput } from "../commands/RegisterResourceCommand";
import { RevokePermissionsCommandInput, RevokePermissionsCommandOutput } from "../commands/RevokePermissionsCommand";
import { UpdateResourceCommandInput, UpdateResourceCommandOutput } from "../commands/UpdateResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1BatchGrantPermissionsCommand(input: BatchGrantPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchRevokePermissionsCommand(input: BatchRevokePermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeregisterResourceCommand(input: DeregisterResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeResourceCommand(input: DescribeResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDataLakeSettingsCommand(input: GetDataLakeSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetEffectivePermissionsForPathCommand(input: GetEffectivePermissionsForPathCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GrantPermissionsCommand(input: GrantPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPermissionsCommand(input: ListPermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourcesCommand(input: ListResourcesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutDataLakeSettingsCommand(input: PutDataLakeSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RegisterResourceCommand(input: RegisterResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RevokePermissionsCommand(input: RevokePermissionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateResourceCommand(input: UpdateResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1BatchGrantPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGrantPermissionsCommandOutput>;
export declare function deserializeAws_json1_1BatchRevokePermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchRevokePermissionsCommandOutput>;
export declare function deserializeAws_json1_1DeregisterResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeregisterResourceCommandOutput>;
export declare function deserializeAws_json1_1DescribeResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeResourceCommandOutput>;
export declare function deserializeAws_json1_1GetDataLakeSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDataLakeSettingsCommandOutput>;
export declare function deserializeAws_json1_1GetEffectivePermissionsForPathCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetEffectivePermissionsForPathCommandOutput>;
export declare function deserializeAws_json1_1GrantPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GrantPermissionsCommandOutput>;
export declare function deserializeAws_json1_1ListPermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPermissionsCommandOutput>;
export declare function deserializeAws_json1_1ListResourcesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourcesCommandOutput>;
export declare function deserializeAws_json1_1PutDataLakeSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutDataLakeSettingsCommandOutput>;
export declare function deserializeAws_json1_1RegisterResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterResourceCommandOutput>;
export declare function deserializeAws_json1_1RevokePermissionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokePermissionsCommandOutput>;
export declare function deserializeAws_json1_1UpdateResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateResourceCommandOutput>;
