export const _A = "Attachment";
export const _AC = "AdvancedConfiguration";
export const _AD = "AttachmentDetails";
export const _ADE = "AccessDeniedException";
export const _ALEE = "AttributeLimitExceededException";
export const _ASC = "AttachmentStateChange";
export const _ASCt = "AttachmentStateChanges";
export const _ASGP = "AutoScalingGroupProvider";
export const _ASGPU = "AutoScalingGroupProviderUpdate";
export const _AVC = "AwsVpcConfiguration";
export const _At = "Attribute";
export const _Att = "Attachments";
export const _Attr = "Attributes";
export const _BE = "BlockedException";
export const _C = "Cluster";
export const _CA = "CreatedAt";
export const _CC = "ClusterConfiguration";
export const _CCCIE = "ClusterContainsContainerInstancesException";
export const _CCP = "CreateCapacityProvider";
export const _CCPR = "CreateCapacityProviderRequest";
export const _CCPRr = "CreateCapacityProviderResponse";
export const _CCR = "CreateClusterRequest";
export const _CCRr = "CreateClusterResponse";
export const _CCSE = "ClusterContainsServicesException";
export const _CCTE = "ClusterContainsTasksException";
export const _CCr = "CreateCluster";
export const _CD = "ContainerDefinition";
export const _CDo = "ContainerDependency";
export const _CDon = "ContainerDefinitions";
export const _CDont = "ContainerDependencies";
export const _CE = "ClientException";
export const _CEo = "ConflictException";
export const _CI = "ContainerImage";
export const _CIHS = "ContainerInstanceHealthStatus";
export const _CIo = "ContainerInstance";
export const _CIon = "ContainerImages";
export const _CIont = "ContainerInstances";
export const _CNFE = "ClusterNotFoundException";
export const _CO = "ContainerOverride";
export const _COo = "ContainerOverrides";
export const _CP = "CapacityProvider";
export const _CPS = "CapacityProviderStrategy";
export const _CPSI = "CapacityProviderStrategyItem";
export const _CPa = "CapacityProviders";
export const _CRP = "ContainerRestartPolicy";
export const _CS = "ClusterSetting";
export const _CSC = "ContainerStateChange";
export const _CSCD = "ClusterServiceConnectDefaults";
export const _CSCDR = "ClusterServiceConnectDefaultsRequest";
export const _CSCo = "ContainerStateChanges";
export const _CSR = "CreateServiceRequest";
export const _CSRr = "CreateServiceResponse";
export const _CSl = "ClusterSettings";
export const _CSr = "CreateService";
export const _CTS = "CreateTaskSet";
export const _CTSR = "CreateTaskSetRequest";
export const _CTSRr = "CreateTaskSetResponse";
export const _Cl = "Clusters";
export const _Co = "Container";
export const _Con = "Containers";
export const _D = "Deployment";
export const _DA = "DeploymentAlarms";
export const _DAR = "DeleteAttributesRequest";
export const _DARe = "DeleteAttributesResponse";
export const _DAS = "DeleteAccountSetting";
export const _DASR = "DeleteAccountSettingRequest";
export const _DASRe = "DeleteAccountSettingResponse";
export const _DAe = "DeleteAttributes";
export const _DC = "DeploymentConfiguration";
export const _DCB = "DeploymentCircuitBreaker";
export const _DCI = "DeregisterContainerInstance";
export const _DCIR = "DeregisterContainerInstanceRequest";
export const _DCIRe = "DeregisterContainerInstanceResponse";
export const _DCIRes = "DescribeContainerInstancesRequest";
export const _DCIResc = "DescribeContainerInstancesResponse";
export const _DCIe = "DescribeContainerInstances";
export const _DCP = "DeleteCapacityProvider";
export const _DCPR = "DeleteCapacityProviderRequest";
export const _DCPRe = "DeleteCapacityProviderResponse";
export const _DCPRes = "DescribeCapacityProvidersRequest";
export const _DCPResc = "DescribeCapacityProvidersResponse";
export const _DCPe = "DescribeCapacityProviders";
export const _DCR = "DeleteClusterRequest";
export const _DCRe = "DeleteClusterResponse";
export const _DCRes = "DescribeClustersRequest";
export const _DCResc = "DescribeClustersResponse";
export const _DCe = "DeploymentController";
export const _DCel = "DeleteCluster";
export const _DCes = "DescribeClusters";
export const _DES = "DeploymentEphemeralStorage";
export const _DL = "DevicesList";
export const _DLH = "DeploymentLifecycleHook";
export const _DLHL = "DeploymentLifecycleHookList";
export const _DPE = "DiscoverPollEndpoint";
export const _DPER = "DiscoverPollEndpointRequest";
export const _DPERi = "DiscoverPollEndpointResponse";
export const _DS = "DeleteService";
export const _DSD = "DescribeServiceDeployments";
export const _DSDR = "DescribeServiceDeploymentsRequest";
export const _DSDRe = "DescribeServiceDeploymentsResponse";
export const _DSR = "DeleteServiceRequest";
export const _DSRR = "DescribeServiceRevisionsRequest";
export const _DSRRe = "DescribeServiceRevisionsResponse";
export const _DSRe = "DeleteServiceResponse";
export const _DSRes = "DescribeServicesRequest";
export const _DSResc = "DescribeServicesResponse";
export const _DSRescr = "DescribeServiceRevisions";
export const _DSe = "DescribeServices";
export const _DT = "DescribeTasks";
export const _DTD = "DeleteTaskDefinitions";
export const _DTDR = "DeleteTaskDefinitionsRequest";
export const _DTDRe = "DeleteTaskDefinitionsResponse";
export const _DTDRer = "DeregisterTaskDefinitionRequest";
export const _DTDRere = "DeregisterTaskDefinitionResponse";
export const _DTDRes = "DescribeTaskDefinitionRequest";
export const _DTDResc = "DescribeTaskDefinitionResponse";
export const _DTDe = "DeregisterTaskDefinition";
export const _DTDes = "DescribeTaskDefinition";
export const _DTR = "DescribeTasksRequest";
export const _DTRe = "DescribeTasksResponse";
export const _DTS = "DeleteTaskSet";
export const _DTSR = "DeleteTaskSetRequest";
export const _DTSRe = "DeleteTaskSetResponse";
export const _DTSRes = "DescribeTaskSetsRequest";
export const _DTSResc = "DescribeTaskSetsResponse";
export const _DTSe = "DescribeTaskSets";
export const _DVC = "DockerVolumeConfiguration";
export const _De = "Device";
export const _Dep = "Deployments";
export const _EBSTS = "EBSTagSpecification";
export const _EBSTSa = "EBSTagSpecifications";
export const _EC = "ExecuteCommand";
export const _ECC = "ExecuteCommandConfiguration";
export const _ECLC = "ExecuteCommandLogConfiguration";
export const _ECR = "ExecuteCommandRequest";
export const _ECRx = "ExecuteCommandResponse";
export const _EF = "EnvironmentFile";
export const _EFSAC = "EFSAuthorizationConfig";
export const _EFSVC = "EFSVolumeConfiguration";
export const _EFn = "EnvironmentFiles";
export const _ES = "EphemeralStorage";
export const _EV = "EnvironmentVariables";
export const _F = "Failure";
export const _FC = "FirelensConfiguration";
export const _FSWFSAC = "FSxWindowsFileServerAuthorizationConfig";
export const _FSWFSVC = "FSxWindowsFileServerVolumeConfiguration";
export const _Fa = "Failures";
export const _GTP = "GetTaskProtection";
export const _GTPR = "GetTaskProtectionRequest";
export const _GTPRe = "GetTaskProtectionResponse";
export const _HC = "HealthCheck";
export const _HE = "HostEntry";
export const _HEL = "HostEntryList";
export const _HVP = "HostVolumeProperties";
export const _IA = "InferenceAccelerator";
export const _IAO = "InferenceAcceleratorOverride";
export const _IAOn = "InferenceAcceleratorOverrides";
export const _IAn = "InferenceAccelerators";
export const _IHCR = "InstanceHealthCheckResult";
export const _IHCRL = "InstanceHealthCheckResultList";
export const _IPE = "InvalidParameterException";
export const _KC = "KernelCapabilities";
export const _KVP = "KeyValuePair";
export const _LA = "ListAttributes";
export const _LAR = "ListAttributesRequest";
export const _LARi = "ListAttributesResponse";
export const _LAS = "ListAccountSettings";
export const _LASR = "ListAccountSettingsRequest";
export const _LASRi = "ListAccountSettingsResponse";
export const _LB = "LoadBalancer";
export const _LBo = "LoadBalancers";
export const _LC = "LogConfiguration";
export const _LCI = "ListContainerInstances";
export const _LCIR = "ListContainerInstancesRequest";
export const _LCIRi = "ListContainerInstancesResponse";
export const _LCR = "ListClustersRequest";
export const _LCRi = "ListClustersResponse";
export const _LCi = "ListClusters";
export const _LEE = "LimitExceededException";
export const _LP = "LinuxParameters";
export const _LS = "ListServices";
export const _LSBN = "ListServicesByNamespace";
export const _LSBNR = "ListServicesByNamespaceRequest";
export const _LSBNRi = "ListServicesByNamespaceResponse";
export const _LSD = "ListServiceDeployments";
export const _LSDR = "ListServiceDeploymentsRequest";
export const _LSDRi = "ListServiceDeploymentsResponse";
export const _LSR = "ListServicesRequest";
export const _LSRi = "ListServicesResponse";
export const _LT = "ListTasks";
export const _LTD = "ListTaskDefinitions";
export const _LTDF = "ListTaskDefinitionFamilies";
export const _LTDFR = "ListTaskDefinitionFamiliesRequest";
export const _LTDFRi = "ListTaskDefinitionFamiliesResponse";
export const _LTDR = "ListTaskDefinitionsRequest";
export const _LTDRi = "ListTaskDefinitionsResponse";
export const _LTFR = "ListTagsForResource";
export const _LTFRR = "ListTagsForResourceRequest";
export const _LTFRRi = "ListTagsForResourceResponse";
export const _LTR = "ListTasksRequest";
export const _LTRi = "ListTasksResponse";
export const _MA = "ManagedAgent";
export const _MASC = "ManagedAgentStateChange";
export const _MASCa = "ManagedAgentStateChanges";
export const _MAa = "ManagedAgents";
export const _MP = "MountPoint";
export const _MPL = "MountPointList";
export const _MS = "ManagedScaling";
export const _MSC = "ManagedStorageConfiguration";
export const _MVE = "MissingVersionException";
export const _NB = "NetworkBinding";
export const _NBe = "NetworkBindings";
export const _NC = "NetworkConfiguration";
export const _NI = "NetworkInterface";
export const _NIe = "NetworkInterfaces";
export const _NNFE = "NamespaceNotFoundException";
export const _NUAE = "NoUpdateAvailableException";
export const _PA = "PutAttributes";
export const _PAR = "PutAttributesRequest";
export const _PARu = "PutAttributesResponse";
export const _PAS = "PutAccountSetting";
export const _PASD = "PutAccountSettingDefault";
export const _PASDR = "PutAccountSettingDefaultRequest";
export const _PASDRu = "PutAccountSettingDefaultResponse";
export const _PASR = "PutAccountSettingRequest";
export const _PASRu = "PutAccountSettingResponse";
export const _PC = "PlacementConstraint";
export const _PCCP = "PutClusterCapacityProviders";
export const _PCCPR = "PutClusterCapacityProvidersRequest";
export const _PCCPRu = "PutClusterCapacityProvidersResponse";
export const _PCP = "ProxyConfigurationProperties";
export const _PCl = "PlacementConstraints";
export const _PCr = "ProxyConfiguration";
export const _PD = "PlatformDevice";
export const _PDl = "PlatformDevices";
export const _PM = "PortMapping";
export const _PML = "PortMappingList";
export const _PS = "PlacementStrategy";
export const _PSl = "PlacementStrategies";
export const _PT = "ProtectedTask";
export const _PTDIE = "PlatformTaskDefinitionIncompatibilityException";
export const _PTr = "ProtectedTasks";
export const _PUE = "PlatformUnknownException";
export const _R = "Resource";
export const _RA = "RequiresAttributes";
export const _RC = "RepositoryCredentials";
export const _RCI = "RegisterContainerInstance";
export const _RCIR = "RegisterContainerInstanceRequest";
export const _RCIRe = "RegisterContainerInstanceResponse";
export const _RCe = "ResolvedConfiguration";
export const _RIUE = "ResourceInUseException";
export const _RNFE = "ResourceNotFoundException";
export const _RP = "RuntimePlatform";
export const _RR = "ResourceRequirement";
export const _RRe = "ResourceRequirements";
export const _RT = "RunTask";
export const _RTD = "RegisterTaskDefinition";
export const _RTDR = "RegisterTaskDefinitionRequest";
export const _RTDRe = "RegisterTaskDefinitionResponse";
export const _RTR = "RunTaskRequest";
export const _RTRu = "RunTaskResponse";
export const _Re = "Resources";
export const _Ro = "Rollback";
export const _S = "Scale";
export const _SASC = "SubmitAttachmentStateChanges";
export const _SASCR = "SubmitAttachmentStateChangesRequest";
export const _SASCRu = "SubmitAttachmentStateChangesResponse";
export const _SC = "SystemControl";
export const _SCC = "ServiceConnectConfiguration";
export const _SCCA = "ServiceConnectClientAlias";
export const _SCCAL = "ServiceConnectClientAliasList";
export const _SCS = "ServiceConnectService";
export const _SCSC = "SubmitContainerStateChange";
export const _SCSCR = "SubmitContainerStateChangeRequest";
export const _SCSCRu = "SubmitContainerStateChangeResponse";
export const _SCSL = "ServiceConnectServiceList";
export const _SCSR = "ServiceConnectServiceResource";
export const _SCSRL = "ServiceConnectServiceResourceList";
export const _SCTC = "ServiceConnectTlsConfiguration";
export const _SCTCA = "ServiceConnectTlsCertificateAuthority";
export const _SCTTHMR = "ServiceConnectTestTrafficHeaderMatchRules";
export const _SCTTHR = "ServiceConnectTestTrafficHeaderRules";
export const _SCTTR = "ServiceConnectTestTrafficRules";
export const _SCy = "SystemControls";
export const _SD = "ServiceDeployment";
export const _SDA = "ServiceDeploymentAlarms";
export const _SDB = "ServiceDeploymentBrief";
export const _SDBe = "ServiceDeploymentsBrief";
export const _SDCB = "ServiceDeploymentCircuitBreaker";
export const _SDNFE = "ServiceDeploymentNotFoundException";
export const _SDe = "ServiceDeployments";
export const _SE = "ServerException";
export const _SEe = "ServiceEvent";
export const _SEer = "ServiceEvents";
export const _SL = "SecretList";
export const _SMEBSVC = "ServiceManagedEBSVolumeConfiguration";
export const _SNAE = "ServiceNotActiveException";
export const _SNFE = "ServiceNotFoundException";
export const _SR = "ServiceRegistry";
export const _SRLB = "ServiceRevisionLoadBalancer";
export const _SRLBe = "ServiceRevisionLoadBalancers";
export const _SRS = "ServiceRevisionSummary";
export const _SRSL = "ServiceRevisionsSummaryList";
export const _SRe = "ServiceRevision";
export const _SRer = "ServiceRegistries";
export const _SRerv = "ServiceRevisions";
export const _SS = "SensitiveString";
export const _SSD = "StopServiceDeployment";
export const _SSDR = "StopServiceDeploymentRequest";
export const _SSDRt = "StopServiceDeploymentResponse";
export const _ST = "StartTask";
export const _STR = "StartTaskRequest";
export const _STRt = "StartTaskResponse";
export const _STRto = "StopTaskRequest";
export const _STRtop = "StopTaskResponse";
export const _STSC = "SubmitTaskStateChange";
export const _STSCR = "SubmitTaskStateChangeRequest";
export const _STSCRu = "SubmitTaskStateChangeResponse";
export const _STt = "StopTask";
export const _SVC = "ServiceVolumeConfiguration";
export const _SVCe = "ServiceVolumeConfigurations";
export const _Se = "Secret";
export const _Ser = "Service";
export const _Serv = "Services";
export const _Ses = "Session";
export const _Set = "Setting";
export const _Sett = "Settings";
export const _St = "Statistics";
export const _T = "Tag";
export const _TC = "TimeoutConfiguration";
export const _TD = "TaskDefinition";
export const _TDL = "TaskDefinitionList";
export const _TDPC = "TaskDefinitionPlacementConstraint";
export const _TDPCa = "TaskDefinitionPlacementConstraints";
export const _TES = "TaskEphemeralStorage";
export const _TL = "TmpfsList";
export const _TMEBSVC = "TaskManagedEBSVolumeConfiguration";
export const _TMEBSVTP = "TaskManagedEBSVolumeTerminationPolicy";
export const _TNCE = "TargetNotConnectedException";
export const _TNFE = "TargetNotFoundException";
export const _TO = "TaskOverride";
export const _TR = "TagResource";
export const _TRR = "TagResourceRequest";
export const _TRRa = "TagResourceResponse";
export const _TS = "TaskSet";
export const _TSNFE = "TaskSetNotFoundException";
export const _TSa = "TaskSets";
export const _TVC = "TaskVolumeConfiguration";
export const _TVCa = "TaskVolumeConfigurations";
export const _Ta = "Task";
export const _Tag = "Tags";
export const _Tas = "Tasks";
export const _Tm = "Tmpfs";
export const _U = "Ulimit";
export const _UC = "UpdateCluster";
export const _UCA = "UpdateContainerAgent";
export const _UCAR = "UpdateContainerAgentRequest";
export const _UCARp = "UpdateContainerAgentResponse";
export const _UCIS = "UpdateContainerInstancesState";
export const _UCISR = "UpdateContainerInstancesStateRequest";
export const _UCISRp = "UpdateContainerInstancesStateResponse";
export const _UCP = "UpdateCapacityProvider";
export const _UCPR = "UpdateCapacityProviderRequest";
export const _UCPRp = "UpdateCapacityProviderResponse";
export const _UCR = "UpdateClusterRequest";
export const _UCRp = "UpdateClusterResponse";
export const _UCS = "UpdateClusterSettings";
export const _UCSR = "UpdateClusterSettingsRequest";
export const _UCSRp = "UpdateClusterSettingsResponse";
export const _UFE = "UnsupportedFeatureException";
export const _UIPE = "UpdateInProgressException";
export const _UL = "UlimitList";
export const _UR = "UntagResource";
export const _URR = "UntagResourceRequest";
export const _URRn = "UntagResourceResponse";
export const _US = "UpdateService";
export const _USPTS = "UpdateServicePrimaryTaskSet";
export const _USPTSR = "UpdateServicePrimaryTaskSetRequest";
export const _USPTSRp = "UpdateServicePrimaryTaskSetResponse";
export const _USR = "UpdateServiceRequest";
export const _USRp = "UpdateServiceResponse";
export const _UTP = "UpdateTaskProtection";
export const _UTPR = "UpdateTaskProtectionRequest";
export const _UTPRp = "UpdateTaskProtectionResponse";
export const _UTS = "UpdateTaskSet";
export const _UTSR = "UpdateTaskSetRequest";
export const _UTSRp = "UpdateTaskSetResponse";
export const _V = "Volume";
export const _VF = "VolumeFrom";
export const _VFL = "VolumeFromList";
export const _VI = "VersionInfo";
export const _VL = "VolumeList";
export const _VLC = "VpcLatticeConfiguration";
export const _VLCp = "VpcLatticeConfigurations";
export const _a = "attachments";
export const _aA = "attachmentArn";
export const _aC = "agentConnected";
export const _aCd = "advancedConfiguration";
export const _aCu = "authorizationConfig";
export const _aCw = "awsvpcConfiguration";
export const _aH = "agentHash";
export const _aI = "attachmentId";
export const _aN = "alarmNames";
export const _aNt = "attributeName";
export const _aP = "appProtocol";
export const _aPAA = "awsPcaAuthorityArn";
export const _aPI = "assignPublicIp";
export const _aPIc = "accessPointId";
export const _aS = "attachmentsStatus";
export const _aSC = "activeServicesCount";
export const _aSGA = "autoScalingGroupArn";
export const _aSGP = "autoScalingGroupProvider";
export const _aTGA = "alternateTargetGroupArn";
export const _aUS = "agentUpdateStatus";
export const _aV = "attributeValue";
export const _aVg = "agentVersion";
export const _aZ = "availabilityZone";
export const _aZR = "availabilityZoneRebalancing";
export const _ac = "acknowledgment";
export const _ad = "add";
export const _af = "after";
export const _al = "alarms";
export const _ar = "arn";
export const _at = "attributes";
export const _au = "autoprovision";
export const _b = "base";
export const _bIP = "bindIP";
export const _bTIM = "bakeTimeInMinutes";
export const _be = "before";
export const _c = "client";
export const _cA = "clusterArn";
export const _cAL = "configuredAtLaunch";
export const _cAl = "clusterArns";
export const _cAli = "clientAliases";
export const _cAo = "containerArn";
export const _cAon = "connectivityAt";
export const _cAp = "cpuArchitecture";
export const _cAr = "createdAt";
export const _cB = "createdBy";
export const _cD = "containerDefinitions";
export const _cDC = "computedDesiredCount";
export const _cI = "containerInstance";
export const _cIA = "containerInstanceArn";
export const _cIAo = "containerInstanceArns";
export const _cIo = "containerInstances";
export const _cIon = "containerImages";
export const _cN = "clusterName";
export const _cNo = "containerName";
export const _cO = "containerOverrides";
export const _cP = "capacityProvider";
export const _cPA = "capacityProviderArn";
export const _cPN = "capacityProviderName";
export const _cPR = "containerPortRange";
export const _cPS = "capacityProviderStrategy";
export const _cPa = "capacityProviders";
export const _cPo = "containerPath";
export const _cPon = "containerPort";
export const _cPr = "credentialsParameter";
export const _cS = "credentialSpecs";
export const _cT = "clientToken";
export const _cWEE = "cloudWatchEncryptionEnabled";
export const _cWLGN = "cloudWatchLogGroupName";
export const _ca = "capabilities";
export const _cl = "cluster";
export const _clu = "clusters";
export const _co = "configuration";
export const _com = "command";
export const _comp = "compatibilities";
export const _con = "condition";
export const _conn = "connectivity";
export const _cont = "container";
export const _conta = "containers";
export const _cou = "count";
export const _cp = "cpu";
export const _d = "details";
export const _dA = "discoveryArn";
export const _dAe = "deregisteredAt";
export const _dC = "desiredCount";
export const _dCB = "deploymentCircuitBreaker";
export const _dCPS = "defaultCapacityProviderStrategy";
export const _dCe = "deploymentConfiguration";
export const _dCep = "deploymentController";
export const _dL = "dockerLabels";
export const _dN = "disableNetworking";
export const _dNe = "deviceName";
export const _dNi = "discoveryName";
export const _dNn = "dnsName";
export const _dO = "dependsOn";
export const _dOT = "deleteOnTermination";
export const _dOr = "driverOpts";
export const _dS = "dnsServers";
export const _dSD = "dnsSearchDomains";
export const _dSO = "dockerSecurityOptions";
export const _dSe = "desiredStatus";
export const _dT = "deviceType";
export const _dV = "doubleValue";
export const _dVC = "dockerVolumeConfiguration";
export const _dVo = "dockerVersion";
export const _de = "detail";
export const _dep = "deployments";
export const _dev = "devices";
export const _do = "domain";
export const _dr = "driver";
export const _dro = "drop";
export const _e = "error";
export const _eC = "exitCode";
export const _eCC = "executeCommandConfiguration";
export const _eD = "expirationDate";
export const _eEC = "enableExecuteCommand";
export const _eECSMT = "enableECSManagedTags";
export const _eF = "environmentFiles";
export const _eFI = "enableFaultInjection";
export const _eH = "extraHosts";
export const _eI = "externalId";
export const _eII = "ec2InstanceId";
export const _eIM = "expiresInMinutes";
export const _eP = "entryPoint";
export const _eRA = "executionRoleArn";
export const _eS = "effectiveSettings";
export const _eSA = "executionStoppedAt";
export const _eSp = "ephemeralStorage";
export const _eVC = "efsVolumeConfiguration";
export const _en = "environment";
export const _ena = "enabled";
export const _enab = "enable";
export const _enc = "encrypted";
export const _end = "endpoint";
export const _es = "essential";
export const _ev = "events";
export const _ex = "expression";
export const _exa = "exact";
export const _f = "force";
export const _fA = "finishedAt";
export const _fC = "firelensConfiguration";
export const _fCa = "failureCount";
export const _fES = "fargateEphemeralStorage";
export const _fESKKI = "fargateEphemeralStorageKmsKeyId";
export const _fND = "forceNewDeployment";
export const _fP = "familyPrefix";
export const _fSI = "fileSystemId";
export const _fT = "failedTasks";
export const _fTi = "filesystemType";
export const _fWFSVC = "fsxWindowsFileServerVolumeConfiguration";
export const _fa = "failures";
export const _fam = "families";
export const _fami = "family";
export const _fi = "filter";
export const _fie = "field";
export const _g = "group";
export const _gDE = "guardDutyEnabled";
export const _gI = "gpuIds";
export const _h = "hostname";
export const _hC = "healthCheck";
export const _hCGPS = "healthCheckGracePeriodSeconds";
export const _hD = "hookDetails";
export const _hL = "hardLimit";
export const _hP = "hostPath";
export const _hPR = "hostPortRange";
export const _hPo = "hostPort";
export const _hS = "healthStatus";
export const _hTA = "hookTargetArn";
export const _he = "header";
export const _ho = "host";
export const _i = "id";
export const _iA = "ipAddress";
export const _iAO = "inferenceAcceleratorOverrides";
export const _iAn = "inferenceAccelerators";
export const _iAp = "ipv6Address";
export const _iCA = "issuerCertificateAuthority";
export const _iD = "imageDigest";
export const _iEC = "ignoredExitCodes";
export const _iID = "instanceIdentityDocument";
export const _iIDS = "instanceIdentityDocumentSignature";
export const _iM = "ipcMode";
export const _iPE = "initProcessEnabled";
export const _iPO = "ingressPortOverride";
export const _iTS = "idleTimeoutSeconds";
export const _iV = "integerValue";
export const _iWP = "instanceWarmupPeriod";
export const _ia = "iam";
export const _im = "image";
export const _in = "interactive";
export const _inc = "include";
export const _int = "interval";
export const _io = "iops";
export const _k = "key";
export const _kK = "kmsKey";
export const _kKI = "kmsKeyId";
export const _l = "links";
export const _lB = "loadBalancers";
export const _lBN = "loadBalancerName";
export const _lC = "logConfiguration";
export const _lD = "logDriver";
export const _lH = "lifecycleHooks";
export const _lP = "linuxParameters";
export const _lS = "lastStatus";
export const _lSA = "lastStartedAt";
export const _lSC = "lastStatusChange";
export const _lSi = "lifecycleStages";
export const _lSif = "lifecycleStage";
export const _lT = "launchType";
export const _lU = "lastUpdated";
export const _lV = "longValue";
export const _la = "labels";
export const _lo = "logging";
export const _m = "message";
export const _mA = "managedAgents";
export const _mAN = "managedAgentName";
export const _mD = "managedDraining";
export const _mEBSV = "managedEBSVolume";
export const _mHP = "minimumHealthyPercent";
export const _mO = "mountOptions";
export const _mP = "mountPoints";
export const _mPa = "maximumPercent";
export const _mR = "memoryReservation";
export const _mRa = "maxResults";
export const _mS = "managedScaling";
export const _mSC = "managedStorageConfiguration";
export const _mSSS = "minimumScalingStepSize";
export const _mSSSa = "maximumScalingStepSize";
export const _mSa = "maxSwap";
export const _mTP = "managedTerminationProtection";
export const _me = "memory";
export const _n = "name";
export const _nB = "networkBindings";
export const _nC = "networkConfiguration";
export const _nI = "networkInterfaces";
export const _nM = "networkMode";
export const _nT = "nextToken";
export const _na = "namespace";
export const _o = "options";
export const _oS = "overallStatus";
export const _oSF = "operatingSystemFamily";
export const _ov = "overrides";
export const _p = "privileged";
export const _pA = "principalArn";
export const _pC = "placementConstraints";
export const _pCe = "pendingCount";
export const _pCr = "proxyConfiguration";
export const _pD = "platformDevices";
export const _pE = "protectionEnabled";
export const _pF = "platformFamily";
export const _pIA = "privateIpv4Address";
export const _pLR = "productionListenerRule";
export const _pM = "portMappings";
export const _pMi = "pidMode";
export const _pN = "portName";
export const _pRTS = "perRequestTimeoutSeconds";
export const _pS = "placementStrategy";
export const _pSA = "pullStartedAt";
export const _pSAu = "pullStoppedAt";
export const _pT = "pseudoTerminal";
export const _pTC = "pendingTasksCount";
export const _pTCe = "pendingTaskCount";
export const _pTS = "primaryTaskSet";
export const _pTr = "propagateTags";
export const _pTro = "protectedTasks";
export const _pV = "platformVersion";
export const _pe = "permissions";
export const _po = "port";
export const _pr = "protocol";
export const _pro = "properties";
export const _r = "reason";
export const _rA = "roleArn";
export const _rAP = "restartAttemptPeriod";
export const _rAe = "registeredAt";
export const _rAeg = "registryArn";
export const _rAeq = "requiresAttributes";
export const _rAes = "resourceArn";
export const _rB = "registeredBy";
export const _rC = "repositoryCredentials";
export const _rCIC = "registeredContainerInstancesCount";
export const _rCe = "requiresCompatibilities";
export const _rCes = "resolvedConfiguration";
export const _rCu = "runningCount";
export const _rD = "rootDirectory";
export const _rI = "resourceIds";
export const _rIe = "referenceId";
export const _rIu = "runtimeId";
export const _rO = "readOnly";
export const _rP = "restartPolicy";
export const _rPu = "runtimePlatform";
export const _rR = "resourceRequirements";
export const _rRF = "readonlyRootFilesystem";
export const _rRe = "remainingResources";
export const _rReg = "registeredResources";
export const _rS = "rolloutState";
export const _rSR = "rolloutStateReason";
export const _rT = "resourceType";
export const _rTC = "runningTasksCount";
export const _rTCe = "requestedTaskCount";
export const _rTCu = "runningTaskCount";
export const _re = "retries";
export const _rev = "revision";
export const _ro = "role";
export const _rol = "rollback";
export const _s = "status";
export const _sA = "serviceArns";
export const _sAe = "serviceArn";
export const _sAt = "startedAt";
export const _sAto = "stoppedAt";
export const _sAtop = "stoppingAt";
export const _sB = "startedBy";
export const _sBN = "s3BucketName";
export const _sC = "systemControls";
export const _sCC = "serviceConnectConfiguration";
export const _sCD = "serviceConnectDefaults";
export const _sCE = "serviceConnectEndpoint";
export const _sCR = "serviceConnectResources";
export const _sCo = "sourceContainer";
export const _sCt = "stopCode";
export const _sD = "serviceDeployments";
export const _sDA = "serviceDeploymentArns";
export const _sDAe = "serviceDeploymentArn";
export const _sEE = "s3EncryptionEnabled";
export const _sG = "securityGroups";
export const _sI = "snapshotId";
export const _sIGB = "sizeInGiB";
export const _sIe = "sessionId";
export const _sKP = "s3KeyPrefix";
export const _sL = "softLimit";
export const _sMS = "sharedMemorySize";
export const _sN = "serviceName";
export const _sO = "secretOptions";
export const _sP = "startPeriod";
export const _sPo = "sourcePath";
export const _sR = "statusReason";
export const _sRA = "serviceRevisionArns";
export const _sRAe = "serviceRevisionArn";
export const _sRe = "serviceRegistries";
export const _sRer = "serviceRevisions";
export const _sRt = "stoppedReason";
export const _sS = "schedulingStrategy";
export const _sSA = "stabilityStatusAt";
export const _sSR = "sourceServiceRevisions";
export const _sSV = "stringSetValue";
export const _sSt = "stabilityStatus";
export const _sT = "startTimeout";
export const _sTt = "stopTimeout";
export const _sTto = "stopType";
export const _sU = "streamUrl";
export const _sV = "sourceVolume";
export const _sc = "scale";
export const _sco = "scope";
export const _se = "settings";
export const _sec = "secrets";
export const _ser = "service";
export const _serv = "services";
export const _serve = "server";
export const _ses = "session";
export const _set = "setting";
export const _si = "size";
export const _so = "sort";
export const _st = "statistics";
export const _str = "strategy";
export const _su = "subnets";
export const _sw = "swappiness";
export const _t = "type";
export const _tA = "taskArn";
export const _tAN = "triggeredAlarmNames";
export const _tAa = "taskArns";
export const _tC = "targetCapacity";
export const _tD = "taskDefinition";
export const _tDA = "taskDefinitionArns";
export const _tDAa = "taskDefinitionArn";
export const _tDa = "taskDefinitions";
export const _tE = "telemetryEndpoint";
export const _tEP = "transitEncryptionPort";
export const _tEr = "transitEncryption";
export const _tGA = "targetGroupArn";
export const _tI = "targetId";
export const _tK = "tagKeys";
export const _tLR = "testListenerRule";
export const _tP = "terminationPolicy";
export const _tR = "totalResources";
export const _tRA = "taskRoleArn";
export const _tS = "taskSet";
export const _tSA = "taskSetArn";
export const _tSR = "targetServiceRevision";
export const _tSRA = "targetServiceRevisionArn";
export const _tSa = "taskSets";
export const _tSag = "tagSpecifications";
export const _tT = "targetType";
export const _tTR = "testTrafficRules";
export const _tV = "tokenValue";
export const _ta = "tags";
export const _tas = "tasks";
export const _task = "task";
export const _th = "threshold";
export const _thr = "throughput";
export const _ti = "timeout";
export const _tl = "tls";
export const _tm = "tmpfs";
export const _u = "user";
export const _uA = "updatedAt";
export const _uS = "updateStatus";
export const _uSR = "updateStatusReason";
export const _ul = "ulimits";
export const _un = "unit";
export const _v = "value";
export const _vC = "versionConsistency";
export const _vCo = "volumeConfigurations";
export const _vF = "volumesFrom";
export const _vFa = "valueFrom";
export const _vI = "versionInfo";
export const _vIR = "volumeInitializationRate";
export const _vLC = "vpcLatticeConfigurations";
export const _vT = "volumeType";
export const _ve = "version";
export const _vo = "volumes";
export const _w = "weight";
export const _wD = "workingDirectory";
export const n0 = "com.amazonaws.ecs";

// smithy-typescript generated code
import { error, list, struct } from "@smithy/core/schema";

import { ECSServiceException as __ECSServiceException } from "../models/ECSServiceException";
import {
  AccessDeniedException as __AccessDeniedException,
  ClientException as __ClientException,
  ClusterNotFoundException as __ClusterNotFoundException,
  InvalidParameterException as __InvalidParameterException,
  ServerException as __ServerException,
  UnsupportedFeatureException as __UnsupportedFeatureException,
} from "../models/index";

/* eslint no-var: 0 */

export var AccessDeniedException = error(
  n0,
  _ADE,
  {
    [_e]: _c,
  },
  [_m],
  [0],

  __AccessDeniedException
);
export var Attachment = struct(n0, _A, 0, [_i, _t, _s, _d], [0, 0, 0, () => AttachmentDetails]);
export var Attribute = struct(n0, _At, 0, [_n, _v, _tT, _tI], [0, 0, 0, 0]);
export var CapacityProviderStrategyItem = struct(n0, _CPSI, 0, [_cP, _w, _b], [0, 1, 1]);
export var ClientException = error(
  n0,
  _CE,
  {
    [_e]: _c,
  },
  [_m],
  [0],

  __ClientException
);
export var ClusterNotFoundException = error(
  n0,
  _CNFE,
  {
    [_e]: _c,
  },
  [_m],
  [0],

  __ClusterNotFoundException
);
export var Failure = struct(n0, _F, 0, [_ar, _r, _de], [0, 0, 0]);
export var InvalidParameterException = error(
  n0,
  _IPE,
  {
    [_e]: _c,
  },
  [_m],
  [0],

  __InvalidParameterException
);
export var KeyValuePair = struct(n0, _KVP, 0, [_n, _v], [0, 0]);
export var ServerException = error(
  n0,
  _SE,
  {
    [_e]: _serve,
  },
  [_m],
  [0],

  __ServerException
);
export var Tag = struct(n0, _T, 0, [_k, _v], [0, 0]);
export var UnsupportedFeatureException = error(
  n0,
  _UFE,
  {
    [_e]: _c,
  },
  [_m],
  [0],

  __UnsupportedFeatureException
);
export var Unit = "unit" as const;

export var ECSServiceException = error(
  "smithy.ts.sdk.synthetic.com.amazonaws.ecs",
  "ECSServiceException",
  0,
  [],
  [],
  __ECSServiceException
);
export var AttachmentDetails = list(n0, _AD, 0, () => KeyValuePair);
export var Attachments = list(n0, _Att, 0, () => Attachment);
export var CapacityProviderStrategy = list(n0, _CPS, 0, () => CapacityProviderStrategyItem);
export var Failures = list(n0, _Fa, 0, () => Failure);
export var StringList = 64 | 0;

export var Tags = list(n0, _Tag, 0, () => Tag);
