import { AddTagsToCertificateCommandInput, AddTagsToCertificateCommandOutput } from "../commands/AddTagsToCertificateCommand";
import { DeleteCertificateCommandInput, DeleteCertificateCommandOutput } from "../commands/DeleteCertificateCommand";
import { DescribeCertificateCommandInput, DescribeCertificateCommandOutput } from "../commands/DescribeCertificateCommand";
import { ExportCertificateCommandInput, ExportCertificateCommandOutput } from "../commands/ExportCertificateCommand";
import { GetCertificateCommandInput, GetCertificateCommandOutput } from "../commands/GetCertificateCommand";
import { ImportCertificateCommandInput, ImportCertificateCommandOutput } from "../commands/ImportCertificateCommand";
import { ListCertificatesCommandInput, ListCertificatesCommandOutput } from "../commands/ListCertificatesCommand";
import { ListTagsForCertificateCommandInput, ListTagsForCertificateCommandOutput } from "../commands/ListTagsForCertificateCommand";
import { RemoveTagsFromCertificateCommandInput, RemoveTagsFromCertificateCommandOutput } from "../commands/RemoveTagsFromCertificateCommand";
import { RenewCertificateCommandInput, RenewCertificateCommandOutput } from "../commands/RenewCertificateCommand";
import { RequestCertificateCommandInput, RequestCertificateCommandOutput } from "../commands/RequestCertificateCommand";
import { ResendValidationEmailCommandInput, ResendValidationEmailCommandOutput } from "../commands/ResendValidationEmailCommand";
import { UpdateCertificateOptionsCommandInput, UpdateCertificateOptionsCommandOutput } from "../commands/UpdateCertificateOptionsCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AddTagsToCertificateCommand(input: AddTagsToCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteCertificateCommand(input: DeleteCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCertificateCommand(input: DescribeCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ExportCertificateCommand(input: ExportCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCertificateCommand(input: GetCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ImportCertificateCommand(input: ImportCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListCertificatesCommand(input: ListCertificatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForCertificateCommand(input: ListTagsForCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTagsFromCertificateCommand(input: RemoveTagsFromCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RenewCertificateCommand(input: RenewCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RequestCertificateCommand(input: RequestCertificateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResendValidationEmailCommand(input: ResendValidationEmailCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateCertificateOptionsCommand(input: UpdateCertificateOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AddTagsToCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsToCertificateCommandOutput>;
export declare function deserializeAws_json1_1DeleteCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCertificateCommandOutput>;
export declare function deserializeAws_json1_1DescribeCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCertificateCommandOutput>;
export declare function deserializeAws_json1_1ExportCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<ExportCertificateCommandOutput>;
export declare function deserializeAws_json1_1GetCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCertificateCommandOutput>;
export declare function deserializeAws_json1_1ImportCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<ImportCertificateCommandOutput>;
export declare function deserializeAws_json1_1ListCertificatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCertificatesCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForCertificateCommandOutput>;
export declare function deserializeAws_json1_1RemoveTagsFromCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsFromCertificateCommandOutput>;
export declare function deserializeAws_json1_1RenewCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<RenewCertificateCommandOutput>;
export declare function deserializeAws_json1_1RequestCertificateCommand(output: __HttpResponse, context: __SerdeContext): Promise<RequestCertificateCommandOutput>;
export declare function deserializeAws_json1_1ResendValidationEmailCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResendValidationEmailCommandOutput>;
export declare function deserializeAws_json1_1UpdateCertificateOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateCertificateOptionsCommandOutput>;
