// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AbortMultipartUpload$,
  AbortMultipartUploadCommand,
  AccessDenied$,
  BucketAlreadyExists$,
  BucketAlreadyOwnedByYou$,
  CompleteMultipartUpload$,
  CompleteMultipartUploadCommand,
  CopyObject$,
  CopyObjectCommand,
  CreateBucket$,
  CreateBucketCommand,
  CreateBucketMetadataConfiguration$,
  CreateBucketMetadataConfigurationCommand,
  CreateBucketMetadataTableConfiguration$,
  CreateBucketMetadataTableConfigurationCommand,
  CreateMultipartUpload$,
  CreateMultipartUploadCommand,
  CreateSession$,
  CreateSessionCommand,
  DeleteBucket$,
  DeleteBucketAnalyticsConfiguration$,
  DeleteBucketAnalyticsConfigurationCommand,
  DeleteBucketCommand,
  DeleteBucketCors$,
  DeleteBucketCorsCommand,
  DeleteBucketEncryption$,
  DeleteBucketEncryptionCommand,
  DeleteBucketIntelligentTieringConfiguration$,
  DeleteBucketIntelligentTieringConfigurationCommand,
  DeleteBucketInventoryConfiguration$,
  DeleteBucketInventoryConfigurationCommand,
  DeleteBucketLifecycle$,
  DeleteBucketLifecycleCommand,
  DeleteBucketMetadataConfiguration$,
  DeleteBucketMetadataConfigurationCommand,
  DeleteBucketMetadataTableConfiguration$,
  DeleteBucketMetadataTableConfigurationCommand,
  DeleteBucketMetricsConfiguration$,
  DeleteBucketMetricsConfigurationCommand,
  DeleteBucketOwnershipControls$,
  DeleteBucketOwnershipControlsCommand,
  DeleteBucketPolicy$,
  DeleteBucketPolicyCommand,
  DeleteBucketReplication$,
  DeleteBucketReplicationCommand,
  DeleteBucketTagging$,
  DeleteBucketTaggingCommand,
  DeleteBucketWebsite$,
  DeleteBucketWebsiteCommand,
  DeleteObject$,
  DeleteObjectCommand,
  DeleteObjects$,
  DeleteObjectsCommand,
  DeleteObjectTagging$,
  DeleteObjectTaggingCommand,
  DeletePublicAccessBlock$,
  DeletePublicAccessBlockCommand,
  EncryptionTypeMismatch$,
  GetBucketAbac$,
  GetBucketAbacCommand,
  GetBucketAccelerateConfiguration$,
  GetBucketAccelerateConfigurationCommand,
  GetBucketAcl$,
  GetBucketAclCommand,
  GetBucketAnalyticsConfiguration$,
  GetBucketAnalyticsConfigurationCommand,
  GetBucketCors$,
  GetBucketCorsCommand,
  GetBucketEncryption$,
  GetBucketEncryptionCommand,
  GetBucketIntelligentTieringConfiguration$,
  GetBucketIntelligentTieringConfigurationCommand,
  GetBucketInventoryConfiguration$,
  GetBucketInventoryConfigurationCommand,
  GetBucketLifecycleConfiguration$,
  GetBucketLifecycleConfigurationCommand,
  GetBucketLocation$,
  GetBucketLocationCommand,
  GetBucketLogging$,
  GetBucketLoggingCommand,
  GetBucketMetadataConfiguration$,
  GetBucketMetadataConfigurationCommand,
  GetBucketMetadataTableConfiguration$,
  GetBucketMetadataTableConfigurationCommand,
  GetBucketMetricsConfiguration$,
  GetBucketMetricsConfigurationCommand,
  GetBucketNotificationConfiguration$,
  GetBucketNotificationConfigurationCommand,
  GetBucketOwnershipControls$,
  GetBucketOwnershipControlsCommand,
  GetBucketPolicy$,
  GetBucketPolicyCommand,
  GetBucketPolicyStatus$,
  GetBucketPolicyStatusCommand,
  GetBucketReplication$,
  GetBucketReplicationCommand,
  GetBucketRequestPayment$,
  GetBucketRequestPaymentCommand,
  GetBucketTagging$,
  GetBucketTaggingCommand,
  GetBucketVersioning$,
  GetBucketVersioningCommand,
  GetBucketWebsite$,
  GetBucketWebsiteCommand,
  GetObject$,
  GetObjectAcl$,
  GetObjectAclCommand,
  GetObjectAttributes$,
  GetObjectAttributesCommand,
  GetObjectCommand,
  GetObjectLegalHold$,
  GetObjectLegalHoldCommand,
  GetObjectLockConfiguration$,
  GetObjectLockConfigurationCommand,
  GetObjectRetention$,
  GetObjectRetentionCommand,
  GetObjectTagging$,
  GetObjectTaggingCommand,
  GetObjectTorrent$,
  GetObjectTorrentCommand,
  GetPublicAccessBlock$,
  GetPublicAccessBlockCommand,
  HeadBucket$,
  HeadBucketCommand,
  HeadObject$,
  HeadObjectCommand,
  IdempotencyParameterMismatch$,
  InvalidObjectState$,
  InvalidRequest$,
  InvalidWriteOffset$,
  ListBucketAnalyticsConfigurations$,
  ListBucketAnalyticsConfigurationsCommand,
  ListBucketIntelligentTieringConfigurations$,
  ListBucketIntelligentTieringConfigurationsCommand,
  ListBucketInventoryConfigurations$,
  ListBucketInventoryConfigurationsCommand,
  ListBucketMetricsConfigurations$,
  ListBucketMetricsConfigurationsCommand,
  ListBuckets$,
  ListBucketsCommand,
  ListDirectoryBuckets$,
  ListDirectoryBucketsCommand,
  ListMultipartUploads$,
  ListMultipartUploadsCommand,
  ListObjects$,
  ListObjectsCommand,
  ListObjectsV2$,
  ListObjectsV2Command,
  ListObjectVersions$,
  ListObjectVersionsCommand,
  ListParts$,
  ListPartsCommand,
  NoSuchBucket$,
  NoSuchKey$,
  NoSuchUpload$,
  NotFound$,
  ObjectAlreadyInActiveTierError$,
  ObjectNotInActiveTierError$,
  PutBucketAbac$,
  PutBucketAbacCommand,
  PutBucketAccelerateConfiguration$,
  PutBucketAccelerateConfigurationCommand,
  PutBucketAcl$,
  PutBucketAclCommand,
  PutBucketAnalyticsConfiguration$,
  PutBucketAnalyticsConfigurationCommand,
  PutBucketCors$,
  PutBucketCorsCommand,
  PutBucketEncryption$,
  PutBucketEncryptionCommand,
  PutBucketIntelligentTieringConfiguration$,
  PutBucketIntelligentTieringConfigurationCommand,
  PutBucketInventoryConfiguration$,
  PutBucketInventoryConfigurationCommand,
  PutBucketLifecycleConfiguration$,
  PutBucketLifecycleConfigurationCommand,
  PutBucketLogging$,
  PutBucketLoggingCommand,
  PutBucketMetricsConfiguration$,
  PutBucketMetricsConfigurationCommand,
  PutBucketNotificationConfiguration$,
  PutBucketNotificationConfigurationCommand,
  PutBucketOwnershipControls$,
  PutBucketOwnershipControlsCommand,
  PutBucketPolicy$,
  PutBucketPolicyCommand,
  PutBucketReplication$,
  PutBucketReplicationCommand,
  PutBucketRequestPayment$,
  PutBucketRequestPaymentCommand,
  PutBucketTagging$,
  PutBucketTaggingCommand,
  PutBucketVersioning$,
  PutBucketVersioningCommand,
  PutBucketWebsite$,
  PutBucketWebsiteCommand,
  PutObject$,
  PutObjectAcl$,
  PutObjectAclCommand,
  PutObjectCommand,
  PutObjectLegalHold$,
  PutObjectLegalHoldCommand,
  PutObjectLockConfiguration$,
  PutObjectLockConfigurationCommand,
  PutObjectRetention$,
  PutObjectRetentionCommand,
  PutObjectTagging$,
  PutObjectTaggingCommand,
  PutPublicAccessBlock$,
  PutPublicAccessBlockCommand,
  RenameObject$,
  RenameObjectCommand,
  RestoreObject$,
  RestoreObjectCommand,
  S3Client,
  SelectObjectContent$,
  SelectObjectContentCommand,
  TooManyParts$,
  UpdateBucketMetadataInventoryTableConfiguration$,
  UpdateBucketMetadataInventoryTableConfigurationCommand,
  UpdateBucketMetadataJournalTableConfiguration$,
  UpdateBucketMetadataJournalTableConfigurationCommand,
  UpdateObjectEncryption$,
  UpdateObjectEncryptionCommand,
  UploadPart$,
  UploadPartCommand,
  UploadPartCopy$,
  UploadPartCopyCommand,
  WriteGetObjectResponse$,
  WriteGetObjectResponseCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = S3Client;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("S3Client" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AbortMultipartUpload$, AbortMultipartUploadCommand],
      [CompleteMultipartUpload$, CompleteMultipartUploadCommand],
      [CopyObject$, CopyObjectCommand],
      [CreateBucket$, CreateBucketCommand],
      [CreateBucketMetadataConfiguration$, CreateBucketMetadataConfigurationCommand],
      [CreateBucketMetadataTableConfiguration$, CreateBucketMetadataTableConfigurationCommand],
      [CreateMultipartUpload$, CreateMultipartUploadCommand],
      [CreateSession$, CreateSessionCommand],
      [DeleteBucket$, DeleteBucketCommand],
      [DeleteBucketAnalyticsConfiguration$, DeleteBucketAnalyticsConfigurationCommand],
      [DeleteBucketCors$, DeleteBucketCorsCommand],
      [DeleteBucketEncryption$, DeleteBucketEncryptionCommand],
      [DeleteBucketIntelligentTieringConfiguration$, DeleteBucketIntelligentTieringConfigurationCommand],
      [DeleteBucketInventoryConfiguration$, DeleteBucketInventoryConfigurationCommand],
      [DeleteBucketLifecycle$, DeleteBucketLifecycleCommand],
      [DeleteBucketMetadataConfiguration$, DeleteBucketMetadataConfigurationCommand],
      [DeleteBucketMetadataTableConfiguration$, DeleteBucketMetadataTableConfigurationCommand],
      [DeleteBucketMetricsConfiguration$, DeleteBucketMetricsConfigurationCommand],
      [DeleteBucketOwnershipControls$, DeleteBucketOwnershipControlsCommand],
      [DeleteBucketPolicy$, DeleteBucketPolicyCommand],
      [DeleteBucketReplication$, DeleteBucketReplicationCommand],
      [DeleteBucketTagging$, DeleteBucketTaggingCommand],
      [DeleteBucketWebsite$, DeleteBucketWebsiteCommand],
      [DeleteObject$, DeleteObjectCommand],
      [DeleteObjects$, DeleteObjectsCommand],
      [DeleteObjectTagging$, DeleteObjectTaggingCommand],
      [DeletePublicAccessBlock$, DeletePublicAccessBlockCommand],
      [GetBucketAbac$, GetBucketAbacCommand],
      [GetBucketAccelerateConfiguration$, GetBucketAccelerateConfigurationCommand],
      [GetBucketAcl$, GetBucketAclCommand],
      [GetBucketAnalyticsConfiguration$, GetBucketAnalyticsConfigurationCommand],
      [GetBucketCors$, GetBucketCorsCommand],
      [GetBucketEncryption$, GetBucketEncryptionCommand],
      [GetBucketIntelligentTieringConfiguration$, GetBucketIntelligentTieringConfigurationCommand],
      [GetBucketInventoryConfiguration$, GetBucketInventoryConfigurationCommand],
      [GetBucketLifecycleConfiguration$, GetBucketLifecycleConfigurationCommand],
      [GetBucketLocation$, GetBucketLocationCommand],
      [GetBucketLogging$, GetBucketLoggingCommand],
      [GetBucketMetadataConfiguration$, GetBucketMetadataConfigurationCommand],
      [GetBucketMetadataTableConfiguration$, GetBucketMetadataTableConfigurationCommand],
      [GetBucketMetricsConfiguration$, GetBucketMetricsConfigurationCommand],
      [GetBucketNotificationConfiguration$, GetBucketNotificationConfigurationCommand],
      [GetBucketOwnershipControls$, GetBucketOwnershipControlsCommand],
      [GetBucketPolicy$, GetBucketPolicyCommand],
      [GetBucketPolicyStatus$, GetBucketPolicyStatusCommand],
      [GetBucketReplication$, GetBucketReplicationCommand],
      [GetBucketRequestPayment$, GetBucketRequestPaymentCommand],
      [GetBucketTagging$, GetBucketTaggingCommand],
      [GetBucketVersioning$, GetBucketVersioningCommand],
      [GetBucketWebsite$, GetBucketWebsiteCommand],
      [GetObject$, GetObjectCommand],
      [GetObjectAcl$, GetObjectAclCommand],
      [GetObjectAttributes$, GetObjectAttributesCommand],
      [GetObjectLegalHold$, GetObjectLegalHoldCommand],
      [GetObjectLockConfiguration$, GetObjectLockConfigurationCommand],
      [GetObjectRetention$, GetObjectRetentionCommand],
      [GetObjectTagging$, GetObjectTaggingCommand],
      [GetObjectTorrent$, GetObjectTorrentCommand],
      [GetPublicAccessBlock$, GetPublicAccessBlockCommand],
      [HeadBucket$, HeadBucketCommand],
      [HeadObject$, HeadObjectCommand],
      [ListBucketAnalyticsConfigurations$, ListBucketAnalyticsConfigurationsCommand],
      [ListBucketIntelligentTieringConfigurations$, ListBucketIntelligentTieringConfigurationsCommand],
      [ListBucketInventoryConfigurations$, ListBucketInventoryConfigurationsCommand],
      [ListBucketMetricsConfigurations$, ListBucketMetricsConfigurationsCommand],
      [ListBuckets$, ListBucketsCommand],
      [ListDirectoryBuckets$, ListDirectoryBucketsCommand],
      [ListMultipartUploads$, ListMultipartUploadsCommand],
      [ListObjects$, ListObjectsCommand],
      [ListObjectsV2$, ListObjectsV2Command],
      [ListObjectVersions$, ListObjectVersionsCommand],
      [ListParts$, ListPartsCommand],
      [PutBucketAbac$, PutBucketAbacCommand],
      [PutBucketAccelerateConfiguration$, PutBucketAccelerateConfigurationCommand],
      [PutBucketAcl$, PutBucketAclCommand],
      [PutBucketAnalyticsConfiguration$, PutBucketAnalyticsConfigurationCommand],
      [PutBucketCors$, PutBucketCorsCommand],
      [PutBucketEncryption$, PutBucketEncryptionCommand],
      [PutBucketIntelligentTieringConfiguration$, PutBucketIntelligentTieringConfigurationCommand],
      [PutBucketInventoryConfiguration$, PutBucketInventoryConfigurationCommand],
      [PutBucketLifecycleConfiguration$, PutBucketLifecycleConfigurationCommand],
      [PutBucketLogging$, PutBucketLoggingCommand],
      [PutBucketMetricsConfiguration$, PutBucketMetricsConfigurationCommand],
      [PutBucketNotificationConfiguration$, PutBucketNotificationConfigurationCommand],
      [PutBucketOwnershipControls$, PutBucketOwnershipControlsCommand],
      [PutBucketPolicy$, PutBucketPolicyCommand],
      [PutBucketReplication$, PutBucketReplicationCommand],
      [PutBucketRequestPayment$, PutBucketRequestPaymentCommand],
      [PutBucketTagging$, PutBucketTaggingCommand],
      [PutBucketVersioning$, PutBucketVersioningCommand],
      [PutBucketWebsite$, PutBucketWebsiteCommand],
      [PutObject$, PutObjectCommand],
      [PutObjectAcl$, PutObjectAclCommand],
      [PutObjectLegalHold$, PutObjectLegalHoldCommand],
      [PutObjectLockConfiguration$, PutObjectLockConfigurationCommand],
      [PutObjectRetention$, PutObjectRetentionCommand],
      [PutObjectTagging$, PutObjectTaggingCommand],
      [PutPublicAccessBlock$, PutPublicAccessBlockCommand],
      [RenameObject$, RenameObjectCommand],
      [RestoreObject$, RestoreObjectCommand],
      [SelectObjectContent$, SelectObjectContentCommand],
      [UpdateBucketMetadataInventoryTableConfiguration$, UpdateBucketMetadataInventoryTableConfigurationCommand],
      [UpdateBucketMetadataJournalTableConfiguration$, UpdateBucketMetadataJournalTableConfigurationCommand],
      [UpdateObjectEncryption$, UpdateObjectEncryptionCommand],
      [UploadPart$, UploadPartCommand],
      [UploadPartCopy$, UploadPartCopyCommand],
      [WriteGetObjectResponse$, WriteGetObjectResponseCommand],
    ]),
    errors: [
      AccessDenied$,
      BucketAlreadyExists$,
      BucketAlreadyOwnedByYou$,
      EncryptionTypeMismatch$,
      IdempotencyParameterMismatch$,
      InvalidObjectState$,
      InvalidRequest$,
      InvalidWriteOffset$,
      NoSuchBucket$,
      NoSuchKey$,
      NoSuchUpload$,
      NotFound$,
      ObjectAlreadyInActiveTierError$,
      ObjectNotInActiveTierError$,
      TooManyParts$,
    ],
  });
  runner.run();
}, 30_000);
