import { S3ClientResolvedConfig } from "@aws-sdk/client-s3";

import { FIELD_INIT_TYPE } from "../FIELD_INIT_TYPE";

export const RESOLVED_FIELDS: Record<FIELD_INIT_TYPE, (keyof S3ClientResolvedConfig)[]> = {
  resolvedByConfigResolver: [
    "requestHandler",
    "apiVersion",
    "sha256",
    "urlParser",
    "bodyLengthChecker",
    "streamCollector",
    "base64Decoder",
    "base64Encoder",
    "utf8Decoder",
    "utf8Encoder",
    "runtime",
    "disableHostPrefix",
    "maxAttempts",
    "retryMode",
    "logger",
    "useDualstackEndpoint",
    "useFipsEndpoint",
    "serviceId",
    "region",
    "credentialDefaultProvider",
    "signingEscapePath",
    "useArnRegion",
    "defaultUserAgentProvider",
    "streamHasher",
    "md5",
    "sha1",
    "getAwsChunkedEncodingStream",
    "eventStreamSerdeProvider",
    "defaultsMode",
    "sdkStreamMixin",
    "endpointProvider",
    "tls",
    "isCustomEndpoint",
    "retryStrategy",
    "credentials", // deprecated
    "identity",
    "signer",
    "systemClockOffset",
    "forcePathStyle",
    "useAccelerateEndpoint",
    "disableMultiregionAccessPoints",
    "eventStreamMarshaller",
    "defaultSigningName",
    "useGlobalEndpoint",
  ],
  resolvedOnlyIfProvided: ["customUserAgent", "endpoint"],
  neverResolved: [],
};
