// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  BackupInUseException$,
  BackupNotFoundException$,
  BatchExecuteStatement$,
  BatchExecuteStatementCommand,
  BatchGetItem$,
  BatchGetItemCommand,
  BatchWriteItem$,
  BatchWriteItemCommand,
  ConditionalCheckFailedException$,
  ContinuousBackupsUnavailableException$,
  CreateBackup$,
  CreateBackupCommand,
  CreateGlobalTable$,
  CreateGlobalTableCommand,
  CreateTable$,
  CreateTableCommand,
  DeleteBackup$,
  DeleteBackupCommand,
  DeleteItem$,
  DeleteItemCommand,
  DeleteResourcePolicy$,
  DeleteResourcePolicyCommand,
  DeleteTable$,
  DeleteTableCommand,
  DescribeBackup$,
  DescribeBackupCommand,
  DescribeContinuousBackups$,
  DescribeContinuousBackupsCommand,
  DescribeContributorInsights$,
  DescribeContributorInsightsCommand,
  DescribeEndpoints$,
  DescribeEndpointsCommand,
  DescribeExport$,
  DescribeExportCommand,
  DescribeGlobalTable$,
  DescribeGlobalTableCommand,
  DescribeGlobalTableSettings$,
  DescribeGlobalTableSettingsCommand,
  DescribeImport$,
  DescribeImportCommand,
  DescribeKinesisStreamingDestination$,
  DescribeKinesisStreamingDestinationCommand,
  DescribeLimits$,
  DescribeLimitsCommand,
  DescribeTable$,
  DescribeTableCommand,
  DescribeTableReplicaAutoScaling$,
  DescribeTableReplicaAutoScalingCommand,
  DescribeTimeToLive$,
  DescribeTimeToLiveCommand,
  DisableKinesisStreamingDestination$,
  DisableKinesisStreamingDestinationCommand,
  DuplicateItemException$,
  DynamoDBClient,
  EnableKinesisStreamingDestination$,
  EnableKinesisStreamingDestinationCommand,
  ExecuteStatement$,
  ExecuteStatementCommand,
  ExecuteTransaction$,
  ExecuteTransactionCommand,
  ExportConflictException$,
  ExportNotFoundException$,
  ExportTableToPointInTime$,
  ExportTableToPointInTimeCommand,
  GetItem$,
  GetItemCommand,
  GetResourcePolicy$,
  GetResourcePolicyCommand,
  GlobalTableAlreadyExistsException$,
  GlobalTableNotFoundException$,
  IdempotentParameterMismatchException$,
  ImportConflictException$,
  ImportNotFoundException$,
  ImportTable$,
  ImportTableCommand,
  IndexNotFoundException$,
  InternalServerError$,
  InvalidEndpointException$,
  InvalidExportTimeException$,
  InvalidRestoreTimeException$,
  ItemCollectionSizeLimitExceededException$,
  LimitExceededException$,
  ListBackups$,
  ListBackupsCommand,
  ListContributorInsights$,
  ListContributorInsightsCommand,
  ListExports$,
  ListExportsCommand,
  ListGlobalTables$,
  ListGlobalTablesCommand,
  ListImports$,
  ListImportsCommand,
  ListTables$,
  ListTablesCommand,
  ListTagsOfResource$,
  ListTagsOfResourceCommand,
  PointInTimeRecoveryUnavailableException$,
  PolicyNotFoundException$,
  ProvisionedThroughputExceededException$,
  PutItem$,
  PutItemCommand,
  PutResourcePolicy$,
  PutResourcePolicyCommand,
  Query$,
  QueryCommand,
  ReplicaAlreadyExistsException$,
  ReplicaNotFoundException$,
  ReplicatedWriteConflictException$,
  RequestLimitExceeded$,
  ResourceInUseException$,
  ResourceNotFoundException$,
  RestoreTableFromBackup$,
  RestoreTableFromBackupCommand,
  RestoreTableToPointInTime$,
  RestoreTableToPointInTimeCommand,
  Scan$,
  ScanCommand,
  TableAlreadyExistsException$,
  TableInUseException$,
  TableNotFoundException$,
  TagResource$,
  TagResourceCommand,
  ThrottlingException$,
  TransactGetItems$,
  TransactGetItemsCommand,
  TransactionCanceledException$,
  TransactionConflictException$,
  TransactionInProgressException$,
  TransactWriteItems$,
  TransactWriteItemsCommand,
  UntagResource$,
  UntagResourceCommand,
  UpdateContinuousBackups$,
  UpdateContinuousBackupsCommand,
  UpdateContributorInsights$,
  UpdateContributorInsightsCommand,
  UpdateGlobalTable$,
  UpdateGlobalTableCommand,
  UpdateGlobalTableSettings$,
  UpdateGlobalTableSettingsCommand,
  UpdateItem$,
  UpdateItemCommand,
  UpdateKinesisStreamingDestination$,
  UpdateKinesisStreamingDestinationCommand,
  UpdateTable$,
  UpdateTableCommand,
  UpdateTableReplicaAutoScaling$,
  UpdateTableReplicaAutoScalingCommand,
  UpdateTimeToLive$,
  UpdateTimeToLiveCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = DynamoDBClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("DynamoDBClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [BatchExecuteStatement$, BatchExecuteStatementCommand],
      [BatchGetItem$, BatchGetItemCommand],
      [BatchWriteItem$, BatchWriteItemCommand],
      [CreateBackup$, CreateBackupCommand],
      [CreateGlobalTable$, CreateGlobalTableCommand],
      [CreateTable$, CreateTableCommand],
      [DeleteBackup$, DeleteBackupCommand],
      [DeleteItem$, DeleteItemCommand],
      [DeleteResourcePolicy$, DeleteResourcePolicyCommand],
      [DeleteTable$, DeleteTableCommand],
      [DescribeBackup$, DescribeBackupCommand],
      [DescribeContinuousBackups$, DescribeContinuousBackupsCommand],
      [DescribeContributorInsights$, DescribeContributorInsightsCommand],
      [DescribeEndpoints$, DescribeEndpointsCommand],
      [DescribeExport$, DescribeExportCommand],
      [DescribeGlobalTable$, DescribeGlobalTableCommand],
      [DescribeGlobalTableSettings$, DescribeGlobalTableSettingsCommand],
      [DescribeImport$, DescribeImportCommand],
      [DescribeKinesisStreamingDestination$, DescribeKinesisStreamingDestinationCommand],
      [DescribeLimits$, DescribeLimitsCommand],
      [DescribeTable$, DescribeTableCommand],
      [DescribeTableReplicaAutoScaling$, DescribeTableReplicaAutoScalingCommand],
      [DescribeTimeToLive$, DescribeTimeToLiveCommand],
      [DisableKinesisStreamingDestination$, DisableKinesisStreamingDestinationCommand],
      [EnableKinesisStreamingDestination$, EnableKinesisStreamingDestinationCommand],
      [ExecuteStatement$, ExecuteStatementCommand],
      [ExecuteTransaction$, ExecuteTransactionCommand],
      [ExportTableToPointInTime$, ExportTableToPointInTimeCommand],
      [GetItem$, GetItemCommand],
      [GetResourcePolicy$, GetResourcePolicyCommand],
      [ImportTable$, ImportTableCommand],
      [ListBackups$, ListBackupsCommand],
      [ListContributorInsights$, ListContributorInsightsCommand],
      [ListExports$, ListExportsCommand],
      [ListGlobalTables$, ListGlobalTablesCommand],
      [ListImports$, ListImportsCommand],
      [ListTables$, ListTablesCommand],
      [ListTagsOfResource$, ListTagsOfResourceCommand],
      [PutItem$, PutItemCommand],
      [PutResourcePolicy$, PutResourcePolicyCommand],
      [Query$, QueryCommand],
      [RestoreTableFromBackup$, RestoreTableFromBackupCommand],
      [RestoreTableToPointInTime$, RestoreTableToPointInTimeCommand],
      [Scan$, ScanCommand],
      [TagResource$, TagResourceCommand],
      [TransactGetItems$, TransactGetItemsCommand],
      [TransactWriteItems$, TransactWriteItemsCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateContinuousBackups$, UpdateContinuousBackupsCommand],
      [UpdateContributorInsights$, UpdateContributorInsightsCommand],
      [UpdateGlobalTable$, UpdateGlobalTableCommand],
      [UpdateGlobalTableSettings$, UpdateGlobalTableSettingsCommand],
      [UpdateItem$, UpdateItemCommand],
      [UpdateKinesisStreamingDestination$, UpdateKinesisStreamingDestinationCommand],
      [UpdateTable$, UpdateTableCommand],
      [UpdateTableReplicaAutoScaling$, UpdateTableReplicaAutoScalingCommand],
      [UpdateTimeToLive$, UpdateTimeToLiveCommand],
    ]),
    errors: [
      BackupInUseException$,
      BackupNotFoundException$,
      ConditionalCheckFailedException$,
      ContinuousBackupsUnavailableException$,
      DuplicateItemException$,
      ExportConflictException$,
      ExportNotFoundException$,
      GlobalTableAlreadyExistsException$,
      GlobalTableNotFoundException$,
      IdempotentParameterMismatchException$,
      ImportConflictException$,
      ImportNotFoundException$,
      IndexNotFoundException$,
      InternalServerError$,
      InvalidEndpointException$,
      InvalidExportTimeException$,
      InvalidRestoreTimeException$,
      ItemCollectionSizeLimitExceededException$,
      LimitExceededException$,
      PointInTimeRecoveryUnavailableException$,
      PolicyNotFoundException$,
      ProvisionedThroughputExceededException$,
      ReplicaAlreadyExistsException$,
      ReplicaNotFoundException$,
      ReplicatedWriteConflictException$,
      RequestLimitExceeded$,
      ResourceInUseException$,
      ResourceNotFoundException$,
      TableAlreadyExistsException$,
      TableInUseException$,
      TableNotFoundException$,
      ThrottlingException$,
      TransactionCanceledException$,
      TransactionConflictException$,
      TransactionInProgressException$,
    ],
  });
  runner.run();
}, 30_000);
