import { AssociateWebACLCommandInput, AssociateWebACLCommandOutput } from "../commands/AssociateWebACLCommand";
import { CheckCapacityCommandInput, CheckCapacityCommandOutput } from "../commands/CheckCapacityCommand";
import { CreateIPSetCommandInput, CreateIPSetCommandOutput } from "../commands/CreateIPSetCommand";
import { CreateRegexPatternSetCommandInput, CreateRegexPatternSetCommandOutput } from "../commands/CreateRegexPatternSetCommand";
import { CreateRuleGroupCommandInput, CreateRuleGroupCommandOutput } from "../commands/CreateRuleGroupCommand";
import { CreateWebACLCommandInput, CreateWebACLCommandOutput } from "../commands/CreateWebACLCommand";
import { DeleteIPSetCommandInput, DeleteIPSetCommandOutput } from "../commands/DeleteIPSetCommand";
import { DeleteLoggingConfigurationCommandInput, DeleteLoggingConfigurationCommandOutput } from "../commands/DeleteLoggingConfigurationCommand";
import { DeleteRegexPatternSetCommandInput, DeleteRegexPatternSetCommandOutput } from "../commands/DeleteRegexPatternSetCommand";
import { DeleteRuleGroupCommandInput, DeleteRuleGroupCommandOutput } from "../commands/DeleteRuleGroupCommand";
import { DeleteWebACLCommandInput, DeleteWebACLCommandOutput } from "../commands/DeleteWebACLCommand";
import { DescribeManagedRuleGroupCommandInput, DescribeManagedRuleGroupCommandOutput } from "../commands/DescribeManagedRuleGroupCommand";
import { DisassociateWebACLCommandInput, DisassociateWebACLCommandOutput } from "../commands/DisassociateWebACLCommand";
import { GetIPSetCommandInput, GetIPSetCommandOutput } from "../commands/GetIPSetCommand";
import { GetLoggingConfigurationCommandInput, GetLoggingConfigurationCommandOutput } from "../commands/GetLoggingConfigurationCommand";
import { GetRateBasedStatementManagedKeysCommandInput, GetRateBasedStatementManagedKeysCommandOutput } from "../commands/GetRateBasedStatementManagedKeysCommand";
import { GetRegexPatternSetCommandInput, GetRegexPatternSetCommandOutput } from "../commands/GetRegexPatternSetCommand";
import { GetRuleGroupCommandInput, GetRuleGroupCommandOutput } from "../commands/GetRuleGroupCommand";
import { GetSampledRequestsCommandInput, GetSampledRequestsCommandOutput } from "../commands/GetSampledRequestsCommand";
import { GetWebACLCommandInput, GetWebACLCommandOutput } from "../commands/GetWebACLCommand";
import { GetWebACLForResourceCommandInput, GetWebACLForResourceCommandOutput } from "../commands/GetWebACLForResourceCommand";
import { ListAvailableManagedRuleGroupsCommandInput, ListAvailableManagedRuleGroupsCommandOutput } from "../commands/ListAvailableManagedRuleGroupsCommand";
import { ListIPSetsCommandInput, ListIPSetsCommandOutput } from "../commands/ListIPSetsCommand";
import { ListLoggingConfigurationsCommandInput, ListLoggingConfigurationsCommandOutput } from "../commands/ListLoggingConfigurationsCommand";
import { ListRegexPatternSetsCommandInput, ListRegexPatternSetsCommandOutput } from "../commands/ListRegexPatternSetsCommand";
import { ListResourcesForWebACLCommandInput, ListResourcesForWebACLCommandOutput } from "../commands/ListResourcesForWebACLCommand";
import { ListRuleGroupsCommandInput, ListRuleGroupsCommandOutput } from "../commands/ListRuleGroupsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListWebACLsCommandInput, ListWebACLsCommandOutput } from "../commands/ListWebACLsCommand";
import { PutLoggingConfigurationCommandInput, PutLoggingConfigurationCommandOutput } from "../commands/PutLoggingConfigurationCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateIPSetCommandInput, UpdateIPSetCommandOutput } from "../commands/UpdateIPSetCommand";
import { UpdateRegexPatternSetCommandInput, UpdateRegexPatternSetCommandOutput } from "../commands/UpdateRegexPatternSetCommand";
import { UpdateRuleGroupCommandInput, UpdateRuleGroupCommandOutput } from "../commands/UpdateRuleGroupCommand";
import { UpdateWebACLCommandInput, UpdateWebACLCommandOutput } from "../commands/UpdateWebACLCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateWebACLCommand(input: AssociateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CheckCapacityCommand(input: CheckCapacityCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateIPSetCommand(input: CreateIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRegexPatternSetCommand(input: CreateRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRuleGroupCommand(input: CreateRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateWebACLCommand(input: CreateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteIPSetCommand(input: DeleteIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLoggingConfigurationCommand(input: DeleteLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRegexPatternSetCommand(input: DeleteRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRuleGroupCommand(input: DeleteRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteWebACLCommand(input: DeleteWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeManagedRuleGroupCommand(input: DescribeManagedRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateWebACLCommand(input: DisassociateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetIPSetCommand(input: GetIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoggingConfigurationCommand(input: GetLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRateBasedStatementManagedKeysCommand(input: GetRateBasedStatementManagedKeysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRegexPatternSetCommand(input: GetRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRuleGroupCommand(input: GetRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSampledRequestsCommand(input: GetSampledRequestsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWebACLCommand(input: GetWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWebACLForResourceCommand(input: GetWebACLForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAvailableManagedRuleGroupsCommand(input: ListAvailableManagedRuleGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListIPSetsCommand(input: ListIPSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListLoggingConfigurationsCommand(input: ListLoggingConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRegexPatternSetsCommand(input: ListRegexPatternSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListResourcesForWebACLCommand(input: ListResourcesForWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRuleGroupsCommand(input: ListRuleGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListWebACLsCommand(input: ListWebACLsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutLoggingConfigurationCommand(input: PutLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateIPSetCommand(input: UpdateIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRegexPatternSetCommand(input: UpdateRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRuleGroupCommand(input: UpdateRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateWebACLCommand(input: UpdateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateWebACLCommandOutput>;
export declare function deserializeAws_json1_1CheckCapacityCommand(output: __HttpResponse, context: __SerdeContext): Promise<CheckCapacityCommandOutput>;
export declare function deserializeAws_json1_1CreateIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateIPSetCommandOutput>;
export declare function deserializeAws_json1_1CreateRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1CreateRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateWebACLCommandOutput>;
export declare function deserializeAws_json1_1DeleteIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteIPSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeleteRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteWebACLCommandOutput>;
export declare function deserializeAws_json1_1DescribeManagedRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeManagedRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1DisassociateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateWebACLCommandOutput>;
export declare function deserializeAws_json1_1GetIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetIPSetCommandOutput>;
export declare function deserializeAws_json1_1GetLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1GetRateBasedStatementManagedKeysCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRateBasedStatementManagedKeysCommandOutput>;
export declare function deserializeAws_json1_1GetRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1GetRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1GetSampledRequestsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSampledRequestsCommandOutput>;
export declare function deserializeAws_json1_1GetWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWebACLCommandOutput>;
export declare function deserializeAws_json1_1GetWebACLForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWebACLForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListAvailableManagedRuleGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAvailableManagedRuleGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListIPSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListIPSetsCommandOutput>;
export declare function deserializeAws_json1_1ListLoggingConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListLoggingConfigurationsCommandOutput>;
export declare function deserializeAws_json1_1ListRegexPatternSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRegexPatternSetsCommandOutput>;
export declare function deserializeAws_json1_1ListResourcesForWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListResourcesForWebACLCommandOutput>;
export declare function deserializeAws_json1_1ListRuleGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRuleGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListWebACLsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWebACLsCommandOutput>;
export declare function deserializeAws_json1_1PutLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateIPSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1UpdateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateWebACLCommandOutput>;
