import { ConfigureAgentCommandInput, ConfigureAgentCommandOutput } from "../commands/ConfigureAgentCommand";
import { CreateProfilingGroupCommandInput, CreateProfilingGroupCommandOutput } from "../commands/CreateProfilingGroupCommand";
import { DeleteProfilingGroupCommandInput, DeleteProfilingGroupCommandOutput } from "../commands/DeleteProfilingGroupCommand";
import { DescribeProfilingGroupCommandInput, DescribeProfilingGroupCommandOutput } from "../commands/DescribeProfilingGroupCommand";
import { GetProfileCommandInput, GetProfileCommandOutput } from "../commands/GetProfileCommand";
import { ListProfileTimesCommandInput, ListProfileTimesCommandOutput } from "../commands/ListProfileTimesCommand";
import { ListProfilingGroupsCommandInput, ListProfilingGroupsCommandOutput } from "../commands/ListProfilingGroupsCommand";
import { PostAgentProfileCommandInput, PostAgentProfileCommandOutput } from "../commands/PostAgentProfileCommand";
import { UpdateProfilingGroupCommandInput, UpdateProfilingGroupCommandOutput } from "../commands/UpdateProfilingGroupCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restJson1_1ConfigureAgentCommand(input: ConfigureAgentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateProfilingGroupCommand(input: CreateProfilingGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteProfilingGroupCommand(input: DeleteProfilingGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeProfilingGroupCommand(input: DescribeProfilingGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListProfilingGroupsCommand(input: ListProfilingGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateProfilingGroupCommand(input: UpdateProfilingGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1GetProfileCommand(input: GetProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListProfileTimesCommand(input: ListProfileTimesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1PostAgentProfileCommand(input: PostAgentProfileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restJson1_1ConfigureAgentCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfigureAgentCommandOutput>;
export declare function deserializeAws_restJson1_1CreateProfilingGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateProfilingGroupCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteProfilingGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteProfilingGroupCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeProfilingGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeProfilingGroupCommandOutput>;
export declare function deserializeAws_restJson1_1ListProfilingGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListProfilingGroupsCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateProfilingGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateProfilingGroupCommandOutput>;
export declare function deserializeAws_restJson1_1GetProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetProfileCommandOutput>;
export declare function deserializeAws_restJson1_1ListProfileTimesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListProfileTimesCommandOutput>;
export declare function deserializeAws_restJson1_1PostAgentProfileCommand(output: __HttpResponse, context: __SerdeContext): Promise<PostAgentProfileCommandOutput>;
