export * from "./DeleteLexiconCommand";
export * from "./DescribeVoicesCommand";
export * from "./GetLexiconCommand";
export * from "./GetSpeechSynthesisTaskCommand";
export * from "./ListLexiconsCommand";
export * from "./ListSpeechSynthesisTasksCommand";
export * from "./PutLexiconCommand";
export * from "./StartSpeechSynthesisTaskCommand";
export * from "./SynthesizeSpeechCommand";
