export const _AA = "AgentAttributes";
export const _AAD = "AssistantAssociationData";
export const _AAID = "AssistantAssociationInputData";
export const _AAOD = "AssistantAssociationOutputData";
export const _AAS = "AssistantAssociationSummary";
export const _AASL = "AssistantAssociationSummaryList";
export const _AC = "AssociationConfiguration";
export const _ACC = "AssistantCapabilityConfiguration";
export const _ACD = "AssociationConfigurationData";
export const _ACGAD = "AmazonConnectGuideAssociationData";
export const _ACL = "AssociationConfigurationList";
export const _ACn = "AndConditions";
export const _AD = "AssistantData";
export const _ADE = "AccessDeniedException";
export const _AFN = "AttachmentFileName";
export const _AIAC = "AIAgentConfiguration";
export const _AIACD = "AIAgentConfigurationData";
export const _AIACM = "AIAgentConfigurationMap";
export const _AIAD = "AIAgentData";
export const _AIAS = "AIAgentSummary";
export const _AIASL = "AIAgentSummaryList";
export const _AIAVS = "AIAgentVersionSummary";
export const _AIAVSL = "AIAgentVersionSummariesList";
export const _AIC = "AppIntegrationsConfiguration";
export const _AICs = "AssistantIntegrationConfiguration";
export const _AIGBM = "AIGuardrailBlockedMessaging";
export const _AIGCGPC = "AIGuardrailContextualGroundingPolicyConfig";
export const _AIGCPC = "AIGuardrailContentPolicyConfig";
export const _AIGD = "AIGuardrailDescription";
export const _AIGDu = "AIGuardrailData";
export const _AIGS = "AIGuardrailSummary";
export const _AIGSIPC = "AIGuardrailSensitiveInformationPolicyConfig";
export const _AIGSL = "AIGuardrailSummariesList";
export const _AIGTPC = "AIGuardrailTopicPolicyConfig";
export const _AIGVS = "AIGuardrailVersionSummary";
export const _AIGVSL = "AIGuardrailVersionSummariesList";
export const _AIGWPC = "AIGuardrailWordPolicyConfig";
export const _AIPD = "AIPromptData";
export const _AIPS = "AIPromptSummary";
export const _AIPSL = "AIPromptSummaryList";
export const _AIPTC = "AIPromptTemplateConfiguration";
export const _AIPVS = "AIPromptVersionSummary";
export const _AIPVSL = "AIPromptVersionSummariesList";
export const _AL = "AssistantList";
export const _AMT = "ActivateMessageTemplate";
export const _AMTR = "ActivateMessageTemplateRequest";
export const _AMTRc = "ActivateMessageTemplateResponse";
export const _ARAIAC = "AnswerRecommendationAIAgentConfiguration";
export const _AS = "AssistantSummary";
export const _BFMCFP = "BedrockFoundationModelConfigurationForParsing";
export const _C = "Channel";
export const _CA = "ContactAttributes";
export const _CAA = "CreateAssistantAssociation";
export const _CAAR = "CreateAssistantAssociationRequest";
export const _CAARr = "CreateAssistantAssociationResponse";
export const _CAC = "ContentAssociationContents";
export const _CAD = "ContentAssociationData";
export const _CAIA = "CreateAIAgent";
export const _CAIAR = "CreateAIAgentRequest";
export const _CAIARr = "CreateAIAgentResponse";
export const _CAIAV = "CreateAIAgentVersion";
export const _CAIAVR = "CreateAIAgentVersionRequest";
export const _CAIAVRr = "CreateAIAgentVersionResponse";
export const _CAIG = "CreateAIGuardrail";
export const _CAIGR = "CreateAIGuardrailRequest";
export const _CAIGRr = "CreateAIGuardrailResponse";
export const _CAIGV = "CreateAIGuardrailVersion";
export const _CAIGVR = "CreateAIGuardrailVersionRequest";
export const _CAIGVRr = "CreateAIGuardrailVersionResponse";
export const _CAIP = "CreateAIPrompt";
export const _CAIPR = "CreateAIPromptRequest";
export const _CAIPRr = "CreateAIPromptResponse";
export const _CAIPV = "CreateAIPromptVersion";
export const _CAIPVR = "CreateAIPromptVersionRequest";
export const _CAIPVRr = "CreateAIPromptVersionResponse";
export const _CAK = "ContactAttributeKeys";
export const _CAR = "CreateAssistantRequest";
export const _CARr = "CreateAssistantResponse";
export const _CAS = "ContentAssociationSummary";
export const _CASL = "ContentAssociationSummaryList";
export const _CAr = "CreateAssistant";
export const _CAu = "CustomAttributes";
export const _CC = "ChunkingConfiguration";
export const _CCA = "CreateContentAssociation";
export const _CCAR = "CreateContentAssociationRequest";
export const _CCARr = "CreateContentAssociationResponse";
export const _CCR = "CreateContentRequest";
export const _CCRr = "CreateContentResponse";
export const _CCo = "ConnectConfiguration";
export const _CCon = "ConversationContext";
export const _CCr = "CreateContent";
export const _CD = "ContentData";
export const _CDD = "ContentDataDetails";
export const _CE = "ConflictException";
export const _CFD = "ContentFeedbackData";
export const _CKB = "CreateKnowledgeBase";
export const _CKBR = "CreateKnowledgeBaseRequest";
export const _CKBRr = "CreateKnowledgeBaseResponse";
export const _CMT = "CreateMessageTemplate";
export const _CMTA = "CreateMessageTemplateAttachment";
export const _CMTAR = "CreateMessageTemplateAttachmentRequest";
export const _CMTARr = "CreateMessageTemplateAttachmentResponse";
export const _CMTR = "CreateMessageTemplateRequest";
export const _CMTRr = "CreateMessageTemplateResponse";
export const _CMTV = "CreateMessageTemplateVersion";
export const _CMTVR = "CreateMessageTemplateVersionRequest";
export const _CMTVRr = "CreateMessageTemplateVersionResponse";
export const _CPA = "CustomerProfileAttributes";
export const _CQR = "CreateQuickResponse";
export const _CQRR = "CreateQuickResponseRequest";
export const _CQRRr = "CreateQuickResponseResponse";
export const _CR = "ContentReference";
export const _CS = "CitationSpan";
export const _CSL = "ContentSummaryList";
export const _CSR = "CreateSessionRequest";
export const _CSRr = "CreateSessionResponse";
export const _CSo = "ContentSummary";
export const _CSon = "ConversationState";
export const _CSr = "CreateSession";
export const _Ch = "Channels";
export const _Co = "Configuration";
export const _D = "Document";
export const _DA = "DeleteAssistant";
export const _DAA = "DeleteAssistantAssociation";
export const _DAAR = "DeleteAssistantAssociationRequest";
export const _DAARe = "DeleteAssistantAssociationResponse";
export const _DAIA = "DeleteAIAgent";
export const _DAIAR = "DeleteAIAgentRequest";
export const _DAIARe = "DeleteAIAgentResponse";
export const _DAIAV = "DeleteAIAgentVersion";
export const _DAIAVR = "DeleteAIAgentVersionRequest";
export const _DAIAVRe = "DeleteAIAgentVersionResponse";
export const _DAIG = "DeleteAIGuardrail";
export const _DAIGR = "DeleteAIGuardrailRequest";
export const _DAIGRe = "DeleteAIGuardrailResponse";
export const _DAIGV = "DeleteAIGuardrailVersion";
export const _DAIGVR = "DeleteAIGuardrailVersionRequest";
export const _DAIGVRe = "DeleteAIGuardrailVersionResponse";
export const _DAIP = "DeleteAIPrompt";
export const _DAIPR = "DeleteAIPromptRequest";
export const _DAIPRe = "DeleteAIPromptResponse";
export const _DAIPV = "DeleteAIPromptVersion";
export const _DAIPVR = "DeleteAIPromptVersionRequest";
export const _DAIPVRe = "DeleteAIPromptVersionResponse";
export const _DAR = "DeleteAssistantRequest";
export const _DARe = "DeleteAssistantResponse";
export const _DC = "DeleteContent";
export const _DCA = "DeleteContentAssociation";
export const _DCAR = "DeleteContentAssociationRequest";
export const _DCARe = "DeleteContentAssociationResponse";
export const _DCR = "DeleteContentRequest";
export const _DCRe = "DeleteContentResponse";
export const _DD = "DataDetails";
export const _DIJ = "DeleteImportJob";
export const _DIJR = "DeleteImportJobRequest";
export const _DIJRe = "DeleteImportJobResponse";
export const _DKB = "DeleteKnowledgeBase";
export const _DKBR = "DeleteKnowledgeBaseRequest";
export const _DKBRe = "DeleteKnowledgeBaseResponse";
export const _DMT = "DeactivateMessageTemplate";
export const _DMTA = "DeleteMessageTemplateAttachment";
export const _DMTAR = "DeleteMessageTemplateAttachmentRequest";
export const _DMTARe = "DeleteMessageTemplateAttachmentResponse";
export const _DMTR = "DeactivateMessageTemplateRequest";
export const _DMTRe = "DeactivateMessageTemplateResponse";
export const _DMTRel = "DeleteMessageTemplateRequest";
export const _DMTRele = "DeleteMessageTemplateResponse";
export const _DMTe = "DeleteMessageTemplate";
export const _DQR = "DeleteQuickResponse";
export const _DQRR = "DeleteQuickResponseRequest";
export const _DQRRe = "DeleteQuickResponseResponse";
export const _DR = "DataReference";
export const _DS = "DataSummary";
export const _DSL = "DataSummaryList";
export const _DT = "DocumentText";
export const _EH = "EmailHeader";
export const _EHV = "EmailHeaderValue";
export const _EHm = "EmailHeaders";
export const _EMTC = "EmailMessageTemplateContent";
export const _EMTCB = "EmailMessageTemplateContentBody";
export const _EMTD = "ExtendedMessageTemplateData";
export const _ESC = "ExternalSourceConfiguration";
export const _F = "Filter";
export const _FL = "FilterList";
export const _FSCC = "FixedSizeChunkingConfiguration";
export const _GA = "GetAssistant";
export const _GAA = "GetAssistantAssociation";
export const _GAAR = "GetAssistantAssociationRequest";
export const _GAARe = "GetAssistantAssociationResponse";
export const _GAIA = "GetAIAgent";
export const _GAIAR = "GetAIAgentRequest";
export const _GAIARe = "GetAIAgentResponse";
export const _GAIG = "GetAIGuardrail";
export const _GAIGR = "GetAIGuardrailRequest";
export const _GAIGRe = "GetAIGuardrailResponse";
export const _GAIP = "GetAIPrompt";
export const _GAIPR = "GetAIPromptRequest";
export const _GAIPRe = "GetAIPromptResponse";
export const _GAR = "GetAssistantRequest";
export const _GARe = "GetAssistantResponse";
export const _GC = "GroupingCriteria";
export const _GCA = "GetContentAssociation";
export const _GCAR = "GetContentAssociationRequest";
export const _GCARe = "GetContentAssociationResponse";
export const _GCDD = "GenerativeChunkDataDetails";
export const _GCFC = "GuardrailContentFilterConfig";
export const _GCFCu = "GuardrailContentFiltersConfig";
export const _GCFD = "GenerativeContentFeedbackData";
export const _GCFT = "GuardrailContentFilterType";
export const _GCGFC = "GuardrailContextualGroundingFilterConfig";
export const _GCGFCu = "GuardrailContextualGroundingFiltersConfig";
export const _GCGFT = "GuardrailContextualGroundingFilterThreshold";
export const _GCGFTu = "GuardrailContextualGroundingFilterType";
export const _GCR = "GetContentRequest";
export const _GCRe = "GetContentResponse";
export const _GCS = "GetContentSummary";
export const _GCSR = "GetContentSummaryRequest";
export const _GCSRe = "GetContentSummaryResponse";
export const _GCe = "GetContent";
export const _GCr = "GroupingConfiguration";
export const _GDD = "GenerativeDataDetails";
export const _GFS = "GuardrailFilterStrength";
export const _GIJ = "GetImportJob";
export const _GIJR = "GetImportJobRequest";
export const _GIJRe = "GetImportJobResponse";
export const _GKB = "GetKnowledgeBase";
export const _GKBR = "GetKnowledgeBaseRequest";
export const _GKBRe = "GetKnowledgeBaseResponse";
export const _GMT = "GetMessageTemplate";
export const _GMTR = "GetMessageTemplateRequest";
export const _GMTRe = "GetMessageTemplateResponse";
export const _GMWC = "GuardrailManagedWordsConfig";
export const _GMWLC = "GuardrailManagedWordListsConfig";
export const _GMWT = "GuardrailManagedWordsType";
export const _GNM = "GetNextMessage";
export const _GNMR = "GetNextMessageRequest";
export const _GNMRe = "GetNextMessageResponse";
export const _GPEC = "GuardrailPiiEntityConfig";
export const _GPECu = "GuardrailPiiEntitiesConfig";
export const _GPET = "GuardrailPiiEntityType";
export const _GQR = "GetQuickResponse";
export const _GQRR = "GetQuickResponseRequest";
export const _GQRRe = "GetQuickResponseResponse";
export const _GR = "GenerativeReference";
export const _GRC = "GuardrailRegexConfig";
export const _GRCu = "GuardrailRegexesConfig";
export const _GRD = "GuardrailRegexDescription";
export const _GRN = "GuardrailRegexName";
export const _GRP = "GuardrailRegexPattern";
export const _GRR = "GetRecommendationsRequest";
export const _GRRe = "GetRecommendationsResponse";
export const _GRe = "GetRecommendations";
export const _GS = "GetSession";
export const _GSIA = "GuardrailSensitiveInformationAction";
export const _GSR = "GetSessionRequest";
export const _GSRe = "GetSessionResponse";
export const _GTC = "GuardrailTopicConfig";
export const _GTCu = "GuardrailTopicsConfig";
export const _GTD = "GuardrailTopicDefinition";
export const _GTE = "GuardrailTopicExample";
export const _GTEu = "GuardrailTopicExamples";
export const _GTN = "GuardrailTopicName";
export const _GTT = "GuardrailTopicType";
export const _GV = "GroupingValue";
export const _GVr = "GroupingValues";
export const _GWC = "GuardrailWordConfig";
export const _GWCu = "GuardrailWordsConfig";
export const _GWT = "GuardrailWordText";
export const _H = "Highlight";
export const _HCC = "HierarchicalChunkingConfiguration";
export const _HCLC = "HierarchicalChunkingLevelConfiguration";
export const _HCLCi = "HierarchicalChunkingLevelConfigurations";
export const _Hi = "Highlights";
export const _IDDD = "IntentDetectedDataDetails";
export const _IID = "IntentInputData";
export const _IJD = "ImportJobData";
export const _IJL = "ImportJobList";
export const _IJS = "ImportJobSummary";
export const _KBACD = "KnowledgeBaseAssociationConfigurationData";
export const _KBAD = "KnowledgeBaseAssociationData";
export const _KBD = "KnowledgeBaseData";
export const _KBL = "KnowledgeBaseList";
export const _KBS = "KnowledgeBaseSummary";
export const _LA = "ListAssistants";
export const _LAA = "ListAssistantAssociations";
export const _LAAR = "ListAssistantAssociationsRequest";
export const _LAARi = "ListAssistantAssociationsResponse";
export const _LAIA = "ListAIAgents";
export const _LAIAR = "ListAIAgentsRequest";
export const _LAIARi = "ListAIAgentsResponse";
export const _LAIAV = "ListAIAgentVersions";
export const _LAIAVR = "ListAIAgentVersionsRequest";
export const _LAIAVRi = "ListAIAgentVersionsResponse";
export const _LAIG = "ListAIGuardrails";
export const _LAIGR = "ListAIGuardrailsRequest";
export const _LAIGRi = "ListAIGuardrailsResponse";
export const _LAIGV = "ListAIGuardrailVersions";
export const _LAIGVR = "ListAIGuardrailVersionsRequest";
export const _LAIGVRi = "ListAIGuardrailVersionsResponse";
export const _LAIP = "ListAIPrompts";
export const _LAIPR = "ListAIPromptsRequest";
export const _LAIPRi = "ListAIPromptsResponse";
export const _LAIPV = "ListAIPromptVersions";
export const _LAIPVR = "ListAIPromptVersionsRequest";
export const _LAIPVRi = "ListAIPromptVersionsResponse";
export const _LAR = "ListAssistantsRequest";
export const _LARi = "ListAssistantsResponse";
export const _LC = "ListContents";
export const _LCA = "ListContentAssociations";
export const _LCAR = "ListContentAssociationsRequest";
export const _LCARi = "ListContentAssociationsResponse";
export const _LCR = "ListContentsRequest";
export const _LCRi = "ListContentsResponse";
export const _LIJ = "ListImportJobs";
export const _LIJR = "ListImportJobsRequest";
export const _LIJRi = "ListImportJobsResponse";
export const _LKB = "ListKnowledgeBases";
export const _LKBR = "ListKnowledgeBasesRequest";
export const _LKBRi = "ListKnowledgeBasesResponse";
export const _LM = "ListMessages";
export const _LMR = "ListMessagesRequest";
export const _LMRi = "ListMessagesResponse";
export const _LMT = "ListMessageTemplates";
export const _LMTR = "ListMessageTemplatesRequest";
export const _LMTRi = "ListMessageTemplatesResponse";
export const _LMTV = "ListMessageTemplateVersions";
export const _LMTVR = "ListMessageTemplateVersionsRequest";
export const _LMTVRi = "ListMessageTemplateVersionsResponse";
export const _LQR = "ListQuickResponses";
export const _LQRR = "ListQuickResponsesRequest";
export const _LQRRi = "ListQuickResponsesResponse";
export const _LTFR = "ListTagsForResource";
export const _LTFRR = "ListTagsForResourceRequest";
export const _LTFRRi = "ListTagsForResourceResponse";
export const _MC = "MessageConfiguration";
export const _MD = "MessageData";
export const _MI = "MessageInput";
export const _ML = "MessageList";
export const _MO = "MessageOutput";
export const _MSAIAC = "ManualSearchAIAgentConfiguration";
export const _MSC = "ManagedSourceConfiguration";
export const _MTA = "MessageTemplateAttachment";
export const _MTAKL = "MessageTemplateAttributeKeyList";
export const _MTAL = "MessageTemplateAttachmentList";
export const _MTAV = "MessageTemplateAttributeValue";
export const _MTAe = "MessageTemplateAttributes";
export const _MTBCP = "MessageTemplateBodyContentProvider";
export const _MTCP = "MessageTemplateContentProvider";
export const _MTD = "MessageTemplateData";
export const _MTFF = "MessageTemplateFilterField";
export const _MTFFL = "MessageTemplateFilterFieldList";
export const _MTOF = "MessageTemplateOrderField";
export const _MTQF = "MessageTemplateQueryField";
export const _MTQFL = "MessageTemplateQueryFieldList";
export const _MTS = "MessageTemplateSummary";
export const _MTSE = "MessageTemplateSearchExpression";
export const _MTSL = "MessageTemplateSummaryList";
export const _MTSRD = "MessageTemplateSearchResultData";
export const _MTSRL = "MessageTemplateSearchResultsList";
export const _MTVS = "MessageTemplateVersionSummary";
export const _MTVSL = "MessageTemplateVersionSummaryList";
export const _NESS = "NonEmptySensitiveString";
export const _NEUS = "NonEmptyUnlimitedString";
export const _NRR = "NotifyRecommendationsReceived";
export const _NRRE = "NotifyRecommendationsReceivedError";
export const _NRREL = "NotifyRecommendationsReceivedErrorList";
export const _NRRR = "NotifyRecommendationsReceivedRequest";
export const _NRRRo = "NotifyRecommendationsReceivedResponse";
export const _OC = "OrConditions";
export const _OCr = "OrCondition";
export const _PC = "ParsingConfiguration";
export const _PF = "PutFeedback";
export const _PFE = "PreconditionFailedException";
export const _PFR = "PutFeedbackRequest";
export const _PFRu = "PutFeedbackResponse";
export const _PP = "ParsingPrompt";
export const _QA = "QueryAssistant";
export const _QAR = "QueryAssistantRequest";
export const _QARu = "QueryAssistantResponse";
export const _QC = "QueryCondition";
export const _QCE = "QueryConditionExpression";
export const _QCI = "QueryConditionItem";
export const _QID = "QueryInputData";
export const _QRC = "QuickResponseContent";
export const _QRCP = "QuickResponseContentProvider";
export const _QRCu = "QuickResponseContents";
export const _QRD = "QuickResponseData";
export const _QRDP = "QuickResponseDataProvider";
export const _QRFF = "QuickResponseFilterField";
export const _QRFFL = "QuickResponseFilterFieldList";
export const _QRL = "QueryResultsList";
export const _QROF = "QuickResponseOrderField";
export const _QRQF = "QuickResponseQueryField";
export const _QRQFL = "QuickResponseQueryFieldList";
export const _QRS = "QuickResponseSummary";
export const _QRSE = "QuickResponseSearchExpression";
export const _QRSL = "QuickResponseSummaryList";
export const _QRSRD = "QuickResponseSearchResultData";
export const _QRSRL = "QuickResponseSearchResultsList";
export const _QRTD = "QueryRecommendationTriggerData";
export const _QT = "QueryText";
export const _QTID = "QueryTextInputData";
export const _RAAIA = "RemoveAssistantAIAgent";
export const _RAAIAR = "RemoveAssistantAIAgentRequest";
export const _RAAIARe = "RemoveAssistantAIAgentResponse";
export const _RC = "RenderingConfiguration";
export const _RD = "RankingData";
export const _RDe = "RecommendationData";
export const _RDes = "ResultData";
export const _RKBTU = "RemoveKnowledgeBaseTemplateUri";
export const _RKBTUR = "RemoveKnowledgeBaseTemplateUriRequest";
export const _RKBTURe = "RemoveKnowledgeBaseTemplateUriResponse";
export const _RL = "RecommendationList";
export const _RMT = "RenderMessageTemplate";
export const _RMTR = "RenderMessageTemplateRequest";
export const _RMTRe = "RenderMessageTemplateResponse";
export const _RNFE = "ResourceNotFoundException";
export const _RSD = "RuntimeSessionData";
export const _RSDL = "RuntimeSessionDataList";
export const _RSDV = "RuntimeSessionDataValue";
export const _RT = "RecommendationTrigger";
export const _RTD = "RecommendationTriggerData";
export const _RTE = "RequestTimeoutException";
export const _RTL = "RecommendationTriggerList";
export const _SA = "SystemAttributes";
export const _SC = "SourceConfiguration";
export const _SCC = "SemanticChunkingConfiguration";
export const _SCDD = "SourceContentDataDetails";
export const _SCR = "SearchContentRequest";
export const _SCRe = "SearchContentResponse";
export const _SCU = "StartContentUpload";
export const _SCUR = "StartContentUploadRequest";
export const _SCURt = "StartContentUploadResponse";
export const _SCe = "SearchContent";
export const _SD = "SessionData";
export const _SE = "SearchExpression";
export const _SEA = "SystemEndpointAttributes";
export const _SIC = "SessionIntegrationConfiguration";
export const _SIJ = "StartImportJob";
export const _SIJR = "StartImportJobRequest";
export const _SIJRt = "StartImportJobResponse";
export const _SM = "SendMessage";
export const _SMR = "SendMessageRequest";
export const _SMRe = "SendMessageResponse";
export const _SMSMTC = "SMSMessageTemplateContent";
export const _SMSMTCB = "SMSMessageTemplateContentBody";
export const _SMT = "SearchMessageTemplates";
export const _SMTR = "SearchMessageTemplatesRequest";
export const _SMTRe = "SearchMessageTemplatesResponse";
export const _SQEE = "ServiceQuotaExceededException";
export const _SQR = "SearchQuickResponses";
export const _SQRR = "SearchQuickResponsesRequest";
export const _SQRRe = "SearchQuickResponsesResponse";
export const _SS = "SensitiveString";
export const _SSAIAC = "SelfServiceAIAgentConfiguration";
export const _SSCH = "SelfServiceConversationHistory";
export const _SSCHL = "SelfServiceConversationHistoryList";
export const _SSEC = "ServerSideEncryptionConfiguration";
export const _SSR = "SearchSessionsRequest";
export const _SSRe = "SearchSessionsResponse";
export const _SSe = "SessionSummary";
export const _SSea = "SearchSessions";
export const _SSes = "SessionSummaries";
export const _SU = "SeedUrl";
export const _SUe = "SeedUrls";
export const _TAIP = "TextAIPrompt";
export const _TC = "TagCondition";
export const _TD = "TextData";
export const _TE = "ThrottlingException";
export const _TF = "TagFilter";
export const _TFAIPETC = "TextFullAIPromptEditTemplateConfiguration";
export const _TM = "TextMessage";
export const _TMTE = "TooManyTagsException";
export const _TR = "TagResource";
export const _TRR = "TagResourceRequest";
export const _TRRa = "TagResourceResponse";
export const _U = "Url";
export const _UAAIA = "UpdateAssistantAIAgent";
export const _UAAIAR = "UpdateAssistantAIAgentRequest";
export const _UAAIARp = "UpdateAssistantAIAgentResponse";
export const _UAIA = "UpdateAIAgent";
export const _UAIAR = "UpdateAIAgentRequest";
export const _UAIARp = "UpdateAIAgentResponse";
export const _UAIG = "UpdateAIGuardrail";
export const _UAIGR = "UpdateAIGuardrailRequest";
export const _UAIGRp = "UpdateAIGuardrailResponse";
export const _UAIP = "UpdateAIPrompt";
export const _UAIPR = "UpdateAIPromptRequest";
export const _UAIPRp = "UpdateAIPromptResponse";
export const _UC = "UrlConfiguration";
export const _UCR = "UpdateContentRequest";
export const _UCRp = "UpdateContentResponse";
export const _UCp = "UpdateContent";
export const _UE = "UnauthorizedException";
export const _UFL = "UrlFilterList";
export const _UFP = "UrlFilterPattern";
export const _UKBTU = "UpdateKnowledgeBaseTemplateUri";
export const _UKBTUR = "UpdateKnowledgeBaseTemplateUriRequest";
export const _UKBTURp = "UpdateKnowledgeBaseTemplateUriResponse";
export const _UMT = "UpdateMessageTemplate";
export const _UMTM = "UpdateMessageTemplateMetadata";
export const _UMTMR = "UpdateMessageTemplateMetadataRequest";
export const _UMTMRp = "UpdateMessageTemplateMetadataResponse";
export const _UMTR = "UpdateMessageTemplateRequest";
export const _UMTRp = "UpdateMessageTemplateResponse";
export const _UQR = "UpdateQuickResponse";
export const _UQRR = "UpdateQuickResponseRequest";
export const _UQRRp = "UpdateQuickResponseResponse";
export const _UR = "UntagResource";
export const _URR = "UntagResourceRequest";
export const _URRn = "UntagResourceResponse";
export const _US = "UpdateSession";
export const _USD = "UpdateSessionData";
export const _USDR = "UpdateSessionDataRequest";
export const _USDRp = "UpdateSessionDataResponse";
export const _USR = "UpdateSessionRequest";
export const _USRp = "UpdateSessionResponse";
export const _VE = "ValidationException";
export const _VIC = "VectorIngestionConfiguration";
export const _WCC = "WebCrawlerConfiguration";
export const _WCL = "WebCrawlerLimits";
export const _a = "association";
export const _aA = "assistantArn";
export const _aAA = "aiAgentArn";
export const _aAAs = "assistantAssociationArn";
export const _aAC = "aiAgentConfiguration";
export const _aAI = "aiAgentId";
export const _aAIs = "assistantAssociationId";
export const _aAS = "aiAgentSummary";
export const _aASi = "aiAgentSummaries";
export const _aASs = "assistantAssociationSummaries";
export const _aAT = "aiAgentType";
export const _aAVS = "aiAgentVersionSummaries";
export const _aAg = "agentAttributes";
export const _aAi = "aiAgent";
export const _aAs = "assistantAssociation";
export const _aC = "associationConfigurations";
export const _aCD = "associationConfigurationData";
export const _aCGA = "amazonConnectGuideAssociation";
export const _aCn = "andConditions";
export const _aD = "associationData";
export const _aF = "apiFormat";
export const _aFl = "allowFuzziness";
export const _aG = "aiGuardrail";
export const _aGA = "aiGuardrailArn";
export const _aGAIGI = "answerGenerationAIGuardrailId";
export const _aGAIPI = "answerGenerationAIPromptId";
export const _aGI = "aiGuardrailId";
export const _aGS = "aiGuardrailSummary";
export const _aGSi = "aiGuardrailSummaries";
export const _aGVS = "aiGuardrailVersionSummaries";
export const _aI = "assistantId";
export const _aIA = "appIntegrationArn";
export const _aId = "additionalInformation";
export const _aIp = "appIntegrations";
export const _aIs = "associationId";
export const _aIt = "attachmentId";
export const _aItt = "attributesInterpolated";
export const _aN = "accountNumber";
export const _aNI = "attributesNotInterpolated";
export const _aP = "aiPrompt";
export const _aPA = "aiPromptArn";
export const _aPI = "aiPromptId";
export const _aPS = "aiPromptSummary";
export const _aPSi = "aiPromptSummaries";
export const _aPVS = "aiPromptVersionSummaries";
export const _aRAIAC = "answerRecommendationAIAgentConfiguration";
export const _aS = "assistantSummaries";
export const _aT = "associationType";
export const _aTt = "attributeTypes";
export const _aVN = "activeVersionNumber";
export const _ac = "action";
export const _ad = "address1";
export const _add = "address2";
export const _addr = "address3";
export const _addre = "address4";
export const _addres = "address";
export const _as = "assistant";
export const _at = "attachment";
export const _att = "attachments";
export const _attr = "attributes";
export const _b = "body";
export const _bA = "billingAddress1";
export const _bAi = "billingAddress2";
export const _bAil = "billingAddress3";
export const _bAill = "billingAddress4";
export const _bC = "billingCity";
export const _bCi = "billingCounty";
export const _bCil = "billingCountry";
export const _bD = "birthDate";
export const _bEA = "businessEmailAddress";
export const _bFMC = "bedrockFoundationModelConfiguration";
export const _bIM = "blockedInputMessaging";
export const _bN = "businessName";
export const _bOI = "beginOffsetInclusive";
export const _bOM = "blockedOutputsMessaging";
export const _bP = "billingProvince";
export const _bPC = "billingPostalCode";
export const _bPN = "businessPhoneNumber";
export const _bPT = "breakpointPercentileThreshold";
export const _bR = "botResponse";
export const _bS = "billingState";
export const _bSu = "bufferSize";
export const _c = "client";
export const _cA = "contentArn";
export const _cAA = "contentAssociationArn";
export const _cAI = "contentAssociationId";
export const _cAS = "contentAssociationSummaries";
export const _cAo = "contentAssociation";
export const _cAu = "customAttributes";
export const _cC = "capabilityConfiguration";
export const _cCh = "chunkingConfiguration";
export const _cCo = "conversationContext";
export const _cCon = "connectConfiguration";
export const _cD = "contentDisposition";
export const _cDo = "contentData";
export const _cE = "customerEndpoint";
export const _cF = "contentFeedback";
export const _cGPC = "contextualGroundingPolicyConfig";
export const _cI = "contentId";
export const _cL = "crawlerLimits";
export const _cPA = "customerProfileAttributes";
export const _cPC = "contentPolicyConfig";
export const _cR = "contentReference";
export const _cS = "chunkingStrategy";
export const _cSD = "conversationSessionData";
export const _cSh = "channelSubtype";
export const _cSi = "citationSpan";
export const _cSo = "contentSummary";
export const _cSon = "conversationState";
export const _cSont = "contentSummaries";
export const _cT = "contentType";
export const _cTF = "contentTagFilter";
export const _cTl = "clientToken";
export const _cTr = "createdTime";
export const _ch = "channels";
export const _ci = "city";
export const _co = "configuration";
export const _com = "completion";
export const _comp = "comparator";
export const _con = "content";
export const _cont = "contents";
export const _cou = "county";
export const _coun = "country";
export const _cr = "criteria";
export const _cu = "custom";
export const _d = "description";
export const _dA = "defaultAttributes";
export const _da = "data";
export const _de = "details";
export const _def = "definition";
export const _do = "document";
export const _e = "error";
export const _eA = "emailAddress";
export const _eF = "exclusionFilters";
export const _eOE = "endOffsetExclusive";
export const _eSC = "externalSourceConfiguration";
export const _em = "email";
export const _er = "errors";
export const _ex = "excerpt";
export const _exa = "examples";
export const _f = "field";
export const _fC = "filtersConfig";
export const _fI = "flowId";
export const _fN = "firstName";
export const _fRR = "failedRecordReport";
export const _fSCC = "fixedSizeChunkingConfiguration";
export const _fi = "filters";
export const _g = "gender";
export const _gC = "groupingConfiguration";
export const _gCD = "generativeChunkData";
export const _gCFD = "generativeContentFeedbackData";
export const _gD = "generativeData";
export const _gFM = "generateFillerMessage";
export const _gI = "generationId";
export const _gR = "generativeReference";
export const _h = "highlights";
export const _hCC = "hierarchicalChunkingConfiguration";
export const _hE = "httpError";
export const _hPN = "homePhoneNumber";
export const _hQ = "httpQuery";
export const _hTI = "headersToInclude";
export const _he = "headers";
export const _ht = "html";
export const _htt = "http";
export const _i = "intent";
export const _iA = "isActive";
export const _iC = "integrationConfiguration";
export const _iDD = "intentDetectedData";
export const _iF = "inclusionFilters";
export const _iFR = "ingestionFailureReasons";
export const _iI = "instanceId";
export const _iID = "intentInputData";
export const _iIn = "intentId";
export const _iJ = "importJob";
export const _iJI = "importJobId";
export const _iJS = "importJobSummaries";
export const _iJT = "importJobType";
export const _iLGAIPI = "intentLabelingGenerationAIPromptId";
export const _iNE = "includeNoExistence";
export const _iS = "inputStrength";
export const _iSn = "ingestionStatus";
export const _iT = "inputTranscript";
export const _id = "id";
export const _k = "key";
export const _kB = "knowledgeBase";
export const _kBA = "knowledgeBaseArn";
export const _kBACD = "knowledgeBaseAssociationConfigurationData";
export const _kBAn = "knowledgeBaseAssociation";
export const _kBI = "knowledgeBaseId";
export const _kBS = "knowledgeBaseSummaries";
export const _kBT = "knowledgeBaseType";
export const _kKI = "kmsKeyId";
export const _l = "locale";
export const _lC = "levelConfigurations";
export const _lCMT = "lastContentModificationTime";
export const _lMB = "lastModifiedBy";
export const _lMT = "lastModifiedTime";
export const _lN = "lastName";
export const _lOU = "linkOutUri";
export const _la = "language";
export const _m = "message";
export const _mA = "modelArn";
export const _mAa = "mailingAddress1";
export const _mAai = "mailingAddress2";
export const _mAail = "mailingAddress3";
export const _mAaili = "mailingAddress4";
export const _mC = "mailingCity";
export const _mCa = "mailingCounty";
export const _mCai = "mailingCountry";
export const _mI = "modelId";
export const _mIe = "messageId";
export const _mN = "middleName";
export const _mP = "mailingProvince";
export const _mPC = "mailingPostalCode";
export const _mPN = "mobilePhoneNumber";
export const _mR = "maxResults";
export const _mS = "mailingState";
export const _mSAIAC = "manualSearchAIAgentConfiguration";
export const _mSC = "managedSourceConfiguration";
export const _mT = "modifiedTime";
export const _mTA = "messageTemplateArn";
export const _mTCS = "messageTemplateContentSha256";
export const _mTI = "messageTemplateId";
export const _mTS = "messageTemplateSummaries";
export const _mTVS = "messageTemplateVersionSummaries";
export const _mTa = "maxTokens";
export const _mTe = "messageTemplate";
export const _mWLC = "managedWordListsConfig";
export const _ma = "markdown";
export const _me = "metadata";
export const _mes = "messages";
export const _n = "name";
export const _nCT = "nextChunkToken";
export const _nMT = "nextMessageToken";
export const _nT = "nextToken";
export const _na = "namespace";
export const _o = "origin";
export const _oC = "orConditions";
export const _oF = "objectFields";
export const _oKBST = "overrideKnowledgeBaseSearchType";
export const _oLOU = "overrideLinkOutUri";
export const _oOF = "orderOnField";
export const _oP = "overlapPercentage";
export const _oS = "outputStrength";
export const _oT = "overlapTokens";
export const _op = "operator";
export const _or = "order";
export const _p = "province";
export const _pARN = "profileARN";
export const _pC = "postalCode";
export const _pCa = "parsingConfiguration";
export const _pEC = "piiEntitiesConfig";
export const _pI = "profileId";
export const _pN = "phoneNumber";
export const _pP = "parsingPrompt";
export const _pPT = "parsingPromptText";
export const _pS = "parsingStrategy";
export const _pT = "partyType";
export const _pTl = "plainText";
export const _pUTTL = "presignedUrlTimeToLive";
export const _pa = "pattern";
export const _par = "participant";
export const _pr = "priority";
export const _q = "queries";
export const _qC = "queryCondition";
export const _qID = "queryInputData";
export const _qR = "quickResponse";
export const _qRA = "quickResponseArn";
export const _qRAIPI = "queryReformulationAIPromptId";
export const _qRI = "quickResponseId";
export const _qRS = "quickResponseSummaries";
export const _qT = "queryText";
export const _qTID = "queryTextInputData";
export const _qu = "query";
export const _r = "reason";
export const _rA = "resourceArn";
export const _rC = "regexesConfig";
export const _rCe = "renderingConfiguration";
export const _rD = "rankingData";
export const _rDe = "removeDescription";
export const _rGC = "removeGroupingConfiguration";
export const _rI = "revisionId";
export const _rIe = "recommendationId";
export const _rIec = "recommendationIds";
export const _rIes = "resultId";
export const _rL = "relevanceLevel";
export const _rLa = "rateLimit";
export const _rMI = "requestMessageId";
export const _rN = "resourceName";
export const _rOLOU = "removeOverrideLinkOutUri";
export const _rS = "relevanceScore";
export const _rSK = "removeShortcutKey";
export const _rT = "referenceType";
export const _re = "reference";
export const _rec = "recommendations";
export const _ref = "references";
export const _rel = "relevance";
export const _res = "response";
export const _resu = "results";
export const _s = "status";
export const _sA = "shippingAddress1";
export const _sAe = "sessionArn";
export const _sAh = "shippingAddress2";
export const _sAhi = "shippingAddress3";
export const _sAhip = "shippingAddress4";
export const _sAy = "systemAttributes";
export const _sC = "sourceConfiguration";
export const _sCC = "semanticChunkingConfiguration";
export const _sCD = "sourceContentData";
export const _sCh = "shippingCity";
export const _sChi = "shippingCounty";
export const _sChip = "shippingCountry";
export const _sE = "searchExpression";
export const _sEy = "systemEndpoint";
export const _sI = "sessionId";
export const _sIPC = "sensitiveInformationPolicyConfig";
export const _sK = "shortcutKey";
export const _sP = "shippingProvince";
export const _sPC = "shippingPostalCode";
export const _sS = "shippingState";
export const _sSAGAIPI = "selfServiceAnswerGenerationAIPromptId";
export const _sSAIAC = "selfServiceAIAgentConfiguration";
export const _sSAIGI = "selfServiceAIGuardrailId";
export const _sSCH = "selfServiceConversationHistory";
export const _sSEC = "serverSideEncryptionConfiguration";
export const _sSPPAIPI = "selfServicePreProcessingAIPromptId";
export const _sSe = "sessionSummaries";
export const _sU = "seedUrls";
export const _sURL = "sourceURL";
export const _sV = "stringValue";
export const _sc = "scope";
export const _se = "session";
export const _si = "single";
export const _sm = "sms";
export const _so = "source";
export const _st = "state";
export const _su = "subject";
export const _t = "type";
export const _tC = "topicsConfig";
export const _tCa = "tagCondition";
export const _tCe = "templateConfiguration";
export const _tD = "textData";
export const _tF = "tagFilter";
export const _tFAIPETC = "textFullAIPromptEditTemplateConfiguration";
export const _tI = "targetId";
export const _tIA = "topicIntegrationArn";
export const _tK = "tagKeys";
export const _tN = "turnNumber";
export const _tPC = "topicPolicyConfig";
export const _tT = "templateType";
export const _tTa = "targetType";
export const _tU = "templateUri";
export const _ta = "tags";
export const _te = "text";
export const _th = "threshold";
export const _ti = "title";
export const _tim = "timestamp";
export const _tr = "triggers";
export const _u = "url";
export const _uC = "urlConfiguration";
export const _uE = "urlExpiry";
export const _uI = "uploadId";
export const _uT = "uploadedTime";
export const _v = "value";
export const _vIC = "vectorIngestionConfiguration";
export const _vN = "versionNumber";
export const _vS = "visibilityStatus";
export const _va = "values";
export const _wC = "wordsConfig";
export const _wCC = "webCrawlerConfiguration";
export const _wPC = "wordPolicyConfig";
export const _wTS = "waitTimeSeconds";
export const n0 = "com.amazonaws.qconnect";

// smithy-typescript generated code
import { error } from "@smithy/core/schema";

import {
  AccessDeniedException as __AccessDeniedException,
  ConflictException as __ConflictException,
  ResourceNotFoundException as __ResourceNotFoundException,
  ServiceQuotaExceededException as __ServiceQuotaExceededException,
  ThrottlingException as __ThrottlingException,
  UnauthorizedException as __UnauthorizedException,
  ValidationException as __ValidationException,
} from "../models/index";
import { QConnectServiceException as __QConnectServiceException } from "../models/QConnectServiceException";

/* eslint no-var: 0 */

export var AccessDeniedException = error(
  n0,
  _ADE,
  {
    [_e]: _c,
    [_hE]: 403,
  },
  [_m],
  [0],

  __AccessDeniedException
);
export var ConflictException = error(
  n0,
  _CE,
  {
    [_e]: _c,
    [_hE]: 409,
  },
  [_m],
  [0],

  __ConflictException
);
export var ResourceNotFoundException = error(
  n0,
  _RNFE,
  {
    [_e]: _c,
    [_hE]: 404,
  },
  [_m, _rN],
  [0, 0],

  __ResourceNotFoundException
);
export var ServiceQuotaExceededException = error(
  n0,
  _SQEE,
  {
    [_e]: _c,
    [_hE]: 402,
  },
  [_m],
  [0],

  __ServiceQuotaExceededException
);
export var ThrottlingException = error(
  n0,
  _TE,
  {
    [_e]: _c,
    [_hE]: 400,
  },
  [_m],
  [0],

  __ThrottlingException
);
export var UnauthorizedException = error(
  n0,
  _UE,
  {
    [_e]: _c,
    [_hE]: 401,
  },
  [_m],
  [0],

  __UnauthorizedException
);
export var ValidationException = error(
  n0,
  _VE,
  {
    [_e]: _c,
    [_hE]: 400,
  },
  [_m],
  [0],

  __ValidationException
);
export var QConnectServiceException = error(
  "smithy.ts.sdk.synthetic.com.amazonaws.qconnect",
  "QConnectServiceException",
  0,
  [],
  [],
  __QConnectServiceException
);
export var Tags = 128 | 0;
