import { AddPermissionCommandInput, AddPermissionCommandOutput } from "../commands/AddPermissionCommand";
import { CheckIfPhoneNumberIsOptedOutCommandInput, CheckIfPhoneNumberIsOptedOutCommandOutput } from "../commands/CheckIfPhoneNumberIsOptedOutCommand";
import { ConfirmSubscriptionCommandInput, ConfirmSubscriptionCommandOutput } from "../commands/ConfirmSubscriptionCommand";
import { CreatePlatformApplicationCommandInput, CreatePlatformApplicationCommandOutput } from "../commands/CreatePlatformApplicationCommand";
import { CreatePlatformEndpointCommandInput, CreatePlatformEndpointCommandOutput } from "../commands/CreatePlatformEndpointCommand";
import { CreateTopicCommandInput, CreateTopicCommandOutput } from "../commands/CreateTopicCommand";
import { DeleteEndpointCommandInput, DeleteEndpointCommandOutput } from "../commands/DeleteEndpointCommand";
import { DeletePlatformApplicationCommandInput, DeletePlatformApplicationCommandOutput } from "../commands/DeletePlatformApplicationCommand";
import { DeleteTopicCommandInput, DeleteTopicCommandOutput } from "../commands/DeleteTopicCommand";
import { GetEndpointAttributesCommandInput, GetEndpointAttributesCommandOutput } from "../commands/GetEndpointAttributesCommand";
import { GetPlatformApplicationAttributesCommandInput, GetPlatformApplicationAttributesCommandOutput } from "../commands/GetPlatformApplicationAttributesCommand";
import { GetSMSAttributesCommandInput, GetSMSAttributesCommandOutput } from "../commands/GetSMSAttributesCommand";
import { GetSubscriptionAttributesCommandInput, GetSubscriptionAttributesCommandOutput } from "../commands/GetSubscriptionAttributesCommand";
import { GetTopicAttributesCommandInput, GetTopicAttributesCommandOutput } from "../commands/GetTopicAttributesCommand";
import { ListEndpointsByPlatformApplicationCommandInput, ListEndpointsByPlatformApplicationCommandOutput } from "../commands/ListEndpointsByPlatformApplicationCommand";
import { ListPhoneNumbersOptedOutCommandInput, ListPhoneNumbersOptedOutCommandOutput } from "../commands/ListPhoneNumbersOptedOutCommand";
import { ListPlatformApplicationsCommandInput, ListPlatformApplicationsCommandOutput } from "../commands/ListPlatformApplicationsCommand";
import { ListSubscriptionsByTopicCommandInput, ListSubscriptionsByTopicCommandOutput } from "../commands/ListSubscriptionsByTopicCommand";
import { ListSubscriptionsCommandInput, ListSubscriptionsCommandOutput } from "../commands/ListSubscriptionsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListTopicsCommandInput, ListTopicsCommandOutput } from "../commands/ListTopicsCommand";
import { OptInPhoneNumberCommandInput, OptInPhoneNumberCommandOutput } from "../commands/OptInPhoneNumberCommand";
import { PublishCommandInput, PublishCommandOutput } from "../commands/PublishCommand";
import { RemovePermissionCommandInput, RemovePermissionCommandOutput } from "../commands/RemovePermissionCommand";
import { SetEndpointAttributesCommandInput, SetEndpointAttributesCommandOutput } from "../commands/SetEndpointAttributesCommand";
import { SetPlatformApplicationAttributesCommandInput, SetPlatformApplicationAttributesCommandOutput } from "../commands/SetPlatformApplicationAttributesCommand";
import { SetSMSAttributesCommandInput, SetSMSAttributesCommandOutput } from "../commands/SetSMSAttributesCommand";
import { SetSubscriptionAttributesCommandInput, SetSubscriptionAttributesCommandOutput } from "../commands/SetSubscriptionAttributesCommand";
import { SetTopicAttributesCommandInput, SetTopicAttributesCommandOutput } from "../commands/SetTopicAttributesCommand";
import { SubscribeCommandInput, SubscribeCommandOutput } from "../commands/SubscribeCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UnsubscribeCommandInput, UnsubscribeCommandOutput } from "../commands/UnsubscribeCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryAddPermissionCommand(input: AddPermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCheckIfPhoneNumberIsOptedOutCommand(input: CheckIfPhoneNumberIsOptedOutCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryConfirmSubscriptionCommand(input: ConfirmSubscriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreatePlatformApplicationCommand(input: CreatePlatformApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreatePlatformEndpointCommand(input: CreatePlatformEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateTopicCommand(input: CreateTopicCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteEndpointCommand(input: DeleteEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeletePlatformApplicationCommand(input: DeletePlatformApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteTopicCommand(input: DeleteTopicCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetEndpointAttributesCommand(input: GetEndpointAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetPlatformApplicationAttributesCommand(input: GetPlatformApplicationAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetSMSAttributesCommand(input: GetSMSAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetSubscriptionAttributesCommand(input: GetSubscriptionAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryGetTopicAttributesCommand(input: GetTopicAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListEndpointsByPlatformApplicationCommand(input: ListEndpointsByPlatformApplicationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListPhoneNumbersOptedOutCommand(input: ListPhoneNumbersOptedOutCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListPlatformApplicationsCommand(input: ListPlatformApplicationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListSubscriptionsCommand(input: ListSubscriptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListSubscriptionsByTopicCommand(input: ListSubscriptionsByTopicCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListTopicsCommand(input: ListTopicsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryOptInPhoneNumberCommand(input: OptInPhoneNumberCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPublishCommand(input: PublishCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRemovePermissionCommand(input: RemovePermissionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetEndpointAttributesCommand(input: SetEndpointAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetPlatformApplicationAttributesCommand(input: SetPlatformApplicationAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetSMSAttributesCommand(input: SetSMSAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetSubscriptionAttributesCommand(input: SetSubscriptionAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySetTopicAttributesCommand(input: SetTopicAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_querySubscribeCommand(input: SubscribeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryTagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUnsubscribeCommand(input: UnsubscribeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryUntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryAddPermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddPermissionCommandOutput>;
export declare function deserializeAws_queryCheckIfPhoneNumberIsOptedOutCommand(output: __HttpResponse, context: __SerdeContext): Promise<CheckIfPhoneNumberIsOptedOutCommandOutput>;
export declare function deserializeAws_queryConfirmSubscriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfirmSubscriptionCommandOutput>;
export declare function deserializeAws_queryCreatePlatformApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePlatformApplicationCommandOutput>;
export declare function deserializeAws_queryCreatePlatformEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePlatformEndpointCommandOutput>;
export declare function deserializeAws_queryCreateTopicCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTopicCommandOutput>;
export declare function deserializeAws_queryDeleteEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEndpointCommandOutput>;
export declare function deserializeAws_queryDeletePlatformApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePlatformApplicationCommandOutput>;
export declare function deserializeAws_queryDeleteTopicCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTopicCommandOutput>;
export declare function deserializeAws_queryGetEndpointAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetEndpointAttributesCommandOutput>;
export declare function deserializeAws_queryGetPlatformApplicationAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPlatformApplicationAttributesCommandOutput>;
export declare function deserializeAws_queryGetSMSAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSMSAttributesCommandOutput>;
export declare function deserializeAws_queryGetSubscriptionAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSubscriptionAttributesCommandOutput>;
export declare function deserializeAws_queryGetTopicAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTopicAttributesCommandOutput>;
export declare function deserializeAws_queryListEndpointsByPlatformApplicationCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListEndpointsByPlatformApplicationCommandOutput>;
export declare function deserializeAws_queryListPhoneNumbersOptedOutCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPhoneNumbersOptedOutCommandOutput>;
export declare function deserializeAws_queryListPlatformApplicationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPlatformApplicationsCommandOutput>;
export declare function deserializeAws_queryListSubscriptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSubscriptionsCommandOutput>;
export declare function deserializeAws_queryListSubscriptionsByTopicCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSubscriptionsByTopicCommandOutput>;
export declare function deserializeAws_queryListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_queryListTopicsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTopicsCommandOutput>;
export declare function deserializeAws_queryOptInPhoneNumberCommand(output: __HttpResponse, context: __SerdeContext): Promise<OptInPhoneNumberCommandOutput>;
export declare function deserializeAws_queryPublishCommand(output: __HttpResponse, context: __SerdeContext): Promise<PublishCommandOutput>;
export declare function deserializeAws_queryRemovePermissionCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemovePermissionCommandOutput>;
export declare function deserializeAws_querySetEndpointAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetEndpointAttributesCommandOutput>;
export declare function deserializeAws_querySetPlatformApplicationAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetPlatformApplicationAttributesCommandOutput>;
export declare function deserializeAws_querySetSMSAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetSMSAttributesCommandOutput>;
export declare function deserializeAws_querySetSubscriptionAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetSubscriptionAttributesCommandOutput>;
export declare function deserializeAws_querySetTopicAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetTopicAttributesCommandOutput>;
export declare function deserializeAws_querySubscribeCommand(output: __HttpResponse, context: __SerdeContext): Promise<SubscribeCommandOutput>;
export declare function deserializeAws_queryTagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_queryUnsubscribeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UnsubscribeCommandOutput>;
export declare function deserializeAws_queryUntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
