import { CreateAcceleratorCommandInput, CreateAcceleratorCommandOutput } from "../commands/CreateAcceleratorCommand";
import { CreateEndpointGroupCommandInput, CreateEndpointGroupCommandOutput } from "../commands/CreateEndpointGroupCommand";
import { CreateListenerCommandInput, CreateListenerCommandOutput } from "../commands/CreateListenerCommand";
import { DeleteAcceleratorCommandInput, DeleteAcceleratorCommandOutput } from "../commands/DeleteAcceleratorCommand";
import { DeleteEndpointGroupCommandInput, DeleteEndpointGroupCommandOutput } from "../commands/DeleteEndpointGroupCommand";
import { DeleteListenerCommandInput, DeleteListenerCommandOutput } from "../commands/DeleteListenerCommand";
import { DescribeAcceleratorAttributesCommandInput, DescribeAcceleratorAttributesCommandOutput } from "../commands/DescribeAcceleratorAttributesCommand";
import { DescribeAcceleratorCommandInput, DescribeAcceleratorCommandOutput } from "../commands/DescribeAcceleratorCommand";
import { DescribeEndpointGroupCommandInput, DescribeEndpointGroupCommandOutput } from "../commands/DescribeEndpointGroupCommand";
import { DescribeListenerCommandInput, DescribeListenerCommandOutput } from "../commands/DescribeListenerCommand";
import { ListAcceleratorsCommandInput, ListAcceleratorsCommandOutput } from "../commands/ListAcceleratorsCommand";
import { ListEndpointGroupsCommandInput, ListEndpointGroupsCommandOutput } from "../commands/ListEndpointGroupsCommand";
import { ListListenersCommandInput, ListListenersCommandOutput } from "../commands/ListListenersCommand";
import { UpdateAcceleratorAttributesCommandInput, UpdateAcceleratorAttributesCommandOutput } from "../commands/UpdateAcceleratorAttributesCommand";
import { UpdateAcceleratorCommandInput, UpdateAcceleratorCommandOutput } from "../commands/UpdateAcceleratorCommand";
import { UpdateEndpointGroupCommandInput, UpdateEndpointGroupCommandOutput } from "../commands/UpdateEndpointGroupCommand";
import { UpdateListenerCommandInput, UpdateListenerCommandOutput } from "../commands/UpdateListenerCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateAcceleratorCommand(input: CreateAcceleratorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateEndpointGroupCommand(input: CreateEndpointGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateListenerCommand(input: CreateListenerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteAcceleratorCommand(input: DeleteAcceleratorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteEndpointGroupCommand(input: DeleteEndpointGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteListenerCommand(input: DeleteListenerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAcceleratorCommand(input: DescribeAcceleratorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAcceleratorAttributesCommand(input: DescribeAcceleratorAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEndpointGroupCommand(input: DescribeEndpointGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeListenerCommand(input: DescribeListenerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAcceleratorsCommand(input: ListAcceleratorsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListEndpointGroupsCommand(input: ListEndpointGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListListenersCommand(input: ListListenersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAcceleratorCommand(input: UpdateAcceleratorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateAcceleratorAttributesCommand(input: UpdateAcceleratorAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateEndpointGroupCommand(input: UpdateEndpointGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateListenerCommand(input: UpdateListenerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateAcceleratorCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateAcceleratorCommandOutput>;
export declare function deserializeAws_json1_1CreateEndpointGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateEndpointGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateListenerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateListenerCommandOutput>;
export declare function deserializeAws_json1_1DeleteAcceleratorCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteAcceleratorCommandOutput>;
export declare function deserializeAws_json1_1DeleteEndpointGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteEndpointGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteListenerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteListenerCommandOutput>;
export declare function deserializeAws_json1_1DescribeAcceleratorCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAcceleratorCommandOutput>;
export declare function deserializeAws_json1_1DescribeAcceleratorAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAcceleratorAttributesCommandOutput>;
export declare function deserializeAws_json1_1DescribeEndpointGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEndpointGroupCommandOutput>;
export declare function deserializeAws_json1_1DescribeListenerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeListenerCommandOutput>;
export declare function deserializeAws_json1_1ListAcceleratorsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAcceleratorsCommandOutput>;
export declare function deserializeAws_json1_1ListEndpointGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListEndpointGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListListenersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListListenersCommandOutput>;
export declare function deserializeAws_json1_1UpdateAcceleratorCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAcceleratorCommandOutput>;
export declare function deserializeAws_json1_1UpdateAcceleratorAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateAcceleratorAttributesCommandOutput>;
export declare function deserializeAws_json1_1UpdateEndpointGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateEndpointGroupCommandOutput>;
export declare function deserializeAws_json1_1UpdateListenerCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateListenerCommandOutput>;
