// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AccessDeniedException$,
  AddTagsToStream$,
  AddTagsToStreamCommand,
  CreateStream$,
  CreateStreamCommand,
  DecreaseStreamRetentionPeriod$,
  DecreaseStreamRetentionPeriodCommand,
  DeleteResourcePolicy$,
  DeleteResourcePolicyCommand,
  DeleteStream$,
  DeleteStreamCommand,
  DeregisterStreamConsumer$,
  DeregisterStreamConsumerCommand,
  DescribeAccountSettings$,
  DescribeAccountSettingsCommand,
  DescribeLimits$,
  DescribeLimitsCommand,
  DescribeStream$,
  DescribeStreamCommand,
  DescribeStreamConsumer$,
  DescribeStreamConsumerCommand,
  DescribeStreamSummary$,
  DescribeStreamSummaryCommand,
  DisableEnhancedMonitoring$,
  DisableEnhancedMonitoringCommand,
  EnableEnhancedMonitoring$,
  EnableEnhancedMonitoringCommand,
  ExpiredIteratorException$,
  ExpiredNextTokenException$,
  GetRecords$,
  GetRecordsCommand,
  GetResourcePolicy$,
  GetResourcePolicyCommand,
  GetShardIterator$,
  GetShardIteratorCommand,
  IncreaseStreamRetentionPeriod$,
  IncreaseStreamRetentionPeriodCommand,
  InternalFailureException$,
  InvalidArgumentException$,
  KinesisClient,
  KMSAccessDeniedException$,
  KMSDisabledException$,
  KMSInvalidStateException$,
  KMSNotFoundException$,
  KMSOptInRequired$,
  KMSThrottlingException$,
  LimitExceededException$,
  ListShards$,
  ListShardsCommand,
  ListStreamConsumers$,
  ListStreamConsumersCommand,
  ListStreams$,
  ListStreamsCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  ListTagsForStream$,
  ListTagsForStreamCommand,
  MergeShards$,
  MergeShardsCommand,
  ProvisionedThroughputExceededException$,
  PutRecord$,
  PutRecordCommand,
  PutRecords$,
  PutRecordsCommand,
  PutResourcePolicy$,
  PutResourcePolicyCommand,
  RegisterStreamConsumer$,
  RegisterStreamConsumerCommand,
  RemoveTagsFromStream$,
  RemoveTagsFromStreamCommand,
  ResourceInUseException$,
  ResourceNotFoundException$,
  SplitShard$,
  SplitShardCommand,
  StartStreamEncryption$,
  StartStreamEncryptionCommand,
  StopStreamEncryption$,
  StopStreamEncryptionCommand,
  SubscribeToShard$,
  SubscribeToShardCommand,
  TagResource$,
  TagResourceCommand,
  UntagResource$,
  UntagResourceCommand,
  UpdateAccountSettings$,
  UpdateAccountSettingsCommand,
  UpdateMaxRecordSize$,
  UpdateMaxRecordSizeCommand,
  UpdateShardCount$,
  UpdateShardCountCommand,
  UpdateStreamMode$,
  UpdateStreamModeCommand,
  UpdateStreamWarmThroughput$,
  UpdateStreamWarmThroughputCommand,
  ValidationException$,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = KinesisClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("KinesisClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AddTagsToStream$, AddTagsToStreamCommand],
      [CreateStream$, CreateStreamCommand],
      [DecreaseStreamRetentionPeriod$, DecreaseStreamRetentionPeriodCommand],
      [DeleteResourcePolicy$, DeleteResourcePolicyCommand],
      [DeleteStream$, DeleteStreamCommand],
      [DeregisterStreamConsumer$, DeregisterStreamConsumerCommand],
      [DescribeAccountSettings$, DescribeAccountSettingsCommand],
      [DescribeLimits$, DescribeLimitsCommand],
      [DescribeStream$, DescribeStreamCommand],
      [DescribeStreamConsumer$, DescribeStreamConsumerCommand],
      [DescribeStreamSummary$, DescribeStreamSummaryCommand],
      [DisableEnhancedMonitoring$, DisableEnhancedMonitoringCommand],
      [EnableEnhancedMonitoring$, EnableEnhancedMonitoringCommand],
      [GetRecords$, GetRecordsCommand],
      [GetResourcePolicy$, GetResourcePolicyCommand],
      [GetShardIterator$, GetShardIteratorCommand],
      [IncreaseStreamRetentionPeriod$, IncreaseStreamRetentionPeriodCommand],
      [ListShards$, ListShardsCommand],
      [ListStreamConsumers$, ListStreamConsumersCommand],
      [ListStreams$, ListStreamsCommand],
      [ListTagsForResource$, ListTagsForResourceCommand],
      [ListTagsForStream$, ListTagsForStreamCommand],
      [MergeShards$, MergeShardsCommand],
      [PutRecord$, PutRecordCommand],
      [PutRecords$, PutRecordsCommand],
      [PutResourcePolicy$, PutResourcePolicyCommand],
      [RegisterStreamConsumer$, RegisterStreamConsumerCommand],
      [RemoveTagsFromStream$, RemoveTagsFromStreamCommand],
      [SplitShard$, SplitShardCommand],
      [StartStreamEncryption$, StartStreamEncryptionCommand],
      [StopStreamEncryption$, StopStreamEncryptionCommand],
      [SubscribeToShard$, SubscribeToShardCommand],
      [TagResource$, TagResourceCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateAccountSettings$, UpdateAccountSettingsCommand],
      [UpdateMaxRecordSize$, UpdateMaxRecordSizeCommand],
      [UpdateShardCount$, UpdateShardCountCommand],
      [UpdateStreamMode$, UpdateStreamModeCommand],
      [UpdateStreamWarmThroughput$, UpdateStreamWarmThroughputCommand],
    ]),
    errors: [
      AccessDeniedException$,
      ExpiredIteratorException$,
      ExpiredNextTokenException$,
      InternalFailureException$,
      InvalidArgumentException$,
      KMSAccessDeniedException$,
      KMSDisabledException$,
      KMSInvalidStateException$,
      KMSNotFoundException$,
      KMSOptInRequired$,
      KMSThrottlingException$,
      LimitExceededException$,
      ProvisionedThroughputExceededException$,
      ResourceInUseException$,
      ResourceNotFoundException$,
      ValidationException$,
    ],
  });
  runner.run();
}, 30_000);
