// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AssociateAccessGrantsIdentityCenter$,
  AssociateAccessGrantsIdentityCenterCommand,
  CreateAccessGrant$,
  CreateAccessGrantCommand,
  CreateAccessGrantsInstance$,
  CreateAccessGrantsInstanceCommand,
  CreateAccessGrantsLocation$,
  CreateAccessGrantsLocationCommand,
  CreateAccessPoint$,
  CreateAccessPointCommand,
  CreateAccessPointForObjectLambda$,
  CreateAccessPointForObjectLambdaCommand,
  CreateBucket$,
  CreateBucketCommand,
  CreateJob$,
  CreateJobCommand,
  CreateMultiRegionAccessPoint$,
  CreateMultiRegionAccessPointCommand,
  CreateStorageLensGroup$,
  CreateStorageLensGroupCommand,
  DeleteAccessGrant$,
  DeleteAccessGrantCommand,
  DeleteAccessGrantsInstance$,
  DeleteAccessGrantsInstanceCommand,
  DeleteAccessGrantsInstanceResourcePolicy$,
  DeleteAccessGrantsInstanceResourcePolicyCommand,
  DeleteAccessGrantsLocation$,
  DeleteAccessGrantsLocationCommand,
  DeleteAccessPoint$,
  DeleteAccessPointCommand,
  DeleteAccessPointForObjectLambda$,
  DeleteAccessPointForObjectLambdaCommand,
  DeleteAccessPointPolicy$,
  DeleteAccessPointPolicyCommand,
  DeleteAccessPointPolicyForObjectLambda$,
  DeleteAccessPointPolicyForObjectLambdaCommand,
  DeleteAccessPointScope$,
  DeleteAccessPointScopeCommand,
  DeleteBucket$,
  DeleteBucketCommand,
  DeleteBucketLifecycleConfiguration$,
  DeleteBucketLifecycleConfigurationCommand,
  DeleteBucketPolicy$,
  DeleteBucketPolicyCommand,
  DeleteBucketReplication$,
  DeleteBucketReplicationCommand,
  DeleteBucketTagging$,
  DeleteBucketTaggingCommand,
  DeleteJobTagging$,
  DeleteJobTaggingCommand,
  DeleteMultiRegionAccessPoint$,
  DeleteMultiRegionAccessPointCommand,
  DeletePublicAccessBlock$,
  DeletePublicAccessBlockCommand,
  DeleteStorageLensConfiguration$,
  DeleteStorageLensConfigurationCommand,
  DeleteStorageLensConfigurationTagging$,
  DeleteStorageLensConfigurationTaggingCommand,
  DeleteStorageLensGroup$,
  DeleteStorageLensGroupCommand,
  DescribeJob$,
  DescribeJobCommand,
  DescribeMultiRegionAccessPointOperation$,
  DescribeMultiRegionAccessPointOperationCommand,
  DissociateAccessGrantsIdentityCenter$,
  DissociateAccessGrantsIdentityCenterCommand,
  GetAccessGrant$,
  GetAccessGrantCommand,
  GetAccessGrantsInstance$,
  GetAccessGrantsInstanceCommand,
  GetAccessGrantsInstanceForPrefix$,
  GetAccessGrantsInstanceForPrefixCommand,
  GetAccessGrantsInstanceResourcePolicy$,
  GetAccessGrantsInstanceResourcePolicyCommand,
  GetAccessGrantsLocation$,
  GetAccessGrantsLocationCommand,
  GetAccessPoint$,
  GetAccessPointCommand,
  GetAccessPointConfigurationForObjectLambda$,
  GetAccessPointConfigurationForObjectLambdaCommand,
  GetAccessPointForObjectLambda$,
  GetAccessPointForObjectLambdaCommand,
  GetAccessPointPolicy$,
  GetAccessPointPolicyCommand,
  GetAccessPointPolicyForObjectLambda$,
  GetAccessPointPolicyForObjectLambdaCommand,
  GetAccessPointPolicyStatus$,
  GetAccessPointPolicyStatusCommand,
  GetAccessPointPolicyStatusForObjectLambda$,
  GetAccessPointPolicyStatusForObjectLambdaCommand,
  GetAccessPointScope$,
  GetAccessPointScopeCommand,
  GetBucket$,
  GetBucketCommand,
  GetBucketLifecycleConfiguration$,
  GetBucketLifecycleConfigurationCommand,
  GetBucketPolicy$,
  GetBucketPolicyCommand,
  GetBucketReplication$,
  GetBucketReplicationCommand,
  GetBucketTagging$,
  GetBucketTaggingCommand,
  GetBucketVersioning$,
  GetBucketVersioningCommand,
  GetDataAccess$,
  GetDataAccessCommand,
  GetJobTagging$,
  GetJobTaggingCommand,
  GetMultiRegionAccessPoint$,
  GetMultiRegionAccessPointCommand,
  GetMultiRegionAccessPointPolicy$,
  GetMultiRegionAccessPointPolicyCommand,
  GetMultiRegionAccessPointPolicyStatus$,
  GetMultiRegionAccessPointPolicyStatusCommand,
  GetMultiRegionAccessPointRoutes$,
  GetMultiRegionAccessPointRoutesCommand,
  GetPublicAccessBlock$,
  GetPublicAccessBlockCommand,
  GetStorageLensConfiguration$,
  GetStorageLensConfigurationCommand,
  GetStorageLensConfigurationTagging$,
  GetStorageLensConfigurationTaggingCommand,
  GetStorageLensGroup$,
  GetStorageLensGroupCommand,
  ListAccessGrants$,
  ListAccessGrantsCommand,
  ListAccessGrantsInstances$,
  ListAccessGrantsInstancesCommand,
  ListAccessGrantsLocations$,
  ListAccessGrantsLocationsCommand,
  ListAccessPoints$,
  ListAccessPointsCommand,
  ListAccessPointsForDirectoryBuckets$,
  ListAccessPointsForDirectoryBucketsCommand,
  ListAccessPointsForObjectLambda$,
  ListAccessPointsForObjectLambdaCommand,
  ListCallerAccessGrants$,
  ListCallerAccessGrantsCommand,
  ListJobs$,
  ListJobsCommand,
  ListMultiRegionAccessPoints$,
  ListMultiRegionAccessPointsCommand,
  ListRegionalBuckets$,
  ListRegionalBucketsCommand,
  ListStorageLensConfigurations$,
  ListStorageLensConfigurationsCommand,
  ListStorageLensGroups$,
  ListStorageLensGroupsCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  PutAccessGrantsInstanceResourcePolicy$,
  PutAccessGrantsInstanceResourcePolicyCommand,
  PutAccessPointConfigurationForObjectLambda$,
  PutAccessPointConfigurationForObjectLambdaCommand,
  PutAccessPointPolicy$,
  PutAccessPointPolicyCommand,
  PutAccessPointPolicyForObjectLambda$,
  PutAccessPointPolicyForObjectLambdaCommand,
  PutAccessPointScope$,
  PutAccessPointScopeCommand,
  PutBucketLifecycleConfiguration$,
  PutBucketLifecycleConfigurationCommand,
  PutBucketPolicy$,
  PutBucketPolicyCommand,
  PutBucketReplication$,
  PutBucketReplicationCommand,
  PutBucketTagging$,
  PutBucketTaggingCommand,
  PutBucketVersioning$,
  PutBucketVersioningCommand,
  PutJobTagging$,
  PutJobTaggingCommand,
  PutMultiRegionAccessPointPolicy$,
  PutMultiRegionAccessPointPolicyCommand,
  PutPublicAccessBlock$,
  PutPublicAccessBlockCommand,
  PutStorageLensConfiguration$,
  PutStorageLensConfigurationCommand,
  PutStorageLensConfigurationTagging$,
  PutStorageLensConfigurationTaggingCommand,
  S3ControlClient,
  SubmitMultiRegionAccessPointRoutes$,
  SubmitMultiRegionAccessPointRoutesCommand,
  TagResource$,
  TagResourceCommand,
  UntagResource$,
  UntagResourceCommand,
  UpdateAccessGrantsLocation$,
  UpdateAccessGrantsLocationCommand,
  UpdateJobPriority$,
  UpdateJobPriorityCommand,
  UpdateJobStatus$,
  UpdateJobStatusCommand,
  UpdateStorageLensGroup$,
  UpdateStorageLensGroupCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = S3ControlClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe(
  "S3ControlClient" + ` (${mode})`,
  () => {
    const runner = new SnapshotRunner({
      snapshotDirPath: join(__dirname, "snapshots"),
      Client,
      mode,
      testCase(caseName: string, run: () => Promise<void>) {
        it(caseName, run);
      },
      assertions(caseName: string, expected: string, actual: string): Promise<void> {
        expect(actual).toEqual(expected);
        return Promise.resolve();
      },
      schemas: new Map<any, any>([
        [AssociateAccessGrantsIdentityCenter$, AssociateAccessGrantsIdentityCenterCommand],
        [CreateAccessGrant$, CreateAccessGrantCommand],
        [CreateAccessGrantsInstance$, CreateAccessGrantsInstanceCommand],
        [CreateAccessGrantsLocation$, CreateAccessGrantsLocationCommand],
        [CreateAccessPoint$, CreateAccessPointCommand],
        [CreateAccessPointForObjectLambda$, CreateAccessPointForObjectLambdaCommand],
        [CreateBucket$, CreateBucketCommand],
        [CreateJob$, CreateJobCommand],
        [CreateMultiRegionAccessPoint$, CreateMultiRegionAccessPointCommand],
        [CreateStorageLensGroup$, CreateStorageLensGroupCommand],
        [DeleteAccessGrant$, DeleteAccessGrantCommand],
        [DeleteAccessGrantsInstance$, DeleteAccessGrantsInstanceCommand],
        [DeleteAccessGrantsInstanceResourcePolicy$, DeleteAccessGrantsInstanceResourcePolicyCommand],
        [DeleteAccessGrantsLocation$, DeleteAccessGrantsLocationCommand],
        [DeleteAccessPoint$, DeleteAccessPointCommand],
        [DeleteAccessPointForObjectLambda$, DeleteAccessPointForObjectLambdaCommand],
        [DeleteAccessPointPolicy$, DeleteAccessPointPolicyCommand],
        [DeleteAccessPointPolicyForObjectLambda$, DeleteAccessPointPolicyForObjectLambdaCommand],
        [DeleteAccessPointScope$, DeleteAccessPointScopeCommand],
        [DeleteBucket$, DeleteBucketCommand],
        [DeleteBucketLifecycleConfiguration$, DeleteBucketLifecycleConfigurationCommand],
        [DeleteBucketPolicy$, DeleteBucketPolicyCommand],
        [DeleteBucketReplication$, DeleteBucketReplicationCommand],
        [DeleteBucketTagging$, DeleteBucketTaggingCommand],
        [DeleteJobTagging$, DeleteJobTaggingCommand],
        [DeleteMultiRegionAccessPoint$, DeleteMultiRegionAccessPointCommand],
        [DeletePublicAccessBlock$, DeletePublicAccessBlockCommand],
        [DeleteStorageLensConfiguration$, DeleteStorageLensConfigurationCommand],
        [DeleteStorageLensConfigurationTagging$, DeleteStorageLensConfigurationTaggingCommand],
        [DeleteStorageLensGroup$, DeleteStorageLensGroupCommand],
        [DescribeJob$, DescribeJobCommand],
        [DescribeMultiRegionAccessPointOperation$, DescribeMultiRegionAccessPointOperationCommand],
        [DissociateAccessGrantsIdentityCenter$, DissociateAccessGrantsIdentityCenterCommand],
        [GetAccessGrant$, GetAccessGrantCommand],
        [GetAccessGrantsInstance$, GetAccessGrantsInstanceCommand],
        [GetAccessGrantsInstanceForPrefix$, GetAccessGrantsInstanceForPrefixCommand],
        [GetAccessGrantsInstanceResourcePolicy$, GetAccessGrantsInstanceResourcePolicyCommand],
        [GetAccessGrantsLocation$, GetAccessGrantsLocationCommand],
        [GetAccessPoint$, GetAccessPointCommand],
        [GetAccessPointConfigurationForObjectLambda$, GetAccessPointConfigurationForObjectLambdaCommand],
        [GetAccessPointForObjectLambda$, GetAccessPointForObjectLambdaCommand],
        [GetAccessPointPolicy$, GetAccessPointPolicyCommand],
        [GetAccessPointPolicyForObjectLambda$, GetAccessPointPolicyForObjectLambdaCommand],
        [GetAccessPointPolicyStatus$, GetAccessPointPolicyStatusCommand],
        [GetAccessPointPolicyStatusForObjectLambda$, GetAccessPointPolicyStatusForObjectLambdaCommand],
        [GetAccessPointScope$, GetAccessPointScopeCommand],
        [GetBucket$, GetBucketCommand],
        [GetBucketLifecycleConfiguration$, GetBucketLifecycleConfigurationCommand],
        [GetBucketPolicy$, GetBucketPolicyCommand],
        [GetBucketReplication$, GetBucketReplicationCommand],
        [GetBucketTagging$, GetBucketTaggingCommand],
        [GetBucketVersioning$, GetBucketVersioningCommand],
        [GetDataAccess$, GetDataAccessCommand],
        [GetJobTagging$, GetJobTaggingCommand],
        [GetMultiRegionAccessPoint$, GetMultiRegionAccessPointCommand],
        [GetMultiRegionAccessPointPolicy$, GetMultiRegionAccessPointPolicyCommand],
        [GetMultiRegionAccessPointPolicyStatus$, GetMultiRegionAccessPointPolicyStatusCommand],
        [GetMultiRegionAccessPointRoutes$, GetMultiRegionAccessPointRoutesCommand],
        [GetPublicAccessBlock$, GetPublicAccessBlockCommand],
        [GetStorageLensConfiguration$, GetStorageLensConfigurationCommand],
        [GetStorageLensConfigurationTagging$, GetStorageLensConfigurationTaggingCommand],
        [GetStorageLensGroup$, GetStorageLensGroupCommand],
        [ListAccessGrants$, ListAccessGrantsCommand],
        [ListAccessGrantsInstances$, ListAccessGrantsInstancesCommand],
        [ListAccessGrantsLocations$, ListAccessGrantsLocationsCommand],
        [ListAccessPoints$, ListAccessPointsCommand],
        [ListAccessPointsForDirectoryBuckets$, ListAccessPointsForDirectoryBucketsCommand],
        [ListAccessPointsForObjectLambda$, ListAccessPointsForObjectLambdaCommand],
        [ListCallerAccessGrants$, ListCallerAccessGrantsCommand],
        [ListJobs$, ListJobsCommand],
        [ListMultiRegionAccessPoints$, ListMultiRegionAccessPointsCommand],
        [ListRegionalBuckets$, ListRegionalBucketsCommand],
        [ListStorageLensConfigurations$, ListStorageLensConfigurationsCommand],
        [ListStorageLensGroups$, ListStorageLensGroupsCommand],
        [ListTagsForResource$, ListTagsForResourceCommand],
        [PutAccessGrantsInstanceResourcePolicy$, PutAccessGrantsInstanceResourcePolicyCommand],
        [PutAccessPointConfigurationForObjectLambda$, PutAccessPointConfigurationForObjectLambdaCommand],
        [PutAccessPointPolicy$, PutAccessPointPolicyCommand],
        [PutAccessPointPolicyForObjectLambda$, PutAccessPointPolicyForObjectLambdaCommand],
        [PutAccessPointScope$, PutAccessPointScopeCommand],
        [PutBucketLifecycleConfiguration$, PutBucketLifecycleConfigurationCommand],
        [PutBucketPolicy$, PutBucketPolicyCommand],
        [PutBucketReplication$, PutBucketReplicationCommand],
        [PutBucketTagging$, PutBucketTaggingCommand],
        [PutBucketVersioning$, PutBucketVersioningCommand],
        [PutJobTagging$, PutJobTaggingCommand],
        [PutMultiRegionAccessPointPolicy$, PutMultiRegionAccessPointPolicyCommand],
        [PutPublicAccessBlock$, PutPublicAccessBlockCommand],
        [PutStorageLensConfiguration$, PutStorageLensConfigurationCommand],
        [PutStorageLensConfigurationTagging$, PutStorageLensConfigurationTaggingCommand],
        [SubmitMultiRegionAccessPointRoutes$, SubmitMultiRegionAccessPointRoutesCommand],
        [TagResource$, TagResourceCommand],
        [UntagResource$, UntagResourceCommand],
        [UpdateAccessGrantsLocation$, UpdateAccessGrantsLocationCommand],
        [UpdateJobPriority$, UpdateJobPriorityCommand],
        [UpdateJobStatus$, UpdateJobStatusCommand],
        [UpdateStorageLensGroup$, UpdateStorageLensGroupCommand],
      ]),
    });

    runner.run();
  },
  30_000
);
