// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AccessDeniedException$,
  AssociateKmsKey$,
  AssociateKmsKeyCommand,
  AssociateSourceToS3TableIntegration$,
  AssociateSourceToS3TableIntegrationCommand,
  CancelExportTask$,
  CancelExportTaskCommand,
  CancelImportTask$,
  CancelImportTaskCommand,
  CloudWatchLogsClient,
  ConflictException$,
  CreateDelivery$,
  CreateDeliveryCommand,
  CreateExportTask$,
  CreateExportTaskCommand,
  CreateImportTask$,
  CreateImportTaskCommand,
  CreateLogAnomalyDetector$,
  CreateLogAnomalyDetectorCommand,
  CreateLogGroup$,
  CreateLogGroupCommand,
  CreateLogStream$,
  CreateLogStreamCommand,
  CreateScheduledQuery$,
  CreateScheduledQueryCommand,
  DataAlreadyAcceptedException$,
  DeleteAccountPolicy$,
  DeleteAccountPolicyCommand,
  DeleteDataProtectionPolicy$,
  DeleteDataProtectionPolicyCommand,
  DeleteDelivery$,
  DeleteDeliveryCommand,
  DeleteDeliveryDestination$,
  DeleteDeliveryDestinationCommand,
  DeleteDeliveryDestinationPolicy$,
  DeleteDeliveryDestinationPolicyCommand,
  DeleteDeliverySource$,
  DeleteDeliverySourceCommand,
  DeleteDestination$,
  DeleteDestinationCommand,
  DeleteIndexPolicy$,
  DeleteIndexPolicyCommand,
  DeleteIntegration$,
  DeleteIntegrationCommand,
  DeleteLogAnomalyDetector$,
  DeleteLogAnomalyDetectorCommand,
  DeleteLogGroup$,
  DeleteLogGroupCommand,
  DeleteLogStream$,
  DeleteLogStreamCommand,
  DeleteMetricFilter$,
  DeleteMetricFilterCommand,
  DeleteQueryDefinition$,
  DeleteQueryDefinitionCommand,
  DeleteResourcePolicy$,
  DeleteResourcePolicyCommand,
  DeleteRetentionPolicy$,
  DeleteRetentionPolicyCommand,
  DeleteScheduledQuery$,
  DeleteScheduledQueryCommand,
  DeleteSubscriptionFilter$,
  DeleteSubscriptionFilterCommand,
  DeleteTransformer$,
  DeleteTransformerCommand,
  DescribeAccountPolicies$,
  DescribeAccountPoliciesCommand,
  DescribeConfigurationTemplates$,
  DescribeConfigurationTemplatesCommand,
  DescribeDeliveries$,
  DescribeDeliveriesCommand,
  DescribeDeliveryDestinations$,
  DescribeDeliveryDestinationsCommand,
  DescribeDeliverySources$,
  DescribeDeliverySourcesCommand,
  DescribeDestinations$,
  DescribeDestinationsCommand,
  DescribeExportTasks$,
  DescribeExportTasksCommand,
  DescribeFieldIndexes$,
  DescribeFieldIndexesCommand,
  DescribeImportTaskBatches$,
  DescribeImportTaskBatchesCommand,
  DescribeImportTasks$,
  DescribeImportTasksCommand,
  DescribeIndexPolicies$,
  DescribeIndexPoliciesCommand,
  DescribeLogGroups$,
  DescribeLogGroupsCommand,
  DescribeLogStreams$,
  DescribeLogStreamsCommand,
  DescribeMetricFilters$,
  DescribeMetricFiltersCommand,
  DescribeQueries$,
  DescribeQueriesCommand,
  DescribeQueryDefinitions$,
  DescribeQueryDefinitionsCommand,
  DescribeResourcePolicies$,
  DescribeResourcePoliciesCommand,
  DescribeSubscriptionFilters$,
  DescribeSubscriptionFiltersCommand,
  DisassociateKmsKey$,
  DisassociateKmsKeyCommand,
  DisassociateSourceFromS3TableIntegration$,
  DisassociateSourceFromS3TableIntegrationCommand,
  FilterLogEvents$,
  FilterLogEventsCommand,
  GetDataProtectionPolicy$,
  GetDataProtectionPolicyCommand,
  GetDelivery$,
  GetDeliveryCommand,
  GetDeliveryDestination$,
  GetDeliveryDestinationCommand,
  GetDeliveryDestinationPolicy$,
  GetDeliveryDestinationPolicyCommand,
  GetDeliverySource$,
  GetDeliverySourceCommand,
  GetIntegration$,
  GetIntegrationCommand,
  GetLogAnomalyDetector$,
  GetLogAnomalyDetectorCommand,
  GetLogEvents$,
  GetLogEventsCommand,
  GetLogFields$,
  GetLogFieldsCommand,
  GetLogGroupFields$,
  GetLogGroupFieldsCommand,
  GetLogObject$,
  GetLogObjectCommand,
  GetLogRecord$,
  GetLogRecordCommand,
  GetQueryResults$,
  GetQueryResultsCommand,
  GetScheduledQuery$,
  GetScheduledQueryCommand,
  GetScheduledQueryHistory$,
  GetScheduledQueryHistoryCommand,
  GetTransformer$,
  GetTransformerCommand,
  InternalServerException$,
  InternalStreamingException$,
  InvalidOperationException$,
  InvalidParameterException$,
  InvalidSequenceTokenException$,
  LimitExceededException$,
  ListAggregateLogGroupSummaries$,
  ListAggregateLogGroupSummariesCommand,
  ListAnomalies$,
  ListAnomaliesCommand,
  ListIntegrations$,
  ListIntegrationsCommand,
  ListLogAnomalyDetectors$,
  ListLogAnomalyDetectorsCommand,
  ListLogGroups$,
  ListLogGroupsCommand,
  ListLogGroupsForQuery$,
  ListLogGroupsForQueryCommand,
  ListScheduledQueries$,
  ListScheduledQueriesCommand,
  ListSourcesForS3TableIntegration$,
  ListSourcesForS3TableIntegrationCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  ListTagsLogGroup$,
  ListTagsLogGroupCommand,
  MalformedQueryException$,
  OperationAbortedException$,
  PutAccountPolicy$,
  PutAccountPolicyCommand,
  PutBearerTokenAuthentication$,
  PutBearerTokenAuthenticationCommand,
  PutDataProtectionPolicy$,
  PutDataProtectionPolicyCommand,
  PutDeliveryDestination$,
  PutDeliveryDestinationCommand,
  PutDeliveryDestinationPolicy$,
  PutDeliveryDestinationPolicyCommand,
  PutDeliverySource$,
  PutDeliverySourceCommand,
  PutDestination$,
  PutDestinationCommand,
  PutDestinationPolicy$,
  PutDestinationPolicyCommand,
  PutIndexPolicy$,
  PutIndexPolicyCommand,
  PutIntegration$,
  PutIntegrationCommand,
  PutLogEvents$,
  PutLogEventsCommand,
  PutLogGroupDeletionProtection$,
  PutLogGroupDeletionProtectionCommand,
  PutMetricFilter$,
  PutMetricFilterCommand,
  PutQueryDefinition$,
  PutQueryDefinitionCommand,
  PutResourcePolicy$,
  PutResourcePolicyCommand,
  PutRetentionPolicy$,
  PutRetentionPolicyCommand,
  PutSubscriptionFilter$,
  PutSubscriptionFilterCommand,
  PutTransformer$,
  PutTransformerCommand,
  ResourceAlreadyExistsException$,
  ResourceNotFoundException$,
  ServiceQuotaExceededException$,
  ServiceUnavailableException$,
  SessionStreamingException$,
  SessionTimeoutException$,
  StartLiveTail$,
  StartLiveTailCommand,
  StartQuery$,
  StartQueryCommand,
  StopQuery$,
  StopQueryCommand,
  TagLogGroup$,
  TagLogGroupCommand,
  TagResource$,
  TagResourceCommand,
  TestMetricFilter$,
  TestMetricFilterCommand,
  TestTransformer$,
  TestTransformerCommand,
  ThrottlingException$,
  TooManyTagsException$,
  UnrecognizedClientException$,
  UntagLogGroup$,
  UntagLogGroupCommand,
  UntagResource$,
  UntagResourceCommand,
  UpdateAnomaly$,
  UpdateAnomalyCommand,
  UpdateDeliveryConfiguration$,
  UpdateDeliveryConfigurationCommand,
  UpdateLogAnomalyDetector$,
  UpdateLogAnomalyDetectorCommand,
  UpdateScheduledQuery$,
  UpdateScheduledQueryCommand,
  ValidationException$,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = CloudWatchLogsClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("CloudWatchLogsClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AssociateKmsKey$, AssociateKmsKeyCommand],
      [AssociateSourceToS3TableIntegration$, AssociateSourceToS3TableIntegrationCommand],
      [CancelExportTask$, CancelExportTaskCommand],
      [CancelImportTask$, CancelImportTaskCommand],
      [CreateDelivery$, CreateDeliveryCommand],
      [CreateExportTask$, CreateExportTaskCommand],
      [CreateImportTask$, CreateImportTaskCommand],
      [CreateLogAnomalyDetector$, CreateLogAnomalyDetectorCommand],
      [CreateLogGroup$, CreateLogGroupCommand],
      [CreateLogStream$, CreateLogStreamCommand],
      [CreateScheduledQuery$, CreateScheduledQueryCommand],
      [DeleteAccountPolicy$, DeleteAccountPolicyCommand],
      [DeleteDataProtectionPolicy$, DeleteDataProtectionPolicyCommand],
      [DeleteDelivery$, DeleteDeliveryCommand],
      [DeleteDeliveryDestination$, DeleteDeliveryDestinationCommand],
      [DeleteDeliveryDestinationPolicy$, DeleteDeliveryDestinationPolicyCommand],
      [DeleteDeliverySource$, DeleteDeliverySourceCommand],
      [DeleteDestination$, DeleteDestinationCommand],
      [DeleteIndexPolicy$, DeleteIndexPolicyCommand],
      [DeleteIntegration$, DeleteIntegrationCommand],
      [DeleteLogAnomalyDetector$, DeleteLogAnomalyDetectorCommand],
      [DeleteLogGroup$, DeleteLogGroupCommand],
      [DeleteLogStream$, DeleteLogStreamCommand],
      [DeleteMetricFilter$, DeleteMetricFilterCommand],
      [DeleteQueryDefinition$, DeleteQueryDefinitionCommand],
      [DeleteResourcePolicy$, DeleteResourcePolicyCommand],
      [DeleteRetentionPolicy$, DeleteRetentionPolicyCommand],
      [DeleteScheduledQuery$, DeleteScheduledQueryCommand],
      [DeleteSubscriptionFilter$, DeleteSubscriptionFilterCommand],
      [DeleteTransformer$, DeleteTransformerCommand],
      [DescribeAccountPolicies$, DescribeAccountPoliciesCommand],
      [DescribeConfigurationTemplates$, DescribeConfigurationTemplatesCommand],
      [DescribeDeliveries$, DescribeDeliveriesCommand],
      [DescribeDeliveryDestinations$, DescribeDeliveryDestinationsCommand],
      [DescribeDeliverySources$, DescribeDeliverySourcesCommand],
      [DescribeDestinations$, DescribeDestinationsCommand],
      [DescribeExportTasks$, DescribeExportTasksCommand],
      [DescribeFieldIndexes$, DescribeFieldIndexesCommand],
      [DescribeImportTaskBatches$, DescribeImportTaskBatchesCommand],
      [DescribeImportTasks$, DescribeImportTasksCommand],
      [DescribeIndexPolicies$, DescribeIndexPoliciesCommand],
      [DescribeLogGroups$, DescribeLogGroupsCommand],
      [DescribeLogStreams$, DescribeLogStreamsCommand],
      [DescribeMetricFilters$, DescribeMetricFiltersCommand],
      [DescribeQueries$, DescribeQueriesCommand],
      [DescribeQueryDefinitions$, DescribeQueryDefinitionsCommand],
      [DescribeResourcePolicies$, DescribeResourcePoliciesCommand],
      [DescribeSubscriptionFilters$, DescribeSubscriptionFiltersCommand],
      [DisassociateKmsKey$, DisassociateKmsKeyCommand],
      [DisassociateSourceFromS3TableIntegration$, DisassociateSourceFromS3TableIntegrationCommand],
      [FilterLogEvents$, FilterLogEventsCommand],
      [GetDataProtectionPolicy$, GetDataProtectionPolicyCommand],
      [GetDelivery$, GetDeliveryCommand],
      [GetDeliveryDestination$, GetDeliveryDestinationCommand],
      [GetDeliveryDestinationPolicy$, GetDeliveryDestinationPolicyCommand],
      [GetDeliverySource$, GetDeliverySourceCommand],
      [GetIntegration$, GetIntegrationCommand],
      [GetLogAnomalyDetector$, GetLogAnomalyDetectorCommand],
      [GetLogEvents$, GetLogEventsCommand],
      [GetLogFields$, GetLogFieldsCommand],
      [GetLogGroupFields$, GetLogGroupFieldsCommand],
      [GetLogObject$, GetLogObjectCommand],
      [GetLogRecord$, GetLogRecordCommand],
      [GetQueryResults$, GetQueryResultsCommand],
      [GetScheduledQuery$, GetScheduledQueryCommand],
      [GetScheduledQueryHistory$, GetScheduledQueryHistoryCommand],
      [GetTransformer$, GetTransformerCommand],
      [ListAggregateLogGroupSummaries$, ListAggregateLogGroupSummariesCommand],
      [ListAnomalies$, ListAnomaliesCommand],
      [ListIntegrations$, ListIntegrationsCommand],
      [ListLogAnomalyDetectors$, ListLogAnomalyDetectorsCommand],
      [ListLogGroups$, ListLogGroupsCommand],
      [ListLogGroupsForQuery$, ListLogGroupsForQueryCommand],
      [ListScheduledQueries$, ListScheduledQueriesCommand],
      [ListSourcesForS3TableIntegration$, ListSourcesForS3TableIntegrationCommand],
      [ListTagsForResource$, ListTagsForResourceCommand],
      [ListTagsLogGroup$, ListTagsLogGroupCommand],
      [PutAccountPolicy$, PutAccountPolicyCommand],
      [PutBearerTokenAuthentication$, PutBearerTokenAuthenticationCommand],
      [PutDataProtectionPolicy$, PutDataProtectionPolicyCommand],
      [PutDeliveryDestination$, PutDeliveryDestinationCommand],
      [PutDeliveryDestinationPolicy$, PutDeliveryDestinationPolicyCommand],
      [PutDeliverySource$, PutDeliverySourceCommand],
      [PutDestination$, PutDestinationCommand],
      [PutDestinationPolicy$, PutDestinationPolicyCommand],
      [PutIndexPolicy$, PutIndexPolicyCommand],
      [PutIntegration$, PutIntegrationCommand],
      [PutLogEvents$, PutLogEventsCommand],
      [PutLogGroupDeletionProtection$, PutLogGroupDeletionProtectionCommand],
      [PutMetricFilter$, PutMetricFilterCommand],
      [PutQueryDefinition$, PutQueryDefinitionCommand],
      [PutResourcePolicy$, PutResourcePolicyCommand],
      [PutRetentionPolicy$, PutRetentionPolicyCommand],
      [PutSubscriptionFilter$, PutSubscriptionFilterCommand],
      [PutTransformer$, PutTransformerCommand],
      [StartLiveTail$, StartLiveTailCommand],
      [StartQuery$, StartQueryCommand],
      [StopQuery$, StopQueryCommand],
      [TagLogGroup$, TagLogGroupCommand],
      [TagResource$, TagResourceCommand],
      [TestMetricFilter$, TestMetricFilterCommand],
      [TestTransformer$, TestTransformerCommand],
      [UntagLogGroup$, UntagLogGroupCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateAnomaly$, UpdateAnomalyCommand],
      [UpdateDeliveryConfiguration$, UpdateDeliveryConfigurationCommand],
      [UpdateLogAnomalyDetector$, UpdateLogAnomalyDetectorCommand],
      [UpdateScheduledQuery$, UpdateScheduledQueryCommand],
    ]),
    errors: [
      AccessDeniedException$,
      ConflictException$,
      DataAlreadyAcceptedException$,
      InternalServerException$,
      InternalStreamingException$,
      InvalidOperationException$,
      InvalidParameterException$,
      InvalidSequenceTokenException$,
      LimitExceededException$,
      MalformedQueryException$,
      OperationAbortedException$,
      ResourceAlreadyExistsException$,
      ResourceNotFoundException$,
      ServiceQuotaExceededException$,
      ServiceUnavailableException$,
      SessionStreamingException$,
      SessionTimeoutException$,
      ThrottlingException$,
      TooManyTagsException$,
      UnrecognizedClientException$,
      ValidationException$,
    ],
  });
  runner.run();
}, 30_000);
