// smithy-typescript generated code
/**
 * @public
 * @enum
 */
export const AdMarkerDash = {
  BINARY: "BINARY",
  XML: "XML",
} as const;
/**
 * @public
 */
export type AdMarkerDash = (typeof AdMarkerDash)[keyof typeof AdMarkerDash];

/**
 * @public
 * @enum
 */
export const AdMarkerHls = {
  DATERANGE: "DATERANGE",
  SCTE35_ENHANCED: "SCTE35_ENHANCED",
} as const;
/**
 * @public
 */
export type AdMarkerHls = (typeof AdMarkerHls)[keyof typeof AdMarkerHls];

/**
 * @public
 * @enum
 */
export const ConflictExceptionType = {
  CONFLICTING_OPERATION: "CONFLICTING_OPERATION",
  IDEMPOTENT_PARAMETER_MISMATCH: "IDEMPOTENT_PARAMETER_MISMATCH",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_IN_USE: "RESOURCE_IN_USE",
} as const;
/**
 * @public
 */
export type ConflictExceptionType = (typeof ConflictExceptionType)[keyof typeof ConflictExceptionType];

/**
 * @public
 * @enum
 */
export const ResourceTypeNotFound = {
  CHANNEL: "CHANNEL",
  CHANNEL_GROUP: "CHANNEL_GROUP",
  HARVEST_JOB: "HARVEST_JOB",
  ORIGIN_ENDPOINT: "ORIGIN_ENDPOINT",
} as const;
/**
 * @public
 */
export type ResourceTypeNotFound = (typeof ResourceTypeNotFound)[keyof typeof ResourceTypeNotFound];

/**
 * @public
 * @enum
 */
export const ValidationExceptionType = {
  BATCH_GET_SECRET_VALUE_DENIED: "BATCH_GET_SECRET_VALUE_DENIED",
  CENC_IV_INCOMPATIBLE: "CENC_IV_INCOMPATIBLE",
  CLIP_START_TIME_WITH_START_OR_END: "CLIP_START_TIME_WITH_START_OR_END",
  CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST: "CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST",
  CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE:
    "CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE",
  CONTAINER_TYPE_IMMUTABLE: "CONTAINER_TYPE_IMMUTABLE",
  DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE: "DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE",
  DECRYPT_SECRET_FAILED: "DECRYPT_SECRET_FAILED",
  DESCRIBE_SECRET_DENIED: "DESCRIBE_SECRET_DENIED",
  DIRECT_MODE_WITH_TIMING_SOURCE: "DIRECT_MODE_WITH_TIMING_SOURCE",
  DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS: "DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS",
  DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE: "DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE",
  DUPLICATED_SECRET: "DUPLICATED_SECRET",
  ENCRYPTION_CONTRACT_SHARED: "ENCRYPTION_CONTRACT_SHARED",
  ENCRYPTION_CONTRACT_UNENCRYPTED: "ENCRYPTION_CONTRACT_UNENCRYPTED",
  ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE: "ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE",
  ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE: "ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE",
  ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH: "ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH",
  END_TIME_EARLIER_THAN_START_TIME: "END_TIME_EARLIER_THAN_START_TIME",
  GET_SECRET_VALUE_DENIED: "GET_SECRET_VALUE_DENIED",
  HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION: "HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION",
  HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT: "HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT",
  HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED: "HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED",
  HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION: "HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION",
  HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE: "HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE",
  HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION: "HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION",
  INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION: "INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION",
  INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION: "INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION",
  INCOMPATIBLE_XML_ENCODING: "INCOMPATIBLE_XML_ENCODING",
  INVALID_HARVEST_JOB_DURATION: "INVALID_HARVEST_JOB_DURATION",
  INVALID_MANIFEST_FILTER: "INVALID_MANIFEST_FILTER",
  INVALID_PAGINATION_MAX_RESULTS: "INVALID_PAGINATION_MAX_RESULTS",
  INVALID_PAGINATION_TOKEN: "INVALID_PAGINATION_TOKEN",
  INVALID_POLICY: "INVALID_POLICY",
  INVALID_ROLE_ARN: "INVALID_ROLE_ARN",
  INVALID_SECRET: "INVALID_SECRET",
  INVALID_SECRET_FORMAT: "INVALID_SECRET_FORMAT",
  INVALID_SECRET_KEY: "INVALID_SECRET_KEY",
  INVALID_SECRET_VALUE: "INVALID_SECRET_VALUE",
  INVALID_TIME_DELAY_SECONDS: "INVALID_TIME_DELAY_SECONDS",
  ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST: "ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST",
  ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST: "ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST",
  ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST: "ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST",
  ISM_CONTAINER_TYPE_WITH_SCTE: "ISM_CONTAINER_TYPE_WITH_SCTE",
  ISM_CONTAINER_WITH_KEY_ROTATION: "ISM_CONTAINER_WITH_KEY_ROTATION",
  MALFORMED_SECRET_ARN: "MALFORMED_SECRET_ARN",
  MANIFEST_DRM_SYSTEMS_INCOMPATIBLE: "MANIFEST_DRM_SYSTEMS_INCOMPATIBLE",
  MANIFEST_NAME_COLLISION: "MANIFEST_NAME_COLLISION",
  MEMBER_DOES_NOT_MATCH_PATTERN: "MEMBER_DOES_NOT_MATCH_PATTERN",
  MEMBER_INVALID: "MEMBER_INVALID",
  MEMBER_INVALID_ENUM_VALUE: "MEMBER_INVALID_ENUM_VALUE",
  MEMBER_MAX_LENGTH: "MEMBER_MAX_LENGTH",
  MEMBER_MAX_VALUE: "MEMBER_MAX_VALUE",
  MEMBER_MIN_LENGTH: "MEMBER_MIN_LENGTH",
  MEMBER_MIN_VALUE: "MEMBER_MIN_VALUE",
  MEMBER_MISSING: "MEMBER_MISSING",
  NONE_MODE_WITH_TIMING_SOURCE: "NONE_MODE_WITH_TIMING_SOURCE",
  NUM_MANIFESTS_HIGH: "NUM_MANIFESTS_HIGH",
  NUM_MANIFESTS_LOW: "NUM_MANIFESTS_LOW",
  ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION:
    "ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION",
  ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING: "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING",
  ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION: "ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION",
  ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION: "ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION",
  PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES: "PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES",
  ROLE_ARN_INVALID_FORMAT: "ROLE_ARN_INVALID_FORMAT",
  ROLE_ARN_LENGTH_OUT_OF_RANGE: "ROLE_ARN_LENGTH_OUT_OF_RANGE",
  ROLE_ARN_NOT_ASSUMABLE: "ROLE_ARN_NOT_ASSUMABLE",
  SECRET_ARN_RESOURCE_NOT_FOUND: "SECRET_ARN_RESOURCE_NOT_FOUND",
  SECRET_FROM_DIFFERENT_ACCOUNT: "SECRET_FROM_DIFFERENT_ACCOUNT",
  SECRET_FROM_DIFFERENT_REGION: "SECRET_FROM_DIFFERENT_REGION",
  SECRET_IS_NOT_ONE_KEY_VALUE_PAIR: "SECRET_IS_NOT_ONE_KEY_VALUE_PAIR",
  SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY: "SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY",
  START_TAG_TIME_OFFSET_INVALID: "START_TAG_TIME_OFFSET_INVALID",
  TIMING_SOURCE_MISSING: "TIMING_SOURCE_MISSING",
  TOO_MANY_IN_PROGRESS_HARVEST_JOBS: "TOO_MANY_IN_PROGRESS_HARVEST_JOBS",
  TOO_MANY_SECRETS: "TOO_MANY_SECRETS",
  TS_CONTAINER_TYPE_WITH_DASH_MANIFEST: "TS_CONTAINER_TYPE_WITH_DASH_MANIFEST",
  TS_CONTAINER_TYPE_WITH_MSS_MANIFEST: "TS_CONTAINER_TYPE_WITH_MSS_MANIFEST",
  UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION: "UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION",
  URL_INVALID: "URL_INVALID",
  URL_LINK_LOCAL_ADDRESS: "URL_LINK_LOCAL_ADDRESS",
  URL_LOCAL_ADDRESS: "URL_LOCAL_ADDRESS",
  URL_LOOPBACK_ADDRESS: "URL_LOOPBACK_ADDRESS",
  URL_MULTICAST_ADDRESS: "URL_MULTICAST_ADDRESS",
  URL_PORT: "URL_PORT",
  URL_SCHEME: "URL_SCHEME",
  URL_UNKNOWN_HOST: "URL_UNKNOWN_HOST",
  URL_USER_INFO: "URL_USER_INFO",
} as const;
/**
 * @public
 */
export type ValidationExceptionType = (typeof ValidationExceptionType)[keyof typeof ValidationExceptionType];

/**
 * @public
 * @enum
 */
export const InputType = {
  CMAF: "CMAF",
  HLS: "HLS",
} as const;
/**
 * @public
 */
export type InputType = (typeof InputType)[keyof typeof InputType];

/**
 * @public
 * @enum
 */
export const ContainerType = {
  CMAF: "CMAF",
  ISM: "ISM",
  TS: "TS",
} as const;
/**
 * @public
 */
export type ContainerType = (typeof ContainerType)[keyof typeof ContainerType];

/**
 * @public
 * @enum
 */
export const DashCompactness = {
  NONE: "NONE",
  STANDARD: "STANDARD",
} as const;
/**
 * @public
 */
export type DashCompactness = (typeof DashCompactness)[keyof typeof DashCompactness];

/**
 * @public
 * @enum
 */
export const DashDrmSignaling = {
  INDIVIDUAL: "INDIVIDUAL",
  REFERENCED: "REFERENCED",
} as const;
/**
 * @public
 */
export type DashDrmSignaling = (typeof DashDrmSignaling)[keyof typeof DashDrmSignaling];

/**
 * @public
 * @enum
 */
export const DashPeriodTrigger = {
  AVAILS: "AVAILS",
  DRM_KEY_ROTATION: "DRM_KEY_ROTATION",
  NONE: "NONE",
  SOURCE_CHANGES: "SOURCE_CHANGES",
  SOURCE_DISRUPTIONS: "SOURCE_DISRUPTIONS",
} as const;
/**
 * @public
 */
export type DashPeriodTrigger = (typeof DashPeriodTrigger)[keyof typeof DashPeriodTrigger];

/**
 * @public
 * @enum
 */
export const DashProfile = {
  DVB_DASH: "DVB_DASH",
} as const;
/**
 * @public
 */
export type DashProfile = (typeof DashProfile)[keyof typeof DashProfile];

/**
 * @public
 * @enum
 */
export const DashSegmentTemplateFormat = {
  NUMBER_WITH_TIMELINE: "NUMBER_WITH_TIMELINE",
} as const;
/**
 * @public
 */
export type DashSegmentTemplateFormat = (typeof DashSegmentTemplateFormat)[keyof typeof DashSegmentTemplateFormat];

/**
 * @public
 * @enum
 */
export const DashTtmlProfile = {
  EBU_TT_D_101: "EBU_TT_D_101",
  IMSC_1: "IMSC_1",
} as const;
/**
 * @public
 */
export type DashTtmlProfile = (typeof DashTtmlProfile)[keyof typeof DashTtmlProfile];

/**
 * @public
 * @enum
 */
export const DashUtcTimingMode = {
  HTTP_HEAD: "HTTP_HEAD",
  HTTP_ISO: "HTTP_ISO",
  HTTP_XSDATE: "HTTP_XSDATE",
  UTC_DIRECT: "UTC_DIRECT",
} as const;
/**
 * @public
 */
export type DashUtcTimingMode = (typeof DashUtcTimingMode)[keyof typeof DashUtcTimingMode];

/**
 * @public
 * @enum
 */
export const EndpointErrorCondition = {
  INCOMPLETE_MANIFEST: "INCOMPLETE_MANIFEST",
  MISSING_DRM_KEY: "MISSING_DRM_KEY",
  SLATE_INPUT: "SLATE_INPUT",
  STALE_MANIFEST: "STALE_MANIFEST",
} as const;
/**
 * @public
 */
export type EndpointErrorCondition = (typeof EndpointErrorCondition)[keyof typeof EndpointErrorCondition];

/**
 * @public
 * @enum
 */
export const MssManifestLayout = {
  COMPACT: "COMPACT",
  FULL: "FULL",
} as const;
/**
 * @public
 */
export type MssManifestLayout = (typeof MssManifestLayout)[keyof typeof MssManifestLayout];

/**
 * @public
 * @enum
 */
export const CmafEncryptionMethod = {
  CBCS: "CBCS",
  CENC: "CENC",
} as const;
/**
 * @public
 */
export type CmafEncryptionMethod = (typeof CmafEncryptionMethod)[keyof typeof CmafEncryptionMethod];

/**
 * @public
 * @enum
 */
export const IsmEncryptionMethod = {
  CENC: "CENC",
} as const;
/**
 * @public
 */
export type IsmEncryptionMethod = (typeof IsmEncryptionMethod)[keyof typeof IsmEncryptionMethod];

/**
 * @public
 * @enum
 */
export const TsEncryptionMethod = {
  AES_128: "AES_128",
  SAMPLE_AES: "SAMPLE_AES",
} as const;
/**
 * @public
 */
export type TsEncryptionMethod = (typeof TsEncryptionMethod)[keyof typeof TsEncryptionMethod];

/**
 * @public
 * @enum
 */
export const DrmSystem = {
  CLEAR_KEY_AES_128: "CLEAR_KEY_AES_128",
  FAIRPLAY: "FAIRPLAY",
  IRDETO: "IRDETO",
  PLAYREADY: "PLAYREADY",
  WIDEVINE: "WIDEVINE",
} as const;
/**
 * @public
 */
export type DrmSystem = (typeof DrmSystem)[keyof typeof DrmSystem];

/**
 * @public
 * @enum
 */
export const PresetSpeke20Audio = {
  PRESET_AUDIO_1: "PRESET_AUDIO_1",
  PRESET_AUDIO_2: "PRESET_AUDIO_2",
  PRESET_AUDIO_3: "PRESET_AUDIO_3",
  SHARED: "SHARED",
  UNENCRYPTED: "UNENCRYPTED",
} as const;
/**
 * @public
 */
export type PresetSpeke20Audio = (typeof PresetSpeke20Audio)[keyof typeof PresetSpeke20Audio];

/**
 * @public
 * @enum
 */
export const PresetSpeke20Video = {
  PRESET_VIDEO_1: "PRESET_VIDEO_1",
  PRESET_VIDEO_2: "PRESET_VIDEO_2",
  PRESET_VIDEO_3: "PRESET_VIDEO_3",
  PRESET_VIDEO_4: "PRESET_VIDEO_4",
  PRESET_VIDEO_5: "PRESET_VIDEO_5",
  PRESET_VIDEO_6: "PRESET_VIDEO_6",
  PRESET_VIDEO_7: "PRESET_VIDEO_7",
  PRESET_VIDEO_8: "PRESET_VIDEO_8",
  SHARED: "SHARED",
  UNENCRYPTED: "UNENCRYPTED",
} as const;
/**
 * @public
 */
export type PresetSpeke20Video = (typeof PresetSpeke20Video)[keyof typeof PresetSpeke20Video];

/**
 * @public
 * @enum
 */
export const ScteFilter = {
  BREAK: "BREAK",
  DISTRIBUTOR_ADVERTISEMENT: "DISTRIBUTOR_ADVERTISEMENT",
  DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY: "DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY",
  DISTRIBUTOR_PLACEMENT_OPPORTUNITY: "DISTRIBUTOR_PLACEMENT_OPPORTUNITY",
  PROGRAM: "PROGRAM",
  PROVIDER_ADVERTISEMENT: "PROVIDER_ADVERTISEMENT",
  PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY: "PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY",
  PROVIDER_PLACEMENT_OPPORTUNITY: "PROVIDER_PLACEMENT_OPPORTUNITY",
  SPLICE_INSERT: "SPLICE_INSERT",
} as const;
/**
 * @public
 */
export type ScteFilter = (typeof ScteFilter)[keyof typeof ScteFilter];

/**
 * @public
 * @enum
 */
export const ScteInSegments = {
  ALL: "ALL",
  NONE: "NONE",
} as const;
/**
 * @public
 */
export type ScteInSegments = (typeof ScteInSegments)[keyof typeof ScteInSegments];

/**
 * @public
 * @enum
 */
export const HarvestJobStatus = {
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  IN_PROGRESS: "IN_PROGRESS",
  QUEUED: "QUEUED",
} as const;
/**
 * @public
 */
export type HarvestJobStatus = (typeof HarvestJobStatus)[keyof typeof HarvestJobStatus];
