import { AddFlowOutputsCommandInput, AddFlowOutputsCommandOutput } from "../commands/AddFlowOutputsCommand";
import { CreateFlowCommandInput, CreateFlowCommandOutput } from "../commands/CreateFlowCommand";
import { DeleteFlowCommandInput, DeleteFlowCommandOutput } from "../commands/DeleteFlowCommand";
import { DescribeFlowCommandInput, DescribeFlowCommandOutput } from "../commands/DescribeFlowCommand";
import { GrantFlowEntitlementsCommandInput, GrantFlowEntitlementsCommandOutput } from "../commands/GrantFlowEntitlementsCommand";
import { ListEntitlementsCommandInput, ListEntitlementsCommandOutput } from "../commands/ListEntitlementsCommand";
import { ListFlowsCommandInput, ListFlowsCommandOutput } from "../commands/ListFlowsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { RemoveFlowOutputCommandInput, RemoveFlowOutputCommandOutput } from "../commands/RemoveFlowOutputCommand";
import { RevokeFlowEntitlementCommandInput, RevokeFlowEntitlementCommandOutput } from "../commands/RevokeFlowEntitlementCommand";
import { StartFlowCommandInput, StartFlowCommandOutput } from "../commands/StartFlowCommand";
import { StopFlowCommandInput, StopFlowCommandOutput } from "../commands/StopFlowCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateFlowEntitlementCommandInput, UpdateFlowEntitlementCommandOutput } from "../commands/UpdateFlowEntitlementCommand";
import { UpdateFlowOutputCommandInput, UpdateFlowOutputCommandOutput } from "../commands/UpdateFlowOutputCommand";
import { UpdateFlowSourceCommandInput, UpdateFlowSourceCommandOutput } from "../commands/UpdateFlowSourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_restJson1_1AddFlowOutputsCommand(input: AddFlowOutputsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1CreateFlowCommand(input: CreateFlowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DeleteFlowCommand(input: DeleteFlowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1DescribeFlowCommand(input: DescribeFlowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1GrantFlowEntitlementsCommand(input: GrantFlowEntitlementsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListEntitlementsCommand(input: ListEntitlementsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListFlowsCommand(input: ListFlowsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1RemoveFlowOutputCommand(input: RemoveFlowOutputCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1RevokeFlowEntitlementCommand(input: RevokeFlowEntitlementCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1StartFlowCommand(input: StartFlowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1StopFlowCommand(input: StopFlowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateFlowEntitlementCommand(input: UpdateFlowEntitlementCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateFlowOutputCommand(input: UpdateFlowOutputCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_restJson1_1UpdateFlowSourceCommand(input: UpdateFlowSourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_restJson1_1AddFlowOutputsCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddFlowOutputsCommandOutput>;
export declare function deserializeAws_restJson1_1CreateFlowCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateFlowCommandOutput>;
export declare function deserializeAws_restJson1_1DeleteFlowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFlowCommandOutput>;
export declare function deserializeAws_restJson1_1DescribeFlowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeFlowCommandOutput>;
export declare function deserializeAws_restJson1_1GrantFlowEntitlementsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GrantFlowEntitlementsCommandOutput>;
export declare function deserializeAws_restJson1_1ListEntitlementsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListEntitlementsCommandOutput>;
export declare function deserializeAws_restJson1_1ListFlowsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFlowsCommandOutput>;
export declare function deserializeAws_restJson1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_restJson1_1RemoveFlowOutputCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveFlowOutputCommandOutput>;
export declare function deserializeAws_restJson1_1RevokeFlowEntitlementCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokeFlowEntitlementCommandOutput>;
export declare function deserializeAws_restJson1_1StartFlowCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartFlowCommandOutput>;
export declare function deserializeAws_restJson1_1StopFlowCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopFlowCommandOutput>;
export declare function deserializeAws_restJson1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateFlowEntitlementCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFlowEntitlementCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateFlowOutputCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFlowOutputCommandOutput>;
export declare function deserializeAws_restJson1_1UpdateFlowSourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateFlowSourceCommandOutput>;
