// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AddPermission$,
  AddPermissionCommand,
  BatchEntryIdsNotDistinct$,
  BatchRequestTooLong$,
  CancelMessageMoveTask$,
  CancelMessageMoveTaskCommand,
  ChangeMessageVisibility$,
  ChangeMessageVisibilityBatch$,
  ChangeMessageVisibilityBatchCommand,
  ChangeMessageVisibilityCommand,
  CreateQueue$,
  CreateQueueCommand,
  DeleteMessage$,
  DeleteMessageBatch$,
  DeleteMessageBatchCommand,
  DeleteMessageCommand,
  DeleteQueue$,
  DeleteQueueCommand,
  EmptyBatchRequest$,
  GetQueueAttributes$,
  GetQueueAttributesCommand,
  GetQueueUrl$,
  GetQueueUrlCommand,
  InvalidAddress$,
  InvalidAttributeName$,
  InvalidAttributeValue$,
  InvalidBatchEntryId$,
  InvalidIdFormat$,
  InvalidMessageContents$,
  InvalidSecurity$,
  KmsAccessDenied$,
  KmsDisabled$,
  KmsInvalidKeyUsage$,
  KmsInvalidState$,
  KmsNotFound$,
  KmsOptInRequired$,
  KmsThrottled$,
  ListDeadLetterSourceQueues$,
  ListDeadLetterSourceQueuesCommand,
  ListMessageMoveTasks$,
  ListMessageMoveTasksCommand,
  ListQueues$,
  ListQueuesCommand,
  ListQueueTags$,
  ListQueueTagsCommand,
  MessageNotInflight$,
  OverLimit$,
  PurgeQueue$,
  PurgeQueueCommand,
  PurgeQueueInProgress$,
  QueueDeletedRecently$,
  QueueDoesNotExist$,
  QueueNameExists$,
  ReceiptHandleIsInvalid$,
  ReceiveMessage$,
  ReceiveMessageCommand,
  RemovePermission$,
  RemovePermissionCommand,
  RequestThrottled$,
  ResourceNotFoundException$,
  SendMessage$,
  SendMessageBatch$,
  SendMessageBatchCommand,
  SendMessageCommand,
  SetQueueAttributes$,
  SetQueueAttributesCommand,
  SQSClient,
  StartMessageMoveTask$,
  StartMessageMoveTaskCommand,
  TagQueue$,
  TagQueueCommand,
  TooManyEntriesInBatchRequest$,
  UnsupportedOperation$,
  UntagQueue$,
  UntagQueueCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = SQSClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("SQSClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AddPermission$, AddPermissionCommand],
      [CancelMessageMoveTask$, CancelMessageMoveTaskCommand],
      [ChangeMessageVisibility$, ChangeMessageVisibilityCommand],
      [ChangeMessageVisibilityBatch$, ChangeMessageVisibilityBatchCommand],
      [CreateQueue$, CreateQueueCommand],
      [DeleteMessage$, DeleteMessageCommand],
      [DeleteMessageBatch$, DeleteMessageBatchCommand],
      [DeleteQueue$, DeleteQueueCommand],
      [GetQueueAttributes$, GetQueueAttributesCommand],
      [GetQueueUrl$, GetQueueUrlCommand],
      [ListDeadLetterSourceQueues$, ListDeadLetterSourceQueuesCommand],
      [ListMessageMoveTasks$, ListMessageMoveTasksCommand],
      [ListQueues$, ListQueuesCommand],
      [ListQueueTags$, ListQueueTagsCommand],
      [PurgeQueue$, PurgeQueueCommand],
      [ReceiveMessage$, ReceiveMessageCommand],
      [RemovePermission$, RemovePermissionCommand],
      [SendMessage$, SendMessageCommand],
      [SendMessageBatch$, SendMessageBatchCommand],
      [SetQueueAttributes$, SetQueueAttributesCommand],
      [StartMessageMoveTask$, StartMessageMoveTaskCommand],
      [TagQueue$, TagQueueCommand],
      [UntagQueue$, UntagQueueCommand],
    ]),
    errors: [
      BatchEntryIdsNotDistinct$,
      BatchRequestTooLong$,
      EmptyBatchRequest$,
      InvalidAddress$,
      InvalidAttributeName$,
      InvalidAttributeValue$,
      InvalidBatchEntryId$,
      InvalidIdFormat$,
      InvalidMessageContents$,
      InvalidSecurity$,
      KmsAccessDenied$,
      KmsDisabled$,
      KmsInvalidKeyUsage$,
      KmsInvalidState$,
      KmsNotFound$,
      KmsOptInRequired$,
      KmsThrottled$,
      MessageNotInflight$,
      OverLimit$,
      PurgeQueueInProgress$,
      QueueDeletedRecently$,
      QueueDoesNotExist$,
      QueueNameExists$,
      ReceiptHandleIsInvalid$,
      RequestThrottled$,
      ResourceNotFoundException$,
      TooManyEntriesInBatchRequest$,
      UnsupportedOperation$,
    ],
  });
  runner.run();
}, 30_000);
