// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  CloudWatchClient,
  DeleteAlarmMuteRule$,
  DeleteAlarmMuteRuleCommand,
  DeleteAlarms$,
  DeleteAlarmsCommand,
  DeleteAnomalyDetector$,
  DeleteAnomalyDetectorCommand,
  DeleteDashboards$,
  DeleteDashboardsCommand,
  DeleteInsightRules$,
  DeleteInsightRulesCommand,
  DeleteMetricStream$,
  DeleteMetricStreamCommand,
  DescribeAlarmContributors$,
  DescribeAlarmContributorsCommand,
  DescribeAlarmHistory$,
  DescribeAlarmHistoryCommand,
  DescribeAlarms$,
  DescribeAlarmsCommand,
  DescribeAlarmsForMetric$,
  DescribeAlarmsForMetricCommand,
  DescribeAnomalyDetectors$,
  DescribeAnomalyDetectorsCommand,
  DescribeInsightRules$,
  DescribeInsightRulesCommand,
  DisableAlarmActions$,
  DisableAlarmActionsCommand,
  DisableInsightRules$,
  DisableInsightRulesCommand,
  EnableAlarmActions$,
  EnableAlarmActionsCommand,
  EnableInsightRules$,
  EnableInsightRulesCommand,
  GetAlarmMuteRule$,
  GetAlarmMuteRuleCommand,
  GetDashboard$,
  GetDashboardCommand,
  GetInsightRuleReport$,
  GetInsightRuleReportCommand,
  GetMetricData$,
  GetMetricDataCommand,
  GetMetricStatistics$,
  GetMetricStatisticsCommand,
  GetMetricStream$,
  GetMetricStreamCommand,
  GetMetricWidgetImage$,
  GetMetricWidgetImageCommand,
  ListAlarmMuteRules$,
  ListAlarmMuteRulesCommand,
  ListDashboards$,
  ListDashboardsCommand,
  ListManagedInsightRules$,
  ListManagedInsightRulesCommand,
  ListMetrics$,
  ListMetricsCommand,
  ListMetricStreams$,
  ListMetricStreamsCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  PutAlarmMuteRule$,
  PutAlarmMuteRuleCommand,
  PutAnomalyDetector$,
  PutAnomalyDetectorCommand,
  PutCompositeAlarm$,
  PutCompositeAlarmCommand,
  PutDashboard$,
  PutDashboardCommand,
  PutInsightRule$,
  PutInsightRuleCommand,
  PutManagedInsightRules$,
  PutManagedInsightRulesCommand,
  PutMetricAlarm$,
  PutMetricAlarmCommand,
  PutMetricData$,
  PutMetricDataCommand,
  PutMetricStream$,
  PutMetricStreamCommand,
  SetAlarmState$,
  SetAlarmStateCommand,
  StartMetricStreams$,
  StartMetricStreamsCommand,
  StopMetricStreams$,
  StopMetricStreamsCommand,
  TagResource$,
  TagResourceCommand,
  UntagResource$,
  UntagResourceCommand,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = CloudWatchClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe(
  "CloudWatchClient" + ` (${mode})`,
  () => {
    const runner = new SnapshotRunner({
      snapshotDirPath: join(__dirname, "snapshots"),
      Client,
      mode,
      testCase(caseName: string, run: () => Promise<void>) {
        it(caseName, run);
      },
      assertions(caseName: string, expected: string, actual: string): Promise<void> {
        expect(actual).toEqual(expected);
        return Promise.resolve();
      },
      schemas: new Map<any, any>([
        [DeleteAlarmMuteRule$, DeleteAlarmMuteRuleCommand],
        [DeleteAlarms$, DeleteAlarmsCommand],
        [DeleteAnomalyDetector$, DeleteAnomalyDetectorCommand],
        [DeleteDashboards$, DeleteDashboardsCommand],
        [DeleteInsightRules$, DeleteInsightRulesCommand],
        [DeleteMetricStream$, DeleteMetricStreamCommand],
        [DescribeAlarmContributors$, DescribeAlarmContributorsCommand],
        [DescribeAlarmHistory$, DescribeAlarmHistoryCommand],
        [DescribeAlarms$, DescribeAlarmsCommand],
        [DescribeAlarmsForMetric$, DescribeAlarmsForMetricCommand],
        [DescribeAnomalyDetectors$, DescribeAnomalyDetectorsCommand],
        [DescribeInsightRules$, DescribeInsightRulesCommand],
        [DisableAlarmActions$, DisableAlarmActionsCommand],
        [DisableInsightRules$, DisableInsightRulesCommand],
        [EnableAlarmActions$, EnableAlarmActionsCommand],
        [EnableInsightRules$, EnableInsightRulesCommand],
        [GetAlarmMuteRule$, GetAlarmMuteRuleCommand],
        [GetDashboard$, GetDashboardCommand],
        [GetInsightRuleReport$, GetInsightRuleReportCommand],
        [GetMetricData$, GetMetricDataCommand],
        [GetMetricStatistics$, GetMetricStatisticsCommand],
        [GetMetricStream$, GetMetricStreamCommand],
        [GetMetricWidgetImage$, GetMetricWidgetImageCommand],
        [ListAlarmMuteRules$, ListAlarmMuteRulesCommand],
        [ListDashboards$, ListDashboardsCommand],
        [ListManagedInsightRules$, ListManagedInsightRulesCommand],
        [ListMetrics$, ListMetricsCommand],
        [ListMetricStreams$, ListMetricStreamsCommand],
        [ListTagsForResource$, ListTagsForResourceCommand],
        [PutAlarmMuteRule$, PutAlarmMuteRuleCommand],
        [PutAnomalyDetector$, PutAnomalyDetectorCommand],
        [PutCompositeAlarm$, PutCompositeAlarmCommand],
        [PutDashboard$, PutDashboardCommand],
        [PutInsightRule$, PutInsightRuleCommand],
        [PutManagedInsightRules$, PutManagedInsightRulesCommand],
        [PutMetricAlarm$, PutMetricAlarmCommand],
        [PutMetricData$, PutMetricDataCommand],
        [PutMetricStream$, PutMetricStreamCommand],
        [SetAlarmState$, SetAlarmStateCommand],
        [StartMetricStreams$, StartMetricStreamsCommand],
        [StopMetricStreams$, StopMetricStreamsCommand],
        [TagResource$, TagResourceCommand],
        [UntagResource$, UntagResourceCommand],
      ]),
    });

    runner.run();
  },
  30_000
);
