import { BatchCreatePartitionCommandInput, BatchCreatePartitionCommandOutput } from "../commands/BatchCreatePartitionCommand";
import { BatchDeleteConnectionCommandInput, BatchDeleteConnectionCommandOutput } from "../commands/BatchDeleteConnectionCommand";
import { BatchDeletePartitionCommandInput, BatchDeletePartitionCommandOutput } from "../commands/BatchDeletePartitionCommand";
import { BatchDeleteTableCommandInput, BatchDeleteTableCommandOutput } from "../commands/BatchDeleteTableCommand";
import { BatchDeleteTableVersionCommandInput, BatchDeleteTableVersionCommandOutput } from "../commands/BatchDeleteTableVersionCommand";
import { BatchGetCrawlersCommandInput, BatchGetCrawlersCommandOutput } from "../commands/BatchGetCrawlersCommand";
import { BatchGetDevEndpointsCommandInput, BatchGetDevEndpointsCommandOutput } from "../commands/BatchGetDevEndpointsCommand";
import { BatchGetJobsCommandInput, BatchGetJobsCommandOutput } from "../commands/BatchGetJobsCommand";
import { BatchGetPartitionCommandInput, BatchGetPartitionCommandOutput } from "../commands/BatchGetPartitionCommand";
import { BatchGetTriggersCommandInput, BatchGetTriggersCommandOutput } from "../commands/BatchGetTriggersCommand";
import { BatchGetWorkflowsCommandInput, BatchGetWorkflowsCommandOutput } from "../commands/BatchGetWorkflowsCommand";
import { BatchStopJobRunCommandInput, BatchStopJobRunCommandOutput } from "../commands/BatchStopJobRunCommand";
import { CancelMLTaskRunCommandInput, CancelMLTaskRunCommandOutput } from "../commands/CancelMLTaskRunCommand";
import { CreateClassifierCommandInput, CreateClassifierCommandOutput } from "../commands/CreateClassifierCommand";
import { CreateConnectionCommandInput, CreateConnectionCommandOutput } from "../commands/CreateConnectionCommand";
import { CreateCrawlerCommandInput, CreateCrawlerCommandOutput } from "../commands/CreateCrawlerCommand";
import { CreateDatabaseCommandInput, CreateDatabaseCommandOutput } from "../commands/CreateDatabaseCommand";
import { CreateDevEndpointCommandInput, CreateDevEndpointCommandOutput } from "../commands/CreateDevEndpointCommand";
import { CreateJobCommandInput, CreateJobCommandOutput } from "../commands/CreateJobCommand";
import { CreateMLTransformCommandInput, CreateMLTransformCommandOutput } from "../commands/CreateMLTransformCommand";
import { CreatePartitionCommandInput, CreatePartitionCommandOutput } from "../commands/CreatePartitionCommand";
import { CreateScriptCommandInput, CreateScriptCommandOutput } from "../commands/CreateScriptCommand";
import { CreateSecurityConfigurationCommandInput, CreateSecurityConfigurationCommandOutput } from "../commands/CreateSecurityConfigurationCommand";
import { CreateTableCommandInput, CreateTableCommandOutput } from "../commands/CreateTableCommand";
import { CreateTriggerCommandInput, CreateTriggerCommandOutput } from "../commands/CreateTriggerCommand";
import { CreateUserDefinedFunctionCommandInput, CreateUserDefinedFunctionCommandOutput } from "../commands/CreateUserDefinedFunctionCommand";
import { CreateWorkflowCommandInput, CreateWorkflowCommandOutput } from "../commands/CreateWorkflowCommand";
import { DeleteClassifierCommandInput, DeleteClassifierCommandOutput } from "../commands/DeleteClassifierCommand";
import { DeleteConnectionCommandInput, DeleteConnectionCommandOutput } from "../commands/DeleteConnectionCommand";
import { DeleteCrawlerCommandInput, DeleteCrawlerCommandOutput } from "../commands/DeleteCrawlerCommand";
import { DeleteDatabaseCommandInput, DeleteDatabaseCommandOutput } from "../commands/DeleteDatabaseCommand";
import { DeleteDevEndpointCommandInput, DeleteDevEndpointCommandOutput } from "../commands/DeleteDevEndpointCommand";
import { DeleteJobCommandInput, DeleteJobCommandOutput } from "../commands/DeleteJobCommand";
import { DeleteMLTransformCommandInput, DeleteMLTransformCommandOutput } from "../commands/DeleteMLTransformCommand";
import { DeletePartitionCommandInput, DeletePartitionCommandOutput } from "../commands/DeletePartitionCommand";
import { DeleteResourcePolicyCommandInput, DeleteResourcePolicyCommandOutput } from "../commands/DeleteResourcePolicyCommand";
import { DeleteSecurityConfigurationCommandInput, DeleteSecurityConfigurationCommandOutput } from "../commands/DeleteSecurityConfigurationCommand";
import { DeleteTableCommandInput, DeleteTableCommandOutput } from "../commands/DeleteTableCommand";
import { DeleteTableVersionCommandInput, DeleteTableVersionCommandOutput } from "../commands/DeleteTableVersionCommand";
import { DeleteTriggerCommandInput, DeleteTriggerCommandOutput } from "../commands/DeleteTriggerCommand";
import { DeleteUserDefinedFunctionCommandInput, DeleteUserDefinedFunctionCommandOutput } from "../commands/DeleteUserDefinedFunctionCommand";
import { DeleteWorkflowCommandInput, DeleteWorkflowCommandOutput } from "../commands/DeleteWorkflowCommand";
import { GetCatalogImportStatusCommandInput, GetCatalogImportStatusCommandOutput } from "../commands/GetCatalogImportStatusCommand";
import { GetClassifierCommandInput, GetClassifierCommandOutput } from "../commands/GetClassifierCommand";
import { GetClassifiersCommandInput, GetClassifiersCommandOutput } from "../commands/GetClassifiersCommand";
import { GetConnectionCommandInput, GetConnectionCommandOutput } from "../commands/GetConnectionCommand";
import { GetConnectionsCommandInput, GetConnectionsCommandOutput } from "../commands/GetConnectionsCommand";
import { GetCrawlerCommandInput, GetCrawlerCommandOutput } from "../commands/GetCrawlerCommand";
import { GetCrawlerMetricsCommandInput, GetCrawlerMetricsCommandOutput } from "../commands/GetCrawlerMetricsCommand";
import { GetCrawlersCommandInput, GetCrawlersCommandOutput } from "../commands/GetCrawlersCommand";
import { GetDataCatalogEncryptionSettingsCommandInput, GetDataCatalogEncryptionSettingsCommandOutput } from "../commands/GetDataCatalogEncryptionSettingsCommand";
import { GetDatabaseCommandInput, GetDatabaseCommandOutput } from "../commands/GetDatabaseCommand";
import { GetDatabasesCommandInput, GetDatabasesCommandOutput } from "../commands/GetDatabasesCommand";
import { GetDataflowGraphCommandInput, GetDataflowGraphCommandOutput } from "../commands/GetDataflowGraphCommand";
import { GetDevEndpointCommandInput, GetDevEndpointCommandOutput } from "../commands/GetDevEndpointCommand";
import { GetDevEndpointsCommandInput, GetDevEndpointsCommandOutput } from "../commands/GetDevEndpointsCommand";
import { GetJobBookmarkCommandInput, GetJobBookmarkCommandOutput } from "../commands/GetJobBookmarkCommand";
import { GetJobCommandInput, GetJobCommandOutput } from "../commands/GetJobCommand";
import { GetJobRunCommandInput, GetJobRunCommandOutput } from "../commands/GetJobRunCommand";
import { GetJobRunsCommandInput, GetJobRunsCommandOutput } from "../commands/GetJobRunsCommand";
import { GetJobsCommandInput, GetJobsCommandOutput } from "../commands/GetJobsCommand";
import { GetMLTaskRunCommandInput, GetMLTaskRunCommandOutput } from "../commands/GetMLTaskRunCommand";
import { GetMLTaskRunsCommandInput, GetMLTaskRunsCommandOutput } from "../commands/GetMLTaskRunsCommand";
import { GetMLTransformCommandInput, GetMLTransformCommandOutput } from "../commands/GetMLTransformCommand";
import { GetMLTransformsCommandInput, GetMLTransformsCommandOutput } from "../commands/GetMLTransformsCommand";
import { GetMappingCommandInput, GetMappingCommandOutput } from "../commands/GetMappingCommand";
import { GetPartitionCommandInput, GetPartitionCommandOutput } from "../commands/GetPartitionCommand";
import { GetPartitionsCommandInput, GetPartitionsCommandOutput } from "../commands/GetPartitionsCommand";
import { GetPlanCommandInput, GetPlanCommandOutput } from "../commands/GetPlanCommand";
import { GetResourcePolicyCommandInput, GetResourcePolicyCommandOutput } from "../commands/GetResourcePolicyCommand";
import { GetSecurityConfigurationCommandInput, GetSecurityConfigurationCommandOutput } from "../commands/GetSecurityConfigurationCommand";
import { GetSecurityConfigurationsCommandInput, GetSecurityConfigurationsCommandOutput } from "../commands/GetSecurityConfigurationsCommand";
import { GetTableCommandInput, GetTableCommandOutput } from "../commands/GetTableCommand";
import { GetTableVersionCommandInput, GetTableVersionCommandOutput } from "../commands/GetTableVersionCommand";
import { GetTableVersionsCommandInput, GetTableVersionsCommandOutput } from "../commands/GetTableVersionsCommand";
import { GetTablesCommandInput, GetTablesCommandOutput } from "../commands/GetTablesCommand";
import { GetTagsCommandInput, GetTagsCommandOutput } from "../commands/GetTagsCommand";
import { GetTriggerCommandInput, GetTriggerCommandOutput } from "../commands/GetTriggerCommand";
import { GetTriggersCommandInput, GetTriggersCommandOutput } from "../commands/GetTriggersCommand";
import { GetUserDefinedFunctionCommandInput, GetUserDefinedFunctionCommandOutput } from "../commands/GetUserDefinedFunctionCommand";
import { GetUserDefinedFunctionsCommandInput, GetUserDefinedFunctionsCommandOutput } from "../commands/GetUserDefinedFunctionsCommand";
import { GetWorkflowCommandInput, GetWorkflowCommandOutput } from "../commands/GetWorkflowCommand";
import { GetWorkflowRunCommandInput, GetWorkflowRunCommandOutput } from "../commands/GetWorkflowRunCommand";
import { GetWorkflowRunPropertiesCommandInput, GetWorkflowRunPropertiesCommandOutput } from "../commands/GetWorkflowRunPropertiesCommand";
import { GetWorkflowRunsCommandInput, GetWorkflowRunsCommandOutput } from "../commands/GetWorkflowRunsCommand";
import { ImportCatalogToGlueCommandInput, ImportCatalogToGlueCommandOutput } from "../commands/ImportCatalogToGlueCommand";
import { ListCrawlersCommandInput, ListCrawlersCommandOutput } from "../commands/ListCrawlersCommand";
import { ListDevEndpointsCommandInput, ListDevEndpointsCommandOutput } from "../commands/ListDevEndpointsCommand";
import { ListJobsCommandInput, ListJobsCommandOutput } from "../commands/ListJobsCommand";
import { ListTriggersCommandInput, ListTriggersCommandOutput } from "../commands/ListTriggersCommand";
import { ListWorkflowsCommandInput, ListWorkflowsCommandOutput } from "../commands/ListWorkflowsCommand";
import { PutDataCatalogEncryptionSettingsCommandInput, PutDataCatalogEncryptionSettingsCommandOutput } from "../commands/PutDataCatalogEncryptionSettingsCommand";
import { PutResourcePolicyCommandInput, PutResourcePolicyCommandOutput } from "../commands/PutResourcePolicyCommand";
import { PutWorkflowRunPropertiesCommandInput, PutWorkflowRunPropertiesCommandOutput } from "../commands/PutWorkflowRunPropertiesCommand";
import { ResetJobBookmarkCommandInput, ResetJobBookmarkCommandOutput } from "../commands/ResetJobBookmarkCommand";
import { SearchTablesCommandInput, SearchTablesCommandOutput } from "../commands/SearchTablesCommand";
import { StartCrawlerCommandInput, StartCrawlerCommandOutput } from "../commands/StartCrawlerCommand";
import { StartCrawlerScheduleCommandInput, StartCrawlerScheduleCommandOutput } from "../commands/StartCrawlerScheduleCommand";
import { StartExportLabelsTaskRunCommandInput, StartExportLabelsTaskRunCommandOutput } from "../commands/StartExportLabelsTaskRunCommand";
import { StartImportLabelsTaskRunCommandInput, StartImportLabelsTaskRunCommandOutput } from "../commands/StartImportLabelsTaskRunCommand";
import { StartJobRunCommandInput, StartJobRunCommandOutput } from "../commands/StartJobRunCommand";
import { StartMLEvaluationTaskRunCommandInput, StartMLEvaluationTaskRunCommandOutput } from "../commands/StartMLEvaluationTaskRunCommand";
import { StartMLLabelingSetGenerationTaskRunCommandInput, StartMLLabelingSetGenerationTaskRunCommandOutput } from "../commands/StartMLLabelingSetGenerationTaskRunCommand";
import { StartTriggerCommandInput, StartTriggerCommandOutput } from "../commands/StartTriggerCommand";
import { StartWorkflowRunCommandInput, StartWorkflowRunCommandOutput } from "../commands/StartWorkflowRunCommand";
import { StopCrawlerCommandInput, StopCrawlerCommandOutput } from "../commands/StopCrawlerCommand";
import { StopCrawlerScheduleCommandInput, StopCrawlerScheduleCommandOutput } from "../commands/StopCrawlerScheduleCommand";
import { StopTriggerCommandInput, StopTriggerCommandOutput } from "../commands/StopTriggerCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateClassifierCommandInput, UpdateClassifierCommandOutput } from "../commands/UpdateClassifierCommand";
import { UpdateConnectionCommandInput, UpdateConnectionCommandOutput } from "../commands/UpdateConnectionCommand";
import { UpdateCrawlerCommandInput, UpdateCrawlerCommandOutput } from "../commands/UpdateCrawlerCommand";
import { UpdateCrawlerScheduleCommandInput, UpdateCrawlerScheduleCommandOutput } from "../commands/UpdateCrawlerScheduleCommand";
import { UpdateDatabaseCommandInput, UpdateDatabaseCommandOutput } from "../commands/UpdateDatabaseCommand";
import { UpdateDevEndpointCommandInput, UpdateDevEndpointCommandOutput } from "../commands/UpdateDevEndpointCommand";
import { UpdateJobCommandInput, UpdateJobCommandOutput } from "../commands/UpdateJobCommand";
import { UpdateMLTransformCommandInput, UpdateMLTransformCommandOutput } from "../commands/UpdateMLTransformCommand";
import { UpdatePartitionCommandInput, UpdatePartitionCommandOutput } from "../commands/UpdatePartitionCommand";
import { UpdateTableCommandInput, UpdateTableCommandOutput } from "../commands/UpdateTableCommand";
import { UpdateTriggerCommandInput, UpdateTriggerCommandOutput } from "../commands/UpdateTriggerCommand";
import { UpdateUserDefinedFunctionCommandInput, UpdateUserDefinedFunctionCommandOutput } from "../commands/UpdateUserDefinedFunctionCommand";
import { UpdateWorkflowCommandInput, UpdateWorkflowCommandOutput } from "../commands/UpdateWorkflowCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1GetTagsCommand(input: GetTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchCreatePartitionCommand(input: BatchCreatePartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDeleteConnectionCommand(input: BatchDeleteConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDeletePartitionCommand(input: BatchDeletePartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDeleteTableCommand(input: BatchDeleteTableCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDeleteTableVersionCommand(input: BatchDeleteTableVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetPartitionCommand(input: BatchGetPartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateConnectionCommand(input: CreateConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDatabaseCommand(input: CreateDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePartitionCommand(input: CreatePartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTableCommand(input: CreateTableCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateUserDefinedFunctionCommand(input: CreateUserDefinedFunctionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteConnectionCommand(input: DeleteConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDatabaseCommand(input: DeleteDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePartitionCommand(input: DeletePartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteResourcePolicyCommand(input: DeleteResourcePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTableCommand(input: DeleteTableCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTableVersionCommand(input: DeleteTableVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteUserDefinedFunctionCommand(input: DeleteUserDefinedFunctionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCatalogImportStatusCommand(input: GetCatalogImportStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetConnectionCommand(input: GetConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetConnectionsCommand(input: GetConnectionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDataCatalogEncryptionSettingsCommand(input: GetDataCatalogEncryptionSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDatabaseCommand(input: GetDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDatabasesCommand(input: GetDatabasesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPartitionCommand(input: GetPartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPartitionsCommand(input: GetPartitionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetResourcePolicyCommand(input: GetResourcePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTableCommand(input: GetTableCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTableVersionCommand(input: GetTableVersionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTableVersionsCommand(input: GetTableVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTablesCommand(input: GetTablesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetUserDefinedFunctionCommand(input: GetUserDefinedFunctionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetUserDefinedFunctionsCommand(input: GetUserDefinedFunctionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ImportCatalogToGlueCommand(input: ImportCatalogToGlueCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutDataCatalogEncryptionSettingsCommand(input: PutDataCatalogEncryptionSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutResourcePolicyCommand(input: PutResourcePolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SearchTablesCommand(input: SearchTablesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateConnectionCommand(input: UpdateConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDatabaseCommand(input: UpdateDatabaseCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePartitionCommand(input: UpdatePartitionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateTableCommand(input: UpdateTableCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateUserDefinedFunctionCommand(input: UpdateUserDefinedFunctionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetDevEndpointsCommand(input: BatchGetDevEndpointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDevEndpointCommand(input: CreateDevEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSecurityConfigurationCommand(input: CreateSecurityConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDevEndpointCommand(input: DeleteDevEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSecurityConfigurationCommand(input: DeleteSecurityConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDevEndpointCommand(input: GetDevEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDevEndpointsCommand(input: GetDevEndpointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobBookmarkCommand(input: GetJobBookmarkCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSecurityConfigurationCommand(input: GetSecurityConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSecurityConfigurationsCommand(input: GetSecurityConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListDevEndpointsCommand(input: ListDevEndpointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResetJobBookmarkCommand(input: ResetJobBookmarkCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDevEndpointCommand(input: UpdateDevEndpointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelMLTaskRunCommand(input: CancelMLTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateMLTransformCommand(input: CreateMLTransformCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteMLTransformCommand(input: DeleteMLTransformCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMLTaskRunCommand(input: GetMLTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMLTaskRunsCommand(input: GetMLTaskRunsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMLTransformCommand(input: GetMLTransformCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMLTransformsCommand(input: GetMLTransformsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartExportLabelsTaskRunCommand(input: StartExportLabelsTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartImportLabelsTaskRunCommand(input: StartImportLabelsTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartMLEvaluationTaskRunCommand(input: StartMLEvaluationTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartMLLabelingSetGenerationTaskRunCommand(input: StartMLLabelingSetGenerationTaskRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMLTransformCommand(input: UpdateMLTransformCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetJobsCommand(input: BatchGetJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetTriggersCommand(input: BatchGetTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetWorkflowsCommand(input: BatchGetWorkflowsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchStopJobRunCommand(input: BatchStopJobRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateJobCommand(input: CreateJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTriggerCommand(input: CreateTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateWorkflowCommand(input: CreateWorkflowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteJobCommand(input: DeleteJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTriggerCommand(input: DeleteTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteWorkflowCommand(input: DeleteWorkflowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobCommand(input: GetJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobRunCommand(input: GetJobRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobRunsCommand(input: GetJobRunsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetJobsCommand(input: GetJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTriggerCommand(input: GetTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetTriggersCommand(input: GetTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWorkflowCommand(input: GetWorkflowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWorkflowRunCommand(input: GetWorkflowRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWorkflowRunPropertiesCommand(input: GetWorkflowRunPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWorkflowRunsCommand(input: GetWorkflowRunsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListJobsCommand(input: ListJobsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTriggersCommand(input: ListTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListWorkflowsCommand(input: ListWorkflowsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutWorkflowRunPropertiesCommand(input: PutWorkflowRunPropertiesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartJobRunCommand(input: StartJobRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartTriggerCommand(input: StartTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartWorkflowRunCommand(input: StartWorkflowRunCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopTriggerCommand(input: StopTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateJobCommand(input: UpdateJobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateTriggerCommand(input: UpdateTriggerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateWorkflowCommand(input: UpdateWorkflowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetCrawlersCommand(input: BatchGetCrawlersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateClassifierCommand(input: CreateClassifierCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateCrawlerCommand(input: CreateCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateScriptCommand(input: CreateScriptCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteClassifierCommand(input: DeleteClassifierCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteCrawlerCommand(input: DeleteCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetClassifierCommand(input: GetClassifierCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetClassifiersCommand(input: GetClassifiersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCrawlerCommand(input: GetCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCrawlerMetricsCommand(input: GetCrawlerMetricsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCrawlersCommand(input: GetCrawlersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDataflowGraphCommand(input: GetDataflowGraphCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMappingCommand(input: GetMappingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPlanCommand(input: GetPlanCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListCrawlersCommand(input: ListCrawlersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartCrawlerCommand(input: StartCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartCrawlerScheduleCommand(input: StartCrawlerScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopCrawlerCommand(input: StopCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StopCrawlerScheduleCommand(input: StopCrawlerScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateClassifierCommand(input: UpdateClassifierCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateCrawlerCommand(input: UpdateCrawlerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateCrawlerScheduleCommand(input: UpdateCrawlerScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1GetTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTagsCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1BatchCreatePartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchCreatePartitionCommandOutput>;
export declare function deserializeAws_json1_1BatchDeleteConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeleteConnectionCommandOutput>;
export declare function deserializeAws_json1_1BatchDeletePartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeletePartitionCommandOutput>;
export declare function deserializeAws_json1_1BatchDeleteTableCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeleteTableCommandOutput>;
export declare function deserializeAws_json1_1BatchDeleteTableVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDeleteTableVersionCommandOutput>;
export declare function deserializeAws_json1_1BatchGetPartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetPartitionCommandOutput>;
export declare function deserializeAws_json1_1CreateConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateConnectionCommandOutput>;
export declare function deserializeAws_json1_1CreateDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDatabaseCommandOutput>;
export declare function deserializeAws_json1_1CreatePartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePartitionCommandOutput>;
export declare function deserializeAws_json1_1CreateTableCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTableCommandOutput>;
export declare function deserializeAws_json1_1CreateUserDefinedFunctionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateUserDefinedFunctionCommandOutput>;
export declare function deserializeAws_json1_1DeleteConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteConnectionCommandOutput>;
export declare function deserializeAws_json1_1DeleteDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDatabaseCommandOutput>;
export declare function deserializeAws_json1_1DeletePartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePartitionCommandOutput>;
export declare function deserializeAws_json1_1DeleteResourcePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteResourcePolicyCommandOutput>;
export declare function deserializeAws_json1_1DeleteTableCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTableCommandOutput>;
export declare function deserializeAws_json1_1DeleteTableVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTableVersionCommandOutput>;
export declare function deserializeAws_json1_1DeleteUserDefinedFunctionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteUserDefinedFunctionCommandOutput>;
export declare function deserializeAws_json1_1GetCatalogImportStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCatalogImportStatusCommandOutput>;
export declare function deserializeAws_json1_1GetConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetConnectionCommandOutput>;
export declare function deserializeAws_json1_1GetConnectionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetConnectionsCommandOutput>;
export declare function deserializeAws_json1_1GetDataCatalogEncryptionSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDataCatalogEncryptionSettingsCommandOutput>;
export declare function deserializeAws_json1_1GetDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDatabaseCommandOutput>;
export declare function deserializeAws_json1_1GetDatabasesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDatabasesCommandOutput>;
export declare function deserializeAws_json1_1GetPartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPartitionCommandOutput>;
export declare function deserializeAws_json1_1GetPartitionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPartitionsCommandOutput>;
export declare function deserializeAws_json1_1GetResourcePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetResourcePolicyCommandOutput>;
export declare function deserializeAws_json1_1GetTableCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTableCommandOutput>;
export declare function deserializeAws_json1_1GetTableVersionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTableVersionCommandOutput>;
export declare function deserializeAws_json1_1GetTableVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTableVersionsCommandOutput>;
export declare function deserializeAws_json1_1GetTablesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTablesCommandOutput>;
export declare function deserializeAws_json1_1GetUserDefinedFunctionCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetUserDefinedFunctionCommandOutput>;
export declare function deserializeAws_json1_1GetUserDefinedFunctionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetUserDefinedFunctionsCommandOutput>;
export declare function deserializeAws_json1_1ImportCatalogToGlueCommand(output: __HttpResponse, context: __SerdeContext): Promise<ImportCatalogToGlueCommandOutput>;
export declare function deserializeAws_json1_1PutDataCatalogEncryptionSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutDataCatalogEncryptionSettingsCommandOutput>;
export declare function deserializeAws_json1_1PutResourcePolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutResourcePolicyCommandOutput>;
export declare function deserializeAws_json1_1SearchTablesCommand(output: __HttpResponse, context: __SerdeContext): Promise<SearchTablesCommandOutput>;
export declare function deserializeAws_json1_1UpdateConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateConnectionCommandOutput>;
export declare function deserializeAws_json1_1UpdateDatabaseCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDatabaseCommandOutput>;
export declare function deserializeAws_json1_1UpdatePartitionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePartitionCommandOutput>;
export declare function deserializeAws_json1_1UpdateTableCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateTableCommandOutput>;
export declare function deserializeAws_json1_1UpdateUserDefinedFunctionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateUserDefinedFunctionCommandOutput>;
export declare function deserializeAws_json1_1BatchGetDevEndpointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetDevEndpointsCommandOutput>;
export declare function deserializeAws_json1_1CreateDevEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDevEndpointCommandOutput>;
export declare function deserializeAws_json1_1CreateSecurityConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSecurityConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeleteDevEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDevEndpointCommandOutput>;
export declare function deserializeAws_json1_1DeleteSecurityConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSecurityConfigurationCommandOutput>;
export declare function deserializeAws_json1_1GetDevEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDevEndpointCommandOutput>;
export declare function deserializeAws_json1_1GetDevEndpointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDevEndpointsCommandOutput>;
export declare function deserializeAws_json1_1GetJobBookmarkCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobBookmarkCommandOutput>;
export declare function deserializeAws_json1_1GetSecurityConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSecurityConfigurationCommandOutput>;
export declare function deserializeAws_json1_1GetSecurityConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSecurityConfigurationsCommandOutput>;
export declare function deserializeAws_json1_1ListDevEndpointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDevEndpointsCommandOutput>;
export declare function deserializeAws_json1_1ResetJobBookmarkCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetJobBookmarkCommandOutput>;
export declare function deserializeAws_json1_1UpdateDevEndpointCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDevEndpointCommandOutput>;
export declare function deserializeAws_json1_1CancelMLTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelMLTaskRunCommandOutput>;
export declare function deserializeAws_json1_1CreateMLTransformCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateMLTransformCommandOutput>;
export declare function deserializeAws_json1_1DeleteMLTransformCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteMLTransformCommandOutput>;
export declare function deserializeAws_json1_1GetMLTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMLTaskRunCommandOutput>;
export declare function deserializeAws_json1_1GetMLTaskRunsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMLTaskRunsCommandOutput>;
export declare function deserializeAws_json1_1GetMLTransformCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMLTransformCommandOutput>;
export declare function deserializeAws_json1_1GetMLTransformsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMLTransformsCommandOutput>;
export declare function deserializeAws_json1_1StartExportLabelsTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartExportLabelsTaskRunCommandOutput>;
export declare function deserializeAws_json1_1StartImportLabelsTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartImportLabelsTaskRunCommandOutput>;
export declare function deserializeAws_json1_1StartMLEvaluationTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMLEvaluationTaskRunCommandOutput>;
export declare function deserializeAws_json1_1StartMLLabelingSetGenerationTaskRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMLLabelingSetGenerationTaskRunCommandOutput>;
export declare function deserializeAws_json1_1UpdateMLTransformCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMLTransformCommandOutput>;
export declare function deserializeAws_json1_1BatchGetJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetJobsCommandOutput>;
export declare function deserializeAws_json1_1BatchGetTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetTriggersCommandOutput>;
export declare function deserializeAws_json1_1BatchGetWorkflowsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetWorkflowsCommandOutput>;
export declare function deserializeAws_json1_1BatchStopJobRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchStopJobRunCommandOutput>;
export declare function deserializeAws_json1_1CreateJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateJobCommandOutput>;
export declare function deserializeAws_json1_1CreateTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTriggerCommandOutput>;
export declare function deserializeAws_json1_1CreateWorkflowCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateWorkflowCommandOutput>;
export declare function deserializeAws_json1_1DeleteJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteJobCommandOutput>;
export declare function deserializeAws_json1_1DeleteTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTriggerCommandOutput>;
export declare function deserializeAws_json1_1DeleteWorkflowCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteWorkflowCommandOutput>;
export declare function deserializeAws_json1_1GetJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobCommandOutput>;
export declare function deserializeAws_json1_1GetJobRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobRunCommandOutput>;
export declare function deserializeAws_json1_1GetJobRunsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobRunsCommandOutput>;
export declare function deserializeAws_json1_1GetJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetJobsCommandOutput>;
export declare function deserializeAws_json1_1GetTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTriggerCommandOutput>;
export declare function deserializeAws_json1_1GetTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetTriggersCommandOutput>;
export declare function deserializeAws_json1_1GetWorkflowCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWorkflowCommandOutput>;
export declare function deserializeAws_json1_1GetWorkflowRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWorkflowRunCommandOutput>;
export declare function deserializeAws_json1_1GetWorkflowRunPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWorkflowRunPropertiesCommandOutput>;
export declare function deserializeAws_json1_1GetWorkflowRunsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWorkflowRunsCommandOutput>;
export declare function deserializeAws_json1_1ListJobsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListJobsCommandOutput>;
export declare function deserializeAws_json1_1ListTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTriggersCommandOutput>;
export declare function deserializeAws_json1_1ListWorkflowsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWorkflowsCommandOutput>;
export declare function deserializeAws_json1_1PutWorkflowRunPropertiesCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutWorkflowRunPropertiesCommandOutput>;
export declare function deserializeAws_json1_1StartJobRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartJobRunCommandOutput>;
export declare function deserializeAws_json1_1StartTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartTriggerCommandOutput>;
export declare function deserializeAws_json1_1StartWorkflowRunCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartWorkflowRunCommandOutput>;
export declare function deserializeAws_json1_1StopTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopTriggerCommandOutput>;
export declare function deserializeAws_json1_1UpdateJobCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateJobCommandOutput>;
export declare function deserializeAws_json1_1UpdateTriggerCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateTriggerCommandOutput>;
export declare function deserializeAws_json1_1UpdateWorkflowCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateWorkflowCommandOutput>;
export declare function deserializeAws_json1_1BatchGetCrawlersCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetCrawlersCommandOutput>;
export declare function deserializeAws_json1_1CreateClassifierCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClassifierCommandOutput>;
export declare function deserializeAws_json1_1CreateCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCrawlerCommandOutput>;
export declare function deserializeAws_json1_1CreateScriptCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateScriptCommandOutput>;
export declare function deserializeAws_json1_1DeleteClassifierCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClassifierCommandOutput>;
export declare function deserializeAws_json1_1DeleteCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCrawlerCommandOutput>;
export declare function deserializeAws_json1_1GetClassifierCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetClassifierCommandOutput>;
export declare function deserializeAws_json1_1GetClassifiersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetClassifiersCommandOutput>;
export declare function deserializeAws_json1_1GetCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCrawlerCommandOutput>;
export declare function deserializeAws_json1_1GetCrawlerMetricsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCrawlerMetricsCommandOutput>;
export declare function deserializeAws_json1_1GetCrawlersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCrawlersCommandOutput>;
export declare function deserializeAws_json1_1GetDataflowGraphCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDataflowGraphCommandOutput>;
export declare function deserializeAws_json1_1GetMappingCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMappingCommandOutput>;
export declare function deserializeAws_json1_1GetPlanCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPlanCommandOutput>;
export declare function deserializeAws_json1_1ListCrawlersCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListCrawlersCommandOutput>;
export declare function deserializeAws_json1_1StartCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartCrawlerCommandOutput>;
export declare function deserializeAws_json1_1StartCrawlerScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartCrawlerScheduleCommandOutput>;
export declare function deserializeAws_json1_1StopCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopCrawlerCommandOutput>;
export declare function deserializeAws_json1_1StopCrawlerScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<StopCrawlerScheduleCommandOutput>;
export declare function deserializeAws_json1_1UpdateClassifierCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateClassifierCommandOutput>;
export declare function deserializeAws_json1_1UpdateCrawlerCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateCrawlerCommandOutput>;
export declare function deserializeAws_json1_1UpdateCrawlerScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateCrawlerScheduleCommandOutput>;
