// smithy-typescript generated code
/**
 * @public
 * @enum
 */
export const ActionType = {
  ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE: "ADD_ORGANIZATIONS_SERVICE_LINKED_ROLE",
  APPROVE_ALL_FEATURES: "APPROVE_ALL_FEATURES",
  ENABLE_ALL_FEATURES: "ENABLE_ALL_FEATURES",
  INVITE_ACCOUNT_TO_ORGANIZATION: "INVITE",
  TRANSFER_RESPONSIBILITY: "TRANSFER_RESPONSIBILITY",
} as const;
/**
 * @public
 */
export type ActionType = (typeof ActionType)[keyof typeof ActionType];

/**
 * @public
 * @enum
 */
export const HandshakePartyType = {
  ACCOUNT: "ACCOUNT",
  EMAIL: "EMAIL",
  ORGANIZATION: "ORGANIZATION",
} as const;
/**
 * @public
 */
export type HandshakePartyType = (typeof HandshakePartyType)[keyof typeof HandshakePartyType];

/**
 * @public
 * @enum
 */
export const HandshakeResourceType = {
  ACCOUNT: "ACCOUNT",
  EMAIL: "EMAIL",
  MANAGEMENT_ACCOUNT: "MANAGEMENT_ACCOUNT",
  MANAGEMENT_EMAIL: "MANAGEMENT_EMAIL",
  MANAGEMENT_NAME: "MANAGEMENT_NAME",
  MASTER_EMAIL: "MASTER_EMAIL",
  MASTER_NAME: "MASTER_NAME",
  NOTES: "NOTES",
  ORGANIZATION: "ORGANIZATION",
  ORGANIZATION_FEATURE_SET: "ORGANIZATION_FEATURE_SET",
  PARENT_HANDSHAKE: "PARENT_HANDSHAKE",
  RESPONSIBILITY_TRANSFER: "RESPONSIBILITY_TRANSFER",
  TRANSFER_START_TIMESTAMP: "TRANSFER_START_TIMESTAMP",
  TRANSFER_TYPE: "TRANSFER_TYPE",
} as const;
/**
 * @public
 */
export type HandshakeResourceType = (typeof HandshakeResourceType)[keyof typeof HandshakeResourceType];

/**
 * @public
 * @enum
 */
export const HandshakeState = {
  ACCEPTED: "ACCEPTED",
  CANCELED: "CANCELED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  OPEN: "OPEN",
  REQUESTED: "REQUESTED",
} as const;
/**
 * @public
 */
export type HandshakeState = (typeof HandshakeState)[keyof typeof HandshakeState];

/**
 * @public
 * @enum
 */
export const AccessDeniedForDependencyExceptionReason = {
  ACCESS_DENIED_DURING_CREATE_SERVICE_LINKED_ROLE: "ACCESS_DENIED_DURING_CREATE_SERVICE_LINKED_ROLE",
} as const;
/**
 * @public
 */
export type AccessDeniedForDependencyExceptionReason =
  (typeof AccessDeniedForDependencyExceptionReason)[keyof typeof AccessDeniedForDependencyExceptionReason];

/**
 * @public
 * @enum
 */
export const ConstraintViolationExceptionReason = {
  ACCOUNT_CANNOT_LEAVE_ORGANIZATION: "ACCOUNT_CANNOT_LEAVE_ORGANIZATION",
  ACCOUNT_CANNOT_LEAVE_WITHOUT_EULA: "ACCOUNT_CANNOT_LEAVE_WITHOUT_EULA",
  ACCOUNT_CANNOT_LEAVE_WITHOUT_PHONE_VERIFICATION: "ACCOUNT_CANNOT_LEAVE_WITHOUT_PHONE_VERIFICATION",
  ACCOUNT_CREATION_NOT_COMPLETE: "ACCOUNT_CREATION_NOT_COMPLETE",
  ACCOUNT_CREATION_RATE_LIMIT_EXCEEDED: "ACCOUNT_CREATION_RATE_LIMIT_EXCEEDED",
  ACCOUNT_NUMBER_LIMIT_EXCEEDED: "ACCOUNT_NUMBER_LIMIT_EXCEEDED",
  ACTIVE_RESPONSIBILITY_TRANSFER_PROCESS: "ACTIVE_RESPONSIBILITY_TRANSFER_PROCESS",
  ALL_FEATURES_MIGRATION_ORGANIZATION_SIZE_LIMIT_EXCEEDED: "ALL_FEATURES_MIGRATION_ORGANIZATION_SIZE_LIMIT_EXCEEDED",
  CANNOT_CLOSE_MANAGEMENT_ACCOUNT: "CANNOT_CLOSE_MANAGEMENT_ACCOUNT",
  CANNOT_REGISTER_MASTER_AS_DELEGATED_ADMINISTRATOR: "CANNOT_REGISTER_MASTER_AS_DELEGATED_ADMINISTRATOR",
  CANNOT_REGISTER_SUSPENDED_ACCOUNT_AS_DELEGATED_ADMINISTRATOR:
    "CANNOT_REGISTER_SUSPENDED_ACCOUNT_AS_DELEGATED_ADMINISTRATOR",
  CANNOT_REMOVE_DELEGATED_ADMINISTRATOR_FROM_ORG: "CANNOT_REMOVE_DELEGATED_ADMINISTRATOR_FROM_ORG",
  CLOSE_ACCOUNT_QUOTA_EXCEEDED: "CLOSE_ACCOUNT_QUOTA_EXCEEDED",
  CLOSE_ACCOUNT_REQUESTS_LIMIT_EXCEEDED: "CLOSE_ACCOUNT_REQUESTS_LIMIT_EXCEEDED",
  CREATE_ORGANIZATION_IN_BILLING_MODE_UNSUPPORTED_REGION: "CREATE_ORGANIZATION_IN_BILLING_MODE_UNSUPPORTED_REGION",
  DELEGATED_ADMINISTRATOR_EXISTS_FOR_THIS_SERVICE: "DELEGATED_ADMINISTRATOR_EXISTS_FOR_THIS_SERVICE",
  EMAIL_VERIFICATION_CODE_EXPIRED: "EMAIL_VERIFICATION_CODE_EXPIRED",
  HANDSHAKE_RATE_LIMIT_EXCEEDED: "HANDSHAKE_RATE_LIMIT_EXCEEDED",
  INVALID_PAYMENT_INSTRUMENT: "INVALID_PAYMENT_INSTRUMENT",
  MASTER_ACCOUNT_ADDRESS_DOES_NOT_MATCH_MARKETPLACE: "MASTER_ACCOUNT_ADDRESS_DOES_NOT_MATCH_MARKETPLACE",
  MASTER_ACCOUNT_MISSING_BUSINESS_LICENSE: "MASTER_ACCOUNT_MISSING_BUSINESS_LICENSE",
  MASTER_ACCOUNT_MISSING_CONTACT_INFO: "MASTER_ACCOUNT_MISSING_CONTACT_INFO",
  MASTER_ACCOUNT_NOT_GOVCLOUD_ENABLED: "MASTER_ACCOUNT_NOT_GOVCLOUD_ENABLED",
  MASTER_ACCOUNT_PAYMENT_INSTRUMENT_REQUIRED: "MASTER_ACCOUNT_PAYMENT_INSTRUMENT_REQUIRED",
  MAX_DELEGATED_ADMINISTRATORS_FOR_SERVICE_LIMIT_EXCEEDED: "MAX_DELEGATED_ADMINISTRATORS_FOR_SERVICE_LIMIT_EXCEEDED",
  MAX_POLICY_TYPE_ATTACHMENT_LIMIT_EXCEEDED: "MAX_POLICY_TYPE_ATTACHMENT_LIMIT_EXCEEDED",
  MAX_TAG_LIMIT_EXCEEDED: "MAX_TAG_LIMIT_EXCEEDED",
  MEMBER_ACCOUNT_PAYMENT_INSTRUMENT_REQUIRED: "MEMBER_ACCOUNT_PAYMENT_INSTRUMENT_REQUIRED",
  MIN_POLICY_TYPE_ATTACHMENT_LIMIT_EXCEEDED: "MIN_POLICY_TYPE_ATTACHMENT_LIMIT_EXCEEDED",
  ORGANIZATION_NOT_IN_ALL_FEATURES_MODE: "ORGANIZATION_NOT_IN_ALL_FEATURES_MODE",
  OU_DEPTH_LIMIT_EXCEEDED: "OU_DEPTH_LIMIT_EXCEEDED",
  OU_NUMBER_LIMIT_EXCEEDED: "OU_NUMBER_LIMIT_EXCEEDED",
  POLICY_CONTENT_LIMIT_EXCEEDED: "POLICY_CONTENT_LIMIT_EXCEEDED",
  POLICY_NUMBER_LIMIT_EXCEEDED: "POLICY_NUMBER_LIMIT_EXCEEDED",
  POLICY_TYPE_ENABLED_FOR_THIS_SERVICE: "POLICY_TYPE_ENABLED_FOR_THIS_SERVICE",
  RESPONSIBILITY_TRANSFER_MAX_INBOUND_QUOTA_VIOLATION: "RESPONSIBILITY_TRANSFER_MAX_INBOUND_QUOTA_VIOLATION",
  RESPONSIBILITY_TRANSFER_MAX_LEVEL_VIOLATION: "RESPONSIBILITY_TRANSFER_MAX_LEVEL_VIOLATION",
  RESPONSIBILITY_TRANSFER_MAX_OUTBOUND_QUOTA_VIOLATION: "RESPONSIBILITY_TRANSFER_MAX_OUTBOUND_QUOTA_VIOLATION",
  RESPONSIBILITY_TRANSFER_MAX_TRANSFERS_QUOTA_VIOLATION: "RESPONSIBILITY_TRANSFER_MAX_TRANSFERS_QUOTA_VIOLATION",
  SERVICE_ACCESS_NOT_ENABLED: "SERVICE_ACCESS_NOT_ENABLED",
  TAG_POLICY_VIOLATION: "TAG_POLICY_VIOLATION",
  TRANSFER_RESPONSIBILITY_SOURCE_DELETION_IN_PROGRESS: "TRANSFER_RESPONSIBILITY_SOURCE_DELETION_IN_PROGRESS",
  TRANSFER_RESPONSIBILITY_TARGET_DELETION_IN_PROGRESS: "TRANSFER_RESPONSIBILITY_TARGET_DELETION_IN_PROGRESS",
  UNSUPPORTED_PRICING: "UNSUPPORTED_PRICING",
  WAIT_PERIOD_ACTIVE: "WAIT_PERIOD_ACTIVE",
} as const;
/**
 * @public
 */
export type ConstraintViolationExceptionReason =
  (typeof ConstraintViolationExceptionReason)[keyof typeof ConstraintViolationExceptionReason];

/**
 * @public
 * @enum
 */
export const HandshakeConstraintViolationExceptionReason = {
  ACCOUNT_NUMBER_LIMIT_EXCEEDED: "ACCOUNT_NUMBER_LIMIT_EXCEEDED",
  ALREADY_IN_AN_ORGANIZATION: "ALREADY_IN_AN_ORGANIZATION",
  HANDSHAKE_RATE_LIMIT_EXCEEDED: "HANDSHAKE_RATE_LIMIT_EXCEEDED",
  INVITE_DISABLED_DURING_ENABLE_ALL_FEATURES: "INVITE_DISABLED_DURING_ENABLE_ALL_FEATURES",
  LEGACY_PERMISSIONS_STILL_IN_USE: "LEGACY_PERMISSIONS_STILL_IN_USE",
  MANAGEMENT_ACCOUNT_EMAIL_NOT_VERIFIED: "MANAGEMENT_ACCOUNT_EMAIL_NOT_VERIFIED",
  ORGANIZATION_ALREADY_HAS_ALL_FEATURES: "ORGANIZATION_ALREADY_HAS_ALL_FEATURES",
  ORGANIZATION_FROM_DIFFERENT_SELLER_OF_RECORD: "ORGANIZATION_FROM_DIFFERENT_SELLER_OF_RECORD",
  ORGANIZATION_IS_ALREADY_PENDING_ALL_FEATURES_MIGRATION: "ORGANIZATION_IS_ALREADY_PENDING_ALL_FEATURES_MIGRATION",
  ORGANIZATION_MEMBERSHIP_CHANGE_RATE_LIMIT_EXCEEDED: "ORGANIZATION_MEMBERSHIP_CHANGE_RATE_LIMIT_EXCEEDED",
  PAYMENT_INSTRUMENT_REQUIRED: "PAYMENT_INSTRUMENT_REQUIRED",
  RESPONSIBILITY_TRANSFER_ALREADY_EXISTS: "RESPONSIBILITY_TRANSFER_ALREADY_EXISTS",
  SOURCE_AND_TARGET_CANNOT_MATCH: "SOURCE_AND_TARGET_CANNOT_MATCH",
  UNUSED_PREPAYMENT_BALANCE: "UNUSED_PREPAYMENT_BALANCE",
} as const;
/**
 * @public
 */
export type HandshakeConstraintViolationExceptionReason =
  (typeof HandshakeConstraintViolationExceptionReason)[keyof typeof HandshakeConstraintViolationExceptionReason];

/**
 * @public
 * @enum
 */
export const InvalidInputExceptionReason = {
  CALLER_REQUIRED_FIELD_MISSING: "CALLER_REQUIRED_FIELD_MISSING",
  DUPLICATE_TAG_KEY: "DUPLICATE_TAG_KEY",
  END_DATE_NOT_END_OF_MONTH: "END_DATE_NOT_END_OF_MONTH",
  END_DATE_TOO_EARLY: "END_DATE_TOO_EARLY",
  IMMUTABLE_POLICY: "IMMUTABLE_POLICY",
  INPUT_REQUIRED: "INPUT_REQUIRED",
  INVALID_EMAIL_ADDRESS_TARGET: "INVALID_EMAIL_ADDRESS_TARGET",
  INVALID_END_DATE: "INVALID_END_DATE",
  INVALID_ENUM: "INVALID_ENUM",
  INVALID_ENUM_POLICY_TYPE: "INVALID_ENUM_POLICY_TYPE",
  INVALID_FULL_NAME_TARGET: "INVALID_FULL_NAME_TARGET",
  INVALID_LIST_MEMBER: "INVALID_LIST_MEMBER",
  INVALID_PAGINATION_TOKEN: "INVALID_NEXT_TOKEN",
  INVALID_PARTY_TYPE_TARGET: "INVALID_PARTY_TYPE_TARGET",
  INVALID_PATTERN: "INVALID_PATTERN",
  INVALID_PATTERN_TARGET_ID: "INVALID_PATTERN_TARGET_ID",
  INVALID_PRINCIPAL: "INVALID_PRINCIPAL",
  INVALID_RESOURCE_POLICY_JSON: "INVALID_RESOURCE_POLICY_JSON",
  INVALID_ROLE_NAME: "INVALID_ROLE_NAME",
  INVALID_START_DATE: "INVALID_START_DATE",
  INVALID_SYNTAX_ORGANIZATION: "INVALID_SYNTAX_ORGANIZATION_ARN",
  INVALID_SYNTAX_POLICY: "INVALID_SYNTAX_POLICY_ID",
  INVALID_SYSTEM_TAGS_PARAMETER: "INVALID_SYSTEM_TAGS_PARAMETER",
  MAX_FILTER_LIMIT_EXCEEDED: "MAX_LIMIT_EXCEEDED_FILTER",
  MAX_LENGTH_EXCEEDED: "MAX_LENGTH_EXCEEDED",
  MAX_VALUE_EXCEEDED: "MAX_VALUE_EXCEEDED",
  MIN_LENGTH_EXCEEDED: "MIN_LENGTH_EXCEEDED",
  MIN_VALUE_EXCEEDED: "MIN_VALUE_EXCEEDED",
  MOVING_ACCOUNT_BETWEEN_DIFFERENT_ROOTS: "MOVING_ACCOUNT_BETWEEN_DIFFERENT_ROOTS",
  NON_DETACHABLE_POLICY: "NON_DETACHABLE_POLICY",
  START_DATE_NOT_BEGINNING_OF_DAY: "START_DATE_NOT_BEGINNING_OF_DAY",
  START_DATE_NOT_BEGINNING_OF_MONTH: "START_DATE_NOT_BEGINNING_OF_MONTH",
  START_DATE_TOO_EARLY: "START_DATE_TOO_EARLY",
  START_DATE_TOO_LATE: "START_DATE_TOO_LATE",
  TARGET_NOT_SUPPORTED: "TARGET_NOT_SUPPORTED",
  UNRECOGNIZED_SERVICE_PRINCIPAL: "UNRECOGNIZED_SERVICE_PRINCIPAL",
  UNSUPPORTED_ACTION_IN_RESOURCE_POLICY: "UNSUPPORTED_ACTION_IN_RESOURCE_POLICY",
  UNSUPPORTED_ACTION_IN_RESPONSIBILITY_TRANSFER: "UNSUPPORTED_ACTION_IN_RESPONSIBILITY_TRANSFER",
  UNSUPPORTED_POLICY_TYPE_IN_RESOURCE_POLICY: "UNSUPPORTED_POLICY_TYPE_IN_RESOURCE_POLICY",
  UNSUPPORTED_RESOURCE_IN_RESOURCE_POLICY: "UNSUPPORTED_RESOURCE_IN_RESOURCE_POLICY",
} as const;
/**
 * @public
 */
export type InvalidInputExceptionReason =
  (typeof InvalidInputExceptionReason)[keyof typeof InvalidInputExceptionReason];

/**
 * @public
 * @enum
 */
export const AccountJoinedMethod = {
  CREATED: "CREATED",
  INVITED: "INVITED",
} as const;
/**
 * @public
 */
export type AccountJoinedMethod = (typeof AccountJoinedMethod)[keyof typeof AccountJoinedMethod];

/**
 * @public
 * @enum
 */
export const AccountState = {
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
  PENDING_ACTIVATION: "PENDING_ACTIVATION",
  PENDING_CLOSURE: "PENDING_CLOSURE",
  SUSPENDED: "SUSPENDED",
} as const;
/**
 * @public
 */
export type AccountState = (typeof AccountState)[keyof typeof AccountState];

/**
 * @public
 * @enum
 */
export const AccountStatus = {
  ACTIVE: "ACTIVE",
  PENDING_CLOSURE: "PENDING_CLOSURE",
  SUSPENDED: "SUSPENDED",
} as const;
/**
 * @public
 */
export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus];

/**
 * @public
 * @enum
 */
export const IAMUserAccessToBilling = {
  ALLOW: "ALLOW",
  DENY: "DENY",
} as const;
/**
 * @public
 */
export type IAMUserAccessToBilling = (typeof IAMUserAccessToBilling)[keyof typeof IAMUserAccessToBilling];

/**
 * @public
 * @enum
 */
export const CreateAccountFailureReason = {
  ACCOUNT_LIMIT_EXCEEDED: "ACCOUNT_LIMIT_EXCEEDED",
  CONCURRENT_ACCOUNT_MODIFICATION: "CONCURRENT_ACCOUNT_MODIFICATION",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  FAILED_BUSINESS_VALIDATION: "FAILED_BUSINESS_VALIDATION",
  GOVCLOUD_ACCOUNT_ALREADY_EXISTS: "GOVCLOUD_ACCOUNT_ALREADY_EXISTS",
  INTERNAL_FAILURE: "INTERNAL_FAILURE",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_IDENTITY_FOR_BUSINESS_VALIDATION: "INVALID_IDENTITY_FOR_BUSINESS_VALIDATION",
  INVALID_PAYMENT_INSTRUMENT: "INVALID_PAYMENT_INSTRUMENT",
  MISSING_BUSINESS_VALIDATION: "MISSING_BUSINESS_VALIDATION",
  MISSING_PAYMENT_INSTRUMENT: "MISSING_PAYMENT_INSTRUMENT",
  PENDING_BUSINESS_VALIDATIONv: "PENDING_BUSINESS_VALIDATION",
  UNKNOWN_BUSINESS_VALIDATION: "UNKNOWN_BUSINESS_VALIDATION",
  UPDATE_EXISTING_RESOURCE_POLICY_WITH_TAGS_NOT_SUPPORTED: "UPDATE_EXISTING_RESOURCE_POLICY_WITH_TAGS_NOT_SUPPORTED",
} as const;
/**
 * @public
 */
export type CreateAccountFailureReason = (typeof CreateAccountFailureReason)[keyof typeof CreateAccountFailureReason];

/**
 * @public
 * @enum
 */
export const CreateAccountState = {
  FAILED: "FAILED",
  IN_PROGRESS: "IN_PROGRESS",
  SUCCEEDED: "SUCCEEDED",
} as const;
/**
 * @public
 */
export type CreateAccountState = (typeof CreateAccountState)[keyof typeof CreateAccountState];

/**
 * @public
 * @enum
 */
export const OrganizationFeatureSet = {
  ALL: "ALL",
  CONSOLIDATED_BILLING: "CONSOLIDATED_BILLING",
} as const;
/**
 * @public
 */
export type OrganizationFeatureSet = (typeof OrganizationFeatureSet)[keyof typeof OrganizationFeatureSet];

/**
 * @public
 * @enum
 */
export const PolicyTypeStatus = {
  ENABLED: "ENABLED",
  PENDING_DISABLE: "PENDING_DISABLE",
  PENDING_ENABLE: "PENDING_ENABLE",
} as const;
/**
 * @public
 */
export type PolicyTypeStatus = (typeof PolicyTypeStatus)[keyof typeof PolicyTypeStatus];

/**
 * @public
 * @enum
 */
export const PolicyType = {
  AISERVICES_OPT_OUT_POLICY: "AISERVICES_OPT_OUT_POLICY",
  BACKUP_POLICY: "BACKUP_POLICY",
  CHATBOT_POLICY: "CHATBOT_POLICY",
  DECLARATIVE_POLICY_EC2: "DECLARATIVE_POLICY_EC2",
  INSPECTOR_POLICY: "INSPECTOR_POLICY",
  RESOURCE_CONTROL_POLICY: "RESOURCE_CONTROL_POLICY",
  SECURITYHUB_POLICY: "SECURITYHUB_POLICY",
  SERVICE_CONTROL_POLICY: "SERVICE_CONTROL_POLICY",
  TAG_POLICY: "TAG_POLICY",
} as const;
/**
 * @public
 */
export type PolicyType = (typeof PolicyType)[keyof typeof PolicyType];

/**
 * @public
 * @enum
 */
export const EffectivePolicyType = {
  AISERVICES_OPT_OUT_POLICY: "AISERVICES_OPT_OUT_POLICY",
  BACKUP_POLICY: "BACKUP_POLICY",
  CHATBOT_POLICY: "CHATBOT_POLICY",
  DECLARATIVE_POLICY_EC2: "DECLARATIVE_POLICY_EC2",
  INSPECTOR_POLICY: "INSPECTOR_POLICY",
  SECURITYHUB_POLICY: "SECURITYHUB_POLICY",
  TAG_POLICY: "TAG_POLICY",
} as const;
/**
 * @public
 */
export type EffectivePolicyType = (typeof EffectivePolicyType)[keyof typeof EffectivePolicyType];

/**
 * @public
 * @enum
 */
export const ResponsibilityTransferStatus = {
  ACCEPTED: "ACCEPTED",
  CANCELED: "CANCELED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  REQUESTED: "REQUESTED",
  WITHDRAWN: "WITHDRAWN",
} as const;
/**
 * @public
 */
export type ResponsibilityTransferStatus =
  (typeof ResponsibilityTransferStatus)[keyof typeof ResponsibilityTransferStatus];

/**
 * @public
 * @enum
 */
export const ResponsibilityTransferType = {
  BILLING: "BILLING",
} as const;
/**
 * @public
 */
export type ResponsibilityTransferType = (typeof ResponsibilityTransferType)[keyof typeof ResponsibilityTransferType];

/**
 * @public
 * @enum
 */
export const ChildType = {
  ACCOUNT: "ACCOUNT",
  ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT",
} as const;
/**
 * @public
 */
export type ChildType = (typeof ChildType)[keyof typeof ChildType];

/**
 * @public
 * @enum
 */
export const ParentType = {
  ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT",
  ROOT: "ROOT",
} as const;
/**
 * @public
 */
export type ParentType = (typeof ParentType)[keyof typeof ParentType];

/**
 * @public
 * @enum
 */
export const TargetType = {
  ACCOUNT: "ACCOUNT",
  ORGANIZATIONAL_UNIT: "ORGANIZATIONAL_UNIT",
  ROOT: "ROOT",
} as const;
/**
 * @public
 */
export type TargetType = (typeof TargetType)[keyof typeof TargetType];
