import { AssociateApprovalRuleTemplateWithRepositoryCommandInput, AssociateApprovalRuleTemplateWithRepositoryCommandOutput } from "../commands/AssociateApprovalRuleTemplateWithRepositoryCommand";
import { BatchAssociateApprovalRuleTemplateWithRepositoriesCommandInput, BatchAssociateApprovalRuleTemplateWithRepositoriesCommandOutput } from "../commands/BatchAssociateApprovalRuleTemplateWithRepositoriesCommand";
import { BatchDescribeMergeConflictsCommandInput, BatchDescribeMergeConflictsCommandOutput } from "../commands/BatchDescribeMergeConflictsCommand";
import { BatchDisassociateApprovalRuleTemplateFromRepositoriesCommandInput, BatchDisassociateApprovalRuleTemplateFromRepositoriesCommandOutput } from "../commands/BatchDisassociateApprovalRuleTemplateFromRepositoriesCommand";
import { BatchGetCommitsCommandInput, BatchGetCommitsCommandOutput } from "../commands/BatchGetCommitsCommand";
import { BatchGetRepositoriesCommandInput, BatchGetRepositoriesCommandOutput } from "../commands/BatchGetRepositoriesCommand";
import { CreateApprovalRuleTemplateCommandInput, CreateApprovalRuleTemplateCommandOutput } from "../commands/CreateApprovalRuleTemplateCommand";
import { CreateBranchCommandInput, CreateBranchCommandOutput } from "../commands/CreateBranchCommand";
import { CreateCommitCommandInput, CreateCommitCommandOutput } from "../commands/CreateCommitCommand";
import { CreatePullRequestApprovalRuleCommandInput, CreatePullRequestApprovalRuleCommandOutput } from "../commands/CreatePullRequestApprovalRuleCommand";
import { CreatePullRequestCommandInput, CreatePullRequestCommandOutput } from "../commands/CreatePullRequestCommand";
import { CreateRepositoryCommandInput, CreateRepositoryCommandOutput } from "../commands/CreateRepositoryCommand";
import { CreateUnreferencedMergeCommitCommandInput, CreateUnreferencedMergeCommitCommandOutput } from "../commands/CreateUnreferencedMergeCommitCommand";
import { DeleteApprovalRuleTemplateCommandInput, DeleteApprovalRuleTemplateCommandOutput } from "../commands/DeleteApprovalRuleTemplateCommand";
import { DeleteBranchCommandInput, DeleteBranchCommandOutput } from "../commands/DeleteBranchCommand";
import { DeleteCommentContentCommandInput, DeleteCommentContentCommandOutput } from "../commands/DeleteCommentContentCommand";
import { DeleteFileCommandInput, DeleteFileCommandOutput } from "../commands/DeleteFileCommand";
import { DeletePullRequestApprovalRuleCommandInput, DeletePullRequestApprovalRuleCommandOutput } from "../commands/DeletePullRequestApprovalRuleCommand";
import { DeleteRepositoryCommandInput, DeleteRepositoryCommandOutput } from "../commands/DeleteRepositoryCommand";
import { DescribeMergeConflictsCommandInput, DescribeMergeConflictsCommandOutput } from "../commands/DescribeMergeConflictsCommand";
import { DescribePullRequestEventsCommandInput, DescribePullRequestEventsCommandOutput } from "../commands/DescribePullRequestEventsCommand";
import { DisassociateApprovalRuleTemplateFromRepositoryCommandInput, DisassociateApprovalRuleTemplateFromRepositoryCommandOutput } from "../commands/DisassociateApprovalRuleTemplateFromRepositoryCommand";
import { EvaluatePullRequestApprovalRulesCommandInput, EvaluatePullRequestApprovalRulesCommandOutput } from "../commands/EvaluatePullRequestApprovalRulesCommand";
import { GetApprovalRuleTemplateCommandInput, GetApprovalRuleTemplateCommandOutput } from "../commands/GetApprovalRuleTemplateCommand";
import { GetBlobCommandInput, GetBlobCommandOutput } from "../commands/GetBlobCommand";
import { GetBranchCommandInput, GetBranchCommandOutput } from "../commands/GetBranchCommand";
import { GetCommentCommandInput, GetCommentCommandOutput } from "../commands/GetCommentCommand";
import { GetCommentsForComparedCommitCommandInput, GetCommentsForComparedCommitCommandOutput } from "../commands/GetCommentsForComparedCommitCommand";
import { GetCommentsForPullRequestCommandInput, GetCommentsForPullRequestCommandOutput } from "../commands/GetCommentsForPullRequestCommand";
import { GetCommitCommandInput, GetCommitCommandOutput } from "../commands/GetCommitCommand";
import { GetDifferencesCommandInput, GetDifferencesCommandOutput } from "../commands/GetDifferencesCommand";
import { GetFileCommandInput, GetFileCommandOutput } from "../commands/GetFileCommand";
import { GetFolderCommandInput, GetFolderCommandOutput } from "../commands/GetFolderCommand";
import { GetMergeCommitCommandInput, GetMergeCommitCommandOutput } from "../commands/GetMergeCommitCommand";
import { GetMergeConflictsCommandInput, GetMergeConflictsCommandOutput } from "../commands/GetMergeConflictsCommand";
import { GetMergeOptionsCommandInput, GetMergeOptionsCommandOutput } from "../commands/GetMergeOptionsCommand";
import { GetPullRequestApprovalStatesCommandInput, GetPullRequestApprovalStatesCommandOutput } from "../commands/GetPullRequestApprovalStatesCommand";
import { GetPullRequestCommandInput, GetPullRequestCommandOutput } from "../commands/GetPullRequestCommand";
import { GetPullRequestOverrideStateCommandInput, GetPullRequestOverrideStateCommandOutput } from "../commands/GetPullRequestOverrideStateCommand";
import { GetRepositoryCommandInput, GetRepositoryCommandOutput } from "../commands/GetRepositoryCommand";
import { GetRepositoryTriggersCommandInput, GetRepositoryTriggersCommandOutput } from "../commands/GetRepositoryTriggersCommand";
import { ListApprovalRuleTemplatesCommandInput, ListApprovalRuleTemplatesCommandOutput } from "../commands/ListApprovalRuleTemplatesCommand";
import { ListAssociatedApprovalRuleTemplatesForRepositoryCommandInput, ListAssociatedApprovalRuleTemplatesForRepositoryCommandOutput } from "../commands/ListAssociatedApprovalRuleTemplatesForRepositoryCommand";
import { ListBranchesCommandInput, ListBranchesCommandOutput } from "../commands/ListBranchesCommand";
import { ListPullRequestsCommandInput, ListPullRequestsCommandOutput } from "../commands/ListPullRequestsCommand";
import { ListRepositoriesCommandInput, ListRepositoriesCommandOutput } from "../commands/ListRepositoriesCommand";
import { ListRepositoriesForApprovalRuleTemplateCommandInput, ListRepositoriesForApprovalRuleTemplateCommandOutput } from "../commands/ListRepositoriesForApprovalRuleTemplateCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { MergeBranchesByFastForwardCommandInput, MergeBranchesByFastForwardCommandOutput } from "../commands/MergeBranchesByFastForwardCommand";
import { MergeBranchesBySquashCommandInput, MergeBranchesBySquashCommandOutput } from "../commands/MergeBranchesBySquashCommand";
import { MergeBranchesByThreeWayCommandInput, MergeBranchesByThreeWayCommandOutput } from "../commands/MergeBranchesByThreeWayCommand";
import { MergePullRequestByFastForwardCommandInput, MergePullRequestByFastForwardCommandOutput } from "../commands/MergePullRequestByFastForwardCommand";
import { MergePullRequestBySquashCommandInput, MergePullRequestBySquashCommandOutput } from "../commands/MergePullRequestBySquashCommand";
import { MergePullRequestByThreeWayCommandInput, MergePullRequestByThreeWayCommandOutput } from "../commands/MergePullRequestByThreeWayCommand";
import { OverridePullRequestApprovalRulesCommandInput, OverridePullRequestApprovalRulesCommandOutput } from "../commands/OverridePullRequestApprovalRulesCommand";
import { PostCommentForComparedCommitCommandInput, PostCommentForComparedCommitCommandOutput } from "../commands/PostCommentForComparedCommitCommand";
import { PostCommentForPullRequestCommandInput, PostCommentForPullRequestCommandOutput } from "../commands/PostCommentForPullRequestCommand";
import { PostCommentReplyCommandInput, PostCommentReplyCommandOutput } from "../commands/PostCommentReplyCommand";
import { PutFileCommandInput, PutFileCommandOutput } from "../commands/PutFileCommand";
import { PutRepositoryTriggersCommandInput, PutRepositoryTriggersCommandOutput } from "../commands/PutRepositoryTriggersCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { TestRepositoryTriggersCommandInput, TestRepositoryTriggersCommandOutput } from "../commands/TestRepositoryTriggersCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateApprovalRuleTemplateContentCommandInput, UpdateApprovalRuleTemplateContentCommandOutput } from "../commands/UpdateApprovalRuleTemplateContentCommand";
import { UpdateApprovalRuleTemplateDescriptionCommandInput, UpdateApprovalRuleTemplateDescriptionCommandOutput } from "../commands/UpdateApprovalRuleTemplateDescriptionCommand";
import { UpdateApprovalRuleTemplateNameCommandInput, UpdateApprovalRuleTemplateNameCommandOutput } from "../commands/UpdateApprovalRuleTemplateNameCommand";
import { UpdateCommentCommandInput, UpdateCommentCommandOutput } from "../commands/UpdateCommentCommand";
import { UpdateDefaultBranchCommandInput, UpdateDefaultBranchCommandOutput } from "../commands/UpdateDefaultBranchCommand";
import { UpdatePullRequestApprovalRuleContentCommandInput, UpdatePullRequestApprovalRuleContentCommandOutput } from "../commands/UpdatePullRequestApprovalRuleContentCommand";
import { UpdatePullRequestApprovalStateCommandInput, UpdatePullRequestApprovalStateCommandOutput } from "../commands/UpdatePullRequestApprovalStateCommand";
import { UpdatePullRequestDescriptionCommandInput, UpdatePullRequestDescriptionCommandOutput } from "../commands/UpdatePullRequestDescriptionCommand";
import { UpdatePullRequestStatusCommandInput, UpdatePullRequestStatusCommandOutput } from "../commands/UpdatePullRequestStatusCommand";
import { UpdatePullRequestTitleCommandInput, UpdatePullRequestTitleCommandOutput } from "../commands/UpdatePullRequestTitleCommand";
import { UpdateRepositoryDescriptionCommandInput, UpdateRepositoryDescriptionCommandOutput } from "../commands/UpdateRepositoryDescriptionCommand";
import { UpdateRepositoryNameCommandInput, UpdateRepositoryNameCommandOutput } from "../commands/UpdateRepositoryNameCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AssociateApprovalRuleTemplateWithRepositoryCommand(input: AssociateApprovalRuleTemplateWithRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchAssociateApprovalRuleTemplateWithRepositoriesCommand(input: BatchAssociateApprovalRuleTemplateWithRepositoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDescribeMergeConflictsCommand(input: BatchDescribeMergeConflictsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchDisassociateApprovalRuleTemplateFromRepositoriesCommand(input: BatchDisassociateApprovalRuleTemplateFromRepositoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetCommitsCommand(input: BatchGetCommitsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1BatchGetRepositoriesCommand(input: BatchGetRepositoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateApprovalRuleTemplateCommand(input: CreateApprovalRuleTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateBranchCommand(input: CreateBranchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateCommitCommand(input: CreateCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePullRequestCommand(input: CreatePullRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePullRequestApprovalRuleCommand(input: CreatePullRequestApprovalRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRepositoryCommand(input: CreateRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateUnreferencedMergeCommitCommand(input: CreateUnreferencedMergeCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteApprovalRuleTemplateCommand(input: DeleteApprovalRuleTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBranchCommand(input: DeleteBranchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteCommentContentCommand(input: DeleteCommentContentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteFileCommand(input: DeleteFileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePullRequestApprovalRuleCommand(input: DeletePullRequestApprovalRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRepositoryCommand(input: DeleteRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMergeConflictsCommand(input: DescribeMergeConflictsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribePullRequestEventsCommand(input: DescribePullRequestEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateApprovalRuleTemplateFromRepositoryCommand(input: DisassociateApprovalRuleTemplateFromRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1EvaluatePullRequestApprovalRulesCommand(input: EvaluatePullRequestApprovalRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetApprovalRuleTemplateCommand(input: GetApprovalRuleTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetBlobCommand(input: GetBlobCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetBranchCommand(input: GetBranchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCommentCommand(input: GetCommentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCommentsForComparedCommitCommand(input: GetCommentsForComparedCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCommentsForPullRequestCommand(input: GetCommentsForPullRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetCommitCommand(input: GetCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetDifferencesCommand(input: GetDifferencesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetFileCommand(input: GetFileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetFolderCommand(input: GetFolderCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMergeCommitCommand(input: GetMergeCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMergeConflictsCommand(input: GetMergeConflictsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetMergeOptionsCommand(input: GetMergeOptionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPullRequestCommand(input: GetPullRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPullRequestApprovalStatesCommand(input: GetPullRequestApprovalStatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPullRequestOverrideStateCommand(input: GetPullRequestOverrideStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRepositoryCommand(input: GetRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRepositoryTriggersCommand(input: GetRepositoryTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListApprovalRuleTemplatesCommand(input: ListApprovalRuleTemplatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListAssociatedApprovalRuleTemplatesForRepositoryCommand(input: ListAssociatedApprovalRuleTemplatesForRepositoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListBranchesCommand(input: ListBranchesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListPullRequestsCommand(input: ListPullRequestsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRepositoriesCommand(input: ListRepositoriesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRepositoriesForApprovalRuleTemplateCommand(input: ListRepositoriesForApprovalRuleTemplateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergeBranchesByFastForwardCommand(input: MergeBranchesByFastForwardCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergeBranchesBySquashCommand(input: MergeBranchesBySquashCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergeBranchesByThreeWayCommand(input: MergeBranchesByThreeWayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergePullRequestByFastForwardCommand(input: MergePullRequestByFastForwardCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergePullRequestBySquashCommand(input: MergePullRequestBySquashCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1MergePullRequestByThreeWayCommand(input: MergePullRequestByThreeWayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1OverridePullRequestApprovalRulesCommand(input: OverridePullRequestApprovalRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PostCommentForComparedCommitCommand(input: PostCommentForComparedCommitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PostCommentForPullRequestCommand(input: PostCommentForPullRequestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PostCommentReplyCommand(input: PostCommentReplyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutFileCommand(input: PutFileCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutRepositoryTriggersCommand(input: PutRepositoryTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TestRepositoryTriggersCommand(input: TestRepositoryTriggersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateApprovalRuleTemplateContentCommand(input: UpdateApprovalRuleTemplateContentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateApprovalRuleTemplateDescriptionCommand(input: UpdateApprovalRuleTemplateDescriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateApprovalRuleTemplateNameCommand(input: UpdateApprovalRuleTemplateNameCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateCommentCommand(input: UpdateCommentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDefaultBranchCommand(input: UpdateDefaultBranchCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePullRequestApprovalRuleContentCommand(input: UpdatePullRequestApprovalRuleContentCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePullRequestApprovalStateCommand(input: UpdatePullRequestApprovalStateCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePullRequestDescriptionCommand(input: UpdatePullRequestDescriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePullRequestStatusCommand(input: UpdatePullRequestStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdatePullRequestTitleCommand(input: UpdatePullRequestTitleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRepositoryDescriptionCommand(input: UpdateRepositoryDescriptionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRepositoryNameCommand(input: UpdateRepositoryNameCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AssociateApprovalRuleTemplateWithRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateApprovalRuleTemplateWithRepositoryCommandOutput>;
export declare function deserializeAws_json1_1BatchAssociateApprovalRuleTemplateWithRepositoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchAssociateApprovalRuleTemplateWithRepositoriesCommandOutput>;
export declare function deserializeAws_json1_1BatchDescribeMergeConflictsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDescribeMergeConflictsCommandOutput>;
export declare function deserializeAws_json1_1BatchDisassociateApprovalRuleTemplateFromRepositoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchDisassociateApprovalRuleTemplateFromRepositoriesCommandOutput>;
export declare function deserializeAws_json1_1BatchGetCommitsCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetCommitsCommandOutput>;
export declare function deserializeAws_json1_1BatchGetRepositoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchGetRepositoriesCommandOutput>;
export declare function deserializeAws_json1_1CreateApprovalRuleTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateApprovalRuleTemplateCommandOutput>;
export declare function deserializeAws_json1_1CreateBranchCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBranchCommandOutput>;
export declare function deserializeAws_json1_1CreateCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCommitCommandOutput>;
export declare function deserializeAws_json1_1CreatePullRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePullRequestCommandOutput>;
export declare function deserializeAws_json1_1CreatePullRequestApprovalRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePullRequestApprovalRuleCommandOutput>;
export declare function deserializeAws_json1_1CreateRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRepositoryCommandOutput>;
export declare function deserializeAws_json1_1CreateUnreferencedMergeCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateUnreferencedMergeCommitCommandOutput>;
export declare function deserializeAws_json1_1DeleteApprovalRuleTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteApprovalRuleTemplateCommandOutput>;
export declare function deserializeAws_json1_1DeleteBranchCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBranchCommandOutput>;
export declare function deserializeAws_json1_1DeleteCommentContentCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCommentContentCommandOutput>;
export declare function deserializeAws_json1_1DeleteFileCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFileCommandOutput>;
export declare function deserializeAws_json1_1DeletePullRequestApprovalRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePullRequestApprovalRuleCommandOutput>;
export declare function deserializeAws_json1_1DeleteRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRepositoryCommandOutput>;
export declare function deserializeAws_json1_1DescribeMergeConflictsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMergeConflictsCommandOutput>;
export declare function deserializeAws_json1_1DescribePullRequestEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribePullRequestEventsCommandOutput>;
export declare function deserializeAws_json1_1DisassociateApprovalRuleTemplateFromRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateApprovalRuleTemplateFromRepositoryCommandOutput>;
export declare function deserializeAws_json1_1EvaluatePullRequestApprovalRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<EvaluatePullRequestApprovalRulesCommandOutput>;
export declare function deserializeAws_json1_1GetApprovalRuleTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetApprovalRuleTemplateCommandOutput>;
export declare function deserializeAws_json1_1GetBlobCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetBlobCommandOutput>;
export declare function deserializeAws_json1_1GetBranchCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetBranchCommandOutput>;
export declare function deserializeAws_json1_1GetCommentCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCommentCommandOutput>;
export declare function deserializeAws_json1_1GetCommentsForComparedCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCommentsForComparedCommitCommandOutput>;
export declare function deserializeAws_json1_1GetCommentsForPullRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCommentsForPullRequestCommandOutput>;
export declare function deserializeAws_json1_1GetCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetCommitCommandOutput>;
export declare function deserializeAws_json1_1GetDifferencesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetDifferencesCommandOutput>;
export declare function deserializeAws_json1_1GetFileCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFileCommandOutput>;
export declare function deserializeAws_json1_1GetFolderCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetFolderCommandOutput>;
export declare function deserializeAws_json1_1GetMergeCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMergeCommitCommandOutput>;
export declare function deserializeAws_json1_1GetMergeConflictsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMergeConflictsCommandOutput>;
export declare function deserializeAws_json1_1GetMergeOptionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetMergeOptionsCommandOutput>;
export declare function deserializeAws_json1_1GetPullRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPullRequestCommandOutput>;
export declare function deserializeAws_json1_1GetPullRequestApprovalStatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPullRequestApprovalStatesCommandOutput>;
export declare function deserializeAws_json1_1GetPullRequestOverrideStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPullRequestOverrideStateCommandOutput>;
export declare function deserializeAws_json1_1GetRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRepositoryCommandOutput>;
export declare function deserializeAws_json1_1GetRepositoryTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRepositoryTriggersCommandOutput>;
export declare function deserializeAws_json1_1ListApprovalRuleTemplatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListApprovalRuleTemplatesCommandOutput>;
export declare function deserializeAws_json1_1ListAssociatedApprovalRuleTemplatesForRepositoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAssociatedApprovalRuleTemplatesForRepositoryCommandOutput>;
export declare function deserializeAws_json1_1ListBranchesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListBranchesCommandOutput>;
export declare function deserializeAws_json1_1ListPullRequestsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListPullRequestsCommandOutput>;
export declare function deserializeAws_json1_1ListRepositoriesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRepositoriesCommandOutput>;
export declare function deserializeAws_json1_1ListRepositoriesForApprovalRuleTemplateCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRepositoriesForApprovalRuleTemplateCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1MergeBranchesByFastForwardCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergeBranchesByFastForwardCommandOutput>;
export declare function deserializeAws_json1_1MergeBranchesBySquashCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergeBranchesBySquashCommandOutput>;
export declare function deserializeAws_json1_1MergeBranchesByThreeWayCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergeBranchesByThreeWayCommandOutput>;
export declare function deserializeAws_json1_1MergePullRequestByFastForwardCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergePullRequestByFastForwardCommandOutput>;
export declare function deserializeAws_json1_1MergePullRequestBySquashCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergePullRequestBySquashCommandOutput>;
export declare function deserializeAws_json1_1MergePullRequestByThreeWayCommand(output: __HttpResponse, context: __SerdeContext): Promise<MergePullRequestByThreeWayCommandOutput>;
export declare function deserializeAws_json1_1OverridePullRequestApprovalRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<OverridePullRequestApprovalRulesCommandOutput>;
export declare function deserializeAws_json1_1PostCommentForComparedCommitCommand(output: __HttpResponse, context: __SerdeContext): Promise<PostCommentForComparedCommitCommandOutput>;
export declare function deserializeAws_json1_1PostCommentForPullRequestCommand(output: __HttpResponse, context: __SerdeContext): Promise<PostCommentForPullRequestCommandOutput>;
export declare function deserializeAws_json1_1PostCommentReplyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PostCommentReplyCommandOutput>;
export declare function deserializeAws_json1_1PutFileCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutFileCommandOutput>;
export declare function deserializeAws_json1_1PutRepositoryTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutRepositoryTriggersCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1TestRepositoryTriggersCommand(output: __HttpResponse, context: __SerdeContext): Promise<TestRepositoryTriggersCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateApprovalRuleTemplateContentCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApprovalRuleTemplateContentCommandOutput>;
export declare function deserializeAws_json1_1UpdateApprovalRuleTemplateDescriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApprovalRuleTemplateDescriptionCommandOutput>;
export declare function deserializeAws_json1_1UpdateApprovalRuleTemplateNameCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateApprovalRuleTemplateNameCommandOutput>;
export declare function deserializeAws_json1_1UpdateCommentCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateCommentCommandOutput>;
export declare function deserializeAws_json1_1UpdateDefaultBranchCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDefaultBranchCommandOutput>;
export declare function deserializeAws_json1_1UpdatePullRequestApprovalRuleContentCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePullRequestApprovalRuleContentCommandOutput>;
export declare function deserializeAws_json1_1UpdatePullRequestApprovalStateCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePullRequestApprovalStateCommandOutput>;
export declare function deserializeAws_json1_1UpdatePullRequestDescriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePullRequestDescriptionCommandOutput>;
export declare function deserializeAws_json1_1UpdatePullRequestStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePullRequestStatusCommandOutput>;
export declare function deserializeAws_json1_1UpdatePullRequestTitleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdatePullRequestTitleCommandOutput>;
export declare function deserializeAws_json1_1UpdateRepositoryDescriptionCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRepositoryDescriptionCommandOutput>;
export declare function deserializeAws_json1_1UpdateRepositoryNameCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRepositoryNameCommandOutput>;
