import { CreateByteMatchSetCommandInput, CreateByteMatchSetCommandOutput } from "../commands/CreateByteMatchSetCommand";
import { CreateGeoMatchSetCommandInput, CreateGeoMatchSetCommandOutput } from "../commands/CreateGeoMatchSetCommand";
import { CreateIPSetCommandInput, CreateIPSetCommandOutput } from "../commands/CreateIPSetCommand";
import { CreateRateBasedRuleCommandInput, CreateRateBasedRuleCommandOutput } from "../commands/CreateRateBasedRuleCommand";
import { CreateRegexMatchSetCommandInput, CreateRegexMatchSetCommandOutput } from "../commands/CreateRegexMatchSetCommand";
import { CreateRegexPatternSetCommandInput, CreateRegexPatternSetCommandOutput } from "../commands/CreateRegexPatternSetCommand";
import { CreateRuleCommandInput, CreateRuleCommandOutput } from "../commands/CreateRuleCommand";
import { CreateRuleGroupCommandInput, CreateRuleGroupCommandOutput } from "../commands/CreateRuleGroupCommand";
import { CreateSizeConstraintSetCommandInput, CreateSizeConstraintSetCommandOutput } from "../commands/CreateSizeConstraintSetCommand";
import { CreateSqlInjectionMatchSetCommandInput, CreateSqlInjectionMatchSetCommandOutput } from "../commands/CreateSqlInjectionMatchSetCommand";
import { CreateWebACLCommandInput, CreateWebACLCommandOutput } from "../commands/CreateWebACLCommand";
import { CreateXssMatchSetCommandInput, CreateXssMatchSetCommandOutput } from "../commands/CreateXssMatchSetCommand";
import { DeleteByteMatchSetCommandInput, DeleteByteMatchSetCommandOutput } from "../commands/DeleteByteMatchSetCommand";
import { DeleteGeoMatchSetCommandInput, DeleteGeoMatchSetCommandOutput } from "../commands/DeleteGeoMatchSetCommand";
import { DeleteIPSetCommandInput, DeleteIPSetCommandOutput } from "../commands/DeleteIPSetCommand";
import { DeleteLoggingConfigurationCommandInput, DeleteLoggingConfigurationCommandOutput } from "../commands/DeleteLoggingConfigurationCommand";
import { DeletePermissionPolicyCommandInput, DeletePermissionPolicyCommandOutput } from "../commands/DeletePermissionPolicyCommand";
import { DeleteRateBasedRuleCommandInput, DeleteRateBasedRuleCommandOutput } from "../commands/DeleteRateBasedRuleCommand";
import { DeleteRegexMatchSetCommandInput, DeleteRegexMatchSetCommandOutput } from "../commands/DeleteRegexMatchSetCommand";
import { DeleteRegexPatternSetCommandInput, DeleteRegexPatternSetCommandOutput } from "../commands/DeleteRegexPatternSetCommand";
import { DeleteRuleCommandInput, DeleteRuleCommandOutput } from "../commands/DeleteRuleCommand";
import { DeleteRuleGroupCommandInput, DeleteRuleGroupCommandOutput } from "../commands/DeleteRuleGroupCommand";
import { DeleteSizeConstraintSetCommandInput, DeleteSizeConstraintSetCommandOutput } from "../commands/DeleteSizeConstraintSetCommand";
import { DeleteSqlInjectionMatchSetCommandInput, DeleteSqlInjectionMatchSetCommandOutput } from "../commands/DeleteSqlInjectionMatchSetCommand";
import { DeleteWebACLCommandInput, DeleteWebACLCommandOutput } from "../commands/DeleteWebACLCommand";
import { DeleteXssMatchSetCommandInput, DeleteXssMatchSetCommandOutput } from "../commands/DeleteXssMatchSetCommand";
import { GetByteMatchSetCommandInput, GetByteMatchSetCommandOutput } from "../commands/GetByteMatchSetCommand";
import { GetChangeTokenCommandInput, GetChangeTokenCommandOutput } from "../commands/GetChangeTokenCommand";
import { GetChangeTokenStatusCommandInput, GetChangeTokenStatusCommandOutput } from "../commands/GetChangeTokenStatusCommand";
import { GetGeoMatchSetCommandInput, GetGeoMatchSetCommandOutput } from "../commands/GetGeoMatchSetCommand";
import { GetIPSetCommandInput, GetIPSetCommandOutput } from "../commands/GetIPSetCommand";
import { GetLoggingConfigurationCommandInput, GetLoggingConfigurationCommandOutput } from "../commands/GetLoggingConfigurationCommand";
import { GetPermissionPolicyCommandInput, GetPermissionPolicyCommandOutput } from "../commands/GetPermissionPolicyCommand";
import { GetRateBasedRuleCommandInput, GetRateBasedRuleCommandOutput } from "../commands/GetRateBasedRuleCommand";
import { GetRateBasedRuleManagedKeysCommandInput, GetRateBasedRuleManagedKeysCommandOutput } from "../commands/GetRateBasedRuleManagedKeysCommand";
import { GetRegexMatchSetCommandInput, GetRegexMatchSetCommandOutput } from "../commands/GetRegexMatchSetCommand";
import { GetRegexPatternSetCommandInput, GetRegexPatternSetCommandOutput } from "../commands/GetRegexPatternSetCommand";
import { GetRuleCommandInput, GetRuleCommandOutput } from "../commands/GetRuleCommand";
import { GetRuleGroupCommandInput, GetRuleGroupCommandOutput } from "../commands/GetRuleGroupCommand";
import { GetSampledRequestsCommandInput, GetSampledRequestsCommandOutput } from "../commands/GetSampledRequestsCommand";
import { GetSizeConstraintSetCommandInput, GetSizeConstraintSetCommandOutput } from "../commands/GetSizeConstraintSetCommand";
import { GetSqlInjectionMatchSetCommandInput, GetSqlInjectionMatchSetCommandOutput } from "../commands/GetSqlInjectionMatchSetCommand";
import { GetWebACLCommandInput, GetWebACLCommandOutput } from "../commands/GetWebACLCommand";
import { GetXssMatchSetCommandInput, GetXssMatchSetCommandOutput } from "../commands/GetXssMatchSetCommand";
import { ListActivatedRulesInRuleGroupCommandInput, ListActivatedRulesInRuleGroupCommandOutput } from "../commands/ListActivatedRulesInRuleGroupCommand";
import { ListByteMatchSetsCommandInput, ListByteMatchSetsCommandOutput } from "../commands/ListByteMatchSetsCommand";
import { ListGeoMatchSetsCommandInput, ListGeoMatchSetsCommandOutput } from "../commands/ListGeoMatchSetsCommand";
import { ListIPSetsCommandInput, ListIPSetsCommandOutput } from "../commands/ListIPSetsCommand";
import { ListLoggingConfigurationsCommandInput, ListLoggingConfigurationsCommandOutput } from "../commands/ListLoggingConfigurationsCommand";
import { ListRateBasedRulesCommandInput, ListRateBasedRulesCommandOutput } from "../commands/ListRateBasedRulesCommand";
import { ListRegexMatchSetsCommandInput, ListRegexMatchSetsCommandOutput } from "../commands/ListRegexMatchSetsCommand";
import { ListRegexPatternSetsCommandInput, ListRegexPatternSetsCommandOutput } from "../commands/ListRegexPatternSetsCommand";
import { ListRuleGroupsCommandInput, ListRuleGroupsCommandOutput } from "../commands/ListRuleGroupsCommand";
import { ListRulesCommandInput, ListRulesCommandOutput } from "../commands/ListRulesCommand";
import { ListSizeConstraintSetsCommandInput, ListSizeConstraintSetsCommandOutput } from "../commands/ListSizeConstraintSetsCommand";
import { ListSqlInjectionMatchSetsCommandInput, ListSqlInjectionMatchSetsCommandOutput } from "../commands/ListSqlInjectionMatchSetsCommand";
import { ListSubscribedRuleGroupsCommandInput, ListSubscribedRuleGroupsCommandOutput } from "../commands/ListSubscribedRuleGroupsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListWebACLsCommandInput, ListWebACLsCommandOutput } from "../commands/ListWebACLsCommand";
import { ListXssMatchSetsCommandInput, ListXssMatchSetsCommandOutput } from "../commands/ListXssMatchSetsCommand";
import { PutLoggingConfigurationCommandInput, PutLoggingConfigurationCommandOutput } from "../commands/PutLoggingConfigurationCommand";
import { PutPermissionPolicyCommandInput, PutPermissionPolicyCommandOutput } from "../commands/PutPermissionPolicyCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateByteMatchSetCommandInput, UpdateByteMatchSetCommandOutput } from "../commands/UpdateByteMatchSetCommand";
import { UpdateGeoMatchSetCommandInput, UpdateGeoMatchSetCommandOutput } from "../commands/UpdateGeoMatchSetCommand";
import { UpdateIPSetCommandInput, UpdateIPSetCommandOutput } from "../commands/UpdateIPSetCommand";
import { UpdateRateBasedRuleCommandInput, UpdateRateBasedRuleCommandOutput } from "../commands/UpdateRateBasedRuleCommand";
import { UpdateRegexMatchSetCommandInput, UpdateRegexMatchSetCommandOutput } from "../commands/UpdateRegexMatchSetCommand";
import { UpdateRegexPatternSetCommandInput, UpdateRegexPatternSetCommandOutput } from "../commands/UpdateRegexPatternSetCommand";
import { UpdateRuleCommandInput, UpdateRuleCommandOutput } from "../commands/UpdateRuleCommand";
import { UpdateRuleGroupCommandInput, UpdateRuleGroupCommandOutput } from "../commands/UpdateRuleGroupCommand";
import { UpdateSizeConstraintSetCommandInput, UpdateSizeConstraintSetCommandOutput } from "../commands/UpdateSizeConstraintSetCommand";
import { UpdateSqlInjectionMatchSetCommandInput, UpdateSqlInjectionMatchSetCommandOutput } from "../commands/UpdateSqlInjectionMatchSetCommand";
import { UpdateWebACLCommandInput, UpdateWebACLCommandOutput } from "../commands/UpdateWebACLCommand";
import { UpdateXssMatchSetCommandInput, UpdateXssMatchSetCommandOutput } from "../commands/UpdateXssMatchSetCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateByteMatchSetCommand(input: CreateByteMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateGeoMatchSetCommand(input: CreateGeoMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateIPSetCommand(input: CreateIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRateBasedRuleCommand(input: CreateRateBasedRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRegexMatchSetCommand(input: CreateRegexMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRegexPatternSetCommand(input: CreateRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRuleCommand(input: CreateRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateRuleGroupCommand(input: CreateRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSizeConstraintSetCommand(input: CreateSizeConstraintSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSqlInjectionMatchSetCommand(input: CreateSqlInjectionMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateWebACLCommand(input: CreateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateXssMatchSetCommand(input: CreateXssMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteByteMatchSetCommand(input: DeleteByteMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteGeoMatchSetCommand(input: DeleteGeoMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteIPSetCommand(input: DeleteIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLoggingConfigurationCommand(input: DeleteLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeletePermissionPolicyCommand(input: DeletePermissionPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRateBasedRuleCommand(input: DeleteRateBasedRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRegexMatchSetCommand(input: DeleteRegexMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRegexPatternSetCommand(input: DeleteRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRuleCommand(input: DeleteRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteRuleGroupCommand(input: DeleteRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSizeConstraintSetCommand(input: DeleteSizeConstraintSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSqlInjectionMatchSetCommand(input: DeleteSqlInjectionMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteWebACLCommand(input: DeleteWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteXssMatchSetCommand(input: DeleteXssMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetByteMatchSetCommand(input: GetByteMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetChangeTokenCommand(input: GetChangeTokenCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetChangeTokenStatusCommand(input: GetChangeTokenStatusCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetGeoMatchSetCommand(input: GetGeoMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetIPSetCommand(input: GetIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetLoggingConfigurationCommand(input: GetLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetPermissionPolicyCommand(input: GetPermissionPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRateBasedRuleCommand(input: GetRateBasedRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRateBasedRuleManagedKeysCommand(input: GetRateBasedRuleManagedKeysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRegexMatchSetCommand(input: GetRegexMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRegexPatternSetCommand(input: GetRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRuleCommand(input: GetRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetRuleGroupCommand(input: GetRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSampledRequestsCommand(input: GetSampledRequestsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSizeConstraintSetCommand(input: GetSizeConstraintSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetSqlInjectionMatchSetCommand(input: GetSqlInjectionMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetWebACLCommand(input: GetWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1GetXssMatchSetCommand(input: GetXssMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListActivatedRulesInRuleGroupCommand(input: ListActivatedRulesInRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListByteMatchSetsCommand(input: ListByteMatchSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListGeoMatchSetsCommand(input: ListGeoMatchSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListIPSetsCommand(input: ListIPSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListLoggingConfigurationsCommand(input: ListLoggingConfigurationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRateBasedRulesCommand(input: ListRateBasedRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRegexMatchSetsCommand(input: ListRegexMatchSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRegexPatternSetsCommand(input: ListRegexPatternSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRuleGroupsCommand(input: ListRuleGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListRulesCommand(input: ListRulesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListSizeConstraintSetsCommand(input: ListSizeConstraintSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListSqlInjectionMatchSetsCommand(input: ListSqlInjectionMatchSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListSubscribedRuleGroupsCommand(input: ListSubscribedRuleGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListWebACLsCommand(input: ListWebACLsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListXssMatchSetsCommand(input: ListXssMatchSetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutLoggingConfigurationCommand(input: PutLoggingConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1PutPermissionPolicyCommand(input: PutPermissionPolicyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateByteMatchSetCommand(input: UpdateByteMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateGeoMatchSetCommand(input: UpdateGeoMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateIPSetCommand(input: UpdateIPSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRateBasedRuleCommand(input: UpdateRateBasedRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRegexMatchSetCommand(input: UpdateRegexMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRegexPatternSetCommand(input: UpdateRegexPatternSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRuleCommand(input: UpdateRuleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateRuleGroupCommand(input: UpdateRuleGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSizeConstraintSetCommand(input: UpdateSizeConstraintSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSqlInjectionMatchSetCommand(input: UpdateSqlInjectionMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateWebACLCommand(input: UpdateWebACLCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateXssMatchSetCommand(input: UpdateXssMatchSetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateByteMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateByteMatchSetCommandOutput>;
export declare function deserializeAws_json1_1CreateGeoMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateGeoMatchSetCommandOutput>;
export declare function deserializeAws_json1_1CreateIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateIPSetCommandOutput>;
export declare function deserializeAws_json1_1CreateRateBasedRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRateBasedRuleCommandOutput>;
export declare function deserializeAws_json1_1CreateRegexMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRegexMatchSetCommandOutput>;
export declare function deserializeAws_json1_1CreateRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1CreateRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRuleCommandOutput>;
export declare function deserializeAws_json1_1CreateRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateSizeConstraintSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSizeConstraintSetCommandOutput>;
export declare function deserializeAws_json1_1CreateSqlInjectionMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSqlInjectionMatchSetCommandOutput>;
export declare function deserializeAws_json1_1CreateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateWebACLCommandOutput>;
export declare function deserializeAws_json1_1CreateXssMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateXssMatchSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteByteMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteByteMatchSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteGeoMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteGeoMatchSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteIPSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1DeletePermissionPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeletePermissionPolicyCommandOutput>;
export declare function deserializeAws_json1_1DeleteRateBasedRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRateBasedRuleCommandOutput>;
export declare function deserializeAws_json1_1DeleteRegexMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRegexMatchSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRuleCommandOutput>;
export declare function deserializeAws_json1_1DeleteRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteSizeConstraintSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSizeConstraintSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteSqlInjectionMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSqlInjectionMatchSetCommandOutput>;
export declare function deserializeAws_json1_1DeleteWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteWebACLCommandOutput>;
export declare function deserializeAws_json1_1DeleteXssMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteXssMatchSetCommandOutput>;
export declare function deserializeAws_json1_1GetByteMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetByteMatchSetCommandOutput>;
export declare function deserializeAws_json1_1GetChangeTokenCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetChangeTokenCommandOutput>;
export declare function deserializeAws_json1_1GetChangeTokenStatusCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetChangeTokenStatusCommandOutput>;
export declare function deserializeAws_json1_1GetGeoMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetGeoMatchSetCommandOutput>;
export declare function deserializeAws_json1_1GetIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetIPSetCommandOutput>;
export declare function deserializeAws_json1_1GetLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1GetPermissionPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetPermissionPolicyCommandOutput>;
export declare function deserializeAws_json1_1GetRateBasedRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRateBasedRuleCommandOutput>;
export declare function deserializeAws_json1_1GetRateBasedRuleManagedKeysCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRateBasedRuleManagedKeysCommandOutput>;
export declare function deserializeAws_json1_1GetRegexMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRegexMatchSetCommandOutput>;
export declare function deserializeAws_json1_1GetRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1GetRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRuleCommandOutput>;
export declare function deserializeAws_json1_1GetRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1GetSampledRequestsCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSampledRequestsCommandOutput>;
export declare function deserializeAws_json1_1GetSizeConstraintSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSizeConstraintSetCommandOutput>;
export declare function deserializeAws_json1_1GetSqlInjectionMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetSqlInjectionMatchSetCommandOutput>;
export declare function deserializeAws_json1_1GetWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWebACLCommandOutput>;
export declare function deserializeAws_json1_1GetXssMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetXssMatchSetCommandOutput>;
export declare function deserializeAws_json1_1ListActivatedRulesInRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListActivatedRulesInRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1ListByteMatchSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListByteMatchSetsCommandOutput>;
export declare function deserializeAws_json1_1ListGeoMatchSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListGeoMatchSetsCommandOutput>;
export declare function deserializeAws_json1_1ListIPSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListIPSetsCommandOutput>;
export declare function deserializeAws_json1_1ListLoggingConfigurationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListLoggingConfigurationsCommandOutput>;
export declare function deserializeAws_json1_1ListRateBasedRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRateBasedRulesCommandOutput>;
export declare function deserializeAws_json1_1ListRegexMatchSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRegexMatchSetsCommandOutput>;
export declare function deserializeAws_json1_1ListRegexPatternSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRegexPatternSetsCommandOutput>;
export declare function deserializeAws_json1_1ListRuleGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRuleGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListRulesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListRulesCommandOutput>;
export declare function deserializeAws_json1_1ListSizeConstraintSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSizeConstraintSetsCommandOutput>;
export declare function deserializeAws_json1_1ListSqlInjectionMatchSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSqlInjectionMatchSetsCommandOutput>;
export declare function deserializeAws_json1_1ListSubscribedRuleGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListSubscribedRuleGroupsCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListWebACLsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWebACLsCommandOutput>;
export declare function deserializeAws_json1_1ListXssMatchSetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListXssMatchSetsCommandOutput>;
export declare function deserializeAws_json1_1PutLoggingConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutLoggingConfigurationCommandOutput>;
export declare function deserializeAws_json1_1PutPermissionPolicyCommand(output: __HttpResponse, context: __SerdeContext): Promise<PutPermissionPolicyCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateByteMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateByteMatchSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateGeoMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateGeoMatchSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateIPSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateIPSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateRateBasedRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRateBasedRuleCommandOutput>;
export declare function deserializeAws_json1_1UpdateRegexMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRegexMatchSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateRegexPatternSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRegexPatternSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateRuleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRuleCommandOutput>;
export declare function deserializeAws_json1_1UpdateRuleGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateRuleGroupCommandOutput>;
export declare function deserializeAws_json1_1UpdateSizeConstraintSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSizeConstraintSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateSqlInjectionMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSqlInjectionMatchSetCommandOutput>;
export declare function deserializeAws_json1_1UpdateWebACLCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateWebACLCommandOutput>;
export declare function deserializeAws_json1_1UpdateXssMatchSetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateXssMatchSetCommandOutput>;
