import { CountClosedWorkflowExecutionsCommandInput, CountClosedWorkflowExecutionsCommandOutput } from "../commands/CountClosedWorkflowExecutionsCommand";
import { CountOpenWorkflowExecutionsCommandInput, CountOpenWorkflowExecutionsCommandOutput } from "../commands/CountOpenWorkflowExecutionsCommand";
import { CountPendingActivityTasksCommandInput, CountPendingActivityTasksCommandOutput } from "../commands/CountPendingActivityTasksCommand";
import { CountPendingDecisionTasksCommandInput, CountPendingDecisionTasksCommandOutput } from "../commands/CountPendingDecisionTasksCommand";
import { DeprecateActivityTypeCommandInput, DeprecateActivityTypeCommandOutput } from "../commands/DeprecateActivityTypeCommand";
import { DeprecateDomainCommandInput, DeprecateDomainCommandOutput } from "../commands/DeprecateDomainCommand";
import { DeprecateWorkflowTypeCommandInput, DeprecateWorkflowTypeCommandOutput } from "../commands/DeprecateWorkflowTypeCommand";
import { DescribeActivityTypeCommandInput, DescribeActivityTypeCommandOutput } from "../commands/DescribeActivityTypeCommand";
import { DescribeDomainCommandInput, DescribeDomainCommandOutput } from "../commands/DescribeDomainCommand";
import { DescribeWorkflowExecutionCommandInput, DescribeWorkflowExecutionCommandOutput } from "../commands/DescribeWorkflowExecutionCommand";
import { DescribeWorkflowTypeCommandInput, DescribeWorkflowTypeCommandOutput } from "../commands/DescribeWorkflowTypeCommand";
import { GetWorkflowExecutionHistoryCommandInput, GetWorkflowExecutionHistoryCommandOutput } from "../commands/GetWorkflowExecutionHistoryCommand";
import { ListActivityTypesCommandInput, ListActivityTypesCommandOutput } from "../commands/ListActivityTypesCommand";
import { ListClosedWorkflowExecutionsCommandInput, ListClosedWorkflowExecutionsCommandOutput } from "../commands/ListClosedWorkflowExecutionsCommand";
import { ListDomainsCommandInput, ListDomainsCommandOutput } from "../commands/ListDomainsCommand";
import { ListOpenWorkflowExecutionsCommandInput, ListOpenWorkflowExecutionsCommandOutput } from "../commands/ListOpenWorkflowExecutionsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListWorkflowTypesCommandInput, ListWorkflowTypesCommandOutput } from "../commands/ListWorkflowTypesCommand";
import { PollForActivityTaskCommandInput, PollForActivityTaskCommandOutput } from "../commands/PollForActivityTaskCommand";
import { PollForDecisionTaskCommandInput, PollForDecisionTaskCommandOutput } from "../commands/PollForDecisionTaskCommand";
import { RecordActivityTaskHeartbeatCommandInput, RecordActivityTaskHeartbeatCommandOutput } from "../commands/RecordActivityTaskHeartbeatCommand";
import { RegisterActivityTypeCommandInput, RegisterActivityTypeCommandOutput } from "../commands/RegisterActivityTypeCommand";
import { RegisterDomainCommandInput, RegisterDomainCommandOutput } from "../commands/RegisterDomainCommand";
import { RegisterWorkflowTypeCommandInput, RegisterWorkflowTypeCommandOutput } from "../commands/RegisterWorkflowTypeCommand";
import { RequestCancelWorkflowExecutionCommandInput, RequestCancelWorkflowExecutionCommandOutput } from "../commands/RequestCancelWorkflowExecutionCommand";
import { RespondActivityTaskCanceledCommandInput, RespondActivityTaskCanceledCommandOutput } from "../commands/RespondActivityTaskCanceledCommand";
import { RespondActivityTaskCompletedCommandInput, RespondActivityTaskCompletedCommandOutput } from "../commands/RespondActivityTaskCompletedCommand";
import { RespondActivityTaskFailedCommandInput, RespondActivityTaskFailedCommandOutput } from "../commands/RespondActivityTaskFailedCommand";
import { RespondDecisionTaskCompletedCommandInput, RespondDecisionTaskCompletedCommandOutput } from "../commands/RespondDecisionTaskCompletedCommand";
import { SignalWorkflowExecutionCommandInput, SignalWorkflowExecutionCommandOutput } from "../commands/SignalWorkflowExecutionCommand";
import { StartWorkflowExecutionCommandInput, StartWorkflowExecutionCommandOutput } from "../commands/StartWorkflowExecutionCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { TerminateWorkflowExecutionCommandInput, TerminateWorkflowExecutionCommandOutput } from "../commands/TerminateWorkflowExecutionCommand";
import { UndeprecateActivityTypeCommandInput, UndeprecateActivityTypeCommandOutput } from "../commands/UndeprecateActivityTypeCommand";
import { UndeprecateDomainCommandInput, UndeprecateDomainCommandOutput } from "../commands/UndeprecateDomainCommand";
import { UndeprecateWorkflowTypeCommandInput, UndeprecateWorkflowTypeCommandOutput } from "../commands/UndeprecateWorkflowTypeCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_0CountClosedWorkflowExecutionsCommand(input: CountClosedWorkflowExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0CountOpenWorkflowExecutionsCommand(input: CountOpenWorkflowExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0CountPendingActivityTasksCommand(input: CountPendingActivityTasksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0CountPendingDecisionTasksCommand(input: CountPendingDecisionTasksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DeprecateActivityTypeCommand(input: DeprecateActivityTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DeprecateDomainCommand(input: DeprecateDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DeprecateWorkflowTypeCommand(input: DeprecateWorkflowTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeActivityTypeCommand(input: DescribeActivityTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeDomainCommand(input: DescribeDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeWorkflowExecutionCommand(input: DescribeWorkflowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0DescribeWorkflowTypeCommand(input: DescribeWorkflowTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0GetWorkflowExecutionHistoryCommand(input: GetWorkflowExecutionHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListActivityTypesCommand(input: ListActivityTypesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListClosedWorkflowExecutionsCommand(input: ListClosedWorkflowExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListDomainsCommand(input: ListDomainsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListOpenWorkflowExecutionsCommand(input: ListOpenWorkflowExecutionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0ListWorkflowTypesCommand(input: ListWorkflowTypesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0PollForActivityTaskCommand(input: PollForActivityTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0PollForDecisionTaskCommand(input: PollForDecisionTaskCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RecordActivityTaskHeartbeatCommand(input: RecordActivityTaskHeartbeatCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RegisterActivityTypeCommand(input: RegisterActivityTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RegisterDomainCommand(input: RegisterDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RegisterWorkflowTypeCommand(input: RegisterWorkflowTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RequestCancelWorkflowExecutionCommand(input: RequestCancelWorkflowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RespondActivityTaskCanceledCommand(input: RespondActivityTaskCanceledCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RespondActivityTaskCompletedCommand(input: RespondActivityTaskCompletedCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RespondActivityTaskFailedCommand(input: RespondActivityTaskFailedCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0RespondDecisionTaskCompletedCommand(input: RespondDecisionTaskCompletedCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0SignalWorkflowExecutionCommand(input: SignalWorkflowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0StartWorkflowExecutionCommand(input: StartWorkflowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0TerminateWorkflowExecutionCommand(input: TerminateWorkflowExecutionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UndeprecateActivityTypeCommand(input: UndeprecateActivityTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UndeprecateDomainCommand(input: UndeprecateDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UndeprecateWorkflowTypeCommand(input: UndeprecateWorkflowTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_0UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_0CountClosedWorkflowExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CountClosedWorkflowExecutionsCommandOutput>;
export declare function deserializeAws_json1_0CountOpenWorkflowExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<CountOpenWorkflowExecutionsCommandOutput>;
export declare function deserializeAws_json1_0CountPendingActivityTasksCommand(output: __HttpResponse, context: __SerdeContext): Promise<CountPendingActivityTasksCommandOutput>;
export declare function deserializeAws_json1_0CountPendingDecisionTasksCommand(output: __HttpResponse, context: __SerdeContext): Promise<CountPendingDecisionTasksCommandOutput>;
export declare function deserializeAws_json1_0DeprecateActivityTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeprecateActivityTypeCommandOutput>;
export declare function deserializeAws_json1_0DeprecateDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeprecateDomainCommandOutput>;
export declare function deserializeAws_json1_0DeprecateWorkflowTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeprecateWorkflowTypeCommandOutput>;
export declare function deserializeAws_json1_0DescribeActivityTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeActivityTypeCommandOutput>;
export declare function deserializeAws_json1_0DescribeDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDomainCommandOutput>;
export declare function deserializeAws_json1_0DescribeWorkflowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkflowExecutionCommandOutput>;
export declare function deserializeAws_json1_0DescribeWorkflowTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkflowTypeCommandOutput>;
export declare function deserializeAws_json1_0GetWorkflowExecutionHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<GetWorkflowExecutionHistoryCommandOutput>;
export declare function deserializeAws_json1_0ListActivityTypesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListActivityTypesCommandOutput>;
export declare function deserializeAws_json1_0ListClosedWorkflowExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListClosedWorkflowExecutionsCommandOutput>;
export declare function deserializeAws_json1_0ListDomainsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListDomainsCommandOutput>;
export declare function deserializeAws_json1_0ListOpenWorkflowExecutionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListOpenWorkflowExecutionsCommandOutput>;
export declare function deserializeAws_json1_0ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_0ListWorkflowTypesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListWorkflowTypesCommandOutput>;
export declare function deserializeAws_json1_0PollForActivityTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<PollForActivityTaskCommandOutput>;
export declare function deserializeAws_json1_0PollForDecisionTaskCommand(output: __HttpResponse, context: __SerdeContext): Promise<PollForDecisionTaskCommandOutput>;
export declare function deserializeAws_json1_0RecordActivityTaskHeartbeatCommand(output: __HttpResponse, context: __SerdeContext): Promise<RecordActivityTaskHeartbeatCommandOutput>;
export declare function deserializeAws_json1_0RegisterActivityTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterActivityTypeCommandOutput>;
export declare function deserializeAws_json1_0RegisterDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterDomainCommandOutput>;
export declare function deserializeAws_json1_0RegisterWorkflowTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<RegisterWorkflowTypeCommandOutput>;
export declare function deserializeAws_json1_0RequestCancelWorkflowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<RequestCancelWorkflowExecutionCommandOutput>;
export declare function deserializeAws_json1_0RespondActivityTaskCanceledCommand(output: __HttpResponse, context: __SerdeContext): Promise<RespondActivityTaskCanceledCommandOutput>;
export declare function deserializeAws_json1_0RespondActivityTaskCompletedCommand(output: __HttpResponse, context: __SerdeContext): Promise<RespondActivityTaskCompletedCommandOutput>;
export declare function deserializeAws_json1_0RespondActivityTaskFailedCommand(output: __HttpResponse, context: __SerdeContext): Promise<RespondActivityTaskFailedCommandOutput>;
export declare function deserializeAws_json1_0RespondDecisionTaskCompletedCommand(output: __HttpResponse, context: __SerdeContext): Promise<RespondDecisionTaskCompletedCommandOutput>;
export declare function deserializeAws_json1_0SignalWorkflowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<SignalWorkflowExecutionCommandOutput>;
export declare function deserializeAws_json1_0StartWorkflowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartWorkflowExecutionCommandOutput>;
export declare function deserializeAws_json1_0TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_0TerminateWorkflowExecutionCommand(output: __HttpResponse, context: __SerdeContext): Promise<TerminateWorkflowExecutionCommandOutput>;
export declare function deserializeAws_json1_0UndeprecateActivityTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UndeprecateActivityTypeCommandOutput>;
export declare function deserializeAws_json1_0UndeprecateDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<UndeprecateDomainCommandOutput>;
export declare function deserializeAws_json1_0UndeprecateWorkflowTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UndeprecateWorkflowTypeCommandOutput>;
export declare function deserializeAws_json1_0UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
