import { CreateClusterCommandInput, CreateClusterCommandOutput } from "../commands/CreateClusterCommand";
import { CreateParameterGroupCommandInput, CreateParameterGroupCommandOutput } from "../commands/CreateParameterGroupCommand";
import { CreateSubnetGroupCommandInput, CreateSubnetGroupCommandOutput } from "../commands/CreateSubnetGroupCommand";
import { DecreaseReplicationFactorCommandInput, DecreaseReplicationFactorCommandOutput } from "../commands/DecreaseReplicationFactorCommand";
import { DeleteClusterCommandInput, DeleteClusterCommandOutput } from "../commands/DeleteClusterCommand";
import { DeleteParameterGroupCommandInput, DeleteParameterGroupCommandOutput } from "../commands/DeleteParameterGroupCommand";
import { DeleteSubnetGroupCommandInput, DeleteSubnetGroupCommandOutput } from "../commands/DeleteSubnetGroupCommand";
import { DescribeClustersCommandInput, DescribeClustersCommandOutput } from "../commands/DescribeClustersCommand";
import { DescribeDefaultParametersCommandInput, DescribeDefaultParametersCommandOutput } from "../commands/DescribeDefaultParametersCommand";
import { DescribeEventsCommandInput, DescribeEventsCommandOutput } from "../commands/DescribeEventsCommand";
import { DescribeParameterGroupsCommandInput, DescribeParameterGroupsCommandOutput } from "../commands/DescribeParameterGroupsCommand";
import { DescribeParametersCommandInput, DescribeParametersCommandOutput } from "../commands/DescribeParametersCommand";
import { DescribeSubnetGroupsCommandInput, DescribeSubnetGroupsCommandOutput } from "../commands/DescribeSubnetGroupsCommand";
import { IncreaseReplicationFactorCommandInput, IncreaseReplicationFactorCommandOutput } from "../commands/IncreaseReplicationFactorCommand";
import { ListTagsCommandInput, ListTagsCommandOutput } from "../commands/ListTagsCommand";
import { RebootNodeCommandInput, RebootNodeCommandOutput } from "../commands/RebootNodeCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateClusterCommandInput, UpdateClusterCommandOutput } from "../commands/UpdateClusterCommand";
import { UpdateParameterGroupCommandInput, UpdateParameterGroupCommandOutput } from "../commands/UpdateParameterGroupCommand";
import { UpdateSubnetGroupCommandInput, UpdateSubnetGroupCommandOutput } from "../commands/UpdateSubnetGroupCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateClusterCommand(input: CreateClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateParameterGroupCommand(input: CreateParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSubnetGroupCommand(input: CreateSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DecreaseReplicationFactorCommand(input: DecreaseReplicationFactorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteClusterCommand(input: DeleteClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteParameterGroupCommand(input: DeleteParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSubnetGroupCommand(input: DeleteSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeClustersCommand(input: DescribeClustersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDefaultParametersCommand(input: DescribeDefaultParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeEventsCommand(input: DescribeEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeParameterGroupsCommand(input: DescribeParameterGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeParametersCommand(input: DescribeParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSubnetGroupsCommand(input: DescribeSubnetGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1IncreaseReplicationFactorCommand(input: IncreaseReplicationFactorCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsCommand(input: ListTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RebootNodeCommand(input: RebootNodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateClusterCommand(input: UpdateClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateParameterGroupCommand(input: UpdateParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSubnetGroupCommand(input: UpdateSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateClusterCommandOutput>;
export declare function deserializeAws_json1_1CreateParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateParameterGroupCommandOutput>;
export declare function deserializeAws_json1_1CreateSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSubnetGroupCommandOutput>;
export declare function deserializeAws_json1_1DecreaseReplicationFactorCommand(output: __HttpResponse, context: __SerdeContext): Promise<DecreaseReplicationFactorCommandOutput>;
export declare function deserializeAws_json1_1DeleteClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteClusterCommandOutput>;
export declare function deserializeAws_json1_1DeleteParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteParameterGroupCommandOutput>;
export declare function deserializeAws_json1_1DeleteSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSubnetGroupCommandOutput>;
export declare function deserializeAws_json1_1DescribeClustersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeClustersCommandOutput>;
export declare function deserializeAws_json1_1DescribeDefaultParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDefaultParametersCommandOutput>;
export declare function deserializeAws_json1_1DescribeEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventsCommandOutput>;
export declare function deserializeAws_json1_1DescribeParameterGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeParameterGroupsCommandOutput>;
export declare function deserializeAws_json1_1DescribeParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeParametersCommandOutput>;
export declare function deserializeAws_json1_1DescribeSubnetGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSubnetGroupsCommandOutput>;
export declare function deserializeAws_json1_1IncreaseReplicationFactorCommand(output: __HttpResponse, context: __SerdeContext): Promise<IncreaseReplicationFactorCommandOutput>;
export declare function deserializeAws_json1_1ListTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsCommandOutput>;
export declare function deserializeAws_json1_1RebootNodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootNodeCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateClusterCommandOutput>;
export declare function deserializeAws_json1_1UpdateParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateParameterGroupCommandOutput>;
export declare function deserializeAws_json1_1UpdateSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSubnetGroupCommandOutput>;
