import { ActivateGatewayCommandInput, ActivateGatewayCommandOutput } from "../commands/ActivateGatewayCommand";
import { AddCacheCommandInput, AddCacheCommandOutput } from "../commands/AddCacheCommand";
import { AddTagsToResourceCommandInput, AddTagsToResourceCommandOutput } from "../commands/AddTagsToResourceCommand";
import { AddUploadBufferCommandInput, AddUploadBufferCommandOutput } from "../commands/AddUploadBufferCommand";
import { AddWorkingStorageCommandInput, AddWorkingStorageCommandOutput } from "../commands/AddWorkingStorageCommand";
import { AssignTapePoolCommandInput, AssignTapePoolCommandOutput } from "../commands/AssignTapePoolCommand";
import { AttachVolumeCommandInput, AttachVolumeCommandOutput } from "../commands/AttachVolumeCommand";
import { CancelArchivalCommandInput, CancelArchivalCommandOutput } from "../commands/CancelArchivalCommand";
import { CancelRetrievalCommandInput, CancelRetrievalCommandOutput } from "../commands/CancelRetrievalCommand";
import { CreateCachediSCSIVolumeCommandInput, CreateCachediSCSIVolumeCommandOutput } from "../commands/CreateCachediSCSIVolumeCommand";
import { CreateNFSFileShareCommandInput, CreateNFSFileShareCommandOutput } from "../commands/CreateNFSFileShareCommand";
import { CreateSMBFileShareCommandInput, CreateSMBFileShareCommandOutput } from "../commands/CreateSMBFileShareCommand";
import { CreateSnapshotCommandInput, CreateSnapshotCommandOutput } from "../commands/CreateSnapshotCommand";
import { CreateSnapshotFromVolumeRecoveryPointCommandInput, CreateSnapshotFromVolumeRecoveryPointCommandOutput } from "../commands/CreateSnapshotFromVolumeRecoveryPointCommand";
import { CreateStorediSCSIVolumeCommandInput, CreateStorediSCSIVolumeCommandOutput } from "../commands/CreateStorediSCSIVolumeCommand";
import { CreateTapeWithBarcodeCommandInput, CreateTapeWithBarcodeCommandOutput } from "../commands/CreateTapeWithBarcodeCommand";
import { CreateTapesCommandInput, CreateTapesCommandOutput } from "../commands/CreateTapesCommand";
import { DeleteBandwidthRateLimitCommandInput, DeleteBandwidthRateLimitCommandOutput } from "../commands/DeleteBandwidthRateLimitCommand";
import { DeleteChapCredentialsCommandInput, DeleteChapCredentialsCommandOutput } from "../commands/DeleteChapCredentialsCommand";
import { DeleteFileShareCommandInput, DeleteFileShareCommandOutput } from "../commands/DeleteFileShareCommand";
import { DeleteGatewayCommandInput, DeleteGatewayCommandOutput } from "../commands/DeleteGatewayCommand";
import { DeleteSnapshotScheduleCommandInput, DeleteSnapshotScheduleCommandOutput } from "../commands/DeleteSnapshotScheduleCommand";
import { DeleteTapeArchiveCommandInput, DeleteTapeArchiveCommandOutput } from "../commands/DeleteTapeArchiveCommand";
import { DeleteTapeCommandInput, DeleteTapeCommandOutput } from "../commands/DeleteTapeCommand";
import { DeleteVolumeCommandInput, DeleteVolumeCommandOutput } from "../commands/DeleteVolumeCommand";
import { DescribeAvailabilityMonitorTestCommandInput, DescribeAvailabilityMonitorTestCommandOutput } from "../commands/DescribeAvailabilityMonitorTestCommand";
import { DescribeBandwidthRateLimitCommandInput, DescribeBandwidthRateLimitCommandOutput } from "../commands/DescribeBandwidthRateLimitCommand";
import { DescribeCacheCommandInput, DescribeCacheCommandOutput } from "../commands/DescribeCacheCommand";
import { DescribeCachediSCSIVolumesCommandInput, DescribeCachediSCSIVolumesCommandOutput } from "../commands/DescribeCachediSCSIVolumesCommand";
import { DescribeChapCredentialsCommandInput, DescribeChapCredentialsCommandOutput } from "../commands/DescribeChapCredentialsCommand";
import { DescribeGatewayInformationCommandInput, DescribeGatewayInformationCommandOutput } from "../commands/DescribeGatewayInformationCommand";
import { DescribeMaintenanceStartTimeCommandInput, DescribeMaintenanceStartTimeCommandOutput } from "../commands/DescribeMaintenanceStartTimeCommand";
import { DescribeNFSFileSharesCommandInput, DescribeNFSFileSharesCommandOutput } from "../commands/DescribeNFSFileSharesCommand";
import { DescribeSMBFileSharesCommandInput, DescribeSMBFileSharesCommandOutput } from "../commands/DescribeSMBFileSharesCommand";
import { DescribeSMBSettingsCommandInput, DescribeSMBSettingsCommandOutput } from "../commands/DescribeSMBSettingsCommand";
import { DescribeSnapshotScheduleCommandInput, DescribeSnapshotScheduleCommandOutput } from "../commands/DescribeSnapshotScheduleCommand";
import { DescribeStorediSCSIVolumesCommandInput, DescribeStorediSCSIVolumesCommandOutput } from "../commands/DescribeStorediSCSIVolumesCommand";
import { DescribeTapeArchivesCommandInput, DescribeTapeArchivesCommandOutput } from "../commands/DescribeTapeArchivesCommand";
import { DescribeTapeRecoveryPointsCommandInput, DescribeTapeRecoveryPointsCommandOutput } from "../commands/DescribeTapeRecoveryPointsCommand";
import { DescribeTapesCommandInput, DescribeTapesCommandOutput } from "../commands/DescribeTapesCommand";
import { DescribeUploadBufferCommandInput, DescribeUploadBufferCommandOutput } from "../commands/DescribeUploadBufferCommand";
import { DescribeVTLDevicesCommandInput, DescribeVTLDevicesCommandOutput } from "../commands/DescribeVTLDevicesCommand";
import { DescribeWorkingStorageCommandInput, DescribeWorkingStorageCommandOutput } from "../commands/DescribeWorkingStorageCommand";
import { DetachVolumeCommandInput, DetachVolumeCommandOutput } from "../commands/DetachVolumeCommand";
import { DisableGatewayCommandInput, DisableGatewayCommandOutput } from "../commands/DisableGatewayCommand";
import { JoinDomainCommandInput, JoinDomainCommandOutput } from "../commands/JoinDomainCommand";
import { ListFileSharesCommandInput, ListFileSharesCommandOutput } from "../commands/ListFileSharesCommand";
import { ListGatewaysCommandInput, ListGatewaysCommandOutput } from "../commands/ListGatewaysCommand";
import { ListLocalDisksCommandInput, ListLocalDisksCommandOutput } from "../commands/ListLocalDisksCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ListTapesCommandInput, ListTapesCommandOutput } from "../commands/ListTapesCommand";
import { ListVolumeInitiatorsCommandInput, ListVolumeInitiatorsCommandOutput } from "../commands/ListVolumeInitiatorsCommand";
import { ListVolumeRecoveryPointsCommandInput, ListVolumeRecoveryPointsCommandOutput } from "../commands/ListVolumeRecoveryPointsCommand";
import { ListVolumesCommandInput, ListVolumesCommandOutput } from "../commands/ListVolumesCommand";
import { NotifyWhenUploadedCommandInput, NotifyWhenUploadedCommandOutput } from "../commands/NotifyWhenUploadedCommand";
import { RefreshCacheCommandInput, RefreshCacheCommandOutput } from "../commands/RefreshCacheCommand";
import { RemoveTagsFromResourceCommandInput, RemoveTagsFromResourceCommandOutput } from "../commands/RemoveTagsFromResourceCommand";
import { ResetCacheCommandInput, ResetCacheCommandOutput } from "../commands/ResetCacheCommand";
import { RetrieveTapeArchiveCommandInput, RetrieveTapeArchiveCommandOutput } from "../commands/RetrieveTapeArchiveCommand";
import { RetrieveTapeRecoveryPointCommandInput, RetrieveTapeRecoveryPointCommandOutput } from "../commands/RetrieveTapeRecoveryPointCommand";
import { SetLocalConsolePasswordCommandInput, SetLocalConsolePasswordCommandOutput } from "../commands/SetLocalConsolePasswordCommand";
import { SetSMBGuestPasswordCommandInput, SetSMBGuestPasswordCommandOutput } from "../commands/SetSMBGuestPasswordCommand";
import { ShutdownGatewayCommandInput, ShutdownGatewayCommandOutput } from "../commands/ShutdownGatewayCommand";
import { StartAvailabilityMonitorTestCommandInput, StartAvailabilityMonitorTestCommandOutput } from "../commands/StartAvailabilityMonitorTestCommand";
import { StartGatewayCommandInput, StartGatewayCommandOutput } from "../commands/StartGatewayCommand";
import { UpdateBandwidthRateLimitCommandInput, UpdateBandwidthRateLimitCommandOutput } from "../commands/UpdateBandwidthRateLimitCommand";
import { UpdateChapCredentialsCommandInput, UpdateChapCredentialsCommandOutput } from "../commands/UpdateChapCredentialsCommand";
import { UpdateGatewayInformationCommandInput, UpdateGatewayInformationCommandOutput } from "../commands/UpdateGatewayInformationCommand";
import { UpdateGatewaySoftwareNowCommandInput, UpdateGatewaySoftwareNowCommandOutput } from "../commands/UpdateGatewaySoftwareNowCommand";
import { UpdateMaintenanceStartTimeCommandInput, UpdateMaintenanceStartTimeCommandOutput } from "../commands/UpdateMaintenanceStartTimeCommand";
import { UpdateNFSFileShareCommandInput, UpdateNFSFileShareCommandOutput } from "../commands/UpdateNFSFileShareCommand";
import { UpdateSMBFileShareCommandInput, UpdateSMBFileShareCommandOutput } from "../commands/UpdateSMBFileShareCommand";
import { UpdateSMBSecurityStrategyCommandInput, UpdateSMBSecurityStrategyCommandOutput } from "../commands/UpdateSMBSecurityStrategyCommand";
import { UpdateSnapshotScheduleCommandInput, UpdateSnapshotScheduleCommandOutput } from "../commands/UpdateSnapshotScheduleCommand";
import { UpdateVTLDeviceTypeCommandInput, UpdateVTLDeviceTypeCommandOutput } from "../commands/UpdateVTLDeviceTypeCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1ActivateGatewayCommand(input: ActivateGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddCacheCommand(input: AddCacheCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddTagsToResourceCommand(input: AddTagsToResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddUploadBufferCommand(input: AddUploadBufferCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AddWorkingStorageCommand(input: AddWorkingStorageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssignTapePoolCommand(input: AssignTapePoolCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AttachVolumeCommand(input: AttachVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelArchivalCommand(input: CancelArchivalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CancelRetrievalCommand(input: CancelRetrievalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateCachediSCSIVolumeCommand(input: CreateCachediSCSIVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateNFSFileShareCommand(input: CreateNFSFileShareCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSMBFileShareCommand(input: CreateSMBFileShareCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSnapshotCommand(input: CreateSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSnapshotFromVolumeRecoveryPointCommand(input: CreateSnapshotFromVolumeRecoveryPointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateStorediSCSIVolumeCommand(input: CreateStorediSCSIVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTapeWithBarcodeCommand(input: CreateTapeWithBarcodeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTapesCommand(input: CreateTapesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBandwidthRateLimitCommand(input: DeleteBandwidthRateLimitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteChapCredentialsCommand(input: DeleteChapCredentialsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteFileShareCommand(input: DeleteFileShareCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteGatewayCommand(input: DeleteGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSnapshotScheduleCommand(input: DeleteSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTapeCommand(input: DeleteTapeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteTapeArchiveCommand(input: DeleteTapeArchiveCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVolumeCommand(input: DeleteVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeAvailabilityMonitorTestCommand(input: DescribeAvailabilityMonitorTestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBandwidthRateLimitCommand(input: DescribeBandwidthRateLimitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCacheCommand(input: DescribeCacheCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeCachediSCSIVolumesCommand(input: DescribeCachediSCSIVolumesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeChapCredentialsCommand(input: DescribeChapCredentialsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeGatewayInformationCommand(input: DescribeGatewayInformationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeMaintenanceStartTimeCommand(input: DescribeMaintenanceStartTimeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeNFSFileSharesCommand(input: DescribeNFSFileSharesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSMBFileSharesCommand(input: DescribeSMBFileSharesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSMBSettingsCommand(input: DescribeSMBSettingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSnapshotScheduleCommand(input: DescribeSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeStorediSCSIVolumesCommand(input: DescribeStorediSCSIVolumesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTapeArchivesCommand(input: DescribeTapeArchivesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTapeRecoveryPointsCommand(input: DescribeTapeRecoveryPointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTapesCommand(input: DescribeTapesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeUploadBufferCommand(input: DescribeUploadBufferCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVTLDevicesCommand(input: DescribeVTLDevicesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeWorkingStorageCommand(input: DescribeWorkingStorageCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DetachVolumeCommand(input: DetachVolumeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisableGatewayCommand(input: DisableGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1JoinDomainCommand(input: JoinDomainCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListFileSharesCommand(input: ListFileSharesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListGatewaysCommand(input: ListGatewaysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListLocalDisksCommand(input: ListLocalDisksCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListTapesCommand(input: ListTapesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVolumeInitiatorsCommand(input: ListVolumeInitiatorsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVolumeRecoveryPointsCommand(input: ListVolumeRecoveryPointsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ListVolumesCommand(input: ListVolumesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1NotifyWhenUploadedCommand(input: NotifyWhenUploadedCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RefreshCacheCommand(input: RefreshCacheCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RemoveTagsFromResourceCommand(input: RemoveTagsFromResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ResetCacheCommand(input: ResetCacheCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RetrieveTapeArchiveCommand(input: RetrieveTapeArchiveCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1RetrieveTapeRecoveryPointCommand(input: RetrieveTapeRecoveryPointCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetLocalConsolePasswordCommand(input: SetLocalConsolePasswordCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1SetSMBGuestPasswordCommand(input: SetSMBGuestPasswordCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ShutdownGatewayCommand(input: ShutdownGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartAvailabilityMonitorTestCommand(input: StartAvailabilityMonitorTestCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1StartGatewayCommand(input: StartGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateBandwidthRateLimitCommand(input: UpdateBandwidthRateLimitCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateChapCredentialsCommand(input: UpdateChapCredentialsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateGatewayInformationCommand(input: UpdateGatewayInformationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateGatewaySoftwareNowCommand(input: UpdateGatewaySoftwareNowCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateMaintenanceStartTimeCommand(input: UpdateMaintenanceStartTimeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateNFSFileShareCommand(input: UpdateNFSFileShareCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSMBFileShareCommand(input: UpdateSMBFileShareCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSMBSecurityStrategyCommand(input: UpdateSMBSecurityStrategyCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSnapshotScheduleCommand(input: UpdateSnapshotScheduleCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVTLDeviceTypeCommand(input: UpdateVTLDeviceTypeCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1ActivateGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<ActivateGatewayCommandOutput>;
export declare function deserializeAws_json1_1AddCacheCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddCacheCommandOutput>;
export declare function deserializeAws_json1_1AddTagsToResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsToResourceCommandOutput>;
export declare function deserializeAws_json1_1AddUploadBufferCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddUploadBufferCommandOutput>;
export declare function deserializeAws_json1_1AddWorkingStorageCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddWorkingStorageCommandOutput>;
export declare function deserializeAws_json1_1AssignTapePoolCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssignTapePoolCommandOutput>;
export declare function deserializeAws_json1_1AttachVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<AttachVolumeCommandOutput>;
export declare function deserializeAws_json1_1CancelArchivalCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelArchivalCommandOutput>;
export declare function deserializeAws_json1_1CancelRetrievalCommand(output: __HttpResponse, context: __SerdeContext): Promise<CancelRetrievalCommandOutput>;
export declare function deserializeAws_json1_1CreateCachediSCSIVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCachediSCSIVolumeCommandOutput>;
export declare function deserializeAws_json1_1CreateNFSFileShareCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateNFSFileShareCommandOutput>;
export declare function deserializeAws_json1_1CreateSMBFileShareCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSMBFileShareCommandOutput>;
export declare function deserializeAws_json1_1CreateSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSnapshotCommandOutput>;
export declare function deserializeAws_json1_1CreateSnapshotFromVolumeRecoveryPointCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSnapshotFromVolumeRecoveryPointCommandOutput>;
export declare function deserializeAws_json1_1CreateStorediSCSIVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateStorediSCSIVolumeCommandOutput>;
export declare function deserializeAws_json1_1CreateTapeWithBarcodeCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTapeWithBarcodeCommandOutput>;
export declare function deserializeAws_json1_1CreateTapesCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTapesCommandOutput>;
export declare function deserializeAws_json1_1DeleteBandwidthRateLimitCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBandwidthRateLimitCommandOutput>;
export declare function deserializeAws_json1_1DeleteChapCredentialsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteChapCredentialsCommandOutput>;
export declare function deserializeAws_json1_1DeleteFileShareCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteFileShareCommandOutput>;
export declare function deserializeAws_json1_1DeleteGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteGatewayCommandOutput>;
export declare function deserializeAws_json1_1DeleteSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSnapshotScheduleCommandOutput>;
export declare function deserializeAws_json1_1DeleteTapeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTapeCommandOutput>;
export declare function deserializeAws_json1_1DeleteTapeArchiveCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteTapeArchiveCommandOutput>;
export declare function deserializeAws_json1_1DeleteVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVolumeCommandOutput>;
export declare function deserializeAws_json1_1DescribeAvailabilityMonitorTestCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeAvailabilityMonitorTestCommandOutput>;
export declare function deserializeAws_json1_1DescribeBandwidthRateLimitCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBandwidthRateLimitCommandOutput>;
export declare function deserializeAws_json1_1DescribeCacheCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheCommandOutput>;
export declare function deserializeAws_json1_1DescribeCachediSCSIVolumesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCachediSCSIVolumesCommandOutput>;
export declare function deserializeAws_json1_1DescribeChapCredentialsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeChapCredentialsCommandOutput>;
export declare function deserializeAws_json1_1DescribeGatewayInformationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeGatewayInformationCommandOutput>;
export declare function deserializeAws_json1_1DescribeMaintenanceStartTimeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeMaintenanceStartTimeCommandOutput>;
export declare function deserializeAws_json1_1DescribeNFSFileSharesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeNFSFileSharesCommandOutput>;
export declare function deserializeAws_json1_1DescribeSMBFileSharesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSMBFileSharesCommandOutput>;
export declare function deserializeAws_json1_1DescribeSMBSettingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSMBSettingsCommandOutput>;
export declare function deserializeAws_json1_1DescribeSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSnapshotScheduleCommandOutput>;
export declare function deserializeAws_json1_1DescribeStorediSCSIVolumesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeStorediSCSIVolumesCommandOutput>;
export declare function deserializeAws_json1_1DescribeTapeArchivesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTapeArchivesCommandOutput>;
export declare function deserializeAws_json1_1DescribeTapeRecoveryPointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTapeRecoveryPointsCommandOutput>;
export declare function deserializeAws_json1_1DescribeTapesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTapesCommandOutput>;
export declare function deserializeAws_json1_1DescribeUploadBufferCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeUploadBufferCommandOutput>;
export declare function deserializeAws_json1_1DescribeVTLDevicesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVTLDevicesCommandOutput>;
export declare function deserializeAws_json1_1DescribeWorkingStorageCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeWorkingStorageCommandOutput>;
export declare function deserializeAws_json1_1DetachVolumeCommand(output: __HttpResponse, context: __SerdeContext): Promise<DetachVolumeCommandOutput>;
export declare function deserializeAws_json1_1DisableGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisableGatewayCommandOutput>;
export declare function deserializeAws_json1_1JoinDomainCommand(output: __HttpResponse, context: __SerdeContext): Promise<JoinDomainCommandOutput>;
export declare function deserializeAws_json1_1ListFileSharesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListFileSharesCommandOutput>;
export declare function deserializeAws_json1_1ListGatewaysCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListGatewaysCommandOutput>;
export declare function deserializeAws_json1_1ListLocalDisksCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListLocalDisksCommandOutput>;
export declare function deserializeAws_json1_1ListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_json1_1ListTapesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTapesCommandOutput>;
export declare function deserializeAws_json1_1ListVolumeInitiatorsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVolumeInitiatorsCommandOutput>;
export declare function deserializeAws_json1_1ListVolumeRecoveryPointsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVolumeRecoveryPointsCommandOutput>;
export declare function deserializeAws_json1_1ListVolumesCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListVolumesCommandOutput>;
export declare function deserializeAws_json1_1NotifyWhenUploadedCommand(output: __HttpResponse, context: __SerdeContext): Promise<NotifyWhenUploadedCommandOutput>;
export declare function deserializeAws_json1_1RefreshCacheCommand(output: __HttpResponse, context: __SerdeContext): Promise<RefreshCacheCommandOutput>;
export declare function deserializeAws_json1_1RemoveTagsFromResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsFromResourceCommandOutput>;
export declare function deserializeAws_json1_1ResetCacheCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetCacheCommandOutput>;
export declare function deserializeAws_json1_1RetrieveTapeArchiveCommand(output: __HttpResponse, context: __SerdeContext): Promise<RetrieveTapeArchiveCommandOutput>;
export declare function deserializeAws_json1_1RetrieveTapeRecoveryPointCommand(output: __HttpResponse, context: __SerdeContext): Promise<RetrieveTapeRecoveryPointCommandOutput>;
export declare function deserializeAws_json1_1SetLocalConsolePasswordCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetLocalConsolePasswordCommandOutput>;
export declare function deserializeAws_json1_1SetSMBGuestPasswordCommand(output: __HttpResponse, context: __SerdeContext): Promise<SetSMBGuestPasswordCommandOutput>;
export declare function deserializeAws_json1_1ShutdownGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<ShutdownGatewayCommandOutput>;
export declare function deserializeAws_json1_1StartAvailabilityMonitorTestCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartAvailabilityMonitorTestCommandOutput>;
export declare function deserializeAws_json1_1StartGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartGatewayCommandOutput>;
export declare function deserializeAws_json1_1UpdateBandwidthRateLimitCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateBandwidthRateLimitCommandOutput>;
export declare function deserializeAws_json1_1UpdateChapCredentialsCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateChapCredentialsCommandOutput>;
export declare function deserializeAws_json1_1UpdateGatewayInformationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateGatewayInformationCommandOutput>;
export declare function deserializeAws_json1_1UpdateGatewaySoftwareNowCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateGatewaySoftwareNowCommandOutput>;
export declare function deserializeAws_json1_1UpdateMaintenanceStartTimeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateMaintenanceStartTimeCommandOutput>;
export declare function deserializeAws_json1_1UpdateNFSFileShareCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateNFSFileShareCommandOutput>;
export declare function deserializeAws_json1_1UpdateSMBFileShareCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSMBFileShareCommandOutput>;
export declare function deserializeAws_json1_1UpdateSMBSecurityStrategyCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSMBSecurityStrategyCommandOutput>;
export declare function deserializeAws_json1_1UpdateSnapshotScheduleCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSnapshotScheduleCommandOutput>;
export declare function deserializeAws_json1_1UpdateVTLDeviceTypeCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVTLDeviceTypeCommandOutput>;
