import { AddTagsToResourceCommandInput, AddTagsToResourceCommandOutput } from "../commands/AddTagsToResourceCommand";
import { AuthorizeCacheSecurityGroupIngressCommandInput, AuthorizeCacheSecurityGroupIngressCommandOutput } from "../commands/AuthorizeCacheSecurityGroupIngressCommand";
import { BatchApplyUpdateActionCommandInput, BatchApplyUpdateActionCommandOutput } from "../commands/BatchApplyUpdateActionCommand";
import { BatchStopUpdateActionCommandInput, BatchStopUpdateActionCommandOutput } from "../commands/BatchStopUpdateActionCommand";
import { CompleteMigrationCommandInput, CompleteMigrationCommandOutput } from "../commands/CompleteMigrationCommand";
import { CopySnapshotCommandInput, CopySnapshotCommandOutput } from "../commands/CopySnapshotCommand";
import { CreateCacheClusterCommandInput, CreateCacheClusterCommandOutput } from "../commands/CreateCacheClusterCommand";
import { CreateCacheParameterGroupCommandInput, CreateCacheParameterGroupCommandOutput } from "../commands/CreateCacheParameterGroupCommand";
import { CreateCacheSecurityGroupCommandInput, CreateCacheSecurityGroupCommandOutput } from "../commands/CreateCacheSecurityGroupCommand";
import { CreateCacheSubnetGroupCommandInput, CreateCacheSubnetGroupCommandOutput } from "../commands/CreateCacheSubnetGroupCommand";
import { CreateReplicationGroupCommandInput, CreateReplicationGroupCommandOutput } from "../commands/CreateReplicationGroupCommand";
import { CreateSnapshotCommandInput, CreateSnapshotCommandOutput } from "../commands/CreateSnapshotCommand";
import { DecreaseReplicaCountCommandInput, DecreaseReplicaCountCommandOutput } from "../commands/DecreaseReplicaCountCommand";
import { DeleteCacheClusterCommandInput, DeleteCacheClusterCommandOutput } from "../commands/DeleteCacheClusterCommand";
import { DeleteCacheParameterGroupCommandInput, DeleteCacheParameterGroupCommandOutput } from "../commands/DeleteCacheParameterGroupCommand";
import { DeleteCacheSecurityGroupCommandInput, DeleteCacheSecurityGroupCommandOutput } from "../commands/DeleteCacheSecurityGroupCommand";
import { DeleteCacheSubnetGroupCommandInput, DeleteCacheSubnetGroupCommandOutput } from "../commands/DeleteCacheSubnetGroupCommand";
import { DeleteReplicationGroupCommandInput, DeleteReplicationGroupCommandOutput } from "../commands/DeleteReplicationGroupCommand";
import { DeleteSnapshotCommandInput, DeleteSnapshotCommandOutput } from "../commands/DeleteSnapshotCommand";
import { DescribeCacheClustersCommandInput, DescribeCacheClustersCommandOutput } from "../commands/DescribeCacheClustersCommand";
import { DescribeCacheEngineVersionsCommandInput, DescribeCacheEngineVersionsCommandOutput } from "../commands/DescribeCacheEngineVersionsCommand";
import { DescribeCacheParameterGroupsCommandInput, DescribeCacheParameterGroupsCommandOutput } from "../commands/DescribeCacheParameterGroupsCommand";
import { DescribeCacheParametersCommandInput, DescribeCacheParametersCommandOutput } from "../commands/DescribeCacheParametersCommand";
import { DescribeCacheSecurityGroupsCommandInput, DescribeCacheSecurityGroupsCommandOutput } from "../commands/DescribeCacheSecurityGroupsCommand";
import { DescribeCacheSubnetGroupsCommandInput, DescribeCacheSubnetGroupsCommandOutput } from "../commands/DescribeCacheSubnetGroupsCommand";
import { DescribeEngineDefaultParametersCommandInput, DescribeEngineDefaultParametersCommandOutput } from "../commands/DescribeEngineDefaultParametersCommand";
import { DescribeEventsCommandInput, DescribeEventsCommandOutput } from "../commands/DescribeEventsCommand";
import { DescribeReplicationGroupsCommandInput, DescribeReplicationGroupsCommandOutput } from "../commands/DescribeReplicationGroupsCommand";
import { DescribeReservedCacheNodesCommandInput, DescribeReservedCacheNodesCommandOutput } from "../commands/DescribeReservedCacheNodesCommand";
import { DescribeReservedCacheNodesOfferingsCommandInput, DescribeReservedCacheNodesOfferingsCommandOutput } from "../commands/DescribeReservedCacheNodesOfferingsCommand";
import { DescribeServiceUpdatesCommandInput, DescribeServiceUpdatesCommandOutput } from "../commands/DescribeServiceUpdatesCommand";
import { DescribeSnapshotsCommandInput, DescribeSnapshotsCommandOutput } from "../commands/DescribeSnapshotsCommand";
import { DescribeUpdateActionsCommandInput, DescribeUpdateActionsCommandOutput } from "../commands/DescribeUpdateActionsCommand";
import { IncreaseReplicaCountCommandInput, IncreaseReplicaCountCommandOutput } from "../commands/IncreaseReplicaCountCommand";
import { ListAllowedNodeTypeModificationsCommandInput, ListAllowedNodeTypeModificationsCommandOutput } from "../commands/ListAllowedNodeTypeModificationsCommand";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "../commands/ListTagsForResourceCommand";
import { ModifyCacheClusterCommandInput, ModifyCacheClusterCommandOutput } from "../commands/ModifyCacheClusterCommand";
import { ModifyCacheParameterGroupCommandInput, ModifyCacheParameterGroupCommandOutput } from "../commands/ModifyCacheParameterGroupCommand";
import { ModifyCacheSubnetGroupCommandInput, ModifyCacheSubnetGroupCommandOutput } from "../commands/ModifyCacheSubnetGroupCommand";
import { ModifyReplicationGroupCommandInput, ModifyReplicationGroupCommandOutput } from "../commands/ModifyReplicationGroupCommand";
import { ModifyReplicationGroupShardConfigurationCommandInput, ModifyReplicationGroupShardConfigurationCommandOutput } from "../commands/ModifyReplicationGroupShardConfigurationCommand";
import { PurchaseReservedCacheNodesOfferingCommandInput, PurchaseReservedCacheNodesOfferingCommandOutput } from "../commands/PurchaseReservedCacheNodesOfferingCommand";
import { RebootCacheClusterCommandInput, RebootCacheClusterCommandOutput } from "../commands/RebootCacheClusterCommand";
import { RemoveTagsFromResourceCommandInput, RemoveTagsFromResourceCommandOutput } from "../commands/RemoveTagsFromResourceCommand";
import { ResetCacheParameterGroupCommandInput, ResetCacheParameterGroupCommandOutput } from "../commands/ResetCacheParameterGroupCommand";
import { RevokeCacheSecurityGroupIngressCommandInput, RevokeCacheSecurityGroupIngressCommandOutput } from "../commands/RevokeCacheSecurityGroupIngressCommand";
import { StartMigrationCommandInput, StartMigrationCommandOutput } from "../commands/StartMigrationCommand";
import { TestFailoverCommandInput, TestFailoverCommandOutput } from "../commands/TestFailoverCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_queryAddTagsToResourceCommand(input: AddTagsToResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryAuthorizeCacheSecurityGroupIngressCommand(input: AuthorizeCacheSecurityGroupIngressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryBatchApplyUpdateActionCommand(input: BatchApplyUpdateActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryBatchStopUpdateActionCommand(input: BatchStopUpdateActionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCompleteMigrationCommand(input: CompleteMigrationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCopySnapshotCommand(input: CopySnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateCacheClusterCommand(input: CreateCacheClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateCacheParameterGroupCommand(input: CreateCacheParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateCacheSecurityGroupCommand(input: CreateCacheSecurityGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateCacheSubnetGroupCommand(input: CreateCacheSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateReplicationGroupCommand(input: CreateReplicationGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryCreateSnapshotCommand(input: CreateSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDecreaseReplicaCountCommand(input: DecreaseReplicaCountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteCacheClusterCommand(input: DeleteCacheClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteCacheParameterGroupCommand(input: DeleteCacheParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteCacheSecurityGroupCommand(input: DeleteCacheSecurityGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteCacheSubnetGroupCommand(input: DeleteCacheSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteReplicationGroupCommand(input: DeleteReplicationGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDeleteSnapshotCommand(input: DeleteSnapshotCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheClustersCommand(input: DescribeCacheClustersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheEngineVersionsCommand(input: DescribeCacheEngineVersionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheParameterGroupsCommand(input: DescribeCacheParameterGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheParametersCommand(input: DescribeCacheParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheSecurityGroupsCommand(input: DescribeCacheSecurityGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeCacheSubnetGroupsCommand(input: DescribeCacheSubnetGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEngineDefaultParametersCommand(input: DescribeEngineDefaultParametersCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeEventsCommand(input: DescribeEventsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeReplicationGroupsCommand(input: DescribeReplicationGroupsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeReservedCacheNodesCommand(input: DescribeReservedCacheNodesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeReservedCacheNodesOfferingsCommand(input: DescribeReservedCacheNodesOfferingsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeServiceUpdatesCommand(input: DescribeServiceUpdatesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeSnapshotsCommand(input: DescribeSnapshotsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryDescribeUpdateActionsCommand(input: DescribeUpdateActionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryIncreaseReplicaCountCommand(input: IncreaseReplicaCountCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListAllowedNodeTypeModificationsCommand(input: ListAllowedNodeTypeModificationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryListTagsForResourceCommand(input: ListTagsForResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyCacheClusterCommand(input: ModifyCacheClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyCacheParameterGroupCommand(input: ModifyCacheParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyCacheSubnetGroupCommand(input: ModifyCacheSubnetGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyReplicationGroupCommand(input: ModifyReplicationGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryModifyReplicationGroupShardConfigurationCommand(input: ModifyReplicationGroupShardConfigurationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryPurchaseReservedCacheNodesOfferingCommand(input: PurchaseReservedCacheNodesOfferingCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRebootCacheClusterCommand(input: RebootCacheClusterCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRemoveTagsFromResourceCommand(input: RemoveTagsFromResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryResetCacheParameterGroupCommand(input: ResetCacheParameterGroupCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryRevokeCacheSecurityGroupIngressCommand(input: RevokeCacheSecurityGroupIngressCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryStartMigrationCommand(input: StartMigrationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_queryTestFailoverCommand(input: TestFailoverCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_queryAddTagsToResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AddTagsToResourceCommandOutput>;
export declare function deserializeAws_queryAuthorizeCacheSecurityGroupIngressCommand(output: __HttpResponse, context: __SerdeContext): Promise<AuthorizeCacheSecurityGroupIngressCommandOutput>;
export declare function deserializeAws_queryBatchApplyUpdateActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchApplyUpdateActionCommandOutput>;
export declare function deserializeAws_queryBatchStopUpdateActionCommand(output: __HttpResponse, context: __SerdeContext): Promise<BatchStopUpdateActionCommandOutput>;
export declare function deserializeAws_queryCompleteMigrationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CompleteMigrationCommandOutput>;
export declare function deserializeAws_queryCopySnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CopySnapshotCommandOutput>;
export declare function deserializeAws_queryCreateCacheClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCacheClusterCommandOutput>;
export declare function deserializeAws_queryCreateCacheParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCacheParameterGroupCommandOutput>;
export declare function deserializeAws_queryCreateCacheSecurityGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCacheSecurityGroupCommandOutput>;
export declare function deserializeAws_queryCreateCacheSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateCacheSubnetGroupCommandOutput>;
export declare function deserializeAws_queryCreateReplicationGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateReplicationGroupCommandOutput>;
export declare function deserializeAws_queryCreateSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSnapshotCommandOutput>;
export declare function deserializeAws_queryDecreaseReplicaCountCommand(output: __HttpResponse, context: __SerdeContext): Promise<DecreaseReplicaCountCommandOutput>;
export declare function deserializeAws_queryDeleteCacheClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCacheClusterCommandOutput>;
export declare function deserializeAws_queryDeleteCacheParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCacheParameterGroupCommandOutput>;
export declare function deserializeAws_queryDeleteCacheSecurityGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCacheSecurityGroupCommandOutput>;
export declare function deserializeAws_queryDeleteCacheSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteCacheSubnetGroupCommandOutput>;
export declare function deserializeAws_queryDeleteReplicationGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteReplicationGroupCommandOutput>;
export declare function deserializeAws_queryDeleteSnapshotCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSnapshotCommandOutput>;
export declare function deserializeAws_queryDescribeCacheClustersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheClustersCommandOutput>;
export declare function deserializeAws_queryDescribeCacheEngineVersionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheEngineVersionsCommandOutput>;
export declare function deserializeAws_queryDescribeCacheParameterGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheParameterGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeCacheParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheParametersCommandOutput>;
export declare function deserializeAws_queryDescribeCacheSecurityGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheSecurityGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeCacheSubnetGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeCacheSubnetGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeEngineDefaultParametersCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEngineDefaultParametersCommandOutput>;
export declare function deserializeAws_queryDescribeEventsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeEventsCommandOutput>;
export declare function deserializeAws_queryDescribeReplicationGroupsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReplicationGroupsCommandOutput>;
export declare function deserializeAws_queryDescribeReservedCacheNodesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReservedCacheNodesCommandOutput>;
export declare function deserializeAws_queryDescribeReservedCacheNodesOfferingsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeReservedCacheNodesOfferingsCommandOutput>;
export declare function deserializeAws_queryDescribeServiceUpdatesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeServiceUpdatesCommandOutput>;
export declare function deserializeAws_queryDescribeSnapshotsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSnapshotsCommandOutput>;
export declare function deserializeAws_queryDescribeUpdateActionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeUpdateActionsCommandOutput>;
export declare function deserializeAws_queryIncreaseReplicaCountCommand(output: __HttpResponse, context: __SerdeContext): Promise<IncreaseReplicaCountCommandOutput>;
export declare function deserializeAws_queryListAllowedNodeTypeModificationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListAllowedNodeTypeModificationsCommandOutput>;
export declare function deserializeAws_queryListTagsForResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ListTagsForResourceCommandOutput>;
export declare function deserializeAws_queryModifyCacheClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyCacheClusterCommandOutput>;
export declare function deserializeAws_queryModifyCacheParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyCacheParameterGroupCommandOutput>;
export declare function deserializeAws_queryModifyCacheSubnetGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyCacheSubnetGroupCommandOutput>;
export declare function deserializeAws_queryModifyReplicationGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyReplicationGroupCommandOutput>;
export declare function deserializeAws_queryModifyReplicationGroupShardConfigurationCommand(output: __HttpResponse, context: __SerdeContext): Promise<ModifyReplicationGroupShardConfigurationCommandOutput>;
export declare function deserializeAws_queryPurchaseReservedCacheNodesOfferingCommand(output: __HttpResponse, context: __SerdeContext): Promise<PurchaseReservedCacheNodesOfferingCommandOutput>;
export declare function deserializeAws_queryRebootCacheClusterCommand(output: __HttpResponse, context: __SerdeContext): Promise<RebootCacheClusterCommandOutput>;
export declare function deserializeAws_queryRemoveTagsFromResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<RemoveTagsFromResourceCommandOutput>;
export declare function deserializeAws_queryResetCacheParameterGroupCommand(output: __HttpResponse, context: __SerdeContext): Promise<ResetCacheParameterGroupCommandOutput>;
export declare function deserializeAws_queryRevokeCacheSecurityGroupIngressCommand(output: __HttpResponse, context: __SerdeContext): Promise<RevokeCacheSecurityGroupIngressCommandOutput>;
export declare function deserializeAws_queryStartMigrationCommand(output: __HttpResponse, context: __SerdeContext): Promise<StartMigrationCommandOutput>;
export declare function deserializeAws_queryTestFailoverCommand(output: __HttpResponse, context: __SerdeContext): Promise<TestFailoverCommandOutput>;
