import { AcceptDirectConnectGatewayAssociationProposalCommandInput, AcceptDirectConnectGatewayAssociationProposalCommandOutput } from "../commands/AcceptDirectConnectGatewayAssociationProposalCommand";
import { AllocateConnectionOnInterconnectCommandInput, AllocateConnectionOnInterconnectCommandOutput } from "../commands/AllocateConnectionOnInterconnectCommand";
import { AllocateHostedConnectionCommandInput, AllocateHostedConnectionCommandOutput } from "../commands/AllocateHostedConnectionCommand";
import { AllocatePrivateVirtualInterfaceCommandInput, AllocatePrivateVirtualInterfaceCommandOutput } from "../commands/AllocatePrivateVirtualInterfaceCommand";
import { AllocatePublicVirtualInterfaceCommandInput, AllocatePublicVirtualInterfaceCommandOutput } from "../commands/AllocatePublicVirtualInterfaceCommand";
import { AllocateTransitVirtualInterfaceCommandInput, AllocateTransitVirtualInterfaceCommandOutput } from "../commands/AllocateTransitVirtualInterfaceCommand";
import { AssociateConnectionWithLagCommandInput, AssociateConnectionWithLagCommandOutput } from "../commands/AssociateConnectionWithLagCommand";
import { AssociateHostedConnectionCommandInput, AssociateHostedConnectionCommandOutput } from "../commands/AssociateHostedConnectionCommand";
import { AssociateVirtualInterfaceCommandInput, AssociateVirtualInterfaceCommandOutput } from "../commands/AssociateVirtualInterfaceCommand";
import { ConfirmConnectionCommandInput, ConfirmConnectionCommandOutput } from "../commands/ConfirmConnectionCommand";
import { ConfirmPrivateVirtualInterfaceCommandInput, ConfirmPrivateVirtualInterfaceCommandOutput } from "../commands/ConfirmPrivateVirtualInterfaceCommand";
import { ConfirmPublicVirtualInterfaceCommandInput, ConfirmPublicVirtualInterfaceCommandOutput } from "../commands/ConfirmPublicVirtualInterfaceCommand";
import { ConfirmTransitVirtualInterfaceCommandInput, ConfirmTransitVirtualInterfaceCommandOutput } from "../commands/ConfirmTransitVirtualInterfaceCommand";
import { CreateBGPPeerCommandInput, CreateBGPPeerCommandOutput } from "../commands/CreateBGPPeerCommand";
import { CreateConnectionCommandInput, CreateConnectionCommandOutput } from "../commands/CreateConnectionCommand";
import { CreateDirectConnectGatewayAssociationCommandInput, CreateDirectConnectGatewayAssociationCommandOutput } from "../commands/CreateDirectConnectGatewayAssociationCommand";
import { CreateDirectConnectGatewayAssociationProposalCommandInput, CreateDirectConnectGatewayAssociationProposalCommandOutput } from "../commands/CreateDirectConnectGatewayAssociationProposalCommand";
import { CreateDirectConnectGatewayCommandInput, CreateDirectConnectGatewayCommandOutput } from "../commands/CreateDirectConnectGatewayCommand";
import { CreateInterconnectCommandInput, CreateInterconnectCommandOutput } from "../commands/CreateInterconnectCommand";
import { CreateLagCommandInput, CreateLagCommandOutput } from "../commands/CreateLagCommand";
import { CreatePrivateVirtualInterfaceCommandInput, CreatePrivateVirtualInterfaceCommandOutput } from "../commands/CreatePrivateVirtualInterfaceCommand";
import { CreatePublicVirtualInterfaceCommandInput, CreatePublicVirtualInterfaceCommandOutput } from "../commands/CreatePublicVirtualInterfaceCommand";
import { CreateTransitVirtualInterfaceCommandInput, CreateTransitVirtualInterfaceCommandOutput } from "../commands/CreateTransitVirtualInterfaceCommand";
import { DeleteBGPPeerCommandInput, DeleteBGPPeerCommandOutput } from "../commands/DeleteBGPPeerCommand";
import { DeleteConnectionCommandInput, DeleteConnectionCommandOutput } from "../commands/DeleteConnectionCommand";
import { DeleteDirectConnectGatewayAssociationCommandInput, DeleteDirectConnectGatewayAssociationCommandOutput } from "../commands/DeleteDirectConnectGatewayAssociationCommand";
import { DeleteDirectConnectGatewayAssociationProposalCommandInput, DeleteDirectConnectGatewayAssociationProposalCommandOutput } from "../commands/DeleteDirectConnectGatewayAssociationProposalCommand";
import { DeleteDirectConnectGatewayCommandInput, DeleteDirectConnectGatewayCommandOutput } from "../commands/DeleteDirectConnectGatewayCommand";
import { DeleteInterconnectCommandInput, DeleteInterconnectCommandOutput } from "../commands/DeleteInterconnectCommand";
import { DeleteLagCommandInput, DeleteLagCommandOutput } from "../commands/DeleteLagCommand";
import { DeleteVirtualInterfaceCommandInput, DeleteVirtualInterfaceCommandOutput } from "../commands/DeleteVirtualInterfaceCommand";
import { DescribeConnectionLoaCommandInput, DescribeConnectionLoaCommandOutput } from "../commands/DescribeConnectionLoaCommand";
import { DescribeConnectionsCommandInput, DescribeConnectionsCommandOutput } from "../commands/DescribeConnectionsCommand";
import { DescribeConnectionsOnInterconnectCommandInput, DescribeConnectionsOnInterconnectCommandOutput } from "../commands/DescribeConnectionsOnInterconnectCommand";
import { DescribeDirectConnectGatewayAssociationProposalsCommandInput, DescribeDirectConnectGatewayAssociationProposalsCommandOutput } from "../commands/DescribeDirectConnectGatewayAssociationProposalsCommand";
import { DescribeDirectConnectGatewayAssociationsCommandInput, DescribeDirectConnectGatewayAssociationsCommandOutput } from "../commands/DescribeDirectConnectGatewayAssociationsCommand";
import { DescribeDirectConnectGatewayAttachmentsCommandInput, DescribeDirectConnectGatewayAttachmentsCommandOutput } from "../commands/DescribeDirectConnectGatewayAttachmentsCommand";
import { DescribeDirectConnectGatewaysCommandInput, DescribeDirectConnectGatewaysCommandOutput } from "../commands/DescribeDirectConnectGatewaysCommand";
import { DescribeHostedConnectionsCommandInput, DescribeHostedConnectionsCommandOutput } from "../commands/DescribeHostedConnectionsCommand";
import { DescribeInterconnectLoaCommandInput, DescribeInterconnectLoaCommandOutput } from "../commands/DescribeInterconnectLoaCommand";
import { DescribeInterconnectsCommandInput, DescribeInterconnectsCommandOutput } from "../commands/DescribeInterconnectsCommand";
import { DescribeLagsCommandInput, DescribeLagsCommandOutput } from "../commands/DescribeLagsCommand";
import { DescribeLoaCommandInput, DescribeLoaCommandOutput } from "../commands/DescribeLoaCommand";
import { DescribeLocationsCommandInput, DescribeLocationsCommandOutput } from "../commands/DescribeLocationsCommand";
import { DescribeTagsCommandInput, DescribeTagsCommandOutput } from "../commands/DescribeTagsCommand";
import { DescribeVirtualGatewaysCommandInput, DescribeVirtualGatewaysCommandOutput } from "../commands/DescribeVirtualGatewaysCommand";
import { DescribeVirtualInterfacesCommandInput, DescribeVirtualInterfacesCommandOutput } from "../commands/DescribeVirtualInterfacesCommand";
import { DisassociateConnectionFromLagCommandInput, DisassociateConnectionFromLagCommandOutput } from "../commands/DisassociateConnectionFromLagCommand";
import { TagResourceCommandInput, TagResourceCommandOutput } from "../commands/TagResourceCommand";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "../commands/UntagResourceCommand";
import { UpdateDirectConnectGatewayAssociationCommandInput, UpdateDirectConnectGatewayAssociationCommandOutput } from "../commands/UpdateDirectConnectGatewayAssociationCommand";
import { UpdateLagCommandInput, UpdateLagCommandOutput } from "../commands/UpdateLagCommand";
import { UpdateVirtualInterfaceAttributesCommandInput, UpdateVirtualInterfaceAttributesCommandOutput } from "../commands/UpdateVirtualInterfaceAttributesCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1AcceptDirectConnectGatewayAssociationProposalCommand(input: AcceptDirectConnectGatewayAssociationProposalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AllocateConnectionOnInterconnectCommand(input: AllocateConnectionOnInterconnectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AllocateHostedConnectionCommand(input: AllocateHostedConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AllocatePrivateVirtualInterfaceCommand(input: AllocatePrivateVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AllocatePublicVirtualInterfaceCommand(input: AllocatePublicVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AllocateTransitVirtualInterfaceCommand(input: AllocateTransitVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateConnectionWithLagCommand(input: AssociateConnectionWithLagCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateHostedConnectionCommand(input: AssociateHostedConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1AssociateVirtualInterfaceCommand(input: AssociateVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ConfirmConnectionCommand(input: ConfirmConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ConfirmPrivateVirtualInterfaceCommand(input: ConfirmPrivateVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ConfirmPublicVirtualInterfaceCommand(input: ConfirmPublicVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1ConfirmTransitVirtualInterfaceCommand(input: ConfirmTransitVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateBGPPeerCommand(input: CreateBGPPeerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateConnectionCommand(input: CreateConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDirectConnectGatewayCommand(input: CreateDirectConnectGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDirectConnectGatewayAssociationCommand(input: CreateDirectConnectGatewayAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateDirectConnectGatewayAssociationProposalCommand(input: CreateDirectConnectGatewayAssociationProposalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateInterconnectCommand(input: CreateInterconnectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateLagCommand(input: CreateLagCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePrivateVirtualInterfaceCommand(input: CreatePrivateVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreatePublicVirtualInterfaceCommand(input: CreatePublicVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateTransitVirtualInterfaceCommand(input: CreateTransitVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBGPPeerCommand(input: DeleteBGPPeerCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteConnectionCommand(input: DeleteConnectionCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDirectConnectGatewayCommand(input: DeleteDirectConnectGatewayCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDirectConnectGatewayAssociationCommand(input: DeleteDirectConnectGatewayAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteDirectConnectGatewayAssociationProposalCommand(input: DeleteDirectConnectGatewayAssociationProposalCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteInterconnectCommand(input: DeleteInterconnectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteLagCommand(input: DeleteLagCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteVirtualInterfaceCommand(input: DeleteVirtualInterfaceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeConnectionLoaCommand(input: DescribeConnectionLoaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeConnectionsCommand(input: DescribeConnectionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeConnectionsOnInterconnectCommand(input: DescribeConnectionsOnInterconnectCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDirectConnectGatewayAssociationProposalsCommand(input: DescribeDirectConnectGatewayAssociationProposalsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDirectConnectGatewayAssociationsCommand(input: DescribeDirectConnectGatewayAssociationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDirectConnectGatewayAttachmentsCommand(input: DescribeDirectConnectGatewayAttachmentsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeDirectConnectGatewaysCommand(input: DescribeDirectConnectGatewaysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeHostedConnectionsCommand(input: DescribeHostedConnectionsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInterconnectLoaCommand(input: DescribeInterconnectLoaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeInterconnectsCommand(input: DescribeInterconnectsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLagsCommand(input: DescribeLagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLoaCommand(input: DescribeLoaCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeLocationsCommand(input: DescribeLocationsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeTagsCommand(input: DescribeTagsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVirtualGatewaysCommand(input: DescribeVirtualGatewaysCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeVirtualInterfacesCommand(input: DescribeVirtualInterfacesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DisassociateConnectionFromLagCommand(input: DisassociateConnectionFromLagCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1TagResourceCommand(input: TagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UntagResourceCommand(input: UntagResourceCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateDirectConnectGatewayAssociationCommand(input: UpdateDirectConnectGatewayAssociationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateLagCommand(input: UpdateLagCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateVirtualInterfaceAttributesCommand(input: UpdateVirtualInterfaceAttributesCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1AcceptDirectConnectGatewayAssociationProposalCommand(output: __HttpResponse, context: __SerdeContext): Promise<AcceptDirectConnectGatewayAssociationProposalCommandOutput>;
export declare function deserializeAws_json1_1AllocateConnectionOnInterconnectCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocateConnectionOnInterconnectCommandOutput>;
export declare function deserializeAws_json1_1AllocateHostedConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocateHostedConnectionCommandOutput>;
export declare function deserializeAws_json1_1AllocatePrivateVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocatePrivateVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1AllocatePublicVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocatePublicVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1AllocateTransitVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AllocateTransitVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1AssociateConnectionWithLagCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateConnectionWithLagCommandOutput>;
export declare function deserializeAws_json1_1AssociateHostedConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateHostedConnectionCommandOutput>;
export declare function deserializeAws_json1_1AssociateVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<AssociateVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1ConfirmConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfirmConnectionCommandOutput>;
export declare function deserializeAws_json1_1ConfirmPrivateVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfirmPrivateVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1ConfirmPublicVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfirmPublicVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1ConfirmTransitVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<ConfirmTransitVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1CreateBGPPeerCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBGPPeerCommandOutput>;
export declare function deserializeAws_json1_1CreateConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateConnectionCommandOutput>;
export declare function deserializeAws_json1_1CreateDirectConnectGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDirectConnectGatewayCommandOutput>;
export declare function deserializeAws_json1_1CreateDirectConnectGatewayAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDirectConnectGatewayAssociationCommandOutput>;
export declare function deserializeAws_json1_1CreateDirectConnectGatewayAssociationProposalCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateDirectConnectGatewayAssociationProposalCommandOutput>;
export declare function deserializeAws_json1_1CreateInterconnectCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateInterconnectCommandOutput>;
export declare function deserializeAws_json1_1CreateLagCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateLagCommandOutput>;
export declare function deserializeAws_json1_1CreatePrivateVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePrivateVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1CreatePublicVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreatePublicVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1CreateTransitVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateTransitVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1DeleteBGPPeerCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBGPPeerCommandOutput>;
export declare function deserializeAws_json1_1DeleteConnectionCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteConnectionCommandOutput>;
export declare function deserializeAws_json1_1DeleteDirectConnectGatewayCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDirectConnectGatewayCommandOutput>;
export declare function deserializeAws_json1_1DeleteDirectConnectGatewayAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDirectConnectGatewayAssociationCommandOutput>;
export declare function deserializeAws_json1_1DeleteDirectConnectGatewayAssociationProposalCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteDirectConnectGatewayAssociationProposalCommandOutput>;
export declare function deserializeAws_json1_1DeleteInterconnectCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteInterconnectCommandOutput>;
export declare function deserializeAws_json1_1DeleteLagCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteLagCommandOutput>;
export declare function deserializeAws_json1_1DeleteVirtualInterfaceCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteVirtualInterfaceCommandOutput>;
export declare function deserializeAws_json1_1DescribeConnectionLoaCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeConnectionLoaCommandOutput>;
export declare function deserializeAws_json1_1DescribeConnectionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeConnectionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeConnectionsOnInterconnectCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeConnectionsOnInterconnectCommandOutput>;
export declare function deserializeAws_json1_1DescribeDirectConnectGatewayAssociationProposalsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDirectConnectGatewayAssociationProposalsCommandOutput>;
export declare function deserializeAws_json1_1DescribeDirectConnectGatewayAssociationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDirectConnectGatewayAssociationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeDirectConnectGatewayAttachmentsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDirectConnectGatewayAttachmentsCommandOutput>;
export declare function deserializeAws_json1_1DescribeDirectConnectGatewaysCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeDirectConnectGatewaysCommandOutput>;
export declare function deserializeAws_json1_1DescribeHostedConnectionsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeHostedConnectionsCommandOutput>;
export declare function deserializeAws_json1_1DescribeInterconnectLoaCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInterconnectLoaCommandOutput>;
export declare function deserializeAws_json1_1DescribeInterconnectsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeInterconnectsCommandOutput>;
export declare function deserializeAws_json1_1DescribeLagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLagsCommandOutput>;
export declare function deserializeAws_json1_1DescribeLoaCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLoaCommandOutput>;
export declare function deserializeAws_json1_1DescribeLocationsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeLocationsCommandOutput>;
export declare function deserializeAws_json1_1DescribeTagsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeTagsCommandOutput>;
export declare function deserializeAws_json1_1DescribeVirtualGatewaysCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVirtualGatewaysCommandOutput>;
export declare function deserializeAws_json1_1DescribeVirtualInterfacesCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeVirtualInterfacesCommandOutput>;
export declare function deserializeAws_json1_1DisassociateConnectionFromLagCommand(output: __HttpResponse, context: __SerdeContext): Promise<DisassociateConnectionFromLagCommandOutput>;
export declare function deserializeAws_json1_1TagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<TagResourceCommandOutput>;
export declare function deserializeAws_json1_1UntagResourceCommand(output: __HttpResponse, context: __SerdeContext): Promise<UntagResourceCommandOutput>;
export declare function deserializeAws_json1_1UpdateDirectConnectGatewayAssociationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateDirectConnectGatewayAssociationCommandOutput>;
export declare function deserializeAws_json1_1UpdateLagCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateLagCommandOutput>;
export declare function deserializeAws_json1_1UpdateVirtualInterfaceAttributesCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateVirtualInterfaceAttributesCommandOutput>;
