name: Build

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, build and test
      run: |
        yarn --frozen-lockfile
        ./node_modules/.bin/lerna run build --since origin/master --include-dependents
        ./node_modules/.bin/lerna run test --since origin/master
      env:
        CI: true