name: Closed Issue Message
on:
    issues:
       types: [closed]
jobs:
    auto_comment:
        if: github.repository == 'aws/aws-sdk-js-v3'
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
        - uses: aws-actions/closed-issue-message@cf797c2463fa6b95a23b2957fe075a3fa9aa8138 # v1
          with:
            # These inputs are both required
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            message: |
                     This issue is now closed. Comments on closed issues are hard for our team to see. 
                     If you need more assistance, please open a new issue that references this one.
