name: codegen-ci

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/codegen-ci.yml'
      - 'codegen/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/codegen-ci.yml'
      - 'codegen/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Java ${{ matrix.java }}
    strategy: 
      matrix:
        java: [17]

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: build and publish smithy-typescript
        run: |
          node ./scripts/generate-clients/build-smithy-typescript-ci.js
      
      - name: build and test codegen
        run: |
          cd ./codegen
          ./gradlew clean sdk-codegen:build smithy-aws-typescript-codegen:build protocol-test-codegen:build -Plog-tests

      - name: publish codegen
        run: |
          cd ./codegen
          ./gradlew :smithy-aws-typescript-codegen:publish

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: test-codegen
        run: make test-codegen
