name: commit-message-lint

on:
  push:
    branches: [ main, feat/sra-identity-auth ]
  pull_request:
    branches: [ main, feat/sra-identity-auth ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
            
