name: server-protocol-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - uses: actions/checkout@v2
        with:
          repository: awslabs/smithy-typescript
          path: smithy-typescript
          fetch-depth: 1

      - name: build and publish smithy-typescript
        run: |
          cd smithy-typescript
          ./gradlew clean :smithy-typescript-codegen:publishToMavenLocal
          cd smithy-typescript-ssdk-libs
          yarn install
          yarn build
          cd server-common
          yarn link
          cd ../..

      - name: install dependencies
        run: |
          yarn install

      - name: generate protocol tests
        run: |
          yarn generate-clients --server-artifacts

      # there are new dependencies as a result of generating server protocol tests
      - name: install dependencies again
        run: |
          yarn link @aws-smithy/server-common
          yarn install

      - name: run protocol tests
        run: |
          yarn test:server-protocols


