name: server-protocol-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: build and publish smithy-typescript
        run: |
          git clone --depth 1 https://github.com/awslabs/smithy-typescript.git
          cd smithy-typescript
          ./gradlew clean build publishToMavenLocal
          cd ..

      - name: generate protocol tests
        run: |
          yarn generate-server-protocols

      - name: run protocol tests
        run: |
          yarn test:server-protocols


