services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
