// smithy-typescript generated code
import { SnapshotRunner } from "@smithy/snapshot-testing";
import { join } from "node:path";
import { describe, expect, test as it, vi } from "vitest";

import {
  AccessDeniedException$,
  AssociatePermission$,
  AssociatePermissionCommand,
  BatchDeleteDocument$,
  BatchDeleteDocumentCommand,
  BatchPutDocument$,
  BatchPutDocumentCommand,
  CancelSubscription$,
  CancelSubscriptionCommand,
  Chat$,
  ChatCommand,
  ChatSync$,
  ChatSyncCommand,
  CheckDocumentAccess$,
  CheckDocumentAccessCommand,
  ConflictException$,
  CreateAnonymousWebExperienceUrl$,
  CreateAnonymousWebExperienceUrlCommand,
  CreateApplication$,
  CreateApplicationCommand,
  CreateChatResponseConfiguration$,
  CreateChatResponseConfigurationCommand,
  CreateDataAccessor$,
  CreateDataAccessorCommand,
  CreateDataSource$,
  CreateDataSourceCommand,
  CreateIndex$,
  CreateIndexCommand,
  CreatePlugin$,
  CreatePluginCommand,
  CreateRetriever$,
  CreateRetrieverCommand,
  CreateSubscription$,
  CreateSubscriptionCommand,
  CreateUser$,
  CreateUserCommand,
  CreateWebExperience$,
  CreateWebExperienceCommand,
  DeleteApplication$,
  DeleteApplicationCommand,
  DeleteAttachment$,
  DeleteAttachmentCommand,
  DeleteChatControlsConfiguration$,
  DeleteChatControlsConfigurationCommand,
  DeleteChatResponseConfiguration$,
  DeleteChatResponseConfigurationCommand,
  DeleteConversation$,
  DeleteConversationCommand,
  DeleteDataAccessor$,
  DeleteDataAccessorCommand,
  DeleteDataSource$,
  DeleteDataSourceCommand,
  DeleteGroup$,
  DeleteGroupCommand,
  DeleteIndex$,
  DeleteIndexCommand,
  DeletePlugin$,
  DeletePluginCommand,
  DeleteRetriever$,
  DeleteRetrieverCommand,
  DeleteUser$,
  DeleteUserCommand,
  DeleteWebExperience$,
  DeleteWebExperienceCommand,
  DisassociatePermission$,
  DisassociatePermissionCommand,
  ExternalResourceException$,
  GetApplication$,
  GetApplicationCommand,
  GetChatControlsConfiguration$,
  GetChatControlsConfigurationCommand,
  GetChatResponseConfiguration$,
  GetChatResponseConfigurationCommand,
  GetDataAccessor$,
  GetDataAccessorCommand,
  GetDataSource$,
  GetDataSourceCommand,
  GetDocumentContent$,
  GetDocumentContentCommand,
  GetGroup$,
  GetGroupCommand,
  GetIndex$,
  GetIndexCommand,
  GetMedia$,
  GetMediaCommand,
  GetPlugin$,
  GetPluginCommand,
  GetPolicy$,
  GetPolicyCommand,
  GetRetriever$,
  GetRetrieverCommand,
  GetUser$,
  GetUserCommand,
  GetWebExperience$,
  GetWebExperienceCommand,
  InternalServerException$,
  LicenseNotFoundException$,
  ListApplications$,
  ListApplicationsCommand,
  ListAttachments$,
  ListAttachmentsCommand,
  ListChatResponseConfigurations$,
  ListChatResponseConfigurationsCommand,
  ListConversations$,
  ListConversationsCommand,
  ListDataAccessors$,
  ListDataAccessorsCommand,
  ListDataSources$,
  ListDataSourcesCommand,
  ListDataSourceSyncJobs$,
  ListDataSourceSyncJobsCommand,
  ListDocuments$,
  ListDocumentsCommand,
  ListGroups$,
  ListGroupsCommand,
  ListIndices$,
  ListIndicesCommand,
  ListMessages$,
  ListMessagesCommand,
  ListPluginActions$,
  ListPluginActionsCommand,
  ListPlugins$,
  ListPluginsCommand,
  ListPluginTypeActions$,
  ListPluginTypeActionsCommand,
  ListPluginTypeMetadata$,
  ListPluginTypeMetadataCommand,
  ListRetrievers$,
  ListRetrieversCommand,
  ListSubscriptions$,
  ListSubscriptionsCommand,
  ListTagsForResource$,
  ListTagsForResourceCommand,
  ListWebExperiences$,
  ListWebExperiencesCommand,
  MediaTooLargeException$,
  PutFeedback$,
  PutFeedbackCommand,
  PutGroup$,
  PutGroupCommand,
  QBusinessClient,
  ResourceNotFoundException$,
  SearchRelevantContent$,
  SearchRelevantContentCommand,
  ServiceQuotaExceededException$,
  StartDataSourceSyncJob$,
  StartDataSourceSyncJobCommand,
  StopDataSourceSyncJob$,
  StopDataSourceSyncJobCommand,
  TagResource$,
  TagResourceCommand,
  ThrottlingException$,
  UntagResource$,
  UntagResourceCommand,
  UpdateApplication$,
  UpdateApplicationCommand,
  UpdateChatControlsConfiguration$,
  UpdateChatControlsConfigurationCommand,
  UpdateChatResponseConfiguration$,
  UpdateChatResponseConfigurationCommand,
  UpdateDataAccessor$,
  UpdateDataAccessorCommand,
  UpdateDataSource$,
  UpdateDataSourceCommand,
  UpdateIndex$,
  UpdateIndexCommand,
  UpdatePlugin$,
  UpdatePluginCommand,
  UpdateRetriever$,
  UpdateRetrieverCommand,
  UpdateSubscription$,
  UpdateSubscriptionCommand,
  UpdateUser$,
  UpdateUserCommand,
  UpdateWebExperience$,
  UpdateWebExperienceCommand,
  ValidationException$,
} from "../src";

vi.setSystemTime(new Date(946702799999));
const Client = QBusinessClient;

const mode = (process.env.SNAPSHOT_MODE as "write" | "compare") ?? "write";

describe("QBusinessClient" + ` (${mode})`, () => {
  const runner = new SnapshotRunner({
    snapshotDirPath: join(__dirname, "snapshots"),
    Client,
    mode,
    testCase(caseName: string, run: () => Promise<void>) {
      it(caseName, run);
    },
    assertions(caseName: string, expected: string, actual: string): Promise<void> {
      expect(actual).toEqual(expected);
      return Promise.resolve();
    },
    schemas: new Map<any, any>([
      [AssociatePermission$, AssociatePermissionCommand],
      [BatchDeleteDocument$, BatchDeleteDocumentCommand],
      [BatchPutDocument$, BatchPutDocumentCommand],
      [CancelSubscription$, CancelSubscriptionCommand],
      [Chat$, ChatCommand],
      [ChatSync$, ChatSyncCommand],
      [CheckDocumentAccess$, CheckDocumentAccessCommand],
      [CreateAnonymousWebExperienceUrl$, CreateAnonymousWebExperienceUrlCommand],
      [CreateApplication$, CreateApplicationCommand],
      [CreateChatResponseConfiguration$, CreateChatResponseConfigurationCommand],
      [CreateDataAccessor$, CreateDataAccessorCommand],
      [CreateDataSource$, CreateDataSourceCommand],
      [CreateIndex$, CreateIndexCommand],
      [CreatePlugin$, CreatePluginCommand],
      [CreateRetriever$, CreateRetrieverCommand],
      [CreateSubscription$, CreateSubscriptionCommand],
      [CreateUser$, CreateUserCommand],
      [CreateWebExperience$, CreateWebExperienceCommand],
      [DeleteApplication$, DeleteApplicationCommand],
      [DeleteAttachment$, DeleteAttachmentCommand],
      [DeleteChatControlsConfiguration$, DeleteChatControlsConfigurationCommand],
      [DeleteChatResponseConfiguration$, DeleteChatResponseConfigurationCommand],
      [DeleteConversation$, DeleteConversationCommand],
      [DeleteDataAccessor$, DeleteDataAccessorCommand],
      [DeleteDataSource$, DeleteDataSourceCommand],
      [DeleteGroup$, DeleteGroupCommand],
      [DeleteIndex$, DeleteIndexCommand],
      [DeletePlugin$, DeletePluginCommand],
      [DeleteRetriever$, DeleteRetrieverCommand],
      [DeleteUser$, DeleteUserCommand],
      [DeleteWebExperience$, DeleteWebExperienceCommand],
      [DisassociatePermission$, DisassociatePermissionCommand],
      [GetApplication$, GetApplicationCommand],
      [GetChatControlsConfiguration$, GetChatControlsConfigurationCommand],
      [GetChatResponseConfiguration$, GetChatResponseConfigurationCommand],
      [GetDataAccessor$, GetDataAccessorCommand],
      [GetDataSource$, GetDataSourceCommand],
      [GetDocumentContent$, GetDocumentContentCommand],
      [GetGroup$, GetGroupCommand],
      [GetIndex$, GetIndexCommand],
      [GetMedia$, GetMediaCommand],
      [GetPlugin$, GetPluginCommand],
      [GetPolicy$, GetPolicyCommand],
      [GetRetriever$, GetRetrieverCommand],
      [GetUser$, GetUserCommand],
      [GetWebExperience$, GetWebExperienceCommand],
      [ListApplications$, ListApplicationsCommand],
      [ListAttachments$, ListAttachmentsCommand],
      [ListChatResponseConfigurations$, ListChatResponseConfigurationsCommand],
      [ListConversations$, ListConversationsCommand],
      [ListDataAccessors$, ListDataAccessorsCommand],
      [ListDataSources$, ListDataSourcesCommand],
      [ListDataSourceSyncJobs$, ListDataSourceSyncJobsCommand],
      [ListDocuments$, ListDocumentsCommand],
      [ListGroups$, ListGroupsCommand],
      [ListIndices$, ListIndicesCommand],
      [ListMessages$, ListMessagesCommand],
      [ListPluginActions$, ListPluginActionsCommand],
      [ListPlugins$, ListPluginsCommand],
      [ListPluginTypeActions$, ListPluginTypeActionsCommand],
      [ListPluginTypeMetadata$, ListPluginTypeMetadataCommand],
      [ListRetrievers$, ListRetrieversCommand],
      [ListSubscriptions$, ListSubscriptionsCommand],
      [ListTagsForResource$, ListTagsForResourceCommand],
      [ListWebExperiences$, ListWebExperiencesCommand],
      [PutFeedback$, PutFeedbackCommand],
      [PutGroup$, PutGroupCommand],
      [SearchRelevantContent$, SearchRelevantContentCommand],
      [StartDataSourceSyncJob$, StartDataSourceSyncJobCommand],
      [StopDataSourceSyncJob$, StopDataSourceSyncJobCommand],
      [TagResource$, TagResourceCommand],
      [UntagResource$, UntagResourceCommand],
      [UpdateApplication$, UpdateApplicationCommand],
      [UpdateChatControlsConfiguration$, UpdateChatControlsConfigurationCommand],
      [UpdateChatResponseConfiguration$, UpdateChatResponseConfigurationCommand],
      [UpdateDataAccessor$, UpdateDataAccessorCommand],
      [UpdateDataSource$, UpdateDataSourceCommand],
      [UpdateIndex$, UpdateIndexCommand],
      [UpdatePlugin$, UpdatePluginCommand],
      [UpdateRetriever$, UpdateRetrieverCommand],
      [UpdateSubscription$, UpdateSubscriptionCommand],
      [UpdateUser$, UpdateUserCommand],
      [UpdateWebExperience$, UpdateWebExperienceCommand],
    ]),
    errors: [
      AccessDeniedException$,
      ConflictException$,
      ExternalResourceException$,
      InternalServerException$,
      LicenseNotFoundException$,
      MediaTooLargeException$,
      ResourceNotFoundException$,
      ServiceQuotaExceededException$,
      ThrottlingException$,
      ValidationException$,
    ],
  });
  runner.run();
}, 30_000);
