import { CreateBudgetCommandInput, CreateBudgetCommandOutput } from "../commands/CreateBudgetCommand";
import { CreateNotificationCommandInput, CreateNotificationCommandOutput } from "../commands/CreateNotificationCommand";
import { CreateSubscriberCommandInput, CreateSubscriberCommandOutput } from "../commands/CreateSubscriberCommand";
import { DeleteBudgetCommandInput, DeleteBudgetCommandOutput } from "../commands/DeleteBudgetCommand";
import { DeleteNotificationCommandInput, DeleteNotificationCommandOutput } from "../commands/DeleteNotificationCommand";
import { DeleteSubscriberCommandInput, DeleteSubscriberCommandOutput } from "../commands/DeleteSubscriberCommand";
import { DescribeBudgetCommandInput, DescribeBudgetCommandOutput } from "../commands/DescribeBudgetCommand";
import { DescribeBudgetPerformanceHistoryCommandInput, DescribeBudgetPerformanceHistoryCommandOutput } from "../commands/DescribeBudgetPerformanceHistoryCommand";
import { DescribeBudgetsCommandInput, DescribeBudgetsCommandOutput } from "../commands/DescribeBudgetsCommand";
import { DescribeNotificationsForBudgetCommandInput, DescribeNotificationsForBudgetCommandOutput } from "../commands/DescribeNotificationsForBudgetCommand";
import { DescribeSubscribersForNotificationCommandInput, DescribeSubscribersForNotificationCommandOutput } from "../commands/DescribeSubscribersForNotificationCommand";
import { UpdateBudgetCommandInput, UpdateBudgetCommandOutput } from "../commands/UpdateBudgetCommand";
import { UpdateNotificationCommandInput, UpdateNotificationCommandOutput } from "../commands/UpdateNotificationCommand";
import { UpdateSubscriberCommandInput, UpdateSubscriberCommandOutput } from "../commands/UpdateSubscriberCommand";
import { HttpRequest as __HttpRequest, HttpResponse as __HttpResponse } from "@aws-sdk/protocol-http";
import { SerdeContext as __SerdeContext } from "@aws-sdk/types";
export declare function serializeAws_json1_1CreateBudgetCommand(input: CreateBudgetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateNotificationCommand(input: CreateNotificationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1CreateSubscriberCommand(input: CreateSubscriberCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteBudgetCommand(input: DeleteBudgetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteNotificationCommand(input: DeleteNotificationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DeleteSubscriberCommand(input: DeleteSubscriberCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBudgetCommand(input: DescribeBudgetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBudgetPerformanceHistoryCommand(input: DescribeBudgetPerformanceHistoryCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeBudgetsCommand(input: DescribeBudgetsCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeNotificationsForBudgetCommand(input: DescribeNotificationsForBudgetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1DescribeSubscribersForNotificationCommand(input: DescribeSubscribersForNotificationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateBudgetCommand(input: UpdateBudgetCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateNotificationCommand(input: UpdateNotificationCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function serializeAws_json1_1UpdateSubscriberCommand(input: UpdateSubscriberCommandInput, context: __SerdeContext): Promise<__HttpRequest>;
export declare function deserializeAws_json1_1CreateBudgetCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateBudgetCommandOutput>;
export declare function deserializeAws_json1_1CreateNotificationCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateNotificationCommandOutput>;
export declare function deserializeAws_json1_1CreateSubscriberCommand(output: __HttpResponse, context: __SerdeContext): Promise<CreateSubscriberCommandOutput>;
export declare function deserializeAws_json1_1DeleteBudgetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteBudgetCommandOutput>;
export declare function deserializeAws_json1_1DeleteNotificationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteNotificationCommandOutput>;
export declare function deserializeAws_json1_1DeleteSubscriberCommand(output: __HttpResponse, context: __SerdeContext): Promise<DeleteSubscriberCommandOutput>;
export declare function deserializeAws_json1_1DescribeBudgetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBudgetCommandOutput>;
export declare function deserializeAws_json1_1DescribeBudgetPerformanceHistoryCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBudgetPerformanceHistoryCommandOutput>;
export declare function deserializeAws_json1_1DescribeBudgetsCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeBudgetsCommandOutput>;
export declare function deserializeAws_json1_1DescribeNotificationsForBudgetCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeNotificationsForBudgetCommandOutput>;
export declare function deserializeAws_json1_1DescribeSubscribersForNotificationCommand(output: __HttpResponse, context: __SerdeContext): Promise<DescribeSubscribersForNotificationCommandOutput>;
export declare function deserializeAws_json1_1UpdateBudgetCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateBudgetCommandOutput>;
export declare function deserializeAws_json1_1UpdateNotificationCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateNotificationCommandOutput>;
export declare function deserializeAws_json1_1UpdateSubscriberCommand(output: __HttpResponse, context: __SerdeContext): Promise<UpdateSubscriberCommandOutput>;
